{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.9.jar",
          "size": 559995,
          "sha512": "51a96723bee91acd5d5a04f1df2599bf2bb83705451044ac30eda24861cbef7552eed5b83e9842900e5e47e3e9f33297478f45c0070616266d0e2438e05d4190",
          "sha256": "a7a4f9bbd198bd20ba03fe80722641833ac0065f39fdc224e53ffb9281233b12",
          "sha1": "40be38dbc03f554f956fb747fb228d371600b62e",
          "md5": "c49ecbf9580737724402489b3ab8f025"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.9.jar",
          "size": 559995,
          "sha512": "51a96723bee91acd5d5a04f1df2599bf2bb83705451044ac30eda24861cbef7552eed5b83e9842900e5e47e3e9f33297478f45c0070616266d0e2438e05d4190",
          "sha256": "a7a4f9bbd198bd20ba03fe80722641833ac0065f39fdc224e53ffb9281233b12",
          "sha1": "40be38dbc03f554f956fb747fb228d371600b62e",
          "md5": "c49ecbf9580737724402489b3ab8f025"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.9-sources.jar",
          "size": 256782,
          "sha512": "6afc4da6a2707c64ac0c3b8c1490c227fbf73152f849f1a4cebfbfb5c24aafa761da8836f81f45d8ba4b983198faa8d67d21de0266babcfe06b463023a1b2a6f",
          "sha256": "e10c1695a4c13b09ae8c45edcce2a0fba0360456e420d2e9bdfee2ddc38e2e47",
          "sha1": "23904131042b2b9b7854f7f6094a3049884e59de",
          "md5": "cb127e43f057b0a15d48c1a3f891ff26"
        },
        {
          "name": "factory_api-neoforge-1.21.10-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.9-sources.jar",
          "size": 256782,
          "sha512": "6afc4da6a2707c64ac0c3b8c1490c227fbf73152f849f1a4cebfbfb5c24aafa761da8836f81f45d8ba4b983198faa8d67d21de0266babcfe06b463023a1b2a6f",
          "sha256": "e10c1695a4c13b09ae8c45edcce2a0fba0360456e420d2e9bdfee2ddc38e2e47",
          "sha1": "23904131042b2b9b7854f7f6094a3049884e59de",
          "md5": "cb127e43f057b0a15d48c1a3f891ff26"
        }
      ]
    }
  ]
}
