{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "size": 513686,
          "sha512": "717b7362360291f39c9048b71e58e264a241c88128e603ac2fbf180937ba990d9a5e58950774bc6ed8565b5dc0287e41199836a8d46d79fc13458d0ccd4e8034",
          "sha256": "b0ec00ab1dacf4c60259bc6edbd33fe47f3a06842737e27ac608cce96971a9de",
          "sha1": "a734dbcbbed13d6d781ad14b656e81e1d0b029bb",
          "md5": "31eee772424a1d1aa1e4e5a19aeb6195"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "size": 513686,
          "sha512": "717b7362360291f39c9048b71e58e264a241c88128e603ac2fbf180937ba990d9a5e58950774bc6ed8565b5dc0287e41199836a8d46d79fc13458d0ccd4e8034",
          "sha256": "b0ec00ab1dacf4c60259bc6edbd33fe47f3a06842737e27ac608cce96971a9de",
          "sha1": "a734dbcbbed13d6d781ad14b656e81e1d0b029bb",
          "md5": "31eee772424a1d1aa1e4e5a19aeb6195"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.5-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.5-sources.jar",
          "size": 250727,
          "sha512": "97a219daa7c4bd62cc97344885e70458dfcc1c730f2057d386bb4160f372b6a0a401a045b459921bd25d8fc33792ed760efcc1a67e9b7724cf1bd16e18177639",
          "sha256": "f7310e28267b4623422c2f4688657f3109412f1bbe0996efc7ebd9655ea3b127",
          "sha1": "38072e5a9ef496ec1aa5425c3e73a989ecc8e5c6",
          "md5": "3264db6bbb3ab32e557a71d662684137"
        }
      ]
    }
  ]
}
