{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "size": 513866,
          "sha512": "85eb824a085e60808a5e3cec9859d7ba95961da6298da5587490a11cec1d705bc30752c5256e46fd30faa7cee0b6169368435f3c35d42f78b29a7bbe23775c0e",
          "sha256": "6c9f520251a71ffa9bc127e3cc9f541f6879f21d063737e78f6e4449ba375ba2",
          "sha1": "9c9632ef9887e9c4963215c6b07055e433ec19f3",
          "md5": "2aaa447db6be05919b5e0e86efbbeb2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.5.jar",
          "size": 513866,
          "sha512": "85eb824a085e60808a5e3cec9859d7ba95961da6298da5587490a11cec1d705bc30752c5256e46fd30faa7cee0b6169368435f3c35d42f78b29a7bbe23775c0e",
          "sha256": "6c9f520251a71ffa9bc127e3cc9f541f6879f21d063737e78f6e4449ba375ba2",
          "sha1": "9c9632ef9887e9c4963215c6b07055e433ec19f3",
          "md5": "2aaa447db6be05919b5e0e86efbbeb2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.5-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.5-sources.jar",
          "size": 250812,
          "sha512": "5f15f77126d8bd517556a11656e6a2d925fc5a8fad08b6ddeb47f92df3f089207f56d0ba03a6280ebc7f2dca83b0a836e67261b516e873e76732050bad7ffe17",
          "sha256": "0321a609d7f2aff497e425a5c26c960852244d852818eac6c4de487af795323c",
          "sha1": "749360b38c815f348078da414413671fbacc53d9",
          "md5": "8ddb0c24064b815e7cd4297cdb83156d"
        }
      ]
    }
  ]
}
