{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.13.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.13.jar",
          "size": 445622,
          "sha512": "bec27947ce48f3be696c341a64c41e418f79caac74a6893a8bd29a436d70fdc041d3b617f2c97a9eab5380b25f125300d8b7ef6d8a0c81401546dc0595cf6cfd",
          "sha256": "8bc275a5a57d09b539b14c574138979639dd8c9d30d38aa3af271797bff9405e",
          "sha1": "45a2d844d4e024f9c39212030faaa580c7f4187c",
          "md5": "ede358e466263c96e3226a21ee5d916b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.13.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.13.jar",
          "size": 445622,
          "sha512": "bec27947ce48f3be696c341a64c41e418f79caac74a6893a8bd29a436d70fdc041d3b617f2c97a9eab5380b25f125300d8b7ef6d8a0c81401546dc0595cf6cfd",
          "sha256": "8bc275a5a57d09b539b14c574138979639dd8c9d30d38aa3af271797bff9405e",
          "sha1": "45a2d844d4e024f9c39212030faaa580c7f4187c",
          "md5": "ede358e466263c96e3226a21ee5d916b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.13-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.13-sources.jar",
          "size": 230495,
          "sha512": "99ad597d1b2bc22021d32e4ff68e48c6dd37f449e0e0447639308a2690c7f1012912305d49298ca01cecc54371dfb7f470ad7ace1c9682aeee3ab70e4fc086dc",
          "sha256": "e9e88112aab29cb8d65ac9ec82b47379354155a8a88b3c80dbd82f88c6dd40a0",
          "sha1": "47a3b15064f3490b42814da586f29f8ee6199d3b",
          "md5": "6b6aa5abaabcc1e4368d89e3dfd9f1eb"
        }
      ]
    }
  ]
}
