{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2516.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2516.3.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2516.3.jar",
          "size": 18276503,
          "sha512": "38e10610df9a3d555eef81aa19dfa72a3acd385c2f816bec0a8a1e334d1100ca67bcc799078bea44588607ae985eecf692675dc06b85e44dbf294cd417e363c3",
          "sha256": "b0b44caee59de1e81b109fa5233cd7c60fa3206eecc66cf529ab020676c8a639",
          "sha1": "b8bbe6557c96a7a3c75670864dee2c6ab9fefbc6",
          "md5": "1c16fc3607602e843f98e362edc9b83e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2516.3.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2516.3.jar",
          "size": 18276503,
          "sha512": "38e10610df9a3d555eef81aa19dfa72a3acd385c2f816bec0a8a1e334d1100ca67bcc799078bea44588607ae985eecf692675dc06b85e44dbf294cd417e363c3",
          "sha256": "b0b44caee59de1e81b109fa5233cd7c60fa3206eecc66cf529ab020676c8a639",
          "sha1": "b8bbe6557c96a7a3c75670864dee2c6ab9fefbc6",
          "md5": "1c16fc3607602e843f98e362edc9b83e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2516.3-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2516.3-sources.jar",
          "size": 17428461,
          "sha512": "14030a0135e178a1def188409d1f252e81106cfd8aefba90695aa0d90d3e7d664980b5b43d751b33cecd05bef5295813b0ae45855a115138f0343a6684740655",
          "sha256": "84c64b7bcd8440b02e7d67a60a9a4684a1f76d18409e798951759ac198dc0342",
          "sha1": "cc25d64dbfbfa09891e979e5ed86fea930cc43a0",
          "md5": "94028a8ec1161bd1056e694a399e7303"
        }
      ]
    }
  ]
}
