{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.2.jar",
          "size": 380298,
          "sha512": "eb7d189e68642a5e4ae112dc8be696cd0b05d48f6e43044e4266df3d43d43ec854e1763f4ebb267d6a3b762016e1910e59c8cd5dccdc03be295aa09379111227",
          "sha256": "77c529512212407bf3c2e0fd54dd38779f6e039a4ecabf070ebb719c0c42499d",
          "sha1": "8976522661904ac1634267a2b5cfec4b65a6db3a",
          "md5": "68584ed80758a81185e8377090987a75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.2.jar",
          "size": 380298,
          "sha512": "eb7d189e68642a5e4ae112dc8be696cd0b05d48f6e43044e4266df3d43d43ec854e1763f4ebb267d6a3b762016e1910e59c8cd5dccdc03be295aa09379111227",
          "sha256": "77c529512212407bf3c2e0fd54dd38779f6e039a4ecabf070ebb719c0c42499d",
          "sha1": "8976522661904ac1634267a2b5cfec4b65a6db3a",
          "md5": "68584ed80758a81185e8377090987a75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.2-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.2-sources.jar",
          "size": 199639,
          "sha512": "7012cf26b8ef7588b88409411b2a3c148d461e46733073861f53cbae3a3a7a1b84d78301d63927ae2b065a93754b62fcdb693e6b6073fce41b23b53e6852c52c",
          "sha256": "f5329544aa65c9ff7368cae4436df6e4a232ad82fa7b7692b0e40d88f6d254ae",
          "sha1": "505dd339e36f2adb8c8c6302eed7a31ec1ef807a",
          "md5": "d530ba01889c9722991035b6bdc1f8e9"
        }
      ]
    }
  ]
}
