{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2504.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.5.jar",
          "size": 446422,
          "sha512": "4a70d2060ade93386b40c4e71d8078473490edeadb1314e3bee121a63c8194056c72f4d1798e29fbffb42e17492efc572f0de78ecc62bfe97cdb8256c7785ff5",
          "sha256": "f1a4b7dbbf273fa42157e7930090f0a34f19b4a0564d9a7028b37b48d9db53cc",
          "sha1": "33c31a10c23700623bd4eb12adbd319d98cf695e",
          "md5": "ec3ebd66254b2f7806dae53eda81145f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.5.jar",
          "size": 446422,
          "sha512": "4a70d2060ade93386b40c4e71d8078473490edeadb1314e3bee121a63c8194056c72f4d1798e29fbffb42e17492efc572f0de78ecc62bfe97cdb8256c7785ff5",
          "sha256": "f1a4b7dbbf273fa42157e7930090f0a34f19b4a0564d9a7028b37b48d9db53cc",
          "sha1": "33c31a10c23700623bd4eb12adbd319d98cf695e",
          "md5": "ec3ebd66254b2f7806dae53eda81145f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.5-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.5-sources.jar",
          "size": 230230,
          "sha512": "9fd9a44c44dab98c9b49715c5de67bf1e9f94c3041db1848be85c6b01db9a117de7af32c1c9ac825d9f231952264ef489e789f25179b0aeacc975f7d5866265b",
          "sha256": "94fad67222438d4ffac11055ca1639a154d0cf954a8e1a0f1d4e9c116a1c77eb",
          "sha1": "215312e126c14503ba8f49617eb4fd89613fb7a9",
          "md5": "13f4c5569fbd7d1ea4d22c9bd498bcc5"
        }
      ]
    }
  ]
}
