{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.12.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.12.jar",
          "size": 495878,
          "sha512": "af923769d8fadbd7e1f134670c867a1ee251a2a82e43d622757f47405c6677c96a0dd2327022adee364bf428285ef1d137367d9e8ee0a1adcc6099fe0b8c1407",
          "sha256": "0a64a3259206988214b509bab08f9cb00064f183c79ea2ee5a73d74e735e6e83",
          "sha1": "669453b4c6ac55f9bfe5a1594a91a8dbc22f6267",
          "md5": "deb323e88deae41aed4b2f8346388c65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.12.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.12.jar",
          "size": 495878,
          "sha512": "af923769d8fadbd7e1f134670c867a1ee251a2a82e43d622757f47405c6677c96a0dd2327022adee364bf428285ef1d137367d9e8ee0a1adcc6099fe0b8c1407",
          "sha256": "0a64a3259206988214b509bab08f9cb00064f183c79ea2ee5a73d74e735e6e83",
          "sha1": "669453b4c6ac55f9bfe5a1594a91a8dbc22f6267",
          "md5": "deb323e88deae41aed4b2f8346388c65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.12-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.12-sources.jar",
          "size": 244773,
          "sha512": "ac9afeddc23eaf1d61b6d4ced2894210c4e4b38c5332ebebacf4334a5d2503c7b48b91526ba65d52b1ebf82d909c1097b570979eca36f1d9a52afe2ce20aff76",
          "sha256": "e6ff7a61b0807fea2221827e15cfe060fcb97c4080c023bbf5be0167eda495c6",
          "sha1": "2fd6dd7694da1e73c4021cf3f81953d84203c8d8",
          "md5": "81f026a5e9acb577d9867b6a5a6ab851"
        }
      ]
    }
  ]
}
