{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2508.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.1.jar",
          "size": 679120,
          "sha512": "11d9661da79087424520b3b442cd1909e10a2d48f3422d20dcc906626965b48efc68b88bcd76bd820daddbca662a7a4dbe4eadcca5cb565eb67f166392044d01",
          "sha256": "a0e57bbcda2063137ae2e5c081ce57ef1c75b2653ff84d46518c26127c2b2b7d",
          "sha1": "3c35bdd06854fafe3ab91ce4cdaffb8c97c3b37b",
          "md5": "46ec48967e95743ccd108395c42ce0ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.1.jar",
          "size": 679120,
          "sha512": "11d9661da79087424520b3b442cd1909e10a2d48f3422d20dcc906626965b48efc68b88bcd76bd820daddbca662a7a4dbe4eadcca5cb565eb67f166392044d01",
          "sha256": "a0e57bbcda2063137ae2e5c081ce57ef1c75b2653ff84d46518c26127c2b2b7d",
          "sha1": "3c35bdd06854fafe3ab91ce4cdaffb8c97c3b37b",
          "md5": "46ec48967e95743ccd108395c42ce0ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.1-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.1-sources.jar",
          "size": 247906,
          "sha512": "2df3c0ec8581cf94860ae5ec178a3a12aa6918e8fad98215fb2ab3c69c88348ed159e6c3143d9f33e1efc797081def68667ea52635480b53fa579b59e778fb4d",
          "sha256": "5704954ef80ebda7089adb7610bffbbcd156f3521926c78e66624c39a99424ab",
          "sha1": "edbd8b03782c635c8f076d8a4124cbae2941d17e",
          "md5": "048ebcda89777e30184224e9557da633"
        }
      ]
    }
  ]
}
