{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.9.jar",
          "size": 537692,
          "sha512": "20de5e22784395ab3ffe0f8bce8e75fa5ecae15e4a171737eaf9255c61e6cb3872a70db8f3d825a0fb0c07edbabaa31980e73f59cc5558338c081eada5bd8c46",
          "sha256": "0164c3491a5e8ceabddb1afa49866061718b9c57097dd8d8d1c9acdae2ed59ce",
          "sha1": "d28db3883dbd8170b95efdc24df7e14924e808de",
          "md5": "883847feb0451183193999cc961cf82d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.9.jar",
          "size": 537692,
          "sha512": "20de5e22784395ab3ffe0f8bce8e75fa5ecae15e4a171737eaf9255c61e6cb3872a70db8f3d825a0fb0c07edbabaa31980e73f59cc5558338c081eada5bd8c46",
          "sha256": "0164c3491a5e8ceabddb1afa49866061718b9c57097dd8d8d1c9acdae2ed59ce",
          "sha1": "d28db3883dbd8170b95efdc24df7e14924e808de",
          "md5": "883847feb0451183193999cc961cf82d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.9-sources.jar",
          "size": 256859,
          "sha512": "5b161599a0c045019ccc115ac48e7b3b1b633723c51512bdac1e1e05f590af15aeb9e728c6e733b65479b2bcf3612e6e06ca9f68c006a14a139ee7dc543fa93f",
          "sha256": "4c7b4cd91670a482359fc313dd02af81244e4c794b9dc31d6267b37b8e4b5c2b",
          "sha1": "561ec9e92c9215f7bf4f2498e7693a98530c3d6b",
          "md5": "7de770c803847a422ca7fec50e92eca3"
        },
        {
          "name": "factory_api-neoforge-1.21.1-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.9-sources.jar",
          "size": 256859,
          "sha512": "5b161599a0c045019ccc115ac48e7b3b1b633723c51512bdac1e1e05f590af15aeb9e728c6e733b65479b2bcf3612e6e06ca9f68c006a14a139ee7dc543fa93f",
          "sha256": "4c7b4cd91670a482359fc313dd02af81244e4c794b9dc31d6267b37b8e4b5c2b",
          "sha1": "561ec9e92c9215f7bf4f2498e7693a98530c3d6b",
          "md5": "7de770c803847a422ca7fec50e92eca3"
        }
      ]
    }
  ]
}
