{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2513.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.7.jar",
          "size": 502127,
          "sha512": "bdf9f9df442a860ad21f9e8d50d5a1fe1be5f0484ed14f4ffe98fc1fb7be2000db4abdc9b3e01625deca62098a5a6a53fe8293c8fb35980a636a391d29849349",
          "sha256": "ca82ef2ad3eebc5c5bbbc2e367301adcbd7e6121ea714d186f8db35777d2dd76",
          "sha1": "bacb844b22bb5fb3bbe8227213eb88b39640dc7f",
          "md5": "66019c7600ea53bbc0a1dd4429f38f40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.7.jar",
          "size": 502127,
          "sha512": "bdf9f9df442a860ad21f9e8d50d5a1fe1be5f0484ed14f4ffe98fc1fb7be2000db4abdc9b3e01625deca62098a5a6a53fe8293c8fb35980a636a391d29849349",
          "sha256": "ca82ef2ad3eebc5c5bbbc2e367301adcbd7e6121ea714d186f8db35777d2dd76",
          "sha1": "bacb844b22bb5fb3bbe8227213eb88b39640dc7f",
          "md5": "66019c7600ea53bbc0a1dd4429f38f40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.7-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.7-sources.jar",
          "size": 251446,
          "sha512": "876dbddeb8751c8181e41ebc252a44c9039cac5335282ab7f432a61ac982093937e8a79ad141fef50046cf2ff8045123368b97f069168da76e94274a9c9b020a",
          "sha256": "ebee51572f799d207308819afb25cf36739a178e919efadd15f0cda8908d666c",
          "sha1": "8d113285c445e5c61da3a58dbe665649ed0e356b",
          "md5": "36088564aad33ba5df9390bf568aaef0"
        }
      ]
    }
  ]
}
