{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.18.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.18.jar",
          "size": 372414,
          "sha512": "c3058d44b6fab98499d24f23e7de58268e96be52bc390e0056e7ae016ccbfdb7a9c70a58029840a885cc212d8e3fd59baef7d5d492cac4abbca728f5ee618fd8",
          "sha256": "8536087c3895db43483a1815c3bf8294945e446b8355525f394c765757e17f52",
          "sha1": "0bd36618b2c3195db695642e1428595eac9c6dc8",
          "md5": "0f22195b07ff63534de0d0cf7149fcd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.18.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.18.jar",
          "size": 372414,
          "sha512": "c3058d44b6fab98499d24f23e7de58268e96be52bc390e0056e7ae016ccbfdb7a9c70a58029840a885cc212d8e3fd59baef7d5d492cac4abbca728f5ee618fd8",
          "sha256": "8536087c3895db43483a1815c3bf8294945e446b8355525f394c765757e17f52",
          "sha1": "0bd36618b2c3195db695642e1428595eac9c6dc8",
          "md5": "0f22195b07ff63534de0d0cf7149fcd3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.18-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.18-sources.jar",
          "size": 200198,
          "sha512": "f8aa2578e9f20ae8dba791b4c9c7a6dc21759da8fc4022c249a0f2c1297a7a7298fc126fe4d77a3d7a0e1bfdbff6a0d83d4da7dfbb6fd06e6cfd53726b1a8e5e",
          "sha256": "f6d23fb8d60b51292f3e9a249f1fbd648aebad31de52c4fada133a9f888bfe05",
          "sha1": "d9bd6199b23afa60f5be3323227a68ec1f65d0d8",
          "md5": "e18b0b5efae2739cdfabb4a20d1ad635"
        }
      ]
    }
  ]
}
