{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.0.jar",
          "size": 710484,
          "sha512": "354efd2055a26df141cf058149e29a343c3e953ed73dd94af4139861ed467c6808c2ec466eb0fb950777d4532a99974f72da0b5fa58a8c39903042946bc25110",
          "sha256": "cf004274e7aafeeaa376186b3ec82677ad7daf68d459fa1dd3d9a1d14d5eee95",
          "sha1": "46616263dff5c27dd46685bac1efe0497cd9bbf3",
          "md5": "34c54bfbbbaeb2f178c25f698d105629"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.0.jar",
          "size": 710484,
          "sha512": "354efd2055a26df141cf058149e29a343c3e953ed73dd94af4139861ed467c6808c2ec466eb0fb950777d4532a99974f72da0b5fa58a8c39903042946bc25110",
          "sha256": "cf004274e7aafeeaa376186b3ec82677ad7daf68d459fa1dd3d9a1d14d5eee95",
          "sha1": "46616263dff5c27dd46685bac1efe0497cd9bbf3",
          "md5": "34c54bfbbbaeb2f178c25f698d105629"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.0-sources.jar",
          "size": 253330,
          "sha512": "05696a7d88b67ac99d14bd8c3b63c990caa0d187b5c65895645be2295eb84f9be18a15f2718bc9a4dc1fe9d23906280ce1d3855bc74848440ed6d148a619543b",
          "sha256": "6f2e095c95e370a3a4e33431c4a469de8fdfa4bc17ae1a9c6453d6617a915e30",
          "sha1": "fe54fb9f5a77984b813840e9b56b9757a36e4fe5",
          "md5": "4897980b6ebc3223bc5a5990698df09e"
        }
      ]
    }
  ]
}
