{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.5-2.2.6.2546.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.6.2546.0.jar",
          "url": "factory_api-fabric-1.21.5-2.2.6.2546.0.jar",
          "size": 569520,
          "sha512": "c24d5fb7af7552647371ecacf3faef32982aca81e0bf7c76ff26043528857904c328362962b98848ddcbe4cb273acdbd0df1fd3a34d3f0251eb49e5267911901",
          "sha256": "1b22aad9b492d7cd6bef5df298163c5659abdbe575aecc61687ded99b52b7716",
          "sha1": "10fca68c4012a2086bc4bd9a2580435847128d90",
          "md5": "40c0fc034e22426feeea9971f51ce228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "14.0.0-rc.2"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.6.2546.0.jar",
          "url": "factory_api-fabric-1.21.5-2.2.6.2546.0.jar",
          "size": 569520,
          "sha512": "c24d5fb7af7552647371ecacf3faef32982aca81e0bf7c76ff26043528857904c328362962b98848ddcbe4cb273acdbd0df1fd3a34d3f0251eb49e5267911901",
          "sha256": "1b22aad9b492d7cd6bef5df298163c5659abdbe575aecc61687ded99b52b7716",
          "sha1": "10fca68c4012a2086bc4bd9a2580435847128d90",
          "md5": "40c0fc034e22426feeea9971f51ce228"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.6.2546.0-sources.jar",
          "url": "factory_api-fabric-1.21.5-2.2.6.2546.0-sources.jar",
          "size": 266963,
          "sha512": "af42839be33d88c5173138b087bccce193daa5cb7afeedc89354f38e2ed80e99352f8dd44b853093ba42abcc3f080b1782118647595d297fc9aacab7ebd9c4ef",
          "sha256": "47a9c4d9560d04576d1c2fbb686a1fb56c710ac4fcf3e6bcaf6e31fb05f4bc07",
          "sha1": "843771bc073adf677ae969ce8c58b2d2d6852a15",
          "md5": "68cbd7c88ee3a72dddb50b6ab8596c0b"
        }
      ]
    }
  ]
}
