{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.0.jar",
          "size": 521799,
          "sha512": "64df62abb4e2c48bcc053ec72c10ad81d5df438c7118337516112a48266f54f78bd2812aeca618a3421c8450c2153bae3ff001fd523034de03394c7cb6482436",
          "sha256": "c293395837fb1e1d514b9868091a2049666b9b692b7f55e84f0683f40c2daad0",
          "sha1": "1b83d805787d9a67619a6e6b5ef5ef0eeb2062b6",
          "md5": "88b5e3d718abcf07df360a6e36f055d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.0.jar",
          "size": 521799,
          "sha512": "64df62abb4e2c48bcc053ec72c10ad81d5df438c7118337516112a48266f54f78bd2812aeca618a3421c8450c2153bae3ff001fd523034de03394c7cb6482436",
          "sha256": "c293395837fb1e1d514b9868091a2049666b9b692b7f55e84f0683f40c2daad0",
          "sha1": "1b83d805787d9a67619a6e6b5ef5ef0eeb2062b6",
          "md5": "88b5e3d718abcf07df360a6e36f055d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.0-sources.jar",
          "size": 252370,
          "sha512": "c72eabc8bfc1b3f70fb44c35d597e3a717f5ac3252b0491a4b998a35b59a055e8fceae4e1c0540fcc17cf9349d96e80f90d1cd5d7b82956ee5c6a27f855c3403",
          "sha256": "5b4b629ee3e40c49a779bf10e933ed39159ab9707c5ea397b7dbf474e395e961",
          "sha1": "fb9c337b8563357e1db12ea0222fcfbb7c4fc529",
          "md5": "977afe78cacdc60c390cf0fa0a5346e2"
        }
      ]
    }
  ]
}
