{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.6.2545.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.6.2545.0.jar",
          "size": 565608,
          "sha512": "5185747965533666c3ca4d29a0385db84a74d289a1106f5447bb3310b0a6d18a762777cc1f7036050e43738f637ee3b1aaa352a1f47e4c2b35c0127fc6f41c83",
          "sha256": "dfdf5bc661eac8b6d9c2f72e51fbdeaf76d9509e49c1deb61914f6d003f98386",
          "sha1": "a3a02a6d5bf61d85087393084405f4aa5ff09424",
          "md5": "4f263f48d6150d3a245651f01a30fc31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.6.2545.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.6.2545.0.jar",
          "size": 565608,
          "sha512": "5185747965533666c3ca4d29a0385db84a74d289a1106f5447bb3310b0a6d18a762777cc1f7036050e43738f637ee3b1aaa352a1f47e4c2b35c0127fc6f41c83",
          "sha256": "dfdf5bc661eac8b6d9c2f72e51fbdeaf76d9509e49c1deb61914f6d003f98386",
          "sha1": "a3a02a6d5bf61d85087393084405f4aa5ff09424",
          "md5": "4f263f48d6150d3a245651f01a30fc31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.6.2545.0-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.6.2545.0-sources.jar",
          "size": 266522,
          "sha512": "d30bd9720e835dd762d51995fcbf06d8205527f71e3b735cd565b7278a2ff956354fe44bb4ea3d8ef6a7b2477c50b2bd24f347b1610bb9e99612a408adce884d",
          "sha256": "200ad6b6c110f5f6629744485430fe24c1b2796049b9b43cad24eeda97ac5940",
          "sha1": "338b3501cba19c7fce8ec575a23e9e4b4a5c5347",
          "md5": "37bc82c9d7e3294b9deb4f2e4ecefb8a"
        }
      ]
    }
  ]
}
