{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2502.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.8.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.8.jar",
          "size": 443929,
          "sha512": "48c9ce6325582803033e7d4ff593f3b96f696605aeea757c032827b1db817ad2bc89741202b5ff551ddadc08e3f2c95b9f30eec9c2fee4700b776ae278299965",
          "sha256": "42607722973e04f4e1317ad3edec870184fa30ea1f39767dd90c19d101b7b2b4",
          "sha1": "eb72af6aaf52d51157deb1ee0f53c4752deaefab",
          "md5": "c61ac6e7504a13d4b4e7ca25c3d4f2bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.8.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.8.jar",
          "size": 443929,
          "sha512": "48c9ce6325582803033e7d4ff593f3b96f696605aeea757c032827b1db817ad2bc89741202b5ff551ddadc08e3f2c95b9f30eec9c2fee4700b776ae278299965",
          "sha256": "42607722973e04f4e1317ad3edec870184fa30ea1f39767dd90c19d101b7b2b4",
          "sha1": "eb72af6aaf52d51157deb1ee0f53c4752deaefab",
          "md5": "c61ac6e7504a13d4b4e7ca25c3d4f2bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.8-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.8-sources.jar",
          "size": 222302,
          "sha512": "7b5cbe5739e5a64da0e984e49103e5bf14ffef7737914aa40eb4bec41efc173f94134451eaacce4bf9bf84b483e60097f400da848b480ffbda7cecf45cd520be",
          "sha256": "c27659094544786e9c98f387c40ed11de25da99ddc6e568400052a2d12796d2c",
          "sha1": "366dac0ec4d48e4adb1f9a6abbac86120ac00556",
          "md5": "707cc20cf7a67b10ce11bfeccac7d112"
        }
      ]
    }
  ]
}
