{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2501.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.11.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.11.jar",
          "size": 358695,
          "sha512": "c49da5eabb113abb8f7de4f478f0c85e8cade36853c600d0d1d692d944353b71c7b07e2ff28bbec24ee01db71b502446438c5a4cbb6e421e8302a7a5514846da",
          "sha256": "edd0c5f8b32f8de2c0cde72a40ba0e63c08143f20d05b8a4a5f5021715d5ee6d",
          "sha1": "3126e72d919b6d7638c4a47e805e37e52da4a7de",
          "md5": "d1739866d0f829d6a0e9b71a08cad8f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.11.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.11.jar",
          "size": 358695,
          "sha512": "c49da5eabb113abb8f7de4f478f0c85e8cade36853c600d0d1d692d944353b71c7b07e2ff28bbec24ee01db71b502446438c5a4cbb6e421e8302a7a5514846da",
          "sha256": "edd0c5f8b32f8de2c0cde72a40ba0e63c08143f20d05b8a4a5f5021715d5ee6d",
          "sha1": "3126e72d919b6d7638c4a47e805e37e52da4a7de",
          "md5": "d1739866d0f829d6a0e9b71a08cad8f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.11-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.11-sources.jar",
          "size": 198289,
          "sha512": "30b0e04388890ebe285a495167366dc1ded3258b1f222102745eb7447a6e98e1d43a245fd8c2a3d69e476223480e761af353cc3f4846a008c1e9910732385d64",
          "sha256": "824e26ef967f6aa28b817ac7e02111f5ad1c0e4990ca737fbd15e50e17c2039a",
          "sha1": "038e0f79006c239a59ab45460644fb42ccc47428",
          "md5": "84822081bfafaeaca59d1dadee093c02"
        }
      ]
    }
  ]
}
