{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2516.1.jar",
          "size": 523073,
          "sha512": "7aad417495a52ea4fc3df6086214d8d8149c78415ba942d7d50c946bc5c9c1f0013d67d2194c835bf24ed3b8047c0b228cba187b509f487de393d409cacb275e",
          "sha256": "135e2a4fb1638850092dd021344116b3206a4c61ab9caada56321992d65bbe7f",
          "sha1": "ba105c4141c85bf32accdd300a3730fb6eb1f933",
          "md5": "fdcb0d4e6ada314ede42ff9337e20054"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2516.1.jar",
          "size": 523073,
          "sha512": "7aad417495a52ea4fc3df6086214d8d8149c78415ba942d7d50c946bc5c9c1f0013d67d2194c835bf24ed3b8047c0b228cba187b509f487de393d409cacb275e",
          "sha256": "135e2a4fb1638850092dd021344116b3206a4c61ab9caada56321992d65bbe7f",
          "sha1": "ba105c4141c85bf32accdd300a3730fb6eb1f933",
          "md5": "fdcb0d4e6ada314ede42ff9337e20054"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2516.1-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2516.1-sources.jar",
          "size": 253424,
          "sha512": "5f93ca0aec9847f11dc2da326583176fa6eaa35fd955c1f472d144b2a2a580b32809f0484b52324bd1ef40e2d0bd4f269a72dbcb10a3b26806a3e1a6398485f3",
          "sha256": "2bf728ec5f90bbea61a0a4c47c75d9dca8d4030f4837f3cbf398e2e70d08f0fd",
          "sha1": "309c3e4afd057d9d92cfda22066f7e2f88431928",
          "md5": "8c0bccba19a9416e32860cb81134b48d"
        }
      ]
    }
  ]
}
