{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2513.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.2.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.2.jar",
          "size": 495875,
          "sha512": "1ddae598eed7be7fabb3a65413ac26ccd791526ccb7a8de4b2243f12b923845216efd035b545cf288c999cdf54e1ffaab3b0ddabf905311174ab9b69be114492",
          "sha256": "f349957311f1ec93f649134565a319425ddcf1ee51e41dd7b881741aad21d1f6",
          "sha1": "0b1456a9eb1fc9372d39c4b6f2e6762505c2c14b",
          "md5": "72bb0a4802fad5f63caf34c1e8bbadc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.2.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.2.jar",
          "size": 495875,
          "sha512": "1ddae598eed7be7fabb3a65413ac26ccd791526ccb7a8de4b2243f12b923845216efd035b545cf288c999cdf54e1ffaab3b0ddabf905311174ab9b69be114492",
          "sha256": "f349957311f1ec93f649134565a319425ddcf1ee51e41dd7b881741aad21d1f6",
          "sha1": "0b1456a9eb1fc9372d39c4b6f2e6762505c2c14b",
          "md5": "72bb0a4802fad5f63caf34c1e8bbadc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.2-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.2-sources.jar",
          "size": 250781,
          "sha512": "6877c8299f4af7114a74660aa6139deccb1aeeb3c1e0ed2be7fa73ee94f32e7848176cd4393816654b97ae387294ddfd36d265526efab296f4603d6cac757217",
          "sha256": "528ffee480a0348695eeece978c692842e5d321fe52522b6b4348e814a11999d",
          "sha1": "f332a662b01c82780114789707b32623f47efc0b",
          "md5": "bf22094bb36c6c5d1f536f61ba8d984a"
        }
      ]
    }
  ]
}
