{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.5-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.3.jar",
          "size": 645391,
          "sha512": "31f4a84b03d12c64eaec02f7a70306c1d629f17e4548e5c39054f10ed6bbcbd586039a58becf997ef449e34909301f8f6e5e107e0070171d1607c4e9d61edefb",
          "sha256": "8b0acde87187b64ed344fdd9169204a3dbef1586da6bd5ae12849a5b3dcdb0cc",
          "sha1": "be020787b917e5000598e9300bb39e7a4dffdede",
          "md5": "744d435289c20bd1f3d16f4a09fd8d1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.3.jar",
          "size": 645391,
          "sha512": "31f4a84b03d12c64eaec02f7a70306c1d629f17e4548e5c39054f10ed6bbcbd586039a58becf997ef449e34909301f8f6e5e107e0070171d1607c4e9d61edefb",
          "sha256": "8b0acde87187b64ed344fdd9169204a3dbef1586da6bd5ae12849a5b3dcdb0cc",
          "sha1": "be020787b917e5000598e9300bb39e7a4dffdede",
          "md5": "744d435289c20bd1f3d16f4a09fd8d1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.3-sources.jar",
          "size": 586110,
          "sha512": "f169eee77f8941ccf370cf8d69a1ddc472da8609c697ebe4932aa6a267ea1ea4b9d8b3ed652b0ccf7b15c162728b012ac602a0615e203dc46074302b2cf6eda5",
          "sha256": "08dd41f9fcfb09e7977c11b486d10cd89a742250d29a4d189fc5ccf1176e4840",
          "sha1": "7ce26e9e6ec719662b9ae3cc18e9c7534a5e2977",
          "md5": "200961e721df02f9e371e0bdd7075ce8"
        }
      ]
    }
  ]
}
