{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2506.0.jar",
          "size": 479372,
          "sha512": "41f89c4b40c1f2feb154e03ef36d6b673fb287bf9e34e4eb5f8b743ac750a8b3c28f721eef1f5de34c9ce662a8a1cd451e299d4b251f0f753f5e8ba2119266c0",
          "sha256": "c782d0997f01ab0d72a0f921c338682bad51c7e711704a9070a6d2ce5ae059d0",
          "sha1": "94bc9dd90fb237c7a54d7543b8f407dc03f06bf2",
          "md5": "f9076fa16e8e1774fbac0a8b0accd9ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2506.0.jar",
          "size": 479372,
          "sha512": "41f89c4b40c1f2feb154e03ef36d6b673fb287bf9e34e4eb5f8b743ac750a8b3c28f721eef1f5de34c9ce662a8a1cd451e299d4b251f0f753f5e8ba2119266c0",
          "sha256": "c782d0997f01ab0d72a0f921c338682bad51c7e711704a9070a6d2ce5ae059d0",
          "sha1": "94bc9dd90fb237c7a54d7543b8f407dc03f06bf2",
          "md5": "f9076fa16e8e1774fbac0a8b0accd9ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2506.0-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2506.0-sources.jar",
          "size": 237256,
          "sha512": "6012850ca376f8621387d060f533c7237bae98627c29f5a66633aa40866ff5c0d3bb0f310ef035e0e7283678544c4694555def3680c24b68ad17b2b382a32bb7",
          "sha256": "325846fe384f0cdfb96966ae909a9609d67c8dfb00e7602686d4b7ce18c9c286",
          "sha1": "4aaaaedd9e1d00eef890f98dfb5ca356680161cb",
          "md5": "a6cefa32a2772c951f5fb8a01248f9a2"
        }
      ]
    }
  ]
}
