{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2501.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.4.jar",
          "size": 368347,
          "sha512": "29ed5f3e4d14bdd2b2f4e006f0d35c8c0c0e4a846610067124a8b641b2c8bc8a7dbbfe835f5da3aab5affdaedfb013f1373cb924f28f340f807a87ea2adf6e75",
          "sha256": "ef1098b5d9c4571a32e238395969751d1c3fe59da9d4ae6ed0a0435164e322b3",
          "sha1": "65ac1d1e467cd95dcebee00f750af4ea7809b4b9",
          "md5": "070a81adfbfb86b3c6fa78b450fe276d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.4.jar",
          "size": 368347,
          "sha512": "29ed5f3e4d14bdd2b2f4e006f0d35c8c0c0e4a846610067124a8b641b2c8bc8a7dbbfe835f5da3aab5affdaedfb013f1373cb924f28f340f807a87ea2adf6e75",
          "sha256": "ef1098b5d9c4571a32e238395969751d1c3fe59da9d4ae6ed0a0435164e322b3",
          "sha1": "65ac1d1e467cd95dcebee00f750af4ea7809b4b9",
          "md5": "070a81adfbfb86b3c6fa78b450fe276d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.4-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.4-sources.jar",
          "size": 195234,
          "sha512": "ec48f095b232f272059b5a99e20a754dd588d3dbc55b0dad904b62a828e63f13ee313fa159d4a6ac1a86b3e01f4d29963cfdbba438e07e6e0d6f685225f293b8",
          "sha256": "4cbc2425b07cc737a684cf7b778ea8e4226c7bc2625789e16c471eccbaca60f2",
          "sha1": "15d3d7f42b851d58b33fcc570999e4db78f542c6",
          "md5": "7344317fb09e7803f159084dd9b54daa"
        }
      ]
    }
  ]
}
