{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.7.2616.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.7.2616.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.7.2616.2.jar",
          "size": 1151207,
          "sha512": "e1a34ca4208726e3fdadd6e47c8a45a72645251611f5208afbbfc1abff5d78e146508b8f2eb42889b9f8e3e32369af69b0fb5090cec7270f07b1d8ce5bcef5b6",
          "sha256": "b532177071f0c38ec4b6b681eb0c481c6fc26fc5cdfb189d943e64a1bc5a97f3",
          "sha1": "17caecd0f801ddcb26284a6ab9bb97ae616b4c87",
          "md5": "9063e6da9efed9751eafa77314471626"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.4-49.0.48"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.7.2616.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.7.2616.2.jar",
          "size": 1151207,
          "sha512": "e1a34ca4208726e3fdadd6e47c8a45a72645251611f5208afbbfc1abff5d78e146508b8f2eb42889b9f8e3e32369af69b0fb5090cec7270f07b1d8ce5bcef5b6",
          "sha256": "b532177071f0c38ec4b6b681eb0c481c6fc26fc5cdfb189d943e64a1bc5a97f3",
          "sha1": "17caecd0f801ddcb26284a6ab9bb97ae616b4c87",
          "md5": "9063e6da9efed9751eafa77314471626"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.7.2616.2-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.7.2616.2-sources.jar",
          "size": 256873,
          "sha512": "117d747fd172aa9ddd2c4baa4fd07baff300ae878cd7aa68e17455ffb7a5574e0442ac1091df8ceafbb71190f15f6f68349ebc55c167177cc3cf991544934ad8",
          "sha256": "d03b4bb95718fe58d0fc69cb69f9c2b083212ab2c877a7c62e22c15e6100fa30",
          "sha1": "b5a0063eae46c681c1cd499380f840ea2647cd43",
          "md5": "7fe07d2bd708482acb9baa93e0aff1c7"
        },
        {
          "name": "factory_api-forge-1.20.4-2.2.7.2616.2-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.7.2616.2-sources.jar",
          "size": 256873,
          "sha512": "117d747fd172aa9ddd2c4baa4fd07baff300ae878cd7aa68e17455ffb7a5574e0442ac1091df8ceafbb71190f15f6f68349ebc55c167177cc3cf991544934ad8",
          "sha256": "d03b4bb95718fe58d0fc69cb69f9c2b083212ab2c877a7c62e22c15e6100fa30",
          "sha1": "b5a0063eae46c681c1cd499380f840ea2647cd43",
          "md5": "7fe07d2bd708482acb9baa93e0aff1c7"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.4-49.0.48"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.7.2616.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.7.2616.2.jar",
          "size": 1151207,
          "sha512": "e1a34ca4208726e3fdadd6e47c8a45a72645251611f5208afbbfc1abff5d78e146508b8f2eb42889b9f8e3e32369af69b0fb5090cec7270f07b1d8ce5bcef5b6",
          "sha256": "b532177071f0c38ec4b6b681eb0c481c6fc26fc5cdfb189d943e64a1bc5a97f3",
          "sha1": "17caecd0f801ddcb26284a6ab9bb97ae616b4c87",
          "md5": "9063e6da9efed9751eafa77314471626"
        }
      ]
    }
  ]
}
