{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.20.4-1.7.10.2504.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2504.5.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2504.5.jar",
          "size": 14280779,
          "sha512": "3ce3cd23577d217099fa7c0a32f76590b02065cf6396275dae69689103a0065223c190778492b4ed14112f2fef69120edb8b6497f800612bec5bdf8be162018d",
          "sha256": "d22018d62fe2bd783b901f41da399d8353bcc0036bd4b0a0b97ae479009005ea",
          "sha1": "a4640acee32927bc9463671f6ac4943d1167190e",
          "md5": "c8154a153b326585989cd66363ec4918"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2504.5.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2504.5.jar",
          "size": 14280779,
          "sha512": "3ce3cd23577d217099fa7c0a32f76590b02065cf6396275dae69689103a0065223c190778492b4ed14112f2fef69120edb8b6497f800612bec5bdf8be162018d",
          "sha256": "d22018d62fe2bd783b901f41da399d8353bcc0036bd4b0a0b97ae479009005ea",
          "sha1": "a4640acee32927bc9463671f6ac4943d1167190e",
          "md5": "c8154a153b326585989cd66363ec4918"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2504.5-sources.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2504.5-sources.jar",
          "size": 13466251,
          "sha512": "0731d3d88f83592f8afaff663d0edab66a0f130353039bec252fb36bd9b0113b33107f028d48a35b755c15ca41c9231ce760f482e9cc4c71417700295f0604cd",
          "sha256": "999e69ca541a1f074d629a1569e3ab48764ccc2050e4ce80fcc2e4e903c6f7ab",
          "sha1": "bd47d3d8c7ff6c30fd5591305f0b71d5ea7d862f",
          "md5": "f0f9026b3f2c64fd5fc49b266ec146ff"
        }
      ]
    }
  ]
}
