{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2518.5.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2518.5.jar",
          "size": 19733361,
          "sha512": "004b688c29e072798c1913c2d40bfd36e06d11b74ca62038f3034ae5ce2377eda0f342af27006be54e26b3e1d5670781049a1236322400f1afb9e5b0d72c660c",
          "sha256": "60e935c1b97e245439fe2d6eb14077e4c60aa1961a0b5858428c6ff6f98eb24e",
          "sha1": "50480e634094f5c55c4dbd68687f8b69b862a6bb",
          "md5": "11c4ec5d1a38c9c1b229c28831878d7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2518.5.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2518.5.jar",
          "size": 19733361,
          "sha512": "004b688c29e072798c1913c2d40bfd36e06d11b74ca62038f3034ae5ce2377eda0f342af27006be54e26b3e1d5670781049a1236322400f1afb9e5b0d72c660c",
          "sha256": "60e935c1b97e245439fe2d6eb14077e4c60aa1961a0b5858428c6ff6f98eb24e",
          "sha1": "50480e634094f5c55c4dbd68687f8b69b862a6bb",
          "md5": "11c4ec5d1a38c9c1b229c28831878d7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2518.5-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2518.5-sources.jar",
          "size": 18854113,
          "sha512": "d0d4c21799ee3394d57c6912592892bc090b8504fb1da0b61727507a77978efb8b6b19bd4db1d012e3a14446223dd9951308d28a46104a563b81a34e76024138",
          "sha256": "a5cb1827940bf8355f338697d0967a28293dfce96b568f4f7292dcbd6dc3782e",
          "sha1": "a0f85b476e67c42c740742804205ea737a0c6b84",
          "md5": "9ba3fcab7e03a984ebd5f386ccc81985"
        }
      ]
    }
  ]
}
