{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.jar",
          "size": 537585,
          "sha512": "2bb7c270e5db2200ee079e54a3f04ec0a797dd3b461c6d4a140bc4ef2542eee9d958cb42521f7002a34e0a827a814b56585c1af70a0e57771322b947049afc40",
          "sha256": "5933f881c07d278f7a6c0dc90b207151b93f2432884a05116d2fcc01a9738471",
          "sha1": "249ef95e4d81a1e16ac63119551045998a9d54e9",
          "md5": "d69426acc519709f71607c21d2e1af95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.jar",
          "size": 537585,
          "sha512": "2bb7c270e5db2200ee079e54a3f04ec0a797dd3b461c6d4a140bc4ef2542eee9d958cb42521f7002a34e0a827a814b56585c1af70a0e57771322b947049afc40",
          "sha256": "5933f881c07d278f7a6c0dc90b207151b93f2432884a05116d2fcc01a9738471",
          "sha1": "249ef95e4d81a1e16ac63119551045998a9d54e9",
          "md5": "d69426acc519709f71607c21d2e1af95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6-sources.jar",
          "size": 259001,
          "sha512": "b23473910e0dd88067e6770d236236adf025dfac913708734e3be96a6e974e063a7c92f8eb35172584ffd427bf6333ed26426f4b4ca73441e1594d14bc0889a7",
          "sha256": "45ec70749cedd0cce26ebf65e79fd0ca32dd2fefc46bd8dc39efbd543bdd3e66",
          "sha1": "b7eac517ed62ff52440260b9332fa28e10007848",
          "md5": "8439a98b8ec4866508ac7decda1a3eb3"
        }
      ]
    }
  ]
}
