{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.2500.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2500.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2500.0.jar",
          "size": 374305,
          "sha512": "054861da06c76518c28011034920746683a301767e00d0801f2237a1fd4caaf7622d9da94c6092dfbbf824398dcccf8dbf9a73dd2d6f6a967800c6ef1627945c",
          "sha256": "149e77764d14109089968eab093156dcd678d459421c1ac94156bcd0177b2d34",
          "sha1": "0620c956eeb967dd53357bf458626f08b3621f4c",
          "md5": "51a031dbfb083b7e6e82616398efbd2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2500.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2500.0.jar",
          "size": 374305,
          "sha512": "054861da06c76518c28011034920746683a301767e00d0801f2237a1fd4caaf7622d9da94c6092dfbbf824398dcccf8dbf9a73dd2d6f6a967800c6ef1627945c",
          "sha256": "149e77764d14109089968eab093156dcd678d459421c1ac94156bcd0177b2d34",
          "sha1": "0620c956eeb967dd53357bf458626f08b3621f4c",
          "md5": "51a031dbfb083b7e6e82616398efbd2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2500.0-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2500.0-sources.jar",
          "size": 189562,
          "sha512": "282bb3741fafa0f0a0611dfcdcc191c2419dd5ef20fa2f45cea98439316ab4391ea77be78ff8cd8ccb33a7262e819dd30c008456b3a55df610c58d12b063f171",
          "sha256": "cecaa4a15323c98cac30ecbfa36969ad81bc8c7e02fd15c72910fdc74e11ff4d",
          "sha1": "c40808cb038bb6fe53ab6b18e263d5516c4a3693",
          "md5": "b02e5f5b42bf322d45f951f37ca8cf3e"
        }
      ]
    }
  ]
}
