{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2500.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.3.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.3.jar",
          "size": 368998,
          "sha512": "5500bab0a48572fba8ab92b17c08987b781aa695f7064006c667af339b48fe69f3796fb132188646ba135d05f5836d9daa4ee11d5444c45eb85b74e4974cfc22",
          "sha256": "69d33b18707da87f7a139a3605a78ae5d2135c2e7e295a5d7f134863ffd67e73",
          "sha1": "08e15404dd20a471588476975d24804261511a18",
          "md5": "3c889930a47c08ea40d0d891c09b0762"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.3.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.3.jar",
          "size": 368998,
          "sha512": "5500bab0a48572fba8ab92b17c08987b781aa695f7064006c667af339b48fe69f3796fb132188646ba135d05f5836d9daa4ee11d5444c45eb85b74e4974cfc22",
          "sha256": "69d33b18707da87f7a139a3605a78ae5d2135c2e7e295a5d7f134863ffd67e73",
          "sha1": "08e15404dd20a471588476975d24804261511a18",
          "md5": "3c889930a47c08ea40d0d891c09b0762"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.3-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.3-sources.jar",
          "size": 193675,
          "sha512": "64069e8475be49a80e59fded2224803d186e8b859c1214d4d10ed654f8df43399abd96df2ed1f73026a9593e9489debc42540ea7845331e4e314d7699e2363e9",
          "sha256": "5eab0cefb627ee5cef2b891ec063e3bea4f4f778401fea98ddfd293687d1c5e8",
          "sha1": "7911dec3367434cb2d5280165b5bf65b1003dd74",
          "md5": "6b65511858747d98ab05407a085e4f30"
        }
      ]
    }
  ]
}
