{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.1-2.2.2507.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2507.9.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2507.9.jar",
          "size": 534894,
          "sha512": "4419a51a2161617f89bbef04383916739800cb8db21615cb91cc14daa52645d1d30260e359561e1ac05f877b5ac34b67bda918b8cbd0d9f1a853855df48bb76e",
          "sha256": "6df60e76b4e9d050b3f11a9f34d8d1d8e89d5bf11d354cdfe49de70fcf1a292b",
          "sha1": "3eb98d6317826198777e0710f07d9ed6082d3333",
          "md5": "0a29f06b1c102f352b761f8509d4004b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2507.9.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2507.9.jar",
          "size": 534894,
          "sha512": "4419a51a2161617f89bbef04383916739800cb8db21615cb91cc14daa52645d1d30260e359561e1ac05f877b5ac34b67bda918b8cbd0d9f1a853855df48bb76e",
          "sha256": "6df60e76b4e9d050b3f11a9f34d8d1d8e89d5bf11d354cdfe49de70fcf1a292b",
          "sha1": "3eb98d6317826198777e0710f07d9ed6082d3333",
          "md5": "0a29f06b1c102f352b761f8509d4004b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2507.9-sources.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2507.9-sources.jar",
          "size": 242955,
          "sha512": "205761a2095abcb46a92dc43e4b120412fdeb2e94c63c0d8d7c007449cf79a7e0873944d4ecc1bec18986dd6fc4c82aac8466d802cfa40fa8fe87729b44cdc58",
          "sha256": "ba4a54da3fc7025627e62dff6ddb218da9c9d0e577d3fbf0d10afab691f2de4d",
          "sha1": "70b9b72201a08be87de06934e6572b992bbfc9c9",
          "md5": "447a8f2d14d234bc82b4c9d0ae03fe84"
        }
      ]
    }
  ]
}
