{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.6.2545.0.jar",
          "size": 722993,
          "sha512": "23d6731d620a12fdbf2250fb5c6c181593696b8db554e1a4af2c121ce97289b70c64a1e4a755e07fb8136e16e5f4f3a7151b1155edfdaf38067b1f12a888b268",
          "sha256": "6bc3c593767a486b9f24e371aae2a52169c4ba6b6220d66be0115f649d7689d6",
          "sha1": "3a51848a1bcc03d9ef95657d19941f106258c3ee",
          "md5": "211ac2d9206e2ccbf700b10dd94d3ad5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.6.2545.0.jar",
          "size": 722993,
          "sha512": "23d6731d620a12fdbf2250fb5c6c181593696b8db554e1a4af2c121ce97289b70c64a1e4a755e07fb8136e16e5f4f3a7151b1155edfdaf38067b1f12a888b268",
          "sha256": "6bc3c593767a486b9f24e371aae2a52169c4ba6b6220d66be0115f649d7689d6",
          "sha1": "3a51848a1bcc03d9ef95657d19941f106258c3ee",
          "md5": "211ac2d9206e2ccbf700b10dd94d3ad5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.6.2545.0-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.6.2545.0-sources.jar",
          "size": 268442,
          "sha512": "097b6c1f98f425861f1f001469257ab3245fa62c3a35e3a01d231b67696d835cccffc715acb098c3113a6a3fd3094be30a8d3b964e483aa6e846ab441f06f823",
          "sha256": "8925a72c1176b9570ba5738c07107ca8503d3d6662a3668e7da24456dcf2412d",
          "sha1": "806bc64c3e1b25d9e3865c22ecb54323b3ce926f",
          "md5": "42a5e9ddc6f63e950b74c474129ee25b"
        }
      ]
    }
  ]
}
