{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2502.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2502.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2502.1.jar",
          "size": 394819,
          "sha512": "1da838ad6ff04f88a6967d107fcd7f4dbad8d70821f82e49f554e38d49376c040652d85926526daa3641d5a6c574225e29498d95034c4878a2ef86c42baca28e",
          "sha256": "e7e8ed91964e68ace5d93107097f93d229552da91317b3f9b5da30542e5b5c00",
          "sha1": "ea17dbf22f511ac4bb834571fa15d12566119185",
          "md5": "e3c7f482cadee4225e75c7492c34cece"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2502.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2502.1.jar",
          "size": 394819,
          "sha512": "1da838ad6ff04f88a6967d107fcd7f4dbad8d70821f82e49f554e38d49376c040652d85926526daa3641d5a6c574225e29498d95034c4878a2ef86c42baca28e",
          "sha256": "e7e8ed91964e68ace5d93107097f93d229552da91317b3f9b5da30542e5b5c00",
          "sha1": "ea17dbf22f511ac4bb834571fa15d12566119185",
          "md5": "e3c7f482cadee4225e75c7492c34cece"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2502.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2502.1-sources.jar",
          "size": 197945,
          "sha512": "cf14e358090ddb1a234cd9517fa203d6f40cef5745e10ef2380ad44397e4865f966896ad9a7d18fc57ad8d834917633e78376e6fe45329354d66bb253ad007d9",
          "sha256": "6afb3504de9aa350f7c6d433e240de81b41cda30ef27487fa42d8e0ddd3f1e5a",
          "sha1": "ac966f325c82e7b078b05c528456676c55e6001c",
          "md5": "b5c62c7de3761141d69f6907ef225870"
        }
      ]
    }
  ]
}
