{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.7.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.7.jar",
          "size": 443815,
          "sha512": "de6cd882bd715afc73fed1e261ded9370de17deb48bdebb0ae68a1abbbadae2748df40d8b2328830b678db2d422631ade888f556a0071ed3e1316c2df48a5c3c",
          "sha256": "7668b3175afb171cbc196cb930e40abb1e311c67495d8c740c96fe9f5fb7292d",
          "sha1": "8e46b3dbbd14bfa86dfad792ee3ce45048b45f5d",
          "md5": "00d42bed8699b96f9545ae24cd57bb74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.7.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.7.jar",
          "size": 443815,
          "sha512": "de6cd882bd715afc73fed1e261ded9370de17deb48bdebb0ae68a1abbbadae2748df40d8b2328830b678db2d422631ade888f556a0071ed3e1316c2df48a5c3c",
          "sha256": "7668b3175afb171cbc196cb930e40abb1e311c67495d8c740c96fe9f5fb7292d",
          "sha1": "8e46b3dbbd14bfa86dfad792ee3ce45048b45f5d",
          "md5": "00d42bed8699b96f9545ae24cd57bb74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.7-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.7-sources.jar",
          "size": 222421,
          "sha512": "447cc2b163577aef79fc13aaa987e1e3ce002c5a02ee2371acf13b2c74500910279ed5516328593df6a9ebdf8ec4b8c68b039aa742feb6ecc29941dd4839d9b2",
          "sha256": "c14745814108b61c4d00d2a2a15df3f22d715a088f4901f29ce72eaa7e86bbaa",
          "sha1": "0049f5e530205afbeec4590025e6eafc92beb45f",
          "md5": "7339f6dea12651feb43f9f370d0e55bf"
        }
      ]
    }
  ]
}
