{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.22.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.22.jar",
          "size": 382351,
          "sha512": "611657c42f1e796ffe0d958688af132eb80f6232ac21197a14644f645fd452af4bce9cd0b2f695baeed1c026fee294c6457480ff686d7757085cd56caffbb51b",
          "sha256": "bfe0e699b0d53ac328ee2bd44c9924fbd6ef07639bcd58452157d1a540b1cd26",
          "sha1": "9df6390932ecb57656b0ffb1530c346af168316f",
          "md5": "a0ae66967e033a1b16c408ff92aeab19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.22.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.22.jar",
          "size": 382351,
          "sha512": "611657c42f1e796ffe0d958688af132eb80f6232ac21197a14644f645fd452af4bce9cd0b2f695baeed1c026fee294c6457480ff686d7757085cd56caffbb51b",
          "sha256": "bfe0e699b0d53ac328ee2bd44c9924fbd6ef07639bcd58452157d1a540b1cd26",
          "sha1": "9df6390932ecb57656b0ffb1530c346af168316f",
          "md5": "a0ae66967e033a1b16c408ff92aeab19"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.22-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.22-sources.jar",
          "size": 201305,
          "sha512": "f728d857333eb4d5ed786e0346efd1da17370bf243eeeb5f65837ae3ebb8e3dd779bb210aafc1759ce62b60f18d9a1a205fdb642feaf3f6812766d9822d4dbb6",
          "sha256": "b77bf388faef67be6839fbdedf88fb96c2f714060011aee5581ff634e73d4c44",
          "sha1": "0b95018fdfc5d62afcfba1c59219c58efb9bdf14",
          "md5": "6d04471692cd7bf1ada06e2cadfe40cd"
        }
      ]
    }
  ]
}
