{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.5.jar",
          "size": 516410,
          "sha512": "8332c40e50eabf209a4f452bb89cf3365ed756a1d1cc9dac5647734abc5aea3e3818cfe41e5f2fec5bc65f7b1f11fb22a44cdb2868506e1712924b4f85dfe436",
          "sha256": "1f89f43baf459f1df29006c1e83b699e519d9c4ea58fa0c9df99bc483ee4ce5c",
          "sha1": "b5737f1e72972105ef696c825f8588b576d365fc",
          "md5": "3a194b8c9d8d14afe39eceec0e816981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.5.jar",
          "size": 516410,
          "sha512": "8332c40e50eabf209a4f452bb89cf3365ed756a1d1cc9dac5647734abc5aea3e3818cfe41e5f2fec5bc65f7b1f11fb22a44cdb2868506e1712924b4f85dfe436",
          "sha256": "1f89f43baf459f1df29006c1e83b699e519d9c4ea58fa0c9df99bc483ee4ce5c",
          "sha1": "b5737f1e72972105ef696c825f8588b576d365fc",
          "md5": "3a194b8c9d8d14afe39eceec0e816981"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.5-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.5-sources.jar",
          "size": 255120,
          "sha512": "3b8364917c8e7f3e5c90cb664da445f6a69870c17dc2d231f0468e760a45d5526124501679544cd88e54c51dde9ee029fd80af3dd891fe2f2fc7e028224af5b8",
          "sha256": "2a07bf56fb37ff0880ba9cf78c01749ebd6aa64c542f599d45ccfd2b6ecce511",
          "sha1": "365659f199db467c116d9aadddba89aa9b63a922",
          "md5": "6ed3ec3f0080efad282a0acb04dd397a"
        }
      ]
    }
  ]
}
