{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.2.jar",
          "size": 550944,
          "sha512": "3d33ecc43490c5ba8f1543037f8debc66ad4393058ec4ff9f896109ca69847b20b3fa094a285daedf1f6b97f7948f387925772327220e56fb3629775ba3f4dd6",
          "sha256": "6e41adb978703bca9ab37f3acc751139479cd50d298b2783ca8bbeba6d6cef53",
          "sha1": "ec1b76f2349983aafac77431583c4154cdfabecf",
          "md5": "4e9ba3016c3d59b5778d817fd1a26216"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.2.jar",
          "size": 550944,
          "sha512": "3d33ecc43490c5ba8f1543037f8debc66ad4393058ec4ff9f896109ca69847b20b3fa094a285daedf1f6b97f7948f387925772327220e56fb3629775ba3f4dd6",
          "sha256": "6e41adb978703bca9ab37f3acc751139479cd50d298b2783ca8bbeba6d6cef53",
          "sha1": "ec1b76f2349983aafac77431583c4154cdfabecf",
          "md5": "4e9ba3016c3d59b5778d817fd1a26216"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.2-sources.jar",
          "size": 256754,
          "sha512": "710eb18dd0b16b63635cedf90d2e31b551f960106bc07e6951dde21e5997598f1029dbd386e2d66b237b607ba7eb4c1de9513adbaef7eb6be4a4ec5b7b8f50df",
          "sha256": "43946acdc57acf5b6146bea391a0eef92fbf322acb0b4cd09f9f572cf09afa9f",
          "sha1": "817ced16440200fd0479fb50dde121d7c78400b8",
          "md5": "5a547b2b0174b600e4172d24fe996606"
        },
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.2-sources.jar",
          "size": 256754,
          "sha512": "710eb18dd0b16b63635cedf90d2e31b551f960106bc07e6951dde21e5997598f1029dbd386e2d66b237b607ba7eb4c1de9513adbaef7eb6be4a4ec5b7b8f50df",
          "sha256": "43946acdc57acf5b6146bea391a0eef92fbf322acb0b4cd09f9f572cf09afa9f",
          "sha1": "817ced16440200fd0479fb50dde121d7c78400b8",
          "md5": "5a547b2b0174b600e4172d24fe996606"
        }
      ]
    }
  ]
}
