{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.4-2.2.2502.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2502.8.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2502.8.jar",
          "size": 479465,
          "sha512": "11af086dda1f354ca399a870aedf8bbf54a4e3611836e7e482d3ac836614770c4b5a9bbd4ae237e932017c15e8e619c587d82f720ef630c2dae80534c88b3f16",
          "sha256": "f24f8956d96cf64651d8d0926029c7c44f0aaebe46e15493c977dc84114b5fd9",
          "sha1": "c0a6501a1cc5e74c6deb8612ff0925327476c4b8",
          "md5": "aab7402adb7bdec71175e3884aacfc74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2502.8.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2502.8.jar",
          "size": 479465,
          "sha512": "11af086dda1f354ca399a870aedf8bbf54a4e3611836e7e482d3ac836614770c4b5a9bbd4ae237e932017c15e8e619c587d82f720ef630c2dae80534c88b3f16",
          "sha256": "f24f8956d96cf64651d8d0926029c7c44f0aaebe46e15493c977dc84114b5fd9",
          "sha1": "c0a6501a1cc5e74c6deb8612ff0925327476c4b8",
          "md5": "aab7402adb7bdec71175e3884aacfc74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2502.8-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2502.8-sources.jar",
          "size": 221321,
          "sha512": "3a605658c2511af341b91666cc5f50210c96da2a27e971d58b170c74c22b67fa376176e10a784d5f5d047623c041ca68d50300ecb99190a63da74a223a76a269",
          "sha256": "b0ef9c49871780bf005f951d68e7b65804c7a1e561bff7bb6093ec5ef6846094",
          "sha1": "ac8be2d5a0e8fc571c5ebb87f4f86971645f82cc",
          "md5": "f15707a36684d41b40bf30fc58945965"
        }
      ]
    }
  ]
}
