{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.1-1.1.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2515.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2515.0.jar",
          "size": 521337,
          "sha512": "286f73f9afa3c8bbd4acc66e188745e9fff2bbcc8d492f53565c4211f19272b8e2e21511098c05b4a4543f6aec8dbef86ec741c3ae6eef0546450d7239300ac6",
          "sha256": "146ebf4fae845179c1a12af97ad45214fb58a00ea67d30a89b823230d53654c0",
          "sha1": "fc70d36bc39af6e865ec007eb9cdd9b0e5803274",
          "md5": "aa49fee60283ff9eeb6dfe0d1196f3b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2515.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2515.0.jar",
          "size": 521337,
          "sha512": "286f73f9afa3c8bbd4acc66e188745e9fff2bbcc8d492f53565c4211f19272b8e2e21511098c05b4a4543f6aec8dbef86ec741c3ae6eef0546450d7239300ac6",
          "sha256": "146ebf4fae845179c1a12af97ad45214fb58a00ea67d30a89b823230d53654c0",
          "sha1": "fc70d36bc39af6e865ec007eb9cdd9b0e5803274",
          "md5": "aa49fee60283ff9eeb6dfe0d1196f3b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2515.0-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2515.0-sources.jar",
          "size": 452004,
          "sha512": "2e6de05dbcf0279f819dabbda7738e243298486259dd52171acd6ffb2e27633d5dc2512528acb868223238855f584279d4b886f3e238b9b0252a67105f08b651",
          "sha256": "c17a636dc39f8cb6cde57113cdd97d7d8d862cc536dba1d09d54a86deb0765bd",
          "sha1": "6ff5b4bf9f994fcb415de33c90806f92e31010cf",
          "md5": "23488f270822d334fe7c7fd58d1dfbe6"
        }
      ]
    }
  ]
}
