{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.6.2547.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2547.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2547.0.jar",
          "size": 540573,
          "sha512": "c1e8f85d918dd4cf46f9d00fd559be0b3450e05a8c9e5f0e9f561be38c5637aca017d8bb8ef36c622afa3b8351fd9f50ac28fc7b18c75c69c83d9789ece5dc0f",
          "sha256": "cfc994496569a8bd5ef3ddeac3f0ee6b25a2a1b109ad64d6b78ef2dc7599ea8f",
          "sha1": "bd56f9385fc6805fdf7c138c99bca3274bae706a",
          "md5": "0b744f83a056a7c0166cfd860a2743bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2547.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2547.0.jar",
          "size": 540573,
          "sha512": "c1e8f85d918dd4cf46f9d00fd559be0b3450e05a8c9e5f0e9f561be38c5637aca017d8bb8ef36c622afa3b8351fd9f50ac28fc7b18c75c69c83d9789ece5dc0f",
          "sha256": "cfc994496569a8bd5ef3ddeac3f0ee6b25a2a1b109ad64d6b78ef2dc7599ea8f",
          "sha1": "bd56f9385fc6805fdf7c138c99bca3274bae706a",
          "md5": "0b744f83a056a7c0166cfd860a2743bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2547.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2547.0-sources.jar",
          "size": 269229,
          "sha512": "57eadce04b7830a748df41b277150d1161a828478ce3a6548bf833ecac4970f86d6a38a382443d159accf0f441010777704e68ee3724bd1054350b87455dc13a",
          "sha256": "abb85b3994b1f8e6688484a585759dbe1b65f2867fb5af154eee7d91d9f3a7d8",
          "sha1": "c95bd080f9f2b0660647b24bc862e36050af3f01",
          "md5": "150d2e528a288db480c7a414a8378357"
        }
      ]
    }
  ]
}
