{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.6.2544.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2544.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2544.1.jar",
          "size": 545632,
          "sha512": "96c1155b108ad6d3ecc6cf5f5247f1710b1155a79a12d91d3643a8bb6fa62b3c4a5f83ca96bfeac0dbfffc05355016a7c84545352cdf094df95c4bbfd4ff0957",
          "sha256": "7b44e57dd34e1e1977a38783fb39270f666fe9ee50b2e05dabd55f40e9db9a38",
          "sha1": "4ac60068ad07521c3c5947619273e11be43d283e",
          "md5": "f91629e6956068a1773f160270e4e7a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2544.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2544.1.jar",
          "size": 545632,
          "sha512": "96c1155b108ad6d3ecc6cf5f5247f1710b1155a79a12d91d3643a8bb6fa62b3c4a5f83ca96bfeac0dbfffc05355016a7c84545352cdf094df95c4bbfd4ff0957",
          "sha256": "7b44e57dd34e1e1977a38783fb39270f666fe9ee50b2e05dabd55f40e9db9a38",
          "sha1": "4ac60068ad07521c3c5947619273e11be43d283e",
          "md5": "f91629e6956068a1773f160270e4e7a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2544.1-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2544.1-sources.jar",
          "size": 268392,
          "sha512": "e1d6d08a26ce7e0ec243642b7e87925fbd466f14c41e5e68e4a3a021b9446cbd35bcb82f254afe6f9ad9762b7ad3688cc4f3a69104688a4d155abc0d8f6ffeea",
          "sha256": "9bd2aa5e826a72d734db29bf3fbb01088dc73d7a452c6a24262e39d1a53a8668",
          "sha1": "7e93d8d7fcb20cf6076b2bf8a980960f027ae879",
          "md5": "974f2a669be10b171b0d0486661ecd15"
        }
      ]
    }
  ]
}
