{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2513.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2513.9.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2513.9.jar",
          "size": 706629,
          "sha512": "a2dcc1d9417ea019031e95d583ea9a430622ae92ebc4e1dbc879333417e7a995d6d6631d5f27d031e94271522b7f67e94842be043624605137fd9eeecea66005",
          "sha256": "f7d15cb34c37ac1b57bc7ac29983af2c0f3296964b3eb6db2a729ae0d531bdfe",
          "sha1": "c5d5c33f8ec5c476a2bfe5b5b9409ed9718dd97f",
          "md5": "1d12a321975acac9d9a9274c09ba4239"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2513.9.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2513.9.jar",
          "size": 706629,
          "sha512": "a2dcc1d9417ea019031e95d583ea9a430622ae92ebc4e1dbc879333417e7a995d6d6631d5f27d031e94271522b7f67e94842be043624605137fd9eeecea66005",
          "sha256": "f7d15cb34c37ac1b57bc7ac29983af2c0f3296964b3eb6db2a729ae0d531bdfe",
          "sha1": "c5d5c33f8ec5c476a2bfe5b5b9409ed9718dd97f",
          "md5": "1d12a321975acac9d9a9274c09ba4239"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2513.9-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2513.9-sources.jar",
          "size": 251633,
          "sha512": "d47512b03510dd44ec4b6f13e640444ac5a9e009efeb4440311211f566db1553fdaae331761f340996dff4c5c64ccee20387f20d6cb3f830a40b0ebb6138f185",
          "sha256": "a769883de3cc55503fd68f9fe54d91668438d53d8afc68b556fe77ebec593252",
          "sha1": "e61258b5cccf31efbe96dc00033f2c087b564d53",
          "md5": "9e33d1afa6ee24834b2568232c98fc15"
        }
      ]
    }
  ]
}
