{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2507.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.11.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.11.jar",
          "size": 498488,
          "sha512": "dfa0c0f08400c4c13e3a13d9a0ef98c5a48028e2a8cb3e8fd30036514ac50589cbff7feb0691bdbf8b7126acdb88bfa542edfec274446a750f83a58abfb58c4a",
          "sha256": "d578950f9f339412855046ba98bd9d57aa226a2a0011728aba84a355779ed24b",
          "sha1": "d165b943859a48d6bd3c7f876d43b887edde642a",
          "md5": "304e4d0a12dc6da47f525d724a46dee8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.11.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.11.jar",
          "size": 498488,
          "sha512": "dfa0c0f08400c4c13e3a13d9a0ef98c5a48028e2a8cb3e8fd30036514ac50589cbff7feb0691bdbf8b7126acdb88bfa542edfec274446a750f83a58abfb58c4a",
          "sha256": "d578950f9f339412855046ba98bd9d57aa226a2a0011728aba84a355779ed24b",
          "sha1": "d165b943859a48d6bd3c7f876d43b887edde642a",
          "md5": "304e4d0a12dc6da47f525d724a46dee8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.11-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.11-sources.jar",
          "size": 244749,
          "sha512": "36f0f6fc0e68102dab367b8663b814956bf34ecf388111204b00f002dd08753f71c290f6490448abc78367bbe000c5dc595b1bae4ab5066f0da0275d538a49fe",
          "sha256": "8cd84f291c75272da2a58bf5f6f7590fcc5fefd8c27cb20adbc5cd9808144be0",
          "sha1": "4cf8a8e7a4a3d5ec384a8d11e39db6d30c7bf1b1",
          "md5": "c4b38b183c1a1044227605cdd9a7932b"
        }
      ]
    }
  ]
}
