{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.7.2617.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.7.2617.0.jar",
          "size": 596054,
          "sha512": "260e4730f5b0750c7c3953ee2b83c8a8ec54e36dd19a596c297533368e14a770b5d18476b33fd12a174e4d59fb535fd1c0e9509eb85d3a919dd3a5c005b95289",
          "sha256": "ed5aec3a4095147ba5a276e908705659ed1c1250730f8603d0cff1c2a36699cb",
          "sha1": "110fd70aa4628b5b1867820fbd3f9def95ebcd76",
          "md5": "5417b67458324935041d198c1ac52f8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.7.2617.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.7.2617.0.jar",
          "size": 596054,
          "sha512": "260e4730f5b0750c7c3953ee2b83c8a8ec54e36dd19a596c297533368e14a770b5d18476b33fd12a174e4d59fb535fd1c0e9509eb85d3a919dd3a5c005b95289",
          "sha256": "ed5aec3a4095147ba5a276e908705659ed1c1250730f8603d0cff1c2a36699cb",
          "sha1": "110fd70aa4628b5b1867820fbd3f9def95ebcd76",
          "md5": "5417b67458324935041d198c1ac52f8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.7.2617.0-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.7.2617.0-sources.jar",
          "size": 256504,
          "sha512": "fbc095e188aa60056e054b94d532a0dcef57d678f0a195fb541423b5214d366b15bd281198f283c7ae0931584c102c9cc3e8a65f089194adcd7b6a047c3c0487",
          "sha256": "eddd99977bb4111fe837fe3ff84362d105d2c1b29dcf1ad16ded0956b2a0be16",
          "sha1": "41ea8ca137de11dd3b5e890c18abce89918f46ed",
          "md5": "e75d979e02be41040972509b3657f3ba"
        }
      ]
    }
  ]
}
