{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2507.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.8.jar",
          "size": 492778,
          "sha512": "092dd82feb3b09a66ffb68e662819b676a87afd909ff1f5e067e952c7dae76da634f0a72815149c307c8262342baf1717f26796bbd0edadd1be218843598950e",
          "sha256": "d1556ae032b6a951a11e142a99fef3d0dee06c7ce82c4468bdd6baeb7fd00f8a",
          "sha1": "7cd637326a0ecfea5b7f7c5f3adf8190e49bc7c9",
          "md5": "7ea30ac82139463764f0c190dce61c46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.8.jar",
          "size": 492778,
          "sha512": "092dd82feb3b09a66ffb68e662819b676a87afd909ff1f5e067e952c7dae76da634f0a72815149c307c8262342baf1717f26796bbd0edadd1be218843598950e",
          "sha256": "d1556ae032b6a951a11e142a99fef3d0dee06c7ce82c4468bdd6baeb7fd00f8a",
          "sha1": "7cd637326a0ecfea5b7f7c5f3adf8190e49bc7c9",
          "md5": "7ea30ac82139463764f0c190dce61c46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.8-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.8-sources.jar",
          "size": 244502,
          "sha512": "a894d92a5540a3fa016b0b8cb5f86a2e55d739dd31e2fc2cd17e510bcbdc8191c6547a900a432a181d7b9d2b44da6f1fa649ea873054c791690f740a0db6f69e",
          "sha256": "f613fe898700d6a714e9cf2947e7cf90775e4c47fe4289c5e7e871ec8e6a35c6",
          "sha1": "d1a3673d49840f22f315d1981eb57b3cb2e38a58",
          "md5": "b471e167ff364ab4661f9c3bbc1110ac"
        }
      ]
    }
  ]
}
