{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2504.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2504.7.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2504.7.jar",
          "size": 467439,
          "sha512": "b9f8810ed9c36d0440855fd8f97e55eeb5b8c566aaa8145c07f9fe2810dc85487eb7b6ca2cc5429a92edd60965cab8840de5f4c3e054375f2754221cfdd15c97",
          "sha256": "122fee76658af743c9323670d4fb150b645f87672054696904a8f1a42a9fac8d",
          "sha1": "d652056f1112fd8664626ac14428467a6759abff",
          "md5": "85a14a2f377b86e7f9e05c7fb59fb836"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2504.7.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2504.7.jar",
          "size": 467439,
          "sha512": "b9f8810ed9c36d0440855fd8f97e55eeb5b8c566aaa8145c07f9fe2810dc85487eb7b6ca2cc5429a92edd60965cab8840de5f4c3e054375f2754221cfdd15c97",
          "sha256": "122fee76658af743c9323670d4fb150b645f87672054696904a8f1a42a9fac8d",
          "sha1": "d652056f1112fd8664626ac14428467a6759abff",
          "md5": "85a14a2f377b86e7f9e05c7fb59fb836"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2504.7-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2504.7-sources.jar",
          "size": 236969,
          "sha512": "7fb1591cb4ee4db941220d745caa794cb02f44de3ac1ad0839f0ee0dc2660b8a5300e6266d715382fb3a32410f3d1fdc7587a715a4293bbf4626d21cbe5e01c3",
          "sha256": "bf407e35c06e1abf936ab1d7caa0b3f3437c92a46eaabf73eb98fc30f66fd151",
          "sha1": "9c86c2cafd10f976bbe6992cb85afb31e79d47e0",
          "md5": "ed6f5eaea38756df0f18acde3fc04c27"
        }
      ]
    }
  ]
}
