{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2513.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.0.jar",
          "size": 495859,
          "sha512": "12a82afca4dc6524dc7df479dbdbf7c2e2d7c6408d6b28ec3c96aec1fbf51c22b020e7256072ede12417b0735410f9f1b0f2ae0c303eb4ff24ca7a9c8a1f3e09",
          "sha256": "243a3cd4b1d3ea8cc19c29efff03aa80dab82e2e5a83761b9badf7fa7fed3b30",
          "sha1": "dd68c4d3ffab20eb8299fa1d5d01b1b5f4f616db",
          "md5": "bd340cf7053cccf27c100e326bea3f17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.0.jar",
          "size": 495859,
          "sha512": "12a82afca4dc6524dc7df479dbdbf7c2e2d7c6408d6b28ec3c96aec1fbf51c22b020e7256072ede12417b0735410f9f1b0f2ae0c303eb4ff24ca7a9c8a1f3e09",
          "sha256": "243a3cd4b1d3ea8cc19c29efff03aa80dab82e2e5a83761b9badf7fa7fed3b30",
          "sha1": "dd68c4d3ffab20eb8299fa1d5d01b1b5f4f616db",
          "md5": "bd340cf7053cccf27c100e326bea3f17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.0-sources.jar",
          "size": 250655,
          "sha512": "44c0e83c00828db185f9a8fc07190bec356e760bdee2079a92dfdee3616a77609752cdbac25ad9c2ea72ce031cba642b552fe232dcb591ec21184b7752308425",
          "sha256": "35ee5f9d21417902c34aa0ad02ffd3682935c8fb2a4d8885e228c614e3e681a9",
          "sha1": "14646ec7e8239d8bc2299f9359ca2f6c279e2de8",
          "md5": "c8a8e2d73809d043f75d7049371035e8"
        }
      ]
    }
  ]
}
