{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3-pre.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3-pre.jar",
          "size": 492783,
          "sha512": "cca6c11dc0c63aef62576ecb0d3cd03794e9141e01444b4a381a27c5d0d624320cb93e2f58e3bfeea99bea60ab03ac118b0da644a3f715f904ec391f2a6e00ce",
          "sha256": "c543847911232be22f81c5d7671d655ae54d60ac2fe8344296a5be0b3bbfd1d9",
          "sha1": "a19c96de58e432c0ad3d4d41b85ea40f4c43f660",
          "md5": "e7ed0d76bad5039ca7891c2e4897ae62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3-pre.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3-pre.jar",
          "size": 492783,
          "sha512": "cca6c11dc0c63aef62576ecb0d3cd03794e9141e01444b4a381a27c5d0d624320cb93e2f58e3bfeea99bea60ab03ac118b0da644a3f715f904ec391f2a6e00ce",
          "sha256": "c543847911232be22f81c5d7671d655ae54d60ac2fe8344296a5be0b3bbfd1d9",
          "sha1": "a19c96de58e432c0ad3d4d41b85ea40f4c43f660",
          "md5": "e7ed0d76bad5039ca7891c2e4897ae62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3-pre-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3-pre-sources.jar",
          "size": 248451,
          "sha512": "bfcb7773f891726a0fe929c1e5c16cb0b9fd0791cba40d45ceeb1aab0c2dfc8d2b42f388e4278495c47d2bcdc939badd93b14e1ee9545b183495b4e061b009de",
          "sha256": "5a901083d3ad290ea5427b4d640bb709aa2c8bf1b771449587069e5df1c55530",
          "sha1": "ec6c980794dc5ceb258ed0a311de33ed2e734b6b",
          "md5": "22b1ae9c3eec107fef92ad3db09fa2ab"
        }
      ]
    }
  ]
}
