{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2508.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.3.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.3.jar",
          "size": 679360,
          "sha512": "217ee0d053cc4ca431076ae2a6127edb0b96f4fd2f18b5ddbf2ca61800d4f0d1afadd5f8c5c9a7d7f77777964d240411415578ebe00e8e17ec1362fd0545d47e",
          "sha256": "410726ec17ce1ec81549765eb2ff01457b03ef431d67180be910c93ccf852a07",
          "sha1": "c383bdab8b0ca5f0224f7ba03744316e410ce1c2",
          "md5": "e767a3a6a77c774c4168ca654ce482d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.3.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.3.jar",
          "size": 679360,
          "sha512": "217ee0d053cc4ca431076ae2a6127edb0b96f4fd2f18b5ddbf2ca61800d4f0d1afadd5f8c5c9a7d7f77777964d240411415578ebe00e8e17ec1362fd0545d47e",
          "sha256": "410726ec17ce1ec81549765eb2ff01457b03ef431d67180be910c93ccf852a07",
          "sha1": "c383bdab8b0ca5f0224f7ba03744316e410ce1c2",
          "md5": "e767a3a6a77c774c4168ca654ce482d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.3-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.3-sources.jar",
          "size": 247973,
          "sha512": "5847ee53aa50f15f547e180141b7b4752f009bae55ebe6f649c82ecb30d2a16e928247af24c280c9f26cf1d6358dfd0ce880cb66726b82608c7830e6545827b4",
          "sha256": "a7a2e7835b36c674ca6d1c0a6a5d3cd2e6e98a6802b1efe6c8d12cb675e0823d",
          "sha1": "0b019f7478aeb2f42a8d7624288b5bd552c84848",
          "md5": "f0a67d65293ea9de9d1f547046890ba3"
        }
      ]
    }
  ]
}
