{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.22.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.22.jar",
          "size": 403670,
          "sha512": "55538cd00587f83c2d5c9dc012e80f19637c5412dd597c7fc3b0e5c6ec575b8f50fea55507c6e730ac254aa32b6cfa5b907711ec1741035afce5f3526fa4f21f",
          "sha256": "7b3111722cbbeb42b68dec8210ea78ddda188b10538cbdacd1916720711f506d",
          "sha1": "568cd767d672662d65be738d5da87c86319caa58",
          "md5": "fbcb5957ce8a259bba548ffdb8572322"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.22.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.22.jar",
          "size": 403670,
          "sha512": "55538cd00587f83c2d5c9dc012e80f19637c5412dd597c7fc3b0e5c6ec575b8f50fea55507c6e730ac254aa32b6cfa5b907711ec1741035afce5f3526fa4f21f",
          "sha256": "7b3111722cbbeb42b68dec8210ea78ddda188b10538cbdacd1916720711f506d",
          "sha1": "568cd767d672662d65be738d5da87c86319caa58",
          "md5": "fbcb5957ce8a259bba548ffdb8572322"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.22-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.22-sources.jar",
          "size": 203068,
          "sha512": "6a8c33f818fcd52404afee400d927682b872ed69acedcd1e8bedcf96b59add5491bb1814c22842393dd07096e17d02905450ba2ba057af162e54917d3af6b882",
          "sha256": "08bf81b63effce4c67d4682fb02b19378797001f8e71b8e0b0700265a5087198",
          "sha1": "550bfc7e04ca5ae14b2993ee025bdb3569b639f9",
          "md5": "59f7e80034659b16286d86981a1a7600"
        }
      ]
    }
  ]
}
