{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.3.jar",
          "size": 480862,
          "sha512": "365239c18e1257872795c3a4251a481157324c8c306b17e70876791d3611d435fde53e20aad628a0f2301d007be9f7e053cc2cafa73d252da1ac2417f4fd6026",
          "sha256": "01c32a84a67db2d6993cc5148aca4434bc12f8993de25f985826249227d1aaf0",
          "sha1": "bb8103c04b0a78c11420d90127aec571a55da071",
          "md5": "daddaf65cc83fb7c9dcd51b8161d01d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.3.jar",
          "size": 480862,
          "sha512": "365239c18e1257872795c3a4251a481157324c8c306b17e70876791d3611d435fde53e20aad628a0f2301d007be9f7e053cc2cafa73d252da1ac2417f4fd6026",
          "sha256": "01c32a84a67db2d6993cc5148aca4434bc12f8993de25f985826249227d1aaf0",
          "sha1": "bb8103c04b0a78c11420d90127aec571a55da071",
          "md5": "daddaf65cc83fb7c9dcd51b8161d01d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.3-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.3-sources.jar",
          "size": 243965,
          "sha512": "2d55f9a2cda84b3454a73e04078998a40fa34f289edb64268572e939c69c269b9774a19d8125ecbb8c931194f31f1aa01ecfac255fb29d2214badefd2e8e6b11",
          "sha256": "7118a4847ccc5df6c8c7ae8a209c4ee0f46460f6b5a0a599023944ae1167ded4",
          "sha1": "441a7db1aa33261e13b96d9a258a49a766ea1fe4",
          "md5": "6b770281e01f2cbb861f499eb4cfc58a"
        }
      ]
    }
  ]
}
