{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.1-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2514.2.jar",
          "size": 539048,
          "sha512": "e6508db28bbcc508308fe7257491b94e67c0dd4788a58b018c4a3b1144da87767521ee1afe5e6dd2e6e6b2ab744c3b8109f1b75b407badf4bae45638ea88f9bf",
          "sha256": "b66856f9d7f232dfea1e22f38a0481cace7873f3e800da60c81761c58b22bbf3",
          "sha1": "eacac6995f23a2f2def5669dc6047a9c51622579",
          "md5": "69fbe7e39f2f9221b7ef1bbb2bf82cd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2514.2.jar",
          "size": 539048,
          "sha512": "e6508db28bbcc508308fe7257491b94e67c0dd4788a58b018c4a3b1144da87767521ee1afe5e6dd2e6e6b2ab744c3b8109f1b75b407badf4bae45638ea88f9bf",
          "sha256": "b66856f9d7f232dfea1e22f38a0481cace7873f3e800da60c81761c58b22bbf3",
          "sha1": "eacac6995f23a2f2def5669dc6047a9c51622579",
          "md5": "69fbe7e39f2f9221b7ef1bbb2bf82cd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2514.2-sources.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2514.2-sources.jar",
          "size": 251024,
          "sha512": "978e1122c015defe6992d0a2dc205e28ce39eaef60c68dbc8824a2908f6ad24be80538e3624fa2faa6d7ebc522c0b6899b34763360f179a2ff7c46b6b2222ca0",
          "sha256": "0ae6eb55bfe542011aa73a75cf3bb927b22b8541137cd395d096268b32169b46",
          "sha1": "7cb05fd8fe33aa5b106d0831c18dd108f75b9ff0",
          "md5": "465a15282854541ed422b85eb430ad75"
        }
      ]
    }
  ]
}
