{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2514.2.jar",
          "size": 705439,
          "sha512": "70abaa027b975b8fcbac9e3caced4a532a3f47ae6e66d2af45036613bb2d5d40f73a21b3d97e45279c5aca17e0c5164d926f62e3a6b7a37ab74a4acfa0640bf4",
          "sha256": "b8469ad8415b02bcde72a4caec966734ef4d8f2a2b0817228a61fd8e89013262",
          "sha1": "36fcfc1159dd00aef3148b85237870747e80533a",
          "md5": "e21989dd8c3481f8ec44fde2dd06bba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2514.2.jar",
          "size": 705439,
          "sha512": "70abaa027b975b8fcbac9e3caced4a532a3f47ae6e66d2af45036613bb2d5d40f73a21b3d97e45279c5aca17e0c5164d926f62e3a6b7a37ab74a4acfa0640bf4",
          "sha256": "b8469ad8415b02bcde72a4caec966734ef4d8f2a2b0817228a61fd8e89013262",
          "sha1": "36fcfc1159dd00aef3148b85237870747e80533a",
          "md5": "e21989dd8c3481f8ec44fde2dd06bba9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2514.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2514.2-sources.jar",
          "size": 252677,
          "sha512": "19afe37886e87de504c43642fd54659519ac9e5303076401c32e45ecc4825540ce18a5e62f17516bef65f629679596df4da2382a92460caea1aa664b9f10ebcd",
          "sha256": "6feb2a09c09091cb9ff7661c47a36b37d309ea119c16f1840ea21a687695bd5d",
          "sha1": "c3e5f5b7247d25f9cafdd34999c8f61ce2d63f4b",
          "md5": "01e4424815e50fad6803efc25955851d"
        }
      ]
    }
  ]
}
