{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.2511.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.2511.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.2511.0.jar",
          "size": 16941468,
          "sha512": "c2f170e687742d0d958ef2975b6104fccf1dc529cce273e2e43f75e33c1df41e2adfbd32f7d983e6d0c4c4f6f249b76ed692557c587af6a29aec05db4841917a",
          "sha256": "213ad94a5a9fd765143150d4453f971421a6ba1487f3c6f0d179bc331816c200",
          "sha1": "71a5aeed1dba9e1f33ac996ce4f6dd85490675af",
          "md5": "f21df40f90961029e95527e4e1107852"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.4-0.6.10-neoforge"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.2511.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.2511.0.jar",
          "size": 16941468,
          "sha512": "c2f170e687742d0d958ef2975b6104fccf1dc529cce273e2e43f75e33c1df41e2adfbd32f7d983e6d0c4c4f6f249b76ed692557c587af6a29aec05db4841917a",
          "sha256": "213ad94a5a9fd765143150d4453f971421a6ba1487f3c6f0d179bc331816c200",
          "sha1": "71a5aeed1dba9e1f33ac996ce4f6dd85490675af",
          "md5": "f21df40f90961029e95527e4e1107852"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.2511.0-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.2511.0-sources.jar",
          "size": 16093202,
          "sha512": "f21528fa10db3cac9e9a51862a66b11a9a15605bbc12854a15470c900922af3a85f34b01b157b76239f930e04145f020da5af88ef86b3d15f0afcc61f1758ebc",
          "sha256": "d0b2e3c99e808ef58735747e10885a52583c70c14f5044f758cd5030b32ed257",
          "sha1": "66c948bd369b8bd4666f417ff4409ca2f965e707",
          "md5": "642e7d68faf83d2a15556a4bcfccc928"
        }
      ]
    }
  ]
}
