{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.7.2617.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.1.jar",
          "size": 560276,
          "sha512": "a61ebfea0ae7c92e3706d8bab0ff21aeb6de52f0a60e3897d298f318a6dabd0e22f4bb874b097dff75c2032c52bb444a46f493cbb9db272ab1f1cfedd26903de",
          "sha256": "0b912c9613a4ff4bb5c5e70eca4dd9da07aca2000099dbf1234ee088bda178a8",
          "sha1": "a8eb522e9b47a746718f0d8fb2e3a120c221a0e5",
          "md5": "82aa57cc4c35810131cea304d113740c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.1.jar",
          "size": 560276,
          "sha512": "a61ebfea0ae7c92e3706d8bab0ff21aeb6de52f0a60e3897d298f318a6dabd0e22f4bb874b097dff75c2032c52bb444a46f493cbb9db272ab1f1cfedd26903de",
          "sha256": "0b912c9613a4ff4bb5c5e70eca4dd9da07aca2000099dbf1234ee088bda178a8",
          "sha1": "a8eb522e9b47a746718f0d8fb2e3a120c221a0e5",
          "md5": "82aa57cc4c35810131cea304d113740c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.1-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.1-sources.jar",
          "size": 256726,
          "sha512": "82560fbd8273edf325981d8a439cbc47fec84c1f60c8487453f31785206adef8367d6773c60ee96b886374cb331b34fd3864c2402b202780d500920c738e2950",
          "sha256": "65612e72ef9b67518354b53ebc14599802a538cf1b76e8cb2d92179e7f6aa306",
          "sha1": "76782d7e339c68c88eb2a7979f17b7a4a09e0729",
          "md5": "dd0875b860dfe2ea86ebcc702f65dd60"
        },
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.1-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.1-sources.jar",
          "size": 256726,
          "sha512": "82560fbd8273edf325981d8a439cbc47fec84c1f60c8487453f31785206adef8367d6773c60ee96b886374cb331b34fd3864c2402b202780d500920c738e2950",
          "sha256": "65612e72ef9b67518354b53ebc14599802a538cf1b76e8cb2d92179e7f6aa306",
          "sha1": "76782d7e339c68c88eb2a7979f17b7a4a09e0729",
          "md5": "dd0875b860dfe2ea86ebcc702f65dd60"
        }
      ]
    }
  ]
}
