{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2517.0.jar",
          "size": 698041,
          "sha512": "84e5f671ea402cfa3599ac0b712533c5bdea9f8b29142c785a34c7ca6c6456d2a043094c927361d718c73a2c07d37ea29933707c1a0e6db8d938332ed40e002b",
          "sha256": "2c51bb3c8a000896b130083691b13588b4c8ff6930871d8d243fbc9e4100afbc",
          "sha1": "345b08eff930ea4d1206efabccbc318f0670173f",
          "md5": "7ae9db7594ff8b8cc8b624d4aa9981c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2517.0.jar",
          "size": 698041,
          "sha512": "84e5f671ea402cfa3599ac0b712533c5bdea9f8b29142c785a34c7ca6c6456d2a043094c927361d718c73a2c07d37ea29933707c1a0e6db8d938332ed40e002b",
          "sha256": "2c51bb3c8a000896b130083691b13588b4c8ff6930871d8d243fbc9e4100afbc",
          "sha1": "345b08eff930ea4d1206efabccbc318f0670173f",
          "md5": "7ae9db7594ff8b8cc8b624d4aa9981c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2517.0-sources.jar",
          "size": 256521,
          "sha512": "2b36db2d20f518823d67523ae06ff50abbe42f8b0ff5f49101b1266a1bdd7c0f50c64a0d321fe8ad424ca2bf7b9f8877cd937fb4c758ff3f05116f13674a3e62",
          "sha256": "e3e1d28875b805450901e404578c577383cb480ef176356b5f664860091d4a68",
          "sha1": "0d4e048fb36878073712004930952dae0705fde2",
          "md5": "df410fff3fe64672b838729668d3d28f"
        }
      ]
    }
  ]
}
