{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.6.2541.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2541.2.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2541.2.jar",
          "size": 538961,
          "sha512": "f7c780771762db95d10f01d20d47d96af25d87dfa4c90b0b436b75adc1d109084b4d2fc9602bfb0b004db05344e42792d157c88d39263dd64fd44dc2a5aa5e74",
          "sha256": "d0318b5be29b07d0ba30ce46e36638625c169ab76090d55ec4c03bab8db61dc1",
          "sha1": "cf4ab2686b2634163d64e9ced42920bffe99c061",
          "md5": "e005c49454e911cf3358dc13098b8c25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2541.2.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2541.2.jar",
          "size": 538961,
          "sha512": "f7c780771762db95d10f01d20d47d96af25d87dfa4c90b0b436b75adc1d109084b4d2fc9602bfb0b004db05344e42792d157c88d39263dd64fd44dc2a5aa5e74",
          "sha256": "d0318b5be29b07d0ba30ce46e36638625c169ab76090d55ec4c03bab8db61dc1",
          "sha1": "cf4ab2686b2634163d64e9ced42920bffe99c061",
          "md5": "e005c49454e911cf3358dc13098b8c25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2541.2-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2541.2-sources.jar",
          "size": 267971,
          "sha512": "44a5bc7f99688720208489ef8def9ec23ccb734ba8fc1e1fe0c72e49c93a481d2bb2f9100428c0460c9c58e5501fe4f3842472d323a168fbfc7281917bd31f08",
          "sha256": "76a81c8616db150056ba9ebc6b32ee227933220a5632054e9166db30f41be074",
          "sha1": "60f3d20cd09702f6cf7bfc0025bf18d87a2a004d",
          "md5": "25c75c42d5cb2ab2b01bb1f543bc7db2"
        }
      ]
    }
  ]
}
