{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "26.1.2-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.2.jar",
          "size": 561542,
          "sha512": "682699f196c4fa9ef682700ccd505117832fc22f03d4ac8c47d02d4cfbc474cc6870f9b9ed187ab3a393b4a098cbe0820e62c0eaca0400bae1584039039a501f",
          "sha256": "9673c8ffdbf92c253dac47d96a8cdb6ce0101492725124fba06638db00555529",
          "sha1": "a59dd283bfe9ed5838faa95ab7a623e578c58642",
          "md5": "f52c90aa67bf310c800850e5e1c4e6eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.2.jar",
          "size": 561542,
          "sha512": "682699f196c4fa9ef682700ccd505117832fc22f03d4ac8c47d02d4cfbc474cc6870f9b9ed187ab3a393b4a098cbe0820e62c0eaca0400bae1584039039a501f",
          "sha256": "9673c8ffdbf92c253dac47d96a8cdb6ce0101492725124fba06638db00555529",
          "sha1": "a59dd283bfe9ed5838faa95ab7a623e578c58642",
          "md5": "f52c90aa67bf310c800850e5e1c4e6eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.2-sources.jar",
          "size": 256801,
          "sha512": "f19029cecbe9d74498ab7b26e4551b3ba9f4bb6d50a707a1a763e8e2143e0bcacb4ac69c694d77321a578f1e6e906133391fa1a0cd5a8cd7d8b05d1d4ddeabc0",
          "sha256": "b90d8b067a85099e5b89ff6d3441d648b054ef9f52d9324464c00bbf1ee6d548",
          "sha1": "2b8a4ec7b4e621136ed409a9a300f718f079e10a",
          "md5": "680c94d9a515a71fe1e45abc688bce2b"
        },
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.2-sources.jar",
          "size": 256801,
          "sha512": "f19029cecbe9d74498ab7b26e4551b3ba9f4bb6d50a707a1a763e8e2143e0bcacb4ac69c694d77321a578f1e6e906133391fa1a0cd5a8cd7d8b05d1d4ddeabc0",
          "sha256": "b90d8b067a85099e5b89ff6d3441d648b054ef9f52d9324464c00bbf1ee6d548",
          "sha1": "2b8a4ec7b4e621136ed409a9a300f718f079e10a",
          "md5": "680c94d9a515a71fe1e45abc688bce2b"
        }
      ]
    }
  ]
}
