{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.8.0.2512.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2512.2.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2512.2.jar",
          "size": 18248149,
          "sha512": "f3533d95da0f8637b985231aba0f823eb358f0360e85fc74834dbce8b7172f5db2818173fcf91f48acbecf641428cebe5536ad2b035911c6fcf53839d559d8e5",
          "sha256": "139ec99591f2e36965c709b82224c6bf45d13b9da976b15ce3af56b729f40224",
          "sha1": "2aace96301adb4f9c7c138c52ae7922ad149e488",
          "md5": "780e53e99cc6985b2c834dd7be38217e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2512.2.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2512.2.jar",
          "size": 18248149,
          "sha512": "f3533d95da0f8637b985231aba0f823eb358f0360e85fc74834dbce8b7172f5db2818173fcf91f48acbecf641428cebe5536ad2b035911c6fcf53839d559d8e5",
          "sha256": "139ec99591f2e36965c709b82224c6bf45d13b9da976b15ce3af56b729f40224",
          "sha1": "2aace96301adb4f9c7c138c52ae7922ad149e488",
          "md5": "780e53e99cc6985b2c834dd7be38217e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2512.2-sources.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2512.2-sources.jar",
          "size": 17412581,
          "sha512": "7c864c434dba80e9e6a1d3a9fd9f845b68d7b418e031b428d78e574dd09ed63852c9543c33a307b1b3cfa2c9eaae95b484e88fcbe0eb0f42dbc65704d052c71a",
          "sha256": "6b635102c6733c7309d780a7db6ed408ad669f53c3d74c6d4328b422bfb16ab7",
          "sha1": "c80b76322b9ce329a1fac2e72cfc663b075660cc",
          "md5": "b67c064a9c529167d94552008761febf"
        }
      ]
    }
  ]
}
