{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.0.2518.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2518.4.jar",
          "size": 19677833,
          "sha512": "eb6559e5fbdc55437e75f29f36dd26a45cdd4f7178fe7a0bb19798fc0c17dddf98e96781a6aab31f8c5303953b15ac08cf781a4e6d83d92f9df751d62e921867",
          "sha256": "f558efb8aeb6971530aa22691e8a3a5d16629e41eb30104ea46e48231e654d8e",
          "sha1": "dd7c089be5a27d3275f7d2443619738d6ec82d99",
          "md5": "6b9b515244cca2669c0e5ccaa0f63a4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2518.4.jar",
          "size": 19677833,
          "sha512": "eb6559e5fbdc55437e75f29f36dd26a45cdd4f7178fe7a0bb19798fc0c17dddf98e96781a6aab31f8c5303953b15ac08cf781a4e6d83d92f9df751d62e921867",
          "sha256": "f558efb8aeb6971530aa22691e8a3a5d16629e41eb30104ea46e48231e654d8e",
          "sha1": "dd7c089be5a27d3275f7d2443619738d6ec82d99",
          "md5": "6b9b515244cca2669c0e5ccaa0f63a4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2518.4-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2518.4-sources.jar",
          "size": 18817971,
          "sha512": "eefa1788a659b66839117306c65d0393cc7f374d55f50fa8f5afa6ab6613c065aecd6b48ba683cc154f3ee090706dd8877ec56437a7653fefb614eb99a10c34d",
          "sha256": "69dacb9d464fdbd07623fc77a90b57b614894f48c6d6152ef0792643b74c4f12",
          "sha1": "35d74f3d2e62ca94e2abe3091869d51c3d762f2e",
          "md5": "dd4b257447eee0eddd40722da6116953"
        }
      ]
    }
  ]
}
