{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2502.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.6.jar",
          "size": 433392,
          "sha512": "99fac816ee231c1740f2ce1556ed1858241bf6454b580aeffbbd0509444c622386cd0d3ca6c39b1121f9c5b4c930113582d95615d3ee7903cb9311e0a03fa77e",
          "sha256": "43800a184d3aaab9f5c702cbf6ee53e92083e909c06464b965d8922d99e390ec",
          "sha1": "600a9b8e1c64e6abe1bfca1115bbdd0d31ca077e",
          "md5": "90b1f284fc6a771c9645b6f966ad2755"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.6.jar",
          "size": 433392,
          "sha512": "99fac816ee231c1740f2ce1556ed1858241bf6454b580aeffbbd0509444c622386cd0d3ca6c39b1121f9c5b4c930113582d95615d3ee7903cb9311e0a03fa77e",
          "sha256": "43800a184d3aaab9f5c702cbf6ee53e92083e909c06464b965d8922d99e390ec",
          "sha1": "600a9b8e1c64e6abe1bfca1115bbdd0d31ca077e",
          "md5": "90b1f284fc6a771c9645b6f966ad2755"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.6-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.6-sources.jar",
          "size": 222050,
          "sha512": "9a2a34bc5d92987c7eafd72de356d88d73ad8213deed418ab58b9d2adc050432606db5e8875fb393cd69d01a7af29a21e00ea00ce0c4d4c337509a42c84e710b",
          "sha256": "3e92fc752b8a61593c1294a51137d94d39e5c4c781d4137080d8955a512d3029",
          "sha1": "3d2854879efa133c7d28c6bb36ae50dbd1c96fda",
          "md5": "c090b69916a2b797f6e0a4ff35ce792f"
        }
      ]
    }
  ]
}
