{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.8-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3-pre"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8-pre.jar",
          "url": "legacy-forge-1.21.3-1.8-pre.jar",
          "size": 14399451,
          "sha512": "5ea9bf94833ec7ba7490905ddf6d5776cb6fc1d532eee8ace95c301676e1cdc1c7b17af7a33d4e32fdda6e1bc212ef22e527fb4632d7749adc3ff8007768ca88",
          "sha256": "92a2da0f263737806cb773aee03fd3726da27c8e426d496cd219fe825eea7aad",
          "sha1": "f6dff12081086f4ea82b7bdf710967c56cfa195f",
          "md5": "fde9e1e2baf6cfeb23492ef7d440057e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3-pre"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8-pre.jar",
          "url": "legacy-forge-1.21.3-1.8-pre.jar",
          "size": 14399451,
          "sha512": "5ea9bf94833ec7ba7490905ddf6d5776cb6fc1d532eee8ace95c301676e1cdc1c7b17af7a33d4e32fdda6e1bc212ef22e527fb4632d7749adc3ff8007768ca88",
          "sha256": "92a2da0f263737806cb773aee03fd3726da27c8e426d496cd219fe825eea7aad",
          "sha1": "f6dff12081086f4ea82b7bdf710967c56cfa195f",
          "md5": "fde9e1e2baf6cfeb23492ef7d440057e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8-pre-sources.jar",
          "url": "legacy-forge-1.21.3-1.8-pre-sources.jar",
          "size": 13586675,
          "sha512": "e676bf4d30cb286c7da616a2f859b5d2055ac3a4bd7eeb91aec30abfa42ba0dda40157e538151a5d21764ade447263ca39a1d67a1485ee65e70dfa084a579455",
          "sha256": "8be0498305f9f61d6c4f9c3432bbb6a526e0f0e72d3579b614c54321963bdf39",
          "sha1": "4bb4a95b817cb4faac9e4af2bb7c11e5cdacf452",
          "md5": "af4d033ea00cf8615a68311d2372fbf2"
        }
      ]
    }
  ]
}
