{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.15.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.15.jar",
          "size": 482151,
          "sha512": "debbd6e45ccb8ca93f0ef2fd3bc71e211fc1fcb5c82fc7271d656b44475a41eda072dad9d3896376ba8a3925e79125787aed28afc63eeb7ef761b1023439b3e3",
          "sha256": "a656e21ffd039cd629983b35d2e9e9cde703ed6f6510a4084ff509d31c0ed62f",
          "sha1": "93d01849d24a9955587e52b45cf361ebeff8533e",
          "md5": "6ed3bf5d6bff7e048ca5f682d2236a11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.15.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.15.jar",
          "size": 482151,
          "sha512": "debbd6e45ccb8ca93f0ef2fd3bc71e211fc1fcb5c82fc7271d656b44475a41eda072dad9d3896376ba8a3925e79125787aed28afc63eeb7ef761b1023439b3e3",
          "sha256": "a656e21ffd039cd629983b35d2e9e9cde703ed6f6510a4084ff509d31c0ed62f",
          "sha1": "93d01849d24a9955587e52b45cf361ebeff8533e",
          "md5": "6ed3bf5d6bff7e048ca5f682d2236a11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.15-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.15-sources.jar",
          "size": 244788,
          "sha512": "e0f707310a692d96eb9985f78ec7e672aaed6f78069d6f936b19eac346fbbff263627f6a810931daed3a8242a1bbd95a7771f2a02e8593dcc83131ba9c4b4fa6",
          "sha256": "5209a3a3dd475a5515847c45fefebf19dd267a93e9960affbe9c03da25736bcf",
          "sha1": "885878359a1b821736953770e168f0ad914e02eb",
          "md5": "78132a3bdc8b66de1a7e0d6bc4ffba1d"
        }
      ]
    }
  ]
}
