{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.2.jar",
          "size": 393274,
          "sha512": "de463c945542a6151a5820aef8026b85877668b344d6d1466dcf1d895eccb4ceda04775699e67109b6aa5456e310b84170dfe84ee76e94e4398efa904664aa55",
          "sha256": "c2196d18c0f0a5b3ba916f58d445be366c590595964cc0b822bee09bdc2beb7a",
          "sha1": "1086e901040f3eda0b15daa1f8a78e126cc83385",
          "md5": "48f2dca61fc4b0fd175111a07d05636c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.2.jar",
          "size": 393274,
          "sha512": "de463c945542a6151a5820aef8026b85877668b344d6d1466dcf1d895eccb4ceda04775699e67109b6aa5456e310b84170dfe84ee76e94e4398efa904664aa55",
          "sha256": "c2196d18c0f0a5b3ba916f58d445be366c590595964cc0b822bee09bdc2beb7a",
          "sha1": "1086e901040f3eda0b15daa1f8a78e126cc83385",
          "md5": "48f2dca61fc4b0fd175111a07d05636c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.2-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.2-sources.jar",
          "size": 198323,
          "sha512": "456b2ff32e9fd8f4b98f7548e36061cdd9dda9aeb20378e92ba08bce8fbc20e68171fa482f714d29a6c074efc1759be55de423a3e05322feff2bcb840434f464",
          "sha256": "b79390dd04e29ec1b7d6d04ede214be5511a161622ee8abdc8e01f228b9d8959",
          "sha1": "fd909f6bca6e3f2aa357fc4ca346ecc700f361a7",
          "md5": "3686272c089fc82cd527854d649917f2"
        }
      ]
    }
  ]
}
