{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2501.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.20.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.20.jar",
          "size": 379710,
          "sha512": "7abf42edabe0b154a2fe960a67780c9115d50365a5bc2f4c592801865b4fc0bbd1f352adab4d86b2ffc74e7f97e2e1569db3b30515be8dff163956a2da521f9f",
          "sha256": "963a81e83f167a8aff25a315e5bac1492f5e369f9d812fb78ab4f9fd0859e0ce",
          "sha1": "27afacd1685e7299d89ea5afcf5c68f761771807",
          "md5": "7336f701527f036438856643a42e071c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.20.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.20.jar",
          "size": 379710,
          "sha512": "7abf42edabe0b154a2fe960a67780c9115d50365a5bc2f4c592801865b4fc0bbd1f352adab4d86b2ffc74e7f97e2e1569db3b30515be8dff163956a2da521f9f",
          "sha256": "963a81e83f167a8aff25a315e5bac1492f5e369f9d812fb78ab4f9fd0859e0ce",
          "sha1": "27afacd1685e7299d89ea5afcf5c68f761771807",
          "md5": "7336f701527f036438856643a42e071c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.20-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.20-sources.jar",
          "size": 200556,
          "sha512": "3622d0fcc2702c5d21d2420b158dd77f8a034a839008653e6675e4099b085b951c659c130f2b809507588edf427b838cb9b0a7a9285c1e701cb542ec0a40decb",
          "sha256": "c95937d1ac781c5915fd9425f6e1c7b89213778e0c3838174a5a7994bf9c8197",
          "sha1": "2fc6175241efe2fe2cce4ce98dcca08bfe0a2b2e",
          "md5": "9e6335d78ce7f2e1657af0c461e8224f"
        }
      ]
    }
  ]
}
