{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.8-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.131.0+1.21.8"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-fabric-1.21.8-2.2.6.2545.0.jar",
          "size": 572701,
          "sha512": "5e506424eae6a7ed8cd720f3d034cfc1978b36765fad64ddb52299a48b14f5b37448a82af4679642a1697235e08ccfb0dd3c99fb95f9ff85958944d8a4299d73",
          "sha256": "f08f4aca4f2472fbc73b0aa1babd07c5cac7d3eb51852e5bb84692205454cebf",
          "sha1": "02848269bbcacf4fbea194c7affc70b32d2d58c9",
          "md5": "a7830586183102c8c0bdd91c8f8b0b6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.131.0+1.21.8"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "15.0.0-beta.3"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-fabric-1.21.8-2.2.6.2545.0.jar",
          "size": 572701,
          "sha512": "5e506424eae6a7ed8cd720f3d034cfc1978b36765fad64ddb52299a48b14f5b37448a82af4679642a1697235e08ccfb0dd3c99fb95f9ff85958944d8a4299d73",
          "sha256": "f08f4aca4f2472fbc73b0aa1babd07c5cac7d3eb51852e5bb84692205454cebf",
          "sha1": "02848269bbcacf4fbea194c7affc70b32d2d58c9",
          "md5": "a7830586183102c8c0bdd91c8f8b0b6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.6.2545.0-sources.jar",
          "url": "factory_api-fabric-1.21.8-2.2.6.2545.0-sources.jar",
          "size": 266571,
          "sha512": "a2d9a358632ebc8736432a65484960b5565f1aadf2a5360877882377ee08c20071e82432b0904ea8d27d3dd9f3d7da0f618f7887e961225d5b41c41053be9be0",
          "sha256": "ce592d039c2a7b2993be4b4a6572f7024089dc32f84b3dada244cf891b4cdd68",
          "sha1": "0efa67b469e29b4d758b4edd7b7f5ce8fcc76392",
          "md5": "9167fe00e768b1059d511a810571f353"
        }
      ]
    }
  ]
}
