{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2507.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.3.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.3.jar",
          "size": 481605,
          "sha512": "3c2ce34ca3364d04166baa5b86631474017b25a962027dc4f34a16a4e64607f6efb7d856c1c76091ece716af59c55c41093bc3f31921d455f357e04bc819448b",
          "sha256": "25ea732dc4377fd462f15b09d795186d965d2e52d22540e36347988847c7fed5",
          "sha1": "62229e29bbf256bea37ef1977f32c173b155c01a",
          "md5": "6122e92f5adf9145ac66bce6e0f64c9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.3.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.3.jar",
          "size": 481605,
          "sha512": "3c2ce34ca3364d04166baa5b86631474017b25a962027dc4f34a16a4e64607f6efb7d856c1c76091ece716af59c55c41093bc3f31921d455f357e04bc819448b",
          "sha256": "25ea732dc4377fd462f15b09d795186d965d2e52d22540e36347988847c7fed5",
          "sha1": "62229e29bbf256bea37ef1977f32c173b155c01a",
          "md5": "6122e92f5adf9145ac66bce6e0f64c9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.3-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.3-sources.jar",
          "size": 243846,
          "sha512": "eeafc38ae6815b5bd97e4fca6751ce612627cef0fdef7c6500d16b825c973007c3a2820973895f1864545b31fbfc144056ade2e0fe297b7beedb9ca851e38e38",
          "sha256": "9b6e9f2ddb878c5e11f7c7b67fcc37be7786e20cfe00128395e56f8663364e63",
          "sha1": "80b713263d8cfd8d3eb2709782ffb25521455fd3",
          "md5": "d5aef627f7fba0651a0d3adf03f91e24"
        }
      ]
    }
  ]
}
