{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2508.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.4.jar",
          "size": 509485,
          "sha512": "77cab024245d6db423d5cc80f9d60018763bdc3f2d291a02fd4225befcb5ae0335bad6238c2c1ac920af4691741d11cba93f5bf40604477aac4b8c188e20f02d",
          "sha256": "85b37bc61eab18f00275ed6374cde1ce0a7339fb9c6b7cbea60fd3a149818eb7",
          "sha1": "74ad0890363863b4eef678e96f1db86bc5149757",
          "md5": "2d6340f60a80592bf5247cc92990de4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.4.jar",
          "size": 509485,
          "sha512": "77cab024245d6db423d5cc80f9d60018763bdc3f2d291a02fd4225befcb5ae0335bad6238c2c1ac920af4691741d11cba93f5bf40604477aac4b8c188e20f02d",
          "sha256": "85b37bc61eab18f00275ed6374cde1ce0a7339fb9c6b7cbea60fd3a149818eb7",
          "sha1": "74ad0890363863b4eef678e96f1db86bc5149757",
          "md5": "2d6340f60a80592bf5247cc92990de4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.4-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.4-sources.jar",
          "size": 248350,
          "sha512": "9298520b768515b9f980d9ca1dce1ed3cac4dbe4394197bf7baef8b015ed9f723ce94e1a9d659312cc28dac831892338213a4a9094296da6a1f6fa674056e294",
          "sha256": "2e709fba6971f1358ec2ce3c471d83940506aafacd9eabbbc947a586322235d5",
          "sha1": "95c39a674e7267b8ae3fdbaaa19ccb15541e7100",
          "md5": "0b56809a3b3d167921380e947c48ed11"
        }
      ]
    }
  ]
}
