{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2514.2.jar",
          "size": 690746,
          "sha512": "07e5fd5a7c5d239d21c3fac45b84beb6f107e9dcb0d790fbfef489cc86504e86acf2a4031956bea8673767ca5fe4bed10c6824207322d5af29b8a89633c74dd1",
          "sha256": "a61a5da13a13a74178f52a62253aeeab5724cb76ea1610be6033538e744fc1ec",
          "sha1": "f1602ba9ede0abd2cbb763b609dd049e03946d26",
          "md5": "74a2103c23b97c577b8762c8aa1ba2ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2514.2.jar",
          "size": 690746,
          "sha512": "07e5fd5a7c5d239d21c3fac45b84beb6f107e9dcb0d790fbfef489cc86504e86acf2a4031956bea8673767ca5fe4bed10c6824207322d5af29b8a89633c74dd1",
          "sha256": "a61a5da13a13a74178f52a62253aeeab5724cb76ea1610be6033538e744fc1ec",
          "sha1": "f1602ba9ede0abd2cbb763b609dd049e03946d26",
          "md5": "74a2103c23b97c577b8762c8aa1ba2ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2514.2-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2514.2-sources.jar",
          "size": 254627,
          "sha512": "383604e4ad42efa6d99a2a45e616e0d6a2c79ac68b0b77ca97a8dd755b89c464b684e0e3aa64b6fc19ec114ffd8555ba9e22aa4f1d48e48a74920469d0254cca",
          "sha256": "3ddd996f6a78d3c70e10d42430bb42c4c85a36e806b8c4f7dc763ae4ddaffeb7",
          "sha1": "9a031157c84dbe80f1e9fa9b4bc97bdea380859a",
          "md5": "a0feab4076007a829961ffea959dcb8b"
        }
      ]
    }
  ]
}
