{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.7.10.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2504.4.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2504.4.jar",
          "size": 14248397,
          "sha512": "4df68bf3773220094f09413f1b973f05943f2c5e70c892aacdd5396ca7f86e7975dc3bc1be5ed4b5c876662adfe591c42393a5f91e2f41bb2b96d5b4f5ba24a2",
          "sha256": "125292c50bc4420fb9d34c2945e0c79b1513977553e6839dce43a4d44043a669",
          "sha1": "666074bd629dbf7fb28463cd9a50692b7f49d732",
          "md5": "5432c1edf4d2a3c93f3ae20fbbe4ba2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2504.4.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2504.4.jar",
          "size": 14248397,
          "sha512": "4df68bf3773220094f09413f1b973f05943f2c5e70c892aacdd5396ca7f86e7975dc3bc1be5ed4b5c876662adfe591c42393a5f91e2f41bb2b96d5b4f5ba24a2",
          "sha256": "125292c50bc4420fb9d34c2945e0c79b1513977553e6839dce43a4d44043a669",
          "sha1": "666074bd629dbf7fb28463cd9a50692b7f49d732",
          "md5": "5432c1edf4d2a3c93f3ae20fbbe4ba2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2504.4-sources.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2504.4-sources.jar",
          "size": 13453952,
          "sha512": "bb1ac8d57b353e2b068596ccc8e7077c7c68bacdd3b76f2464a477791c87c466c8c9282156bea4d42de589e3b550c30d7a5069b46fb6a923c30dfb4595dfdd6a",
          "sha256": "f5d87b3695d8e632709603551e5ac119280dee23c329efb994c853a6ee078567",
          "sha1": "807dfe35090a3ada3398383d0e9734c0f24b1a53",
          "md5": "e4daa37f56dffc8fad6d90ea249b94e9"
        }
      ]
    }
  ]
}
