{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.10-2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.8.jar",
          "url": "factory_api-forge-1.21.10-2.2.8.jar",
          "size": 1157211,
          "sha512": "11a26235a337511219055155650067a8f4eb1baf426b4fff58adb95feacffd6eeeec9109cf971373496eefb8a8de60a5e1cffc8be3d709fcfc5cf7896274e5e2",
          "sha256": "c27cc489298a622df44e6f4660b329b0baa5d47a6ef3ba67bc9f63561a4b008d",
          "sha1": "91b66d52fd6b7cb9d51ec430d8bcdc072582f78f",
          "md5": "9631d40d3afbc81de89148bf9005aeee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.10-60.0.0"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.8.jar",
          "url": "factory_api-forge-1.21.10-2.2.8.jar",
          "size": 1157211,
          "sha512": "11a26235a337511219055155650067a8f4eb1baf426b4fff58adb95feacffd6eeeec9109cf971373496eefb8a8de60a5e1cffc8be3d709fcfc5cf7896274e5e2",
          "sha256": "c27cc489298a622df44e6f4660b329b0baa5d47a6ef3ba67bc9f63561a4b008d",
          "sha1": "91b66d52fd6b7cb9d51ec430d8bcdc072582f78f",
          "md5": "9631d40d3afbc81de89148bf9005aeee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.8-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.8-sources.jar",
          "size": 256871,
          "sha512": "35bf0c83a127b5f0c19b6269fc46e7ce800b72182223fd7ae7b5409ef8127a5047417685b9700f2c3a1585fcf9a8bfe1e7c59d967fdaaebddb4d11bc4698708d",
          "sha256": "33a3878a23ecb5fab37e31b7f570c7debebd2f0cbefd6ca42ed0591f2996b9e5",
          "sha1": "cfef653f4d76f9b806b750f7eba204a3f2eb48a8",
          "md5": "eb4affeb290feaaef06fd2957495f4c9"
        },
        {
          "name": "factory_api-forge-1.21.10-2.2.8-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.8-sources.jar",
          "size": 256871,
          "sha512": "35bf0c83a127b5f0c19b6269fc46e7ce800b72182223fd7ae7b5409ef8127a5047417685b9700f2c3a1585fcf9a8bfe1e7c59d967fdaaebddb4d11bc4698708d",
          "sha256": "33a3878a23ecb5fab37e31b7f570c7debebd2f0cbefd6ca42ed0591f2996b9e5",
          "sha1": "cfef653f4d76f9b806b750f7eba204a3f2eb48a8",
          "md5": "eb4affeb290feaaef06fd2957495f4c9"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.10-60.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.8.jar",
          "url": "factory_api-forge-1.21.10-2.2.8.jar",
          "size": 1157211,
          "sha512": "11a26235a337511219055155650067a8f4eb1baf426b4fff58adb95feacffd6eeeec9109cf971373496eefb8a8de60a5e1cffc8be3d709fcfc5cf7896274e5e2",
          "sha256": "c27cc489298a622df44e6f4660b329b0baa5d47a6ef3ba67bc9f63561a4b008d",
          "sha1": "91b66d52fd6b7cb9d51ec430d8bcdc072582f78f",
          "md5": "9631d40d3afbc81de89148bf9005aeee"
        }
      ]
    }
  ]
}
