{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2508.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.3.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.3.jar",
          "size": 509174,
          "sha512": "7fc6e6e43900a9dcdd13491bcb74a0beca702d8a7266581c0e3b7ffd619957ef04103ba39289e99ac22b4fe68d55e8a4a108b21dfdd4d7db7625d84ac1ec6688",
          "sha256": "21007b1ceb11e7fcb2d5246a466f4960576c05c0cd70434fe5ce803df7445801",
          "sha1": "7547f3a38dacde39957ab0aa980d198a4861fa57",
          "md5": "a71ab2422e0abc13726ea103aa00b011"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.3.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.3.jar",
          "size": 509174,
          "sha512": "7fc6e6e43900a9dcdd13491bcb74a0beca702d8a7266581c0e3b7ffd619957ef04103ba39289e99ac22b4fe68d55e8a4a108b21dfdd4d7db7625d84ac1ec6688",
          "sha256": "21007b1ceb11e7fcb2d5246a466f4960576c05c0cd70434fe5ce803df7445801",
          "sha1": "7547f3a38dacde39957ab0aa980d198a4861fa57",
          "md5": "a71ab2422e0abc13726ea103aa00b011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.3-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.3-sources.jar",
          "size": 248271,
          "sha512": "7cb233506ce18b769d1219730f0b44d9305d02ec3357a45e1ededba1114272ef7e4582ddc15800db26cc8024836a324574f81edb2ace42b36fd2c1a5d698cb3b",
          "sha256": "8f0228c5a6d143123eca287a259a7831d53298266c3427c505b2c1bf31337a4d",
          "sha1": "eee3c78f7fef07f6564f1ac303cb6f1bcf09f2c7",
          "md5": "09df9f09f79be24d35f75f7d6542da53"
        }
      ]
    }
  ]
}
