{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2504.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.0.jar",
          "size": 494455,
          "sha512": "ab7c5180a0fc010d13e504ed67787023957ed27ab7b5d4d6fbf687a04832ada7d3bbf015f8480aacc29dc5cf7d2af2ca70ce8e9a6c9faeafdfa572198b64d1ca",
          "sha256": "c5618abf12dd8e2069ce7755c98926917923a6a7e3a38d2582feb5be8707a4a2",
          "sha1": "0ec48b6ed2af6144e73bec0b1ecdfe78a7977893",
          "md5": "c913a0064b9b8ca45a185d1983d4f789"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.0.jar",
          "size": 494455,
          "sha512": "ab7c5180a0fc010d13e504ed67787023957ed27ab7b5d4d6fbf687a04832ada7d3bbf015f8480aacc29dc5cf7d2af2ca70ce8e9a6c9faeafdfa572198b64d1ca",
          "sha256": "c5618abf12dd8e2069ce7755c98926917923a6a7e3a38d2582feb5be8707a4a2",
          "sha1": "0ec48b6ed2af6144e73bec0b1ecdfe78a7977893",
          "md5": "c913a0064b9b8ca45a185d1983d4f789"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.0-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.0-sources.jar",
          "size": 230238,
          "sha512": "4985dd3bdc8d1e2062f4526ee007c16e990c78af3c74c8ece676977433f86524f46ef35a546325c0e680168bd5b97b71c3fd22330c821803230d666212bf9466",
          "sha256": "632df98b205b135867f38c7f9d1a2efe3b15d6d67de3c4c254bf68d902f8fc46",
          "sha1": "d8bbd05b616b04680bd6fa529322138de78c1bea",
          "md5": "04bde015193338358c2bcfcdd9811850"
        }
      ]
    }
  ]
}
