{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.0.jar",
          "size": 518975,
          "sha512": "fd99b29dc3e5d499a8608f406b675959c01a60dc0189dcf34c19c8dbc319d1e29efccaeb7ffec4981c81a25cc458160829461b03ea496485e41ea762853d515b",
          "sha256": "ad65d476659fbe73852c056f8e54b33903d19aac546b5751fa75eaffcc867c70",
          "sha1": "445413176e43fae1c732e3d6ef6a083d19efcb58",
          "md5": "4fc2e62c010b6fa1cfa093f1942a88dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.0.jar",
          "size": 518975,
          "sha512": "fd99b29dc3e5d499a8608f406b675959c01a60dc0189dcf34c19c8dbc319d1e29efccaeb7ffec4981c81a25cc458160829461b03ea496485e41ea762853d515b",
          "sha256": "ad65d476659fbe73852c056f8e54b33903d19aac546b5751fa75eaffcc867c70",
          "sha1": "445413176e43fae1c732e3d6ef6a083d19efcb58",
          "md5": "4fc2e62c010b6fa1cfa093f1942a88dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.0-sources.jar",
          "size": 252269,
          "sha512": "0607feab32ba5bcec151918fde5abea1fd10712ae3a8563cb5baf8feb238a17a90131a74b1481b59199336f9916feaf94b868f231b8049c64dd4db7c4ec775d7",
          "sha256": "6527ac314e39561305bbc74e6b1f2c0cc7288ba8018b57582715e922cde654e6",
          "sha1": "34fe20145105d5bab8db989ed8a22a5a3123eb48",
          "md5": "a74f78ab5aa0256e1441a351984643b1"
        }
      ]
    }
  ]
}
