{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2510.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.4.jar",
          "size": 513866,
          "sha512": "c1721be513d3bd5f1d336772e478631cbf07bbd7c0796e0a677e3d93d2b28486c6929a4cec497bbfb93574e46757fac7c8db66e8fd53b5686daab6a54c1f588f",
          "sha256": "15ce351dd5f5ea92aad8ab609ed6959bed262923aed5f7207553e149ae240179",
          "sha1": "b372bb218b6462acf01a2db2fc32bc710a474188",
          "md5": "dad1e65d376097328fb2bfac697bc134"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.4.jar",
          "size": 513866,
          "sha512": "c1721be513d3bd5f1d336772e478631cbf07bbd7c0796e0a677e3d93d2b28486c6929a4cec497bbfb93574e46757fac7c8db66e8fd53b5686daab6a54c1f588f",
          "sha256": "15ce351dd5f5ea92aad8ab609ed6959bed262923aed5f7207553e149ae240179",
          "sha1": "b372bb218b6462acf01a2db2fc32bc710a474188",
          "md5": "dad1e65d376097328fb2bfac697bc134"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.4-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.4-sources.jar",
          "size": 250816,
          "sha512": "edfe741ba9f948d3d4414271ea9193e35408e0cbd3d73cf1b829151e2ff95dbcfd466bda132d202a371f8c8d394c600bdca20790af7282dee6e1f1301889d240",
          "sha256": "ba5a3c3181079994a5231612f63f2077b110f28002e6f1398bc4b52db3aa11de",
          "sha1": "93cf963b60dcb758d85aa209317954c21984e81f",
          "md5": "b22f08195a88e98d57d81e65989aee17"
        }
      ]
    }
  ]
}
