{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.5-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2518.3.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2518.3.jar",
          "size": 19666725,
          "sha512": "3213ee566bc6aa40654a90437350eb98155c439b0c7098f870d13c7a7d973782b86f11025c080a0453020fc76d9d0552810011e00a509ec1bf9057400b2a74cf",
          "sha256": "4e913fbe6931bac47071a14770004e3a08422a8633c42afa444412e6c6f7800c",
          "sha1": "3b7cfbf6a19be06ce13938e79fb0e2ea45fb67dc",
          "md5": "f989126a3d90703ebf98b41f7b0756d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "14.0.0-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2518.3.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2518.3.jar",
          "size": 19666725,
          "sha512": "3213ee566bc6aa40654a90437350eb98155c439b0c7098f870d13c7a7d973782b86f11025c080a0453020fc76d9d0552810011e00a509ec1bf9057400b2a74cf",
          "sha256": "4e913fbe6931bac47071a14770004e3a08422a8633c42afa444412e6c6f7800c",
          "sha1": "3b7cfbf6a19be06ce13938e79fb0e2ea45fb67dc",
          "md5": "f989126a3d90703ebf98b41f7b0756d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2518.3-sources.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2518.3-sources.jar",
          "size": 18808671,
          "sha512": "8118afffc3eefded9e5b78b1ebef0462d7a9e9cadec045e1ed188072feea84115742e7acfa3af3bf5bcd6ce1cb429baa832169aba7a3595c913a89623cb59b19",
          "sha256": "c8d925a72f1d92b29c31dee9258b4c54838eae83ecf743c02fbce79b316c4920",
          "sha1": "84f52a02bcf9e674401bad03d5df7ac0bba02536",
          "md5": "b78d52e8395fe5e00ca1d7f718cb45e3"
        }
      ]
    }
  ]
}
