{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.7.10.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.3.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.3.jar",
          "size": 14242473,
          "sha512": "3d6f324bbe90e54612d416df064eda535354b818675c0044577743d00ffa74fbec9559259f9f289948184faa07d1468cad6b92af2d5d1f5ecbd1ef2f8a25b50e",
          "sha256": "9c86ed0bd2cccc9bad6da159544423a3af05da60df188f80a9558ece57a7e485",
          "sha1": "df6ce32e5fc51fa617704b507c47e11f87aa2ad2",
          "md5": "5d1a652029f817a54627f08e348d423a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.3.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.3.jar",
          "size": 14242473,
          "sha512": "3d6f324bbe90e54612d416df064eda535354b818675c0044577743d00ffa74fbec9559259f9f289948184faa07d1468cad6b92af2d5d1f5ecbd1ef2f8a25b50e",
          "sha256": "9c86ed0bd2cccc9bad6da159544423a3af05da60df188f80a9558ece57a7e485",
          "sha1": "df6ce32e5fc51fa617704b507c47e11f87aa2ad2",
          "md5": "5d1a652029f817a54627f08e348d423a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.3-sources.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.3-sources.jar",
          "size": 13454893,
          "sha512": "b738fdaf9a664d60c304780b15a8e4b453f38f4ea95f1dd084049826f8688e958e298fb7ac03aeb5186b27f65e4557fc28494eaf1dee01ce9d488ae8ebadff8d",
          "sha256": "79d3e91aa63bc39f55654c36e99761ec2a5ed225ffebc1c5527050fd349f3bd6",
          "sha1": "e41cabf8f37e0d42b3036467ed5eb644f22af1ab",
          "md5": "724f1fa0c0c2d248384059c0b424b7a9"
        }
      ]
    }
  ]
}
