{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2518.5.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2518.5.jar",
          "size": 19708623,
          "sha512": "d31308dc6c1a1cca019797a13595eb1c74c0cd72b561025d20ec4fe4adebe4503175bd4a2c8acf23a466f74aa1be2de97a914a294a4493adc6027edc0c68413d",
          "sha256": "845a3d9a7ba457a80db7be3526e157b7ca4674e25703ae94efb5f7e42d53dd3d",
          "sha1": "504087c665c5e3e32102b2c49f8756ce79c42055",
          "md5": "0ec00962ee86877594be22d599255d11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2518.5.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2518.5.jar",
          "size": 19708623,
          "sha512": "d31308dc6c1a1cca019797a13595eb1c74c0cd72b561025d20ec4fe4adebe4503175bd4a2c8acf23a466f74aa1be2de97a914a294a4493adc6027edc0c68413d",
          "sha256": "845a3d9a7ba457a80db7be3526e157b7ca4674e25703ae94efb5f7e42d53dd3d",
          "sha1": "504087c665c5e3e32102b2c49f8756ce79c42055",
          "md5": "0ec00962ee86877594be22d599255d11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2518.5-sources.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2518.5-sources.jar",
          "size": 18853423,
          "sha512": "466b4aa6375f2a41ecdeb595599a90ab23a3c94f7be45f2827c1b0d4c55901029a33ff544aadb2c723f6d8c62c93766fa7eb462cad0f6c871715678f1f7da720",
          "sha256": "8442fdbea9c114e354fd6a4166808627bdeb3d3a72e57e726c7abae18a361b66",
          "sha1": "bd7f8ab01f992cb9d9ce52c18df133a0fe059573",
          "md5": "3fb5eab79861fa7696ce21de1616f66d"
        }
      ]
    }
  ]
}
