{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2514.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2514.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2514.0.jar",
          "size": 18276193,
          "sha512": "9b29b226839161fb0c5ebbf07b95ec24c7a7dde4fc3747db8f9b0c31a3457b24b434686a723d638c269e746d913e95e94a3e93e2f086ad1db23dc0d2f46be606",
          "sha256": "cb276af7f186fdd2d32115f78424318cec0b893bb4ba29819dc45d52ec5d9c58",
          "sha1": "40cb86bfdcb8e83b6a636b724526c1880426f267",
          "md5": "ad4a4573e1869deab8990f206bc5e7f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2514.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2514.0.jar",
          "size": 18276193,
          "sha512": "9b29b226839161fb0c5ebbf07b95ec24c7a7dde4fc3747db8f9b0c31a3457b24b434686a723d638c269e746d913e95e94a3e93e2f086ad1db23dc0d2f46be606",
          "sha256": "cb276af7f186fdd2d32115f78424318cec0b893bb4ba29819dc45d52ec5d9c58",
          "sha1": "40cb86bfdcb8e83b6a636b724526c1880426f267",
          "md5": "ad4a4573e1869deab8990f206bc5e7f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2514.0-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2514.0-sources.jar",
          "size": 17438525,
          "sha512": "851847b46039090a8791b646efe3ec51556c018001bc67b782a2ead32023e21f47ad67c475bd38fdaa74d5f98d2a2e6a26a0428e038a7e5e85377280a3964b84",
          "sha256": "eeb6a81d7b5dad8fee33e55a3d7522d3b268e603c8829a08a684c1e175e95051",
          "sha1": "30dfb58ccb1a4b5ac2f2a4512e170ae276b89c21",
          "md5": "726569ac96b9e8b138cd2656f8f54f39"
        }
      ]
    }
  ]
}
