{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "26.1.2-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.0.jar",
          "size": 561541,
          "sha512": "a9ea6d07574c2fb8b41d208e3f0c640407f0a8b236437b532f838bc130d13c3a677c344327ede9877a8bc84b4a3dd7cfbd5764bee9a03f0567b2521b543535a4",
          "sha256": "ebd799c7b580d43560a1d4fc7229caee4d8f43e7bb73639c18b715441ecb4dc6",
          "sha1": "84802409428765709dc374eb8045be36688b40a9",
          "md5": "7c348967c63dce1b15da974abdc89999"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.0.jar",
          "size": 561541,
          "sha512": "a9ea6d07574c2fb8b41d208e3f0c640407f0a8b236437b532f838bc130d13c3a677c344327ede9877a8bc84b4a3dd7cfbd5764bee9a03f0567b2521b543535a4",
          "sha256": "ebd799c7b580d43560a1d4fc7229caee4d8f43e7bb73639c18b715441ecb4dc6",
          "sha1": "84802409428765709dc374eb8045be36688b40a9",
          "md5": "7c348967c63dce1b15da974abdc89999"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.0-sources.jar",
          "size": 256801,
          "sha512": "642f707ca3b3660ad78ac3f019420e408b08699783b57c0dae938e2363bb21ada087548225afcbb15480008bfb44c637e2aba3206d5f27f887241ea494279388",
          "sha256": "11b1bb0602541395f282cbffd655e620299fea1750ff6aa91df0805664b02866",
          "sha1": "3cc71029e7966a8e01f9f9b5c05a9b9f9fa3d1f1",
          "md5": "98e5ef45d45afe2fa353a87c6276fde7"
        },
        {
          "name": "factory_api-neoforge-26.1.2-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.7.2617.0-sources.jar",
          "size": 256801,
          "sha512": "642f707ca3b3660ad78ac3f019420e408b08699783b57c0dae938e2363bb21ada087548225afcbb15480008bfb44c637e2aba3206d5f27f887241ea494279388",
          "sha256": "11b1bb0602541395f282cbffd655e620299fea1750ff6aa91df0805664b02866",
          "sha1": "3cc71029e7966a8e01f9f9b5c05a9b9f9fa3d1f1",
          "md5": "98e5ef45d45afe2fa353a87c6276fde7"
        }
      ]
    }
  ]
}
