{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2507.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.3.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.3.jar",
          "size": 503508,
          "sha512": "391cc83330dae223b1fe4bce81789041b480b45cdc442e5c38bc123dc3ced45f372755580854d9e1dda47af86abba7e4c465fe81b46cfe9d6f650a16c398472c",
          "sha256": "92da20b0ef644e64e588156a503bd5a7797e044508a2040e209b2b4cc4406b5c",
          "sha1": "7cfd4de7dc3595124996911ed231f831026452fd",
          "md5": "0da989e198b007233eeac575c7c024f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.3.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.3.jar",
          "size": 503508,
          "sha512": "391cc83330dae223b1fe4bce81789041b480b45cdc442e5c38bc123dc3ced45f372755580854d9e1dda47af86abba7e4c465fe81b46cfe9d6f650a16c398472c",
          "sha256": "92da20b0ef644e64e588156a503bd5a7797e044508a2040e209b2b4cc4406b5c",
          "sha1": "7cfd4de7dc3595124996911ed231f831026452fd",
          "md5": "0da989e198b007233eeac575c7c024f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.3-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.3-sources.jar",
          "size": 246018,
          "sha512": "c87dea45c08b6d5484f18d49210af3bf0bc213fa2790720d202e6eb2c64e42cd197245acc0d52ba8bfeb547687a8bb179cc5bd3e4964b72a6a9444f5d3158aa2",
          "sha256": "f51d88c3da0178a64f9e2b9a0138de43ec6eddb401eb5cb07e7ddfe81943d042",
          "sha1": "3fe209906b04cb846cf154347aba59550338596a",
          "md5": "83adefe0c9c1aaf002d29790736e7ff0"
        }
      ]
    }
  ]
}
