{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2507.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.8.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.8.jar",
          "size": 504208,
          "sha512": "c77681f41dbb5a7edf7eacaf8006dde144c0d9726483bef16d1ebbb08d0b94cead8e58c7f120a01efa0bebd02f521e9998b0b398470e838795b7813131e75876",
          "sha256": "d80eed67b1a6916526f2275f08bfc12c394e71afff03b87f9f20f20ac5b76287",
          "sha1": "be5919ada64afcb3e9507d2255bdee0455cf0a7c",
          "md5": "669d534c58061fc6143ad722860fba25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.8.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.8.jar",
          "size": 504208,
          "sha512": "c77681f41dbb5a7edf7eacaf8006dde144c0d9726483bef16d1ebbb08d0b94cead8e58c7f120a01efa0bebd02f521e9998b0b398470e838795b7813131e75876",
          "sha256": "d80eed67b1a6916526f2275f08bfc12c394e71afff03b87f9f20f20ac5b76287",
          "sha1": "be5919ada64afcb3e9507d2255bdee0455cf0a7c",
          "md5": "669d534c58061fc6143ad722860fba25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.8-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.8-sources.jar",
          "size": 246492,
          "sha512": "fb9c68786e3a90834f460bfdf8c316822789785859a0c2ea932e360bb993713c5c8dfadc37c636012e7394eaa0a67b4259d133dfd779c74f156dfae7de1e6f6b",
          "sha256": "f96b82f1b6ffd0383b96ade941b46330e8e6e2e84f7d5565d9c4977e2cba13ae",
          "sha1": "39ae9afb7ec8c33e1ed03cc689633fdb532969af",
          "md5": "6bd3dfe911e2d2b9d7e3259c654e8228"
        }
      ]
    }
  ]
}
