{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.20.4-1.7.10.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2508.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2508.0.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2508.0.jar",
          "size": 14379077,
          "sha512": "cf32e30b244b4aa227303a53292afd51cfc6d6cb07224043c0a39a51cebfd8120b68903d229f6ff99e81483cde68e853f257ec1332d0f995c52172e97884e62e",
          "sha256": "ce2a25250995e9d84684a370ffc218abc490b3080911a7b73ef21e62b07c35cf",
          "sha1": "8afc5d9465c9dc0a92d656436a9c47e0e53ecf9a",
          "md5": "4ae28b7e9e1a5a8a1e2b799af28b3847"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2508.0.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2508.0.jar",
          "size": 14379077,
          "sha512": "cf32e30b244b4aa227303a53292afd51cfc6d6cb07224043c0a39a51cebfd8120b68903d229f6ff99e81483cde68e853f257ec1332d0f995c52172e97884e62e",
          "sha256": "ce2a25250995e9d84684a370ffc218abc490b3080911a7b73ef21e62b07c35cf",
          "sha1": "8afc5d9465c9dc0a92d656436a9c47e0e53ecf9a",
          "md5": "4ae28b7e9e1a5a8a1e2b799af28b3847"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2508.0-sources.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2508.0-sources.jar",
          "size": 13554202,
          "sha512": "1e5fa8c21f182cc017b67a436391570eb8d0ff51c6392c5d13b3d3d4fe21f29d1e8d8de13c35c704d23833978d3f778ff5f535e92ee2de126009d44c2575490c",
          "sha256": "c68c002ebf494832bc90f36facaa8b68721525563331c4fd26e04351ee4bfa83",
          "sha1": "52096402b77336a7c5fa71b016ab770f550a3b3f",
          "md5": "43bb2fed7cf81652a64b13be396c4894"
        }
      ]
    }
  ]
}
