{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.4-1.1.2518.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2518.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2518.0.jar",
          "size": 643275,
          "sha512": "c602268a561709299b374fc712cdcf15f26a31fb690c5fd63a1a244d5653009468137e608f3f0a3183aee3728fdb1a222980adccff3d3c620f23b6eadf3b29b7",
          "sha256": "57487c6d640325ce78dc52ae377a3ad4b866efeaa658ea45b70378aec4cf5bca",
          "sha1": "36408739967ae5b7ec4441caf7547da3eb6e4f58",
          "md5": "cc81f45423c1819684aa6b628a967fb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2518.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2518.0.jar",
          "size": 643275,
          "sha512": "c602268a561709299b374fc712cdcf15f26a31fb690c5fd63a1a244d5653009468137e608f3f0a3183aee3728fdb1a222980adccff3d3c620f23b6eadf3b29b7",
          "sha256": "57487c6d640325ce78dc52ae377a3ad4b866efeaa658ea45b70378aec4cf5bca",
          "sha1": "36408739967ae5b7ec4441caf7547da3eb6e4f58",
          "md5": "cc81f45423c1819684aa6b628a967fb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2518.0-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2518.0-sources.jar",
          "size": 585481,
          "sha512": "abe8667747852d7aaefb4821dacacc887010a8f27bacbad77b75a51be4869e9a54705adec6fce9eda81d185024fe9e6230cb4b32e30c8c6fc2085b551cfcecb9",
          "sha256": "999fd8ccdcdcf0f44cfebf59297f8a5045f69236a35f65625a892eb7c6604671",
          "sha1": "5c3dda1f22064568c93ab2d5d5589545e9ec4653",
          "md5": "762a17506b2e6ea71164eb1390b635c3"
        }
      ]
    }
  ]
}
