{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.6.2541.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2541.1.jar",
          "size": 543505,
          "sha512": "c1f4d4eb7440d6fda4e3a7d7bacfea3d0bdb314c0c259a5d077a22457c974343da837a209f425d19cd2c6ea71b5579d1f8a246cb96221caf7f1fff592ce6ecf0",
          "sha256": "27be73e5bd3d8c87dbc623bb59e068021814817d1659d7c2601b05a97efdf933",
          "sha1": "d22168948b57f6e08cbdb3d2acfa6fa5eb89142a",
          "md5": "b1f21b41d518b01454b728a6a03feafb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2541.1.jar",
          "size": 543505,
          "sha512": "c1f4d4eb7440d6fda4e3a7d7bacfea3d0bdb314c0c259a5d077a22457c974343da837a209f425d19cd2c6ea71b5579d1f8a246cb96221caf7f1fff592ce6ecf0",
          "sha256": "27be73e5bd3d8c87dbc623bb59e068021814817d1659d7c2601b05a97efdf933",
          "sha1": "d22168948b57f6e08cbdb3d2acfa6fa5eb89142a",
          "md5": "b1f21b41d518b01454b728a6a03feafb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2541.1-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2541.1-sources.jar",
          "size": 267957,
          "sha512": "418dab671d66175c7b444a3e08038ab49d1dbc8393968b2473ecb05f73bad21244798ea3fbc2263e10d18ac1c3c278c66b7d53b6b3ee792d24fa1c9b9b704178",
          "sha256": "d7d5aab178ebb8b95d8eabcb2e17f878c78fc5a74cc0f7ebe8d4ef5eaf57eb53",
          "sha1": "e7fd32175ceb4d93fc176062e409ca274fb2a6ac",
          "md5": "9fb55cc450b889835abf7f496e469d27"
        }
      ]
    }
  ]
}
