{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.11.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.11.jar",
          "size": 454375,
          "sha512": "73557f609ec91b205daef53d3f359d3fc070d38fe87127c61be476db52fed8fee2183975c7838560c0e01373bd69979e04077db0da3212d0b820c3d776ea59be",
          "sha256": "0fe760fd2de6eb2d8e5068bbbd75b2dadddd24e21621fa8959a8fc59cb64760a",
          "sha1": "b50270afb81a905ec8a728036ef4005e139335d5",
          "md5": "cc76ba96f4218b8c8298f1f4029ef8c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.11.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.11.jar",
          "size": 454375,
          "sha512": "73557f609ec91b205daef53d3f359d3fc070d38fe87127c61be476db52fed8fee2183975c7838560c0e01373bd69979e04077db0da3212d0b820c3d776ea59be",
          "sha256": "0fe760fd2de6eb2d8e5068bbbd75b2dadddd24e21621fa8959a8fc59cb64760a",
          "sha1": "b50270afb81a905ec8a728036ef4005e139335d5",
          "md5": "cc76ba96f4218b8c8298f1f4029ef8c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.11-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.11-sources.jar",
          "size": 227688,
          "sha512": "ceefa18cf80bebe4ba769488acbaef00df8fcb9be020544c1e74e21f6bbb39e0bb0128b6754407284fbf5f4577bb1879d1ba323aa70fc344f5b0b7eb1ba97759",
          "sha256": "3b31ff22d9af74ac34a0e9e570d01223ba2366dbb1967aca2c2f1514e53d2341",
          "sha1": "75de51bf8f6a2434d948e59c304bd7e2bb746c4d",
          "md5": "1b6fb040da53d372021af7ec8b9b3ba7"
        }
      ]
    }
  ]
}
