{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2500.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.9.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.9.jar",
          "size": 364523,
          "sha512": "38c31f9ae85980c22e1c243ff5acd453b33d061ff0ab6e91b35808ec64c54e1b636d3c8f614c0b01c3c8392f187fab14f98716605e9cacf25e74b03f18948f5f",
          "sha256": "a57be2140c76a48764ce80fee52bb2dbf9e2401ddd34fc9172958ed9910e57a0",
          "sha1": "93e910179cdc9dff6d73cf91536c4702bdf68d3a",
          "md5": "fa0f855ada247b634bf7fc3d46c2f370"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.9.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.9.jar",
          "size": 364523,
          "sha512": "38c31f9ae85980c22e1c243ff5acd453b33d061ff0ab6e91b35808ec64c54e1b636d3c8f614c0b01c3c8392f187fab14f98716605e9cacf25e74b03f18948f5f",
          "sha256": "a57be2140c76a48764ce80fee52bb2dbf9e2401ddd34fc9172958ed9910e57a0",
          "sha1": "93e910179cdc9dff6d73cf91536c4702bdf68d3a",
          "md5": "fa0f855ada247b634bf7fc3d46c2f370"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.9-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.9-sources.jar",
          "size": 193384,
          "sha512": "53f4cd037258dade3010b46630e933b2499f9a1caf4e75e2bcc190cdbb675f1f7efb18446c69e3ced410e3934b3a27d2d1683bc04347b86a50264ceccc09c514",
          "sha256": "0e7af7a4d181d704ccb8c813f7a43a8ee5720932dad8d559fdcc709bb381fcbf",
          "sha1": "b070d2001ee68f789c17b5458c9c2a79b17997b2",
          "md5": "5a2a5587b6e06d084aa703ea4761c84f"
        }
      ]
    }
  ]
}
