{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.0.2512.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2512.4.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2512.4.jar",
          "size": 18264247,
          "sha512": "00211eb9d09d662c20bd655d7d5fc52663c3b01620b821574b9b75dee6ab2ce8ac6f886ccde5d9c038801f5769bba1db805558822007ac545810079463a102ee",
          "sha256": "72bb5d8aca9a91a1346e6e6feb011dc27aaa60e6ba4a69e4169175d698dda355",
          "sha1": "88b7e9b55724ae039762c7ac9c710ba1cb9af92c",
          "md5": "22aff857c1c97662afef88659cd58c42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2512.4.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2512.4.jar",
          "size": 18264247,
          "sha512": "00211eb9d09d662c20bd655d7d5fc52663c3b01620b821574b9b75dee6ab2ce8ac6f886ccde5d9c038801f5769bba1db805558822007ac545810079463a102ee",
          "sha256": "72bb5d8aca9a91a1346e6e6feb011dc27aaa60e6ba4a69e4169175d698dda355",
          "sha1": "88b7e9b55724ae039762c7ac9c710ba1cb9af92c",
          "md5": "22aff857c1c97662afef88659cd58c42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2512.4-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2512.4-sources.jar",
          "size": 17425569,
          "sha512": "8d63ceaa92af037ad10559f840ddaceb29b6171dd11afc1ddebc30874af10d1210e3cb34c3a6e7e62e4b9df1985460c5c89afefcedc44b196d3a36b5cc8b8c72",
          "sha256": "41dc9c5122b952a653fce8475f5cd221f4eaccb2cf3dc451628c087f9f6dc5bf",
          "sha1": "717248a703699b7095bb448d4fbb941920212d3f",
          "md5": "c1d0dd5d50be9106b679bf1d1d24af01"
        }
      ]
    }
  ]
}
