{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2518.3.jar",
          "size": 19760359,
          "sha512": "c73438ff79b071bba03708914b2ab3b0ac64f6a391bc2822cfa6b7ccf65e5fd65db9145a8d77afd804bba518de63ea822a89c835dd6a95997af9ae46470cbae8",
          "sha256": "f3700467619accbabf5b0cbe7187d20731101ecc3fbf084771c4eab7082d8e61",
          "sha1": "3dd50cb66c50bd9772f4e2e5eff6d591d47cabf3",
          "md5": "a03e7681f9e84da8c0ee6f8baa030f2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2518.3.jar",
          "size": 19760359,
          "sha512": "c73438ff79b071bba03708914b2ab3b0ac64f6a391bc2822cfa6b7ccf65e5fd65db9145a8d77afd804bba518de63ea822a89c835dd6a95997af9ae46470cbae8",
          "sha256": "f3700467619accbabf5b0cbe7187d20731101ecc3fbf084771c4eab7082d8e61",
          "sha1": "3dd50cb66c50bd9772f4e2e5eff6d591d47cabf3",
          "md5": "a03e7681f9e84da8c0ee6f8baa030f2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2518.3-sources.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2518.3-sources.jar",
          "size": 18903959,
          "sha512": "166e9a356c723ac18e46d5bfbbee29485afc4d5f7f396f07db7d8426f4605b47d8b8dd143a35228c849515b9473a3b572b8eb4493b25d79b8dc7c0a4d8a0774d",
          "sha256": "6a655fda2d20d09f1d9b51eafc42446b47099b4c9b2b951eaed5df786b5de57d",
          "sha1": "a00b5d37daa2203c1cc171a32d163cd322d04bc7",
          "md5": "8493e5a0af480d9b9873152edb7e7763"
        }
      ]
    }
  ]
}
