{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.22.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.22.jar",
          "size": 377820,
          "sha512": "3c0c35e36ed7b970aaaf6e83c6809e6d3d94f3a6ad53bb42f3d8676eb40f0c1a6d245578741ab00cf96512e5d9ad2e8d98268d8ed3de8b7a1b3501497b48bf93",
          "sha256": "aaf983edeb5c51a785927214ad2ccd450427bef4a9f0a1b680bd831a56ebf6cb",
          "sha1": "bc0b124d00561dfcc4a6a0c37974973efeede0e2",
          "md5": "688664894e4e08c1098cac624c2959ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.22.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.22.jar",
          "size": 377820,
          "sha512": "3c0c35e36ed7b970aaaf6e83c6809e6d3d94f3a6ad53bb42f3d8676eb40f0c1a6d245578741ab00cf96512e5d9ad2e8d98268d8ed3de8b7a1b3501497b48bf93",
          "sha256": "aaf983edeb5c51a785927214ad2ccd450427bef4a9f0a1b680bd831a56ebf6cb",
          "sha1": "bc0b124d00561dfcc4a6a0c37974973efeede0e2",
          "md5": "688664894e4e08c1098cac624c2959ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.22-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.22-sources.jar",
          "size": 201361,
          "sha512": "9e92b339792aa2e72745c3b818c805ffe84ebbea7013ae1596b28743177aa4f2dcd059f33f6ee5dac49385b7bb9e6215f3419ef980d6be36bf6680c1aa364b22",
          "sha256": "9bf492a279f375b05a97c0f75e9f5dd8660c6203b0b4879246730d253bad584d",
          "sha1": "7e2d55ecd4b2d6dbb940e8ff3f42d2a62298fee8",
          "md5": "b68e6c16b73462492f45b7da0545f3a2"
        }
      ]
    }
  ]
}
