{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2504.6.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2504.6.jar",
          "size": 474234,
          "sha512": "3d2e45e1878ee87ff6f4627bc3ab8b29b87003eb8b94c16e7aebe5f7a1df5d387ece163fc8568dcd662b07892c78e03bb7090798c536af6b908ef04e0bd5465d",
          "sha256": "910749ecb6d9e88e763a770a9bc94c3d446dbc4641f799ffea5f819c8dfcbc57",
          "sha1": "ab845648bf3a50ffd1a406cb955a16a85ab9a149",
          "md5": "a93a297b8a6c05ac02cde97ee802c3fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2504.6.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2504.6.jar",
          "size": 474234,
          "sha512": "3d2e45e1878ee87ff6f4627bc3ab8b29b87003eb8b94c16e7aebe5f7a1df5d387ece163fc8568dcd662b07892c78e03bb7090798c536af6b908ef04e0bd5465d",
          "sha256": "910749ecb6d9e88e763a770a9bc94c3d446dbc4641f799ffea5f819c8dfcbc57",
          "sha1": "ab845648bf3a50ffd1a406cb955a16a85ab9a149",
          "md5": "a93a297b8a6c05ac02cde97ee802c3fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2504.6-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2504.6-sources.jar",
          "size": 236874,
          "sha512": "7625d6a20de5a4d544900588b5aa37eec0002844c4590d198dcf55a453ae2845714b99f65fe7368557b576c01c29f8f1c372cbe2e633889b66be5ada6f9d0562",
          "sha256": "241f5aa07a0c68d3639a1328aa8b383847eb5f783f143ce4039f11b740a8699a",
          "sha1": "a13ba20477e86fc062c2f6f8ea55ee0f1eb5f36a",
          "md5": "a97b1de812d575e9485354d690acc849"
        }
      ]
    }
  ]
}
