{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2501.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.0.jar",
          "size": 351579,
          "sha512": "059abe5800c632bf76987ba90b8770d6911d95354d84d1e492fa011d89e80097fff54f35735972451a7e3a4fbcaa73b35136760d295e6233374ea9f1f8c59649",
          "sha256": "12e29242bdbdb7735568e01f8e25d923836edb1a62ca8e46cf20987c1c064896",
          "sha1": "6e5656e3ce00f0f13606eca64ebccad936da7a9d",
          "md5": "8500342ed261a9b8c7e5aef0fcfeaf8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.0.jar",
          "size": 351579,
          "sha512": "059abe5800c632bf76987ba90b8770d6911d95354d84d1e492fa011d89e80097fff54f35735972451a7e3a4fbcaa73b35136760d295e6233374ea9f1f8c59649",
          "sha256": "12e29242bdbdb7735568e01f8e25d923836edb1a62ca8e46cf20987c1c064896",
          "sha1": "6e5656e3ce00f0f13606eca64ebccad936da7a9d",
          "md5": "8500342ed261a9b8c7e5aef0fcfeaf8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.0-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.0-sources.jar",
          "size": 194826,
          "sha512": "2c3ce2ab413428a04947ab194b44401a357254132047ecf5b68dc842f04354a34a4de3e815470234fb5c61f8dd3a6ca61c9058570c0edbde83b8b64831484214",
          "sha256": "57bbae79c391f51e3c290ac09a66c7294879c075189d9bf795af6e81109a945b",
          "sha1": "e61fb922ed7ff27dc7c676bf9ff459356d189b15",
          "md5": "f46612a5f40cf4ae79432f6488bd0eb8"
        }
      ]
    }
  ]
}
