{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.3.jar",
          "size": 451651,
          "sha512": "9d0b0dfc8e71f7c5744b29ad256972685b8328338940445d87415136f390b5501cbe3deb39d075ea789366ccb6a71753c8580a76b2fa676ad6b699d359c83bb1",
          "sha256": "66946d0359598c4054b0435155a0764a92a98a38bdc02e1384304cad3a93d8a9",
          "sha1": "0788508529a2eaacec5d8b3a0de29ffa24275cda",
          "md5": "d7d1c75c39ca82f684accf4c804e73e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.3.jar",
          "size": 451651,
          "sha512": "9d0b0dfc8e71f7c5744b29ad256972685b8328338940445d87415136f390b5501cbe3deb39d075ea789366ccb6a71753c8580a76b2fa676ad6b699d359c83bb1",
          "sha256": "66946d0359598c4054b0435155a0764a92a98a38bdc02e1384304cad3a93d8a9",
          "sha1": "0788508529a2eaacec5d8b3a0de29ffa24275cda",
          "md5": "d7d1c75c39ca82f684accf4c804e73e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.3-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.3-sources.jar",
          "size": 233096,
          "sha512": "607184813e2a00b8b8f58f352084d8f969ebec0064a93e364d828640bbff945c62743b3e942f41d16da81932d8d78d907bbab2ba4a87ac29cf3852d15f552ca4",
          "sha256": "77185dbc40782dcd54ec9f57fc7fb0577aba14801b83791a0f02b25c4fb94aa9",
          "sha1": "dfadd041b80101dedf10366da9b05a5bbc2faa23",
          "md5": "29e4cb61e660bd566cfb259ea09f24d2"
        }
      ]
    }
  ]
}
