{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.3.2513.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2513.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2513.2.jar",
          "size": 530073,
          "sha512": "df85ee30434146980bbc864c83a172456bfe02448e7e7ebe898894b2eeff900525dad1399b9e1fafebacf3fcb107a5a6c7d32ee749163b57abaad9f2dbbee510",
          "sha256": "e18e361809c473c21e36a7df839c14b6ac65c8f62ab64f446b5f8d7ed0d9db2a",
          "sha1": "35148911955c61a48b32ea3194e26c81f051a282",
          "md5": "df37d35e7ce372f2d202d6d08df3e135"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2513.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2513.2.jar",
          "size": 530073,
          "sha512": "df85ee30434146980bbc864c83a172456bfe02448e7e7ebe898894b2eeff900525dad1399b9e1fafebacf3fcb107a5a6c7d32ee749163b57abaad9f2dbbee510",
          "sha256": "e18e361809c473c21e36a7df839c14b6ac65c8f62ab64f446b5f8d7ed0d9db2a",
          "sha1": "35148911955c61a48b32ea3194e26c81f051a282",
          "md5": "df37d35e7ce372f2d202d6d08df3e135"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2513.2-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2513.2-sources.jar",
          "size": 248968,
          "sha512": "508637177753ad088a372f37571555c7a1522911e25a8d8b203477df02ba014f0582bd5684d70368d7abc6065a0ee3b446ad5bb59e835e0b6975e54b6eaa4382",
          "sha256": "02163c84288ef6c6dd60b975b3a9fe28e42b18f2c3ac71f56f3df34203859f50",
          "sha1": "1440a3601bd87962018482d2b68691360d437b88",
          "md5": "2a95bace500d777ccc0352a81a086e63"
        }
      ]
    }
  ]
}
