{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.1.jar",
          "size": 452578,
          "sha512": "c3dda3ab2901b55ee10ee18afffad7c303ba20aee508319b2497d2ec89ab375dc6b566053084671e9671668aa7a4b5e4c5fa2cfe697c8b8f08a1a58202c15ac1",
          "sha256": "b5a7eced52660c8bfe79238c06c884b3c601edefdb0cd0a97ede8149ef873532",
          "sha1": "9700d247f372fa4ec6e4a2d35d01c7f9b6b5f86d",
          "md5": "fafc8b6fcf1db0ccd7e87829d22446ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.1.jar",
          "size": 452578,
          "sha512": "c3dda3ab2901b55ee10ee18afffad7c303ba20aee508319b2497d2ec89ab375dc6b566053084671e9671668aa7a4b5e4c5fa2cfe697c8b8f08a1a58202c15ac1",
          "sha256": "b5a7eced52660c8bfe79238c06c884b3c601edefdb0cd0a97ede8149ef873532",
          "sha1": "9700d247f372fa4ec6e4a2d35d01c7f9b6b5f86d",
          "md5": "fafc8b6fcf1db0ccd7e87829d22446ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.1-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.1-sources.jar",
          "size": 231880,
          "sha512": "231191dda3a89759bc683b089f93d904f0a168bd1530df849ac7fe9cfbd0027bc9ec265674bcd4646914dd90a3b825b30dc46c79eed603d859e6e12096f85dc3",
          "sha256": "40efcc3786390994e9cd455084c4cf3f6ca633832940374f2082cc8821fde0a0",
          "sha1": "dd1617ba6db17186db90311c0d0a66f08fa952e5",
          "md5": "f53b9e85466cea8c8f8f8c37d1bef9e9"
        }
      ]
    }
  ]
}
