{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.4-1.8.0.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3.2514.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2514.0.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2514.0.jar",
          "size": 18254308,
          "sha512": "c8e9ee8690042af13130625a5f8a4635bb9fdc3460acbc3515e8daadf8e5b93463c31572ed4370d81d05e0a667dd9864519ba30e2343e8c37d57a329d857b6cc",
          "sha256": "fce4dc99785b3e5a3bec5b6b2de9c0fb0c10a36766cc315c481e2be9b559621f",
          "sha1": "4c6bf960f04d2fcf82ebc84c6d3073a3a4cdacc3",
          "md5": "859e6837450eeecfb28f69ee1b53c6e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3.2514.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2514.0.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2514.0.jar",
          "size": 18254308,
          "sha512": "c8e9ee8690042af13130625a5f8a4635bb9fdc3460acbc3515e8daadf8e5b93463c31572ed4370d81d05e0a667dd9864519ba30e2343e8c37d57a329d857b6cc",
          "sha256": "fce4dc99785b3e5a3bec5b6b2de9c0fb0c10a36766cc315c481e2be9b559621f",
          "sha1": "4c6bf960f04d2fcf82ebc84c6d3073a3a4cdacc3",
          "md5": "859e6837450eeecfb28f69ee1b53c6e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2514.0-sources.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2514.0-sources.jar",
          "size": 17422390,
          "sha512": "b7dc2eb587a3673525720dc799788e85a5af2ff32ca600a5a4f9e0bcd791c0a35ace4bf8516dc254c70f9399451dd25e1df78b3d5474d1443af3f17bb1c4b403",
          "sha256": "6b8c6a49045ea8dc0832248a855d0ab93f55b81872ccac1ebef7c22143498c91",
          "sha1": "128e0919511f4c18c72e148b23045669f867fc4c",
          "md5": "2f36c5d00ac05c0241ea59e8bd1a0d23"
        }
      ]
    }
  ]
}
