{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.10-1.8.5.2546.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.10-2.2.6.2545.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.135.0+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.10-1.8.5.2546.0.jar",
          "url": "legacy-fabric-1.21.10-1.8.5.2546.0.jar",
          "size": 20112903,
          "sha512": "7c8f0bc79a9f7d2d703f985ee44e3592482ec80f3650ccd0ad5f8445220b162edcfdf0bfed2d58b032597530089e6e3a05640730e567460c654f82884550078d",
          "sha256": "48614231b7f9925fb53f8128a3664090d362ff41a48d0340f57e882c473934cb",
          "sha1": "33851cce5940a7b41904ca669357c58f2b0c7c25",
          "md5": "7fb4179146680649f8cc05ef1b3efe58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.10-2.2.6.2545.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.135.0+1.21.10"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "16.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.10-1.8.5.2546.0.jar",
          "url": "legacy-fabric-1.21.10-1.8.5.2546.0.jar",
          "size": 20112903,
          "sha512": "7c8f0bc79a9f7d2d703f985ee44e3592482ec80f3650ccd0ad5f8445220b162edcfdf0bfed2d58b032597530089e6e3a05640730e567460c654f82884550078d",
          "sha256": "48614231b7f9925fb53f8128a3664090d362ff41a48d0340f57e882c473934cb",
          "sha1": "33851cce5940a7b41904ca669357c58f2b0c7c25",
          "md5": "7fb4179146680649f8cc05ef1b3efe58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.10-1.8.5.2546.0-sources.jar",
          "url": "legacy-fabric-1.21.10-1.8.5.2546.0-sources.jar",
          "size": 19110331,
          "sha512": "e04db4f60eb5315b0e614e977e3a62b47ca0645aa4a2272b74d26bd067ea6a3091bc892c3647c60c9846ceea6b92c7feb837f884085a38e07c4ce25cd0cdbbdc",
          "sha256": "26fa0432e2a562f7ec85c1c6bc2807e44222f10988922abadc829cf889ca9e4e",
          "sha1": "b9170a1443879dc374e35712c1ce47ade70bb86f",
          "md5": "6b82ba45fefa2d746eead19ae368016b"
        }
      ]
    }
  ]
}
