{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2516.0.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2516.0.jar",
          "size": 18252967,
          "sha512": "43e655e1c871406620b30ca37d51a05a326e7ef259a54dfa01fdbb469cabfe7a526a00258cd474efc2a499bb578bfb67089081784f7e3776c0f15dc11535ce03",
          "sha256": "76566a32eac071b58dc85ed90bb24dc9ef2aa64b2cca9920d56a93a5bfb66136",
          "sha1": "f0d7bb9889110a644671b2d13127a19712ebd21e",
          "md5": "ccc115ef567194a7460d9c1ec0555aeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2516.0.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2516.0.jar",
          "size": 18252967,
          "sha512": "43e655e1c871406620b30ca37d51a05a326e7ef259a54dfa01fdbb469cabfe7a526a00258cd474efc2a499bb578bfb67089081784f7e3776c0f15dc11535ce03",
          "sha256": "76566a32eac071b58dc85ed90bb24dc9ef2aa64b2cca9920d56a93a5bfb66136",
          "sha1": "f0d7bb9889110a644671b2d13127a19712ebd21e",
          "md5": "ccc115ef567194a7460d9c1ec0555aeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2516.0-sources.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2516.0-sources.jar",
          "size": 17424322,
          "sha512": "96e69b929a381c440257f71598f726dce4c30f3c89ca1691f051ebbc5c36a9c7c765726cbc16d5c347efcaaf7af52c3e27d1137c02ee72ae6e929296178d756a",
          "sha256": "b7c8545e7e6d7d8e1a80558ac28cb2229412f139d360abeae5404295aea0f69b",
          "sha1": "9fed86773b49b8ddbef197a95def442df939a02a",
          "md5": "75f7501970bb2e4597f402cd3cd848ff"
        }
      ]
    }
  ]
}
