{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.3.jar",
          "size": 19760758,
          "sha512": "20eb20b71916cb012d6ccd4287e136fc8954bc298024a0aa9986a0294745901a6a6dfe79e259607bef3bad10156c95737d9be76dbea9483c037945e7fada0115",
          "sha256": "e01821facac9cf95e103d10a728e2780b00d4d0dcf83ff24ffb743d20c2f3430",
          "sha1": "fe1e68c20f80ff2ef8a2cb4b597d80464b9984c6",
          "md5": "9688574381345ea7b085d2c338b9317c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.3.jar",
          "size": 19760758,
          "sha512": "20eb20b71916cb012d6ccd4287e136fc8954bc298024a0aa9986a0294745901a6a6dfe79e259607bef3bad10156c95737d9be76dbea9483c037945e7fada0115",
          "sha256": "e01821facac9cf95e103d10a728e2780b00d4d0dcf83ff24ffb743d20c2f3430",
          "sha1": "fe1e68c20f80ff2ef8a2cb4b597d80464b9984c6",
          "md5": "9688574381345ea7b085d2c338b9317c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.3-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.3-sources.jar",
          "size": 18904037,
          "sha512": "b4991beb8ba9a2b36768780d39f9a9daed40595b9c3efdaf71c925be431e45d84294244a24d74224c1468d507e9d5e02dc703f4fed09517b678b7633cf12a9f5",
          "sha256": "9788c145411c2a5c6dd1a255c3143335469a135c65758a24d2c7c2b6914aa930",
          "sha1": "fe509fd4339513a035d91e24a982ef364b4de292",
          "md5": "bc4b5c62e653441007fddcdb31a6d77f"
        }
      ]
    }
  ]
}
