{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2507.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.1.jar",
          "size": 488253,
          "sha512": "ebcbaec55878d17f46a1dc43dd9ff5feec6877a88f39c571df13358218d75bec9c34ecae0a53859572950185da464414c855a0854b1ff37713c91a094bc763a1",
          "sha256": "ec1b5620c99d6ffa0f7ce45b995228c85fe471286cf1930f77ea36f3080790ba",
          "sha1": "58052dc049118bfd055714f374b1f7752bb5e2b2",
          "md5": "6b6eea065db7171260a2be03304a3790"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.1.jar",
          "size": 488253,
          "sha512": "ebcbaec55878d17f46a1dc43dd9ff5feec6877a88f39c571df13358218d75bec9c34ecae0a53859572950185da464414c855a0854b1ff37713c91a094bc763a1",
          "sha256": "ec1b5620c99d6ffa0f7ce45b995228c85fe471286cf1930f77ea36f3080790ba",
          "sha1": "58052dc049118bfd055714f374b1f7752bb5e2b2",
          "md5": "6b6eea065db7171260a2be03304a3790"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.1-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.1-sources.jar",
          "size": 241277,
          "sha512": "29cbadbc2648b040c3c23f9d74662484a1ac1304dc8ec80de7f7d1ae76caa243e53648a3f42de08acd2d14e20a3d9e625f5c3ba6ca3b3dbb72d0b1438bf8125d",
          "sha256": "d4d667f73e52733e3aea71270089b0673ae01ff4a4900bdb4f3c96920f74ae71",
          "sha1": "e655e9950f3682d0ca130ba69cabf847abde4f25",
          "md5": "85d80b780e1f765473c0565fc1b24140"
        }
      ]
    }
  ]
}
