{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.7.10.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.4.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.4.jar",
          "size": 14279335,
          "sha512": "7f8133a997378ba01c65b624ae3c4b4386ab605a84ad678b50ec97ec766cd449e7828d14d447a1563a21e749e052fb4f11e6f2d718d71a6b7a010964ddad2d8c",
          "sha256": "174c9437464d091d4547d20a51a9198c7c1581cc5d0abd4053608582ba4a6c3f",
          "sha1": "576f972e6799e98be27df06db6575a46dc21d054",
          "md5": "528b7cbb8e110df3ead430ec215ba837"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.4.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.4.jar",
          "size": 14279335,
          "sha512": "7f8133a997378ba01c65b624ae3c4b4386ab605a84ad678b50ec97ec766cd449e7828d14d447a1563a21e749e052fb4f11e6f2d718d71a6b7a010964ddad2d8c",
          "sha256": "174c9437464d091d4547d20a51a9198c7c1581cc5d0abd4053608582ba4a6c3f",
          "sha1": "576f972e6799e98be27df06db6575a46dc21d054",
          "md5": "528b7cbb8e110df3ead430ec215ba837"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.4-sources.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.4-sources.jar",
          "size": 13469699,
          "sha512": "559f3647e8323360262e5f54ae4fc47f57ee3d6895579376eb204def036c6787b4f2331bc44bbc5e9109924f592c14331d3039738841badbe8c781e294979ba9",
          "sha256": "3add4af414fdfe6b63cfb2c709f531e0b488b4c5c4a4e49baaceae5514e3132b",
          "sha1": "171dccf5f7679d340e3ccd4d005e4f6dc88913c4",
          "md5": "d9680bc6dbd359d0e9d03cf5646d5af5"
        }
      ]
    }
  ]
}
