{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2512.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2512.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2512.3.jar",
          "size": 18287886,
          "sha512": "5c9cd9c4d813c7613ffcb3c83b25384f9f9d43978d84d16ebd394f5f4d96d535c9f04453b94404fce288ab171abcaeaacfba14922a2798636e10a7af9822ad62",
          "sha256": "9fe90b00a0a65b908846fd3104c6e018b7e64ef961bc202887edb39feb093e61",
          "sha1": "58282a2f227efedb3c1914e7a7212364328740b8",
          "md5": "c7b4fe2b635fb0a9bcafcf8bdccfaca6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2512.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2512.3.jar",
          "size": 18287886,
          "sha512": "5c9cd9c4d813c7613ffcb3c83b25384f9f9d43978d84d16ebd394f5f4d96d535c9f04453b94404fce288ab171abcaeaacfba14922a2798636e10a7af9822ad62",
          "sha256": "9fe90b00a0a65b908846fd3104c6e018b7e64ef961bc202887edb39feb093e61",
          "sha1": "58282a2f227efedb3c1914e7a7212364328740b8",
          "md5": "c7b4fe2b635fb0a9bcafcf8bdccfaca6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2512.3-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2512.3-sources.jar",
          "size": 17425497,
          "sha512": "aae6ed1f5cbc07ed209f2bf265a84c081c4814129aa48169d7a5a40aac9da60da7885d021dd6ada2b9bcf0e67d62652b8f47202d409bec4c8511b20dde2cd229",
          "sha256": "ce435d458fcd0f5d0da70ee89cfd7b1520c14929847eac8aa6be87613f30d3e5",
          "sha1": "39973f920845efe80b7c9c0ce3b13a9bf40aec20",
          "md5": "6fe6f0e97f13f4c8044533caad65089d"
        }
      ]
    }
  ]
}
