{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.7.2617.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.1.jar",
          "size": 550945,
          "sha512": "670a067456f114d719839d2f883520433a78d1b2370c134c73d4c2f27bc771e8d77baf0a9a20729c9dace19c68a85a8fc4b70cfc7ff8d57c5017258fd4066f82",
          "sha256": "8d709d7670857bc7d53462892d436ce6dc5eaa7988b78716617e1647ea7ad297",
          "sha1": "6341615ca214c8459623e41e30cf83b0a5015fb1",
          "md5": "da6ae2dad4ff2bcde9f28f3d9f81b87b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.1.jar",
          "size": 550945,
          "sha512": "670a067456f114d719839d2f883520433a78d1b2370c134c73d4c2f27bc771e8d77baf0a9a20729c9dace19c68a85a8fc4b70cfc7ff8d57c5017258fd4066f82",
          "sha256": "8d709d7670857bc7d53462892d436ce6dc5eaa7988b78716617e1647ea7ad297",
          "sha1": "6341615ca214c8459623e41e30cf83b0a5015fb1",
          "md5": "da6ae2dad4ff2bcde9f28f3d9f81b87b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.1-sources.jar",
          "size": 256729,
          "sha512": "84b26cf1eacebc5934abe9c30f0766a3163884c11c44a62cdcf4d0605870be8e925afe5ee2aa2b9618ee340f71a9a9b639094337d19f147120087b335798fdd7",
          "sha256": "a8d82715df0ec3ce9d6f32656a696180225fa4905391c42860d6691aff8fe44d",
          "sha1": "e0f6ac42030f19bc52e82ad09de107faf46adfd2",
          "md5": "03b3049b660bc01159fca170670bcf81"
        },
        {
          "name": "factory_api-neoforge-1.21.4-2.2.7.2617.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.7.2617.1-sources.jar",
          "size": 256729,
          "sha512": "84b26cf1eacebc5934abe9c30f0766a3163884c11c44a62cdcf4d0605870be8e925afe5ee2aa2b9618ee340f71a9a9b639094337d19f147120087b335798fdd7",
          "sha256": "a8d82715df0ec3ce9d6f32656a696180225fa4905391c42860d6691aff8fe44d",
          "sha1": "e0f6ac42030f19bc52e82ad09de107faf46adfd2",
          "md5": "03b3049b660bc01159fca170670bcf81"
        }
      ]
    }
  ]
}
