{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.7.10.2504.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.7.10.2504.0.jar",
          "url": "legacy-neoforge-1.21.3-1.7.10.2504.0.jar",
          "size": 14239714,
          "sha512": "8ff51e48b73045bf55ed8c940736dbec026053dac99d3fe2f0c857cdcb66b888f422dd9269b7e7864f6d3bd99ce7d988d95ac839161f3df9fd05c0e0fdda10be",
          "sha256": "f69914ede255c5507f0812d4995bfda131bf500ffc250bfdf5dd8d50f7e5df4c",
          "sha1": "6197d7f33461a358baaaf39caca16325f8d8dcb3",
          "md5": "29598a6d08c8da267152bd5aa1090afc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.7.10.2504.0.jar",
          "url": "legacy-neoforge-1.21.3-1.7.10.2504.0.jar",
          "size": 14239714,
          "sha512": "8ff51e48b73045bf55ed8c940736dbec026053dac99d3fe2f0c857cdcb66b888f422dd9269b7e7864f6d3bd99ce7d988d95ac839161f3df9fd05c0e0fdda10be",
          "sha256": "f69914ede255c5507f0812d4995bfda131bf500ffc250bfdf5dd8d50f7e5df4c",
          "sha1": "6197d7f33461a358baaaf39caca16325f8d8dcb3",
          "md5": "29598a6d08c8da267152bd5aa1090afc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.7.10.2504.0-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.7.10.2504.0-sources.jar",
          "size": 13444016,
          "sha512": "b606efc3dd0b1799f0e9bd89e108d95363074c7e0c0a76a429441923f412f4c1588d73817a49febce69fc1cac9ab5175937f6d59ef9167ee3137ddc0fbd0aabb",
          "sha256": "e30c045986e96f05921569bccb1a3881a6fd7b85d129e0dd7b18a7464c832785",
          "sha1": "f9e66d2e5f5464c828faa805fecdb2db31d321fe",
          "md5": "f1c2147e510ba7933108a0366a88b79a"
        }
      ]
    }
  ]
}
