{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.2509.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2509.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2509.0.jar",
          "size": 526881,
          "sha512": "5e1600771bcb64ef5f499bb0faf9e4e90ea7ffebc1c487b7a783dd4c53e58952e68fda5caeeeea19cdd4d432c32830d08714d997e849b71ff02684e819299610",
          "sha256": "4a3f9d9ad15da7ec33aac3331adeec6ff934449ccd69fb41ea50e04ad88dd604",
          "sha1": "23ec26a89099099f22ffa4a742ffef2bf5b0caee",
          "md5": "347394c9d52f70109d0d0af77b3669b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2509.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2509.0.jar",
          "size": 526881,
          "sha512": "5e1600771bcb64ef5f499bb0faf9e4e90ea7ffebc1c487b7a783dd4c53e58952e68fda5caeeeea19cdd4d432c32830d08714d997e849b71ff02684e819299610",
          "sha256": "4a3f9d9ad15da7ec33aac3331adeec6ff934449ccd69fb41ea50e04ad88dd604",
          "sha1": "23ec26a89099099f22ffa4a742ffef2bf5b0caee",
          "md5": "347394c9d52f70109d0d0af77b3669b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2509.0-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2509.0-sources.jar",
          "size": 246543,
          "sha512": "1c6a90eaf60e105790796254a5f182e239e00c275523c33237c9465b763b19e83831bc45faeecd7ec094425da9744aad4e1d552410e410b29a2b7333a19065c8",
          "sha256": "fe1541a96ddb969aa61b8b6b4ad1d8f7212896aaa7e3bfd2bf037051142072c9",
          "sha1": "c9c6e798fb2352755f3c9e9fe7c532b9c982d37f",
          "md5": "59d542e1af1324bd8c0f38a62d871718"
        }
      ]
    }
  ]
}
