{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.10.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.10.jar",
          "size": 382544,
          "sha512": "630f80573c21f4f6d4b70bdcc1cf94e2ddfebb635d9dd8b73cfbfbbcc08b5ca8d6629e9051e62990d899c8b2bb9f316784cfa0e25f892633269ff80292530243",
          "sha256": "3d8de08084136ab2bf95906b99e69a55503080a7967c3f41f46c4c45539b67c0",
          "sha1": "4eab9e2f5ef451d16378d019a66bd5e0156eefa0",
          "md5": "71592e5fb95587d7867d8c6614a4a7d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.10.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.10.jar",
          "size": 382544,
          "sha512": "630f80573c21f4f6d4b70bdcc1cf94e2ddfebb635d9dd8b73cfbfbbcc08b5ca8d6629e9051e62990d899c8b2bb9f316784cfa0e25f892633269ff80292530243",
          "sha256": "3d8de08084136ab2bf95906b99e69a55503080a7967c3f41f46c4c45539b67c0",
          "sha1": "4eab9e2f5ef451d16378d019a66bd5e0156eefa0",
          "md5": "71592e5fb95587d7867d8c6614a4a7d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.10-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.10-sources.jar",
          "size": 198649,
          "sha512": "263ab906033d35dd70e9e8e4711c851a44892fdf83f97d9a330107c1b181b41600701571037a44616c804354b6affe310590093d0b29ce2987486adc8319c1f1",
          "sha256": "2f2c93ad0cc2df033594ad48cbc8df7471f94d24231ec08c6e4b288faf4a3b61",
          "sha1": "d898c6d2b87426367165d71bbbf5051a32eb2b01",
          "md5": "10d49198292e270b087ed541a717dd94"
        }
      ]
    }
  ]
}
