{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "size": 401919,
          "sha512": "55730daad5eaed1eb5f038bb996b718ce6c5ce9bbd2919f1e70fd244215c33f01f47cf4ce03de978b423019c90592eaae051c36317e5f9fa34e428b29a9f9792",
          "sha256": "310cce49d35ee81530ceedbf1512635e1c046c67e87333033d448bdd3b8487e7",
          "sha1": "9f5343864b9f4102a31d01961223c3bdd5a06b41",
          "md5": "69c9d3faef41c20497055aaa2cebbab7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "size": 401919,
          "sha512": "55730daad5eaed1eb5f038bb996b718ce6c5ce9bbd2919f1e70fd244215c33f01f47cf4ce03de978b423019c90592eaae051c36317e5f9fa34e428b29a9f9792",
          "sha256": "310cce49d35ee81530ceedbf1512635e1c046c67e87333033d448bdd3b8487e7",
          "sha1": "9f5343864b9f4102a31d01961223c3bdd5a06b41",
          "md5": "69c9d3faef41c20497055aaa2cebbab7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.24-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.24-sources.jar",
          "size": 199309,
          "sha512": "a6df37698f62b2a879fca211da87ceb566813faa5af1b3bd0fe4fca5c370270651401bc44716f33e3637c87e8512dd93a6b66b890514a18f36a2eadbec0ef7aa",
          "sha256": "276bf32f730a70de928be4fe4b6cbe13d940338c157dd9c74bee2e171ce2e71d",
          "sha1": "43180c0cdac35a834078cecb7e92bba1b5e4ef6a",
          "md5": "098695f30c6d1f662cf84100775f7c85"
        }
      ]
    }
  ]
}
