{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "size": 401921,
          "sha512": "74641a982315b4dd3392728188d90beecb2df996c18eeaedb4316db3b5d9b747a8a989564be73570889fc767be1fd6bfbde1a5177b9ab0d144de27a81ae9d013",
          "sha256": "669755000b1b524c1e901f1cf97981bb6c198d31013ff99790f50a65e30e06e7",
          "sha1": "a3f1f4e5820557e4af63b06e01fe3b902480e7cf",
          "md5": "88941769aa71dc2f52f2c836c62ce072"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.24.jar",
          "size": 401921,
          "sha512": "74641a982315b4dd3392728188d90beecb2df996c18eeaedb4316db3b5d9b747a8a989564be73570889fc767be1fd6bfbde1a5177b9ab0d144de27a81ae9d013",
          "sha256": "669755000b1b524c1e901f1cf97981bb6c198d31013ff99790f50a65e30e06e7",
          "sha1": "a3f1f4e5820557e4af63b06e01fe3b902480e7cf",
          "md5": "88941769aa71dc2f52f2c836c62ce072"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.24-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.24-sources.jar",
          "size": 199310,
          "sha512": "207a6f61c337a93fcb55560394734bcf43a89aaf9b1ddc46652994188652e671467453b9c84ae5672e0bbcde7cb725056058db4b558ff0f1f91217a9150b7643",
          "sha256": "7593ba9d0a3b7cf20882857214937ff4b0143935e4f8065a321de4823f11a908",
          "sha1": "4fa7f1ac82529a8e835866bcee1ffbde10b85442",
          "md5": "092d15e2d110f4a84af0ad0b65980b1a"
        }
      ]
    }
  ]
}
