{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.8.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.8.jar",
          "size": 534177,
          "sha512": "c03a5486f0754167a5a8e892432e0e054457a590509630af03165869ff8c83c1dedaf2b7bc414953f0e83b59e69a3da4d6e0c761a1acaa445a34c1f1e8af015f",
          "sha256": "bd71cde902427b4374a5c098944c33b97d7aa90952d622ff961efeb98ef9ea15",
          "sha1": "b7213bb2ea1e982f25784bebbff6b30b71f9f4c9",
          "md5": "83877a25f1aa4c58890011d352507ec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.8.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.8.jar",
          "size": 534177,
          "sha512": "c03a5486f0754167a5a8e892432e0e054457a590509630af03165869ff8c83c1dedaf2b7bc414953f0e83b59e69a3da4d6e0c761a1acaa445a34c1f1e8af015f",
          "sha256": "bd71cde902427b4374a5c098944c33b97d7aa90952d622ff961efeb98ef9ea15",
          "sha1": "b7213bb2ea1e982f25784bebbff6b30b71f9f4c9",
          "md5": "83877a25f1aa4c58890011d352507ec1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.8-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.8-sources.jar",
          "size": 256826,
          "sha512": "e2653a53c4c16528106836f0dd0cfee464f3c330ddd57fd1d81965f8f1c599c5c634f94c8a4c8d2b0dfa78208f2595cbb84224ce07c3be4355b774469167faf5",
          "sha256": "c38a4f229099b782dcfc63ec578e91b79f239e4101609c2bb465b3cebc4eec50",
          "sha1": "6f7075aab380df67091cfde47d3aecdfa507f0d3",
          "md5": "6bc0fde5a7fd70379c5dd4ce384bd4a5"
        },
        {
          "name": "factory_api-neoforge-1.20.4-2.2.8-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.8-sources.jar",
          "size": 256826,
          "sha512": "e2653a53c4c16528106836f0dd0cfee464f3c330ddd57fd1d81965f8f1c599c5c634f94c8a4c8d2b0dfa78208f2595cbb84224ce07c3be4355b774469167faf5",
          "sha256": "c38a4f229099b782dcfc63ec578e91b79f239e4101609c2bb465b3cebc4eec50",
          "sha1": "6f7075aab380df67091cfde47d3aecdfa507f0d3",
          "md5": "6bc0fde5a7fd70379c5dd4ce384bd4a5"
        }
      ]
    }
  ]
}
