{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2508.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2508.0.jar",
          "size": 512761,
          "sha512": "5a3c30c34b42aeb3c9c4b5bfc0f53a5ad3f9f06087d6b81fd4531ac0263523956f0a241e5881fdc4b3f5e85547db5e562082a1f274a9de1e280857e7ec4debe7",
          "sha256": "e73a2886aa8bef8e9d7055fdfae678376cf768fa75ac2309f7e9e0643fd83663",
          "sha1": "76f155d99e57af888bddeb9f358b1cb33b5f66cf",
          "md5": "13116d989e831b5655254ff10c8ffefd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2508.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2508.0.jar",
          "size": 512761,
          "sha512": "5a3c30c34b42aeb3c9c4b5bfc0f53a5ad3f9f06087d6b81fd4531ac0263523956f0a241e5881fdc4b3f5e85547db5e562082a1f274a9de1e280857e7ec4debe7",
          "sha256": "e73a2886aa8bef8e9d7055fdfae678376cf768fa75ac2309f7e9e0643fd83663",
          "sha1": "76f155d99e57af888bddeb9f358b1cb33b5f66cf",
          "md5": "13116d989e831b5655254ff10c8ffefd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2508.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2508.0-sources.jar",
          "size": 249535,
          "sha512": "483ffc8dcc2fe383beca9bb28a2967546406ac3e912e375aeb21db720abcb97c75792118ed70da150a7bdb06368d5cd2310fc7a0606f0e5125b976333c450fdd",
          "sha256": "cafab580fcf21c0d719f9ad6511fe23ee00ac7b64262491411923bbbe7b1b6e2",
          "sha1": "5ae47f21b62f0d1258c99a056d24052d34dd9eed",
          "md5": "47e99287e98df14700f662b6bf38d34b"
        }
      ]
    }
  ]
}
