{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2518.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2518.1.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2518.1.jar",
          "size": 19768428,
          "sha512": "ab7faa4735ea22d1096ecae715894a0c7d8e95bd994268fa4394700b08d480f500619407dbcfc0aa8f76460167c9bf0ccc73464a8c199b04cd4aef4cd4a1597b",
          "sha256": "c3ac470d4a077e6500a1b5dc98aa68df8ffc62e692fe511399ac15d6d1363993",
          "sha1": "e435ef3300f56ea60aec2072cdfdd992f0d6e81c",
          "md5": "2b1f709ca3c6afe75fc7870409f127d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2518.1.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2518.1.jar",
          "size": 19768428,
          "sha512": "ab7faa4735ea22d1096ecae715894a0c7d8e95bd994268fa4394700b08d480f500619407dbcfc0aa8f76460167c9bf0ccc73464a8c199b04cd4aef4cd4a1597b",
          "sha256": "c3ac470d4a077e6500a1b5dc98aa68df8ffc62e692fe511399ac15d6d1363993",
          "sha1": "e435ef3300f56ea60aec2072cdfdd992f0d6e81c",
          "md5": "2b1f709ca3c6afe75fc7870409f127d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2518.1-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2518.1-sources.jar",
          "size": 18911610,
          "sha512": "d4410d3371f65b47a3b822971334c421de6e1405ed046871bcb94ea4ba122edf9ba1c188353192781c389c64f6ccdc97f0ead6f45eaae5074a5c4f1afc0038d3",
          "sha256": "f906bd0bf5a0d71e5d385da72733dfd5190b0bd94e3bc515453d9e9d2b8dfb54",
          "sha1": "af09b3ffd0f4aa6ca7095fd808ff02fef12c8405",
          "md5": "7b9b6c0ec2368d4aaa9ded3cd09a5e86"
        }
      ]
    }
  ]
}
