{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.5.jar",
          "size": 714139,
          "sha512": "84527148d1d76042e21232aadd0c5a5175c857699cdc7fd7b60babc364438035a292d2e2b4a545e535f21ad117341fe6b55fdf08088b08f53c78c48ac2b350d3",
          "sha256": "a29ea7e9084dc53a7c6b8a9ca0e55e08137ef4b011a1fc3c9925c7a7f594f3fc",
          "sha1": "6f8865ee4f25dfe91fa3672d49feba6269d6f112",
          "md5": "bd162240da9b59029812175e07838893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.5.jar",
          "size": 714139,
          "sha512": "84527148d1d76042e21232aadd0c5a5175c857699cdc7fd7b60babc364438035a292d2e2b4a545e535f21ad117341fe6b55fdf08088b08f53c78c48ac2b350d3",
          "sha256": "a29ea7e9084dc53a7c6b8a9ca0e55e08137ef4b011a1fc3c9925c7a7f594f3fc",
          "sha1": "6f8865ee4f25dfe91fa3672d49feba6269d6f112",
          "md5": "bd162240da9b59029812175e07838893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.5-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.5-sources.jar",
          "size": 254171,
          "sha512": "a455f865a6e8a662d01aea5c41e3a0e16fe283a6813fb3a384a2301667ad9f7029172f3eebf00e04120128ef2aac8cd2db6c9687ae2ac50aee749c79b3e0ab94",
          "sha256": "2aff75305fd0cadff6d4893708f90eff3555f76e2b30528e0dd416ad9efd2d36",
          "sha1": "3b83332bb09fd88ae266ddb7cf6ffc8024f094b0",
          "md5": "32c00885b3d48627b7e3ab85f1c36604"
        }
      ]
    }
  ]
}
