{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.3.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.3.jar",
          "size": 452089,
          "sha512": "6a33b06e87799723609872e43ee25fe38c11b18d9a9489a63ff156fb6a1194befa8aac9fc12a3d241355856857ef3cf2eab6729696edee4e5cd1ce2292037e78",
          "sha256": "10d38449b3405ba70fcb00c7c0cf51a20d6ef581870bc4541a250fe64cb05076",
          "sha1": "c98d9757c8114b6552a96c1d9d9b62e1c85e9e42",
          "md5": "bd54a94d1f8a3d80667df439c6178d3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.3.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.3.jar",
          "size": 452089,
          "sha512": "6a33b06e87799723609872e43ee25fe38c11b18d9a9489a63ff156fb6a1194befa8aac9fc12a3d241355856857ef3cf2eab6729696edee4e5cd1ce2292037e78",
          "sha256": "10d38449b3405ba70fcb00c7c0cf51a20d6ef581870bc4541a250fe64cb05076",
          "sha1": "c98d9757c8114b6552a96c1d9d9b62e1c85e9e42",
          "md5": "bd54a94d1f8a3d80667df439c6178d3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.3-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.3-sources.jar",
          "size": 231252,
          "sha512": "99a841b4d4f1fa88f759c44bc389315aa1b5a6b536729d1b2dbd4fab237bbf9cf73d527d51d6d0b97f25678185914fe6c9ae8f15b98bffeb6ebb8a9be5ce5068",
          "sha256": "dd2fee227a1363b26fa319e409306dc2e0dc705dd16164d6cf307f046892c41a",
          "sha1": "cde5f2ebda5fd35014d91eef789ff41ef67afeb0",
          "md5": "36062da3a7f0f4c52a1a7798a3a5db77"
        }
      ]
    }
  ]
}
