{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2502.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.12.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.12.jar",
          "size": 441201,
          "sha512": "4409357f138537eae922ed9f39d72ab5125427616378cf62366f992e8c16676a47c6342ec8bb503c25cd50645c25a54c84adfad1ac2e1fafb1ddf475caf98fbe",
          "sha256": "d0a58d519385096787786edf9863963ea8e30c504aec62e3b9f78e82f9bf92f7",
          "sha1": "0949792dfa03ac51d908d0310ac7384e8c34f4b1",
          "md5": "6f968b0539095883453328101ba8a6f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.12.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.12.jar",
          "size": 441201,
          "sha512": "4409357f138537eae922ed9f39d72ab5125427616378cf62366f992e8c16676a47c6342ec8bb503c25cd50645c25a54c84adfad1ac2e1fafb1ddf475caf98fbe",
          "sha256": "d0a58d519385096787786edf9863963ea8e30c504aec62e3b9f78e82f9bf92f7",
          "sha1": "0949792dfa03ac51d908d0310ac7384e8c34f4b1",
          "md5": "6f968b0539095883453328101ba8a6f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.12-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.12-sources.jar",
          "size": 227745,
          "sha512": "a4aa0ca990e4ec3cadd86bb4567c0a58ca363b9112eeda5d40b574dcb3e00f24c0be5642dc80be67ed12848d1177810b7fc65ae2fe48e29b0f30239091f048e1",
          "sha256": "95e1bfbcd39c457104d127d849ff478923674a3ea56b3b484cd2f9ce4a3b4306",
          "sha1": "11d97bac4903153d96599143ee6257c35fe7937b",
          "md5": "8e13e0c4e776e40f3497b1b053dc244a"
        }
      ]
    }
  ]
}
