{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2502.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.12.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.12.jar",
          "size": 467274,
          "sha512": "0432ab2e9a93cc927ae2c65159babfc0bbd7ba835a0ef74634eed23059accdf6a35063b5d49c7f2497788fcae4927ce523c5064c0a6c2808227051ecdbdd4507",
          "sha256": "c6b7b14a224e520aa104aa9eca60bdb67183278175287a6f75754e3e8eff73be",
          "sha1": "69103305790858f0f24e8b461e885be91c4d301c",
          "md5": "962a079ee44d6c178d20b2b90273d423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.12.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.12.jar",
          "size": 467274,
          "sha512": "0432ab2e9a93cc927ae2c65159babfc0bbd7ba835a0ef74634eed23059accdf6a35063b5d49c7f2497788fcae4927ce523c5064c0a6c2808227051ecdbdd4507",
          "sha256": "c6b7b14a224e520aa104aa9eca60bdb67183278175287a6f75754e3e8eff73be",
          "sha1": "69103305790858f0f24e8b461e885be91c4d301c",
          "md5": "962a079ee44d6c178d20b2b90273d423"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.12-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.12-sources.jar",
          "size": 229535,
          "sha512": "945131e38eb3931c4b9fce978320a50fa77df50934ae56219f098219d47d74441ec55ee59b7a7a55a401aceb32343c5e3863640bbc5d8ffdcb0aa5c2a6cedc1d",
          "sha256": "a7f7d96655f61c2d825b52432f9020f226fb13d9dcac81fb2d917d3430ba9373",
          "sha1": "143ee9ac0d3429e4b743d6c238d7d5c3b45d64fc",
          "md5": "c4959212930b9f10952bb1e865aa33ce"
        }
      ]
    }
  ]
}
