{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2504.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.0.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.0.jar",
          "size": 14220057,
          "sha512": "c08e215356b4a3cfa15d73486aedcb09d46fd966aeb5881cb6325fd407cd745be7f89baf776275d2905f0d003b82f939e4a127038ea2b0cfec43e3feb34630e1",
          "sha256": "e078a5a1adb6357e7cd33e4cc358505fb9ed42cf5909c99b9efad91919d5c39b",
          "sha1": "686cd771f407e4be1868cc97973b85fc4030c4a3",
          "md5": "f8d4a60ecfb4207b21a08dde2b52982d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.0.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.0.jar",
          "size": 14220057,
          "sha512": "c08e215356b4a3cfa15d73486aedcb09d46fd966aeb5881cb6325fd407cd745be7f89baf776275d2905f0d003b82f939e4a127038ea2b0cfec43e3feb34630e1",
          "sha256": "e078a5a1adb6357e7cd33e4cc358505fb9ed42cf5909c99b9efad91919d5c39b",
          "sha1": "686cd771f407e4be1868cc97973b85fc4030c4a3",
          "md5": "f8d4a60ecfb4207b21a08dde2b52982d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.0-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.0-sources.jar",
          "size": 13443733,
          "sha512": "d8ae26ba2cccc45de354225922363906901e95dd26bd5ea5ae9951c9d890a66e129e9fc7996f91ffa1ed51e877bd54ef738b61ee4d76c19976dfa0e948aa5940",
          "sha256": "a871c39bedc0cf77349bce40b12c9e29d7ab4cd5cbc885b711af78fb6f49e851",
          "sha1": "3fba6f6e5136390bf3e34434e4c61bd571fbaa74",
          "md5": "80b0882f58fb83e1e6b0f24e4700d81e"
        }
      ]
    }
  ]
}
