{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2508.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.1.jar",
          "size": 491893,
          "sha512": "a66008ab52211a61031b36f9e682d6c01dea09179f882e970cf9d956e91e2e3aadbbe767cacb936706c35cdde954268e30d493d7de2279c1cf76f4ab0103d2ac",
          "sha256": "8f79709dd321d3c377ea002fd81f76792eaa89b1689fb6131ed923ae03912b5e",
          "sha1": "5d827f11f8189bdc52ef0a48e86e1eb3e249edd4",
          "md5": "7dcc500d10c7cf5e73e1e79d6b97f132"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.1.jar",
          "size": 491893,
          "sha512": "a66008ab52211a61031b36f9e682d6c01dea09179f882e970cf9d956e91e2e3aadbbe767cacb936706c35cdde954268e30d493d7de2279c1cf76f4ab0103d2ac",
          "sha256": "8f79709dd321d3c377ea002fd81f76792eaa89b1689fb6131ed923ae03912b5e",
          "sha1": "5d827f11f8189bdc52ef0a48e86e1eb3e249edd4",
          "md5": "7dcc500d10c7cf5e73e1e79d6b97f132"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.1-sources.jar",
          "size": 248155,
          "sha512": "3cf6d1a8d00b96bd4380ce0862b91715daad331e8cf3993f3b6122211d76118e59ae226b67d624e83cdfd01a537caf87d10e38ba328ca49a58d1e308f6778e2a",
          "sha256": "c209882fa7255e3f66365052c9fd61d47466d95d8c3042aab41b8c47d711597d",
          "sha1": "e5fd359fa13ce3e193b340205fcfdc39bc1e25f2",
          "md5": "6dd834bcedcdbd313b9ec326fa9b414b"
        }
      ]
    }
  ]
}
