{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.20.4-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.1+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.20.4-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.20.4-1.1.2516.3.jar",
          "size": 638534,
          "sha512": "52c86d853ad3f9531ff8d1ced312c93ea7b67161d76cfad6f0f1fa1b5590675ddfec37656fdbdb3d59afc806c911522ce1fe14d56580c76946c87272988e2da3",
          "sha256": "767c3295c7b128999f704bae2d7533adb96eb41f85c750c25b902a8c5ad90bbd",
          "sha1": "ae625f4016959ebed0290d4fd90b3c081956ea43",
          "md5": "ec09d42d77a6f750b29956f18f240212"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.1+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric",
          "version": {
            "requires": "17.3.1.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.20.4-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.20.4-1.1.2516.3.jar",
          "size": 638534,
          "sha512": "52c86d853ad3f9531ff8d1ced312c93ea7b67161d76cfad6f0f1fa1b5590675ddfec37656fdbdb3d59afc806c911522ce1fe14d56580c76946c87272988e2da3",
          "sha256": "767c3295c7b128999f704bae2d7533adb96eb41f85c750c25b902a8c5ad90bbd",
          "sha1": "ae625f4016959ebed0290d4fd90b3c081956ea43",
          "md5": "ec09d42d77a6f750b29956f18f240212"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.20.4-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.20.4-1.1.2516.3-sources.jar",
          "size": 583103,
          "sha512": "680a627da072ba7ecf8bd27c352ba47458741a74ff0f145c43499ebe819da2776754bbc9dd21b4602b55b20c6161a890d8984076e2de12121762e6d1fdbd7f6e",
          "sha256": "d229e4ffedea6dc4a7c44af1d397ea15f36bab2ccce07241b7b224cbd6722121",
          "sha1": "26661e2385d56ab58bd5c8deebc1f969aac49155",
          "md5": "0235d0c8d23d006992ac0ceb14fbf9c3"
        }
      ]
    }
  ]
}
