{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.1-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2516.5.jar",
          "size": 544335,
          "sha512": "4ffeb6eed8ea6e554bb53d62989ec1cf5d4d70cac56f4f98b1697c984ad0f53757902e661c04e933b7fd8364ec207582050eeb40ae6f7a61fcc3b2731377a803",
          "sha256": "7e924d95dfae7d436b84d0defe108c3a19f16d64645e38502d9236d34ea2e441",
          "sha1": "dc9b0fa6d3d35bbbde1db0184f2316d7b17fd6d3",
          "md5": "583f850bd42fd6283f620e7ab1d101e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2516.5.jar",
          "size": 544335,
          "sha512": "4ffeb6eed8ea6e554bb53d62989ec1cf5d4d70cac56f4f98b1697c984ad0f53757902e661c04e933b7fd8364ec207582050eeb40ae6f7a61fcc3b2731377a803",
          "sha256": "7e924d95dfae7d436b84d0defe108c3a19f16d64645e38502d9236d34ea2e441",
          "sha1": "dc9b0fa6d3d35bbbde1db0184f2316d7b17fd6d3",
          "md5": "583f850bd42fd6283f620e7ab1d101e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2516.5-sources.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2516.5-sources.jar",
          "size": 252345,
          "sha512": "e0d0c0e7d607fe825dd5f39555d68d307074311e066e7c2c1b59582aae329178ebafe0a7ddfbdf8080b7d041da0d653725476c9e7501c54878adab0b336f4204",
          "sha256": "02a874d86100f36095ce0da382a6b187d71ebe5096faf941eb54cfc9e1d8fe72",
          "sha1": "68d5233da959bdf6c0da43dcb7dbb02bc9169371",
          "md5": "962e1df94708db48213b411db9a4d386"
        }
      ]
    }
  ]
}
