{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.10-1.8.5.2541.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.10-2.2.6.2541.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.8.5.2541.0.jar",
          "url": "legacy-neoforge-1.21.10-1.8.5.2541.0.jar",
          "size": 20020186,
          "sha512": "ec988097ed003ee907f70bfa5497086e1417fe56a90d32116b3adb82c86521db37762127a2d16fa9191b187f5f3519bbb3a553e0ff532f1d40caa90c4cf16956",
          "sha256": "16406bf4c2fd9680a88f804fedcced5246179b4f9d5605a2702ba6057cb3e084",
          "sha1": "edc6bfdabcfdb793a0eb5fb542ecfeecd9a863c0",
          "md5": "0bceeb26f0939a8a33316cae8222c21d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.10-2.2.6.2541.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.8.5.2541.0.jar",
          "url": "legacy-neoforge-1.21.10-1.8.5.2541.0.jar",
          "size": 20020186,
          "sha512": "ec988097ed003ee907f70bfa5497086e1417fe56a90d32116b3adb82c86521db37762127a2d16fa9191b187f5f3519bbb3a553e0ff532f1d40caa90c4cf16956",
          "sha256": "16406bf4c2fd9680a88f804fedcced5246179b4f9d5605a2702ba6057cb3e084",
          "sha1": "edc6bfdabcfdb793a0eb5fb542ecfeecd9a863c0",
          "md5": "0bceeb26f0939a8a33316cae8222c21d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.8.5.2541.0-sources.jar",
          "url": "legacy-neoforge-1.21.10-1.8.5.2541.0-sources.jar",
          "size": 19065523,
          "sha512": "f146631db3a1d0c55a57ab6b799e289b78b9425d74d416ac9b5ad1c23586493a87d55643e471dbb04d649c39e65e1b9e6e92d1b313466eb265912d15dab01928",
          "sha256": "d0a4b44c24ab241be9dbc788d9ad25d52102121e7b327e408f433f705b782074",
          "sha1": "b1ec17e3b20443a39e2b78acb5cdc8d4ab27e7d6",
          "md5": "c88787a04ebd68e28fab73cdaf68ca26"
        }
      ]
    }
  ]
}
