{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.20.4-1.7.10.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2506.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2506.0.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2506.0.jar",
          "size": 14350974,
          "sha512": "ae788e6230070801ef1b81930384adb427081d98712fc28d6335b25bfa88a06e316ba3b26827c7bb7f6a413f2cb8fc3d5ed01096ed35a3f729e0dd56fa42ed64",
          "sha256": "a532c016249186c75fba95101807b5b638b79356afac345d4b3653ac981d6e3b",
          "sha1": "c1329d0d8dd245fd921f7a620ede3a0315e362b4",
          "md5": "4c15df98cfbab3806787fb50fc0d5109"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2506.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2506.0.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2506.0.jar",
          "size": 14350974,
          "sha512": "ae788e6230070801ef1b81930384adb427081d98712fc28d6335b25bfa88a06e316ba3b26827c7bb7f6a413f2cb8fc3d5ed01096ed35a3f729e0dd56fa42ed64",
          "sha256": "a532c016249186c75fba95101807b5b638b79356afac345d4b3653ac981d6e3b",
          "sha1": "c1329d0d8dd245fd921f7a620ede3a0315e362b4",
          "md5": "4c15df98cfbab3806787fb50fc0d5109"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2506.0-sources.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2506.0-sources.jar",
          "size": 13527758,
          "sha512": "7bee7a8a3bbde47b7db52fba4ea721a9e27ccd4394a45fe56707fde4fe3048ff4f7767ffd900b9639c3306f84eeda3387b12b9c1ef8dffbb6805badf91e66e1c",
          "sha256": "7dce3e241258eb15318fd442c1f5ce7aea82e329daf99cdb81a9cf439cbea69f",
          "sha1": "b0f8c9a0d553d652ab610bf1733511f0c8010aed",
          "md5": "5207d66b2070bb160c91dc408a15d22a"
        }
      ]
    }
  ]
}
