{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2518.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2518.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2518.0.jar",
          "size": 717299,
          "sha512": "44f709cd833ec7415b069a0ba080b4fe090ffa6b9e49fe245a284fa022abc15cd900492e638ebd56c96fdc13394e2c0d2f02f1e1d6c105a51f4bc596266cbd12",
          "sha256": "a70c93ed9acc4372916fcc7c7d4b474d3b4f95d04a7fe084d391eb68e8e7b949",
          "sha1": "b82c714044e33a28c81fb587a84b939974e36053",
          "md5": "c3047f22427750eaac1bcd88be7a4462"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2518.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2518.0.jar",
          "size": 717299,
          "sha512": "44f709cd833ec7415b069a0ba080b4fe090ffa6b9e49fe245a284fa022abc15cd900492e638ebd56c96fdc13394e2c0d2f02f1e1d6c105a51f4bc596266cbd12",
          "sha256": "a70c93ed9acc4372916fcc7c7d4b474d3b4f95d04a7fe084d391eb68e8e7b949",
          "sha1": "b82c714044e33a28c81fb587a84b939974e36053",
          "md5": "c3047f22427750eaac1bcd88be7a4462"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2518.0-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2518.0-sources.jar",
          "size": 254761,
          "sha512": "226cd0ded2e0256dc84226920e31a991ca0186250f93de3a4ec68c50c17b983510015d7299289922cf5f028b7acac91d832df48023277d19a4bbf210bf638b8e",
          "sha256": "3f505c30cb4f56e49b184d3171f0cfafe439556fd303a51075a477a6ddf49c43",
          "sha1": "fd4c2a40d4bcc7feaca64918ecd9c00ef676878d",
          "md5": "f796268a7442ad3357624deec0faa0e7"
        }
      ]
    }
  ]
}
