{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2515.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2515.0.jar",
          "size": 690793,
          "sha512": "d62a224a21741ef65aaeeb11b540c7b53472cbf8c99b0c4ce81956a3d6e3aa8e2bf3a6a977f4dfadd2f7def45b8a6c8f54eb094aa10f76fc445989b1718c73f0",
          "sha256": "d7615a076200fc8f31e4afb31289bd87461dd5d1f59d1f9b4ad6ee04bc65b49b",
          "sha1": "bfc8061e1b87e09d6687e962b9988e0d6b98f528",
          "md5": "e81dc9be89a11938224a5b8dc22b2245"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2515.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2515.0.jar",
          "size": 690793,
          "sha512": "d62a224a21741ef65aaeeb11b540c7b53472cbf8c99b0c4ce81956a3d6e3aa8e2bf3a6a977f4dfadd2f7def45b8a6c8f54eb094aa10f76fc445989b1718c73f0",
          "sha256": "d7615a076200fc8f31e4afb31289bd87461dd5d1f59d1f9b4ad6ee04bc65b49b",
          "sha1": "bfc8061e1b87e09d6687e962b9988e0d6b98f528",
          "md5": "e81dc9be89a11938224a5b8dc22b2245"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2515.0-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2515.0-sources.jar",
          "size": 254701,
          "sha512": "b90b0ebed0a472b114c56c4384ce8729b7176915ceb1a949e2daaa1bada47bb731c5204912a7e38d38c0349b78bfa870fb9654f3b3aa3ec8c6ca4817260ede41",
          "sha256": "d1f03b7395481b613551c4bf64719a3606f4431f8c7e43100e0938070cdbe8a5",
          "sha1": "0703b72ca7f0cbb76618aa27d779d0444b2d2202",
          "md5": "4850af7efea530c467daa273caa00181"
        }
      ]
    }
  ]
}
