{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2504.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2504.7.jar",
          "url": "factory_api-forge-1.21.3-2.2.2504.7.jar",
          "size": 478380,
          "sha512": "e891b6b60d11bbcd06c56a991ccc5a843a2abc300ae791e50d9fd93594d9239c8a2c5cdcc9a715970c6d1e9e6608d880e0053d8a8b7ccea29416d6ed04785a06",
          "sha256": "9b02a2a7e6de566192b28b0119871d1bd04ecda6f8400d33c2facdb529176be0",
          "sha1": "4b1f3ae0de238e0efb051b9b80c741702d1fca76",
          "md5": "1bd5c8dc08a3f0e1d9d45156dbb6ebbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2504.7.jar",
          "url": "factory_api-forge-1.21.3-2.2.2504.7.jar",
          "size": 478380,
          "sha512": "e891b6b60d11bbcd06c56a991ccc5a843a2abc300ae791e50d9fd93594d9239c8a2c5cdcc9a715970c6d1e9e6608d880e0053d8a8b7ccea29416d6ed04785a06",
          "sha256": "9b02a2a7e6de566192b28b0119871d1bd04ecda6f8400d33c2facdb529176be0",
          "sha1": "4b1f3ae0de238e0efb051b9b80c741702d1fca76",
          "md5": "1bd5c8dc08a3f0e1d9d45156dbb6ebbd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2504.7-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2504.7-sources.jar",
          "size": 237043,
          "sha512": "63ec58e6ad8b42ad186b7248d5e5511bf7ce41037da7192ef0c4975e316aaa9dd0e235c0d4ac5bbee7e4721d35f71f75a5d116f51b3d89498e102576d1c050a9",
          "sha256": "acd9061b27c09c09b9d5978b5abda207d45d09ac7f9abb59118e6345a524d7a3",
          "sha1": "c4ef657fc2719c315747e9e1bca244a9911e8b57",
          "md5": "fba470d8af67b6035ba2788b6709120b"
        }
      ]
    }
  ]
}
