{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2545.0.jar",
          "size": 519768,
          "sha512": "62efbafce1cbd16f091a7d974cfaa252c5d43c7fb570a46a47ad622096d9095e979ad074e63d583e5bcd799932b3c99ba1a599849f7fb681050621d30d14ffd4",
          "sha256": "db1e1dc28c4efa8ef298fa6c35576d56e5d52f95f706ffa802ea6f8add6ecb46",
          "sha1": "d98c055372fdb436798949771323092d05d2400d",
          "md5": "454d2ada11a99ba9af9a98189490b216"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2545.0.jar",
          "size": 519768,
          "sha512": "62efbafce1cbd16f091a7d974cfaa252c5d43c7fb570a46a47ad622096d9095e979ad074e63d583e5bcd799932b3c99ba1a599849f7fb681050621d30d14ffd4",
          "sha256": "db1e1dc28c4efa8ef298fa6c35576d56e5d52f95f706ffa802ea6f8add6ecb46",
          "sha1": "d98c055372fdb436798949771323092d05d2400d",
          "md5": "454d2ada11a99ba9af9a98189490b216"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2545.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2545.0-sources.jar",
          "size": 268384,
          "sha512": "05e66a07057cc30573654474a467ce17c197a96349567c3762e160cfbae2291b3b65aee90db33e428cb03ad90e227334e88534d865aea2d26156d30b67562a7e",
          "sha256": "af4ed61b4d8c7eca0cb2a2a8ab05cd9365c6d37864a494e4cada88414ce865b9",
          "sha1": "d75d7352cc9d700334700c864e0dc2cbb1dacddd",
          "md5": "652e5d1a57220675202a888a5b71bd12"
        }
      ]
    }
  ]
}
