{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.6.2541.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.2.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.2.jar",
          "size": 516972,
          "sha512": "06624a8c23b5e71d836fdd1d428ba8be6026ce6ffae882f0dc58ae88d64432de869459d23580f9bd395b9621fda5f4b09459b034bbf96a70c4be4e8c1968fa9f",
          "sha256": "07f0d9ac94f67a5cb7c9856122755c414050e812d7e56f56999d587cdde8b344",
          "sha1": "7111052234bc8ced2371603d27aa3281937bd86b",
          "md5": "90c83d1dca27f8151ff7737670d28f42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.2.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.2.jar",
          "size": 516972,
          "sha512": "06624a8c23b5e71d836fdd1d428ba8be6026ce6ffae882f0dc58ae88d64432de869459d23580f9bd395b9621fda5f4b09459b034bbf96a70c4be4e8c1968fa9f",
          "sha256": "07f0d9ac94f67a5cb7c9856122755c414050e812d7e56f56999d587cdde8b344",
          "sha1": "7111052234bc8ced2371603d27aa3281937bd86b",
          "md5": "90c83d1dca27f8151ff7737670d28f42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.2-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.2-sources.jar",
          "size": 267756,
          "sha512": "cbac49981948e82f2a3399159af80abec13f206a8a768cf64211a99bdf325f6e7432a4b1eac32d0264b462c8f1f7df1150aa668ee71d3dd9782e0091532bd5da",
          "sha256": "4c4782761ef493d4ea50bfa54185f6607e7647c52be559a3f5e89a3df5cf8eeb",
          "sha1": "c7f60332290d88b3e6415d7f46b11da20beaec3f",
          "md5": "22d68b61022229d2273e18374620083c"
        }
      ]
    }
  ]
}
