{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.8.2511.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.2511.0.jar",
          "url": "legacy-fabric-1.21.4-1.8.2511.0.jar",
          "size": 16908420,
          "sha512": "eb1e21be1c0ac4310db5052efd64250c36d977fc318121dccb17eac1e7e72ac4338f5c294ad55b057885db0e36a8ae9d25e73437b92cead1f99f523b3147638b",
          "sha256": "bcfcdaa241437e1ee4f432d9ec0b465b48999a43319a0491f4c92783043d68ca",
          "sha1": "5daba002f7e5bd8b5cae6197ec81b02cfa8cf077",
          "md5": "ba59df950309bece32ad2b61c416c21c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.4-0.6.5-fabric"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.2511.0.jar",
          "url": "legacy-fabric-1.21.4-1.8.2511.0.jar",
          "size": 16908420,
          "sha512": "eb1e21be1c0ac4310db5052efd64250c36d977fc318121dccb17eac1e7e72ac4338f5c294ad55b057885db0e36a8ae9d25e73437b92cead1f99f523b3147638b",
          "sha256": "bcfcdaa241437e1ee4f432d9ec0b465b48999a43319a0491f4c92783043d68ca",
          "sha1": "5daba002f7e5bd8b5cae6197ec81b02cfa8cf077",
          "md5": "ba59df950309bece32ad2b61c416c21c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.2511.0-sources.jar",
          "url": "legacy-fabric-1.21.4-1.8.2511.0-sources.jar",
          "size": 16082912,
          "sha512": "2eed4ccb18393de90d44fc5c22fc26c9e6768c9be90eafe2dbd60c09829309c8ecdbd0dcd8fa82b1e545efc4dab4276b7db383d04657919040d61337f0265284",
          "sha256": "1d57f42ba68cbd30d67395321012149ca4721375d1dd0d065b586818cc47e654",
          "sha1": "a733f010299dd59c4237b0f88365bffcc459dbc8",
          "md5": "ea737ec6b5b70957136d1d8a6ed72940"
        }
      ]
    }
  ]
}
