{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.8.0.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2512.0.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2512.0.jar",
          "size": 18244844,
          "sha512": "56b1e993ab0c06a689379dbafdf76d6afe1de369e650a8941e5389c41c8f0257dcbf2d9b7007a599e48f8c2d8a779da68a4f7dd3fc482b0e77b9245c9aa388d1",
          "sha256": "60c5195d17e5c13628b5497ee3e6bbee921abbef7d1cd000e86df2e46d78488e",
          "sha1": "74b8adcc11b3fc964759074c04628ec3f2b818ac",
          "md5": "ed46d36e64c46470d88b91f955b61781"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2512.0.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2512.0.jar",
          "size": 18244844,
          "sha512": "56b1e993ab0c06a689379dbafdf76d6afe1de369e650a8941e5389c41c8f0257dcbf2d9b7007a599e48f8c2d8a779da68a4f7dd3fc482b0e77b9245c9aa388d1",
          "sha256": "60c5195d17e5c13628b5497ee3e6bbee921abbef7d1cd000e86df2e46d78488e",
          "sha1": "74b8adcc11b3fc964759074c04628ec3f2b818ac",
          "md5": "ed46d36e64c46470d88b91f955b61781"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2512.0-sources.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2512.0-sources.jar",
          "size": 17412170,
          "sha512": "9e8afe1b60f7bab0250432c1b7cf5d589f1585b98511c874bef72883c20206fd451016655dcc89dd4c2b32f211ec2a7915e0783f9c7a71c834fe0f3c7980b895",
          "sha256": "aaa90e9e4ec254553b5ae068e834ee6b78e16c4bd15249ea1db5baf1cb29d2ca",
          "sha1": "24fd04d1c7e9d071f0ace60fe0981dab3e447bb2",
          "md5": "0ec7355cd4e989bb7d75365a9d74d537"
        }
      ]
    }
  ]
}
