{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.14.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.14.jar",
          "size": 461697,
          "sha512": "7f20a5bec8f4d136967d20b0ef61b58ecfa9f35e2c69ecc3d7410f3b5a2069dc6fffb0cd6fbb3e37186cf14c578f4a7b7a4f5a1c01300017c668c751dd214e9f",
          "sha256": "f1b7493de378a7171e09fd73b04b6c6ef92a398bbdf75199ddb10db7396e48a4",
          "sha1": "c7cd62af8055a8c29357949d2830a9477cd54a56",
          "md5": "f1efdcf2b0e46d08e72c1fd7151f27ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.14.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.14.jar",
          "size": 461697,
          "sha512": "7f20a5bec8f4d136967d20b0ef61b58ecfa9f35e2c69ecc3d7410f3b5a2069dc6fffb0cd6fbb3e37186cf14c578f4a7b7a4f5a1c01300017c668c751dd214e9f",
          "sha256": "f1b7493de378a7171e09fd73b04b6c6ef92a398bbdf75199ddb10db7396e48a4",
          "sha1": "c7cd62af8055a8c29357949d2830a9477cd54a56",
          "md5": "f1efdcf2b0e46d08e72c1fd7151f27ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.14-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.14-sources.jar",
          "size": 232130,
          "sha512": "d6cb037d40ede7b64f70ce51467797118fcbd78fa6f30a45d25906e5910b57fb134bbe48fdd8ba195204f3952f4f2c65736031bfd2793b8b9446a06da0d8aeac",
          "sha256": "b3ff2aa792c6c4b017c76c2c5d6f359e0893f84029b4c4b731250bd9d4fd7d73",
          "sha1": "49a2240cfeb9e1c64bf5a09066b2d4be9f211761",
          "md5": "89b91eee83b78639e79a4c1257ac2058"
        }
      ]
    }
  ]
}
