{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2513.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.5.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.5.jar",
          "size": 699583,
          "sha512": "16b2be9241bcbcdd9b49e1d9d0dcf84cad3a451a909322cf3622b837c228c2340082f03e774e00adbed961707591c62b80ea266004237a8d7dc041e9dbbbfa2d",
          "sha256": "c98c5b1f0aeec10d7bd712b7f6568beb157ad7bb5a6e7ddd22315f404d07f704",
          "sha1": "d964af1968fcadd1539de657dab71826d208df1e",
          "md5": "699eb2f37c06d901911678fd879b1945"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.5.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.5.jar",
          "size": 699583,
          "sha512": "16b2be9241bcbcdd9b49e1d9d0dcf84cad3a451a909322cf3622b837c228c2340082f03e774e00adbed961707591c62b80ea266004237a8d7dc041e9dbbbfa2d",
          "sha256": "c98c5b1f0aeec10d7bd712b7f6568beb157ad7bb5a6e7ddd22315f404d07f704",
          "sha1": "d964af1968fcadd1539de657dab71826d208df1e",
          "md5": "699eb2f37c06d901911678fd879b1945"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.5-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.5-sources.jar",
          "size": 250443,
          "sha512": "3405f90024c98fcd7b4bd2685482dd5933116ebf6a812b2579b73ecc7de056294aebf8e3afada2cf9838dba120e9575e3be2ff123581755b78cb2c5d93627f75",
          "sha256": "7e485e371b7b20aed363f1152e27f6e6b0c0e1c5c8ac857df3493ab283755ba8",
          "sha1": "382a44eed7b69ca7fa578dc09da0233cfde42c28",
          "md5": "03ba30b5dfb8ede84f5d35b37d02584f"
        }
      ]
    }
  ]
}
