{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.20.4-1.7.10.2509.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2509.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2509.0.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2509.0.jar",
          "size": 14403717,
          "sha512": "fdb63d7cdefae2908916efdfe9fdfeb0276585d5f671e3506c8930c9dcd01957e111b13e80a1bfeb60db5ce8fe7bec5ad74f86309381d0f787cb9c9b5dff50e8",
          "sha256": "0616efc821e7d3af6edacea7ee6c7b3f73f74d9f901935a59bfbc473cf95a2e8",
          "sha1": "72f5b8caf288d6710fdf01ad79500b24199f252a",
          "md5": "2aaaae6ff361acf56fecaf8350dee309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2509.0.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2509.0.jar",
          "size": 14403717,
          "sha512": "fdb63d7cdefae2908916efdfe9fdfeb0276585d5f671e3506c8930c9dcd01957e111b13e80a1bfeb60db5ce8fe7bec5ad74f86309381d0f787cb9c9b5dff50e8",
          "sha256": "0616efc821e7d3af6edacea7ee6c7b3f73f74d9f901935a59bfbc473cf95a2e8",
          "sha1": "72f5b8caf288d6710fdf01ad79500b24199f252a",
          "md5": "2aaaae6ff361acf56fecaf8350dee309"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2509.0-sources.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2509.0-sources.jar",
          "size": 13581714,
          "sha512": "62a385edb71c1ad35fc4391be5a2646f7e1e72e9b443ca197e42f6f44edea45ad0ece340ac292a692e2a131cde22c8ff49a4e07ab489b42bffca90303b614f4c",
          "sha256": "ee6e89e3a494dc103d408666c649fad8cada6a1a44413f30da2007f23fa42331",
          "sha1": "755d592510e803d7ec72573ab7c5949b451dbb04",
          "md5": "b875f3f3ac41085f538edb53b636ffaf"
        }
      ]
    }
  ]
}
