{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.8.0.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2514.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-forge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2514.1.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2514.1.jar",
          "size": 18281566,
          "sha512": "04a375ec9c5f79aa3cf269a3c4736b9e9df657137c06bbc8f07132507991897edb3579ab0c641900d73196872fc00893485faae5a8fd2098d86c40dbc275f17a",
          "sha256": "4c23d3537803a8f2ed8ccddb1b8ed65a2e5f24df898e9cdca9505631b0f1943c",
          "sha1": "48e17ab61a6049b482ebc227934db582b96f1e5b",
          "md5": "6327520c323de939f246aa089299bae0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2514.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2514.1.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2514.1.jar",
          "size": 18281566,
          "sha512": "04a375ec9c5f79aa3cf269a3c4736b9e9df657137c06bbc8f07132507991897edb3579ab0c641900d73196872fc00893485faae5a8fd2098d86c40dbc275f17a",
          "sha256": "4c23d3537803a8f2ed8ccddb1b8ed65a2e5f24df898e9cdca9505631b0f1943c",
          "sha1": "48e17ab61a6049b482ebc227934db582b96f1e5b",
          "md5": "6327520c323de939f246aa089299bae0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2514.1-sources.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2514.1-sources.jar",
          "size": 17438657,
          "sha512": "19dd2e5676357e1e71857d8525138b8cbf453c1d8b7266eea4cd551bec80ff62e33b9b74ccef7f057ac0dc2326a6fa98c9626d0340656dd2c3678a622a9e3cf5",
          "sha256": "0c888e4aed1c99c2b3f8672481170e7329943de34fb72c76986984e4df7589cb",
          "sha1": "143d1254cd7d958522dcddb085a4570c0d76d123",
          "md5": "72d3579a4f42d493c6f2a896b2697c27"
        }
      ]
    }
  ]
}
