{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2507.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.3.jar",
          "size": 494889,
          "sha512": "1f8e9b8572a8910cfbc1db5dbd84477472a4415cddaf7827399273170029b8864dd549b7d481345d18e244c9f78360d5e5e2c2ae1c83ada8f66907190e9f02f8",
          "sha256": "448e14c0104c9adf28780f94c4f1a7d1b768e336fa492b2a3183722477369839",
          "sha1": "fba15275720f910753c46ba4ebccce6a424a78e6",
          "md5": "998058770957ffaa0bd2f6fe2f7f5f2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.3.jar",
          "size": 494889,
          "sha512": "1f8e9b8572a8910cfbc1db5dbd84477472a4415cddaf7827399273170029b8864dd549b7d481345d18e244c9f78360d5e5e2c2ae1c83ada8f66907190e9f02f8",
          "sha256": "448e14c0104c9adf28780f94c4f1a7d1b768e336fa492b2a3183722477369839",
          "sha1": "fba15275720f910753c46ba4ebccce6a424a78e6",
          "md5": "998058770957ffaa0bd2f6fe2f7f5f2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.3-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.3-sources.jar",
          "size": 244010,
          "sha512": "fde65a62057fc9ee4b72ac8448f4acb0ca128534594c5d6366e00bf04e58c0a4990f69e2892b59899a7ac8df193c19d5c71ab857995f39abcbddd3af9a8f9d95",
          "sha256": "0c64e5e007bad37e748c1feca178833c6f80416a045d9185b44f521158c38133",
          "sha1": "7534c396d99f5c1b52882a32ca58b74cdfc14228",
          "md5": "fa961ff4f1a9b6f490267cb6e0032319"
        }
      ]
    }
  ]
}
