{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2510.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.8.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.8.jar",
          "size": 498482,
          "sha512": "2cd594d60de4e375a018d71e2847110ba6265faac02725b5e1745916a093ef682e8d543108b085998d041aca1c1f6521aa29ca36bc206035a5d6f6f085d04943",
          "sha256": "d17b11c37db65553dab2ba17d52055ea783cfa5db2cf845ca475e7f71b051376",
          "sha1": "5ef93be961a686810bba7a0d7ac22c0501a226e3",
          "md5": "ebac2f29fdf17831becb851fba0d1c1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.8.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.8.jar",
          "size": 498482,
          "sha512": "2cd594d60de4e375a018d71e2847110ba6265faac02725b5e1745916a093ef682e8d543108b085998d041aca1c1f6521aa29ca36bc206035a5d6f6f085d04943",
          "sha256": "d17b11c37db65553dab2ba17d52055ea783cfa5db2cf845ca475e7f71b051376",
          "sha1": "5ef93be961a686810bba7a0d7ac22c0501a226e3",
          "md5": "ebac2f29fdf17831becb851fba0d1c1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.8-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.8-sources.jar",
          "size": 250556,
          "sha512": "09b0898c06b859b6e8786bbbf9e255824a015ca254e621e9621ae8f0b4d6d0308a967cc651350fcf7f2d4211092e99a407fce1227efc2598a7d893ebda3e2cf0",
          "sha256": "9c56142b7fbdb16c290810c6b5785509298487efae9873a8f112d73891edfc18",
          "sha1": "edea3b871ccf5c22bf77b3ee43014cd35fc575cd",
          "md5": "e8de0f952561929f9e1a847513fda088"
        }
      ]
    }
  ]
}
