{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2517.0.jar",
          "size": 699118,
          "sha512": "72f16a363d68e0a7483d5a01fd6f06920f6009eee43e686f6a5059c4b79d279155f5ce0373b278f538e6aefc93a4061d3060e621f13994882580b6761ca71ee4",
          "sha256": "afa6d832db8a9425ca7595aee75e12892d789abc21a38194edee2c06533231b3",
          "sha1": "c0bc8aeaff8a4a9b729f6b8d60649bfb50ddadb0",
          "md5": "5382d229ff8774d2c4253c5c18343db0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2517.0.jar",
          "size": 699118,
          "sha512": "72f16a363d68e0a7483d5a01fd6f06920f6009eee43e686f6a5059c4b79d279155f5ce0373b278f538e6aefc93a4061d3060e621f13994882580b6761ca71ee4",
          "sha256": "afa6d832db8a9425ca7595aee75e12892d789abc21a38194edee2c06533231b3",
          "sha1": "c0bc8aeaff8a4a9b729f6b8d60649bfb50ddadb0",
          "md5": "5382d229ff8774d2c4253c5c18343db0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2517.0-sources.jar",
          "size": 254284,
          "sha512": "d5ae32306485b1a9d4a13244c695a28c8e1218fc721974ee6c3cb127677248920048296c4c7978ab3a6852e6edee0a7fb05c92afc40538f79bdc88c3f46015b0",
          "sha256": "8b9678da0976ac7f2624afb86e605bdb8aa0924473f1660e36e4956ea572d1cb",
          "sha1": "9b07f68eab992747f14215dd63424cb431d088d0",
          "md5": "789253c25ffd8a7e9ebb18a2dab42ad3"
        }
      ]
    }
  ]
}
