{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2515.0.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2515.0.jar",
          "size": 18292598,
          "sha512": "e093b9132e803fe7546cb2c425c09d3aacc23739edfdda25a9545527b2374587f6d3c2156d379d516d4691548fa29b2f5e24e70cbf8a0c2a123feecabf14ed0d",
          "sha256": "cfe7a9ec0852948febbb7a9ab29d3979e0fbae3e7871217dc2db54ca56194314",
          "sha1": "52e404d0029018af18bc93d1d6c26dfd0b3b6899",
          "md5": "b078d858f9faa8276db9d3014d3a755b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2515.0.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2515.0.jar",
          "size": 18292598,
          "sha512": "e093b9132e803fe7546cb2c425c09d3aacc23739edfdda25a9545527b2374587f6d3c2156d379d516d4691548fa29b2f5e24e70cbf8a0c2a123feecabf14ed0d",
          "sha256": "cfe7a9ec0852948febbb7a9ab29d3979e0fbae3e7871217dc2db54ca56194314",
          "sha1": "52e404d0029018af18bc93d1d6c26dfd0b3b6899",
          "md5": "b078d858f9faa8276db9d3014d3a755b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2515.0-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2515.0-sources.jar",
          "size": 17432786,
          "sha512": "29f5216e92c772cb1e669a1af4b06be7d508d4ab959b339743dc160a0be0b384fa9a7a6e9461a2070720fbb506a16f8443d15d8f8d715f390462ea8e895c33a6",
          "sha256": "7602fc0a34408ab1b3fc1f59bf06b5ab7da68db9632f85bb00343a623eed5979",
          "sha1": "0f165e6c4ea37a52b4f4bd848742b4d1ae8cb5cb",
          "md5": "25e9a651aac2b5855d613d2144d8efd2"
        }
      ]
    }
  ]
}
