{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.19.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.19.jar",
          "size": 389941,
          "sha512": "753f63f490eeaa9f71d11a819f9f1a6ea96af56747eea59d9f10e9f189129739e19b1b8131d0f3c8b06eadac227b51dcff57ff4ba06b3359df386fa60bbe6aae",
          "sha256": "7ef6cb26dce6dfb262c24b53bdd0fd5356619869b99b7c26aab38a14a8a98eca",
          "sha1": "bdb0249c7124e761fcc60ad47d814419e220f99e",
          "md5": "9d7449210a7b12c87dba7635308adce0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.19.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.19.jar",
          "size": 389941,
          "sha512": "753f63f490eeaa9f71d11a819f9f1a6ea96af56747eea59d9f10e9f189129739e19b1b8131d0f3c8b06eadac227b51dcff57ff4ba06b3359df386fa60bbe6aae",
          "sha256": "7ef6cb26dce6dfb262c24b53bdd0fd5356619869b99b7c26aab38a14a8a98eca",
          "sha1": "bdb0249c7124e761fcc60ad47d814419e220f99e",
          "md5": "9d7449210a7b12c87dba7635308adce0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.19-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.19-sources.jar",
          "size": 200717,
          "sha512": "00484fa3a6acec90eeca912c3533dce3b723c3deadbc0d12cb8b1ef4aabdb430dfbe942dcab268280101ca3e519ae2e76e6f67afda732b3f8e31116b943de583",
          "sha256": "e0bb22055742a25706cb7cf41700d2666cb1481b5986e7d219df91d509b54136",
          "sha1": "f563e96a3dacb73fbc2f8505068d9c4e6d6aa642",
          "md5": "73b8e1aed7f1528707de8c16bd451c2e"
        }
      ]
    }
  ]
}
