{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.4-1.8-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3-pre"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8-pre.jar",
          "url": "legacy-fabric-1.20.4-1.8-pre.jar",
          "size": 14387981,
          "sha512": "1edd3bfaf862e259bc80bf39abceb9d08900199ff3a53ae33e4f66eb62c0bd17894a14253804f6ab911b0b2bf56464a34593911c0cf0005b9cfae13b36121e6b",
          "sha256": "385b7a13f44c1956d557803c976284f87dd357e0db3b544782884c8f8ea76b0b",
          "sha1": "f5db3a90ae65d980bbdf109282f8335cac888185",
          "md5": "514c52b763a64429dfe0a0b1a6ce55b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3-pre"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.20.4-0.5.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8-pre.jar",
          "url": "legacy-fabric-1.20.4-1.8-pre.jar",
          "size": 14387981,
          "sha512": "1edd3bfaf862e259bc80bf39abceb9d08900199ff3a53ae33e4f66eb62c0bd17894a14253804f6ab911b0b2bf56464a34593911c0cf0005b9cfae13b36121e6b",
          "sha256": "385b7a13f44c1956d557803c976284f87dd357e0db3b544782884c8f8ea76b0b",
          "sha1": "f5db3a90ae65d980bbdf109282f8335cac888185",
          "md5": "514c52b763a64429dfe0a0b1a6ce55b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8-pre-sources.jar",
          "url": "legacy-fabric-1.20.4-1.8-pre-sources.jar",
          "size": 13576784,
          "sha512": "ccddbbdf75228fc383de492e10e42c8a28a5e89c3aef24ac2a7c40a49d0170de10019a62f05e46b5da0c4c81bdd61be2da4383d343d54436f5472ecafa86861f",
          "sha256": "a6a73fab2b653a6f2ed144c249bd02f9f7259747d53be144b568ce5de44246c8",
          "sha1": "6d5ec132577708cb85be7ba4fdfc60ebb85b449e",
          "md5": "22519ce1c441d6b6f9d035885cd76200"
        }
      ]
    }
  ]
}
