{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2501.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.17.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.17.jar",
          "size": 365897,
          "sha512": "0299ffa79c189582f27ffdf33b136a7c62eb02babd297a442756f7cf21d2c9cb38958a80b87a0f449f3c48b16dd97e948af6367f25c09267ce09ed18a64b7209",
          "sha256": "db42e36ad2ea31b9a3db0e265bb47e2b6b3ab42375daf5a9d270b6d27f8d83ea",
          "sha1": "46d38d849d1788bfcd96644b21a9a7ca2c9f6354",
          "md5": "0c334185e66cfab3b4bc039a64b518e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.17.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.17.jar",
          "size": 365897,
          "sha512": "0299ffa79c189582f27ffdf33b136a7c62eb02babd297a442756f7cf21d2c9cb38958a80b87a0f449f3c48b16dd97e948af6367f25c09267ce09ed18a64b7209",
          "sha256": "db42e36ad2ea31b9a3db0e265bb47e2b6b3ab42375daf5a9d270b6d27f8d83ea",
          "sha1": "46d38d849d1788bfcd96644b21a9a7ca2c9f6354",
          "md5": "0c334185e66cfab3b4bc039a64b518e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.17-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.17-sources.jar",
          "size": 200325,
          "sha512": "750f17d412101decc3795752c95e8a926132f1ccbea15a902887d16fb89e85ab62283cacaffdb1e94340123ea45719716aac520e000cd9db9a6eff1f9d12ad18",
          "sha256": "58b5451255e7500fa9f7563c5366b1b3e417de93bed03657f5669f8779a5b799",
          "sha1": "1f6e752ed47631dac53b0b63d1f9264128c07684",
          "md5": "14c41bb7aeb836c0c9d7d72afc7ff539"
        }
      ]
    }
  ]
}
