{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2506.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2506.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.2506.1.jar",
          "size": 477602,
          "sha512": "626b4827d2866314889b5fd057576d420de7319211778779f915c9d5972c8779b5907289db9b31996acabad8dcc2dd1c88ae2933d7e4b7f3edc32567a44974bc",
          "sha256": "24886b62fa16f23fe8563cff7a1a2ac8d8ce39c622357d2f954ced2faf602243",
          "sha1": "7e75a942c5f93a59d82c32bd960734af3865646f",
          "md5": "21b6fb0693ce058f7c320f2b9fc13a42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2506.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.2506.1.jar",
          "size": 477602,
          "sha512": "626b4827d2866314889b5fd057576d420de7319211778779f915c9d5972c8779b5907289db9b31996acabad8dcc2dd1c88ae2933d7e4b7f3edc32567a44974bc",
          "sha256": "24886b62fa16f23fe8563cff7a1a2ac8d8ce39c622357d2f954ced2faf602243",
          "sha1": "7e75a942c5f93a59d82c32bd960734af3865646f",
          "md5": "21b6fb0693ce058f7c320f2b9fc13a42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2506.1-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2506.1-sources.jar",
          "size": 243042,
          "sha512": "e6ae864f650760d37cc4788adb1aecff08a9b22307cbd9f4d285122c3412ddc169605a2e8dcdfc8c55f64f6049a973fb53895de6ae42d3a13ea2161e27819831",
          "sha256": "afdf3067eb89d3ceb99671ae380abab8d738e617465ce6a7d06a806c0e1fd978",
          "sha1": "91100ce7859ff023020dd832a387097c106f9c4f",
          "md5": "8931cc95ae0660619eb63039ec95e151"
        }
      ]
    }
  ]
}
