{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.5.jar",
          "size": 495601,
          "sha512": "235221b86ab9108b83e3d7676e27ffc3513d1678f18af6bcbd17cce2ae882313b937ae96ed2442ec1ff5dd992b4219c5c95e89018283352629c3de562b1d29b3",
          "sha256": "9e7c1bf11d3722cf54052b1fa401457461cbf612955294313b93ea04854f7dc3",
          "sha1": "24c9e6cbe906143254e5bcc98aff591f2759efde",
          "md5": "665b24361e15aaa5826914f407a30338"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.5.jar",
          "size": 495601,
          "sha512": "235221b86ab9108b83e3d7676e27ffc3513d1678f18af6bcbd17cce2ae882313b937ae96ed2442ec1ff5dd992b4219c5c95e89018283352629c3de562b1d29b3",
          "sha256": "9e7c1bf11d3722cf54052b1fa401457461cbf612955294313b93ea04854f7dc3",
          "sha1": "24c9e6cbe906143254e5bcc98aff591f2759efde",
          "md5": "665b24361e15aaa5826914f407a30338"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.5-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.5-sources.jar",
          "size": 250700,
          "sha512": "9a93cc1eafc44a41cdc404e21ce709fb3082b970f4dafc3405fdc0c642cf0832a5c47ab68f4b352b641df6ea1d859473fea2c3789ff77489f27d1684aa3e9be5",
          "sha256": "6f11e435c446ecb8f29491c53ad6fec0826f8e2395b2a3703ec756ea032e4adc",
          "sha1": "91006da1e1cdfd0c085c593e0c33a24a8921659f",
          "md5": "e8d458218a19ccd2ec63b55f8aeccb2e"
        }
      ]
    }
  ]
}
