{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2508.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.4.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.4.jar",
          "size": 679671,
          "sha512": "5f8202fc89917a0ba40265fa889614d16f2adb0ad715cf6d2ef76f18d048fb8b9fdb18f79ba5719b507e25caf68f0617513dba9768033a624c4f4fb9802f6e3b",
          "sha256": "ddaf023d40683ffe39937c8d42a5db8aa6ef562588925c3b7892f8614e5b6a6f",
          "sha1": "1172779f4471be8e6fd640a99374d7e9efa7e8cf",
          "md5": "470831aa77d60e147bec4298d8acd88e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.4.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.4.jar",
          "size": 679671,
          "sha512": "5f8202fc89917a0ba40265fa889614d16f2adb0ad715cf6d2ef76f18d048fb8b9fdb18f79ba5719b507e25caf68f0617513dba9768033a624c4f4fb9802f6e3b",
          "sha256": "ddaf023d40683ffe39937c8d42a5db8aa6ef562588925c3b7892f8614e5b6a6f",
          "sha1": "1172779f4471be8e6fd640a99374d7e9efa7e8cf",
          "md5": "470831aa77d60e147bec4298d8acd88e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.4-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.4-sources.jar",
          "size": 248052,
          "sha512": "a676c38756fab4ad2b11fb1c100373e33d768022c8fa851ef82a271e9bc51d1540e22c3ed82fc8a357d54ab0a9980310b36a35e8daa4728ff13648696d3b93a1",
          "sha256": "b85c4e2a74343f120c47db02046f259e943aabb05078adc9028da720b2bc8d34",
          "sha1": "a7cb19760d96861adfd63452c57923eaf0261b97",
          "md5": "3c2cc72c17060a2b83fefc998386ce15"
        }
      ]
    }
  ]
}
