{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.7.2616.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2616.1.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2616.1.jar",
          "size": 581325,
          "sha512": "a9938942a2780e49854799493795adbf5ee6b95f696fc051cd2f15f985d775dba084f53cae33c53f0c0d70ce87a64ecbde6ac29037dd83da4227341775879067",
          "sha256": "a97254b295a9f5ac5b41e6ee1b1d31ff0e3170ed6943c5f42f03303cf644def3",
          "sha1": "4080bdbee8e0ccdabc9b92cfbb90a2429cca1274",
          "md5": "093347bca76483ee629f7a04cb5034c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2616.1.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2616.1.jar",
          "size": 581325,
          "sha512": "a9938942a2780e49854799493795adbf5ee6b95f696fc051cd2f15f985d775dba084f53cae33c53f0c0d70ce87a64ecbde6ac29037dd83da4227341775879067",
          "sha256": "a97254b295a9f5ac5b41e6ee1b1d31ff0e3170ed6943c5f42f03303cf644def3",
          "sha1": "4080bdbee8e0ccdabc9b92cfbb90a2429cca1274",
          "md5": "093347bca76483ee629f7a04cb5034c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2616.1-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2616.1-sources.jar",
          "size": 256275,
          "sha512": "02b313cd177f4558060c606f24a8d6e0c280ff1f7ba12664683762b9ad71822276af122d07dd8e726d22fb2af5cd8c2f2f88932bf5530111e9a82ff77dfed93b",
          "sha256": "526494b0b9bdd734bfd26c8d51e2887b065b760d15c80061be3cba26ef86f7bf",
          "sha1": "0c56a0f19120ccf11127f30ef31f48d4e43c1206",
          "md5": "3807d8e07a385161befda44fa765f778"
        }
      ]
    }
  ]
}
