{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2545.0.jar",
          "size": 538375,
          "sha512": "f4f582862c55931a67cb9ab9d2dc09d02fdc6faa6ae81b7f844b8d653e07ec44cebee7b07adaaff5d5a38f7e9567c1e4bfd05346831e7338c17696d68c5575b2",
          "sha256": "3d3e6a1d9c3d4ecef9a6253067a3018b4027dcfcacbf76df9565ead33e766de4",
          "sha1": "bae76437ecebd7416531cf37f06ba6055cb6ccf5",
          "md5": "484f4bdaced2da3fce42070f386856a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2545.0.jar",
          "size": 538375,
          "sha512": "f4f582862c55931a67cb9ab9d2dc09d02fdc6faa6ae81b7f844b8d653e07ec44cebee7b07adaaff5d5a38f7e9567c1e4bfd05346831e7338c17696d68c5575b2",
          "sha256": "3d3e6a1d9c3d4ecef9a6253067a3018b4027dcfcacbf76df9565ead33e766de4",
          "sha1": "bae76437ecebd7416531cf37f06ba6055cb6ccf5",
          "md5": "484f4bdaced2da3fce42070f386856a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2545.0-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2545.0-sources.jar",
          "size": 268523,
          "sha512": "02c34f140b52cb19144d7ebe7df3795430c518e599bf5bd0e60d27bfccbd8cbb77b40e0e00713e417af4e4485642915dddad9005f6aef66c2af90256d84e4dd3",
          "sha256": "680e4b824fc905d2256c96ca2aa4f4861680efbe75b412260b1a90f488ace594",
          "sha1": "3be2e1d8de27fa33bc2f552a2f6fd632593ab18c",
          "md5": "811b340af855f4a23f9467c1391b3d83"
        }
      ]
    }
  ]
}
