{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.11.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.11.jar",
          "size": 495854,
          "sha512": "1ae6b784eb0598d2954fc8c6cdfc80777e955ca945e026d2c28ca47134c220b3acea5077a803cb180d9d1d768089b29462c308168bea06514531bf0d6b725beb",
          "sha256": "d91ca3ac84665884c6fe4f74415821a27d10b91c15e5249ae87a1ae3fa5f0e38",
          "sha1": "d4c86e08a34a66ccf7f7adfe5b27e07a1e02783b",
          "md5": "b5acf35b9a8e97111154572d90b0db29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.11.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.11.jar",
          "size": 495854,
          "sha512": "1ae6b784eb0598d2954fc8c6cdfc80777e955ca945e026d2c28ca47134c220b3acea5077a803cb180d9d1d768089b29462c308168bea06514531bf0d6b725beb",
          "sha256": "d91ca3ac84665884c6fe4f74415821a27d10b91c15e5249ae87a1ae3fa5f0e38",
          "sha1": "d4c86e08a34a66ccf7f7adfe5b27e07a1e02783b",
          "md5": "b5acf35b9a8e97111154572d90b0db29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.11-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.11-sources.jar",
          "size": 244779,
          "sha512": "fdcb6478028441fe7a99323e985f8f911d62f59a9ec662c9a5bdc8a209d68a2a7877484e43b532d5a0dd467530e66f81144c641e98acd6ca78ecc65126b554a0",
          "sha256": "cff185ed57f29daf472b2b080d16e1c4d98ce47cd5292eeb9c0d31a8d574fd2e",
          "sha1": "5e8c5aed25d619a4e04c885cfdc63d299651dc7b",
          "md5": "78ce084e05fc00a5bb57fe417c6abfa8"
        }
      ]
    }
  ]
}
