{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.9.jar",
          "size": 444126,
          "sha512": "2d7ee62d7f3771250d8c40494244f50dc16a7145a099df9e9d5bd37380689f646b21e7b4256fbda36d45691f94734f6cbf4135b9c2de7c7fee07c183a47e96e9",
          "sha256": "ee70fd806b835da6040d4e3bc24c80082c33b6c471dc32a7a1ea581bb0b63683",
          "sha1": "52787b8777549d4e8c0e851498610e07c5a982d2",
          "md5": "a609f216b0a4ca4d7252205fee872dc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.9.jar",
          "size": 444126,
          "sha512": "2d7ee62d7f3771250d8c40494244f50dc16a7145a099df9e9d5bd37380689f646b21e7b4256fbda36d45691f94734f6cbf4135b9c2de7c7fee07c183a47e96e9",
          "sha256": "ee70fd806b835da6040d4e3bc24c80082c33b6c471dc32a7a1ea581bb0b63683",
          "sha1": "52787b8777549d4e8c0e851498610e07c5a982d2",
          "md5": "a609f216b0a4ca4d7252205fee872dc7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.9-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.9-sources.jar",
          "size": 222455,
          "sha512": "8133c5c9ddfd3beee594eb2994cd316ca7591cfd4e2a46010c8496b3ba249fc78a66681826f455c5ba39c4c5133e7c626069e64d31e7b0da16149bf61f28d803",
          "sha256": "b0f191e5159e5e97d32d3246bcfce0f4e5b690392ac5d57b2b7abf55387a605f",
          "sha1": "9890d4e8cac670313b99025dffd362096bc2e812",
          "md5": "053fbbc3d86ae294b5d7dc39684e5e27"
        }
      ]
    }
  ]
}
