{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2518.5.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2518.5.jar",
          "size": 19737754,
          "sha512": "179ef4d2f368a07b1e518b2c2fcc2fff5342cdb2d7d618783edcab690fc112770bb7d3f2b38fc39e580fb50e39e0bb88c291202385b5563247be3323e9b8e03c",
          "sha256": "b1e4aa4253b1451a8078252850ef26fb2a4e93f4e1cd3240b5873119d09e9d74",
          "sha1": "d70bca14d6bf2bf19c48433945a2c699050460f7",
          "md5": "0686cf7af7acb0031219b6c4b6c07b04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2518.5.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2518.5.jar",
          "size": 19737754,
          "sha512": "179ef4d2f368a07b1e518b2c2fcc2fff5342cdb2d7d618783edcab690fc112770bb7d3f2b38fc39e580fb50e39e0bb88c291202385b5563247be3323e9b8e03c",
          "sha256": "b1e4aa4253b1451a8078252850ef26fb2a4e93f4e1cd3240b5873119d09e9d74",
          "sha1": "d70bca14d6bf2bf19c48433945a2c699050460f7",
          "md5": "0686cf7af7acb0031219b6c4b6c07b04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2518.5-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2518.5-sources.jar",
          "size": 18854068,
          "sha512": "6a4d623a001d0657da585f44f8bfede3db2939ac4ac95b4642ac6a7d34eeb76f7f9a81b82839d024e87a24eb7fada40957f4f1ac5c5348cbaae54ef44540f238",
          "sha256": "d4e3b2d6396aa0dd7d7495abfd3ab01c1d68d5c9847021cbc6acbdc33a53a1c1",
          "sha1": "deff92be4a24ee4da356f318258d9a274cae592e",
          "md5": "cdd5b0a1774f9b8b07bccee333228e3f"
        }
      ]
    }
  ]
}
