{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.0.2518.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2518.4.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2518.4.jar",
          "size": 19697825,
          "sha512": "189661630078b81ec23741cb80c449cbbdff802e55badaa8f732d0964cb7e506ef8c2e66b5d26ff5ebe57b8300ac3b23a42af273d05d17db369edbfcd3382bda",
          "sha256": "f2ffd4a6da88a3acdd919d48f57ebc0f894b91cb3bb19b4fbc44e5a10195bdf3",
          "sha1": "e0580d7d489f933ab87f794d57f9d6d131814365",
          "md5": "8b640ad571365ce09987439ac658fe15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2518.4.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2518.4.jar",
          "size": 19697825,
          "sha512": "189661630078b81ec23741cb80c449cbbdff802e55badaa8f732d0964cb7e506ef8c2e66b5d26ff5ebe57b8300ac3b23a42af273d05d17db369edbfcd3382bda",
          "sha256": "f2ffd4a6da88a3acdd919d48f57ebc0f894b91cb3bb19b4fbc44e5a10195bdf3",
          "sha1": "e0580d7d489f933ab87f794d57f9d6d131814365",
          "md5": "8b640ad571365ce09987439ac658fe15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2518.4-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2518.4-sources.jar",
          "size": 18818519,
          "sha512": "e63329db224f19c9b913237e087e16737624b7c2111090adc1a72572def108daaa80856a1e0f3764e34276f09154ad8e826ee12b44ad221b991642557ca86708",
          "sha256": "a732e1cf8f14155db3ba5f6a95c28b9061ea96054fa0fe27c271e5fa9a64ca33",
          "sha1": "a9845da458ee9af632169d4d792f81191f044787",
          "md5": "6d68f1ef3b138847e37fec4261c53df7"
        }
      ]
    }
  ]
}
