{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.19.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.19.jar",
          "size": 374431,
          "sha512": "0e1129d0b90109cc5ac23d907363227fbff5ec33a95cea4a97a296f5e557c2cb705bbd402ceffe2257ce81ea98eeab5de166cf47b2544105886f59ffb6a5a6a0",
          "sha256": "d4287c917c633519c930f6252ac99e13fbba499c60ab7c1f7c8d7e3d25759819",
          "sha1": "b90014ab0ce448c16b3674a4c9a02108cf7d066a",
          "md5": "090aa0bce477324637a0b9d72878289a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.19.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.19.jar",
          "size": 374431,
          "sha512": "0e1129d0b90109cc5ac23d907363227fbff5ec33a95cea4a97a296f5e557c2cb705bbd402ceffe2257ce81ea98eeab5de166cf47b2544105886f59ffb6a5a6a0",
          "sha256": "d4287c917c633519c930f6252ac99e13fbba499c60ab7c1f7c8d7e3d25759819",
          "sha1": "b90014ab0ce448c16b3674a4c9a02108cf7d066a",
          "md5": "090aa0bce477324637a0b9d72878289a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.19-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.19-sources.jar",
          "size": 200731,
          "sha512": "8496699dd8febc44a76a4b22f94112fcadf5887e797b62eb3685349cebe220e6245340a85da160653d7a0f3d604d1155dc29c48697c425112ec53a323a9eb914",
          "sha256": "8ceabd1098e86a94f80bf7327efef424ac05d59ddaa44c51de6cf3871f41500c",
          "sha1": "318504985199fd5e57610f7f925afb793e4fd3f9",
          "md5": "f4eedb9fbfba58d89064328cc360f1c4"
        }
      ]
    }
  ]
}
