{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2510.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2510.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2510.0.jar",
          "size": 509481,
          "sha512": "b179bc76780e20e0454b4d7081f71bb5ac9cc352a0db718339381269766fdc772cd961080df457f022d651dc08438fb64cad59ce804f80cda018d5988714a602",
          "sha256": "5ddfd4d34727670c23f9212e05fd12100e4feaa4da8f96aec00e5d2d868a7ea7",
          "sha1": "62313ed46772f01e932fe1a94244d24f4b8b1267",
          "md5": "86572ed11d01e82ee0d6731e2ef52de4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2510.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2510.0.jar",
          "size": 509481,
          "sha512": "b179bc76780e20e0454b4d7081f71bb5ac9cc352a0db718339381269766fdc772cd961080df457f022d651dc08438fb64cad59ce804f80cda018d5988714a602",
          "sha256": "5ddfd4d34727670c23f9212e05fd12100e4feaa4da8f96aec00e5d2d868a7ea7",
          "sha1": "62313ed46772f01e932fe1a94244d24f4b8b1267",
          "md5": "86572ed11d01e82ee0d6731e2ef52de4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2510.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2510.0-sources.jar",
          "size": 250348,
          "sha512": "d40cd49098e621adf4003b7bc6a10430bdb469127cfea8359afa429d47f1cd863075fa96e8de93167bc7aa73c8623338df31733c21ba2082f03c6b19ebce6a02",
          "sha256": "1228eeac03b91902a8695be8001b85b7511d06cec95724c3f1ebc657bfee0bfb",
          "sha1": "504d1f88536fd5aba10d3fbb2949395aa1d98be4",
          "md5": "7c7cc45bea2cc0b48268f9f7a3844aaf"
        }
      ]
    }
  ]
}
