{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.4.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.4.jar",
          "size": 365605,
          "sha512": "86a09a74ae65e3ce6859ddbfdb7c41957a40eab25ee5569a4df7a23d052e5f4d458a17c0a99b681ca544cade8e04fd285e4b22a3f62f0c6c999c225bb777ecff",
          "sha256": "3c2a7a02f8d9c25889f8d9f746d4b82c6a931e15b7c54d50a7fa0a494a304079",
          "sha1": "9033d2b5b34d05e244705019a7a88187ed05640e",
          "md5": "afc75e8bb530a160f5326a253b31ab76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.4.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.4.jar",
          "size": 365605,
          "sha512": "86a09a74ae65e3ce6859ddbfdb7c41957a40eab25ee5569a4df7a23d052e5f4d458a17c0a99b681ca544cade8e04fd285e4b22a3f62f0c6c999c225bb777ecff",
          "sha256": "3c2a7a02f8d9c25889f8d9f746d4b82c6a931e15b7c54d50a7fa0a494a304079",
          "sha1": "9033d2b5b34d05e244705019a7a88187ed05640e",
          "md5": "afc75e8bb530a160f5326a253b31ab76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.4-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.4-sources.jar",
          "size": 195129,
          "sha512": "2e967dc21971ecc7b413969336950b99e7de22cb9c6af0a26b2376e3c0ca3ac9e03bac262f4e57b30a28b0d449e91f8331e85db858ffed77214493f2f5beee61",
          "sha256": "70ff492db70fc02746048e9375e81671f8cd0db304844e5afc6cba1f28f3c9e9",
          "sha1": "ff67b627c69e120f446107efad6b377815c83e7b",
          "md5": "418d1cd2ecd16bcb9740970f7cc85966"
        }
      ]
    }
  ]
}
