{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2508.2.jar",
          "size": 695072,
          "sha512": "4a1e879a89e4567aa552932188e6f6bdae64c6af4749b4e29ad72e01686ec76cfb92357fc1db65a4d6c8b46ab185bc19e607cdb801589017d126f3728f27e8cb",
          "sha256": "5b994b1a05c812ae28b777451f09deccfbc216ad6d8a437bae52f2ba937aa08d",
          "sha1": "d50958a8ad2574ff2240c461842d0349944cfa54",
          "md5": "1230596a7e797dffcd4561ed893e9825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2508.2.jar",
          "size": 695072,
          "sha512": "4a1e879a89e4567aa552932188e6f6bdae64c6af4749b4e29ad72e01686ec76cfb92357fc1db65a4d6c8b46ab185bc19e607cdb801589017d126f3728f27e8cb",
          "sha256": "5b994b1a05c812ae28b777451f09deccfbc216ad6d8a437bae52f2ba937aa08d",
          "sha1": "d50958a8ad2574ff2240c461842d0349944cfa54",
          "md5": "1230596a7e797dffcd4561ed893e9825"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2508.2-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2508.2-sources.jar",
          "size": 248183,
          "sha512": "678861dbbeb1eb2a5bb0524930473cc7301caa9ef8180a36b7acb8a60f1cb6810d04a2d2b48c4ae834eee94af1c0c291994747bd0893099a4ef3cf9bd73216a1",
          "sha256": "1de1a184b5cc3463f71cf8e06a493fad101af48211b2e0ff6afb4dc4dc4674ee",
          "sha1": "896e07e157fd788772c10825b03315c753743d1e",
          "md5": "f6f56e117ffedd110132d9387c732900"
        }
      ]
    }
  ]
}
