{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2514.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2514.1.jar",
          "size": 506176,
          "sha512": "d3e91c8fbdc7a64adaac8509fc62f8a902f71e2df7c3ddea872a9b0ff0eaf3135ecc0576c089e0a5e445fcfa8cf5ec833f957ad4d1df694e1ded2c8fc844f89f",
          "sha256": "fcb930658d3e7f41a7b7b20c3c2ee65cdd96f4da7e97d605dd097b8e546eaa65",
          "sha1": "acbb441208ad029aa1acd821077e00df8c7ccfae",
          "md5": "35baa0f1014c759c90e8d084cd6d58e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2514.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2514.1.jar",
          "size": 506176,
          "sha512": "d3e91c8fbdc7a64adaac8509fc62f8a902f71e2df7c3ddea872a9b0ff0eaf3135ecc0576c089e0a5e445fcfa8cf5ec833f957ad4d1df694e1ded2c8fc844f89f",
          "sha256": "fcb930658d3e7f41a7b7b20c3c2ee65cdd96f4da7e97d605dd097b8e546eaa65",
          "sha1": "acbb441208ad029aa1acd821077e00df8c7ccfae",
          "md5": "35baa0f1014c759c90e8d084cd6d58e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2514.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2514.1-sources.jar",
          "size": 252179,
          "sha512": "b0ea310c893900db90344fa789e96a1865a2f38cf4b6bd7b2f998331b8f452d18b8934775248480d4333aa89c80297f100c3cfdb9b1946946a6a876c7ccee1f9",
          "sha256": "4592ec0554101eb4ee5aa6762cbbe28d0292fe55435af81ddf6dbdbf4cd0efc3",
          "sha1": "e9cd8b4d8f9e6144d873c25b04c27f0b05c67a2b",
          "md5": "2870245ffac8a2f21223f40ba1afbbbe"
        }
      ]
    }
  ]
}
