{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2509.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.2509.1.jar",
          "size": 678999,
          "sha512": "821641bedb2ab60ec13726c53e972a5d82fa1e66a03a399812b3b5c22ddc70166d7ffbfc145010a84478af9f61759a8a6acb6c8388fc41261be209ffb0bfa591",
          "sha256": "71a3745aea5d1273f03e573241472d72218374914fd26e260b3ab592d542a36e",
          "sha1": "f89a2da218f2c40ae1b5b27af657994510f756d5",
          "md5": "a8a2d77d019d71e35e2a65b32800fd2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2509.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.2509.1.jar",
          "size": 678999,
          "sha512": "821641bedb2ab60ec13726c53e972a5d82fa1e66a03a399812b3b5c22ddc70166d7ffbfc145010a84478af9f61759a8a6acb6c8388fc41261be209ffb0bfa591",
          "sha256": "71a3745aea5d1273f03e573241472d72218374914fd26e260b3ab592d542a36e",
          "sha1": "f89a2da218f2c40ae1b5b27af657994510f756d5",
          "md5": "a8a2d77d019d71e35e2a65b32800fd2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2509.1-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2509.1-sources.jar",
          "size": 250233,
          "sha512": "dc162efd9e0d3dff99c72f02b487d44a221b4dab72a483453f8149cf6f80cf860aa4396ed9068bd97e66451f37a52a38a708148c5716ae7fb99cdfa883e2aaae",
          "sha256": "2c075b67c6cf8a26e72834ffe91701898eb0a0f2deed5d784270d810586dd10b",
          "sha1": "b797740aefa7b8ca95e721da39e321a6db91cbef",
          "md5": "7df70da5afb63950d5689abcb0d849d1"
        }
      ]
    }
  ]
}
