{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.3.jar",
          "size": 465086,
          "sha512": "a7322d7ce8eee62eba2c98cdf75747a3beabd4763bea44bd234a647f3372a846f985b40d8ecbcf123e11f5320a47ee0743494186f8b3c8f4d72da2e8e7dbd4f6",
          "sha256": "1223bf57e3f3b32f475d3270cef62be41db0d2af518c997b8d7509896430ef35",
          "sha1": "c689c9d7fea350e170a402cac79176c91d67329f",
          "md5": "02c8906cbc68a44097a375209a563dc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.3.jar",
          "size": 465086,
          "sha512": "a7322d7ce8eee62eba2c98cdf75747a3beabd4763bea44bd234a647f3372a846f985b40d8ecbcf123e11f5320a47ee0743494186f8b3c8f4d72da2e8e7dbd4f6",
          "sha256": "1223bf57e3f3b32f475d3270cef62be41db0d2af518c997b8d7509896430ef35",
          "sha1": "c689c9d7fea350e170a402cac79176c91d67329f",
          "md5": "02c8906cbc68a44097a375209a563dc9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.3-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.3-sources.jar",
          "size": 231541,
          "sha512": "d6715a0831110aa53cf6b76276c0bf92484cc11bfeb404d4ffae0a7db9946902dde6a1d20b41f84bd88fb7c8d1fdcbc7bb39f1dab23038cd18883e91a6ba3c60",
          "sha256": "8e2d20c15577a0ee2c9d1d813b5435b83ce16474808a98571949f07d445c803c",
          "sha1": "a2fb60d22f3c43935014486fdd6e13df62ad31a2",
          "md5": "f4a1a39286761da82379d722e5f8a68a"
        }
      ]
    }
  ]
}
