{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2504.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.2.jar",
          "size": 452075,
          "sha512": "d64c66540b151c4f5fb87e54d32cfdbc687a8990f63f1a6d65b4b1ff13d7a342cab8dddd31e5722d19400721ef23f4ab79f00cc14b0fef303d0b9c73db12d930",
          "sha256": "a50fb98c895adae858deaf8f3fee62bb0b622ae2dadba1183bc6afed6835ab63",
          "sha1": "3b73d0eb1ead90334f076ac1c918d872b25ffdf0",
          "md5": "4aff96d86943acedfb555ad92bf77b3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.2.jar",
          "size": 452075,
          "sha512": "d64c66540b151c4f5fb87e54d32cfdbc687a8990f63f1a6d65b4b1ff13d7a342cab8dddd31e5722d19400721ef23f4ab79f00cc14b0fef303d0b9c73db12d930",
          "sha256": "a50fb98c895adae858deaf8f3fee62bb0b622ae2dadba1183bc6afed6835ab63",
          "sha1": "3b73d0eb1ead90334f076ac1c918d872b25ffdf0",
          "md5": "4aff96d86943acedfb555ad92bf77b3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.2-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.2-sources.jar",
          "size": 231251,
          "sha512": "78039f7b5432b190c194488e2dfc5083d110fefe268b07a8e1d6d93bace1aab4bf998ae07e6333ebe73708a998987846a74aa371bd5f6ed4ddf95713594cfdc1",
          "sha256": "b1cebccb09aa3bf67d7b216c3b965adbd7ead53679108953e00082795082c1b7",
          "sha1": "66ffab6ce7babf847476329ffefb57c710d2c118",
          "md5": "691cc977d729747892413e51674bc826"
        }
      ]
    }
  ]
}
