{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.1-1.1.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2516.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.2.jar",
          "size": 646119,
          "sha512": "57c94da85930c56aba7f880edaec440be91b655abe6f7d7372737739eedf46784f9aca09ff6aaf05dd1f60790554829ecfb8cbc022462a0f0e0df39a242d0993",
          "sha256": "a2ba7e5b995526f256d5b85bb75b1f0e7c7466eb96b0c31b9a05fdc873085456",
          "sha1": "ec8b2a17fde60dfced8cb7ee30d224f1a3702ae6",
          "md5": "b759c82f97a800f95d07fc1e11550f06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2516.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.2.jar",
          "size": 646119,
          "sha512": "57c94da85930c56aba7f880edaec440be91b655abe6f7d7372737739eedf46784f9aca09ff6aaf05dd1f60790554829ecfb8cbc022462a0f0e0df39a242d0993",
          "sha256": "a2ba7e5b995526f256d5b85bb75b1f0e7c7466eb96b0c31b9a05fdc873085456",
          "sha1": "ec8b2a17fde60dfced8cb7ee30d224f1a3702ae6",
          "md5": "b759c82f97a800f95d07fc1e11550f06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.2-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.2-sources.jar",
          "size": 585770,
          "sha512": "f5e0c90227b43929fbd605df8527b2a607186a5adeaf6273063ac0964200b5c3c6fc95fda7edc7782759456c4ba6da21ef744dee9844e494484d5200d1b3bf6c",
          "sha256": "ebdb1e4971df163d1e39827a6323b2d2d1a19adaf5938f0b221ed423b6676981",
          "sha1": "8a371b087d94bca1258f235e11474541027b3603",
          "md5": "8bd00f43dc501eb66aaa20a3f727f1b8"
        }
      ]
    }
  ]
}
