{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.7.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.7.jar",
          "size": 431845,
          "sha512": "c11cdcbd19f9123d7ff957c1459e3e8c32f99b38a1de9d2b98780624d89049bc5637d5c4483e43512583478a769881e86657475459e7a4fa1a8c21af2742ff06",
          "sha256": "0c041f8e6944ac55e0a5737a7f52b1e515bec99633167e7d8f3701e621a409f7",
          "sha1": "307c0d44d13d26f66666375cf7ebffd7fd77536b",
          "md5": "32b266510d2b1e1ae4dcd6ccb9016691"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.7.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.7.jar",
          "size": 431845,
          "sha512": "c11cdcbd19f9123d7ff957c1459e3e8c32f99b38a1de9d2b98780624d89049bc5637d5c4483e43512583478a769881e86657475459e7a4fa1a8c21af2742ff06",
          "sha256": "0c041f8e6944ac55e0a5737a7f52b1e515bec99633167e7d8f3701e621a409f7",
          "sha1": "307c0d44d13d26f66666375cf7ebffd7fd77536b",
          "md5": "32b266510d2b1e1ae4dcd6ccb9016691"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.7-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.7-sources.jar",
          "size": 223825,
          "sha512": "cfb6005d91ae90ade38a91cf1f48e8bbf9ea4822e53ab630b02d2743ce85ee6e67986889cc62975289adf3410569002f64508b9d8f775e2e1a19b481ccd3bb9a",
          "sha256": "df86a4f1fb0b7ae909c19ec739a52396830f4f39aa3c46b4ce217f01760d6743",
          "sha1": "6c1effc94d9495269cccb5717aca9e6696ee5d9b",
          "md5": "32e930cb3236977284d3d462166ef7d3"
        }
      ]
    }
  ]
}
