{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2513.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.3.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.3.jar",
          "size": 513761,
          "sha512": "f4c3c11795e2da5878d6a66fb150d83623674492089c6e9b8198003450c5a22ce51cc6ef327be74c27ba2352a44424849e1224cc42fae33fe3ad20a28cd7c214",
          "sha256": "73da0f7117c8aed168edcd9cdc7160aafbb86d564dde46a79ead2719fbbf355e",
          "sha1": "1abb2eafe76f72cd07e3330f117d9414cbae4e73",
          "md5": "713f99b44094881f4b467fb330a84453"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.3.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.3.jar",
          "size": 513761,
          "sha512": "f4c3c11795e2da5878d6a66fb150d83623674492089c6e9b8198003450c5a22ce51cc6ef327be74c27ba2352a44424849e1224cc42fae33fe3ad20a28cd7c214",
          "sha256": "73da0f7117c8aed168edcd9cdc7160aafbb86d564dde46a79ead2719fbbf355e",
          "sha1": "1abb2eafe76f72cd07e3330f117d9414cbae4e73",
          "md5": "713f99b44094881f4b467fb330a84453"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.3-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.3-sources.jar",
          "size": 250613,
          "sha512": "0c301ee1c8f50de34af6121ccf9b6c2c24af61843c076848aec4ad54608ddde50b7535ed4bf066ab3c42830279eca6e8db0b40d1e6bf86e4c8f023892de8037b",
          "sha256": "a6a9e2ef315e5bdb333d92f6854843a25dd7e4e7286a4b9359e42ffee6f7aaf0",
          "sha1": "2aadad0376e9a13a93eb77734eb9fea90fc9b430",
          "md5": "54ee019681aff9fc402e9b7b30c21ba5"
        }
      ]
    }
  ]
}
