{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.4-1.1.2518.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2518.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2518.0.jar",
          "size": 643330,
          "sha512": "ed99b8e723f292a1744cd49c2d0ff7517513277ef378b311a9acc7567bea4dc2f8b06a96449359755f7dc74503215c9842c7bc93315098b683fafdd70b65c0e9",
          "sha256": "eb0da4d5f41e3bb50aeee29ab9ed701cd41d2cc77eb03ecdeaf104c23ef0aac6",
          "sha1": "f55a1f6f4ab98ce4243ff820547754fc2e9915b6",
          "md5": "772dff59732aac4fc4ff6b48a11543f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2518.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2518.0.jar",
          "size": 643330,
          "sha512": "ed99b8e723f292a1744cd49c2d0ff7517513277ef378b311a9acc7567bea4dc2f8b06a96449359755f7dc74503215c9842c7bc93315098b683fafdd70b65c0e9",
          "sha256": "eb0da4d5f41e3bb50aeee29ab9ed701cd41d2cc77eb03ecdeaf104c23ef0aac6",
          "sha1": "f55a1f6f4ab98ce4243ff820547754fc2e9915b6",
          "md5": "772dff59732aac4fc4ff6b48a11543f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2518.0-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2518.0-sources.jar",
          "size": 585421,
          "sha512": "594597151fa8dad1251dca09ca8f255d44d225a2e3c0e973df30fcceea7dab6a0d9624531ee14383ce972dc8b38fb626dfae0c2b86104970580879db8bba4b32",
          "sha256": "da23b3b0e03a2688f19d82fc16baa537929e264fa3c3dc4d5363e8f9de96dac5",
          "sha1": "85c8c2f581bc4055b9cb55ef1f16f841a1549d2d",
          "md5": "05beb95cc5e667544628654e535e4173"
        }
      ]
    }
  ]
}
