{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.5-1.1.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2515.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2515.0.jar",
          "size": 520079,
          "sha512": "c34c61b3a29d1bab329ec257e68a224e7636948f3540d6365b43d7c0e539e7ce1c2d32ae09683a1931269e6c7184bc981bb9f551190180760a09cea90ba6ae54",
          "sha256": "8519a36ea76941e1b5d614df44fa4b1185cfb47f0e779d73f7d33eb2ca22cfc7",
          "sha1": "9f6b17dea28c01688531e00ff17cb76dcfd2c380",
          "md5": "e232b58eb5eb8ae5484d4464156e8fea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2515.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2515.0.jar",
          "size": 520079,
          "sha512": "c34c61b3a29d1bab329ec257e68a224e7636948f3540d6365b43d7c0e539e7ce1c2d32ae09683a1931269e6c7184bc981bb9f551190180760a09cea90ba6ae54",
          "sha256": "8519a36ea76941e1b5d614df44fa4b1185cfb47f0e779d73f7d33eb2ca22cfc7",
          "sha1": "9f6b17dea28c01688531e00ff17cb76dcfd2c380",
          "md5": "e232b58eb5eb8ae5484d4464156e8fea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2515.0-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2515.0-sources.jar",
          "size": 451995,
          "sha512": "d3d6cce4e4e3a73f8ba29902f7562bf3a2b13625da2cfc4121829199ee57789ab25be46e6b10a65144b19e638630456eae4cd4c4ce1465c31be56b79a96865d6",
          "sha256": "f53af7121a56adaf3587de2efa18692f2e1672d35d2046f8ffc2860b0590caab",
          "sha1": "2a6389dbea46dfaa522908159f946de552691988",
          "md5": "a48e0d9563b2b3cbaf1c19e155e69cd4"
        }
      ]
    }
  ]
}
