{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.8.3-lts",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.3-lts.jar",
          "url": "legacy-neoforge-1.21.3-1.8.3-lts.jar",
          "size": 19917161,
          "sha512": "70b655bb9d4ee0e21ad7a0935c002a5bddb3ef4d1c262457c7c6faa5fa6c4aee3a880b97f9b1334f104d5be463a506dcff1b6fc6a4e28e218f0d47a7f3e77e25",
          "sha256": "d51a135fd303d394c776d9428d938ed8ce15765e02f6d42d626a4c78374c303f",
          "sha1": "498f6dc7a89875ac5c1c97ab74fb116a0ba05340",
          "md5": "a54ff9e5820aa92842338dc3c0b0907c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.3-lts.jar",
          "url": "legacy-neoforge-1.21.3-1.8.3-lts.jar",
          "size": 19917161,
          "sha512": "70b655bb9d4ee0e21ad7a0935c002a5bddb3ef4d1c262457c7c6faa5fa6c4aee3a880b97f9b1334f104d5be463a506dcff1b6fc6a4e28e218f0d47a7f3e77e25",
          "sha256": "d51a135fd303d394c776d9428d938ed8ce15765e02f6d42d626a4c78374c303f",
          "sha1": "498f6dc7a89875ac5c1c97ab74fb116a0ba05340",
          "md5": "a54ff9e5820aa92842338dc3c0b0907c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.3-lts-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.8.3-lts-sources.jar",
          "size": 19024995,
          "sha512": "db764ceddaba37707f2138e5309e9e95d8748caf28bbe9521c922a6fdcef302d5851d0db4cfca75e2d9bcf432e2a25521df34d28d156e585d3289a70443aa19b",
          "sha256": "74b615e6abb2d52ce5c25ac6bc689310bf0c4f46e71ae84bfaf23b71d1dbaa5c",
          "sha1": "0e92e8aa94f02956bc12fb1bc47472e85b25eca8",
          "md5": "0f2f3c2e52e15c9e7c3f2fe09e73e5fa"
        }
      ]
    }
  ]
}
