{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.2.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.2.jar",
          "size": 18296084,
          "sha512": "f264be301150d148a9a4fef2f5a2fa6b07a95eb28331921a6b7e6c44627a8a283deb97b6f025c2cc77ecfa8bfcd9ca8712144b5751021481ff6cba4dc8f1ae75",
          "sha256": "4320e41c2ed6c33bacb61e5f063ddc552dc941e079120592f859a1340e61ce1a",
          "sha1": "164ed41d8ec6b48f5842d7f8047d453c6833227e",
          "md5": "c21828db677f41d184cc101098a425ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.2.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.2.jar",
          "size": 18296084,
          "sha512": "f264be301150d148a9a4fef2f5a2fa6b07a95eb28331921a6b7e6c44627a8a283deb97b6f025c2cc77ecfa8bfcd9ca8712144b5751021481ff6cba4dc8f1ae75",
          "sha256": "4320e41c2ed6c33bacb61e5f063ddc552dc941e079120592f859a1340e61ce1a",
          "sha1": "164ed41d8ec6b48f5842d7f8047d453c6833227e",
          "md5": "c21828db677f41d184cc101098a425ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.2-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.2-sources.jar",
          "size": 17433856,
          "sha512": "da5380f16afbaf9b9019a0ab9af1b495a09b998fe904e437053dc9e04e112d0af9352c7b8bfc4163817131cd0ca2fc344c40c2affe7bf8756132b52b588bb278",
          "sha256": "be7a86ce9b7801ad7c7be67174df4a631bfd2e9627952a6ef43b3af7c70371e2",
          "sha1": "13b07e6cace0ba90fbcede75c9a074bd0dd19a2c",
          "md5": "fd36543116322315982d3e584f5d6420"
        }
      ]
    }
  ]
}
