{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2502.9.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2502.9.jar",
          "size": 465657,
          "sha512": "1ec6236321055bb8e875b0bde501c2a327008697a2a3af79fb3bdac152e3fc9d627465746c7add46bd6ec514bd7adf3aaa075d4246239726e4d227daad6124a9",
          "sha256": "912078d7b87d2cb4b82089a328d24c5490f8ae0b46502023c55a7e0d14aca1b7",
          "sha1": "6a996e2cede82e709fd170e3f7e906636e7034f0",
          "md5": "f19068238b40a55025c6c0392cac652e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2502.9.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2502.9.jar",
          "size": 465657,
          "sha512": "1ec6236321055bb8e875b0bde501c2a327008697a2a3af79fb3bdac152e3fc9d627465746c7add46bd6ec514bd7adf3aaa075d4246239726e4d227daad6124a9",
          "sha256": "912078d7b87d2cb4b82089a328d24c5490f8ae0b46502023c55a7e0d14aca1b7",
          "sha1": "6a996e2cede82e709fd170e3f7e906636e7034f0",
          "md5": "f19068238b40a55025c6c0392cac652e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2502.9-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2502.9-sources.jar",
          "size": 220927,
          "sha512": "a327963e5848e233313cd64dd784c8ed44f29d512585c75b37372bc4729554e0b0bb74472a0b6d92b3e200b8c34e8599c9eb0406ec609f169bd5006af355c26c",
          "sha256": "3ddd13e365ee136a2a1eea450a8dd22083f0e2f296435c2ea5ff560009eda171",
          "sha1": "3f47b84edbf05a0da85d2797b13818f09b94f686",
          "md5": "f766bab8afa01ac8bb68a6a10c14d82e"
        }
      ]
    }
  ]
}
