{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2513.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.1.jar",
          "size": 700371,
          "sha512": "abbf17d4289033de0064f0f29129ee9d31f73faaf8f627444dfb6e678e53f338766eda1a6fc8ace32f3dcef9f6ad2f188e12e393d2e0ca47c9e0b1078af07190",
          "sha256": "fd742325c012b9e393f854350040003039d373d89a0fd17870cded5be087135a",
          "sha1": "c74a062e71322dfd53be9544b0927f589407132e",
          "md5": "0d93a83e8af15f7d016768b9616b1a42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.1.jar",
          "size": 700371,
          "sha512": "abbf17d4289033de0064f0f29129ee9d31f73faaf8f627444dfb6e678e53f338766eda1a6fc8ace32f3dcef9f6ad2f188e12e393d2e0ca47c9e0b1078af07190",
          "sha256": "fd742325c012b9e393f854350040003039d373d89a0fd17870cded5be087135a",
          "sha1": "c74a062e71322dfd53be9544b0927f589407132e",
          "md5": "0d93a83e8af15f7d016768b9616b1a42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.1-sources.jar",
          "size": 250840,
          "sha512": "23dc125aadea9c26bd08085d4f8ff4adcbf4e4d4153afc030f907268f71e6ea6275ef6213145db5115f613b29ded25a14c929ccaf3931a9c03862281c90e63f5",
          "sha256": "654914a927471b56f401517909b172b591ab433348475e3c7d7594a0223f4487",
          "sha1": "715c3865de424e06bd5651a759ea2696002fa38a",
          "md5": "f4e2bc87cb02e9cb657ea70ce8121a42"
        }
      ]
    }
  ]
}
