{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2515.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2515.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2515.2.jar",
          "size": 707819,
          "sha512": "c6f8e3358f9312856f3b971d7837bdc98e2bf9412d90f23e40f4cb0503d4802d7623dfef7d6914b0fdd1c9c2ea1351ac0025ee7070ee0ac07e14bac2f8333d65",
          "sha256": "1b666348eb3cc76258151bb98acab2653af6f6c59d094d0e892d3badd440873a",
          "sha1": "8abacbad66bf6fc21226f85030937a72fe55ee54",
          "md5": "56a8edacacafa9be23acdba94bb3987f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2515.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2515.2.jar",
          "size": 707819,
          "sha512": "c6f8e3358f9312856f3b971d7837bdc98e2bf9412d90f23e40f4cb0503d4802d7623dfef7d6914b0fdd1c9c2ea1351ac0025ee7070ee0ac07e14bac2f8333d65",
          "sha256": "1b666348eb3cc76258151bb98acab2653af6f6c59d094d0e892d3badd440873a",
          "sha1": "8abacbad66bf6fc21226f85030937a72fe55ee54",
          "md5": "56a8edacacafa9be23acdba94bb3987f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2515.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2515.2-sources.jar",
          "size": 253236,
          "sha512": "38cdadd734f46aafc7a6b07735176b9c2fb12fed012690de85c6b43c5b2dd306ed088afdedab2e7ad184a7a190ee754c3d87e4170f02278a6350323b78cd0ef3",
          "sha256": "da5bc39bdae16117420223050ef7a71b440c9732debbcdf5bfe309e5e6b53f3f",
          "sha1": "efae8cf2570022c44248548c70c64cfa28328531",
          "md5": "a666b7bdd1e347fb34abda36ac85974a"
        }
      ]
    }
  ]
}
