{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "size": 546053,
          "sha512": "a2e206f6f1e65c3ccc196efb6d801cc3f8baf7d5e05f6d3e049c24bfde852ae14b3a6ab41c6c0e8d0f13c16051afcc955c3cb1041b38292a1546ba2d1b6aabea",
          "sha256": "c98a6185e91721a22864eddd8e5711477589ed02aea0f8ef51d7afc487a8b69d",
          "sha1": "eb45f739d6aef42432dc75057fe7952d80ce6956",
          "md5": "380682a0b1542ef3570e4d7a2667feef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "size": 546053,
          "sha512": "a2e206f6f1e65c3ccc196efb6d801cc3f8baf7d5e05f6d3e049c24bfde852ae14b3a6ab41c6c0e8d0f13c16051afcc955c3cb1041b38292a1546ba2d1b6aabea",
          "sha256": "c98a6185e91721a22864eddd8e5711477589ed02aea0f8ef51d7afc487a8b69d",
          "sha1": "eb45f739d6aef42432dc75057fe7952d80ce6956",
          "md5": "380682a0b1542ef3570e4d7a2667feef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2545.0-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2545.0-sources.jar",
          "size": 268567,
          "sha512": "4c3dbb2e695dfd07da1cac856a3e9e64f5cbc16d5168fe5808a005ef9f2f5f479cf4af57be8286c100fd6205ec761b062050bb7efa6598743cb793a8de58f151",
          "sha256": "c6cef053411fc21277d6565173d4d026ca9656dc25d17ba7bd8c1bf9862a2f8b",
          "sha1": "bc9d3da1eb1cfd3fa58b6219410554f9d8ab0ce6",
          "md5": "0deab14b3b5829cc53ac62012091e9ea"
        }
      ]
    }
  ]
}
