{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "size": 546411,
          "sha512": "227a1949c3f466d19f76f99bfb20ff74babad926e82142575defea63b8b5f77b0bbb880dae63b4203e2ef6d60ad0aebfef300aa0928d1cba7cee4b3ec5b08aa9",
          "sha256": "c19957917cad2cb709ed92a2ebde4252ddb9ca38a543488441ce045b301dc7c6",
          "sha1": "d36ee5b6dc58f6840c81eb89ec20e7091e0ae911",
          "md5": "b44930df9c9036d9457210320f695062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2545.0.jar",
          "size": 546411,
          "sha512": "227a1949c3f466d19f76f99bfb20ff74babad926e82142575defea63b8b5f77b0bbb880dae63b4203e2ef6d60ad0aebfef300aa0928d1cba7cee4b3ec5b08aa9",
          "sha256": "c19957917cad2cb709ed92a2ebde4252ddb9ca38a543488441ce045b301dc7c6",
          "sha1": "d36ee5b6dc58f6840c81eb89ec20e7091e0ae911",
          "md5": "b44930df9c9036d9457210320f695062"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2545.0-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2545.0-sources.jar",
          "size": 268482,
          "sha512": "46cd53a89c7f82f6db3d687af84a2083c15a31c9f8e9d056b5f57efd4f1b7f04b1585cb938ea9ba8a3b0c4db442722d845587b5e7c25469dea041719881d44a3",
          "sha256": "299f688f174528d306686142991321b625120ab58837c3a831abc42a4c167cc7",
          "sha1": "143fc301d0c73d8f2cfd679435c2dac700d7f3cf",
          "md5": "dff73cfe76287e93a19ffe21f1583fc3"
        }
      ]
    }
  ]
}
