{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "size": 542100,
          "sha512": "d1bb6d62a1ca68a29c11b98759f217a881bdd8f2f08763f31a0daafaa02f206418a85612ed5106e506be3882996044dca95e14522a1fcd284d9b0293f061fa70",
          "sha256": "220ab12cdec5d3d1e0469530ad8dc8e1974d343844860ea2eb39fe319cae1e54",
          "sha1": "a913af281dc784616ce8acbb11201c389a4520e4",
          "md5": "e701ef712a9f23495a5baeb77875321c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "size": 542100,
          "sha512": "d1bb6d62a1ca68a29c11b98759f217a881bdd8f2f08763f31a0daafaa02f206418a85612ed5106e506be3882996044dca95e14522a1fcd284d9b0293f061fa70",
          "sha256": "220ab12cdec5d3d1e0469530ad8dc8e1974d343844860ea2eb39fe319cae1e54",
          "sha1": "a913af281dc784616ce8acbb11201c389a4520e4",
          "md5": "e701ef712a9f23495a5baeb77875321c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2545.0-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2545.0-sources.jar",
          "size": 268503,
          "sha512": "769638b5e9b8e13c07be2631380c42d48686cfeddaf06f95351d2b8fc0069c92773c3a9c834020ce319678df0e7c411a87200f5ae0f21e6b5787ef6e523162e4",
          "sha256": "2429cccc20728a9041ba344050ba176213b43c31d07a655322ff7bf50c11dcf0",
          "sha1": "418c59d52c28dc8aabaa4f2f4688a05a84084452",
          "md5": "0cbb5f7f9f81a5ab85c319491156d65f"
        }
      ]
    }
  ]
}
