{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "size": 541742,
          "sha512": "5af97df90fb1df18f548ff7bedd75ce12d06d3f9da925dce843957c10c8dc88f4529e35dbac348417f24549cce967f3ae5fed759fcc601e7cccda8e249a60038",
          "sha256": "74474911e00c5d5fe561c5d22ccd944c1b3e06edd2522652ec6ce49f1a57b68e",
          "sha1": "21f09275f57455198c543b14573743d88bc980d9",
          "md5": "ab53be56edcd2f55e236c0107b71e8d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2545.0.jar",
          "size": 541742,
          "sha512": "5af97df90fb1df18f548ff7bedd75ce12d06d3f9da925dce843957c10c8dc88f4529e35dbac348417f24549cce967f3ae5fed759fcc601e7cccda8e249a60038",
          "sha256": "74474911e00c5d5fe561c5d22ccd944c1b3e06edd2522652ec6ce49f1a57b68e",
          "sha1": "21f09275f57455198c543b14573743d88bc980d9",
          "md5": "ab53be56edcd2f55e236c0107b71e8d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2545.0-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2545.0-sources.jar",
          "size": 268588,
          "sha512": "9104dcf7bb7c299a51dccf030b72f2dc62e116493b3fc3ef1594421ed2193834ed4b69f107116146c3c2991c68cbe99bcfc7c1bd0d22f346a118a9c49e234d6a",
          "sha256": "e35ddfb13e6022b041cf34b975a0c66c1e64d05a736eda81dcc4c85d1ae0e893",
          "sha1": "5bf3b4b7f9bba4947b58063bf06faa4f653d8a29",
          "md5": "ee64465342cb4a15c3c83dbd9fcbf5c3"
        }
      ]
    }
  ]
}
