{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2500.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.2.jar",
          "size": 345504,
          "sha512": "b1e1ae77e3fd2a93656865e3fd054956dc239a1ef1c493219b122ec867af70e3dad776960c1d51a5027d7637909581f478354e7c7fdd198cea0a2424e0c2aedf",
          "sha256": "bbe670fc9f596555f6bad4a4ce7f65e54edb272c3b284b675c718338e8508603",
          "sha1": "c8ce7add9302c6a6022935afbf3873eda088c529",
          "md5": "649017da531034bc91767cdf3aecd41f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.2.jar",
          "size": 345504,
          "sha512": "b1e1ae77e3fd2a93656865e3fd054956dc239a1ef1c493219b122ec867af70e3dad776960c1d51a5027d7637909581f478354e7c7fdd198cea0a2424e0c2aedf",
          "sha256": "bbe670fc9f596555f6bad4a4ce7f65e54edb272c3b284b675c718338e8508603",
          "sha1": "c8ce7add9302c6a6022935afbf3873eda088c529",
          "md5": "649017da531034bc91767cdf3aecd41f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.2-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.2-sources.jar",
          "size": 191101,
          "sha512": "fbaed5d626304166a4cc624d185a0d1afa6792a5a5364b5378cb90679942a816a7380647da01631786d4c777ef09bc4cc86db9fa5951ba9d42bb38a8003afcad",
          "sha256": "4769ed5623786fb379b64d5ccd6fdb8673fd420adf91060820251ec0dea3f5b4",
          "sha1": "e85b493f41d916d418d5f21996618a4c2b58afb8",
          "md5": "eab57c457b6cebc94b0579b5a043e817"
        }
      ]
    }
  ]
}
