{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2516.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.4.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.4.jar",
          "size": 696845,
          "sha512": "8921039024a1c93698e654a8ce8a4d168f0b93cbda23d2cd9c57ef019983f51c07d98d3c6c8a1dc4754654729af7ef20b1bd9ec2249a44c3650c8a523f137697",
          "sha256": "a537def32da952859abd5a4a433f7e1380c0850578f90d564f0bf43d9b123462",
          "sha1": "05cf88085e2f108dec41ac02f791db03f1776935",
          "md5": "7bf7a244c57553ce6b6107c79667f62f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.4.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.4.jar",
          "size": 696845,
          "sha512": "8921039024a1c93698e654a8ce8a4d168f0b93cbda23d2cd9c57ef019983f51c07d98d3c6c8a1dc4754654729af7ef20b1bd9ec2249a44c3650c8a523f137697",
          "sha256": "a537def32da952859abd5a4a433f7e1380c0850578f90d564f0bf43d9b123462",
          "sha1": "05cf88085e2f108dec41ac02f791db03f1776935",
          "md5": "7bf7a244c57553ce6b6107c79667f62f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.4-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.4-sources.jar",
          "size": 253786,
          "sha512": "f70917e2e82de55577f5c0ad8506fed1e2ef071c02ab9ab7550277f1148b525af06bbde3d508e751bf72f48196fecb8d49c9e1b43f59796b29acd904d3c4d3de",
          "sha256": "87f3d3cd43532526bc56822802d7bf951154e391b46633d64c29daba412f6e8d",
          "sha1": "4614bb6451213b0b9a4e5785299bedc6c81d8abd",
          "md5": "ccd0287563a55e1d6ddde03b092d93e2"
        }
      ]
    }
  ]
}
