{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.7.10.2501.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.2501.20"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2501.0.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2501.0.jar",
          "size": 11891299,
          "sha512": "3882df5462833f3cf4ad2e7a4daf0fa3cd24201940580184895080d1cbbce71490ff6c69c688037151b417c4623ea35f4a1d440dd08c8daf3e677fe7bf9acf22",
          "sha256": "2e74460e8c57194c6689bc11f13e8514e8ebd4939fa726ebefb21cd71ee176f3",
          "sha1": "a6d280ac42a553a866d12147b04ed9ae09680aba",
          "md5": "5ccdac52660b583e57688e17122b5c6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.2501.20"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2501.0.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2501.0.jar",
          "size": 11891299,
          "sha512": "3882df5462833f3cf4ad2e7a4daf0fa3cd24201940580184895080d1cbbce71490ff6c69c688037151b417c4623ea35f4a1d440dd08c8daf3e677fe7bf9acf22",
          "sha256": "2e74460e8c57194c6689bc11f13e8514e8ebd4939fa726ebefb21cd71ee176f3",
          "sha1": "a6d280ac42a553a866d12147b04ed9ae09680aba",
          "md5": "5ccdac52660b583e57688e17122b5c6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2501.0-sources.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2501.0-sources.jar",
          "size": 11112178,
          "sha512": "c0a616da49646715acc32cd1a245e34b68173756b5887467d201e7c73eee32be49acacd0deacffc129e6b1448270dcb6fc62c84805f038b317be722a14ff226f",
          "sha256": "a549ad1d1c80221b68b0d620b120e97979b6a1ca45ecafef02f61ba4fb470df4",
          "sha1": "6d48e806e6b39f877a6e6526461638e8ccbe8a32",
          "md5": "32b317db9a7afaa379d2fbf33daaad88"
        }
      ]
    }
  ]
}
