{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.5-2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.6.jar",
          "url": "factory_api-fabric-1.21.5-2.2.6.jar",
          "size": 568311,
          "sha512": "4ec26a80f4e71f9a6106de586d426fe8d8e479eefb911c250b99cd265787fd1832009531173f288bcba95984e9f5722d5666ed9a611560886d02d30e2f60c3da",
          "sha256": "bd66cf3dcc83fedd2ed01d5e743c4da3abb26f70cf22a1bda0c9120f348cd838",
          "sha1": "05a88c2604babc27817149c3cbe0cf316f550e20",
          "md5": "28bd179bcaaf4124de66e0a820c913b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "14.0.0-rc.2"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.6.jar",
          "url": "factory_api-fabric-1.21.5-2.2.6.jar",
          "size": 568311,
          "sha512": "4ec26a80f4e71f9a6106de586d426fe8d8e479eefb911c250b99cd265787fd1832009531173f288bcba95984e9f5722d5666ed9a611560886d02d30e2f60c3da",
          "sha256": "bd66cf3dcc83fedd2ed01d5e743c4da3abb26f70cf22a1bda0c9120f348cd838",
          "sha1": "05a88c2604babc27817149c3cbe0cf316f550e20",
          "md5": "28bd179bcaaf4124de66e0a820c913b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.6-sources.jar",
          "url": "factory_api-fabric-1.21.5-2.2.6-sources.jar",
          "size": 257233,
          "sha512": "ef2569df13a352fa4f3d37738c75cd1e23a3bce8a0b0b1c30f0de6f00c11e5485b649eced8687879cc978e1d9e7800f2954329fbb8fac25710474ebc10a3b841",
          "sha256": "95610f10a941ebe2511cbace38b79f755cb326e384f6ffe6258664cea20fc5da",
          "sha1": "e5766a61efd0ea04001765955fdd34e6141b2e71",
          "md5": "aeda8a76d4584711ccbff2b9475ec1d9"
        }
      ]
    }
  ]
}
