{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2504.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.5.jar",
          "size": 449131,
          "sha512": "f1d47aa2275ccd1a2f3221ad070433059f31bd60bbec7b2791f311e96079b539a9e25ffbc2b0788df19f99fcf5d45549ddcf8e9b971261ec5a2d1474da6be174",
          "sha256": "b24ad44ebf7c44657e86c028b1db2f47bfdac32293fe86ac5d65f190f36db07f",
          "sha1": "26ffae558118710aed4007d114042782cdda5a14",
          "md5": "3c54d6863853f8ea06393373a2601325"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.5.jar",
          "size": 449131,
          "sha512": "f1d47aa2275ccd1a2f3221ad070433059f31bd60bbec7b2791f311e96079b539a9e25ffbc2b0788df19f99fcf5d45549ddcf8e9b971261ec5a2d1474da6be174",
          "sha256": "b24ad44ebf7c44657e86c028b1db2f47bfdac32293fe86ac5d65f190f36db07f",
          "sha1": "26ffae558118710aed4007d114042782cdda5a14",
          "md5": "3c54d6863853f8ea06393373a2601325"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.5-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.5-sources.jar",
          "size": 231790,
          "sha512": "6bf82115b572cd39d97536ec4aed3a2c5b2f1ba24b9643b674c5b541e59bcae1359f2d355abe145910eb4a2d97c9a47b05cf7e6aa68a5700b28316fafb9efa12",
          "sha256": "d13fcfc7becf0ff38ec818bc3007a54972a8208d8ec61daadb25d15241f4ae8a",
          "sha1": "44714eab2bff8c2474cca36dc31dddfbac0dab26",
          "md5": "1b0d872a22f5c47e5d3bc9bae63cf0fd"
        }
      ]
    }
  ]
}
