{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.8.0.2511.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2511.2.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2511.2.jar",
          "size": 18250008,
          "sha512": "a45e7e502a737f86339df4ae06dca4072087741dfa765f43c1eeeac43a8e4b6f006241ed4bde60be173e3f5b6b297c94c7a638e3e3e1162cc48795303b2c9b24",
          "sha256": "9cf8e2d881b001a60f5145e60c9fbfb64799ec25f5b02e72c3fb1c68ac17c9fd",
          "sha1": "50736b234a3df8c1c36c57215914e9d41d1ed542",
          "md5": "2773b4dc2c6cc489812cfecda20a0216"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2511.2.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2511.2.jar",
          "size": 18250008,
          "sha512": "a45e7e502a737f86339df4ae06dca4072087741dfa765f43c1eeeac43a8e4b6f006241ed4bde60be173e3f5b6b297c94c7a638e3e3e1162cc48795303b2c9b24",
          "sha256": "9cf8e2d881b001a60f5145e60c9fbfb64799ec25f5b02e72c3fb1c68ac17c9fd",
          "sha1": "50736b234a3df8c1c36c57215914e9d41d1ed542",
          "md5": "2773b4dc2c6cc489812cfecda20a0216"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2511.2-sources.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2511.2-sources.jar",
          "size": 17419405,
          "sha512": "b8dbdb8ea94fe0ddad4ba0f4b291938d4cbca7ebd49b3a76c0810b54a2cd4df69e3d7344df141a5aeb1dc96a834bfa85194c861710cb54f37ce4eb1a43cec738",
          "sha256": "3ca2c83095b81f93bb8eedfec3538e47ea981d6a73ae8f4f78d2a9f85cea5056",
          "sha1": "fe448f66580944b83013665fcef7b76e72abb7e2",
          "md5": "544e3ecc8c9d098a640229aa07891590"
        }
      ]
    }
  ]
}
