{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2500.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2500.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.2500.8.jar",
          "size": 354224,
          "sha512": "9af3844a22ed7132ef753e08bca43605930bd9849e97fc0d6a53e3e2525647d4e27dc248c49cde801635f2ee1927e27039fc278285872cbe0a52fa75a8a156f2",
          "sha256": "6018b0f6cbc4a097c8ff42f43ec9d96643278b1f8f961db654d780f2a68faa2a",
          "sha1": "6693f049260dc4b73fd5b6fda0b5993e6b001cf1",
          "md5": "c28e782534de90cd3eae48fd96d4da3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2500.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.2500.8.jar",
          "size": 354224,
          "sha512": "9af3844a22ed7132ef753e08bca43605930bd9849e97fc0d6a53e3e2525647d4e27dc248c49cde801635f2ee1927e27039fc278285872cbe0a52fa75a8a156f2",
          "sha256": "6018b0f6cbc4a097c8ff42f43ec9d96643278b1f8f961db654d780f2a68faa2a",
          "sha1": "6693f049260dc4b73fd5b6fda0b5993e6b001cf1",
          "md5": "c28e782534de90cd3eae48fd96d4da3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2500.8-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2500.8-sources.jar",
          "size": 193227,
          "sha512": "f5327f08787b16d7c1bcb424e9bbaa5f321f6aab6d0eda64cafdede50e38b7787478901ef7710b5aedc606b16f62c511fd604a2f6c8566e8bc8d3826b2fb976d",
          "sha256": "fe3cc1eaaa2555a189cf8e1236f9fe50410e772b6832be053d42220e4e31f71e",
          "sha1": "c9ff030d281822ffbbc9733df30d384c44e2a8ae",
          "md5": "74595c58509e7dbaccccd876445bfa69"
        }
      ]
    }
  ]
}
