{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2513.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.4.jar",
          "size": 497998,
          "sha512": "eea57e0fd398ab188556665f19cfd34b0666215cc8e756a4e307cbe5cfdf41d87cf04f4ed61f54422ace17ca614a9e54c5a4c843bf6a6f8bdefa068c384cd316",
          "sha256": "1eb14096a79cc71829942e931ebcb36302d639bf3e36dbc42539f6379fb733af",
          "sha1": "2785f2e4b5d963f4a5ed4e1713073842c090243e",
          "md5": "c286c5f04ffa8aa8d8d542b189829247"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.4.jar",
          "size": 497998,
          "sha512": "eea57e0fd398ab188556665f19cfd34b0666215cc8e756a4e307cbe5cfdf41d87cf04f4ed61f54422ace17ca614a9e54c5a4c843bf6a6f8bdefa068c384cd316",
          "sha256": "1eb14096a79cc71829942e931ebcb36302d639bf3e36dbc42539f6379fb733af",
          "sha1": "2785f2e4b5d963f4a5ed4e1713073842c090243e",
          "md5": "c286c5f04ffa8aa8d8d542b189829247"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.4-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.4-sources.jar",
          "size": 250282,
          "sha512": "5f3aa915b478c9361e44ee1b4be629bdacc07a86acaaa5636753b03ef74c1a6849aeccb59d0081595ecb1e498a4993fcde3634452cd71ade3c6aa00196ac46fc",
          "sha256": "bbe932a60b91ce89ae40b1959899c6ed420a2f6c3e176649a7150bf46b515ed2",
          "sha1": "c030ac64bbcad4b10dd16b926179d2f83a111eb4",
          "md5": "135118ffe0ad6c15ceca04519bf6a121"
        }
      ]
    }
  ]
}
