{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2507.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.2.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.2.jar",
          "size": 503506,
          "sha512": "66d20bdcf8d287c16a2b453b3c868e4234d5d906a725a48f66a273abd3dd346a59a04a9d9cf985e152bf4034cbe74a294a39f3c6330191e9c56e45dba51e4b85",
          "sha256": "d46d584b4e9c9fd7916b56d7fcb59dce23ace956a6340a45eb92147973061fba",
          "sha1": "ad838eb199d17f175eeac0c9ca04f62834eaad08",
          "md5": "3f6403c2d88dde4039aa9dde85e1cbff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.2.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.2.jar",
          "size": 503506,
          "sha512": "66d20bdcf8d287c16a2b453b3c868e4234d5d906a725a48f66a273abd3dd346a59a04a9d9cf985e152bf4034cbe74a294a39f3c6330191e9c56e45dba51e4b85",
          "sha256": "d46d584b4e9c9fd7916b56d7fcb59dce23ace956a6340a45eb92147973061fba",
          "sha1": "ad838eb199d17f175eeac0c9ca04f62834eaad08",
          "md5": "3f6403c2d88dde4039aa9dde85e1cbff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.2-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.2-sources.jar",
          "size": 246021,
          "sha512": "c29787c086bc87fc21b67137019cfb136a2bb97bef33a8df86142a712f1de126f2a0144cb8b458c8f61476a52735e3de8bfc4a474a0e6ef500749c6c6abda99a",
          "sha256": "926e6b850082b86ef98a741f52073d973e51c342f56575efc435e6b7eb5aa3ff",
          "sha1": "2c6a37ae9294c929964bc2240bb66f8beeaa6956",
          "md5": "f530f68379266bebe5eaf8edb510142e"
        }
      ]
    }
  ]
}
