{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2510.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.4.jar",
          "size": 498613,
          "sha512": "b294b749b7b74dc27622dd8b4595c6df3a50813269b7424595cc62fca03ea3d44de32e6a413f75a436cff100ca7ffca6fd6e85aa1d2aad54d18eb2f0d2f8889b",
          "sha256": "0dd697d15ed25e7447985bd75ae2de3d4338b3279ed94494a1af1779c401062d",
          "sha1": "52055330e57ea610438182881660c0277359dc39",
          "md5": "0ccb0186ce507db51d12a23b433d000f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.4.jar",
          "size": 498613,
          "sha512": "b294b749b7b74dc27622dd8b4595c6df3a50813269b7424595cc62fca03ea3d44de32e6a413f75a436cff100ca7ffca6fd6e85aa1d2aad54d18eb2f0d2f8889b",
          "sha256": "0dd697d15ed25e7447985bd75ae2de3d4338b3279ed94494a1af1779c401062d",
          "sha1": "52055330e57ea610438182881660c0277359dc39",
          "md5": "0ccb0186ce507db51d12a23b433d000f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.4-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.4-sources.jar",
          "size": 250589,
          "sha512": "bef16928509f9bdac558e129e8af5764d0282ea84b2fbfbd141b97b8a937098420d9293a16e695c62b39fdc48da49bf2181f806a0d0c841f3975f07036022192",
          "sha256": "a4e7c3eea2016c121025d78126bf1002eec3bb99c7cc58e63f1b7a7b614440ea",
          "sha1": "cf1ed1d4e853ac4e6420ce7d490adcaae4135863",
          "md5": "b9e2cf9077c84fc036d28b8e2f918504"
        }
      ]
    }
  ]
}
