{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.8.jar",
          "size": 481630,
          "sha512": "9d31e256a00b1a1e7a4f509bb10e04b9a7e72f8119d40487d6a6b53a264698155a9ed7bfcc6b315d48c0706a364bd416901affc5d8c3193c712156e9f72c6900",
          "sha256": "fb5366bf4dd9b176d487baf11eeb4985dffb51f9e3b3cc2619b062d04bd65daa",
          "sha1": "5d2cf3fbd4eced0450b8e4954fc27b185a210f13",
          "md5": "1914c234227ddd2f07b44f79ec1e95c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.8.jar",
          "size": 481630,
          "sha512": "9d31e256a00b1a1e7a4f509bb10e04b9a7e72f8119d40487d6a6b53a264698155a9ed7bfcc6b315d48c0706a364bd416901affc5d8c3193c712156e9f72c6900",
          "sha256": "fb5366bf4dd9b176d487baf11eeb4985dffb51f9e3b3cc2619b062d04bd65daa",
          "sha1": "5d2cf3fbd4eced0450b8e4954fc27b185a210f13",
          "md5": "1914c234227ddd2f07b44f79ec1e95c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.8-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.8-sources.jar",
          "size": 244428,
          "sha512": "6427031937fcf6cc078c456a03670a3c18dd3b11a9f2c1f1be2585609e7334959f846b3e47279a7eb6d0c0f6b267ad3d11b905a53a7ed2a6ede259972d26cf37",
          "sha256": "c8664e1427579c840ba5b01b206cd467af28d16d80a99aaeee89f0eb52cc87a8",
          "sha1": "8bb969dc0e6f71100d9bda0123ffcde7dc4ad5a6",
          "md5": "5a27a2f3019dbea809f3cbb8f8cb7f1b"
        }
      ]
    }
  ]
}
