{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.5-1.1.2518.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2518.1.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2518.1.jar",
          "size": 643386,
          "sha512": "83e3632932d59420f1e3f31f1e21069bc009ac62f58ad627541c55518e49e02e2b1b6bc0177db80e4541d57ed0e20d636043984f14ca796928028f7d0ddecd75",
          "sha256": "cc5dd64da4d4d9ec98edb819d5886127ca29d1dec2da6bb36cb0f60de62b9b3c",
          "sha1": "4f0cd94693b86ab71b3569890b03ae47b0b023d4",
          "md5": "a6a329b2272507c7d137a9332283d16e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2518.1.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2518.1.jar",
          "size": 643386,
          "sha512": "83e3632932d59420f1e3f31f1e21069bc009ac62f58ad627541c55518e49e02e2b1b6bc0177db80e4541d57ed0e20d636043984f14ca796928028f7d0ddecd75",
          "sha256": "cc5dd64da4d4d9ec98edb819d5886127ca29d1dec2da6bb36cb0f60de62b9b3c",
          "sha1": "4f0cd94693b86ab71b3569890b03ae47b0b023d4",
          "md5": "a6a329b2272507c7d137a9332283d16e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2518.1-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2518.1-sources.jar",
          "size": 585473,
          "sha512": "4b1c4975ff691a994fab65afef69b51ae882dd57704e419a3add65d8e3708367b68888a271af82cfd2872c17298c6907821e3145854f60a7d857a38329e6bf08",
          "sha256": "2486cc2acf014a8439937c4dc14bd8d1de645b4a0c254c95ab01988062a22e29",
          "sha1": "6c80cdb99e6f8aabf7a6371588eaa6ed4cc6c97e",
          "md5": "576b26bd0701808287c1f792a564d308"
        }
      ]
    }
  ]
}
