{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.7-1.8.2.2529.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2529.2.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2529.2.jar",
          "size": 19975505,
          "sha512": "e43b10bc4a14b8269f09d94fd4047ca4b78c8d128884157a7f9095a161177362e605c91d965fbdad61cac278c1f4b67e3f1d86db6b21b53978692d961ecb7ed8",
          "sha256": "a5006c05c44cf9ad6deba9ce219d874cb0c4aa18da040b1ea9e9f0aa775671f9",
          "sha1": "23534c53d7ccfda8bbe0c45b679b711bd4845786",
          "md5": "7821f46280255584a7b2a009b2cedada"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2529.2.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2529.2.jar",
          "size": 19975505,
          "sha512": "e43b10bc4a14b8269f09d94fd4047ca4b78c8d128884157a7f9095a161177362e605c91d965fbdad61cac278c1f4b67e3f1d86db6b21b53978692d961ecb7ed8",
          "sha256": "a5006c05c44cf9ad6deba9ce219d874cb0c4aa18da040b1ea9e9f0aa775671f9",
          "sha1": "23534c53d7ccfda8bbe0c45b679b711bd4845786",
          "md5": "7821f46280255584a7b2a009b2cedada"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2529.2-sources.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2529.2-sources.jar",
          "size": 19050283,
          "sha512": "a71fb8a58a91647095ee71e3e9273f18a493d737ee03cac653cdaf21b1f122d0aa5f3899d293fd4f4b8de012b185d0b4d2a8262b412d3203aa6419039ae03157",
          "sha256": "2ef6003408183d93682529ce4f9f00ece39b79c3fda88c4579f3dd1ed34b99ff",
          "sha1": "7fdef302ed2244e536dee283ed54c801108c8a40",
          "md5": "f15ddc7ec00ef05a0b8aabee74b5517b"
        }
      ]
    }
  ]
}
