{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "size": 708001,
          "sha512": "370c70d78fac60f7010ad0e3a6da17a2d0e4a2d040477b33473fd930d19cff1d6300fa974cdac1af25892b00ad54348e89dba84678dbd1f8e331a16db2fba64f",
          "sha256": "cc9924b202ad621a6b440b40bd707cecd706ec88a539552d2fb5684f004d94de",
          "sha1": "5065e167d17d76d9d1cf9a28906499d3a35afc16",
          "md5": "c1956447b15c4a195c57aad06280d6e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "size": 708001,
          "sha512": "370c70d78fac60f7010ad0e3a6da17a2d0e4a2d040477b33473fd930d19cff1d6300fa974cdac1af25892b00ad54348e89dba84678dbd1f8e331a16db2fba64f",
          "sha256": "cc9924b202ad621a6b440b40bd707cecd706ec88a539552d2fb5684f004d94de",
          "sha1": "5065e167d17d76d9d1cf9a28906499d3a35afc16",
          "md5": "c1956447b15c4a195c57aad06280d6e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2514.2-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2514.2-sources.jar",
          "size": 75240,
          "sha512": "9d851ef6d5ff834057384bf867722ee2ffa0def40d71e139c21e94852b4b70ae8d6280640d51f91d5bb7dc0eb9c9461594807791266176d1ee488ed68933bd96",
          "sha256": "ff2b1a2e7757b8bf2c88b7a3b7eef3f7b0c07f92fb7734af5e24ceabfdeb1cc3",
          "sha1": "719ab3da0eea6a27ff4ec5a4f21330e9c3b021c9",
          "md5": "f6925d2e74f3dba3830f0560a33bcd72"
        }
      ]
    }
  ]
}
