{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "size": 708110,
          "sha512": "2a7872345d652ecee37500f6a4c9b4d227511847dfc0c3c539e81bc6d22fd30f7d5c95dbdfce77bb12484ea670bb98cb1a41efca2520c193a38558a5dea8a8d4",
          "sha256": "8417ee326a3eeb0f83720a680c92ee0a2261aef05a9d432038172d354904705b",
          "sha1": "a4e4874d476a321f869b52d5baf45755789c7b90",
          "md5": "31ee7782dd8cf573a764abd63d98e0e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2514.2.jar",
          "size": 708110,
          "sha512": "2a7872345d652ecee37500f6a4c9b4d227511847dfc0c3c539e81bc6d22fd30f7d5c95dbdfce77bb12484ea670bb98cb1a41efca2520c193a38558a5dea8a8d4",
          "sha256": "8417ee326a3eeb0f83720a680c92ee0a2261aef05a9d432038172d354904705b",
          "sha1": "a4e4874d476a321f869b52d5baf45755789c7b90",
          "md5": "31ee7782dd8cf573a764abd63d98e0e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2514.2-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2514.2-sources.jar",
          "size": 252776,
          "sha512": "cc828c6cbb39b97dc947a664b4ca9b66bad0f678b021ef6bef2a44d436bbe6d69cf0150c3c52f9a7ceff86ea4096b5ff4ad0b3facb4556594b759e36c0f51e3a",
          "sha256": "1843e128d43e98101e48f8069d3782dde7a2b9f10ee4016c27ca6f83a1220830",
          "sha1": "573af21da4e48e343e09eaa6a3e7be32b438f2ff",
          "md5": "95dd7708a2d2ba0ff12daa7f63ef0e4b"
        }
      ]
    }
  ]
}
