{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2513.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.2.jar",
          "size": 498854,
          "sha512": "227ae089d2f18ab9fb82aabcfc2fa40a72096cb408be51e10ec9901757b4f232f525cf3de2faf124757868f0c1e2c3611f132dd286d47c99ffb4db9cd89942a9",
          "sha256": "2e6eeabdb596406dc20e78818764d3f54ec8ce0390f06bf3a2de94b328bff7e3",
          "sha1": "9572916b6a44d01dcfc2a6f7543856fbec7debb7",
          "md5": "02e6cdfb1af70413c9e654fe3d50ac78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.2.jar",
          "size": 498854,
          "sha512": "227ae089d2f18ab9fb82aabcfc2fa40a72096cb408be51e10ec9901757b4f232f525cf3de2faf124757868f0c1e2c3611f132dd286d47c99ffb4db9cd89942a9",
          "sha256": "2e6eeabdb596406dc20e78818764d3f54ec8ce0390f06bf3a2de94b328bff7e3",
          "sha1": "9572916b6a44d01dcfc2a6f7543856fbec7debb7",
          "md5": "02e6cdfb1af70413c9e654fe3d50ac78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.2-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.2-sources.jar",
          "size": 250669,
          "sha512": "c85bbc20baeaf40ab5ffa561530931051b7ba51fadbaf894b157b8f3220269aa28bc73f2c55c45494bef0bf43cd95d9ea883dececc581c82281e0c64452a83df",
          "sha256": "aab9149189783dd20af8bb1ba2d0474715a4cf4365a9c2bc0367b91667a14c8b",
          "sha1": "504e19eb5e1d31f1b4731fd110d1363adcc9bcda",
          "md5": "f08a861dbb34dbdd33721fd448229599"
        }
      ]
    }
  ]
}
