{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.8.0.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2517.0.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2517.0.jar",
          "size": 18270708,
          "sha512": "a3b22bc382c7754a61ae0c3bc2a40f53f1d9a1d611fa0cec884a850eaf9f11d075af8cc08fcc4c94374d640c2f815eaf9ab62e1415f9d5236078a0f3361738ac",
          "sha256": "c3bc4ff7a49604b03cec60089711d695e160ef28bf3a88546eb3c6bdc6a271f5",
          "sha1": "e07e029456304184efdfb0c9f2c635caa7b84871",
          "md5": "c8eb0bc91b4d23b684a070dd1f459db2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2517.0.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2517.0.jar",
          "size": 18270708,
          "sha512": "a3b22bc382c7754a61ae0c3bc2a40f53f1d9a1d611fa0cec884a850eaf9f11d075af8cc08fcc4c94374d640c2f815eaf9ab62e1415f9d5236078a0f3361738ac",
          "sha256": "c3bc4ff7a49604b03cec60089711d695e160ef28bf3a88546eb3c6bdc6a271f5",
          "sha1": "e07e029456304184efdfb0c9f2c635caa7b84871",
          "md5": "c8eb0bc91b4d23b684a070dd1f459db2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2517.0-sources.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2517.0-sources.jar",
          "size": 17421916,
          "sha512": "0944ad00275faaabd9cd96d42ff7d3da5ef275608b63e0a4f0036d56acabd43a8dafd378c4a8d9882ce454917375226112d7d32486d1476702a8369caedac69d",
          "sha256": "047676e222db4cd9b7236b2dba383f8885617336683ab73947c53fe72a56d3c5",
          "sha1": "18fab67bd35c1f85dffb0e836f2a5e26b2ab0227",
          "md5": "bf2ed7429b808d6ffce1cd573d01fad7"
        }
      ]
    }
  ]
}
