{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.1-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2501.24.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2501.24.jar",
          "size": 433804,
          "sha512": "3184a222c2208a058d502c47289564218e67c8fc62c5726e059c096d999bb9d8ea77b995021201e02d124714863351bf860ba4db2aa02f9e91f8e400cb4ec071",
          "sha256": "18b526da5465cefd95875c51ce11601e8aed7e78006599b415ad21102abf3d22",
          "sha1": "e66d8e687a572182b74c45dd0c4c318de038af38",
          "md5": "1bf43cd5dae39b76d90ebbdc9742ec18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2501.24.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2501.24.jar",
          "size": 433804,
          "sha512": "3184a222c2208a058d502c47289564218e67c8fc62c5726e059c096d999bb9d8ea77b995021201e02d124714863351bf860ba4db2aa02f9e91f8e400cb4ec071",
          "sha256": "18b526da5465cefd95875c51ce11601e8aed7e78006599b415ad21102abf3d22",
          "sha1": "e66d8e687a572182b74c45dd0c4c318de038af38",
          "md5": "1bf43cd5dae39b76d90ebbdc9742ec18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2501.24-sources.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2501.24-sources.jar",
          "size": 196292,
          "sha512": "def57afe023c9e2201941685bde34254e95e3dffd201f6a0c2c1fe669d48d7bf44734d040f123cf9630c1846078e1a16e7e3bbcca7c551951b512ddfc2918742",
          "sha256": "f33ad1646d9f8558515cca69cb6e3ab6c66dc9701a8b8101d330bd68a879f474",
          "sha1": "9935e80372542dd90d11d840eac41c1843f4b40f",
          "md5": "71c0bdd3ea5ea3fd2b32db57c4f210cb"
        }
      ]
    }
  ]
}
