{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.8.0.2512.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2512.4.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2512.4.jar",
          "size": 18255251,
          "sha512": "f7fdf311035997146d5a51005d2412f9aca524c7227084c9d1e0508d80ede53c30d124352b6657ed5d5462126397014be1e2492b653495a0968be58d33265faf",
          "sha256": "c6c5a47e3b8b36a3f6011f132edd4d975467aab5ce909e9103f12e5846d90716",
          "sha1": "5601f2f30159d67c1daeb5220bc77d9989ade4d7",
          "md5": "63f90096bf5731f55468f35d710daddc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2512.4.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2512.4.jar",
          "size": 18255251,
          "sha512": "f7fdf311035997146d5a51005d2412f9aca524c7227084c9d1e0508d80ede53c30d124352b6657ed5d5462126397014be1e2492b653495a0968be58d33265faf",
          "sha256": "c6c5a47e3b8b36a3f6011f132edd4d975467aab5ce909e9103f12e5846d90716",
          "sha1": "5601f2f30159d67c1daeb5220bc77d9989ade4d7",
          "md5": "63f90096bf5731f55468f35d710daddc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2512.4-sources.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2512.4-sources.jar",
          "size": 17415620,
          "sha512": "17f1bd85ef69195b96540e562b706fa41219112bb1ca2bc1c2f2ef2f19dd086e91ed3150dedef2c3955f6e7cf45c96917939f45be6f2e66eeb42444e12e293fe",
          "sha256": "0f3ff3e98eda784e17bbd0d370c8aee0c802189ed75167453468e38033ec4736",
          "sha1": "71364085a8b2ef8dd3f09b88daf7cc87dfdc94fc",
          "md5": "f088e9992cf11694e77bc29050ecacdc"
        }
      ]
    }
  ]
}
