{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2516.3.jar",
          "size": 695338,
          "sha512": "85db85a34bc80f167574005c25ae03538e8513476c35a450ce52f008f450e864dcb8a5671022fb8bf196c8cfd54518511435bfa62db87cc098654d709e9c306d",
          "sha256": "d31090f1aed33a1ad16a27556b4ec5d5e2cd5f2f89997eb9cfd7b95cf3aa032d",
          "sha1": "61d24498ad8227cabdacd0f21010a4ec00b33d12",
          "md5": "414e12c442cc800fe1a4e601cc3bc040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2516.3.jar",
          "size": 695338,
          "sha512": "85db85a34bc80f167574005c25ae03538e8513476c35a450ce52f008f450e864dcb8a5671022fb8bf196c8cfd54518511435bfa62db87cc098654d709e9c306d",
          "sha256": "d31090f1aed33a1ad16a27556b4ec5d5e2cd5f2f89997eb9cfd7b95cf3aa032d",
          "sha1": "61d24498ad8227cabdacd0f21010a4ec00b33d12",
          "md5": "414e12c442cc800fe1a4e601cc3bc040"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2516.3-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2516.3-sources.jar",
          "size": 255844,
          "sha512": "1efe7ebab1e9115fcfbeb0929519a7bf6e52bcb15e658ac1d41db7322827dc63116fe4c2a26df9962125495e7aac8544ca4cd5f410565b4b68445fb37437e498",
          "sha256": "2bd468c1a79ad3a35626006b96ffc53017ab7f4f305f8babf7e5d7705d46db4a",
          "sha1": "66cebd4e51bbd29d50f66090315562da1d0bf531",
          "md5": "49fb5797c9134b0a5166ed1695260094"
        }
      ]
    }
  ]
}
