{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "size": 559045,
          "sha512": "b7c10221c7db03e097d453fe40c24523ae7e0fc6fb9d8e67cfb79de9ad39addb67cc625ff22b782d3782373cdc66247759da150f3c48c40175c3ba6e46f25475",
          "sha256": "a52a986d7c23a0f6229ae33e14cce532f7051076dd7a3f9ca3e2b2b6686a4005",
          "sha1": "e37a34a9cb6318c953143b935d12ce912c3485ce",
          "md5": "c0b4a3f182b57c9a27acd0c461539255"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "size": 559045,
          "sha512": "b7c10221c7db03e097d453fe40c24523ae7e0fc6fb9d8e67cfb79de9ad39addb67cc625ff22b782d3782373cdc66247759da150f3c48c40175c3ba6e46f25475",
          "sha256": "a52a986d7c23a0f6229ae33e14cce532f7051076dd7a3f9ca3e2b2b6686a4005",
          "sha1": "e37a34a9cb6318c953143b935d12ce912c3485ce",
          "md5": "c0b4a3f182b57c9a27acd0c461539255"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2517.0-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2517.0-sources.jar",
          "size": 252822,
          "sha512": "afd5dce1ea203ff69adf4ad2c9859e78ae84f76ecba35d66ae2e27739165b372330273be0931c3fbdbf4e07ce4621dfe017c05eb1789214364a108e9bfbf917c",
          "sha256": "e799cf0dda8ea1bfc19b7da14741adb3f67e001479c9d714c8791a8b398171c0",
          "sha1": "0d63ccbfc6660bd9fb4a8fbb6a3e244599796236",
          "md5": "f8b585f83aa1b3e373c3ae3a0c5b7d2c"
        }
      ]
    }
  ]
}
