{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "size": 559467,
          "sha512": "65bbe91f12d6e226900c3ae58973bc3d2b2064b441201171a956b12844b7c66b4c64e6d74de7224cec434fdfa579f2fef9dc162348d82330c662858e6dd741ec",
          "sha256": "8e1eaacfde825565ff2b6d309d0b3b50d8a3dcae2feb85f77ce9b87b2ae0a216",
          "sha1": "5b2301fdefa292b1018e65db6755725cc0a3539e",
          "md5": "b59d16e0d28fb1b821648c5d9d3ebcc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2517.0.jar",
          "size": 559467,
          "sha512": "65bbe91f12d6e226900c3ae58973bc3d2b2064b441201171a956b12844b7c66b4c64e6d74de7224cec434fdfa579f2fef9dc162348d82330c662858e6dd741ec",
          "sha256": "8e1eaacfde825565ff2b6d309d0b3b50d8a3dcae2feb85f77ce9b87b2ae0a216",
          "sha1": "5b2301fdefa292b1018e65db6755725cc0a3539e",
          "md5": "b59d16e0d28fb1b821648c5d9d3ebcc7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2517.0-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2517.0-sources.jar",
          "size": 253008,
          "sha512": "7e81f2e436c4c969a6012b65a12ce1df752a5d77dbf7efdfc8faf20133de58c2a6c9f55cb9a19fc7eef705cf60856a83615f0287a9b1dc1d5ab5dd24f69a28c2",
          "sha256": "9aada299dee8f351ce4341eaf49984967b9a344960a408b1c9d27ccdb1597db4",
          "sha1": "3b988abf49d7e67fbc5a6fbb5401931fedb8ff15",
          "md5": "1b13df9c6219a13677e834fc730ee68e"
        }
      ]
    }
  ]
}
