{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.8.0.2518.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-forge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.1.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.1.jar",
          "size": 19774643,
          "sha512": "82ffc130a5e01c8e3bf4e0196e539a6c792d5ca013444ffe0458ccb3ff6b88a8ede16286abf14efe2a0c579602cc87375128d02f8be251a9f75c84e464f98a28",
          "sha256": "4609d2202b7d047a85f1db2dcc8b3866be479af7c0918b307817a1e396cc7b3e",
          "sha1": "701dfca3620ad896acda1b56922d9c7f40d936fe",
          "md5": "5c92642fd9caf1bad2b219116910b075"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.1.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.1.jar",
          "size": 19774643,
          "sha512": "82ffc130a5e01c8e3bf4e0196e539a6c792d5ca013444ffe0458ccb3ff6b88a8ede16286abf14efe2a0c579602cc87375128d02f8be251a9f75c84e464f98a28",
          "sha256": "4609d2202b7d047a85f1db2dcc8b3866be479af7c0918b307817a1e396cc7b3e",
          "sha1": "701dfca3620ad896acda1b56922d9c7f40d936fe",
          "md5": "5c92642fd9caf1bad2b219116910b075"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.1-sources.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.1-sources.jar",
          "size": 18911573,
          "sha512": "ea442016fe4de4d58e738b089e707102f5ab30fac5abd43b2439fbab5c16c507e2ce1b8c5fea1fcbcb0580d271052aaec525e066e02236b66736ca77d8c303d8",
          "sha256": "9179962c070e8ccbc3963954598f14e0199bd3901c5c6216fc9a877e295fbed4",
          "sha1": "9ccdc69579908f46954b9739540cdcecf62e2a55",
          "md5": "ff38694aa0dbae13ca2ecfe1dd4eb414"
        }
      ]
    }
  ]
}
