{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.8.0.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2512.0.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2512.0.jar",
          "size": 18255044,
          "sha512": "0e0fa2f213013ec0a6e71ff160875e143ff16ca7f6465c8970e7ff5fc4587d342822990663069531fc77a7a120d8f3c716e2e554ee1e7904c47c4bdaa23f0494",
          "sha256": "58a55fe8a0ea4b19378df7fc2669fd0dba3fb4ecb5d3b2d75c1fb1f14cfa671b",
          "sha1": "c01d9c44aac6b82a82d54dd488a9d6a943a4dd70",
          "md5": "061e53e745c995f7cd9cd5d85d3d4c10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2512.0.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2512.0.jar",
          "size": 18255044,
          "sha512": "0e0fa2f213013ec0a6e71ff160875e143ff16ca7f6465c8970e7ff5fc4587d342822990663069531fc77a7a120d8f3c716e2e554ee1e7904c47c4bdaa23f0494",
          "sha256": "58a55fe8a0ea4b19378df7fc2669fd0dba3fb4ecb5d3b2d75c1fb1f14cfa671b",
          "sha1": "c01d9c44aac6b82a82d54dd488a9d6a943a4dd70",
          "md5": "061e53e745c995f7cd9cd5d85d3d4c10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2512.0-sources.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2512.0-sources.jar",
          "size": 17421952,
          "sha512": "b97d396e4ee0401ac61ba932ea6d617995a91a24ba895d465aeffd0a07637f0065a6648a4c2e839448fcee51b63d1ca698a73797c2cf971eeee3ea08d050bbe9",
          "sha256": "ed768e32d6a85dd55133654c79cdadc3333e0fba84bb05c495edc3dcbabc4833",
          "sha1": "c7d1a2d090c24224ff1d90aa69ffa97625c1552e",
          "md5": "03361d33049f03eec8447e603aba88a3"
        }
      ]
    }
  ]
}
