{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.4-1.8.0.2511.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2511.3.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2511.3.jar",
          "size": 18244490,
          "sha512": "a408e0ac6e7f048029bbe3bc21f7cfc7a2dbc0bc5ac3f816c2c79f9aba47f2cf27c214ca6218835cf8150970b84b9bd4f03ee29c8cb0fb8fc9ba9759b713d3ba",
          "sha256": "eb2c3b4ace94be9f6d23f15a5e1923330a8f0bc9e0760d9a359c3837eb6c99fc",
          "sha1": "2b53202c422b9170b0d08d209cb23a412750dd7d",
          "md5": "8459f3ee02bdbad7f788855bc8043719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2511.3.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2511.3.jar",
          "size": 18244490,
          "sha512": "a408e0ac6e7f048029bbe3bc21f7cfc7a2dbc0bc5ac3f816c2c79f9aba47f2cf27c214ca6218835cf8150970b84b9bd4f03ee29c8cb0fb8fc9ba9759b713d3ba",
          "sha256": "eb2c3b4ace94be9f6d23f15a5e1923330a8f0bc9e0760d9a359c3837eb6c99fc",
          "sha1": "2b53202c422b9170b0d08d209cb23a412750dd7d",
          "md5": "8459f3ee02bdbad7f788855bc8043719"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2511.3-sources.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2511.3-sources.jar",
          "size": 17412098,
          "sha512": "e5d46415ae222976e650dcd33cd35263dca1dca96f0ea7faadc6c1dfeda5c3d853c405cd69bcb18ee2022baaed64b00c239287e189ea3244e38f0d86708110df",
          "sha256": "2b9ecd2407d45ff2b8255530449eb9b03d3c029b8cf60c2b8efa84842486c26d",
          "sha1": "345f09e99fa9b574cac9afb4e268b330f20b3b9d",
          "md5": "0546291f347aecdf175a99619ac4d569"
        }
      ]
    }
  ]
}
