{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.7.10.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.7.10.2509.1.jar",
          "url": "legacy-neoforge-1.21.3-1.7.10.2509.1.jar",
          "size": 14418932,
          "sha512": "36a60b6544463e00e114485d21b6f1eac21dd087de1178d22a5eeced9427b70b0de6a76faf4c005d48c97eb3fc8aa500d0999f6e784f75dcb497213023e6d776",
          "sha256": "8882b2fff4595da847df1f940228176b4918534c9f3d3a14551ec1932ab3deda",
          "sha1": "0070f4102305348b0352a1427dc6b94f8d848bc2",
          "md5": "c18852695129218b0dfe5462ad26b7ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.7.10.2509.1.jar",
          "url": "legacy-neoforge-1.21.3-1.7.10.2509.1.jar",
          "size": 14418932,
          "sha512": "36a60b6544463e00e114485d21b6f1eac21dd087de1178d22a5eeced9427b70b0de6a76faf4c005d48c97eb3fc8aa500d0999f6e784f75dcb497213023e6d776",
          "sha256": "8882b2fff4595da847df1f940228176b4918534c9f3d3a14551ec1932ab3deda",
          "sha1": "0070f4102305348b0352a1427dc6b94f8d848bc2",
          "md5": "c18852695129218b0dfe5462ad26b7ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.7.10.2509.1-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.7.10.2509.1-sources.jar",
          "size": 13582904,
          "sha512": "864fab62be70dc49138b42468dd41571ea0db18a07477feab61846f787b74faad5ae983b11182e27b8803b3cb7ccc83c4e49eef4e0b7ca2a6292f5cf30af0832",
          "sha256": "822da939aa91cb4c259ff6f0c0f9b183d5bc0198aebc67834fba183f8e98d235",
          "sha1": "bc248cbe2364c053c771f25ee2621ddeb75b5f81",
          "md5": "ec8700b9494ca7ae0069e5637bf67543"
        }
      ]
    }
  ]
}
