{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2513.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.1.jar",
          "size": 704933,
          "sha512": "39e435c98c7afc99f65fdcef2e2cdca7a4f1a417f45000a403763da4664b21c76fa888b43b41ae247039efa4d5174a7708a60bcb20af010e9dbfc472ec2caf00",
          "sha256": "09ba54029fc3536687c2b8417634a6e966cc95d43f84450d3385786eb6bf8cfa",
          "sha1": "ec9a91f4d2dfb787ae3dd67872be3c650e4745c9",
          "md5": "819807fd0a4862181b018b03a23baa63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.1.jar",
          "size": 704933,
          "sha512": "39e435c98c7afc99f65fdcef2e2cdca7a4f1a417f45000a403763da4664b21c76fa888b43b41ae247039efa4d5174a7708a60bcb20af010e9dbfc472ec2caf00",
          "sha256": "09ba54029fc3536687c2b8417634a6e966cc95d43f84450d3385786eb6bf8cfa",
          "sha1": "ec9a91f4d2dfb787ae3dd67872be3c650e4745c9",
          "md5": "819807fd0a4862181b018b03a23baa63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.1-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.1-sources.jar",
          "size": 252818,
          "sha512": "e0764ea970e45158b24082aad8af29c066a2283551df0e031d5f3c11187e4437616f31d723c016ae18c95420c8916b2434096be6dbd99da0c5587229e28886b1",
          "sha256": "455881f16f6b73da20f4b762590746e88f674a55811d27959f9d2c9419f54dd7",
          "sha1": "5e9597028be003c3e4c387418caf0c182498f94c",
          "md5": "d9451ec9e06943d0496b2543ece523f7"
        }
      ]
    }
  ]
}
