{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2504.4.jar",
          "url": "factory_api-forge-1.21.3-2.2.2504.4.jar",
          "size": 462650,
          "sha512": "94da21de404fd918908b4aee633647a7edc93dde00463c630095a064694b096d5659c7cf13200dd6536c466868e1e4a46deeec460e1b18cda294832cd48bad85",
          "sha256": "bb4703b02e0c0cdc9716134ee86845a52d314c81d98834eb179dcb4c33f3ef5b",
          "sha1": "afe70c2e6097418d0f4a4f8bae9c878ab3698285",
          "md5": "a1f594183f2e4edb6cb5fd215e41a49c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2504.4.jar",
          "url": "factory_api-forge-1.21.3-2.2.2504.4.jar",
          "size": 462650,
          "sha512": "94da21de404fd918908b4aee633647a7edc93dde00463c630095a064694b096d5659c7cf13200dd6536c466868e1e4a46deeec460e1b18cda294832cd48bad85",
          "sha256": "bb4703b02e0c0cdc9716134ee86845a52d314c81d98834eb179dcb4c33f3ef5b",
          "sha1": "afe70c2e6097418d0f4a4f8bae9c878ab3698285",
          "md5": "a1f594183f2e4edb6cb5fd215e41a49c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2504.4-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2504.4-sources.jar",
          "size": 231496,
          "sha512": "8d33fb6f5e9769c79288e99b8b024c90b5bf6d1878fa2c512eca19869029b8712f19707acb10d4e6e54da35b043c0e6896535327c2efba4f5e232c61dcabc747",
          "sha256": "9831f55acd3b4e193f97d03d5fcfd596819a1814e34c1ebd3e17559579adc705",
          "sha1": "bd10fd414a319e5da35aa4f2c5cbead430f89a77",
          "md5": "ea3f500a1c37c0baf02892b93cc13a1d"
        }
      ]
    }
  ]
}
