{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2500.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.8.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.8.jar",
          "size": 348955,
          "sha512": "9de89679eaabfcdbae036840c9c6e12e5d0f7fe15f792f381ce9bcaf28d25333e81aca850ccafdc6aa4005133a8bb7768ea33885a94091ac1f55f6f19ca0ae0f",
          "sha256": "4bcaf30bef4662914896400fa34a06378a5dec24f714a9ad1aba470600334604",
          "sha1": "f833af01c02470effcbd35045576f4b75953887c",
          "md5": "a781a327872d79009cddcf9fc51fb56d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.8.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.8.jar",
          "size": 348955,
          "sha512": "9de89679eaabfcdbae036840c9c6e12e5d0f7fe15f792f381ce9bcaf28d25333e81aca850ccafdc6aa4005133a8bb7768ea33885a94091ac1f55f6f19ca0ae0f",
          "sha256": "4bcaf30bef4662914896400fa34a06378a5dec24f714a9ad1aba470600334604",
          "sha1": "f833af01c02470effcbd35045576f4b75953887c",
          "md5": "a781a327872d79009cddcf9fc51fb56d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.8-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.8-sources.jar",
          "size": 193424,
          "sha512": "fb15a89dc5600a383f982c447164e52420f0a673d824d5381a5d6e59e5fc4e5c9ef3b3b2a8fd01b28c317d5a3a287b38f724130712f47d0f0ce62aef36f96555",
          "sha256": "6ce38094670b4a2d34a813066998348552d6590ba56834b8b703bbaefb52bec3",
          "sha1": "b7616481e67bd551f7d224c86137e1a2d62bd7a2",
          "md5": "2754bbf620163a3f1ddcd826ee9f977e"
        }
      ]
    }
  ]
}
