{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2510.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.6.jar",
          "size": 682618,
          "sha512": "69429b50863c03c2a5b4babfd47383a12477805df2f8cb5b325170fcc3e3b2692e6f6262c4f1a2194bb865c4a5bfc72b373633c989f8f8691f65779dd1d79524",
          "sha256": "ca49cb16ae341bb548e2497f280f97c4e13c984d74f7e7d1851524588b145884",
          "sha1": "380b7a22687991fbbed663c5156f62f613977a50",
          "md5": "b695ef88f637925b8344fa498e4ee0ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.6.jar",
          "size": 682618,
          "sha512": "69429b50863c03c2a5b4babfd47383a12477805df2f8cb5b325170fcc3e3b2692e6f6262c4f1a2194bb865c4a5bfc72b373633c989f8f8691f65779dd1d79524",
          "sha256": "ca49cb16ae341bb548e2497f280f97c4e13c984d74f7e7d1851524588b145884",
          "sha1": "380b7a22687991fbbed663c5156f62f613977a50",
          "md5": "b695ef88f637925b8344fa498e4ee0ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.6-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.6-sources.jar",
          "size": 250363,
          "sha512": "0e032555b633d9cf8e3e60ba581eb8afe3d365fdac742ccd7d85653dcdbdc4bdac8bdd38e964eb43a6cf4355189d09c8740a6cd8ae0b1eed10971b1f8a601491",
          "sha256": "0ed0623d1785ac0142b52a5255888be6d7caf009a37b79cb13be19baf6b9ab80",
          "sha1": "a974c353c935d63f46e5f20af3d44894d2861aab",
          "md5": "a0864e31f6d6cf352af8abea3bf72ffc"
        }
      ]
    }
  ]
}
