{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2513.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.6.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.6.jar",
          "size": 502476,
          "sha512": "a3720b9cdadb15319607bc5683a824c7dea710cb7992a46cebb0e381213ad7b2973de9233de696431232b318b8286cec83ec0830c271e77932749f78224646ad",
          "sha256": "98c1a84faae5c5c16bded2f3231ddd234514426ccb93ef495210addecce9b0bd",
          "sha1": "6324cc81ea56a76d64acc5ee2500a179fae5d36f",
          "md5": "57092e4248e27bd6219b6bc987584343"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.6.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.6.jar",
          "size": 502476,
          "sha512": "a3720b9cdadb15319607bc5683a824c7dea710cb7992a46cebb0e381213ad7b2973de9233de696431232b318b8286cec83ec0830c271e77932749f78224646ad",
          "sha256": "98c1a84faae5c5c16bded2f3231ddd234514426ccb93ef495210addecce9b0bd",
          "sha1": "6324cc81ea56a76d64acc5ee2500a179fae5d36f",
          "md5": "57092e4248e27bd6219b6bc987584343"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.6-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.6-sources.jar",
          "size": 251525,
          "sha512": "a21f7ce39bc71d9f4ea1a6a9d5deb62be2b659408455a113452a7247a5ac669d9e0c988502a563e452190d3c9196995859eb9ff0bc9d734e6422f9a4298e5268",
          "sha256": "45aab32a6698f665bf63db95ea513d5398dd134a22cfb8aa617a1ff955872b6c",
          "sha1": "65730a86bef06ec5580a4c7f9deaaf093946c367",
          "md5": "7ea1e37723df0c284dd91b3f40ed9f92"
        }
      ]
    }
  ]
}
