{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.24.jar",
          "size": 388561,
          "sha512": "e66d318d4769432288f779454998acb91fffd7808cb7abdf75fe7b72dbb36ff22de04240d5dbb710dc7d610d11cd003b16a26f0d4448426f50ec40f840156d5d",
          "sha256": "56dc028b5a3e2c79c20cb0c6c0912494cec7f8c5dc52b7b9d0f5b5697369f2a0",
          "sha1": "a56497a3f024852d3fe90ee7428272330788c27f",
          "md5": "9baad6e68b7a4dca3fd9cbfa2486071c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.24.jar",
          "size": 388561,
          "sha512": "e66d318d4769432288f779454998acb91fffd7808cb7abdf75fe7b72dbb36ff22de04240d5dbb710dc7d610d11cd003b16a26f0d4448426f50ec40f840156d5d",
          "sha256": "56dc028b5a3e2c79c20cb0c6c0912494cec7f8c5dc52b7b9d0f5b5697369f2a0",
          "sha1": "a56497a3f024852d3fe90ee7428272330788c27f",
          "md5": "9baad6e68b7a4dca3fd9cbfa2486071c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.24-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.24-sources.jar",
          "size": 197622,
          "sha512": "e425c7aa1dae579d823b823c58b6e2d446e9a05ad0d6ea371bd3075d27fac69927423e79b9b73bf42294fdaa55c73ffbb2a490022133ede048f391c67f8fc9c1",
          "sha256": "4599b052ff1171283ac12b94b751fcfa88819e65473e863e13482c1f91098373",
          "sha1": "c3405f9e0065a98072f299711311f48f08eb7d76",
          "md5": "eba49a8f7ed72e214acb211e136415a7"
        }
      ]
    }
  ]
}
