{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.3-1.7.10.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.2501.23"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.3-1.7.10.2501.2.jar",
          "url": "legacy-fabric-1.21.3-1.7.10.2501.2.jar",
          "size": 11915494,
          "sha512": "9cf5040daea6917000b53597669ed3b9baabcf117bc50bd471dd7af97df3bce657863de197bf8019d6c6e64237d35f79ce31ff1f70d9838f00ae212b9fddcb19",
          "sha256": "c0cffff73a7eb88da399e620778f1803d24ea005dc22d6127963975b4d0bf95e",
          "sha1": "90c30936353984c49994cb2821f219e1d6bb5092",
          "md5": "009c302266b3af4713e1223c4cabf4bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.2501.23"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.3-1.7.10.2501.2.jar",
          "url": "legacy-fabric-1.21.3-1.7.10.2501.2.jar",
          "size": 11915494,
          "sha512": "9cf5040daea6917000b53597669ed3b9baabcf117bc50bd471dd7af97df3bce657863de197bf8019d6c6e64237d35f79ce31ff1f70d9838f00ae212b9fddcb19",
          "sha256": "c0cffff73a7eb88da399e620778f1803d24ea005dc22d6127963975b4d0bf95e",
          "sha1": "90c30936353984c49994cb2821f219e1d6bb5092",
          "md5": "009c302266b3af4713e1223c4cabf4bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.3-1.7.10.2501.2-sources.jar",
          "url": "legacy-fabric-1.21.3-1.7.10.2501.2-sources.jar",
          "size": 11130568,
          "sha512": "f189132d45130ad0285cf8849d20f63cbcc452821a0212d75424d5f6c81c848477254607362ba8101a1cd80d2124cea8a53ece807c5f300a85952eb8a516d591",
          "sha256": "cd32464cd80e11cd39ebbcbe8398707859d5774fe1ab0830978005c9dd21a34d",
          "sha1": "7ac2e4e1b514f29e76378b08107fffb5285b432e",
          "md5": "5210002c2d21fb073caad215c2588f12"
        }
      ]
    }
  ]
}
