{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.7.10.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2508.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2508.0.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2508.0.jar",
          "size": 14380403,
          "sha512": "878b08d3bd0470c7e6477f067806ff9d13a377dd18130c23c1a0d80fa5f2625417bf07f8ca40aa14bc9a77e8c71da3b7f56cce56b8c99788dd54fb5cacbfc514",
          "sha256": "2eba30587376f00a8790d5164c27483c2aebd55f55e44c1b7ad84e7e6885ffe4",
          "sha1": "15dbc2f0d12a55520c36330e3dbd1ddc795d5b8c",
          "md5": "cc11d7bd125d003d483942ef73eca8d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2508.0.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2508.0.jar",
          "size": 14380403,
          "sha512": "878b08d3bd0470c7e6477f067806ff9d13a377dd18130c23c1a0d80fa5f2625417bf07f8ca40aa14bc9a77e8c71da3b7f56cce56b8c99788dd54fb5cacbfc514",
          "sha256": "2eba30587376f00a8790d5164c27483c2aebd55f55e44c1b7ad84e7e6885ffe4",
          "sha1": "15dbc2f0d12a55520c36330e3dbd1ddc795d5b8c",
          "md5": "cc11d7bd125d003d483942ef73eca8d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2508.0-sources.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2508.0-sources.jar",
          "size": 13560143,
          "sha512": "45e40ce7f17125495822dd111761b1acfc08750102d26d78f75ebe630f57ebbaee3162f15571c7c67e892f5025c98c17e58598af120be7bc2998bbdff2ed4166",
          "sha256": "74428ac09f011fca58cb5a791d03421f14b60bfec97a68e050804dfec1e9bff0",
          "sha1": "37f4764e64c5ffdf12c4b05384870d0c83382434",
          "md5": "10517e23e61a8ae81d805f50462b2eab"
        }
      ]
    }
  ]
}
