{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2508.2.jar",
          "size": 540684,
          "sha512": "a87522964562044cbd64cb7c910615ac06151debb8a99daa1b8a985de953f95327c0d65efed2827b350f011fc10dc87fe34e597df86a45b85eb227fff9b5cced",
          "sha256": "32c342bb2843b0d152557b1c08de9caa756aa0dc39cbea375c6e7b292b6dbc9a",
          "sha1": "c28862fae99a82b2976afb2dbb134b3b04f034b8",
          "md5": "842249467c61ddae8c838fbb653ea813"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2508.2.jar",
          "size": 540684,
          "sha512": "a87522964562044cbd64cb7c910615ac06151debb8a99daa1b8a985de953f95327c0d65efed2827b350f011fc10dc87fe34e597df86a45b85eb227fff9b5cced",
          "sha256": "32c342bb2843b0d152557b1c08de9caa756aa0dc39cbea375c6e7b292b6dbc9a",
          "sha1": "c28862fae99a82b2976afb2dbb134b3b04f034b8",
          "md5": "842249467c61ddae8c838fbb653ea813"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2508.2-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2508.2-sources.jar",
          "size": 246618,
          "sha512": "c1c162fb28e93d4e40f2d92d834bb4a46870baa81993178f0b314048e50c19c3eccbae73818976e1e2ea035795e8dc7c88c929155192009d8d72b593c7c4fa8f",
          "sha256": "81266c59c6f5d2662e03a6bc6eee9c24ac5df028e994480219423d42fa683432",
          "sha1": "e838498b9dcdb2765be9161b67a5a105cee6e08a",
          "md5": "68c2c99ba9a8d380a4a8b08c0fb03fea"
        }
      ]
    }
  ]
}
