{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.5.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.5.jar",
          "size": 19710722,
          "sha512": "a5780e651cabbf1791e6d38f702abaa4b414d060cf7615b36b90ee80600e880b13f659803c94981f52cb2a7c3915c7ffb6a266f5ec5b745d5f5ae3d1f0974905",
          "sha256": "f6473a244965a1c3cb7ea9926bc450d4ad7e35c697e1613ade485dbf5d8d6f32",
          "sha1": "a68707cb457b85ec8f172bc9a39cb9f7c7fb4b1b",
          "md5": "fd34a6c81636cbe2f6832779577c1842"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.5.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.5.jar",
          "size": 19710722,
          "sha512": "a5780e651cabbf1791e6d38f702abaa4b414d060cf7615b36b90ee80600e880b13f659803c94981f52cb2a7c3915c7ffb6a266f5ec5b745d5f5ae3d1f0974905",
          "sha256": "f6473a244965a1c3cb7ea9926bc450d4ad7e35c697e1613ade485dbf5d8d6f32",
          "sha1": "a68707cb457b85ec8f172bc9a39cb9f7c7fb4b1b",
          "md5": "fd34a6c81636cbe2f6832779577c1842"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.5-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.5-sources.jar",
          "size": 18853534,
          "sha512": "874de08235f5548c3cd66974753a3edaf51cc794389c2e0952197d1d0dbc873eb9f7d26b9a309fb0b1e293304453e153babd3d6a7e5bf16c6f61f9a768c90820",
          "sha256": "8a6f8acec1dbb694138b7ddcc93ae41b9a2f4cc5884442a86805467362220ff5",
          "sha1": "c0cccfb01e094f89943e115bbb149fd9e61cf5e4",
          "md5": "182738ab9211201b534c20a8d6f5eecb"
        }
      ]
    }
  ]
}
