{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2518.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2518.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2518.0.jar",
          "size": 716141,
          "sha512": "535cc4de0ec0a74c242172dc4bdeaeaeb5a0b169a3189bf1d7aa91798e5e252dac91357d21b434029e2d14d2488157c71c0a89ccb610a06be241ede446230430",
          "sha256": "83b7c530988f2568a8bce6ac80f783f348bc0cc5790bd01077b7f003eb9a0c3a",
          "sha1": "4c7cad62892175886d96bdbe523fd40629f8dba9",
          "md5": "8d6d368cd4e414496a748bd463028e18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2518.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2518.0.jar",
          "size": 716141,
          "sha512": "535cc4de0ec0a74c242172dc4bdeaeaeb5a0b169a3189bf1d7aa91798e5e252dac91357d21b434029e2d14d2488157c71c0a89ccb610a06be241ede446230430",
          "sha256": "83b7c530988f2568a8bce6ac80f783f348bc0cc5790bd01077b7f003eb9a0c3a",
          "sha1": "4c7cad62892175886d96bdbe523fd40629f8dba9",
          "md5": "8d6d368cd4e414496a748bd463028e18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2518.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2518.0-sources.jar",
          "size": 254693,
          "sha512": "9385bc06125284d279aab5767c180bde4645108f9f60c00116e28ca52676286d160f6f58d9f038f26bbab3914a504e82f71a02cff75bd97732ea1a9fa233fae3",
          "sha256": "a43155f192b167ad53803929e2eb0ee4d4c1979a80ea28d02691f555d1493416",
          "sha1": "1ce3af50430ecfef89e918bb4e3258e13cce55a7",
          "md5": "5a9adf49c4d442f5e9b488425478d43d"
        }
      ]
    }
  ]
}
