{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2516.1.jar",
          "size": 708237,
          "sha512": "ad06e9a85e396ec8104af94d3c19171eec65df6458e34f1ba74a8c341b4af9e88f5556d5e524769a8c426f052c1dfe4fa299f5756aa6c0af8f45312ebdfba80e",
          "sha256": "8ae03fad4e33be941e73c25c3228a4f30bc3cc4db0096ab1ad01606e127ffd41",
          "sha1": "5eec3f864e6b59c42d34217642feca73bb48f77e",
          "md5": "9be0a96bb45061c4cd5be93e4b7aba0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2516.1.jar",
          "size": 708237,
          "sha512": "ad06e9a85e396ec8104af94d3c19171eec65df6458e34f1ba74a8c341b4af9e88f5556d5e524769a8c426f052c1dfe4fa299f5756aa6c0af8f45312ebdfba80e",
          "sha256": "8ae03fad4e33be941e73c25c3228a4f30bc3cc4db0096ab1ad01606e127ffd41",
          "sha1": "5eec3f864e6b59c42d34217642feca73bb48f77e",
          "md5": "9be0a96bb45061c4cd5be93e4b7aba0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2516.1-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2516.1-sources.jar",
          "size": 253432,
          "sha512": "3ce5777f38a0b953ee5e481b5d9d052014647541f4eb5f4cd1d64daf7e8f40f13e4e712d49e86bfbb9701c29e1eee91b8098aaf9eff626887fe508e904378701",
          "sha256": "42079d5e199398c79d51116f792e93c71ae704ce6d344df45f8532dfe4427da7",
          "sha1": "14d4960e58d851c97cc60655a88df414995ba919",
          "md5": "abcf01a8cf18a499b26e6b2a3dbd9c01"
        }
      ]
    }
  ]
}
