{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.10-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.7.2617.0.jar",
          "url": "factory_api-forge-1.21.10-2.2.7.2617.0.jar",
          "size": 1157203,
          "sha512": "7d2f6830ffecf6b4f324de05ce42eff9c925743c677a4a0331c4f9be04cdb25327cb512de7b2b2d769e2ccd9fa1ef0d1fc7ab796ce7a334b4fef9cb6d927f616",
          "sha256": "d21a92db76dd25058edda73b756df52cf144be141c8561ca1798b4ab5713ad22",
          "sha1": "47493320464e7dd3b14c00e3dea1a1fbdf740f93",
          "md5": "78a50c7f8486eda25347db74585f0808"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.10-60.0.0"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.7.2617.0.jar",
          "url": "factory_api-forge-1.21.10-2.2.7.2617.0.jar",
          "size": 1157203,
          "sha512": "7d2f6830ffecf6b4f324de05ce42eff9c925743c677a4a0331c4f9be04cdb25327cb512de7b2b2d769e2ccd9fa1ef0d1fc7ab796ce7a334b4fef9cb6d927f616",
          "sha256": "d21a92db76dd25058edda73b756df52cf144be141c8561ca1798b4ab5713ad22",
          "sha1": "47493320464e7dd3b14c00e3dea1a1fbdf740f93",
          "md5": "78a50c7f8486eda25347db74585f0808"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.7.2617.0-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.7.2617.0-sources.jar",
          "size": 256803,
          "sha512": "86594e744d9ba5441a7c9b086b5aa774df1503583df7dc53d357896e525e84a14caa2e02f6889b344f58d050d923c0aa77bed6ea8299db8dae26695569c62f61",
          "sha256": "7b90959ffb83f73f4819604a3d766b08d7c7b51776266bc0c2f27c0df38884d8",
          "sha1": "d483f3092af79fb729fa47da39a8985da8f47f88",
          "md5": "e94463169a0c353ec676c748a11660d2"
        },
        {
          "name": "factory_api-forge-1.21.10-2.2.7.2617.0-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.7.2617.0-sources.jar",
          "size": 256803,
          "sha512": "86594e744d9ba5441a7c9b086b5aa774df1503583df7dc53d357896e525e84a14caa2e02f6889b344f58d050d923c0aa77bed6ea8299db8dae26695569c62f61",
          "sha256": "7b90959ffb83f73f4819604a3d766b08d7c7b51776266bc0c2f27c0df38884d8",
          "sha1": "d483f3092af79fb729fa47da39a8985da8f47f88",
          "md5": "e94463169a0c353ec676c748a11660d2"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.10-60.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.7.2617.0.jar",
          "url": "factory_api-forge-1.21.10-2.2.7.2617.0.jar",
          "size": 1157203,
          "sha512": "7d2f6830ffecf6b4f324de05ce42eff9c925743c677a4a0331c4f9be04cdb25327cb512de7b2b2d769e2ccd9fa1ef0d1fc7ab796ce7a334b4fef9cb6d927f616",
          "sha256": "d21a92db76dd25058edda73b756df52cf144be141c8561ca1798b4ab5713ad22",
          "sha1": "47493320464e7dd3b14c00e3dea1a1fbdf740f93",
          "md5": "78a50c7f8486eda25347db74585f0808"
        }
      ]
    }
  ]
}
