{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2514.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2514.0.jar",
          "size": 711495,
          "sha512": "0b8c17d4f42a0d1124ed71d2f96d203a1312f35b82210cabd32900539eca5be30cbd82ffc145a1d89b9e937a6fdbdb19c8783f37d8663a0a839c706e3a08c468",
          "sha256": "f804a5681e12c3b47307cdfe28cfca651284cd710118770f02adc5cd58dd6748",
          "sha1": "fbdd8bdb5e4f94373086bb0d60e54f5b2af0b2e5",
          "md5": "d0be03b3bf2c0772448de3995c65dfd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2514.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2514.0.jar",
          "size": 711495,
          "sha512": "0b8c17d4f42a0d1124ed71d2f96d203a1312f35b82210cabd32900539eca5be30cbd82ffc145a1d89b9e937a6fdbdb19c8783f37d8663a0a839c706e3a08c468",
          "sha256": "f804a5681e12c3b47307cdfe28cfca651284cd710118770f02adc5cd58dd6748",
          "sha1": "fbdd8bdb5e4f94373086bb0d60e54f5b2af0b2e5",
          "md5": "d0be03b3bf2c0772448de3995c65dfd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2514.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2514.0-sources.jar",
          "size": 254282,
          "sha512": "feb5322325ea367a4f1a73505b9f14df9093bbce7f2927972b24ac6107c9499f797b8d6e9b2c45812353dbc2ee6d324a2e49e7fc5340d657e261e2729fc6cc6c",
          "sha256": "1d0f6a9fec1b478a4e5baa0c66f02108dd3c29d599f1be4b2eb34242e6f55b26",
          "sha1": "e72f876825057138489ce6d8b2b2276a9fa0288b",
          "md5": "656d007d7ecf11c2129fa8f54eb92815"
        }
      ]
    }
  ]
}
