{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.6.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.6.jar",
          "size": 466554,
          "sha512": "75fd4ded116f31bcd842b298835dbc7f36895a7dba1d11d37562a5c1fb930024631f4acc24cfa6cb9d553de2fd2b2baab1043266ea8a8eadd23ecc17f15da2ea",
          "sha256": "5ee21e52572e84e55a77d9a744a1639c1aabac6ae11b1c7edcfd1c29f3cab42f",
          "sha1": "383795c51ebad2026ac7f33f61088cb07c7f7159",
          "md5": "976c93adabb511daa43110d4aeb01695"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.6.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.6.jar",
          "size": 466554,
          "sha512": "75fd4ded116f31bcd842b298835dbc7f36895a7dba1d11d37562a5c1fb930024631f4acc24cfa6cb9d553de2fd2b2baab1043266ea8a8eadd23ecc17f15da2ea",
          "sha256": "5ee21e52572e84e55a77d9a744a1639c1aabac6ae11b1c7edcfd1c29f3cab42f",
          "sha1": "383795c51ebad2026ac7f33f61088cb07c7f7159",
          "md5": "976c93adabb511daa43110d4aeb01695"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2504.6-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2504.6-sources.jar",
          "size": 238556,
          "sha512": "dfb672123d308bc5b8a6631a09e4326429f5401f293a78020d4cc9a3f4a977dc4820f10c25d725d99f73010a4b3710c9d44bb04ba4ee5340ec5fdc5ddaa4aaa0",
          "sha256": "9116295bdc02f210eded69c185407da4b9ce25e69513f187d8df60981bee0190",
          "sha1": "cfd9921c8afe19263b83f1f0682c5cc984c46a72",
          "md5": "4144e8226a069af626e9415aaf1d3a1a"
        }
      ]
    }
  ]
}
