{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.1-1.1.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.1-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.1-1.1.2516.0.jar",
          "size": 597348,
          "sha512": "767cb049afca606224135374123c94d86c58c9e7d406490b2387a75df8ea83b9b811812c9a09e2cf836065f03116dde27b381fd9dee43d449380b3b02e779f84",
          "sha256": "e72549e49167d2151782d69f3782f27cec5f7f75f2266f3f03a54abeff2189bf",
          "sha1": "6b18da6f271a91bb45524c2555f741fb1da39f57",
          "md5": "c75ff1d14bd1686332172ddfac3df033"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.1-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.1-1.1.2516.0.jar",
          "size": 597348,
          "sha512": "767cb049afca606224135374123c94d86c58c9e7d406490b2387a75df8ea83b9b811812c9a09e2cf836065f03116dde27b381fd9dee43d449380b3b02e779f84",
          "sha256": "e72549e49167d2151782d69f3782f27cec5f7f75f2266f3f03a54abeff2189bf",
          "sha1": "6b18da6f271a91bb45524c2555f741fb1da39f57",
          "md5": "c75ff1d14bd1686332172ddfac3df033"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.1-1.1.2516.0-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.1-1.1.2516.0-sources.jar",
          "size": 536397,
          "sha512": "cacf781f57f8df9ba2aa4b92785f2393b92bf908ed1de7a5f12c799ab263560d557ca8be10b4f61c2bc05973927cffd7b644ce72428ad7f6e444bc740c91839a",
          "sha256": "a00289a74e2edbbe9ac80d50534e694bdabcf4c75cb522f5888bfef4c41f4c29",
          "sha1": "238bd8945806577b548ede8227a5e89f05dfdd85",
          "md5": "c9309e5c9f61127c7227dea7ede29ec3"
        }
      ]
    }
  ]
}
