{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.8-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2617.2.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2617.2.jar",
          "size": 603413,
          "sha512": "629da2e9830b5506b79a4fafa49806967f28c50100d41de010e75a84f835f49fd8a83e06f55e755cd7837fc2e23ae252f607fc2ac0d92dcd20ebae048083fb21",
          "sha256": "0073b7b9cbd4802e1aedfabc212caf5b8391e84dd0c36d1f1aad71646ea7ccc3",
          "sha1": "3ab3e0c52345d12a43384ed21b3ef35d48d64947",
          "md5": "cd04d841a476aee401379efc18c04772"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.131.0+1.21.8"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "15.0.0-beta.3"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2617.2.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2617.2.jar",
          "size": 603413,
          "sha512": "629da2e9830b5506b79a4fafa49806967f28c50100d41de010e75a84f835f49fd8a83e06f55e755cd7837fc2e23ae252f607fc2ac0d92dcd20ebae048083fb21",
          "sha256": "0073b7b9cbd4802e1aedfabc212caf5b8391e84dd0c36d1f1aad71646ea7ccc3",
          "sha1": "3ab3e0c52345d12a43384ed21b3ef35d48d64947",
          "md5": "cd04d841a476aee401379efc18c04772"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2617.2-sources.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2617.2-sources.jar",
          "size": 256751,
          "sha512": "b7fc74ef9074c8e18ad1fb6a6ce4a8dc81bee0361e8128794f03d32a99fe49ef19f50f4893808ac536ce227d1b436a3793a43f90cbb9e2b6ada719ae9a9c3c60",
          "sha256": "7c355fbffc4a01231e3641d6b1306c509ba16554af39f18053d1fbae01baadd3",
          "sha1": "8a24ea300bb80d81ccafb371af722fc1cc0e0ebf",
          "md5": "30595b52dd40d2cc5fd408b97b82d76f"
        }
      ]
    }
  ]
}
