{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2507.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.15.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.15.jar",
          "size": 498841,
          "sha512": "8bee6fdc96f748646d8b1fd640f0d92386053814eab0de99a5c76ddb338c39b3797d6fd784c28d421eb98323080763d60707ebfe19d9b877c3b5543932daee64",
          "sha256": "6da11b153b5ec216ba9035757fd5ebaf41a7db45ba990aa6c4c9973c7d45037a",
          "sha1": "4c2cf70d75a657b1c5f80115d81bf0d03c24fcdc",
          "md5": "648b69817400e0676fddbca67c39cb69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.15.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.15.jar",
          "size": 498841,
          "sha512": "8bee6fdc96f748646d8b1fd640f0d92386053814eab0de99a5c76ddb338c39b3797d6fd784c28d421eb98323080763d60707ebfe19d9b877c3b5543932daee64",
          "sha256": "6da11b153b5ec216ba9035757fd5ebaf41a7db45ba990aa6c4c9973c7d45037a",
          "sha1": "4c2cf70d75a657b1c5f80115d81bf0d03c24fcdc",
          "md5": "648b69817400e0676fddbca67c39cb69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.15-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.15-sources.jar",
          "size": 244910,
          "sha512": "0474d171bb549a3babad670172129701c0322ee78f011a824cea9910775c63ea0d5b18758ede6e2b62d2f7037f1b49b2eec00566c8189d10e1e9b9e650dba5e9",
          "sha256": "0398f65ef8ba9a4819aefcb23c2355de8cbf4ed61db7137f78ae24778057c87a",
          "sha1": "cadbafa7853467787b7f843c2f2a148ac8f29c5e",
          "md5": "77ff1a6c805bb76a05b8a19f4e68d7ca"
        }
      ]
    }
  ]
}
