{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.7-1.8.2.2529.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.7-1.8.2.2529.0.jar",
          "url": "legacy-forge-1.21.7-1.8.2.2529.0.jar",
          "size": 19951304,
          "sha512": "fdcab843e021e6dea4f5cacd601bbacc24334a03bc409ca78e43646abc69775d866c9c5294b2579bb15c56acf8777a5ded3692eac729443bd76862837840bb4e",
          "sha256": "d2d9c8ab31bd2abd623f3c78c824b62a48e42489f11c626e16d0dbd1e55d33a0",
          "sha1": "aea90e1e4e4c37ad8676c6a7d3b96497a78ad6fd",
          "md5": "78521e23c0007eafa63335fbb77a272c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.7-1.8.2.2529.0.jar",
          "url": "legacy-forge-1.21.7-1.8.2.2529.0.jar",
          "size": 19951304,
          "sha512": "fdcab843e021e6dea4f5cacd601bbacc24334a03bc409ca78e43646abc69775d866c9c5294b2579bb15c56acf8777a5ded3692eac729443bd76862837840bb4e",
          "sha256": "d2d9c8ab31bd2abd623f3c78c824b62a48e42489f11c626e16d0dbd1e55d33a0",
          "sha1": "aea90e1e4e4c37ad8676c6a7d3b96497a78ad6fd",
          "md5": "78521e23c0007eafa63335fbb77a272c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.7-1.8.2.2529.0-sources.jar",
          "url": "legacy-forge-1.21.7-1.8.2.2529.0-sources.jar",
          "size": 19053798,
          "sha512": "8b3b10c68a29383b6c1ea85419444ade0aeb90f43ba06e1b0efe22e6952938e9be67a62dddac3bedaadfec933646ad5d1f425a5497b5ea4f19b8bdbb2923d00e",
          "sha256": "435a1d4240ae6ecab710bfbfe0d9f1376f0d3bd5c3a74f7452e15108d1d3b4e9",
          "sha1": "33036c4442ba58fb504b4526405481e6fc094fa8",
          "md5": "e00ad14f7bc9fa8b995e865378acac00"
        }
      ]
    }
  ]
}
