{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.jar",
          "size": 545449,
          "sha512": "dc7ae5b4b92d09d14ae9112bc9377ee3d6cb6ed297f2c5ab326b82233d6db4b18252189dd1e4587e06e1b4819f4e168f9cca1b03253a5264534b1e720dcbd6d8",
          "sha256": "a0444848b26dee7b140377fe8a86db1f1735aa92d4a4cc09cb5cb73e06ad37ba",
          "sha1": "3e96991d145892362cf7d17e63c6943e17b1e621",
          "md5": "7e20a4427e7b9f3da6f9a8f14c35d0d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.jar",
          "size": 545449,
          "sha512": "dc7ae5b4b92d09d14ae9112bc9377ee3d6cb6ed297f2c5ab326b82233d6db4b18252189dd1e4587e06e1b4819f4e168f9cca1b03253a5264534b1e720dcbd6d8",
          "sha256": "a0444848b26dee7b140377fe8a86db1f1735aa92d4a4cc09cb5cb73e06ad37ba",
          "sha1": "3e96991d145892362cf7d17e63c6943e17b1e621",
          "md5": "7e20a4427e7b9f3da6f9a8f14c35d0d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7-sources.jar",
          "size": 269406,
          "sha512": "20feae62ee485e3e3b5bac051909d8c7f8e073e841e7009e67ae61509df4e48f422dddada0623abe6ee8b1a549dadee2529b8def06fc7a9e30ac292626596225",
          "sha256": "cadb327781836cdf31e6b700dcc1b76c401ceb904daf5e63b4f7d5235b8c2a03",
          "sha1": "129a0a4b1b283a8d35c84b933ce852fafb1431d1",
          "md5": "cf4bdb5abdbedcf000d26852179a2eb0"
        }
      ]
    }
  ]
}
