{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.10-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.21.10-2.2.6.2545.0.jar",
          "size": 722434,
          "sha512": "0b7c2a765e6643224d1bfa37b070fbc857e5ccd594a7367526e234e2160f939c87f32f8b6e003dc43e19f30952380d7e42712da779409c35f1bbc3b1ad0711f3",
          "sha256": "4ba8276e9053eb1c30bb80c088af57090588f80735aae0daace9155ac6a343c3",
          "sha1": "3f43033209a3e3e886621970580f51b02b4d0c0c",
          "md5": "e59ca9408d9e0324f0281734833f64cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.21.10-2.2.6.2545.0.jar",
          "size": 722434,
          "sha512": "0b7c2a765e6643224d1bfa37b070fbc857e5ccd594a7367526e234e2160f939c87f32f8b6e003dc43e19f30952380d7e42712da779409c35f1bbc3b1ad0711f3",
          "sha256": "4ba8276e9053eb1c30bb80c088af57090588f80735aae0daace9155ac6a343c3",
          "sha1": "3f43033209a3e3e886621970580f51b02b4d0c0c",
          "md5": "e59ca9408d9e0324f0281734833f64cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.6.2545.0-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.6.2545.0-sources.jar",
          "size": 268525,
          "sha512": "da4d4fdc5f3835788692d941921edd9de8539c8ca49f5f040b409f40572376a727a69fb6fb485f69390590afa0655a89e65b4f7e8558d52cd0a088db6309fb94",
          "sha256": "876108cc407a3fc93718f76dede53c794f6bead56e7c2ed1a8a34ef4b75f0f1f",
          "sha1": "8194c1f84773267a64e87a2747f4a7cc93a026fa",
          "md5": "7c25aad485a626496058061db4349e54"
        }
      ]
    }
  ]
}
