{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.8.0.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2516.2.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2516.2.jar",
          "size": 18262802,
          "sha512": "bb7efa4db03529cf8dd7afff50249475dc8e5be769d49185e2708675381f3718944fd77be4b851af3342a2a87ad6e7f6f565a34cadc1fde818b4ef57c104e534",
          "sha256": "8f1435d666fe5ab6f99f8bce93e76964e1aa9252eeab710d185f209e0b2760dd",
          "sha1": "ab430642536214258f08ff4ce78b40137fccca5d",
          "md5": "ae4a9c8bc44a5b48208574bf6d6b5970"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2516.2.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2516.2.jar",
          "size": 18262802,
          "sha512": "bb7efa4db03529cf8dd7afff50249475dc8e5be769d49185e2708675381f3718944fd77be4b851af3342a2a87ad6e7f6f565a34cadc1fde818b4ef57c104e534",
          "sha256": "8f1435d666fe5ab6f99f8bce93e76964e1aa9252eeab710d185f209e0b2760dd",
          "sha1": "ab430642536214258f08ff4ce78b40137fccca5d",
          "md5": "ae4a9c8bc44a5b48208574bf6d6b5970"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2516.2-sources.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2516.2-sources.jar",
          "size": 17423579,
          "sha512": "6429919d91b3d36f2f4eff418b73eaf9c86ab3ccf7b4c266a870eb1d0306cc118467a5122f9f100fe4ace38b2eb750b10ab78e8d2389326594a2db716b88bbcf",
          "sha256": "7303d1475f74be84e0807cc3978d80fe3341b35d9c220f11a061b151b332a4ce",
          "sha1": "7f08b4ebecc548d6221eb14b02bd163ea4543fcd",
          "md5": "4081883fb265cc0637010d7f7ddc66d2"
        }
      ]
    }
  ]
}
