{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.7.2616.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2616.1.jar",
          "size": 537935,
          "sha512": "e05ac3e5438a935d6816ba50e87a010a32e3203a1aae1227a525272f5dcd0aba8dd19d9739dea92a33c7e846641ac9d58056f73a802a023940676507f7146c24",
          "sha256": "33a998cba6a70ced99662ec140f2bb425a058abbd439eaf32b3c138d03e33060",
          "sha1": "c9ce0ad2cf03e70bd08fd342785421bda6d92412",
          "md5": "c805d9f82aebb5b511ed46fdd6778b7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2616.1.jar",
          "size": 537935,
          "sha512": "e05ac3e5438a935d6816ba50e87a010a32e3203a1aae1227a525272f5dcd0aba8dd19d9739dea92a33c7e846641ac9d58056f73a802a023940676507f7146c24",
          "sha256": "33a998cba6a70ced99662ec140f2bb425a058abbd439eaf32b3c138d03e33060",
          "sha1": "c9ce0ad2cf03e70bd08fd342785421bda6d92412",
          "md5": "c805d9f82aebb5b511ed46fdd6778b7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2616.1-sources.jar",
          "size": 256832,
          "sha512": "b4f59ddbf51fcd7c0c2f9dc1ef0c29bf5df1dc8fa5533957c36a6ff269b564d22eb47f1dcba5228e9fb3206d948a8b04881dbb335007bed3336e74929ed8adb2",
          "sha256": "1a7e9e54ad453d0eafa169f3940aca1bac4b6b01e320fb3a8655aac4cafc1f75",
          "sha1": "2da03e49d6a09dbdf3858675899808e1ecddda54",
          "md5": "bed6ddee9856828f14188467a6d73e3d"
        },
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2616.1-sources.jar",
          "size": 256832,
          "sha512": "b4f59ddbf51fcd7c0c2f9dc1ef0c29bf5df1dc8fa5533957c36a6ff269b564d22eb47f1dcba5228e9fb3206d948a8b04881dbb335007bed3336e74929ed8adb2",
          "sha256": "1a7e9e54ad453d0eafa169f3940aca1bac4b6b01e320fb3a8655aac4cafc1f75",
          "sha1": "2da03e49d6a09dbdf3858675899808e1ecddda54",
          "md5": "bed6ddee9856828f14188467a6d73e3d"
        }
      ]
    }
  ]
}
