{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.6.2541.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.0.jar",
          "size": 516972,
          "sha512": "b6ecb43e43b196af257a4375344ad048a8475e04986f174ca86e600add219010dae962e7f6182c2ce3a8ef8ecc7687cc7fd889a2a891f68c39cb96ad42ced315",
          "sha256": "06dda7b1d95f0964b5accfcee64932787b6ba79d143c1d93f4ad97bc476f2d2e",
          "sha1": "f4a9d9c9fc01911eec7c0ec7bd6b606fdd85b768",
          "md5": "0f1eeaddcd770ef30ad206b1144496bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.0.jar",
          "size": 516972,
          "sha512": "b6ecb43e43b196af257a4375344ad048a8475e04986f174ca86e600add219010dae962e7f6182c2ce3a8ef8ecc7687cc7fd889a2a891f68c39cb96ad42ced315",
          "sha256": "06dda7b1d95f0964b5accfcee64932787b6ba79d143c1d93f4ad97bc476f2d2e",
          "sha1": "f4a9d9c9fc01911eec7c0ec7bd6b606fdd85b768",
          "md5": "0f1eeaddcd770ef30ad206b1144496bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.0-sources.jar",
          "size": 267759,
          "sha512": "2ebcca8f2ccb9cf180669323e9ac9d5322ba998afde1bdb61f8a0d12fb3e3884a2403f44671bd29638fcf6e8acc8f5202171220be1c60014bc83877011b902db",
          "sha256": "19727b84cc381fa001c09521d4687ba627132597ae0fb82e3b644c914746bee7",
          "sha1": "6c52edc0a5ab9928416e0faee76ce6ecc0f492d3",
          "md5": "d85c0cf17db9ff7a0250834eb6c0ae62"
        }
      ]
    }
  ]
}
