{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.1-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2516.1.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2516.1.jar",
          "size": 541439,
          "sha512": "1c79f82113690c35459a1764c1201d19e196fd97b5e22ac759539523dd23571bfa9a687c27807b83c865ff963a9a2eb654351cb1eb245905c5e630560c982b3e",
          "sha256": "e147b62f945ed094cb067a52c3ce56ee7f6d77a7210bc8a5c3ae9af72205be8b",
          "sha1": "e660b1934df7045744905dc9e4315360634d598c",
          "md5": "75a6fab0100a1d39b908a9e14288f365"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2516.1.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2516.1.jar",
          "size": 541439,
          "sha512": "1c79f82113690c35459a1764c1201d19e196fd97b5e22ac759539523dd23571bfa9a687c27807b83c865ff963a9a2eb654351cb1eb245905c5e630560c982b3e",
          "sha256": "e147b62f945ed094cb067a52c3ce56ee7f6d77a7210bc8a5c3ae9af72205be8b",
          "sha1": "e660b1934df7045744905dc9e4315360634d598c",
          "md5": "75a6fab0100a1d39b908a9e14288f365"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2516.1-sources.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2516.1-sources.jar",
          "size": 251655,
          "sha512": "778a71ee9db70fadd9267179c80c8f9e5a8af82a88a89349f670d6b626c01dfba7dc46b07e2808988ade8fe52d0a36debf5a06d3d09e3deccfa844cdad3b3875",
          "sha256": "b2e27d63199d8945bbd264648dbba67d6cd0f1b4b8a48ceffe8fe3174cf01f8a",
          "sha1": "c639e3df42774d697babaad4ce14882616287029",
          "md5": "8bdadf78b29b011e0742202e11fb8099"
        }
      ]
    }
  ]
}
