{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2513.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.2.jar",
          "size": 514234,
          "sha512": "c18dd39e29b452f630fc0f2c6ba9a5a875534779afdc614ee096fbb16c1ee755bfc0b13f66d11d824dae47dc1d465115cf545232203830121f1fad1a38da3055",
          "sha256": "f8a5b7f7bbfafae1b9b9b91570b1b52fa8482b9c5d8e8f87c16bdeb127f96d4a",
          "sha1": "20cb082fb7b6ac8932ec96225b7902d36103f443",
          "md5": "60f61db4ed662f5e8af9093621200477"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.2.jar",
          "size": 514234,
          "sha512": "c18dd39e29b452f630fc0f2c6ba9a5a875534779afdc614ee096fbb16c1ee755bfc0b13f66d11d824dae47dc1d465115cf545232203830121f1fad1a38da3055",
          "sha256": "f8a5b7f7bbfafae1b9b9b91570b1b52fa8482b9c5d8e8f87c16bdeb127f96d4a",
          "sha1": "20cb082fb7b6ac8932ec96225b7902d36103f443",
          "md5": "60f61db4ed662f5e8af9093621200477"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.2-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.2-sources.jar",
          "size": 250886,
          "sha512": "6683f11086af62f4b51f0b2b48a33d733d7ec1af9ce3462e7914298e2db02c2f33ab989a63a3665664e3aa30aeaca8c823596248baf82bcd937ff18c1fbce119",
          "sha256": "0f00e39ebf454fe9b3c2e553a0b49c068064beb0820b6885f1d1204736f0e444",
          "sha1": "3bceb2cec9a5d02978340b5d95355098931fb960",
          "md5": "630ff4196e9338dcfd204e8ebd77b4ab"
        }
      ]
    }
  ]
}
