{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2502.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.12.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.12.jar",
          "size": 443699,
          "sha512": "7807cdc5a1db8eb497d5b876381b91d8b9838de77e13f7dc0d19a58e8305097992725f45fd494d6f78c4ea67f0a9e7256144d7db7d3bc1c05eb353a474443fec",
          "sha256": "fe4d55abd822b0056d2ce523713df976c1d10e5d07d9c66f218abfe481952434",
          "sha1": "ba6b7b818d3fe54ccbcad53cbd3bfafe7ee49efc",
          "md5": "a9dde59746da5a19b68f447367eae629"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.12.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.12.jar",
          "size": 443699,
          "sha512": "7807cdc5a1db8eb497d5b876381b91d8b9838de77e13f7dc0d19a58e8305097992725f45fd494d6f78c4ea67f0a9e7256144d7db7d3bc1c05eb353a474443fec",
          "sha256": "fe4d55abd822b0056d2ce523713df976c1d10e5d07d9c66f218abfe481952434",
          "sha1": "ba6b7b818d3fe54ccbcad53cbd3bfafe7ee49efc",
          "md5": "a9dde59746da5a19b68f447367eae629"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.12-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.12-sources.jar",
          "size": 227599,
          "sha512": "9776c19b83209c5306600165db299b78a75cbcd2ce41bf148649f50f9389a44c40e31186c9fced39aaa18ba0e9d5489fbe84f2ada4ab0e6c2657931bdc5074ec",
          "sha256": "16322ff268129875966f954e616f2ff4caf2d168daf35aac64c2069d1a623456",
          "sha1": "fd2eec3088830d6e07bdc297f3c598dcf31f8b0a",
          "md5": "9bba683b6b004d2810a394271ec0e763"
        }
      ]
    }
  ]
}
