{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.1.jar",
          "size": 711820,
          "sha512": "62756a3ac9328b5b466a3a8cdb35af7591ca2183501f455565c8db9a2baa88ec22bcd0b5b067941ea8c03498fc6c524b6b3da766fa7f263a87def1621e60e7eb",
          "sha256": "ba311593c74ec1d8c9f92191fc3384feee600b95888158214ea3fb3ac57f8ff3",
          "sha1": "93e5a29ef937ea2a054c94e286f7afca783276f2",
          "md5": "6b8d3f503ebe10599f8e86542d4f0c21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.1.jar",
          "size": 711820,
          "sha512": "62756a3ac9328b5b466a3a8cdb35af7591ca2183501f455565c8db9a2baa88ec22bcd0b5b067941ea8c03498fc6c524b6b3da766fa7f263a87def1621e60e7eb",
          "sha256": "ba311593c74ec1d8c9f92191fc3384feee600b95888158214ea3fb3ac57f8ff3",
          "sha1": "93e5a29ef937ea2a054c94e286f7afca783276f2",
          "md5": "6b8d3f503ebe10599f8e86542d4f0c21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.1-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.1-sources.jar",
          "size": 253517,
          "sha512": "3356c08f882c1d03e8fd7caa2015d7b66d4a02a04c7d3c23231a2550ce82e4004aa40a17d4fb39b3ae8989e2f21e917316ec8f0d0c0f3affada7e2cece896fb5",
          "sha256": "927024b22f8e858021d38d8cdfd4107b2ced92009dd22bd179a9b09ab47c5f2d",
          "sha1": "3264f95cb56860a0d514bc60015d8ec7c5aceccf",
          "md5": "715faf99e90b64b887a01baeaf4f8288"
        }
      ]
    }
  ]
}
