{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "26.1.1-2.2.7.2615.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2615.2.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2615.2.jar",
          "size": 561994,
          "sha512": "417e13ee0e5baca68df0b69cf2e20782877f41e00d2cbd5500da7ba6920888a05053f674ba8d8e0ebc6ecf9a2bad1104bef6dd420ea60672eac77a7e10cb2fee",
          "sha256": "3426c614a617c549843c1ee33deaec84fd0f1b414f14ba59d08840effcce48a0",
          "sha1": "020d0d01aea566f3ddf7f82b6e6c435fb24ab366",
          "md5": "d1f891c7d6a79d1fc41572bef02d5d70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2615.2.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2615.2.jar",
          "size": 561994,
          "sha512": "417e13ee0e5baca68df0b69cf2e20782877f41e00d2cbd5500da7ba6920888a05053f674ba8d8e0ebc6ecf9a2bad1104bef6dd420ea60672eac77a7e10cb2fee",
          "sha256": "3426c614a617c549843c1ee33deaec84fd0f1b414f14ba59d08840effcce48a0",
          "sha1": "020d0d01aea566f3ddf7f82b6e6c435fb24ab366",
          "md5": "d1f891c7d6a79d1fc41572bef02d5d70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2615.2-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2615.2-sources.jar",
          "size": 257034,
          "sha512": "e3bd5fae1313346e16998470e96ff4912c58413d0bb57a85b0d09a9afd18ee7a563389806fbb2d995c82f255bf0e3571482990e3ef9fbb5ad9c2016dc3464499",
          "sha256": "d064ef6aee3e3bf44d4e243da8624fa8673c835486b795e0d66fcbab3b57164c",
          "sha1": "9622a85c6d078bcc0e192336b09d07d62298c00d",
          "md5": "c97a1654a00416d92a257fd073ee5a21"
        },
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2615.2-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2615.2-sources.jar",
          "size": 257034,
          "sha512": "e3bd5fae1313346e16998470e96ff4912c58413d0bb57a85b0d09a9afd18ee7a563389806fbb2d995c82f255bf0e3571482990e3ef9fbb5ad9c2016dc3464499",
          "sha256": "d064ef6aee3e3bf44d4e243da8624fa8673c835486b795e0d66fcbab3b57164c",
          "sha1": "9622a85c6d078bcc0e192336b09d07d62298c00d",
          "md5": "c97a1654a00416d92a257fd073ee5a21"
        }
      ]
    }
  ]
}
