{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2510.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2510.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2510.1.jar",
          "size": 696132,
          "sha512": "fbc8da44c4ae3e53e7c0e29c68441c10bcbf86832524adc18cb262283979fcdbc2e37af241b3cc60576720df70299780139f1e688a88136bf298876e2147c937",
          "sha256": "aebf848132ca00b59a628b55cedd68e66db72b01a69389e5b98fce9e141a0478",
          "sha1": "2a31b9fe4371d009d0ce9b5c1c1bf9b37261e621",
          "md5": "fa76180cff4798adbef11eaef3758961"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2510.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2510.1.jar",
          "size": 696132,
          "sha512": "fbc8da44c4ae3e53e7c0e29c68441c10bcbf86832524adc18cb262283979fcdbc2e37af241b3cc60576720df70299780139f1e688a88136bf298876e2147c937",
          "sha256": "aebf848132ca00b59a628b55cedd68e66db72b01a69389e5b98fce9e141a0478",
          "sha1": "2a31b9fe4371d009d0ce9b5c1c1bf9b37261e621",
          "md5": "fa76180cff4798adbef11eaef3758961"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2510.1-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2510.1-sources.jar",
          "size": 250447,
          "sha512": "602c756c0657db7c113a057c646791084d816845bcf7baad883969540b24f39f85c1ad7e7bcde5897b36c066b695fcffc774366e915a3679c918ffd15e1701e4",
          "sha256": "38d0202ace6f049c9248e22e54d0f06561cb79f21af9b47796c7a2533e77715d",
          "sha1": "73bbf540a4480fb7e1c41eb8ee12016cd6059a3f",
          "md5": "7ae548a93d120076534705acd585e263"
        }
      ]
    }
  ]
}
