{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2501.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.1.jar",
          "size": 365081,
          "sha512": "bdb7a9bc1f6e9043ae2bf0507de1ae6e46f24dc0b7f5c40cbd55a41c0f1da4f64064d3725c8f64c657bd563018a0b5bce1f0fd9e10cddd5dbb6a3c3c85770a5a",
          "sha256": "60e39d6a123dd9f5bf0f40413831e64f021525382ff3a189f9816a5964d9e611",
          "sha1": "b5de43fbf144feb380be61cbed03f8726759b5ee",
          "md5": "5cd908e52d6a43b53b1bdf78cb359228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.1.jar",
          "size": 365081,
          "sha512": "bdb7a9bc1f6e9043ae2bf0507de1ae6e46f24dc0b7f5c40cbd55a41c0f1da4f64064d3725c8f64c657bd563018a0b5bce1f0fd9e10cddd5dbb6a3c3c85770a5a",
          "sha256": "60e39d6a123dd9f5bf0f40413831e64f021525382ff3a189f9816a5964d9e611",
          "sha1": "b5de43fbf144feb380be61cbed03f8726759b5ee",
          "md5": "5cd908e52d6a43b53b1bdf78cb359228"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.1-sources.jar",
          "size": 193592,
          "sha512": "4dedf856a98547e41db0f504f2bbf575fe47d1fc43f0af911b8a02da296d2a27b4a560990bfdc19ff49ff29bb635f1def7d30a90a65872dec3f810cb18ecc610",
          "sha256": "a6aa058dd92e3eb8484bab75a3e3dc39882eb92a8b385ac86e8bd63ef7294ddc",
          "sha1": "af7ebe09cfc0694b19ac37d1bfbd1b050c3d724d",
          "md5": "22c3e971632744ec54c984f93dba4e6c"
        }
      ]
    }
  ]
}
