{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2518.3.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2518.3.jar",
          "size": 19784949,
          "sha512": "9bbe0d3b1c5a7431fa1a2664ce3a277512ebd3cbdeab5c4b400ca2af78d88ee5a621455a980d04efd0f3a68c72d37269f56812ad01ceaba141240ab59c3f127b",
          "sha256": "7a23f61cde5ce6741a94020fdd42836a2d0d9f28b938c98129a592a6c184c260",
          "sha1": "759e4c603691ce8409686254454fd5ede2b68081",
          "md5": "d1523503f83646f8b46b5f623158c7b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2518.3.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2518.3.jar",
          "size": 19784949,
          "sha512": "9bbe0d3b1c5a7431fa1a2664ce3a277512ebd3cbdeab5c4b400ca2af78d88ee5a621455a980d04efd0f3a68c72d37269f56812ad01ceaba141240ab59c3f127b",
          "sha256": "7a23f61cde5ce6741a94020fdd42836a2d0d9f28b938c98129a592a6c184c260",
          "sha1": "759e4c603691ce8409686254454fd5ede2b68081",
          "md5": "d1523503f83646f8b46b5f623158c7b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2518.3-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2518.3-sources.jar",
          "size": 18904463,
          "sha512": "8dcf4c92a28dce7ffc48c6befe80a11f485a69e915d1525041cf364a2a4caeda6688f2353df779ac943ef6a9bd28f9b335b18b93f784b89f65bcb9b1369da3bb",
          "sha256": "4d28681f681e0819b49d3e7fa87d438d71b1ec86335f00b10e9cf937f944836f",
          "sha1": "cdf6eae29dd0a55876d7eb041aa44689bf8ff66e",
          "md5": "f92b3e5a8be0806b915295209c637c11"
        }
      ]
    }
  ]
}
