{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.7.10.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2509.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2509.1.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2509.1.jar",
          "size": 14421136,
          "sha512": "631555014d5186056b5560867f5c37b2a4b3a75005eae4559ec48e0015bf9d8e4a93441ac60555084a6c29fa6ee04849b9e902461ddb0b774b0e01031849c41a",
          "sha256": "b89702b7b804910f0f10e0ae4411694cb9f348a8eab445ea503cde98c85775d2",
          "sha1": "6d67ed9d493b1dda8f4b547d690691f37c438bd2",
          "md5": "427988580caa678045b7a3acb29e5b30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2509.1.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2509.1.jar",
          "size": 14421136,
          "sha512": "631555014d5186056b5560867f5c37b2a4b3a75005eae4559ec48e0015bf9d8e4a93441ac60555084a6c29fa6ee04849b9e902461ddb0b774b0e01031849c41a",
          "sha256": "b89702b7b804910f0f10e0ae4411694cb9f348a8eab445ea503cde98c85775d2",
          "sha1": "6d67ed9d493b1dda8f4b547d690691f37c438bd2",
          "md5": "427988580caa678045b7a3acb29e5b30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2509.1-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2509.1-sources.jar",
          "size": 13582867,
          "sha512": "319f6df33758f8bd807a52a00d84a47c7e23948227939e18e74d5087fdd3ead1f71bfd540c5c6c82624106d1cba7bb05f4ae71c8092798fee78ce9455d18a364",
          "sha256": "8037a0429330f0f76a715c95bafd2d2516bdd5029c5a02cf960bbdc3ad6907dc",
          "sha1": "c51b959d9dd9dcad4686ec9e2d8a09998eaa6924",
          "md5": "7008efc457fc049302c13bf9fdd6f68a"
        }
      ]
    }
  ]
}
