{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2511.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2511.1.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2511.1.jar",
          "size": 18240464,
          "sha512": "99d1cd1f68926b2da56f7cd8c75b989d79c3fe597dff633924d6588e8971b939d4ec3f2c719affcb2667e2ae687d5cbbd2e9497d908cca059324cec68a20ae25",
          "sha256": "e907081b804cb70ae63cc81433b61330ea3fb2fee1675a6637e77013e0ba8977",
          "sha1": "1d1131869b777434cfb4df912e120d468c51cf7e",
          "md5": "cb3878e78f30cb6f787346a813932601"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2511.1.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2511.1.jar",
          "size": 18240464,
          "sha512": "99d1cd1f68926b2da56f7cd8c75b989d79c3fe597dff633924d6588e8971b939d4ec3f2c719affcb2667e2ae687d5cbbd2e9497d908cca059324cec68a20ae25",
          "sha256": "e907081b804cb70ae63cc81433b61330ea3fb2fee1675a6637e77013e0ba8977",
          "sha1": "1d1131869b777434cfb4df912e120d468c51cf7e",
          "md5": "cb3878e78f30cb6f787346a813932601"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2511.1-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2511.1-sources.jar",
          "size": 17409398,
          "sha512": "dbb3a20f4f9f0b14eb5363c9b0c8ab4cfc64c386953f8a9fdb8627a08a815902a7bad85c15871dc8630ecfd01e11b03908affae4c3210f402fd3269b0c8bd1b2",
          "sha256": "4624df21a06fee8c99724a3416c54b0154458703ffedd0116b30e761cca88649",
          "sha1": "e69b187a08b3c78666458f203043a73fdaec1f71",
          "md5": "98e783d2af981b9f7f1117c88ebd077e"
        }
      ]
    }
  ]
}
