{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.0.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.0.jar",
          "size": 18269658,
          "sha512": "3829ba84e7a35e6e119ce8f85fb28ac930e3b7b26a0e71b95d0bda16d2318699d6da2d9d15c9c3e53d3b83c85adeb0f9c4e7b232a72e24e6843d9432b74f2207",
          "sha256": "94e11d62cd84b2755a4efecd9f0a88ee32ed221b8b27cb7e66de220cc1e9ce5f",
          "sha1": "5b683fc882cb662eb238335a5f15c4eaa20e02b5",
          "md5": "4df8c477155e0ffdd707fcdeb14925f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.0.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.0.jar",
          "size": 18269658,
          "sha512": "3829ba84e7a35e6e119ce8f85fb28ac930e3b7b26a0e71b95d0bda16d2318699d6da2d9d15c9c3e53d3b83c85adeb0f9c4e7b232a72e24e6843d9432b74f2207",
          "sha256": "94e11d62cd84b2755a4efecd9f0a88ee32ed221b8b27cb7e66de220cc1e9ce5f",
          "sha1": "5b683fc882cb662eb238335a5f15c4eaa20e02b5",
          "md5": "4df8c477155e0ffdd707fcdeb14925f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.0-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.0-sources.jar",
          "size": 17433899,
          "sha512": "0d735b30276b7fe75b8835a86dd756014ec30e3a2882d33131e2bdd8444ea8610fba5c79d14ca4cd766752a5bcec997596df13113d931dd130931f0816025097",
          "sha256": "377a6cdf16bfbf8fdc3a64d5dfa334d0505f5b4a5998d59e49f53c53bba454d4",
          "sha1": "d240ddb890cd2a26c28ac9cdd45625fef4cb2cbc",
          "md5": "0d7355dec9915b9dfbc23ab180093cbc"
        }
      ]
    }
  ]
}
