{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2502.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.5.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.5.jar",
          "size": 454148,
          "sha512": "0cbb33866c2f2af9daf61a2a48800c3a381e426d2c47628fa85cd3976f81ed7c17691542dfc5f798c377972943f5be4e65a09a7c45a74a0bbc1d9f24dd5c3947",
          "sha256": "df4af689988d7d3240698976fa261551a15ed2f5107b5b00705f94e4d19a3165",
          "sha1": "52955c85ab2ab5070b7827c722dd619373f1d836",
          "md5": "0406bcd8c567392b5b860ca07fa4cd9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.5.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.5.jar",
          "size": 454148,
          "sha512": "0cbb33866c2f2af9daf61a2a48800c3a381e426d2c47628fa85cd3976f81ed7c17691542dfc5f798c377972943f5be4e65a09a7c45a74a0bbc1d9f24dd5c3947",
          "sha256": "df4af689988d7d3240698976fa261551a15ed2f5107b5b00705f94e4d19a3165",
          "sha1": "52955c85ab2ab5070b7827c722dd619373f1d836",
          "md5": "0406bcd8c567392b5b860ca07fa4cd9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.5-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.5-sources.jar",
          "size": 223579,
          "sha512": "d98bc39a1230c5a90982c6a633a0c795737baf8335c9901d7068ea01df81cddf94101ef87a1a28bff833d7f1f42bc6875ccd4a2d12450829d69389541a427e00",
          "sha256": "01d489f9b79a556627878a47eac7b4e0467c876596c8726a4a3b0478c26f0363",
          "sha1": "d855ba5b592766bc4509cd3edc7ea0138adafe47",
          "md5": "8653bb11847ba69baaefc5267ebcaec1"
        }
      ]
    }
  ]
}
