{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.6.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.6.jar",
          "size": 463711,
          "sha512": "750316a36df124144f2b3b403c4c48efa26bffef74216335ec7cf23ab8b757113d585d9502b6c0486ef2344d8127467333e084a0b26f04aebee57f59575f3626",
          "sha256": "7221a9060008dce09185481fbdc97c9c37ae4671fe3e4aaedfb550138d5ddf2c",
          "sha1": "862af46a64f5493572136877afddeecd35f644c5",
          "md5": "7ba244304ac847b57f5a043c0ea286be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.6.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.6.jar",
          "size": 463711,
          "sha512": "750316a36df124144f2b3b403c4c48efa26bffef74216335ec7cf23ab8b757113d585d9502b6c0486ef2344d8127467333e084a0b26f04aebee57f59575f3626",
          "sha256": "7221a9060008dce09185481fbdc97c9c37ae4671fe3e4aaedfb550138d5ddf2c",
          "sha1": "862af46a64f5493572136877afddeecd35f644c5",
          "md5": "7ba244304ac847b57f5a043c0ea286be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.6-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.6-sources.jar",
          "size": 236922,
          "sha512": "73e82a42422c50ae9c13d81c16a2cb08ceb004e6e6aaeba359097c25d980606870b1f5df6c4d8201809a29639013a6324bc26b3fabe310b47eb93fc56520e529",
          "sha256": "d8b503994a623fc2744a4c3d81e122489e3b8ba96b818c43b2bfc11383a3f80e",
          "sha1": "674349a0dfbeea26c862992e57c819f206223497",
          "md5": "e121441f526dc0557bd5fe6003b06a9b"
        }
      ]
    }
  ]
}
