{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.5-1.1.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.2.jar",
          "size": 645126,
          "sha512": "dd1db8b97c2c1823bfaddaa281153adb09d0f1736dfc96d61eb62ee7053bbc42d8228110b33e1ea83897835187fb81a3963834aeca3043da69ececcd5175249c",
          "sha256": "3196532da1dd07866a99e2c212a33ad40b09e5a710655ebf4b0e10fbedc08647",
          "sha1": "9ee44b904dc893fc223b4b10446fa95b443bd931",
          "md5": "a58f9015b53acc13d33a83bf3c36b670"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.2.jar",
          "size": 645126,
          "sha512": "dd1db8b97c2c1823bfaddaa281153adb09d0f1736dfc96d61eb62ee7053bbc42d8228110b33e1ea83897835187fb81a3963834aeca3043da69ececcd5175249c",
          "sha256": "3196532da1dd07866a99e2c212a33ad40b09e5a710655ebf4b0e10fbedc08647",
          "sha1": "9ee44b904dc893fc223b4b10446fa95b443bd931",
          "md5": "a58f9015b53acc13d33a83bf3c36b670"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.2-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2516.2-sources.jar",
          "size": 585759,
          "sha512": "3e5eff7905b67f211f1ea0118e34204de457845f334a05174a1a276fc17e6542e16575d38beec4d0598caec8adc494b4e4823e02d64558bdae4bae6964ee491d",
          "sha256": "8f2e271d519d0e21511d34c908a69b00fba7d2995b6590b0adedf1cc1258ac7f",
          "sha1": "80f63ffe2a3caf0fa75cc6b02568b15255633d31",
          "md5": "1bc87e02a26974e8c1cdd75737a020f7"
        }
      ]
    }
  ]
}
