{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.0.jar",
          "size": 506431,
          "sha512": "d01404466cb142ee0bce47515d24dd3e536279d2e7e3fc03ecb951d637769de84bc083c345102d3f2397aa40e3489e10e993ffa0500650234d4050a80e408e0d",
          "sha256": "e9975b98a4c196ffe37fa14c1999cbc0dccaae42f65edf0911b142c95ece600b",
          "sha1": "ad7d53863bbfaa5c05a3090c9819371730b12880",
          "md5": "7c52bdffbf8b0f90e56bdc55ed37cfad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.0.jar",
          "size": 506431,
          "sha512": "d01404466cb142ee0bce47515d24dd3e536279d2e7e3fc03ecb951d637769de84bc083c345102d3f2397aa40e3489e10e993ffa0500650234d4050a80e408e0d",
          "sha256": "e9975b98a4c196ffe37fa14c1999cbc0dccaae42f65edf0911b142c95ece600b",
          "sha1": "ad7d53863bbfaa5c05a3090c9819371730b12880",
          "md5": "7c52bdffbf8b0f90e56bdc55ed37cfad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.0-sources.jar",
          "size": 253313,
          "sha512": "3fb278c07ce9060bfd9cdb3065952a5c9dcae3b26eb734ef85069142dc690c2c3358ab17d4f8976d71ae05d9b53ad508ac1ca27f65e690edf3d16fdbe3ab6b27",
          "sha256": "f3bfb27af3026c7da7500418b2898936ced7d0fc601b7f4092b3ef29a6e91620",
          "sha1": "33b7002fa7ad07c4e5243147c76e71884b004abd",
          "md5": "961b9a571d064f74a696cb0093e7c2da"
        }
      ]
    }
  ]
}
