{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2507.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.12.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.12.jar",
          "size": 498503,
          "sha512": "2cd8ff38bda40d32cdc619c00d50215747e4ce5903311047a38892905bc1295b43c23f8a25f0a6165a5148db5d3c95ec4c681446d2c32b19492bb685d6a131a7",
          "sha256": "df27e252b24e9a2282cb2d399297f092ef1998b5a4ddaddbf967ca18d63616ab",
          "sha1": "e751d267b03a39dcf44577fe1d2ceba65cb9ca89",
          "md5": "95b471c026d3122a86bdc372f8600395"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.12.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.12.jar",
          "size": 498503,
          "sha512": "2cd8ff38bda40d32cdc619c00d50215747e4ce5903311047a38892905bc1295b43c23f8a25f0a6165a5148db5d3c95ec4c681446d2c32b19492bb685d6a131a7",
          "sha256": "df27e252b24e9a2282cb2d399297f092ef1998b5a4ddaddbf967ca18d63616ab",
          "sha1": "e751d267b03a39dcf44577fe1d2ceba65cb9ca89",
          "md5": "95b471c026d3122a86bdc372f8600395"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.12-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.12-sources.jar",
          "size": 244744,
          "sha512": "2c35838a96624df19706732f0cd91dd3ab34c08c6687b2a0cd47871086a890fa6f10a6897670dc509361a324ae3343c0994e3ab923791bc06a8a27b3547812ba",
          "sha256": "2121e3c5dfbca2336819bccfedc4e843d509b61732f3b896391160aff656da46",
          "sha1": "b88e37518b5e562dbeb56b6e04d585375e8337f5",
          "md5": "18f5aeb55b977d9bb8ea79837f329aad"
        }
      ]
    }
  ]
}
