{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.13.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.13.jar",
          "size": 382910,
          "sha512": "aaaf62b8ac5cd3548a66329c5841b56312d9c9c23ef6e5288230f14439bf2c050aab13f1ed4575a43ec06e78036d080370c2c0b9a673dd9e3d0375cd618ce4a0",
          "sha256": "fdc54371ff19042715b37cf00c2fb1f106628717aaaf3e08dcc2214881b8cce7",
          "sha1": "ed54b58e052caf1a7ba9d5d78f66cc844664591c",
          "md5": "3c2f7f5bb66720ae0d04803b7ec51a1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.13.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.13.jar",
          "size": 382910,
          "sha512": "aaaf62b8ac5cd3548a66329c5841b56312d9c9c23ef6e5288230f14439bf2c050aab13f1ed4575a43ec06e78036d080370c2c0b9a673dd9e3d0375cd618ce4a0",
          "sha256": "fdc54371ff19042715b37cf00c2fb1f106628717aaaf3e08dcc2214881b8cce7",
          "sha1": "ed54b58e052caf1a7ba9d5d78f66cc844664591c",
          "md5": "3c2f7f5bb66720ae0d04803b7ec51a1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.13-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.13-sources.jar",
          "size": 199062,
          "sha512": "fc6dd88e4f856570167a1159fee650ba82e152963b336927575ae07737398f805e707fab084fb6c529db7a1bde89d3fd1098e78b12b2760120916e7b8bdc0f8e",
          "sha256": "68817c3866bd6b568533ddce08dcbb0f8e8c5d80c0fcf2dc2a8ff88fc0597e15",
          "sha1": "81742e4c561f3c60e7de971f4665c5ce8a39b38c",
          "md5": "a19ff6b567b290a1079ad116631309a3"
        }
      ]
    }
  ]
}
