{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.6.2545.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.6.2545.0.jar",
          "size": 550282,
          "sha512": "e3d2f3b39411637c35f20a78f1c6270a0b946d095ebd1bb716b72fc647e5dab0b2aa0b2012d8516bfddd839ba8d2d306f893ab16fc62adccbc511f05a62261df",
          "sha256": "4b380584f85581018a74b50f646eb77e28801f44f80807e60500695a2cc24a22",
          "sha1": "ecb1dcf402775d72ebcedceb1e0ca955862e7fb7",
          "md5": "1041bb3ecca54c40493bc0d6c86246f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.6.2545.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.6.2545.0.jar",
          "size": 550282,
          "sha512": "e3d2f3b39411637c35f20a78f1c6270a0b946d095ebd1bb716b72fc647e5dab0b2aa0b2012d8516bfddd839ba8d2d306f893ab16fc62adccbc511f05a62261df",
          "sha256": "4b380584f85581018a74b50f646eb77e28801f44f80807e60500695a2cc24a22",
          "sha1": "ecb1dcf402775d72ebcedceb1e0ca955862e7fb7",
          "md5": "1041bb3ecca54c40493bc0d6c86246f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.6.2545.0-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.6.2545.0-sources.jar",
          "size": 266310,
          "sha512": "f4b88693c51818fdb00988f272d64672a1a840d19d7e4e218f3ed07002251f2dd65c691e0cbc074814aef86550a4a7089f513efd6f72d52dacd24833369f8d58",
          "sha256": "4ef6656e9533113e43c2bd26094b10c30b934dcf3070bc71cfc44feec8722abe",
          "sha1": "1b943d0a5e72801dfe291e82ea14fe6995aa83ec",
          "md5": "937cb4fa2d33946471e5a67146ffb870"
        }
      ]
    }
  ]
}
