{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.9.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.9.jar",
          "size": 443828,
          "sha512": "c3ae3204f377c501de2becb2006a95c3bc329990fa4d44ab74f27c531ce596508452edd763050e232deb1b15aca9f07d319b2a439a5a353a3ce8a34ffeac0105",
          "sha256": "59f9dce4f70903d4a292597c1bc66dd9d4cce70d29b19d3fa32c3eceefb8b42a",
          "sha1": "1fd6d9fb52f381da69ac8f3767fbabb062d4384e",
          "md5": "98ee1fc14064ac948e03caf5f95646f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.9.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.9.jar",
          "size": 443828,
          "sha512": "c3ae3204f377c501de2becb2006a95c3bc329990fa4d44ab74f27c531ce596508452edd763050e232deb1b15aca9f07d319b2a439a5a353a3ce8a34ffeac0105",
          "sha256": "59f9dce4f70903d4a292597c1bc66dd9d4cce70d29b19d3fa32c3eceefb8b42a",
          "sha1": "1fd6d9fb52f381da69ac8f3767fbabb062d4384e",
          "md5": "98ee1fc14064ac948e03caf5f95646f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.9-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.9-sources.jar",
          "size": 229855,
          "sha512": "d801a1464bf15e890f19ae6256d9c4fea0c8d2c6133c3148b6d8cc82f739aa1935b0895d73a0ccb305565d41172827e4fa869a1f7fb8c1b8f4fccb5a08d93db6",
          "sha256": "5193f21946a81a5d005c5d6d36056b8708c4ab45b04b0002a3986089aaf5da23",
          "sha1": "5af84cabc50b50e94fd705c26dff8f61573a6ab5",
          "md5": "f96143e579fc8b033afb8b85aca683c1"
        }
      ]
    }
  ]
}
