{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.4-1.8.0.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3.2516.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2516.3.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2516.3.jar",
          "size": 18254608,
          "sha512": "d422ce7cdecfdb223f0f0977ad37adaf5e59a797bdc41c97a2ad1ce2f22f38dcbece837f8257288c56a25c62434336aa0914e1a73b70f852953a1d135f3f22fb",
          "sha256": "a22b84455bba620beec1759d3c2ce005862c647e6d9a6f6af7a5ea5c0e9226bb",
          "sha1": "a81f16ef3e261795e7114effa852d51d0ed88acf",
          "md5": "9fe887c389006b542d7313086e857f9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3.2516.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2516.3.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2516.3.jar",
          "size": 18254608,
          "sha512": "d422ce7cdecfdb223f0f0977ad37adaf5e59a797bdc41c97a2ad1ce2f22f38dcbece837f8257288c56a25c62434336aa0914e1a73b70f852953a1d135f3f22fb",
          "sha256": "a22b84455bba620beec1759d3c2ce005862c647e6d9a6f6af7a5ea5c0e9226bb",
          "sha1": "a81f16ef3e261795e7114effa852d51d0ed88acf",
          "md5": "9fe887c389006b542d7313086e857f9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2516.3-sources.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2516.3-sources.jar",
          "size": 17412241,
          "sha512": "1497895e6d6dbc0793aa3e013dbf8305b20af3429662cea3dffaf30c623535b382036248a4344bef4dc8af79950fd292857975e1e8e0d0faf3a80c5dd0fa8b54",
          "sha256": "f48eb833fc6da50d22335325f59cca3b576da68a1ec7953c9c1586194435d3bf",
          "sha1": "5409f9b47b4911a750a9232dac02ff9a6b707008",
          "md5": "05acbc6c0ef62b3bf0439b7c970587d0"
        }
      ]
    }
  ]
}
