{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2500.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.3.jar",
          "size": 345930,
          "sha512": "32c06c64144bc5107047f0014965c19c96cd6551304633abcdb7610fabf7f8207494e150545ad29c47226ad3769e86653977d1895cb73d85e724367cc70b5c8e",
          "sha256": "81dcd1918781b93e979c400997c8b886f222bd0c46461d834b8ede29ef8f7492",
          "sha1": "825dfc6f87bd87cd520d0dc42b4fcbe5ce01f722",
          "md5": "73563259c8f99300ba4cc822d3bfbc1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.3.jar",
          "size": 345930,
          "sha512": "32c06c64144bc5107047f0014965c19c96cd6551304633abcdb7610fabf7f8207494e150545ad29c47226ad3769e86653977d1895cb73d85e724367cc70b5c8e",
          "sha256": "81dcd1918781b93e979c400997c8b886f222bd0c46461d834b8ede29ef8f7492",
          "sha1": "825dfc6f87bd87cd520d0dc42b4fcbe5ce01f722",
          "md5": "73563259c8f99300ba4cc822d3bfbc1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.3-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.3-sources.jar",
          "size": 193435,
          "sha512": "a16b59af779d1bd2a985637603c3c54552429bcddda1622ca8c8edd75c6ac3082f11a9c15751395a78efaeccf9511849bc256cc796509aa2cb2587ee1696f735",
          "sha256": "060cee4be7ffbfbb960a41e6cad8d8dd784619f5b5161b82dbc79b6548f186c5",
          "sha1": "c473b7100f7e73cafedd89dc05eeeab6398e5b32",
          "md5": "a3e16df2447e055ce3f588f3cd4bb967"
        }
      ]
    }
  ]
}
