{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2513.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.2.jar",
          "size": 697817,
          "sha512": "cf2eebbdb835e84188ad624436286033e466a1bfcacd33ab36329d1c3cdcbdc380bc67a00b0b4dc0e043102e22d4ebff7f32f7f7227de3436f2a9da41e099d56",
          "sha256": "18fd5ee5160e8dc90320c81e523cc6e26c4121bef8e699f2e26c6c307820769f",
          "sha1": "83ad0c4e18370154d75bbe7d5fcb724d8836206a",
          "md5": "861cbc5bd9dd1871de82c185962bcefa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.2.jar",
          "size": 697817,
          "sha512": "cf2eebbdb835e84188ad624436286033e466a1bfcacd33ab36329d1c3cdcbdc380bc67a00b0b4dc0e043102e22d4ebff7f32f7f7227de3436f2a9da41e099d56",
          "sha256": "18fd5ee5160e8dc90320c81e523cc6e26c4121bef8e699f2e26c6c307820769f",
          "sha1": "83ad0c4e18370154d75bbe7d5fcb724d8836206a",
          "md5": "861cbc5bd9dd1871de82c185962bcefa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.2-sources.jar",
          "size": 250715,
          "sha512": "7b9011ca6322fef74349d9a139f3a1da40a218eb6ff41def735c7b3699bf3c82ea7b27770c18a0d4393317a8ad31ac644c69243060ebde16a21e9ba0ee24bab5",
          "sha256": "5bba884700c751cb94034f25e98b65c1958b8cbc0723363585011291bdcb7fc5",
          "sha1": "78ac497e03a9168d947eb50309d6d96eda6f0886",
          "md5": "171ab5d8e5707869cb658177438b5402"
        }
      ]
    }
  ]
}
