{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2507.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2507.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2507.7.jar",
          "size": 478502,
          "sha512": "18438261fa7331b8f1168fa6c6caeff050d542b8fce22ffc0b2933def0a04bed398eb2a7cfadfa32036313eab57b9eed253d4b6b4e6b619aeea1659f2353e3b4",
          "sha256": "ee7a15016b5e058c5095ffb48cc2589c5e72d04d03916a77fb13f7504320d09f",
          "sha1": "005591e15e87af2df60f52652d89fa92ccdbd5d3",
          "md5": "58f5ac241b1654ed8f47905066e147b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2507.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2507.7.jar",
          "size": 478502,
          "sha512": "18438261fa7331b8f1168fa6c6caeff050d542b8fce22ffc0b2933def0a04bed398eb2a7cfadfa32036313eab57b9eed253d4b6b4e6b619aeea1659f2353e3b4",
          "sha256": "ee7a15016b5e058c5095ffb48cc2589c5e72d04d03916a77fb13f7504320d09f",
          "sha1": "005591e15e87af2df60f52652d89fa92ccdbd5d3",
          "md5": "58f5ac241b1654ed8f47905066e147b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2507.7-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2507.7-sources.jar",
          "size": 244549,
          "sha512": "e73047526166acfceefb159e099342a5438034d90b843f489c8792a9813ce21625122510b39aa8c43e73accff735df8757b3ea457c13829de6b2a7a9e707483d",
          "sha256": "cd4fa6d195f877fe7d841eff317571f68a58ba334de42864d25481add2de12d0",
          "sha1": "be46dcc95a140e0cfa847086df7392d41d4f78ac",
          "md5": "3323d508e096a7cee024f5345234575c"
        }
      ]
    }
  ]
}
