{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2517.0.jar",
          "size": 513461,
          "sha512": "3c05ce8d7555e481ddccbc868dd3e40cdd6385e1c0f5337e05c8746765f11188d8fbd3cd0adad430ad11109e51d8e0838844e4d8fca6adc04ef3d580111bdb7a",
          "sha256": "86aa0ca74c7e8796f075dd8aa83319101277b26e6e6e2faa399e1a1c7b89905c",
          "sha1": "917ef915be173afeb1a2e104844ae2321d69aa84",
          "md5": "b3e5ef8f1061535fc726ca784b9a5327"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2517.0.jar",
          "size": 513461,
          "sha512": "3c05ce8d7555e481ddccbc868dd3e40cdd6385e1c0f5337e05c8746765f11188d8fbd3cd0adad430ad11109e51d8e0838844e4d8fca6adc04ef3d580111bdb7a",
          "sha256": "86aa0ca74c7e8796f075dd8aa83319101277b26e6e6e2faa399e1a1c7b89905c",
          "sha1": "917ef915be173afeb1a2e104844ae2321d69aa84",
          "md5": "b3e5ef8f1061535fc726ca784b9a5327"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2517.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2517.0-sources.jar",
          "size": 254109,
          "sha512": "f844139f949f5eac34732f8c3f0ebef17ba62eccd69626a7dbb2033585d377ee4e982768ea94b22339428c8005fb0ed5907cbb71330783b14d4d2708374c7a46",
          "sha256": "511bb14b0b666ceaa01817138f54098200bb88afa08ae0ad9220009ab81b8b2a",
          "sha1": "6756933e6f19433eef5d1b95370966484496634d",
          "md5": "2c34f33ee47a05d6ac46a006f1265530"
        }
      ]
    }
  ]
}
