{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.24.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.24.jar",
          "size": 394007,
          "sha512": "a1edf4ead7eb87925e83a2891257868fedef998c4aa0a18d19420f4f2cf8c20d3841e765f17525f09dbc6935b5ea4d1ceaec650225941f8ceabf7dc9288b5da4",
          "sha256": "58277c60eaa8ea2fa20fe01534f643649fc36335d78b7f936a7336ec1b79029e",
          "sha1": "8a1f8e1325f3b70ad0b62c4484ae203e8de07c9b",
          "md5": "02bb12cb92843ddd9858b564de66d30c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.24.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.24.jar",
          "size": 394007,
          "sha512": "a1edf4ead7eb87925e83a2891257868fedef998c4aa0a18d19420f4f2cf8c20d3841e765f17525f09dbc6935b5ea4d1ceaec650225941f8ceabf7dc9288b5da4",
          "sha256": "58277c60eaa8ea2fa20fe01534f643649fc36335d78b7f936a7336ec1b79029e",
          "sha1": "8a1f8e1325f3b70ad0b62c4484ae203e8de07c9b",
          "md5": "02bb12cb92843ddd9858b564de66d30c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.24-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.24-sources.jar",
          "size": 197680,
          "sha512": "f9eb20cf4019e513a13bce88893e86746f4cd06e467f477be0fd497cc83373a825e311a9fc628166e3096fef9d5401ca979d32defbab0d7dbcae779d194bc61c",
          "sha256": "a52473e77591fa666a7da00bada2130cdaa5541c7bb409bb49607e0f9e8217ff",
          "sha1": "860fe839b1d194e01c828edd42989fedb3ad8dab",
          "md5": "4c5570cefa3337ae0aed84ff97639c1a"
        }
      ]
    }
  ]
}
