{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2501.24.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2501.24.jar",
          "size": 423314,
          "sha512": "2d2c0988694d1adaa9c3e2346c03f74b2d7d252d7a32f362313fb3c9b4fe0c0ff86eff0fca1f45a667541152f4fed7ee3cbd6856074c1a26a1fd6d22e1286ecd",
          "sha256": "e93820979c7147ee13fdb93802339f06e354ba05a2acb1b6e7a61aa9f35790a8",
          "sha1": "0638da8829007c80e076c7f126df97f464011b28",
          "md5": "cda264383258dd6ad7f9490031a20731"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2501.24.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2501.24.jar",
          "size": 423314,
          "sha512": "2d2c0988694d1adaa9c3e2346c03f74b2d7d252d7a32f362313fb3c9b4fe0c0ff86eff0fca1f45a667541152f4fed7ee3cbd6856074c1a26a1fd6d22e1286ecd",
          "sha256": "e93820979c7147ee13fdb93802339f06e354ba05a2acb1b6e7a61aa9f35790a8",
          "sha1": "0638da8829007c80e076c7f126df97f464011b28",
          "md5": "cda264383258dd6ad7f9490031a20731"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2501.24-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2501.24-sources.jar",
          "size": 196574,
          "sha512": "c952b0864bb5318f1e0f9286ff625546ae859807be466612ae8e53ab99330113d4c825d361dc7d080285c5d18333e27a057044158f75cb2d83fa40e3c4b3f03a",
          "sha256": "eba6c841fa30576f6fa29dbc30e4df59511ab1cade0d40adae3aa1e5e39c0b28",
          "sha1": "c870fa3ac849ab8a5e9e5ce43849d5836227df7f",
          "md5": "8bdbfacc5c569faf34a303f5cc5670b1"
        }
      ]
    }
  ]
}
