{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.10.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.10.jar",
          "size": 481541,
          "sha512": "d3b9a7b258ee597ac62823fa5c4edd7c9fee8556b3a0c09be7064f45bc30667b940ad0cbf3e460c16206b71582e817e64882fb2ec38fa288d648bb3a76db2ca7",
          "sha256": "7eab1f68547ae6ff85dda9ca3239f2376bed79d1e7afd42b1782ef5d3aec41f5",
          "sha1": "1f1d752f88deb2b650ef1847f76952c26555e896",
          "md5": "e96bf1c579b02c6be4ca2e0fb229887c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.10.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.10.jar",
          "size": 481541,
          "sha512": "d3b9a7b258ee597ac62823fa5c4edd7c9fee8556b3a0c09be7064f45bc30667b940ad0cbf3e460c16206b71582e817e64882fb2ec38fa288d648bb3a76db2ca7",
          "sha256": "7eab1f68547ae6ff85dda9ca3239f2376bed79d1e7afd42b1782ef5d3aec41f5",
          "sha1": "1f1d752f88deb2b650ef1847f76952c26555e896",
          "md5": "e96bf1c579b02c6be4ca2e0fb229887c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.10-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.10-sources.jar",
          "size": 246430,
          "sha512": "40e6b3f1b5b33732bd981180e2acb6fcdd71fda3f0baf658257b0f694ec542f1afd5b5bafb0d91466548a1b7405cbea7d17eb51dbc828cd0facd1e0fae6e1203",
          "sha256": "0e137c13b2dfa4bfca3e293b312aadcb250eac574d0803de2d85a3db454c1d14",
          "sha1": "bfe27e844be5bcc4e64a1f79131d0c83fa21d629",
          "md5": "c463eeddc9c878335290ab25dfff1ba7"
        }
      ]
    }
  ]
}
