{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.15.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.15.jar",
          "size": 450971,
          "sha512": "e35b7618b71bd62cdd3739260f20cd9f52e409f453a636d723f7dd8e99f8669cb300a6ceeb720b8225943dd450be3ea84b0d7988cfae1fe2d96b1a336cae5feb",
          "sha256": "1dff3a1152c4194fd052f70e977527d6dd78742c7207ef6c6b78fe259103c98c",
          "sha1": "44cf4163e7d4aef4a55e90917b614bf96c4bbcea",
          "md5": "dcaf72b8e5d88e5813963191b1727ca2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.15.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.15.jar",
          "size": 450971,
          "sha512": "e35b7618b71bd62cdd3739260f20cd9f52e409f453a636d723f7dd8e99f8669cb300a6ceeb720b8225943dd450be3ea84b0d7988cfae1fe2d96b1a336cae5feb",
          "sha256": "1dff3a1152c4194fd052f70e977527d6dd78742c7207ef6c6b78fe259103c98c",
          "sha1": "44cf4163e7d4aef4a55e90917b614bf96c4bbcea",
          "md5": "dcaf72b8e5d88e5813963191b1727ca2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.15-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.15-sources.jar",
          "size": 233656,
          "sha512": "75094b9ea5e8d9bd14c6a00123b219a421967800bb926a7e4b0f77791b92cd8433c5a3017e3d688331f310d36ea0a8d669777d8e3a989c0db06a1caae025b9f2",
          "sha256": "71bf1b400bcd6690062e9122ec01c247a5bd262846c0fcefe94b379158b8dd03",
          "sha1": "058036517899f1c0d66f9ebaad136c0a5d8f32c8",
          "md5": "e811b0502725e6b31a3e2cc27757c2ac"
        }
      ]
    }
  ]
}
