{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.6.2541.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2541.2.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2541.2.jar",
          "size": 535596,
          "sha512": "ca01b49dc1bff526182575a0a40dcfa35854483cca61dd5f15f7b1e56f9ab695521f5fe091752672d9930222fd3e508a337bbebdc3e62263038bfe7b3efc84ce",
          "sha256": "50ab2bd79d1b286e9f470d9af0742f5535eed4a8f0e5c1b091720ce4c3620b8e",
          "sha1": "9c3d4a4bfa3d5d39b89aa8f7e2087a6e050ee6e0",
          "md5": "cb0c9b70b8b51e139569d44766e80150"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2541.2.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2541.2.jar",
          "size": 535596,
          "sha512": "ca01b49dc1bff526182575a0a40dcfa35854483cca61dd5f15f7b1e56f9ab695521f5fe091752672d9930222fd3e508a337bbebdc3e62263038bfe7b3efc84ce",
          "sha256": "50ab2bd79d1b286e9f470d9af0742f5535eed4a8f0e5c1b091720ce4c3620b8e",
          "sha1": "9c3d4a4bfa3d5d39b89aa8f7e2087a6e050ee6e0",
          "md5": "cb0c9b70b8b51e139569d44766e80150"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2541.2-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2541.2-sources.jar",
          "size": 267910,
          "sha512": "87977a92e9c61f0eed7e4c37de360a721c9e68966d0d7af72bfec4f7fadd422e63a449fed867a090c88bc6af06b559bcbeb56aa5d133e8b8e283155025b21791",
          "sha256": "cbce21a7bd4ea18d4e8850707acdd3a12a5398f211a2e369a34818a2b166616b",
          "sha1": "578f6a07e5274eba3482e383d913b43c5ef057cb",
          "md5": "b3e8e676453f956758783867241c6e4e"
        }
      ]
    }
  ]
}
