{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2501.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "size": 380447,
          "sha512": "0653e3f5c741526455924276cd9cd6b069c668d2c2f0e374871b4f28e015371d506f10df3c76549c4f47091a675d0afb247a05a7ccd82f061bed55366446b8d5",
          "sha256": "e61e79073abcee3188b2068c3d602891f2a630cc43a257078c084114bee3dc7e",
          "sha1": "6a750409fe10cb713b5f07864e706c88a3e305e2",
          "md5": "c54a3e667c778751aaa55ae5dce5dba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "size": 380447,
          "sha512": "0653e3f5c741526455924276cd9cd6b069c668d2c2f0e374871b4f28e015371d506f10df3c76549c4f47091a675d0afb247a05a7ccd82f061bed55366446b8d5",
          "sha256": "e61e79073abcee3188b2068c3d602891f2a630cc43a257078c084114bee3dc7e",
          "sha1": "6a750409fe10cb713b5f07864e706c88a3e305e2",
          "md5": "c54a3e667c778751aaa55ae5dce5dba9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.22-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.22-sources.jar",
          "size": 202809,
          "sha512": "64b5ad56be29239eaa759fc4e41a0027910e28da3b529e08cf619a3609ed5929586917f2166670cd4818eae6cf7061114e32703c1682dcabfae79d0b76639074",
          "sha256": "a93b3b232913b99d9216314eb3d97df525ffa791bbef018995d0f415f79b6f53",
          "sha1": "e59830ed37671d3e7c8e9096236d4d00fd9b5703",
          "md5": "85a0203d28534dfc7fe321492faabd64"
        }
      ]
    }
  ]
}
