{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2501.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "size": 380447,
          "sha512": "0653e3f5c741526455924276cd9cd6b069c668d2c2f0e374871b4f28e015371d506f10df3c76549c4f47091a675d0afb247a05a7ccd82f061bed55366446b8d5",
          "sha256": "e61e79073abcee3188b2068c3d602891f2a630cc43a257078c084114bee3dc7e",
          "sha1": "6a750409fe10cb713b5f07864e706c88a3e305e2",
          "md5": "c54a3e667c778751aaa55ae5dce5dba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.22.jar",
          "size": 380447,
          "sha512": "0653e3f5c741526455924276cd9cd6b069c668d2c2f0e374871b4f28e015371d506f10df3c76549c4f47091a675d0afb247a05a7ccd82f061bed55366446b8d5",
          "sha256": "e61e79073abcee3188b2068c3d602891f2a630cc43a257078c084114bee3dc7e",
          "sha1": "6a750409fe10cb713b5f07864e706c88a3e305e2",
          "md5": "c54a3e667c778751aaa55ae5dce5dba9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.22-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.22-sources.jar",
          "size": 202814,
          "sha512": "e4e5cd11d6d6f93cd69d329bc7d202843bbc104f70b16794aece48d3d2e84ff07701de15d48ba5151549a1985024f840e3e10ef5fedfc65695e51934ea4ba292",
          "sha256": "aea5326f4a37e963c576cd18fd7f6e7111b0e8f2349e9fcf48a716d132f998dc",
          "sha1": "4950f50b918269a0b11c842e319eff72d4716a55",
          "md5": "af7778a1b6285a956335ae8ef3ab2e7b"
        }
      ]
    }
  ]
}
