{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2507.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.13.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.13.jar",
          "size": 495932,
          "sha512": "b2d908ae3b120f6d9eb00fea8e2847b30843955a755e8e6e553e5d578c9a2e5c02f1ac455557a5aac93d9e4f619497424f68567aa5c82d5c0fd64989c088ca92",
          "sha256": "ff8c1426df1c130731769c4aa40f50a78d368cc1b496d24ed65356bb7e638bbe",
          "sha1": "d82817c7a3c22cced0a1ea3390356c85dd676bda",
          "md5": "4cff4fc57e5813793d34c43e8febd748"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.13.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.13.jar",
          "size": 495932,
          "sha512": "b2d908ae3b120f6d9eb00fea8e2847b30843955a755e8e6e553e5d578c9a2e5c02f1ac455557a5aac93d9e4f619497424f68567aa5c82d5c0fd64989c088ca92",
          "sha256": "ff8c1426df1c130731769c4aa40f50a78d368cc1b496d24ed65356bb7e638bbe",
          "sha1": "d82817c7a3c22cced0a1ea3390356c85dd676bda",
          "md5": "4cff4fc57e5813793d34c43e8febd748"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.13-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.13-sources.jar",
          "size": 244682,
          "sha512": "331ebd2758686cab5f6b924dcd8c39dd0a8d87617784cc70a427b3bebbc8cc6471df01632085d312f619843b8ecc614420e2cb11937b9a25afd73f7ced102436",
          "sha256": "da8f18b6a60564fb76b72dfa04dfe35e6b437247a7811c66935ab4c41f410ba7",
          "sha1": "e6c3e35cdb7b5a43b795622e9dd706359b14ad98",
          "md5": "65f9e94b5407b386ac9b8d818024fba1"
        }
      ]
    }
  ]
}
