{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2502.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.2.jar",
          "size": 382372,
          "sha512": "54705874313a5bd1d5c092a0710e87c8cdac167f9e42dedbd3469fb2a03ac152161bdf18876a1cde66dcf72a0ebf0a1de936fef5713ee1ec0b9b42d68b4350b5",
          "sha256": "8df3500b8f951e7392a893cdd27f8d4c977493dc10e080ca4e4441b867f7ecf7",
          "sha1": "dc4dd5f28c59c6d7f2d04a6d9aa8f351eb375946",
          "md5": "22008b1f7830f23e99d923f7f000c7b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.2.jar",
          "size": 382372,
          "sha512": "54705874313a5bd1d5c092a0710e87c8cdac167f9e42dedbd3469fb2a03ac152161bdf18876a1cde66dcf72a0ebf0a1de936fef5713ee1ec0b9b42d68b4350b5",
          "sha256": "8df3500b8f951e7392a893cdd27f8d4c977493dc10e080ca4e4441b867f7ecf7",
          "sha1": "dc4dd5f28c59c6d7f2d04a6d9aa8f351eb375946",
          "md5": "22008b1f7830f23e99d923f7f000c7b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.2-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.2-sources.jar",
          "size": 198128,
          "sha512": "18facf72102624a6229fdd4fbe6d082b4d349074522230fe21808de04001b0d75f4a5f4b277d92d02c74ce9ed54f5a48ac939869deeca7c89687dc06c455e044",
          "sha256": "0300390660d9297a05107960967fa7a055199099eee0d3aa6752af3a715cff9f",
          "sha1": "98570e7cfac6c277f78694b72fdd15ce6479bf7d",
          "md5": "1a1b32a98d62dc47c4d136137b87494c"
        }
      ]
    }
  ]
}
