{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2513.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.7.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.7.jar",
          "size": 711018,
          "sha512": "3713362c83afdccbbc8b603a2c46f87ae551482c45e6ca8d23820ce2ad74f7e3a99b8d4e67d3be9129996f7f19aa289cb8e224c6873fa89b9785cc59b93ea689",
          "sha256": "0e084431ad6a28948c256a197aa6353f0c37fa344906f300f56713f75eb85221",
          "sha1": "fa36a6da988d19130164858366a0d62ffef03d78",
          "md5": "5f46aa4994d709391219851ea0a3d984"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.7.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.7.jar",
          "size": 711018,
          "sha512": "3713362c83afdccbbc8b603a2c46f87ae551482c45e6ca8d23820ce2ad74f7e3a99b8d4e67d3be9129996f7f19aa289cb8e224c6873fa89b9785cc59b93ea689",
          "sha256": "0e084431ad6a28948c256a197aa6353f0c37fa344906f300f56713f75eb85221",
          "sha1": "fa36a6da988d19130164858366a0d62ffef03d78",
          "md5": "5f46aa4994d709391219851ea0a3d984"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.7-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.7-sources.jar",
          "size": 253456,
          "sha512": "7d9b68df74a82f1fec30690ecaa55c453b523273407620b48f86ac37ce44b9b1a5e36db85abed1e02080534eca4ed2e303302381b8416246ca2c01099091a2db",
          "sha256": "0f498874b5164519062316fdca0f3ea0f9eaf7dfdd37c9c75e75c6f33529f317",
          "sha1": "cb1d22a8e3256d753f391fa2f505dd490d38bed4",
          "md5": "b5584c6ee85619e7242382886a21094c"
        }
      ]
    }
  ]
}
