{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.8-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.21.8-2.2.6.2545.0.jar",
          "size": 726204,
          "sha512": "71fe2224c3e89669a26fe9c39dc21bb2208034f6fe3375e7ab08e90bbb1b7f79dc5572ea8c79f994cdaf10ec9c11a75712f696392b00d1674491670f1ee9c6ec",
          "sha256": "9cb93f59f5cf7a1836cf3b2134c78e33c18349feac24ef5f73e2b77675fc28c7",
          "sha1": "2e9da3ca1ca9f233f4ca6b2795f7e7ee00b919d3",
          "md5": "53be6f653dd4b7311b096595951eb141"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.8-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.21.8-2.2.6.2545.0.jar",
          "size": 726204,
          "sha512": "71fe2224c3e89669a26fe9c39dc21bb2208034f6fe3375e7ab08e90bbb1b7f79dc5572ea8c79f994cdaf10ec9c11a75712f696392b00d1674491670f1ee9c6ec",
          "sha256": "9cb93f59f5cf7a1836cf3b2134c78e33c18349feac24ef5f73e2b77675fc28c7",
          "sha1": "2e9da3ca1ca9f233f4ca6b2795f7e7ee00b919d3",
          "md5": "53be6f653dd4b7311b096595951eb141"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.8-2.2.6.2545.0-sources.jar",
          "url": "factory_api-forge-1.21.8-2.2.6.2545.0-sources.jar",
          "size": 268523,
          "sha512": "ab74477f75d8b8ee9faf13fcc0f5e5ab941ee76d1308fd9b04d60cd57badbfdb6b1c74aaf2a899ce2723b6b4223cc4b27836af29bfab53524b1ff310a0b178b7",
          "sha256": "f8fe03ee50ac2e99a4bdb9081312a16d0b5a5576302446cf313807a84da1c260",
          "sha1": "006fd03033b93807a20ea33f94cd53e383063eb5",
          "md5": "aedc23e0923a662817ff3d5767d8075c"
        }
      ]
    }
  ]
}
