{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.7.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.7.jar",
          "size": 481388,
          "sha512": "d6a0d3bd5595915f21fa2df0f395f0e36ed05a913ea1d49e017ddcedb1dc697ab643479458b11a023461fc0799da129eca32edc1f772de11e8f1af8c3adbab39",
          "sha256": "b1f182cb86593319fc146c1de86dca64183c316ec172ab15ee5fa3664f6157f5",
          "sha1": "3f1346a89078a1749b95be6a84184435d201d134",
          "md5": "d0f7a2817059a0fdf89a50a2f328f268"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.7.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.7.jar",
          "size": 481388,
          "sha512": "d6a0d3bd5595915f21fa2df0f395f0e36ed05a913ea1d49e017ddcedb1dc697ab643479458b11a023461fc0799da129eca32edc1f772de11e8f1af8c3adbab39",
          "sha256": "b1f182cb86593319fc146c1de86dca64183c316ec172ab15ee5fa3664f6157f5",
          "sha1": "3f1346a89078a1749b95be6a84184435d201d134",
          "md5": "d0f7a2817059a0fdf89a50a2f328f268"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.7-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.7-sources.jar",
          "size": 246267,
          "sha512": "a3786f40e8cb3e4ace443fd1ad04e2324fb6683a2359c4378c66fb9650531d180bdf9c3b19bf39a8afb46c76f38948dfbe15f3ed2365c359d8f2050c1ae872fa",
          "sha256": "3769f93413a6a7a16b9136a72ebd8ab51d5e0c70d211bf7a2cf62e9e278d17c6",
          "sha1": "54cb6ea905a157a3d2e86cb2573fbd92aec7c81b",
          "md5": "f85877b4ab0da725e451b62656b085af"
        }
      ]
    }
  ]
}
