{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "size": 520553,
          "sha512": "c7a46f67efc8fdd40f8e70a9d6243a682be99d79df22f396657e131ef2466a9de0c5e9d4a90785c1e0308aa4841ca09be195a1037ea49cbbeb80790dd284016d",
          "sha256": "6146340dbcc0c3c9e9874f55e7f7b6b95bdfb7b78e10a5e8c6835f030450d026",
          "sha1": "c700b6250cfcbea2b87a0b72b3c202dde7077acf",
          "md5": "b1599554d0ec0d8270bd7d33175f1c39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "size": 520553,
          "sha512": "c7a46f67efc8fdd40f8e70a9d6243a682be99d79df22f396657e131ef2466a9de0c5e9d4a90785c1e0308aa4841ca09be195a1037ea49cbbeb80790dd284016d",
          "sha256": "6146340dbcc0c3c9e9874f55e7f7b6b95bdfb7b78e10a5e8c6835f030450d026",
          "sha1": "c700b6250cfcbea2b87a0b72b3c202dde7077acf",
          "md5": "b1599554d0ec0d8270bd7d33175f1c39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.2-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.2-sources.jar",
          "size": 75250,
          "sha512": "e2cd2d426dcd9d0aa61ca480341838ff7eaaa0a333699dcacc28b07f57dc0544633d17c76823130f2fe2fc2aae4fda546fff3c92b37badb4f5bf7caf51a85a02",
          "sha256": "696f6b52b73344b919c8fe687dcd08774b959fdf868a94405c80ad249ca9f05a",
          "sha1": "49c9d01be9be9e49f0cbc3af45d07a9e3ce5cf91",
          "md5": "80694f4f93676d6fcb43948a17d7bada"
        }
      ]
    }
  ]
}
