{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "size": 520672,
          "sha512": "3646950f0170fb2abe23abf74289bae735d309629e58a4614525078349277708e11c30b8e3325bfe0299f7bc47a94833fecc4edaf60f5bf699dd54cd3b267aee",
          "sha256": "35b8e1f43bbd03184f16a35f8ee08fbb686ea071a764747675c521bf1f879433",
          "sha1": "d79cb7961d044d298da7bc0a1e8919762f5558a8",
          "md5": "649768a82876e3a0d805068ef2b5cfb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.2.jar",
          "size": 520672,
          "sha512": "3646950f0170fb2abe23abf74289bae735d309629e58a4614525078349277708e11c30b8e3325bfe0299f7bc47a94833fecc4edaf60f5bf699dd54cd3b267aee",
          "sha256": "35b8e1f43bbd03184f16a35f8ee08fbb686ea071a764747675c521bf1f879433",
          "sha1": "d79cb7961d044d298da7bc0a1e8919762f5558a8",
          "md5": "649768a82876e3a0d805068ef2b5cfb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2514.2-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2514.2-sources.jar",
          "size": 252772,
          "sha512": "4c24449f4411d8431eb371ec0e79af1bc414d24564fdad572e1ed946e9e8402346b690b8d649613591ace876badffe869fa07fbf4a7a3dc9e8b7146cb6f08922",
          "sha256": "21e377e8b1384753684fd729509d8cd40a4f58c436f8c995353065d3cfb43537",
          "sha1": "ed7c6255cbb2ae953349ab6f0e0c43e42a4ab77b",
          "md5": "eded00f7cf0bfd2a6cecaf324b516a85"
        }
      ]
    }
  ]
}
