{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.8.0.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-forge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2516.2.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2516.2.jar",
          "size": 18286207,
          "sha512": "82d35a5bbf8ae817e0b8a868e7edb76941545b8098e8887fc31cf9d89bf19337b0203f255c34526972cc8ebe5b1706408e3aa6ea17ccbfd95a7d9f599a633ea0",
          "sha256": "85958adf5213c461c50d9f826fff3d4c990db5ce7a8e8b599ccae0a73f0ba167",
          "sha1": "ea2358482dea20eb40ffc39c914fb34a82cdbd89",
          "md5": "34fd5eb18ea942a3dce9716cfa8d73a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2516.2.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2516.2.jar",
          "size": 18286207,
          "sha512": "82d35a5bbf8ae817e0b8a868e7edb76941545b8098e8887fc31cf9d89bf19337b0203f255c34526972cc8ebe5b1706408e3aa6ea17ccbfd95a7d9f599a633ea0",
          "sha256": "85958adf5213c461c50d9f826fff3d4c990db5ce7a8e8b599ccae0a73f0ba167",
          "sha1": "ea2358482dea20eb40ffc39c914fb34a82cdbd89",
          "md5": "34fd5eb18ea942a3dce9716cfa8d73a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2516.2-sources.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2516.2-sources.jar",
          "size": 17439921,
          "sha512": "57a14bf80c30525fa71933c37034345180442ffb1822010659f0a67317da35f0cb28c1b1df9ce72a5340b2d9d0b2a2b3aa4852c532d3f4a5746fe8b713f911fd",
          "sha256": "8e6845573b958fc7e9d35140adc49b30df4772124005bfa312dac9a5ba1e1f06",
          "sha1": "cdcde45aabb8cd9e93ba47a3d80d9191ffeddc51",
          "md5": "47bdc2043ea0501bf06776e3a24b43f0"
        }
      ]
    }
  ]
}
