{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.7.10.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2504.1.jar",
          "size": 14230695,
          "sha512": "7af3b2be175496ad0e803401bc56293f5be6f6d30d2706b4c71dcee6c4e504444f2324f1ad51e227a737c3d21eb994cc20bf3ababad1484718c56fb2a5be0b90",
          "sha256": "5f23414db1ef840b4633bf0e8926eb83e0124bb96218b28719026006bda1c70d",
          "sha1": "6a0fe6049555a0c91cba5a5dafa0afdf534af68a",
          "md5": "dafcbc6db15ca248ca674346e750b1b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2504.1.jar",
          "size": 14230695,
          "sha512": "7af3b2be175496ad0e803401bc56293f5be6f6d30d2706b4c71dcee6c4e504444f2324f1ad51e227a737c3d21eb994cc20bf3ababad1484718c56fb2a5be0b90",
          "sha256": "5f23414db1ef840b4633bf0e8926eb83e0124bb96218b28719026006bda1c70d",
          "sha1": "6a0fe6049555a0c91cba5a5dafa0afdf534af68a",
          "md5": "dafcbc6db15ca248ca674346e750b1b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2504.1-sources.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2504.1-sources.jar",
          "size": 13447473,
          "sha512": "54a5dcf6341bce51aa46beedb89699937a5c820f3bf40237f0d11cee95d4ecf4dffb968b63f0bb9b0e18bfaf260e819c01a2f758dcf7994ab4c9a1d612928cec",
          "sha256": "cd76c87ac96938fbb67b2b889346169c984e07670957e5d9a28d9b730134ddc4",
          "sha1": "9710923a9cc7531570e6fa257df1deecde258772",
          "md5": "bba0639accf8efd1f0519f6d2392971b"
        }
      ]
    }
  ]
}
