{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.0.2518.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2518.0.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2518.0.jar",
          "size": 19758156,
          "sha512": "8b4e70493917c624f6e4b54f1feb83fcd7a7be2e18c81c61200611510ed49eed2a2ae7a80998ab942a9c2b943209dc1eca3b7466e4f76d13458dc3ec21b2e592",
          "sha256": "ff72a62526c32c57548ac7b4d7c17a5f0de17e826b4581c8e8f707b8940b2b90",
          "sha1": "75f0309288d4471566bd167357baabef31b77148",
          "md5": "c06849dcb9152669637bea2d99cd56b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2518.0.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2518.0.jar",
          "size": 19758156,
          "sha512": "8b4e70493917c624f6e4b54f1feb83fcd7a7be2e18c81c61200611510ed49eed2a2ae7a80998ab942a9c2b943209dc1eca3b7466e4f76d13458dc3ec21b2e592",
          "sha256": "ff72a62526c32c57548ac7b4d7c17a5f0de17e826b4581c8e8f707b8940b2b90",
          "sha1": "75f0309288d4471566bd167357baabef31b77148",
          "md5": "c06849dcb9152669637bea2d99cd56b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2518.0-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2518.0-sources.jar",
          "size": 18903055,
          "sha512": "bd5fba730f97e968c93916d269a47f2bdde7c2a0c0cc1a40eeb2880c5c1e4059f32002eaee9c08b56561806f36d6e9d9564cea52f8379e57c93284b66b4601bb",
          "sha256": "c41830bbc10b68755cabe202a1e567572e6733de898f27050df1dd772e3658fb",
          "sha1": "163c6b358db4d0fc09b6697150f65d88e4558782",
          "md5": "208bcb2e43d7bd830d06af805268c70c"
        }
      ]
    }
  ]
}
