{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2502.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2502.10.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2502.10.jar",
          "size": 487213,
          "sha512": "b384687b8825cf9cf4cf1df44f7ded5d4d5b10c8b07695fc2b6c0010451c2e61d31d5cd5d176da1fb22ce8e9322a3788157df9095e96b5db205632524a989186",
          "sha256": "508ac1975335c2af5eb92a63ae758b893b3651668314b2461d67fe8262406e7a",
          "sha1": "c38dc95ccb04d536881846e3c7f7d149d1415763",
          "md5": "ff62c720210677d003712489ff530d38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2502.10.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2502.10.jar",
          "size": 487213,
          "sha512": "b384687b8825cf9cf4cf1df44f7ded5d4d5b10c8b07695fc2b6c0010451c2e61d31d5cd5d176da1fb22ce8e9322a3788157df9095e96b5db205632524a989186",
          "sha256": "508ac1975335c2af5eb92a63ae758b893b3651668314b2461d67fe8262406e7a",
          "sha1": "c38dc95ccb04d536881846e3c7f7d149d1415763",
          "md5": "ff62c720210677d003712489ff530d38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2502.10-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2502.10-sources.jar",
          "size": 227157,
          "sha512": "a0f0a4d25304916e437e4448aacb6d9aaa24c832bc8498928f78dcf613098ce0f3a873883bfb0d72a8cad8c81b3fd2d2e298f0859e134c493531f00ecbc1e125",
          "sha256": "dba4b21c1e9ad4f0c58e7c9a4b8194bdeff99684068b0e7227307844c6d061ea",
          "sha1": "9e36b42cb748402be00cad746543be84e0c4e228",
          "md5": "da40d756c1ab6661cd756685521ef73b"
        }
      ]
    }
  ]
}
