{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2510.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2510.4.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2510.4.jar",
          "size": 699996,
          "sha512": "36b83a772b9bf350231a215032730095f2e61b402634c25f9bc4da53efe9da0eae50e5db84d7fedf432d5f44b44def193ab6625d1b385c89049add123f45f3d3",
          "sha256": "a0f4b6b0300f1e017739d3939a3b651b0e711c76b7e56b6c5f90bd6604eff17c",
          "sha1": "337b69ec9ca6bfae7569c81e3dcb3003d89b2d31",
          "md5": "3ac68fbcd3457bc85a565d0a5b8e463e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2510.4.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2510.4.jar",
          "size": 699996,
          "sha512": "36b83a772b9bf350231a215032730095f2e61b402634c25f9bc4da53efe9da0eae50e5db84d7fedf432d5f44b44def193ab6625d1b385c89049add123f45f3d3",
          "sha256": "a0f4b6b0300f1e017739d3939a3b651b0e711c76b7e56b6c5f90bd6604eff17c",
          "sha1": "337b69ec9ca6bfae7569c81e3dcb3003d89b2d31",
          "md5": "3ac68fbcd3457bc85a565d0a5b8e463e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2510.4-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2510.4-sources.jar",
          "size": 250761,
          "sha512": "d9888962bf3a57cbc9c993a80200ce09e6e9f8845a46342df96d20c68058c8e36d3fc64bccfa1abac0dfb580d0e61c8c2beaa198f4c68c72a6ec0015a851a0c3",
          "sha256": "ff39d60c27a1d1c011a8a825ed0e0d036cc0219981b0af5a0f3535c2bef14b39",
          "sha1": "c214fe464cd4bb869396bb19442f16d5893e2506",
          "md5": "d3310543c028fb310c6b62a2a0c61033"
        }
      ]
    }
  ]
}
