{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.2.jar",
          "url": "legacy-forge-1.21.5-1.8.2.jar",
          "size": 19737754,
          "sha512": "c23e5206cfd4b11640e4742725dd616ad9cc79469f74d6c93061236cbdd4fc5cc21fc0525a82a500df037ad9cdf44223750c741bf2882a767b1a47daa32657e8",
          "sha256": "46da143db66dd6bb4f12b3526eaa74a4da910b4196be2975dc20d2295bac296f",
          "sha1": "7f5c9a9a342bad12e43938634314a7064771cad6",
          "md5": "68a8573e2ac09a122e236f9cd91efd4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.2.jar",
          "url": "legacy-forge-1.21.5-1.8.2.jar",
          "size": 19737754,
          "sha512": "c23e5206cfd4b11640e4742725dd616ad9cc79469f74d6c93061236cbdd4fc5cc21fc0525a82a500df037ad9cdf44223750c741bf2882a767b1a47daa32657e8",
          "sha256": "46da143db66dd6bb4f12b3526eaa74a4da910b4196be2975dc20d2295bac296f",
          "sha1": "7f5c9a9a342bad12e43938634314a7064771cad6",
          "md5": "68a8573e2ac09a122e236f9cd91efd4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.2-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.2-sources.jar",
          "size": 18875186,
          "sha512": "25fb82a5a2edc4665c2d8e646ad93246c3723068a01e311e8a2b769c18617ac97a26605780194444961d487b21a11580c8b623db63b40a6dd1c8df35203fd768",
          "sha256": "11039802dd55c01e6f5e91bd66bf22df8c801f0ea8c6eeecc6975ba407ee2c43",
          "sha1": "a16ca6f15c837700d2d4c7faf35c1b46fe38d11b",
          "md5": "32da3b4d0585be01c2a5bb0118648b20"
        }
      ]
    }
  ]
}
