{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2502.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2502.13.jar",
          "url": "factory_api-forge-1.21.4-2.2.2502.13.jar",
          "size": 459091,
          "sha512": "1185d48c9ddc8e8922dda2145c1acc9bb19390c4e67f480dfb161ffeea5d2e745884125c605845883806f119d7fc9c5fd068ef3bb3297c9f0e3b856123a3d3b1",
          "sha256": "067db499d9a653627cf55934f5904761165c1e1d5f3a09d4d5335de5d12e3ae9",
          "sha1": "b017c5ae3fd38677c2c082ddcfe1700e2ceaeb60",
          "md5": "e3386ccd5cc1ac6ccca02141e49081cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2502.13.jar",
          "url": "factory_api-forge-1.21.4-2.2.2502.13.jar",
          "size": 459091,
          "sha512": "1185d48c9ddc8e8922dda2145c1acc9bb19390c4e67f480dfb161ffeea5d2e745884125c605845883806f119d7fc9c5fd068ef3bb3297c9f0e3b856123a3d3b1",
          "sha256": "067db499d9a653627cf55934f5904761165c1e1d5f3a09d4d5335de5d12e3ae9",
          "sha1": "b017c5ae3fd38677c2c082ddcfe1700e2ceaeb60",
          "md5": "e3386ccd5cc1ac6ccca02141e49081cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2502.13-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2502.13-sources.jar",
          "size": 228957,
          "sha512": "fd307b3d0e7ecb96bde1a5088a8a31a8389ace22ca8936c05c2caf0f32015302b36a6aaf8256feb26868dbacf1c0b6580d6d7a03da1de231e86102816b16b44f",
          "sha256": "fce486883886041d2e063e823e1f8bf0ec98fe545eba7c0498b70b02e5429ba4",
          "sha1": "413f6890006dd49450ec782f0f21474262efb3b9",
          "md5": "66b61643f565a08ee6bcb596d9b17b7f"
        }
      ]
    }
  ]
}
