{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.4.jar",
          "size": 442082,
          "sha512": "1cda432ba6e4a4fd69343c1410761a1b0c0054f085a23d9867f050b16741a918d5c44760673df0f3902d5cdca48fa0261943e478f320b0e3279c99a29d510d93",
          "sha256": "c7edd7ad687fb37ed01a604e92c90dfc7a6d856522accbed6cf42f2266e65c3f",
          "sha1": "40671fd20b387ac150437bbe8be88975102dda42",
          "md5": "dc3c409e1a68e7b420e6016bee9d5094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.4.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.4.jar",
          "size": 442082,
          "sha512": "1cda432ba6e4a4fd69343c1410761a1b0c0054f085a23d9867f050b16741a918d5c44760673df0f3902d5cdca48fa0261943e478f320b0e3279c99a29d510d93",
          "sha256": "c7edd7ad687fb37ed01a604e92c90dfc7a6d856522accbed6cf42f2266e65c3f",
          "sha1": "40671fd20b387ac150437bbe8be88975102dda42",
          "md5": "dc3c409e1a68e7b420e6016bee9d5094"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.4-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.4-sources.jar",
          "size": 221834,
          "sha512": "b9310146c157f3198f58a015e0ffd9a17a9dfb5d95ae8b77d143a35cf027b55acd65797cc76b8b244a6f33f234b6750d07f3f1cfc9f8708f474b06591d61c5fe",
          "sha256": "e2ef593b652898d8f9916144353a2240fcab093fc10d393f768799e7522ba483",
          "sha1": "66679071dd8fb5fca91b8be6708df1b622df1dbd",
          "md5": "dd290d438088cc7850baf94c116ede51"
        }
      ]
    }
  ]
}
