{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.6.2541.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2541.1.jar",
          "size": 538960,
          "sha512": "a2aa5a881c945fc8448293e955cd81382ab023f69dd807b1da2588569076164286606b137d955176526e6948fda5e583e3dae70f520fbe8ee552bc225340ba3d",
          "sha256": "62aeef21490b0e3312b386a6edfb25619a2921e917261013142238743bf7590a",
          "sha1": "943083d285ded03278f4a1236d1c81382320cfd4",
          "md5": "fc59117d89ae7b9f0af0a38e5f01709d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2541.1.jar",
          "size": 538960,
          "sha512": "a2aa5a881c945fc8448293e955cd81382ab023f69dd807b1da2588569076164286606b137d955176526e6948fda5e583e3dae70f520fbe8ee552bc225340ba3d",
          "sha256": "62aeef21490b0e3312b386a6edfb25619a2921e917261013142238743bf7590a",
          "sha1": "943083d285ded03278f4a1236d1c81382320cfd4",
          "md5": "fc59117d89ae7b9f0af0a38e5f01709d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2541.1-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2541.1-sources.jar",
          "size": 267982,
          "sha512": "8dcaef58dde2d9a4db9a194cb811cdcdc1764e891bab038077b4af4f0f8913ccf3135dbb0fa44610a01801323fabafd974ef3358ba30469e7e9227f3455e5e0a",
          "sha256": "b8ac91e63bb2f8b1e3cd6e11d41747b60aa482d9776555f0cd0bea3bac901f81",
          "sha1": "fa852f8d4ff06cc51c631a14d70dbc2494aabd90",
          "md5": "d8bf814dae6dd1a90fc2c999cece8ab4"
        }
      ]
    }
  ]
}
