{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2510.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2510.7.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2510.7.jar",
          "size": 704613,
          "sha512": "2661f6d3c391c452a0cccef5b2532e9d4afcf37aa01b2020b1a182d248e3fd1a4e217f689b9c6168d5a1074ecd9c16a4ba1e4d6d0419481cba2dee7a20f7365c",
          "sha256": "0ad50c03e756e7f3b92294f6f3025d415eef4763be28a20b6e58fa1359eb2e29",
          "sha1": "6c609d8c89b7c59a6468df475ced81602241c79e",
          "md5": "5f85c8379ce202b2ca41750854981288"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2510.7.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2510.7.jar",
          "size": 704613,
          "sha512": "2661f6d3c391c452a0cccef5b2532e9d4afcf37aa01b2020b1a182d248e3fd1a4e217f689b9c6168d5a1074ecd9c16a4ba1e4d6d0419481cba2dee7a20f7365c",
          "sha256": "0ad50c03e756e7f3b92294f6f3025d415eef4763be28a20b6e58fa1359eb2e29",
          "sha1": "6c609d8c89b7c59a6468df475ced81602241c79e",
          "md5": "5f85c8379ce202b2ca41750854981288"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2510.7-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2510.7-sources.jar",
          "size": 252635,
          "sha512": "62ecb96902d9b916bc85c256637e7b8ff1925e5155beca87eb393a5813b33f69650023a3d85fe268804356126bb3522dc77797396824ba417e1f646a6857fedf",
          "sha256": "b7d5338ffea6332b94ee73f76b895e6a4f859d7f4c02df95b3b381e062125e30",
          "sha1": "efbf39bb013cd56094cd2b546ab029c648e77035",
          "md5": "1883fdb45dfd123cc8f55e6966943949"
        }
      ]
    }
  ]
}
