{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2518.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2518.3.jar",
          "size": 19787583,
          "sha512": "57c56364e55928bbdc0e63df228a11fcf21e1ec4e858363be8a2bd4c14e53930361a5762740170ffe8dd519e4a85a77bfd3797eda9fbfa11473f416d275f982c",
          "sha256": "1085fc24de69483d77ef8ba26bb3e3537532c7ad41fd3cb78beca2a4cc3434ed",
          "sha1": "abbf3a6c7f49eeebda9b5abac59b1be7a8638464",
          "md5": "05440399887fa6e3698ece01fcf7d6c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2518.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2518.3.jar",
          "size": 19787583,
          "sha512": "57c56364e55928bbdc0e63df228a11fcf21e1ec4e858363be8a2bd4c14e53930361a5762740170ffe8dd519e4a85a77bfd3797eda9fbfa11473f416d275f982c",
          "sha256": "1085fc24de69483d77ef8ba26bb3e3537532c7ad41fd3cb78beca2a4cc3434ed",
          "sha1": "abbf3a6c7f49eeebda9b5abac59b1be7a8638464",
          "md5": "05440399887fa6e3698ece01fcf7d6c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2518.3-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2518.3-sources.jar",
          "size": 18904384,
          "sha512": "ff694c88acd9c8c4d949c183e19c88aad2d24c14ce0917b0a45139cde4b4075841b38fdbc2d6008225485490e1c83df45cac0da3a695e6f606bd939d780c77e2",
          "sha256": "b4ee5700a95952551b990d59488f63baa75a41cac2afa501139970bbfc5ad0cd",
          "sha1": "932c3f67f7ca4607a017432af5d22692eb4dd569",
          "md5": "51bca609009ddd8c8782907f71005394"
        }
      ]
    }
  ]
}
