{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.7.10.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.2501.23"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2501.2.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2501.2.jar",
          "size": 11914134,
          "sha512": "92ea689a2efd6c08236b6d9174607d20f3b843d02531fd8c774d7311739b3b3ec19908da5e8de2ef6986afabf753d99baed5e97b8dd9d11a160c4845b49e9594",
          "sha256": "617d12c45db005b012d3f65a53838306fcb221e83aa14564b8d3b55b71f3603f",
          "sha1": "9b181d193d2476fab868247f40d9eb7694a8fb3d",
          "md5": "21727a90c61bcc2a335e2f177bf5e92b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.2501.23"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2501.2.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2501.2.jar",
          "size": 11914134,
          "sha512": "92ea689a2efd6c08236b6d9174607d20f3b843d02531fd8c774d7311739b3b3ec19908da5e8de2ef6986afabf753d99baed5e97b8dd9d11a160c4845b49e9594",
          "sha256": "617d12c45db005b012d3f65a53838306fcb221e83aa14564b8d3b55b71f3603f",
          "sha1": "9b181d193d2476fab868247f40d9eb7694a8fb3d",
          "md5": "21727a90c61bcc2a335e2f177bf5e92b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2501.2-sources.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2501.2-sources.jar",
          "size": 11130556,
          "sha512": "8d22f88f84d8752149caa091d59429c5a7f5412a05c9e2c0ed2ba8b95ef02420cead5e8fd693957b0fc42517f46b53ae252fcb782be16613aeada6124a872092",
          "sha256": "09bc793013029e7f71326d162048cd4a0d6b8d788c0cb15a10811c191d6c10ea",
          "sha1": "3a46732f132a23c507662f6511499f4967eee6b8",
          "md5": "3dd3da673dda9035eca5009d54e87458"
        }
      ]
    }
  ]
}
