{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.1.jar",
          "size": 477306,
          "sha512": "8297ec26c22c177d66571c6230022790130d4b014340706d4f162aca105cab5510db6e600fe96c94a1181e03bdf5a02590af43fb38e9f7c483942d2873a0e240",
          "sha256": "ff1e285a78b3ecb30104b0341dd45b7c6416b8b855b0d2ef8404876e6768eedb",
          "sha1": "f149f74fb23ed478e5e5bc3c93ac87d028a29ee3",
          "md5": "1aa85d51ba5a7b8b559a3892c605cf41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.1.jar",
          "size": 477306,
          "sha512": "8297ec26c22c177d66571c6230022790130d4b014340706d4f162aca105cab5510db6e600fe96c94a1181e03bdf5a02590af43fb38e9f7c483942d2873a0e240",
          "sha256": "ff1e285a78b3ecb30104b0341dd45b7c6416b8b855b0d2ef8404876e6768eedb",
          "sha1": "f149f74fb23ed478e5e5bc3c93ac87d028a29ee3",
          "md5": "1aa85d51ba5a7b8b559a3892c605cf41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.1-sources.jar",
          "size": 241206,
          "sha512": "ea1ae5c1f0dfd3b84defd69774d70ae5f23f8fdce9a926a69761b223b9b0f501f35dfdbe3083fe09e096c47a28a5995cdfbd6eec48a16e503b50b7edd2ed0d01",
          "sha256": "b66a46c5a6c9e3148eeaa0b29dc4bcbf92f7e91917487d9b0db1d0c19530cfb8",
          "sha1": "c189da5c8cbc32f8901fdb867c3356926af07c5f",
          "md5": "4cf3120faa78a25be8881bae48bbcb9c"
        }
      ]
    }
  ]
}
