{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2506.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2506.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2506.1.jar",
          "size": 474732,
          "sha512": "ba23cc3e6d55d38aabda3c9b7a5c62a80d326ab32b12713ebf53f29af55d3982f614d7900363167c7746556f8c8d0932e86e6f141a9d7694b8585cac85676e10",
          "sha256": "193f6a49a5b25ed912bcff709666395f7e76a1a22c25446b0728bca4064c327c",
          "sha1": "1b88374855365b2eeb07971b651195b374bf8d83",
          "md5": "bdd66d03218f4db0ef1fbd4ae28a8976"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2506.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2506.1.jar",
          "size": 474732,
          "sha512": "ba23cc3e6d55d38aabda3c9b7a5c62a80d326ab32b12713ebf53f29af55d3982f614d7900363167c7746556f8c8d0932e86e6f141a9d7694b8585cac85676e10",
          "sha256": "193f6a49a5b25ed912bcff709666395f7e76a1a22c25446b0728bca4064c327c",
          "sha1": "1b88374855365b2eeb07971b651195b374bf8d83",
          "md5": "bdd66d03218f4db0ef1fbd4ae28a8976"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2506.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2506.1-sources.jar",
          "size": 241352,
          "sha512": "3f2c2d6cab354aef0ed33d50ee945dcbc460c7c85f4f551a1cbc649f5035eb26c3069895fa90850bb13f4467328c7eae791c4020da09cd0727d9b24093391956",
          "sha256": "9ac94227ba0a7f178394f00ef9889825cf124cead1f38a0b1cb5038ad68c839a",
          "sha1": "66800b61627e3e27da32299d42364b4e01629b66",
          "md5": "8140f73281e1b4262d4d78526eee69ad"
        }
      ]
    }
  ]
}
