{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "26.1.1-2.2.7.2616.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.1.jar",
          "size": 561689,
          "sha512": "afa06098e0ebd8b2a572ca4093d83e9b3d6e27422a3666576657e484d0dddfc8a034fac7a908df385fc31e995050f4983ed0bedc7027a1a7dfc57bf96abd6257",
          "sha256": "2e3dbcc57e8b4a5a92057e58a827e7886131527ac5ca7fad50da7def7d59b461",
          "sha1": "bd92c2276a796ca2c4bd167c02712b70d5f64167",
          "md5": "a7f616f227515bc01f717c257b38d2fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.1.jar",
          "size": 561689,
          "sha512": "afa06098e0ebd8b2a572ca4093d83e9b3d6e27422a3666576657e484d0dddfc8a034fac7a908df385fc31e995050f4983ed0bedc7027a1a7dfc57bf96abd6257",
          "sha256": "2e3dbcc57e8b4a5a92057e58a827e7886131527ac5ca7fad50da7def7d59b461",
          "sha1": "bd92c2276a796ca2c4bd167c02712b70d5f64167",
          "md5": "a7f616f227515bc01f717c257b38d2fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.1-sources.jar",
          "size": 256827,
          "sha512": "ce98f3a4a40f33b2d98164fe9f64206a09ebebf7cf03894581e155bb5ce865e964cc47deb2bd8fd70871e13db922556e46607a23c3c537bc471b6e3095e3069e",
          "sha256": "3217ef615e6000a31923c5a6e56f97ae31a94856b12e86ca63383672ddd3bdb5",
          "sha1": "fe2f6a00f7b7f3b63ccc77a33fae413aa3601588",
          "md5": "937c18cb935ae5500ef46fc3af47a9f2"
        },
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.1-sources.jar",
          "size": 256827,
          "sha512": "ce98f3a4a40f33b2d98164fe9f64206a09ebebf7cf03894581e155bb5ce865e964cc47deb2bd8fd70871e13db922556e46607a23c3c537bc471b6e3095e3069e",
          "sha256": "3217ef615e6000a31923c5a6e56f97ae31a94856b12e86ca63383672ddd3bdb5",
          "sha1": "fe2f6a00f7b7f3b63ccc77a33fae413aa3601588",
          "md5": "937c18cb935ae5500ef46fc3af47a9f2"
        }
      ]
    }
  ]
}
