{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2504.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2504.4.jar",
          "size": 451695,
          "sha512": "8b1880fc9a75b1988b6b546c69e5bc6d5c626d7e49f6ed00c67be85b3076f6661b6268840397dbdfc307db5916f009ec93f0c089fafa547b8cc36f9227e68542",
          "sha256": "d6ad64fc006b24897298230c8c56bdf479dd14926a1a356209073becccba31c7",
          "sha1": "9f8aa0f8919c2a7107a50ddc7563d63a2eb6973f",
          "md5": "969724383caf3b9e70d571c624c87485"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2504.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2504.4.jar",
          "size": 451695,
          "sha512": "8b1880fc9a75b1988b6b546c69e5bc6d5c626d7e49f6ed00c67be85b3076f6661b6268840397dbdfc307db5916f009ec93f0c089fafa547b8cc36f9227e68542",
          "sha256": "d6ad64fc006b24897298230c8c56bdf479dd14926a1a356209073becccba31c7",
          "sha1": "9f8aa0f8919c2a7107a50ddc7563d63a2eb6973f",
          "md5": "969724383caf3b9e70d571c624c87485"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2504.4-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2504.4-sources.jar",
          "size": 231442,
          "sha512": "be123d5a1b218ff0fef1db8c352f0e5a8f33c46240a9e96c9477e7a9d086e058b39bc5ec40454b1f407f5bae123fc624e6998ff329ebd2e18f04a5eb338e5bcd",
          "sha256": "38fa7387b67f4b7e5fb93a000a45409fa29900612220678f4a7f50d4457030c4",
          "sha1": "06b037ba7ec9a373a2503c6f67c4f13e8cc65611",
          "md5": "257380a054ec092142aab1fc83a24113"
        }
      ]
    }
  ]
}
