{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2516.0.jar",
          "size": 18292401,
          "sha512": "f4dac4a15040ef23c623c4fd44757fe3378ea0b05cf92a3106a7630a3374e92213f4a029bb2349b632a6e2d12c0ee96a27cbf0239cb85a762687a45e92f747fd",
          "sha256": "25e95a6cd9597c4303423808c8e3fb5447993e50d248f216320f0085224f1725",
          "sha1": "6dc7f1ab0bc3a64fb4950df7a0e3d342573db214",
          "md5": "a5d176ea74b9b8c2022806a23ebeaec3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2516.0.jar",
          "size": 18292401,
          "sha512": "f4dac4a15040ef23c623c4fd44757fe3378ea0b05cf92a3106a7630a3374e92213f4a029bb2349b632a6e2d12c0ee96a27cbf0239cb85a762687a45e92f747fd",
          "sha256": "25e95a6cd9597c4303423808c8e3fb5447993e50d248f216320f0085224f1725",
          "sha1": "6dc7f1ab0bc3a64fb4950df7a0e3d342573db214",
          "md5": "a5d176ea74b9b8c2022806a23ebeaec3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2516.0-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2516.0-sources.jar",
          "size": 17434315,
          "sha512": "ddd4525fd0d207737312b4a08eb2fc6e8c17aad90816d92c1831b0e115b1dde2b81035ac04b1a9f6ac8e23737776284d026e9677e956f8ef138766a8851b892c",
          "sha256": "3e9a3a213a26ae77eb9d37a7bd4a18513d846dd1633d62a06dc29d743de7920a",
          "sha1": "fb3656bcbce0e73149db88634bd9fc2a7fd7fd51",
          "md5": "f5bc4c132469a3d4ba525624011c8540"
        }
      ]
    }
  ]
}
