{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2515.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2515.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2515.1.jar",
          "size": 694195,
          "sha512": "59702e3bb3d4c17f2a2c56d0dd215d3de94dfb762a022b5b1d805aca9cdbf7216bfb9fc20f3b22c8be4668bb428a722488d270f570b7d181bbb4a2fdbd0c5ade",
          "sha256": "e51117352336a4eaae39f8a6dbf07084eda6049891275b3337bc35d3f71dd6bc",
          "sha1": "c0b6f2b99b1aaa7453dbdf3bb3f217cd693d9c7e",
          "md5": "646e9764c2ba20ac56378a13eff307f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2515.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2515.1.jar",
          "size": 694195,
          "sha512": "59702e3bb3d4c17f2a2c56d0dd215d3de94dfb762a022b5b1d805aca9cdbf7216bfb9fc20f3b22c8be4668bb428a722488d270f570b7d181bbb4a2fdbd0c5ade",
          "sha256": "e51117352336a4eaae39f8a6dbf07084eda6049891275b3337bc35d3f71dd6bc",
          "sha1": "c0b6f2b99b1aaa7453dbdf3bb3f217cd693d9c7e",
          "md5": "646e9764c2ba20ac56378a13eff307f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2515.1-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2515.1-sources.jar",
          "size": 252979,
          "sha512": "d0caa993efbeb18928f9d1aa456b6951d1a866f70a8574303f524cd48c0a1ba8d1f3f32187852e4e00de58650e2772836c607153bbccb49d5caa1faff27524f7",
          "sha256": "9279b8a9c9cb3945166fdf1001d41f1b0c6e1e03728abd24dcea024bc3164808",
          "sha1": "97af143c538c5ba865e33233c7ffe23c89401289",
          "md5": "aaf21c5deb67ead3823844d9252f63bb"
        }
      ]
    }
  ]
}
