{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2500.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2500.6.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2500.6.jar",
          "size": 396673,
          "sha512": "b08c3d31257e218e151902532d9a8d6f745a06f8822581faa7ccf35759b828a2c65267c44eedc1393874bb7e861f585a8ceacf66d8f287c2d708f85254091ddb",
          "sha256": "6be193d31935366bc074e50aaecfda108b4a29c6d73960d2b6a6ff86150efac3",
          "sha1": "75b1a0c30c1617e588998e03fd3589852aa9de42",
          "md5": "7be4021cd06ee7521bbf3576dc07ef77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2500.6.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2500.6.jar",
          "size": 396673,
          "sha512": "b08c3d31257e218e151902532d9a8d6f745a06f8822581faa7ccf35759b828a2c65267c44eedc1393874bb7e861f585a8ceacf66d8f287c2d708f85254091ddb",
          "sha256": "6be193d31935366bc074e50aaecfda108b4a29c6d73960d2b6a6ff86150efac3",
          "sha1": "75b1a0c30c1617e588998e03fd3589852aa9de42",
          "md5": "7be4021cd06ee7521bbf3576dc07ef77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2500.6-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2500.6-sources.jar",
          "size": 192500,
          "sha512": "10e2d86349fa5e3dd444a84e1f22ab0d6371d3e81c96eff6ded4cf2eb54f55cf798dc2be80ca62af66d5d3e771f9cb76aa213df00f41f3925153f535fb3d5e98",
          "sha256": "638c87347ad80d65b302ca54994ed471b762d7543f87825289e8d5964188aaf1",
          "sha1": "233a3a65540b3d0a124b1caea198e1fdaf6c63d2",
          "md5": "5e6764a7c6e0dbb904e4c5f69a0abe40"
        }
      ]
    }
  ]
}
