{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2511.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2511.3.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2511.3.jar",
          "size": 18265679,
          "sha512": "7540a6ed5d4497136bfcfa0f6fb0aae9badf1327738b9402efdee1c8a8835fa599f968d9f90a90df469078ba77cdbc53b2fdd90d2f0052c716b9e56f1473a272",
          "sha256": "027d419d48d80fec27aea05ea2e0a330043c5db83d68c3689b45e2822757dc52",
          "sha1": "81de660f1e3371f9cf94a29cd32ac2edf103cdc7",
          "md5": "33945ad9362c760c9fd06d95029a1275"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2511.3.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2511.3.jar",
          "size": 18265679,
          "sha512": "7540a6ed5d4497136bfcfa0f6fb0aae9badf1327738b9402efdee1c8a8835fa599f968d9f90a90df469078ba77cdbc53b2fdd90d2f0052c716b9e56f1473a272",
          "sha256": "027d419d48d80fec27aea05ea2e0a330043c5db83d68c3689b45e2822757dc52",
          "sha1": "81de660f1e3371f9cf94a29cd32ac2edf103cdc7",
          "md5": "33945ad9362c760c9fd06d95029a1275"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2511.3-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2511.3-sources.jar",
          "size": 17428280,
          "sha512": "0b4e9c4887b295cc3daf9fea3d0df59b4cb60a4590464ed40fee1545e7eaf4d08f67f3c298e1abe0c1f7480822dd958ae436fa8b265d50b147503660da3afae3",
          "sha256": "befea39263c5120872737a19889436796c5e4fcb2ad7b5a885972b58a931bc69",
          "sha1": "78d0539b31e212fea935881ffdf8ef3fe7291a14",
          "md5": "9f27f3d00617fb5cdf2f4a03bc06a0d6"
        }
      ]
    }
  ]
}
