{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.1.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.1.jar",
          "size": 707596,
          "sha512": "ec9f4ad5cb2afee02198e09501c375d5118ff3f9bffbfa34566d3978278df01d0a94ddbdc1eeb9c8b348780d6e4887ff8aae7e94b981e503df0eb699d0436e1b",
          "sha256": "5b02bd8136237487a442fcb477c0444a6dcd30efbd7466654c4ed2463a66771c",
          "sha1": "c73226900e27c58518144749c0403ee85b3525af",
          "md5": "f9a989b85b809488f9b1bb253a7550f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.1.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.1.jar",
          "size": 707596,
          "sha512": "ec9f4ad5cb2afee02198e09501c375d5118ff3f9bffbfa34566d3978278df01d0a94ddbdc1eeb9c8b348780d6e4887ff8aae7e94b981e503df0eb699d0436e1b",
          "sha256": "5b02bd8136237487a442fcb477c0444a6dcd30efbd7466654c4ed2463a66771c",
          "sha1": "c73226900e27c58518144749c0403ee85b3525af",
          "md5": "f9a989b85b809488f9b1bb253a7550f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.1-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.1-sources.jar",
          "size": 252358,
          "sha512": "56f6ea061b528b288350769adb72a2be7d25a3304d66d269c5740914a7896ac6ee13eaa731ec2028a6bbecdf6d7a2d6c4dcf136b3aaab3e4d8f43627af31aa1d",
          "sha256": "4d929d3f15f1c68bf48b5bf8d5fd6105e0b51c648b6bc4a9e0883eedc4ede91d",
          "sha1": "edc0d1803514e7ccfc3885ecb334b2f13f62e454",
          "md5": "5542bebf2912c330d60804caf484200e"
        }
      ]
    }
  ]
}
