{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.4-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.7.2617.0.jar",
          "url": "factory_api-fabric-1.21.4-2.2.7.2617.0.jar",
          "size": 598461,
          "sha512": "883684ea89b2d481bc5f531236ebb5b99ff1696d66d7f7dd10406b0769847f425f5e481f0cfdc8929822af389e803dc276992650a559b63173bf196055ad709a",
          "sha256": "960a976ca7e693bd8a3215b6bf5a290f57a491928756022e995ad13c45407623",
          "sha1": "437bb946f16e141fa5c105793b2be69e8d25ed5d",
          "md5": "4f27047cb55567f5a056c03e38b57440"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.7.2617.0.jar",
          "url": "factory_api-fabric-1.21.4-2.2.7.2617.0.jar",
          "size": 598461,
          "sha512": "883684ea89b2d481bc5f531236ebb5b99ff1696d66d7f7dd10406b0769847f425f5e481f0cfdc8929822af389e803dc276992650a559b63173bf196055ad709a",
          "sha256": "960a976ca7e693bd8a3215b6bf5a290f57a491928756022e995ad13c45407623",
          "sha1": "437bb946f16e141fa5c105793b2be69e8d25ed5d",
          "md5": "4f27047cb55567f5a056c03e38b57440"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.7.2617.0-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.7.2617.0-sources.jar",
          "size": 256570,
          "sha512": "4e2e89659dd2a1e3cff63d00dda6cd4f8a603a4e4cbf3d93e9a18a3d29421fa429ac77801abde823648bd0715ad548fd64de4f4b895f73586ae8ea4f7072c114",
          "sha256": "0cf4e57d399e9d76262672965dc24657ea4cc312d5191b983c4f23dcee14c73a",
          "sha1": "4a08e05c2b0f73a5e116833a64e2994017e9bdcc",
          "md5": "5979e573cd2dcd70b6340648e81a109e"
        }
      ]
    }
  ]
}
