{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.4.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.4.jar",
          "size": 481163,
          "sha512": "29e00656398454eb84dd9979e738859dfe089dde1d15c080e9c27302b7ebd2ce0cba6a623afd2d2027706604890d418807bee02c54a931e1cb8ce3e4c11a7dfc",
          "sha256": "34e0ccde64653b6f02772c800cc9f4dc8b83373c743c3885cb3698b14c9454b5",
          "sha1": "20b16eed88ad5041763215702bda35458c05aeab",
          "md5": "925cba7690cebf47d717d6fef87d19e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.4.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.4.jar",
          "size": 481163,
          "sha512": "29e00656398454eb84dd9979e738859dfe089dde1d15c080e9c27302b7ebd2ce0cba6a623afd2d2027706604890d418807bee02c54a931e1cb8ce3e4c11a7dfc",
          "sha256": "34e0ccde64653b6f02772c800cc9f4dc8b83373c743c3885cb3698b14c9454b5",
          "sha1": "20b16eed88ad5041763215702bda35458c05aeab",
          "md5": "925cba7690cebf47d717d6fef87d19e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.4-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.4-sources.jar",
          "size": 246149,
          "sha512": "b705c454065b050792e37eaeb3e312cd9efc1c2f886e077d0712945bd88b318476a3af9ed4b10b5500a21f09b586486e953dd2afd099ed124010ac56c84d6ff3",
          "sha256": "67782dec6d21a719dd3c34edb2574d30c54ba5d32c26cec020bf7d13437b5879",
          "sha1": "3fd340ab1d72367c3de96c291b98b2e9a4db6589",
          "md5": "14301dbdad55398d0570fc60b4f15fe5"
        }
      ]
    }
  ]
}
