{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.8-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3-pre"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8-pre.jar",
          "url": "legacy-fabric-1.20.1-1.8-pre.jar",
          "size": 14382291,
          "sha512": "1afc1eb38b6e2db61acc115819b31fcaa9f0e653594efcf2fb2a44a8ed87fb7668aab80b685645a0c64a9b4aa21f1314f3c8c8b4fb8f49875b3e8a86e11c47ac",
          "sha256": "b40b665f5bfd8f5a39784c02603974ef6744f0cfada4f47db4b715934c13d40f",
          "sha1": "6da60714f26a5996261d6ba490532231ee155728",
          "md5": "949d3ee8f0b51703e28cbd2f5decc077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3-pre"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.20.1-0.5.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8-pre.jar",
          "url": "legacy-fabric-1.20.1-1.8-pre.jar",
          "size": 14382291,
          "sha512": "1afc1eb38b6e2db61acc115819b31fcaa9f0e653594efcf2fb2a44a8ed87fb7668aab80b685645a0c64a9b4aa21f1314f3c8c8b4fb8f49875b3e8a86e11c47ac",
          "sha256": "b40b665f5bfd8f5a39784c02603974ef6744f0cfada4f47db4b715934c13d40f",
          "sha1": "6da60714f26a5996261d6ba490532231ee155728",
          "md5": "949d3ee8f0b51703e28cbd2f5decc077"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8-pre-sources.jar",
          "url": "legacy-fabric-1.20.1-1.8-pre-sources.jar",
          "size": 13576983,
          "sha512": "02c4f88be8ae756143d7163e0ade86de3fd865a3635e2d4331f2988a196988568d60c4a66d554c9d22554b54785f56eaa9533eb3e34814244d7392d1e532ddc9",
          "sha256": "5d04bee7deb78e0886da0e93c3dc1a41574d5bcbb6db1102d470bc8f703ab084",
          "sha1": "4ade07c4467fa02d3db9b2576c29475f50428195",
          "md5": "6f2a03b5fd32d13898dc449a9a88e5f6"
        }
      ]
    }
  ]
}
