{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.6.2547.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2547.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2547.1.jar",
          "size": 550059,
          "sha512": "ec7f6995e93e355b6b7f1768aabd6c6c14855b717c2a84ce6621118a1f76457c8c13ced3ab27c328c2d649b6923d5264a8ae9eb65109b0b1d8c72e92085b785b",
          "sha256": "f4950a619b9138efda04084ba8c2e51cef61121ca4351141c1728ffa43b838b7",
          "sha1": "9671d336f896b628452cf27a50c2e0c8587d5b14",
          "md5": "f1a3ce05f04097284f803d2b247c03f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2547.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2547.1.jar",
          "size": 550059,
          "sha512": "ec7f6995e93e355b6b7f1768aabd6c6c14855b717c2a84ce6621118a1f76457c8c13ced3ab27c328c2d649b6923d5264a8ae9eb65109b0b1d8c72e92085b785b",
          "sha256": "f4950a619b9138efda04084ba8c2e51cef61121ca4351141c1728ffa43b838b7",
          "sha1": "9671d336f896b628452cf27a50c2e0c8587d5b14",
          "md5": "f1a3ce05f04097284f803d2b247c03f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2547.1-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2547.1-sources.jar",
          "size": 269420,
          "sha512": "932ec3b9d015bc931cbec24c23e2e033dd3fb50156b916fb117ed539fa99de005aec3bbfa7c8ae3d14c54300597af3c6e9029cd1f4eab39c141d4eae8cb72a4d",
          "sha256": "53364bbe5196ee95783b4e297b5db7aef0e0337ae4c2ea5b245d6fc51f5e3a13",
          "sha1": "68eed25275d82cbc9522ba85b21ab13b6e26f003",
          "md5": "dc72f89cde7e27bdc1f3f8f37f39468a"
        }
      ]
    }
  ]
}
