{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2504.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.5.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.5.jar",
          "size": 492279,
          "sha512": "4d76db00d137110a2c3f63ae15c3ed8907adf1f88121064ed4ba6afd5ddab28e469593563f113ebf5ba23b938f07ec89cf03e7cf3a672898a88698ff66b3bfc3",
          "sha256": "fa215e12a0aab8c30b920055c20d28318b011f4047f3026953dc853e81ef4124",
          "sha1": "0b2ff5ca1bdab7c5b04d1a90240c6d3b5881aebf",
          "md5": "e3c85eaf42fbb3bdf7e268434338b1df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.5.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.5.jar",
          "size": 492279,
          "sha512": "4d76db00d137110a2c3f63ae15c3ed8907adf1f88121064ed4ba6afd5ddab28e469593563f113ebf5ba23b938f07ec89cf03e7cf3a672898a88698ff66b3bfc3",
          "sha256": "fa215e12a0aab8c30b920055c20d28318b011f4047f3026953dc853e81ef4124",
          "sha1": "0b2ff5ca1bdab7c5b04d1a90240c6d3b5881aebf",
          "md5": "e3c85eaf42fbb3bdf7e268434338b1df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.5-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.5-sources.jar",
          "size": 228912,
          "sha512": "53bb66f2e16d689a81fee3bd189f1bfc453ad22f7b53aface19c43a535c0381b7fc4cbbf77c2f2321481e7bae5c34e3517c6126379eae0ae5ca272cf8110e1c3",
          "sha256": "524d8ee57984edad2c90a10ad585048e0b927301bbc9914c7c470d5fd9be257d",
          "sha1": "0d6b6e5b5effbceb8f1436d81a5f42e956888847",
          "md5": "e04c2c4b9a29589c1702122c42d18823"
        }
      ]
    }
  ]
}
