{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2501.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.15.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.15.jar",
          "size": 382172,
          "sha512": "ab3072f9179ee7dd6c0fef2d343ab2bcdfff29b5ad729d437b87ccbb3ef873d5b5c1fc39baebe412b34d18dbe6dc888c36d2fbab78d1278ad86bcd998c979897",
          "sha256": "590ac44359d3b3000e364b1ba9d236cb65cfa8db4132ea89798c9b76097719a5",
          "sha1": "44ce538d51cb9984f5eb7590cd3620663385a800",
          "md5": "6b6a7e3173b84cb00d231142b0576142"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.15.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.15.jar",
          "size": 382172,
          "sha512": "ab3072f9179ee7dd6c0fef2d343ab2bcdfff29b5ad729d437b87ccbb3ef873d5b5c1fc39baebe412b34d18dbe6dc888c36d2fbab78d1278ad86bcd998c979897",
          "sha256": "590ac44359d3b3000e364b1ba9d236cb65cfa8db4132ea89798c9b76097719a5",
          "sha1": "44ce538d51cb9984f5eb7590cd3620663385a800",
          "md5": "6b6a7e3173b84cb00d231142b0576142"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.15-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.15-sources.jar",
          "size": 199746,
          "sha512": "53823232bc1bd14032ff40eb1e4f0e984dbe2ab1d8ae1c2ebc631f843a523b0f055cd7911df1f5857ec4cf75ec95df5ca23018010be6f915d18a9cf7f20eef7f",
          "sha256": "63f6377b02da9299592dd7d67962b74116534051c6b40c1ae7868f727155dcc9",
          "sha1": "030e8936a69ec557badcd7808753f797fdc5c220",
          "md5": "c70f15946f8feeacb09e8c9a6961ad17"
        }
      ]
    }
  ]
}
