{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2510.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.8.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.8.jar",
          "size": 513771,
          "sha512": "fefce4ea33000e41dfadff981553757c84e0ffb48fa57cc47dd63d99c5caa75b6b575dc786dcd40f95ad58729ae67d362b9269927e6a7ed35589a5dd68f538fa",
          "sha256": "cab8db773edf4ccf6888535f9e9bfc4ab8f1848fa97d197d7b08c82c74f7a35f",
          "sha1": "d759b5da234b0e149c564d7b245d39d2fa8ae795",
          "md5": "362fcaaf008083cbaf03284978f9d345"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.8.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.8.jar",
          "size": 513771,
          "sha512": "fefce4ea33000e41dfadff981553757c84e0ffb48fa57cc47dd63d99c5caa75b6b575dc786dcd40f95ad58729ae67d362b9269927e6a7ed35589a5dd68f538fa",
          "sha256": "cab8db773edf4ccf6888535f9e9bfc4ab8f1848fa97d197d7b08c82c74f7a35f",
          "sha1": "d759b5da234b0e149c564d7b245d39d2fa8ae795",
          "md5": "362fcaaf008083cbaf03284978f9d345"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.8-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.8-sources.jar",
          "size": 250777,
          "sha512": "365950ef8eca4c28765e664233c347b7873cb1809c93e22265aad8e8b8ba73f33575267f724e36ae7b86e3badc994881efc93d11bf3e6a3eb213496587b1ea94",
          "sha256": "e411beaa58ef6cc0d6f60b00cc9fd63a11a6a5b75529a9a89e10e6452e809893",
          "sha1": "d7cc2e2d4cd119c4dba68865babaf8be21e08b98",
          "md5": "8fc2f3f777f9ed424fed28f5baf23e29"
        }
      ]
    }
  ]
}
