{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.21.1-1.1.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2516.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.2.jar",
          "size": 640273,
          "sha512": "853ce0151a071311a95a8f4e352632b4771c756eb699b09e9b93290b85201cb13ded97010ab4d94822de0f8a54767c7a9ffe201e28d20299b9f5ffc28695eb72",
          "sha256": "1e54efb448831af673d912f66915d06461aa8ad17ea230b21d166bfac842e19c",
          "sha1": "fde77a9f98f0d531dbc6064b8fb8ad9b617e4837",
          "md5": "7485949ecb4b73c7cf1906171a6c6eea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2516.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.2.jar",
          "size": 640273,
          "sha512": "853ce0151a071311a95a8f4e352632b4771c756eb699b09e9b93290b85201cb13ded97010ab4d94822de0f8a54767c7a9ffe201e28d20299b9f5ffc28695eb72",
          "sha256": "1e54efb448831af673d912f66915d06461aa8ad17ea230b21d166bfac842e19c",
          "sha1": "fde77a9f98f0d531dbc6064b8fb8ad9b617e4837",
          "md5": "7485949ecb4b73c7cf1906171a6c6eea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.2-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.2-sources.jar",
          "size": 583303,
          "sha512": "e6b32060a5d679109f9de674b7dbd06bdf6b0e197c74cdeb1bb0cfdb6f553aaa6242d19d654734a5b542483442fc81864f8f77deb063a2ee5213174c9f2d5f22",
          "sha256": "fbaa158d9f7bf9c45b351af6525ac9d8b2fab1a9220f9ec38badecac830af2fa",
          "sha1": "5d65b6f8c89ab5ff81d7c269e61035320be2d707",
          "md5": "e119fc54d7c2baebeb118753617c4988"
        }
      ]
    }
  ]
}
