{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.11.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.11.jar",
          "size": 368921,
          "sha512": "a3b71e48a977e38cfdcbd2da63ace3cb57b68e244c43821e673e557281a69aaf5afeab5043cc9453c76e3c5bff77131fd58c3bbfc54adaa687cce06b28fd2e47",
          "sha256": "2b0fb17f98614e45a31656e47eb89a61af685c167fda5b1c0eaa4f4efc353cbf",
          "sha1": "f34b080305110a6dfd0c217ec043c813724d5dd9",
          "md5": "733c87c743409cf684aa4947b5250c4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.11.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.11.jar",
          "size": 368921,
          "sha512": "a3b71e48a977e38cfdcbd2da63ace3cb57b68e244c43821e673e557281a69aaf5afeab5043cc9453c76e3c5bff77131fd58c3bbfc54adaa687cce06b28fd2e47",
          "sha256": "2b0fb17f98614e45a31656e47eb89a61af685c167fda5b1c0eaa4f4efc353cbf",
          "sha1": "f34b080305110a6dfd0c217ec043c813724d5dd9",
          "md5": "733c87c743409cf684aa4947b5250c4a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.11-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.11-sources.jar",
          "size": 196912,
          "sha512": "60a0833ef64e74a59f26f31d85cfa8fc82ee75e6c03238606c60a5dce3c84b537ee4c5e399f29cac25380ca263dbed23939dfce544796cdb6e78e29aacf4c86d",
          "sha256": "3efe1149d7a4c70f5385942f3a37db3ebb648a0d038d9b7036778d0dd69ec27d",
          "sha1": "269287345fb6f95036e6a9bec4050e41ee29f397",
          "md5": "9d740179941bd3e224dc1e13dc6a54b7"
        }
      ]
    }
  ]
}
