{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.17.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.17.jar",
          "size": 367848,
          "sha512": "e1693afb0fd372fd7c6528a91cfed6fbfb387ce79df22155e6cfdba6bd70856ed3f2a757cad0d4791872b549a9ea9747e8730c17ca5177a1760a217b3f09f572",
          "sha256": "ba5ca741a43530160e41a788326224e1a31daf9637a737bf88c8ec7273f09efe",
          "sha1": "078bbaddb3163492568f865fc1b12fa7f6bf921d",
          "md5": "2ca1bc498d948ba864c5a1d5572bb725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.17.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.17.jar",
          "size": 367848,
          "sha512": "e1693afb0fd372fd7c6528a91cfed6fbfb387ce79df22155e6cfdba6bd70856ed3f2a757cad0d4791872b549a9ea9747e8730c17ca5177a1760a217b3f09f572",
          "sha256": "ba5ca741a43530160e41a788326224e1a31daf9637a737bf88c8ec7273f09efe",
          "sha1": "078bbaddb3163492568f865fc1b12fa7f6bf921d",
          "md5": "2ca1bc498d948ba864c5a1d5572bb725"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.17-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.17-sources.jar",
          "size": 198841,
          "sha512": "a503366f078282c1e1c2e4ee6fc8cefdbebf307f58218247052be651545e56ef241d50bfcae425273a3bca350def818859336cf262b00a569aa52908161b3f5a",
          "sha256": "f65064f86d504b3e2c162852dad8cf325f5076350ff4789549495cea58fc980f",
          "sha1": "dd7a549875f7c7b6d43676540934985c1a835625",
          "md5": "ed66bd32e88e327ff0fd2b0c7fcd3253"
        }
      ]
    }
  ]
}
