{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.1.jar",
          "size": 477525,
          "sha512": "d3ac33d10d6c6a1f9120bc8f027ecbd8b4c6a7024a08475d971c488bc0e06c60a2b0f0e19bb8d43aabfaa0a6c76ca1e80058fe51bbac32ce7cebdee267ddd89d",
          "sha256": "c4c3479bddd927bdac196a4ff675754170088fe7f03b5a9a6bea1e7a0f5b4306",
          "sha1": "cd43a48d9fecf38612789874e87fed91cbf7a361",
          "md5": "894939b172365f3e04ac6ff9b4b06a79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.1.jar",
          "size": 477525,
          "sha512": "d3ac33d10d6c6a1f9120bc8f027ecbd8b4c6a7024a08475d971c488bc0e06c60a2b0f0e19bb8d43aabfaa0a6c76ca1e80058fe51bbac32ce7cebdee267ddd89d",
          "sha256": "c4c3479bddd927bdac196a4ff675754170088fe7f03b5a9a6bea1e7a0f5b4306",
          "sha1": "cd43a48d9fecf38612789874e87fed91cbf7a361",
          "md5": "894939b172365f3e04ac6ff9b4b06a79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.1-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.1-sources.jar",
          "size": 243029,
          "sha512": "d7e319ac03939d7338361b30c2acd1cd73c1b3656df7964e3b907f99539a838b66cc6a9cf9204fc37879bbd211eb200d3b24d6a62f37d7b06a4e85e6b2847fba",
          "sha256": "766d668f8c5e28ce6d4bea56c92178f90008dc09c8c9a86b5e15691a7cef68cf",
          "sha1": "b9e032b2037349bbd968a1ad0ece15f7f89f4461",
          "md5": "79bb86e1c5def61c32fde2df1a93a1a3"
        }
      ]
    }
  ]
}
