{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.8.0.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2514.0.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2514.0.jar",
          "size": 18263353,
          "sha512": "8d2af16804cd8124f27fdcd3f4e373ceb39d0e5a46c4edb698f24a133127104301bbc4815518b60d4f71536a354f795d58efcfe45a3db8f5855d0bb28cd1e83b",
          "sha256": "2ff2f247042dd034cceae0f1e33d1fec5df16805e8c40d5fc833cf5e104ee78d",
          "sha1": "1f69b86baee3e21d2a95b161a1f370f4f2d53b64",
          "md5": "6d566b6cb46b819aade06f696b9cb4c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2514.0.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2514.0.jar",
          "size": 18263353,
          "sha512": "8d2af16804cd8124f27fdcd3f4e373ceb39d0e5a46c4edb698f24a133127104301bbc4815518b60d4f71536a354f795d58efcfe45a3db8f5855d0bb28cd1e83b",
          "sha256": "2ff2f247042dd034cceae0f1e33d1fec5df16805e8c40d5fc833cf5e104ee78d",
          "sha1": "1f69b86baee3e21d2a95b161a1f370f4f2d53b64",
          "md5": "6d566b6cb46b819aade06f696b9cb4c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2514.0-sources.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2514.0-sources.jar",
          "size": 17432045,
          "sha512": "aa0bf2c97f73648b4e0556e452cf18227805f2c42b7bd93afb43f3c3a905a5110eec90c855fd329ac025318474db47e37947d7dc89f2ce570af16808e7a6deee",
          "sha256": "b95570b388c5233a120316d33b7b8f328529f3dcba2096345c81ec6205d1e7cb",
          "sha1": "fb3c405dc5c7a6ef7818436fa8fe51c2698f0d9a",
          "md5": "bab2ef3ada0e46ef292f46f41340cc88"
        }
      ]
    }
  ]
}
