{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2500.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.5.jar",
          "size": 351566,
          "sha512": "2e1a0d397689c75888aa296ba050ba8e9c6ff1467270e5934ec009d706611a7326a6a859b1c4d23f745bebbe522791d76df38233e365d69f4ee7b845de1af9bb",
          "sha256": "9e4c1828e631e2560e7b192d10f773753ecb7a39356344bdbf33701affb40d1e",
          "sha1": "26d3e2d7826dae106ef94237827e17f89bfc50c0",
          "md5": "77695a90a7685b3acd4e095b49d8bfb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.5.jar",
          "size": 351566,
          "sha512": "2e1a0d397689c75888aa296ba050ba8e9c6ff1467270e5934ec009d706611a7326a6a859b1c4d23f745bebbe522791d76df38233e365d69f4ee7b845de1af9bb",
          "sha256": "9e4c1828e631e2560e7b192d10f773753ecb7a39356344bdbf33701affb40d1e",
          "sha1": "26d3e2d7826dae106ef94237827e17f89bfc50c0",
          "md5": "77695a90a7685b3acd4e095b49d8bfb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.5-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.5-sources.jar",
          "size": 194845,
          "sha512": "c42c7d6db5c6b8285488187affb16edcee3600dd14d6098c998410c36a27c4a9dbf1293bc6fad6479d325574d7e9ccca2ccc3fa8fd50cc3a1a2117d50d7cc3a6",
          "sha256": "16cf166e2333fdc5b373d1d37add18e1bab9f135b60c885d02171891bc971808",
          "sha1": "a41039e280fe5c9d7176d5b80172e30daefd90f1",
          "md5": "a964241c2410590986a754f11b4b16b8"
        }
      ]
    }
  ]
}
