{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.4.jar",
          "size": 357368,
          "sha512": "2436a69145283937986648aa8754195471c206de7c185b37a5c46ef3d88dae12e22d8c1bf0589e435d90025a5124dfa75b54342a02d522e7ce296e4fef28b728",
          "sha256": "008244c212f7ed809f7c96fd0021b52b600bff364c05877eef4f3326b4c6ddd0",
          "sha1": "a9d9ba49e2dfbd230b12e614c7c9178eb07ce11d",
          "md5": "b2f4a4ba57bf9154fe078caff0011775"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.4.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.4.jar",
          "size": 357368,
          "sha512": "2436a69145283937986648aa8754195471c206de7c185b37a5c46ef3d88dae12e22d8c1bf0589e435d90025a5124dfa75b54342a02d522e7ce296e4fef28b728",
          "sha256": "008244c212f7ed809f7c96fd0021b52b600bff364c05877eef4f3326b4c6ddd0",
          "sha1": "a9d9ba49e2dfbd230b12e614c7c9178eb07ce11d",
          "md5": "b2f4a4ba57bf9154fe078caff0011775"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.4-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.4-sources.jar",
          "size": 195036,
          "sha512": "e64ae44d16631795718a893c56b5c90053d06188753c755e2a39ef97c5f6d479103d5c24766ca90615ba41ac40dedc8030a52f4983d8dd5768c152ef08bbe2c0",
          "sha256": "a1a4301cdaf18ee588116f2ce5c2386ea9feb6f86011fa6b9ea00919f427fb31",
          "sha1": "9203e83251152cfbbe946b04181dfecea8d66b61",
          "md5": "50153a6ea06ceef97ed75f80f33a0ee7"
        }
      ]
    }
  ]
}
