{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2502.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.2.jar",
          "size": 393281,
          "sha512": "494ddc49cd8b7080492510edf4521d7924a1aeadd00e71235da709de2be31dd857676304c29e0c31f737783c5e090913568d04aedea662b8a5ee3a09bf235291",
          "sha256": "de0ca44de1ff5d27c9c80739f9fe65317d3548274bbb57a4a93140fa31fa561e",
          "sha1": "63e588e9fe804eaa7af66f7969719da674f0ad4f",
          "md5": "0a162ed95dce3589b384a15080c82752"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.2.jar",
          "size": 393281,
          "sha512": "494ddc49cd8b7080492510edf4521d7924a1aeadd00e71235da709de2be31dd857676304c29e0c31f737783c5e090913568d04aedea662b8a5ee3a09bf235291",
          "sha256": "de0ca44de1ff5d27c9c80739f9fe65317d3548274bbb57a4a93140fa31fa561e",
          "sha1": "63e588e9fe804eaa7af66f7969719da674f0ad4f",
          "md5": "0a162ed95dce3589b384a15080c82752"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.2-sources.jar",
          "size": 198164,
          "sha512": "95a3be289b96bffba2081cf1d7907d46c74f9fc6f41133dbf387f741d353466cafecf5543ad7ec94a5f17777d0fa809f893f89a0be961c1245cdce5515f9f608",
          "sha256": "4700fc936082c0a515c8f945784cb4e205a8a438ec2ade266d1fcc2b16f8018a",
          "sha1": "328992e384b0f1bc6c416d62091e476ae5632fe8",
          "md5": "4556dc3db13e28fb00a46873e882fce7"
        }
      ]
    }
  ]
}
