{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2502.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.1.jar",
          "size": 381871,
          "sha512": "250553898385a6e5226972201882bacd7ff8ae2fe49f036753403b284788fd5588f95c9b30951712a48fd3accdfd7b22493aaf078301622999f90ca1302a1433",
          "sha256": "888329f3529d4e86896f89d66ff3b2796a7f854afe313cc3b3f1b45337301a4e",
          "sha1": "6bf9911e77709a75b78d1bf3dc3a5a76a02e0ffe",
          "md5": "0e3c7999b0eb2a1f3d4048838613837b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.1.jar",
          "size": 381871,
          "sha512": "250553898385a6e5226972201882bacd7ff8ae2fe49f036753403b284788fd5588f95c9b30951712a48fd3accdfd7b22493aaf078301622999f90ca1302a1433",
          "sha256": "888329f3529d4e86896f89d66ff3b2796a7f854afe313cc3b3f1b45337301a4e",
          "sha1": "6bf9911e77709a75b78d1bf3dc3a5a76a02e0ffe",
          "md5": "0e3c7999b0eb2a1f3d4048838613837b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.1-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.1-sources.jar",
          "size": 197668,
          "sha512": "f17aae7764891805bce11efb942aa7aa2daec565f1b0ca996b1caad7d89f7a797675c12bae09783a5f9ffeed47a5a345d52c8704cbd4d073291d8eb1b8dc7525",
          "sha256": "599deefec6b0cac2ecfbf415190f9fde1ca702832dbc519045358795d9f57e9d",
          "sha1": "a07f4f60f63b738ac8a1f16120da164dffb32ea0",
          "md5": "8f76dd02dbfd04d6144b24935a41daf5"
        }
      ]
    }
  ]
}
