{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.7.10.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.1.jar",
          "size": 14235911,
          "sha512": "75d69440637a8aee7b159676ce52c56531e4f5ddf65f28faa930b117676f1829e3efe1d856da51759602341a71d59d6f23761a5e86cfee83e2a0f94ca89abdd9",
          "sha256": "b9ace7d3a19353302de6647f5df6817e9737e3ca89bac3750ac29865b1a14d45",
          "sha1": "9d1c9052b0be6e929555462326ee4a281b472297",
          "md5": "ef229506ed6075358e8c4b596873cc78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.1.jar",
          "size": 14235911,
          "sha512": "75d69440637a8aee7b159676ce52c56531e4f5ddf65f28faa930b117676f1829e3efe1d856da51759602341a71d59d6f23761a5e86cfee83e2a0f94ca89abdd9",
          "sha256": "b9ace7d3a19353302de6647f5df6817e9737e3ca89bac3750ac29865b1a14d45",
          "sha1": "9d1c9052b0be6e929555462326ee4a281b472297",
          "md5": "ef229506ed6075358e8c4b596873cc78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2504.1-sources.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2504.1-sources.jar",
          "size": 13453387,
          "sha512": "75bc72d6efba49418a08bf7f1fc54aba4aadf3001c3725ad3e8877c9afd34152ded14c77e984460629e07498088c90ecddab0fa83a52e8f1e36a99fca3fb2f77",
          "sha256": "02bca905d34db259b0b086442ab4f0e8cecbc24e5df07bc916529b7b54005986",
          "sha1": "786973a3103c4a72d73c03dcbb2f208c0dec2920",
          "md5": "f0a49fe1c2f5dd4778908d0437cfbe8d"
        }
      ]
    }
  ]
}
