{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2507.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.9.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.9.jar",
          "size": 492825,
          "sha512": "1f009a56248b877540ec54816dfe9fe2125caf37a241f7ca0cafe60630f365aabc8d266672670cabb855808b0747f7a9afdf1f93af6205e2e9a810da749d797e",
          "sha256": "7a74a5fd95e6661bcd9ac21d41065a333de5e3f73a131db8fb218a0a8a8b27ce",
          "sha1": "33bb516a343ea1f9db2f070787307e049972212a",
          "md5": "0f41af7b288b5eb07c67c0c1e78828fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.9.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.9.jar",
          "size": 492825,
          "sha512": "1f009a56248b877540ec54816dfe9fe2125caf37a241f7ca0cafe60630f365aabc8d266672670cabb855808b0747f7a9afdf1f93af6205e2e9a810da749d797e",
          "sha256": "7a74a5fd95e6661bcd9ac21d41065a333de5e3f73a131db8fb218a0a8a8b27ce",
          "sha1": "33bb516a343ea1f9db2f070787307e049972212a",
          "md5": "0f41af7b288b5eb07c67c0c1e78828fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.9-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.9-sources.jar",
          "size": 244628,
          "sha512": "0a2837c90fb9745ffc5002a6c760ed88fd79ac9258ded5d7327ca72687db24ef08e38252b99360ca7e2b19376210848ec75c38d42496cac4e9c1d6cf73acc094",
          "sha256": "8d67b59f3701b69048e004b765ce583569ba46887f6489daff2ab5b08a7d53b8",
          "sha1": "57b244ffc5e1a64b69bd8484451bc7874ee85d63",
          "md5": "6816ac7103610d91fa0b2b8d981bffc3"
        }
      ]
    }
  ]
}
