{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2513.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2513.6.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2513.6.jar",
          "size": 706798,
          "sha512": "a6c2b78daa3dcad4a704c5e49a8028af9d5cec67861d890f3c5997f678350032a245f2b0c7830edf5a4cdb891c093763bd7be388efcd62572bdd9a30a193aed3",
          "sha256": "1adaa1532c28fe31484797a783886d169898714ad1346543e0afb6ac98f4c6b2",
          "sha1": "14d235906c1b409b4816ec15ed2b9b5c5af4672d",
          "md5": "79e0175310764d376bdd569537592754"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2513.6.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2513.6.jar",
          "size": 706798,
          "sha512": "a6c2b78daa3dcad4a704c5e49a8028af9d5cec67861d890f3c5997f678350032a245f2b0c7830edf5a4cdb891c093763bd7be388efcd62572bdd9a30a193aed3",
          "sha256": "1adaa1532c28fe31484797a783886d169898714ad1346543e0afb6ac98f4c6b2",
          "sha1": "14d235906c1b409b4816ec15ed2b9b5c5af4672d",
          "md5": "79e0175310764d376bdd569537592754"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2513.6-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2513.6-sources.jar",
          "size": 251511,
          "sha512": "a80a8ac76f76fa6792711c1d7b37b5db2730a4720e835133941ca08215dc0c7ff792dafa5ec10eff4595e591a6878a39acdb7c5078903bbab0b59553d341b345",
          "sha256": "8b04632ffc12061d435d6c54ab82b0a4ee20e8dd58d6d0cac158decd94f7bdce",
          "sha1": "8ccf3a40ca6340e7e6fa5c6c2e12dc0d1a155b85",
          "md5": "7e551e24691dc74b48a5ab9dd896dbbb"
        }
      ]
    }
  ]
}
