{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.13.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.13.jar",
          "size": 481718,
          "sha512": "3716d4ca52e4b26734554e00c712d3bf2172f4ee43e56fa70d638dda60e81a2a14bf84226978534ac96019454c796434e13279a36fe0cba20d48bd72da4dc5b9",
          "sha256": "09af0c51d2ea81a8748166b6b3191d2ab1b76a928f8dc5bfd26ba01155da9d85",
          "sha1": "777e2dbcbc8405389b76dd393a4f8a5ff7c4d46c",
          "md5": "1da5ee60e6c419d01def0e6d3e651eb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.13.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.13.jar",
          "size": 481718,
          "sha512": "3716d4ca52e4b26734554e00c712d3bf2172f4ee43e56fa70d638dda60e81a2a14bf84226978534ac96019454c796434e13279a36fe0cba20d48bd72da4dc5b9",
          "sha256": "09af0c51d2ea81a8748166b6b3191d2ab1b76a928f8dc5bfd26ba01155da9d85",
          "sha1": "777e2dbcbc8405389b76dd393a4f8a5ff7c4d46c",
          "md5": "1da5ee60e6c419d01def0e6d3e651eb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.13-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.13-sources.jar",
          "size": 246509,
          "sha512": "a2899602152a6e0e0288bb3c0be5f27281fe08a02b4a65928496ab563fd49e27cd48fb7ceaef1e5d421baafb3bbb327d44e7dfeb05d9de08c5f978b4ce399bf9",
          "sha256": "6316e927e6d5344b129d96c5ede6050c444174e71893a1cc4a585d968d3a5b3c",
          "sha1": "a0e1c4f1eec5025c05dd6587b31a52cc6dd16b7b",
          "md5": "9dfe686844872453a4276ce1ea958cde"
        }
      ]
    }
  ]
}
