{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.9.jar",
          "size": 374682,
          "sha512": "37ae4c63f7b2008f0cd173d3fd6adc00f358d285aee90f9562c8bc7ac1f0c584db1005f75d78ff70e6736dc07c4840ea8f0a4428256b1c3dd6dc6acc75448f62",
          "sha256": "7774c18d6a15fa88cd5b02f2a092796f4b3ea3e44a4532cd3eab9f115413dbfd",
          "sha1": "a687b59b4f2c2f5008d3ec5ede5735ac8fc0c496",
          "md5": "6a4b496cf05f8d597b110bb392ef632e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.9.jar",
          "size": 374682,
          "sha512": "37ae4c63f7b2008f0cd173d3fd6adc00f358d285aee90f9562c8bc7ac1f0c584db1005f75d78ff70e6736dc07c4840ea8f0a4428256b1c3dd6dc6acc75448f62",
          "sha256": "7774c18d6a15fa88cd5b02f2a092796f4b3ea3e44a4532cd3eab9f115413dbfd",
          "sha1": "a687b59b4f2c2f5008d3ec5ede5735ac8fc0c496",
          "md5": "6a4b496cf05f8d597b110bb392ef632e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.9-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.9-sources.jar",
          "size": 196940,
          "sha512": "57ef819ad3e7e68e72dd76aa902cba9f26fb93a9568854e49a90eafadc55e24c1e2538f76f1c5ff57c84d2319927baaa8d09c16de7d5b918699f8c6520b09090",
          "sha256": "0987cf2350cdaf62eca5b3892a6e4881192d575e92f3f1e70bb8dfc91200e607",
          "sha1": "e96f82995054a2d6e8073a49886ba60fcede8955",
          "md5": "b0e5e568db5d27e01d5fbf570d7410d9"
        }
      ]
    }
  ]
}
