{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.2.jar",
          "size": 480862,
          "sha512": "da87a7c56eeea125e867b653ce172fd633debacb7efd13a3b896c8e57a43f1fbd3e89e38ad649beb0030615af6c2e6abd25b4b4d9cae403cd3c64d85f38e515a",
          "sha256": "d520b0244ec3f5661760260b90f028906a8bc6e7258772e1eaade493b1cd2875",
          "sha1": "9e3e0456ec72f4008d6a5760855283b3762af1a6",
          "md5": "2904c0a122dbd7238143cc22be7c4c84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.2.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.2.jar",
          "size": 480862,
          "sha512": "da87a7c56eeea125e867b653ce172fd633debacb7efd13a3b896c8e57a43f1fbd3e89e38ad649beb0030615af6c2e6abd25b4b4d9cae403cd3c64d85f38e515a",
          "sha256": "d520b0244ec3f5661760260b90f028906a8bc6e7258772e1eaade493b1cd2875",
          "sha1": "9e3e0456ec72f4008d6a5760855283b3762af1a6",
          "md5": "2904c0a122dbd7238143cc22be7c4c84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.2-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.2-sources.jar",
          "size": 243968,
          "sha512": "703401f9bc8e99c60d9044c0ee221104ba9f5ed02893996b68e024183c8e94791f9c3ce709c4f664e7687d7ab1ca014f5e3126bae60a5df674719c9de0160e04",
          "sha256": "dbe3c50c572017b75d4dee26259ca5c8e79d3a74013025ac1d79704bf351abaf",
          "sha1": "168bc8f621fe01efacf0cf741591791fdeeb0d11",
          "md5": "84b059f5f864a0c4107993fc99944d8f"
        }
      ]
    }
  ]
}
