{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.10.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.10.jar",
          "size": 481681,
          "sha512": "b1170ef364b6a53279c82b463aa9bd7f1c6dc97f37448be5fefe808282afc5b4a1946dd242ebd5820cbe868b7b80e43448abc06be99690e0cdc0f8837860c2ca",
          "sha256": "eb4799e656ffac2b6db214914879c40ba7e25a78a89d05a58f08b5d113c87e83",
          "sha1": "ef490c51a270371b053307a4c5ef9c577b97c41a",
          "md5": "430a45c5f7729d6cbdb17778078683a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.10.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.10.jar",
          "size": 481681,
          "sha512": "b1170ef364b6a53279c82b463aa9bd7f1c6dc97f37448be5fefe808282afc5b4a1946dd242ebd5820cbe868b7b80e43448abc06be99690e0cdc0f8837860c2ca",
          "sha256": "eb4799e656ffac2b6db214914879c40ba7e25a78a89d05a58f08b5d113c87e83",
          "sha1": "ef490c51a270371b053307a4c5ef9c577b97c41a",
          "md5": "430a45c5f7729d6cbdb17778078683a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.10-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.10-sources.jar",
          "size": 244560,
          "sha512": "994a8dec152e2853702896fc781c8fa04b12935c469cd9ac4f1131d412dc60470152dc8dd7b4d7b30a271f7e3f6047b41d6be4717634a214f98ee884cce511ea",
          "sha256": "84cfb0a191e2e06d2b2654eaf873bc24ec4062a2a86a52b70d9538de7435f33e",
          "sha1": "4d1a47351dc92bc837c9722456a913dafd9c358b",
          "md5": "62cce7beeb95c676f0f3afdfcdee45b9"
        }
      ]
    }
  ]
}
