{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.7.2606.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2606.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2606.0.jar",
          "size": 555063,
          "sha512": "454d7c32593dd56f6d3e3e16774e1de7f844e5019fb4c49e4a524c2a5d1013ec2767861c590d4e480c4189b3731fc9f580ad32e8662cd59466953bcc7ef2e4df",
          "sha256": "a57e888ec243392cd8b7ef49dd5c928e321df150820d54d5cbb83c31c9c8a691",
          "sha1": "d8fd8aacb7be67988b4705956ae0f6a839aabf80",
          "md5": "53c25806be5d0a5520b6a247383cbf41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2606.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2606.0.jar",
          "size": 555063,
          "sha512": "454d7c32593dd56f6d3e3e16774e1de7f844e5019fb4c49e4a524c2a5d1013ec2767861c590d4e480c4189b3731fc9f580ad32e8662cd59466953bcc7ef2e4df",
          "sha256": "a57e888ec243392cd8b7ef49dd5c928e321df150820d54d5cbb83c31c9c8a691",
          "sha1": "d8fd8aacb7be67988b4705956ae0f6a839aabf80",
          "md5": "53c25806be5d0a5520b6a247383cbf41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2606.0-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2606.0-sources.jar",
          "size": 254071,
          "sha512": "67df84b303909c4411f2c9cd4f2362eef1cad8d96f04b98be2119d7c52cc0dd1db74c52cde525e3d563c679be7014f03eabbec048002dbea0cc2be42142819b0",
          "sha256": "0c31c55ca2dd7876a005957500a732850b67302bcb4e45a0e3f2e80ddca2734e",
          "sha1": "1a23b24fbbf358bc923e2fc7f771903739fccd30",
          "md5": "f5b52efa945980e97c6fdb8612f52444"
        }
      ]
    }
  ]
}
