{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2500.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.5.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.5.jar",
          "size": 374630,
          "sha512": "cbb37f16bd384bb2abf28b8b779ce6f92537ac17a463a1fb0169a4f1480a5e1c096c2f5a2256a0f348c32823e745581c52ee45cb4ef8071df1c0084702924847",
          "sha256": "516f3ada5b30fcff325a330b773173d23fab6d0708865cdcb94d021d7e043719",
          "sha1": "b01ba3f13d620cab62a60745207bc6335205de11",
          "md5": "81076b226d477f16b8575d0f97b8be30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.5.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.5.jar",
          "size": 374630,
          "sha512": "cbb37f16bd384bb2abf28b8b779ce6f92537ac17a463a1fb0169a4f1480a5e1c096c2f5a2256a0f348c32823e745581c52ee45cb4ef8071df1c0084702924847",
          "sha256": "516f3ada5b30fcff325a330b773173d23fab6d0708865cdcb94d021d7e043719",
          "sha1": "b01ba3f13d620cab62a60745207bc6335205de11",
          "md5": "81076b226d477f16b8575d0f97b8be30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.5-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.5-sources.jar",
          "size": 195083,
          "sha512": "fae3599b83367e9930ef5444da70d9943450902d5db3d83da308b1e1e6ed6b01092b1ee22dbc08ececc4fcd4f93d78b6b78676be11b85c03898184d961668d66",
          "sha256": "8e4ad5af239a69b75cb395ae03a387dc1264a6e33d26135e5724d9f2f1ad1b4a",
          "sha1": "616f35eb4658984a94dffb157480aab73b4d24b0",
          "md5": "66ac23ca086cb9f59a3d0f1fefd2beb4"
        }
      ]
    }
  ]
}
