{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.14.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.14.jar",
          "size": 450971,
          "sha512": "c01aefff88bd4f572e38e2ae43dd0720542ac193592a7131eb23b5e60fef7533ca012f4ae3c85a77faa0522cf8dc09525f648b10edbcb594a55b9a60424cec8d",
          "sha256": "b0fd2f75eca0de773ae56954eab91c0b56b127b93968e9e97457f8a1831b871f",
          "sha1": "c51616291d6c0d2600967a6845ab05c6551badbc",
          "md5": "d1d2514bbd91250efd342fd28b3e966a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.14.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.14.jar",
          "size": 450971,
          "sha512": "c01aefff88bd4f572e38e2ae43dd0720542ac193592a7131eb23b5e60fef7533ca012f4ae3c85a77faa0522cf8dc09525f648b10edbcb594a55b9a60424cec8d",
          "sha256": "b0fd2f75eca0de773ae56954eab91c0b56b127b93968e9e97457f8a1831b871f",
          "sha1": "c51616291d6c0d2600967a6845ab05c6551badbc",
          "md5": "d1d2514bbd91250efd342fd28b3e966a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.14-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.14-sources.jar",
          "size": 233656,
          "sha512": "70c18fa4e9aa72d040fb77ee902eee4c0f5acf625cb4f83e0a5f064489fec33e4ae59169bc9f75eea59908ded5ebfd0c3261e7011c57936665a6abd132e9fbd2",
          "sha256": "e99f39b9cdda411830a5d748e727746d4be1bcc80e37c38a917bf860cfe555fa",
          "sha1": "0df225c473277df51d26abd4b732fb5a5f204621",
          "md5": "ba75d0485472ddc0c0bb86ce8c54de9a"
        }
      ]
    }
  ]
}
