{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.6.2546.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2546.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2546.0.jar",
          "size": 546711,
          "sha512": "389dbf6eed3e183bbed8e863eec8a26f983f1e0e043eec241ca96432192f47139dc02a6ee072721de8b08e699ba3fbc6c6e5cc1e0e060f64e433bddd855e380b",
          "sha256": "40c732203f15df126d804dccf470eadf5c543c4504bc729808e5ac48e24e3d77",
          "sha1": "95b64ebe0c1398d33fc9cfcdcd4b48929e26e454",
          "md5": "702ae8dbd50c3b6a6305f9f43b1216d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2546.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2546.0.jar",
          "size": 546711,
          "sha512": "389dbf6eed3e183bbed8e863eec8a26f983f1e0e043eec241ca96432192f47139dc02a6ee072721de8b08e699ba3fbc6c6e5cc1e0e060f64e433bddd855e380b",
          "sha256": "40c732203f15df126d804dccf470eadf5c543c4504bc729808e5ac48e24e3d77",
          "sha1": "95b64ebe0c1398d33fc9cfcdcd4b48929e26e454",
          "md5": "702ae8dbd50c3b6a6305f9f43b1216d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.6.2546.0-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.6.2546.0-sources.jar",
          "size": 268862,
          "sha512": "ad19ddcd3cb8870ea76c766a098dd88a1babc65fb247befda425e89755c294c593fe21fcf4b620fcd271427ca1da949544e64d2589eac6e4c3b92d89d866738b",
          "sha256": "352ca923d89d5e63b337eeeda61d9a9209754abdc93e463b3550cbf6c5501380",
          "sha1": "391d032acfbc79d27696736caf26980e3a430b09",
          "md5": "faf22cdf8e39102bf07977b8757b5461"
        }
      ]
    }
  ]
}
