{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.7.10.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.2508.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2508.0.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2508.0.jar",
          "size": 14359667,
          "sha512": "6e62fd61f2a9e1fb09147f89ada3c4178ce0fe6d0d77c9a14a7962ee9cf763fadf5ae2d630f8279865095041816511436d70dd5cbe3608ccabac4313fe888ce6",
          "sha256": "bd62fe12352eb7f0ef43cbaf103ee07db424ce3822fcd491244a302ddfd3163b",
          "sha1": "52258fdc8e2d24eb87252f3e1acd0edbc2cd6cdc",
          "md5": "cd89b9a05882c1bb90374a1de2067746"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.2508.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2508.0.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2508.0.jar",
          "size": 14359667,
          "sha512": "6e62fd61f2a9e1fb09147f89ada3c4178ce0fe6d0d77c9a14a7962ee9cf763fadf5ae2d630f8279865095041816511436d70dd5cbe3608ccabac4313fe888ce6",
          "sha256": "bd62fe12352eb7f0ef43cbaf103ee07db424ce3822fcd491244a302ddfd3163b",
          "sha1": "52258fdc8e2d24eb87252f3e1acd0edbc2cd6cdc",
          "md5": "cd89b9a05882c1bb90374a1de2067746"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2508.0-sources.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2508.0-sources.jar",
          "size": 13543867,
          "sha512": "6b7abe2e41ac193eafff31121dbc8a91349e10fba60cdf3f4a8529dad712b641cdc6ee7ffe893ceaa2aa6632bfdfa106bb825564e31fcad6c454e5e60a4a544e",
          "sha256": "006325ae4cf3b196aced6dc579ca373271d8a76a6ecf5b06bbdeb45e6ddbaadf",
          "sha1": "b152bf767d606a0d72c25edf0a99cdef2339d574",
          "md5": "ebafc1d53f874374c40b304a1cabf311"
        }
      ]
    }
  ]
}
