{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.0.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2516.1.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2516.1.jar",
          "size": 18271769,
          "sha512": "b34b593713500fc8d596581fe21bf6d4ab892018f6a891842b14868c8192c0e5839ddddabb3314e3c09b81d96bdfe244c89eb6a3bb306cfd66db4c90e37450a4",
          "sha256": "929b830b110b548e637ed00d4a3c0d6a2ea32aa6848996cda760695b50df94db",
          "sha1": "a55e758116b07ce117b65f8d81f2d695c888b92e",
          "md5": "da7ecc34b12379ee1db9f5229006795c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2516.1.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2516.1.jar",
          "size": 18271769,
          "sha512": "b34b593713500fc8d596581fe21bf6d4ab892018f6a891842b14868c8192c0e5839ddddabb3314e3c09b81d96bdfe244c89eb6a3bb306cfd66db4c90e37450a4",
          "sha256": "929b830b110b548e637ed00d4a3c0d6a2ea32aa6848996cda760695b50df94db",
          "sha1": "a55e758116b07ce117b65f8d81f2d695c888b92e",
          "md5": "da7ecc34b12379ee1db9f5229006795c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2516.1-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2516.1-sources.jar",
          "size": 17433224,
          "sha512": "2a1cfc2dff345d848fa6f33745efcf0bd24447165e6a00daa03009e1af4b8471577d2c6bcc0ece3d0730d2a197da6adf72d07b614877efbeb768e666dd536e2e",
          "sha256": "e2b80ee704050f402a4c46958e9f8498bf3e61a017a83dd20d6ea7544d678281",
          "sha1": "2319a14126fece6d22f101d916c5198d59d340d8",
          "md5": "bf01c896836a6a0ffa2e80e672e190af"
        }
      ]
    }
  ]
}
