{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.21.1-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.3.jar",
          "size": 646438,
          "sha512": "1a34aa9bb01cddd47fcc7338734dd0f5237e55b409052574957754582097592b3ec825a6047ebd33bd2d40d895f942e90bb23b9d8beda4be5ee26df314935775",
          "sha256": "c559902ad24ba547b75ca0f67c97e2996b8ff5d7c8f9650a48802849d7552f38",
          "sha1": "b9529a4b22b8c410b64c4d89ef0cce367425115c",
          "md5": "f4b383996590869b0d7f129338c46371"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.3.jar",
          "size": 646438,
          "sha512": "1a34aa9bb01cddd47fcc7338734dd0f5237e55b409052574957754582097592b3ec825a6047ebd33bd2d40d895f942e90bb23b9d8beda4be5ee26df314935775",
          "sha256": "c559902ad24ba547b75ca0f67c97e2996b8ff5d7c8f9650a48802849d7552f38",
          "sha1": "b9529a4b22b8c410b64c4d89ef0cce367425115c",
          "md5": "f4b383996590869b0d7f129338c46371"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2516.3-sources.jar",
          "size": 582917,
          "sha512": "e181d2adf6e067d6f544f1ced5307e7933aeb441eec88e854b49ba05cd5c4645984ad3aa5542ee0bdda0320b34661e4f30c5d6ec7df88c58e3b9fd97ac4953ce",
          "sha256": "7d4eb26ed8e7f6620194d3c9b44568c981d48d7434649969e9e2b7f1a0544b24",
          "sha1": "a16bbc7b0a11119fcc164a4abd73cfd0cb3be423",
          "md5": "1133aabc5f32f0ade2fde9a0d6f20e5c"
        }
      ]
    }
  ]
}
