{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "size": 710655,
          "sha512": "9748c18e1f001a1a16c47877d2aa77d6e4af50f3041db395dc6acf3a10915ba2621d62a2503b83138a959e3eb107c6047be4581393b0b797921477510a2d425d",
          "sha256": "ac2178568c097a20e47b2ba9cf2cbbbc7405470ff1814b5cb17e33c757892e84",
          "sha1": "0adc15d55f311ea668b3bb6a5eca98c03861def9",
          "md5": "225cd7ccd6eca5f13776f0c0092b70d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "size": 710655,
          "sha512": "9748c18e1f001a1a16c47877d2aa77d6e4af50f3041db395dc6acf3a10915ba2621d62a2503b83138a959e3eb107c6047be4581393b0b797921477510a2d425d",
          "sha256": "ac2178568c097a20e47b2ba9cf2cbbbc7405470ff1814b5cb17e33c757892e84",
          "sha1": "0adc15d55f311ea668b3bb6a5eca98c03861def9",
          "md5": "225cd7ccd6eca5f13776f0c0092b70d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.1-sources.jar",
          "size": 253451,
          "sha512": "fefcca1aa98ff0d3866a500952a8754d7cc50ea29968d16b9d0fbf7663ac8f67e9abc30dba7ff66756f0bd8da7610439a50f2c2976dacf48d9e46ef14e5dac96",
          "sha256": "59b748876f3472c60d9640a3628e1bda260b70db98b7ac730245c885a29f2bba",
          "sha1": "0178b91bfad0a9f1593d2d9d9d09b954af1c1485",
          "md5": "3d457e1a41238961fded9f181317804d"
        }
      ]
    }
  ]
}
