{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "size": 710900,
          "sha512": "3b564179501320432f0931eff3dc3ab8714597eca04365bf57190b3f38539b1586c8ba681e459d4dcd70ae756b818906edd79a44d579a7414c52430452f19392",
          "sha256": "4802214ac75432f9e0c5f911956e999b115c73af57e9c623b5d68a5c689e55f1",
          "sha1": "d4d6478dae06661f6ebf3dcd24ea775fd6a79e67",
          "md5": "3da71a3687955b4e128f24c2fe0fe6c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.1.jar",
          "size": 710900,
          "sha512": "3b564179501320432f0931eff3dc3ab8714597eca04365bf57190b3f38539b1586c8ba681e459d4dcd70ae756b818906edd79a44d579a7414c52430452f19392",
          "sha256": "4802214ac75432f9e0c5f911956e999b115c73af57e9c623b5d68a5c689e55f1",
          "sha1": "d4d6478dae06661f6ebf3dcd24ea775fd6a79e67",
          "md5": "3da71a3687955b4e128f24c2fe0fe6c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.1-sources.jar",
          "size": 253531,
          "sha512": "bfa0310ce58ef0263c22d9a2982077da7b54b525db31ce49c5afe4a403472d620a973e2648176a026db0e2886629a2ac5c5d54db315f9d69be3fc8fd801ef62a",
          "sha256": "25f6073af54962f63b257746b6ab7e15c805277c135fffbc5cea14145e15c3d6",
          "sha1": "98a418be18bc0344602258f45115e29e94ab4235",
          "md5": "88afe3694c4c8df0c38b778f2e6293f4"
        }
      ]
    }
  ]
}
