{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.0.jar",
          "size": 348952,
          "sha512": "bda34db2fd676fc18bc1a76ea1c722044ece8441d9cb8eceb9249825e215414dc75c1971f7ca19e56918da1ba31f05df7922752713237887196347bfb0c71a11",
          "sha256": "a052dc252c05bbfee4f573f0427bce1e32da8c4f08030113d4c5f91efd675b45",
          "sha1": "27764a8966ce1778ea85b420988e824cab979e28",
          "md5": "6dacd42996e56c6f70f3ba3e46a3affb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.0.jar",
          "size": 348952,
          "sha512": "bda34db2fd676fc18bc1a76ea1c722044ece8441d9cb8eceb9249825e215414dc75c1971f7ca19e56918da1ba31f05df7922752713237887196347bfb0c71a11",
          "sha256": "a052dc252c05bbfee4f573f0427bce1e32da8c4f08030113d4c5f91efd675b45",
          "sha1": "27764a8966ce1778ea85b420988e824cab979e28",
          "md5": "6dacd42996e56c6f70f3ba3e46a3affb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.0-sources.jar",
          "size": 193411,
          "sha512": "7ce8850fe3badabedf9da2824c5a74a021645486060d79f49acbe913d43d65c36de4ca8ee3fc2a1ab48afad5e861854a5fae7ddafddaa5dd7d33be6ae17faa39",
          "sha256": "e6e2fdb32e04ebd43f69cf382ee9a5aff8119c380e52dc99c815a013d8e3238b",
          "sha1": "fb6e531e40ab9d36b6583ca3a61fc38bf67dbd68",
          "md5": "8a2a53305ae0bf57db48dfaf8178664e"
        }
      ]
    }
  ]
}
