{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2504.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2504.7.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2504.7.jar",
          "size": 475514,
          "sha512": "5cb308fafe863eaff8958725c2e9d188ecfe78552c4de4437ddfa1445feaa97dfa951a423964f30fcaec7b5cbaa6334aea75f7952ff07f3d63f88dd4d5fe3de2",
          "sha256": "a96fd0641b68af3203baf27735a703a88f7066b74b8d7c44771df988117d13a1",
          "sha1": "15047018c528f868500e9447df3af0dca9a487cc",
          "md5": "709d7974b42a55d791489a250628352a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2504.7.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2504.7.jar",
          "size": 475514,
          "sha512": "5cb308fafe863eaff8958725c2e9d188ecfe78552c4de4437ddfa1445feaa97dfa951a423964f30fcaec7b5cbaa6334aea75f7952ff07f3d63f88dd4d5fe3de2",
          "sha256": "a96fd0641b68af3203baf27735a703a88f7066b74b8d7c44771df988117d13a1",
          "sha1": "15047018c528f868500e9447df3af0dca9a487cc",
          "md5": "709d7974b42a55d791489a250628352a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2504.7-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2504.7-sources.jar",
          "size": 237068,
          "sha512": "776bfc65cb2aab204c694814e9cd91735390daed0ff0bb58c0b6cbf180b1e54b0787843385f7ea4477afaa534649295fec7d4038434be08e2cdbcaef5efc2c86",
          "sha256": "3bcc138fd95ed5106617ff09c5411d84190fa147ce59603261f403b4fda6bca9",
          "sha1": "d69a4fb828d2e661aded411bb4cac57e6deebf01",
          "md5": "9c15fac78ceec38d851a2fcd5f50e514"
        }
      ]
    }
  ]
}
