{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge-1.20.4",
    "version": "2.2.2500.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.0.jar",
          "size": 338821,
          "sha512": "e370c1fe9e018808d3273a7dc1e531a7d3ec61fc9e5a442001a9ceec9f87170b108215c6700c3882b48b3e007dc3c900d2812ed329addedee7c88ad57fb26fd5",
          "sha256": "d26c84a69d0b5601dc565a330b478e89e367a372fa56128758c8b5ae499ad490",
          "sha1": "7105c3c3c8440e0005b026df3828093bdd5a5528",
          "md5": "7a0d1a8dfaa884b3509389bf51fed3ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.0.jar",
          "size": 338821,
          "sha512": "e370c1fe9e018808d3273a7dc1e531a7d3ec61fc9e5a442001a9ceec9f87170b108215c6700c3882b48b3e007dc3c900d2812ed329addedee7c88ad57fb26fd5",
          "sha256": "d26c84a69d0b5601dc565a330b478e89e367a372fa56128758c8b5ae499ad490",
          "sha1": "7105c3c3c8440e0005b026df3828093bdd5a5528",
          "md5": "7a0d1a8dfaa884b3509389bf51fed3ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.0-sources.jar",
          "size": 190904,
          "sha512": "2ccc3c1361f546b11d082e4463db3cacb41188bc2b8d28443965d889d0880eaaa4f9b04585ab82d0eddff563d2ffbfad4e844eca3af7f4e48f13c27056c4740f",
          "sha256": "cbefee9f014286bda6ca2f629e8b198a40f88c952fd0244549e0414571a15c91",
          "sha1": "a232fbe36e140b09629705a74daf5f05f5f8f65a",
          "md5": "7a10430cb841566b44d513a7a9aeb88d"
        }
      ]
    }
  ]
}
