{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.11-2.2.7.2606.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2606.1.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2606.1.jar",
          "size": 555941,
          "sha512": "d6adc1caa3b9e81284b48abfd357d06fc9af4b8708da2c62f2c0d3af68e761288ffe334a24e101ac0137c918b94fff7c62715b040f966bdd8f7d91086225df97",
          "sha256": "6f3876a5a8e8cd5e4279ebab6da90f902ec2da4bbc19e7ecf641c00b6fce2ff0",
          "sha1": "1bbe3d1fcc198e462c83c88dfcda599476e339b8",
          "md5": "f15e1597cae957ac27f16fc3c1e4f0c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2606.1.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2606.1.jar",
          "size": 555941,
          "sha512": "d6adc1caa3b9e81284b48abfd357d06fc9af4b8708da2c62f2c0d3af68e761288ffe334a24e101ac0137c918b94fff7c62715b040f966bdd8f7d91086225df97",
          "sha256": "6f3876a5a8e8cd5e4279ebab6da90f902ec2da4bbc19e7ecf641c00b6fce2ff0",
          "sha1": "1bbe3d1fcc198e462c83c88dfcda599476e339b8",
          "md5": "f15e1597cae957ac27f16fc3c1e4f0c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2606.1-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2606.1-sources.jar",
          "size": 256520,
          "sha512": "8eab41379a1813fea2edb8f3613ff4f7a460789efd58976920e0e3bc39b7c5c72f1c6c84e363cd5d3783c67896e0a7180c7c7414bfb9fb13801655e2998d493f",
          "sha256": "351a5ec6383f3317079091268597274f934b3fdbb958574a47b0bee739cd6908",
          "sha1": "8b3110336f6cc7751bcb7b0cb98cf82f03395f98",
          "md5": "f6287bb1fa17b8b792cf3fbab5609949"
        }
      ]
    }
  ]
}
