{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.2.jar",
          "size": 494753,
          "sha512": "a9e0ba0f644106c1fc656cb8d9494975ef3bf86c68f852bb0d5bd890334b462a763cfafa178eb156331f3ae387a166c0608abb72428874b5be9639a83724a106",
          "sha256": "95bdb842d74afa2199e9d32cce8c8b2eb4dae67b7acbfe2bedb7eba7325c903d",
          "sha1": "8124935313c88a59894fdc826a143cbcfb46a6f9",
          "md5": "32901b3e89ba46661cd4cc38ac768d56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.2.jar",
          "size": 494753,
          "sha512": "a9e0ba0f644106c1fc656cb8d9494975ef3bf86c68f852bb0d5bd890334b462a763cfafa178eb156331f3ae387a166c0608abb72428874b5be9639a83724a106",
          "sha256": "95bdb842d74afa2199e9d32cce8c8b2eb4dae67b7acbfe2bedb7eba7325c903d",
          "sha1": "8124935313c88a59894fdc826a143cbcfb46a6f9",
          "md5": "32901b3e89ba46661cd4cc38ac768d56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.2-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.2-sources.jar",
          "size": 244159,
          "sha512": "62dc5acfff3258eb43f8af406afc7318fca726f52533dd8a03efd8133e0e406b6d210f236d595646dfebad182fd9beaa2e66c873d2ab3bce6bcdd0a935abd4df",
          "sha256": "2d290e40f10695a50c83c0d7f89ed84d7f2699b9f9129b90e33bda6ba3844192",
          "sha1": "9fdca76c3b7bd67c59047e4f6e626d1f5915d190",
          "md5": "abc142275fa2e0fc1ee7190c5bd43c78"
        }
      ]
    }
  ]
}
