{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2516.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.3.jar",
          "size": 18292282,
          "sha512": "1c6590a7cf96b106636d3ce88b985dd2ef2db97c55f5ee211b87ab3770b09b23cc85931efaf8ab6f31fe350d107f5587945c53dafb8cf69dbead24fd083c466e",
          "sha256": "8f005cd0d68f68bec309fbc18345fd805729c197a9fa8ab636825b0159ce44bc",
          "sha1": "62ce42fbac9fc44e0ee2c602fffc82beafaa42df",
          "md5": "1a4f1ad44f44a31554769172036d37d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.3.jar",
          "size": 18292282,
          "sha512": "1c6590a7cf96b106636d3ce88b985dd2ef2db97c55f5ee211b87ab3770b09b23cc85931efaf8ab6f31fe350d107f5587945c53dafb8cf69dbead24fd083c466e",
          "sha256": "8f005cd0d68f68bec309fbc18345fd805729c197a9fa8ab636825b0159ce44bc",
          "sha1": "62ce42fbac9fc44e0ee2c602fffc82beafaa42df",
          "md5": "1a4f1ad44f44a31554769172036d37d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.3-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.3-sources.jar",
          "size": 17422371,
          "sha512": "073b0e0219f0d175b6d172c58e79162ac8c555b5448b4c6409c678107f9f0d1b24edab219ebfbd5e6aafc3942b45eced7c892b4021300a3e80369eda9b727f41",
          "sha256": "c41ec2ea6c4c62642a77c7f1ec7fdb2cb71cf331ff60331114b47801d6d18e80",
          "sha1": "d4a59095613c761d9b56a1be67fde6f914c8f8d5",
          "md5": "ce8de7c0e7b2087fd6ed7185ad15018e"
        }
      ]
    }
  ]
}
