{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.1.jar",
          "size": 465573,
          "sha512": "993864ae86b962201296307a7be0677aa4600039919749bbbf521a7da4fd80e744ab43e1aa45f8188103d6f91c4d18b5ceae44288756b44dc753e36de4bd808d",
          "sha256": "63b96da2a68609857b404accb12225ee6a69f355873569ed6a7c16222533813c",
          "sha1": "4bc81840a3d6e9ebc55a5b164dd162cd2159c51f",
          "md5": "c944713c51c26b287aca57c6ee75a331"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.1.jar",
          "size": 465573,
          "sha512": "993864ae86b962201296307a7be0677aa4600039919749bbbf521a7da4fd80e744ab43e1aa45f8188103d6f91c4d18b5ceae44288756b44dc753e36de4bd808d",
          "sha256": "63b96da2a68609857b404accb12225ee6a69f355873569ed6a7c16222533813c",
          "sha1": "4bc81840a3d6e9ebc55a5b164dd162cd2159c51f",
          "md5": "c944713c51c26b287aca57c6ee75a331"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.1-sources.jar",
          "size": 232169,
          "sha512": "ddde4c17334188097ac0f4b8331cd8e454cf7f40e4b466c7e18a70c511d20aa4a4462e4e5f521096065dd757b1888920d2127c46877672e36ac1884e126ed724",
          "sha256": "2fbdddd4d29ee48e790a41d8b51b2d159724e81d78cf2e2d520942d4a12733d9",
          "sha1": "b01d0467cae72b7abb34eeabfb73e6ac5d3f546b",
          "md5": "696b674c918cd085ef65e68c03ce27a8"
        }
      ]
    }
  ]
}
