{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2500.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.1.jar",
          "size": 359161,
          "sha512": "6ed3ce51ed912400bd6098d8c9c6c6e7d407ed7c802a2bcf8643d8e711e8edf6639145b564c286e2e120ad8e3cb547e112a8b96408a8d35d782b1c09f6f7f4db",
          "sha256": "a59f7de78b4c1fa7c0895f1ce11a27862f6d419d554e462d26531b0e05df8419",
          "sha1": "8dc30fddce3526bf8a64f9e035583d6da40ea3d8",
          "md5": "faa0c41bb091a016ce04e5b69bed0749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.1.jar",
          "size": 359161,
          "sha512": "6ed3ce51ed912400bd6098d8c9c6c6e7d407ed7c802a2bcf8643d8e711e8edf6639145b564c286e2e120ad8e3cb547e112a8b96408a8d35d782b1c09f6f7f4db",
          "sha256": "a59f7de78b4c1fa7c0895f1ce11a27862f6d419d554e462d26531b0e05df8419",
          "sha1": "8dc30fddce3526bf8a64f9e035583d6da40ea3d8",
          "md5": "faa0c41bb091a016ce04e5b69bed0749"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.1-sources.jar",
          "size": 191248,
          "sha512": "86a4bd686a89b207667cb0abf66c0674d92bf5edb14d4144c1d29f5953b909b84c12d188d3840cb018bdab76ee7b4a51dd707a93eb1612e8abf59e35cc34ca17",
          "sha256": "968e5b307b5a14332cff3e870459c346f2287afebaf4250164614e81257013d7",
          "sha1": "d93f4f6244df54e8c3d09aa977b6a7874f0bfe32",
          "md5": "d8a5ec1795e3df3b2d71ebbe038c7f13"
        }
      ]
    }
  ]
}
