{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.7.10.2504.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2504.2.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2504.2.jar",
          "size": 14253682,
          "sha512": "8ef44310d62d26252e7d077b081a55341512deddae820713f6dd58258017ddcc2084f65277e94c29d65160ed242b95878edc9e9f14d4d9283817c2e0c0b77a4c",
          "sha256": "0488f1fc0be48da6d38b0b2f85969365842b921961df474d0a496ce8393046e1",
          "sha1": "440904e98db496be0741c5195f459de6e8bf2ec3",
          "md5": "db1af7c7170fe5426e8dff03b2aea82b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2504.2.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2504.2.jar",
          "size": 14253682,
          "sha512": "8ef44310d62d26252e7d077b081a55341512deddae820713f6dd58258017ddcc2084f65277e94c29d65160ed242b95878edc9e9f14d4d9283817c2e0c0b77a4c",
          "sha256": "0488f1fc0be48da6d38b0b2f85969365842b921961df474d0a496ce8393046e1",
          "sha1": "440904e98db496be0741c5195f459de6e8bf2ec3",
          "md5": "db1af7c7170fe5426e8dff03b2aea82b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2504.2-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2504.2-sources.jar",
          "size": 13449241,
          "sha512": "23e25a36b52adb993d6647eec30421b3d72d4447ee7ae7acd451cdb69d47c5516462fda0a384c2893708d81f567af8159c02d246bcb6169fc8d9e28edee4d05f",
          "sha256": "2c859a3c40285179b9f98daa9a541a959d2f9f1f85b94ea24cf3cb1105062467",
          "sha1": "2b16bef8862b354c964839e8a03f84785185a181",
          "md5": "85df8e1234d919cc32176b67bb0af8af"
        }
      ]
    }
  ]
}
