{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2514.2.jar",
          "size": 534658,
          "sha512": "213b5aeb0dc56feda916fcef4fab68d639b198ddf48d063109767ffefeaae3e96fe4439faf5999bdbf6d376e495494347ae1909706516faa4c9b39f8c4db077a",
          "sha256": "f4dd5aee68943cecfdcaa1e9ed4acb4e4f0744eff5f906f55b71ceaf7f9f8096",
          "sha1": "f0d0cc5a0277e49072e185ad3c935b2605805c52",
          "md5": "7ba8ecb8c064863166078c59650079f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2514.2.jar",
          "size": 534658,
          "sha512": "213b5aeb0dc56feda916fcef4fab68d639b198ddf48d063109767ffefeaae3e96fe4439faf5999bdbf6d376e495494347ae1909706516faa4c9b39f8c4db077a",
          "sha256": "f4dd5aee68943cecfdcaa1e9ed4acb4e4f0744eff5f906f55b71ceaf7f9f8096",
          "sha1": "f0d0cc5a0277e49072e185ad3c935b2605805c52",
          "md5": "7ba8ecb8c064863166078c59650079f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2514.2-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2514.2-sources.jar",
          "size": 250876,
          "sha512": "a6df738242f2745143d06b9a752ca986753ca25c3dd9ca09633abefa1e749f84b2ff666cf1a6e61f05a800558d02697dd7bb07afe41c3fbe06c72073bf780f91",
          "sha256": "ab18398003c70aeca40911205fa398ad079deee0edb5d11a3805ff5bd1024ce6",
          "sha1": "24b5330e712186f274a2c39d72752f18fa783a43",
          "md5": "17845066a094f1c7a58b4be750eb7868"
        }
      ]
    }
  ]
}
