{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.5.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.5.jar",
          "size": 495261,
          "sha512": "56573bf0f588c5d340beb61f419a63182efade7286b736a76a746eec17151651fb45e55ec28990f5998a10f754bc9715ddad7f46ef057fdaf6beaa2ea9563bc0",
          "sha256": "4f2c17156c88e4c0befdaf5679c2de72e00379e4fd859a5cadf0bb7847c23a3d",
          "sha1": "5917e41465b3571933c0a21dbcb8dc1e08452304",
          "md5": "e2c9b5398229d3d4a159ff5f52b0751b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.5.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.5.jar",
          "size": 495261,
          "sha512": "56573bf0f588c5d340beb61f419a63182efade7286b736a76a746eec17151651fb45e55ec28990f5998a10f754bc9715ddad7f46ef057fdaf6beaa2ea9563bc0",
          "sha256": "4f2c17156c88e4c0befdaf5679c2de72e00379e4fd859a5cadf0bb7847c23a3d",
          "sha1": "5917e41465b3571933c0a21dbcb8dc1e08452304",
          "md5": "e2c9b5398229d3d4a159ff5f52b0751b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.5-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.5-sources.jar",
          "size": 244551,
          "sha512": "f93f4d316e4106e7b3f01fd55220a9dc91a9c52d41b6ba089c84e8c5151097b342b660d2f79811980eb8eacd970dc937cace85a48c0cd4e682bcb5cb83f86f29",
          "sha256": "0b32c042a9fb08104a265744f3fb14ab5b68a9a24447bc1f44647821d761975a",
          "sha1": "4a01a884215b17e9b52fa08364f6f6310c3883ed",
          "md5": "8f2029bf13489fbcf6207b84f9d16345"
        }
      ]
    }
  ]
}
