{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2501.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.9.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.9.jar",
          "size": 361672,
          "sha512": "f41f4f2bb09e21aba09020315943e407b498beb83e2135556a612083378ee4e5e70dfbb44af2edb55b4a08e362259cbf86ee47cd3aa013b20a8ca2b4f1529969",
          "sha256": "06b0e0d93ec5fbddd6f1c26838c771d3229ddbcc3aef359de4bfaba1b7a7f10f",
          "sha1": "809685b0f656e76d475721a6695ef5173d45db49",
          "md5": "4778cf7825c04728457c97546ec901e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.9.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.9.jar",
          "size": 361672,
          "sha512": "f41f4f2bb09e21aba09020315943e407b498beb83e2135556a612083378ee4e5e70dfbb44af2edb55b4a08e362259cbf86ee47cd3aa013b20a8ca2b4f1529969",
          "sha256": "06b0e0d93ec5fbddd6f1c26838c771d3229ddbcc3aef359de4bfaba1b7a7f10f",
          "sha1": "809685b0f656e76d475721a6695ef5173d45db49",
          "md5": "4778cf7825c04728457c97546ec901e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.9-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.9-sources.jar",
          "size": 196657,
          "sha512": "75abd0ac92908f00ea8b9542cc209854df0962593abed3b9862deb0170196103a53f170216010ccea9a661912a6f5ef2c7e6f0a57b1679ec093bce4785608ccf",
          "sha256": "6bc173f826f02965aa924f523bd4252df9bd9d8f96d7c74c6a87b9f52eadd3e5",
          "sha1": "df2b6a26821847761f12ccd0ac9dabdc0f1afd4f",
          "md5": "69414fa27448c62b7a545bcd289bcb7b"
        }
      ]
    }
  ]
}
