{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2515.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2515.0.jar",
          "size": 18276632,
          "sha512": "696928779e674bf5745fb41b1bf35ddc75b7684b64a4247863d7911edde5a6f223a342cedaa060ef05a23e3c0c337d44e92c3ab99883ae4bfbf91b96c92dc590",
          "sha256": "9d12ec5b499915017d6a5c91be56bb7d70a82fac06fa8de0a743134d5e05fde8",
          "sha1": "6f114972684e7061d4ce19973057ced6bde3eb26",
          "md5": "15c50c46424d9a76c6e433f2273c2a42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2515.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2515.0.jar",
          "size": 18276632,
          "sha512": "696928779e674bf5745fb41b1bf35ddc75b7684b64a4247863d7911edde5a6f223a342cedaa060ef05a23e3c0c337d44e92c3ab99883ae4bfbf91b96c92dc590",
          "sha256": "9d12ec5b499915017d6a5c91be56bb7d70a82fac06fa8de0a743134d5e05fde8",
          "sha1": "6f114972684e7061d4ce19973057ced6bde3eb26",
          "md5": "15c50c46424d9a76c6e433f2273c2a42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2515.0-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2515.0-sources.jar",
          "size": 17438818,
          "sha512": "63f5fb0a738642b25a9aeb4aaa5fac6de0a90d342d9fc974b2745b7c69615d6dd339c46d584316a2f66c49ccd0725fc0a5b14546f789370ec55bee3e09cf80c5",
          "sha256": "819a76a1d12122a1d4e08bbcae0f0ad3a96159859b86b28315c0152a059f6fc9",
          "sha1": "10ab152a660b50a4defe919b3554b474c4e139ae",
          "md5": "94b4d5364366ddf813966e7865997c68"
        }
      ]
    }
  ]
}
