{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.4.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.4.jar",
          "size": 529489,
          "sha512": "4444a51dadec607a190aefd79ec5cba450d6f7d14a7ff07c72cd291f6c2564d742a16f2a793cbf775ca0ffaf255e34e5a9a2a4a6e45028e94fb59eec13266a98",
          "sha256": "345151654a799d08dbacf1bfe948a15ee26aa6f33b8b812dcc70887baa963075",
          "sha1": "a12e2dfd5426c3e54125afe2e476381ff14fd751",
          "md5": "f06ed796832f88aaa59c1174403cca88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.4.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.4.jar",
          "size": 529489,
          "sha512": "4444a51dadec607a190aefd79ec5cba450d6f7d14a7ff07c72cd291f6c2564d742a16f2a793cbf775ca0ffaf255e34e5a9a2a4a6e45028e94fb59eec13266a98",
          "sha256": "345151654a799d08dbacf1bfe948a15ee26aa6f33b8b812dcc70887baa963075",
          "sha1": "a12e2dfd5426c3e54125afe2e476381ff14fd751",
          "md5": "f06ed796832f88aaa59c1174403cca88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.4-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.4-sources.jar",
          "size": 255041,
          "sha512": "29aa1d53d1dda3d3bd75a5c3e030ada1a824839676681f1bdc7ea8e8a5e5c4572d5fa33459d09b041c174100181cd772d02e54dc816b33c9841032cec0d67c1f",
          "sha256": "ca6636719c824682ef8d5bd25ea878090e6e0cfc5c7042e2023aeb05036275a2",
          "sha1": "74e018ae31f91a0fee69ee021e2af5c21590dd31",
          "md5": "122259e38de573faa80b33d943236ef2"
        }
      ]
    }
  ]
}
