{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2513.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.1.jar",
          "size": 683076,
          "sha512": "ab5049eead8410e8a00e161dfe12537d86cb6c9030ae6c133be36f9cc8d1d78000d875e4ea20439e7dd93f11c5ea3b252a8767ae6b5769e9280381feddc1ad71",
          "sha256": "a0567d4b636b71a1b270c37a4d79a60df677a0badae6166743d25341178b9086",
          "sha1": "87b32d2e044367375a32457fd430fecc816561f6",
          "md5": "2febf7cec34cce4c853d173e1568e8ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.1.jar",
          "size": 683076,
          "sha512": "ab5049eead8410e8a00e161dfe12537d86cb6c9030ae6c133be36f9cc8d1d78000d875e4ea20439e7dd93f11c5ea3b252a8767ae6b5769e9280381feddc1ad71",
          "sha256": "a0567d4b636b71a1b270c37a4d79a60df677a0badae6166743d25341178b9086",
          "sha1": "87b32d2e044367375a32457fd430fecc816561f6",
          "md5": "2febf7cec34cce4c853d173e1568e8ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.1-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.1-sources.jar",
          "size": 250536,
          "sha512": "65bf50da6862f95b5c03a2bc498a504bb49ad4fd74e5a34e8bae715487ee59b076b743655e627a7b59d75d598c4fd7f5f97418d0b003ff70451b3cb0aa31fac0",
          "sha256": "50b7959c3d6fc4f2d91ca660de413d3d713b97da565072a84f0be00e41b5180b",
          "sha1": "8c3f181585dcbfb272482aa20e4d91944d81f01a",
          "md5": "df95cd8bff72d92d017eac05c647026f"
        }
      ]
    }
  ]
}
