{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2508.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2508.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.2508.1.jar",
          "size": 701044,
          "sha512": "d56defe549bb24abe59830bd099cd8416881acb5a3aaa9e779335276130cf90d16b60afce75645a3d1e7dd3b2520601b04995a9b1efb5dff5ea8f995833b4797",
          "sha256": "3fad6e705764a3382bb79ee6bca0e271aeca3a272fd70ca1e0f69673f0a2a6bf",
          "sha1": "46154757a9f3341c5ca5b31d07fca55e2bef6ab6",
          "md5": "7a87d563789c2d6d98b4b190b3362cd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2508.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.2508.1.jar",
          "size": 701044,
          "sha512": "d56defe549bb24abe59830bd099cd8416881acb5a3aaa9e779335276130cf90d16b60afce75645a3d1e7dd3b2520601b04995a9b1efb5dff5ea8f995833b4797",
          "sha256": "3fad6e705764a3382bb79ee6bca0e271aeca3a272fd70ca1e0f69673f0a2a6bf",
          "sha1": "46154757a9f3341c5ca5b31d07fca55e2bef6ab6",
          "md5": "7a87d563789c2d6d98b4b190b3362cd2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2508.1-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2508.1-sources.jar",
          "size": 250132,
          "sha512": "8615118cfa152a3cb72249aca794312c24365cda998563b7f5d242aeaf90a03d69ec8443ebad216a9e9b42da10ea29dae853a51f405ec8cbf93ff1e76ad47020",
          "sha256": "71798c3b51e588692853f5266558cd3f7999b7826d4793a703c3283fafc4a32e",
          "sha1": "857388b8714fd0982c3d96f49f768f8242af51ed",
          "md5": "2203f5aaf91e98b6ba8bd4f6f472b8e2"
        }
      ]
    }
  ]
}
