{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.5-1.1.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.5-1.1.2517.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.5-1.1.2517.0.jar",
          "size": 643109,
          "sha512": "b9e62a90b968c93b64fc9436d4cabe7914627ce0b3c6f4570fa05251085ca0125eea0ccc259be6241ea2986c1f7de7e8525b2b46a2b91a047474ccdb566bfd24",
          "sha256": "1bee6543eaed5c6005187e212a02e587a8e245c523af08e6bd4742575a32531e",
          "sha1": "7cb6a0ec1db54b8e42f7cbd2bddace64c02ce0b3",
          "md5": "865510c281594e8380ce8591c579370f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.5-1.1.2517.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.5-1.1.2517.0.jar",
          "size": 643109,
          "sha512": "b9e62a90b968c93b64fc9436d4cabe7914627ce0b3c6f4570fa05251085ca0125eea0ccc259be6241ea2986c1f7de7e8525b2b46a2b91a047474ccdb566bfd24",
          "sha256": "1bee6543eaed5c6005187e212a02e587a8e245c523af08e6bd4742575a32531e",
          "sha1": "7cb6a0ec1db54b8e42f7cbd2bddace64c02ce0b3",
          "md5": "865510c281594e8380ce8591c579370f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.5-1.1.2517.0-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.5-1.1.2517.0-sources.jar",
          "size": 585440,
          "sha512": "4e953d94b9bf5b54798a2dd5b4f844aae98b2586195d5ad1411cea795de350d77ba527554808777584f1037c1b3b76233ca7599423cb86113bcab32fb73cd725",
          "sha256": "57cf8da03c88a9b84c8263d18b863f45dea9e7381b2894bd29755947776073c6",
          "sha1": "f458cd65e571f4fb6429ed5e70ed1b0f91649139",
          "md5": "267046e8df82dc362384ff42d3678e4e"
        }
      ]
    }
  ]
}
