{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.1-2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.8.jar",
          "url": "factory_api-fabric-1.21.1-2.2.8.jar",
          "size": 585386,
          "sha512": "d26666a8dffb5994400f4ba65f7775668362162d1d264a13675bab477892da63a2eacb17a9944492931e0ed7afb8cb800552f30c4961442a2c809b0a1f41f726",
          "sha256": "b4d41b23469046ef61cb11016fbac52bcbd2be710c9b63999a63dd899547fd57",
          "sha1": "e5b39f2ee1ea84931b8b25ca06a81baa26bc77c6",
          "md5": "e2bc9b08ccd5f92a92a158155c87af13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.8.jar",
          "url": "factory_api-fabric-1.21.1-2.2.8.jar",
          "size": 585386,
          "sha512": "d26666a8dffb5994400f4ba65f7775668362162d1d264a13675bab477892da63a2eacb17a9944492931e0ed7afb8cb800552f30c4961442a2c809b0a1f41f726",
          "sha256": "b4d41b23469046ef61cb11016fbac52bcbd2be710c9b63999a63dd899547fd57",
          "sha1": "e5b39f2ee1ea84931b8b25ca06a81baa26bc77c6",
          "md5": "e2bc9b08ccd5f92a92a158155c87af13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.8-sources.jar",
          "url": "factory_api-fabric-1.21.1-2.2.8-sources.jar",
          "size": 256556,
          "sha512": "8cc9ec374232e512372b675795e321e8c4dab7bbaf14bacae6d1e6c0ed95459ae5ce8465998c42723446c331d55721be8242f34289678e4d76e93ef5e4a3718e",
          "sha256": "cd877fee114eaf219eea74d461971a1e126dd4e2e8053f7c15bcc862c8163a21",
          "sha1": "ff268dcf619db0a065d209a2e13a8adc926da7c4",
          "md5": "e908d24c2309489e182cfdaea94262df"
        }
      ]
    }
  ]
}
