{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.9.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.9.jar",
          "size": 467240,
          "sha512": "7bd7c65e97a70d4af99652e47e819c1085a097e951f5b188418087e548e8e1b735dea0f6c3199b6478aad02339dc3b6e9786bda7bf93af4ff560eae2bac687da",
          "sha256": "fd91d309f5f832635788ce61afdd1b3a18d3d301e9785a07a8cee9bea5eb2528",
          "sha1": "b43a1889fa2b9de12540763a05e1f3fab1b9f900",
          "md5": "3e752ddadc43775949677a44abb92f28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.9.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.9.jar",
          "size": 467240,
          "sha512": "7bd7c65e97a70d4af99652e47e819c1085a097e951f5b188418087e548e8e1b735dea0f6c3199b6478aad02339dc3b6e9786bda7bf93af4ff560eae2bac687da",
          "sha256": "fd91d309f5f832635788ce61afdd1b3a18d3d301e9785a07a8cee9bea5eb2528",
          "sha1": "b43a1889fa2b9de12540763a05e1f3fab1b9f900",
          "md5": "3e752ddadc43775949677a44abb92f28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.9-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.9-sources.jar",
          "size": 230104,
          "sha512": "0c7a361ea704a030131d76d8f2288d149cddc27b1a36dd49be6d8549032136ab1503f6102374150ad96c8b7eda33e60238df975f3e93395319f24e994b2eda84",
          "sha256": "1c36a2024a28f31415b9e5d943066cf6c0ab4d8287a4d8f0e588ca8f5bb0d78e",
          "sha1": "35294b9cfda1c9c6f8b3ec81cfd8b11b46514778",
          "md5": "04d789cf177fe9013e241312c440a46b"
        }
      ]
    }
  ]
}
