{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2501.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.13.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.13.jar",
          "size": 362448,
          "sha512": "d90343d5235b696624607a6c8341761bba51f3ecbee5e6341c40fc74f03a8d7c564773ab9782391b1ec60f66772ad579efe23801b9eea0c4a7f47c45c93623a6",
          "sha256": "49ccedab765cf13747816793aff7172c2f19620fd30e9fea3454a64b6941b41e",
          "sha1": "9e9df183951c7fed561e22ab41810636c88a1771",
          "md5": "1d7df52d4df137fb84aa0a55dfa902b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.13.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.13.jar",
          "size": 362448,
          "sha512": "d90343d5235b696624607a6c8341761bba51f3ecbee5e6341c40fc74f03a8d7c564773ab9782391b1ec60f66772ad579efe23801b9eea0c4a7f47c45c93623a6",
          "sha256": "49ccedab765cf13747816793aff7172c2f19620fd30e9fea3454a64b6941b41e",
          "sha1": "9e9df183951c7fed561e22ab41810636c88a1771",
          "md5": "1d7df52d4df137fb84aa0a55dfa902b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.13-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.13-sources.jar",
          "size": 197191,
          "sha512": "ce94e1956dc52c406fb568cb7f12265f9a5bdf2453285b8dc9e1f797bdd58371c659511a8fe371682c1a6e71278567d6eaa916ecfc29a5b3ad2a78df3d041873",
          "sha256": "681a8e96412c13c411e8432d03d5b011cf2abc2be62aee619319006386c5d672",
          "sha1": "63c33180ba58dc85164a22379a7d83886b6ee37a",
          "md5": "648fcef1503add1caa4fa8ed98615eff"
        }
      ]
    }
  ]
}
