{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.1.jar",
          "size": 488116,
          "sha512": "675785ec8baa272f450afb0fb54b2b6f7948652600636822836035b26bc49fa25c26fb8d9acad17d7761d3a374be82a01b9aab5f9f85c3350b127fb264ea07be",
          "sha256": "e44b6e4d96d14c21f7e9b3062a8e456d210ee4b897647ff7491572b3fb1ca750",
          "sha1": "7ef9d2ecab1555b07210edc68ecacce4926d3966",
          "md5": "d7ca92d44bac40098157b6319c3cb7c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.1.jar",
          "size": 488116,
          "sha512": "675785ec8baa272f450afb0fb54b2b6f7948652600636822836035b26bc49fa25c26fb8d9acad17d7761d3a374be82a01b9aab5f9f85c3350b127fb264ea07be",
          "sha256": "e44b6e4d96d14c21f7e9b3062a8e456d210ee4b897647ff7491572b3fb1ca750",
          "sha1": "7ef9d2ecab1555b07210edc68ecacce4926d3966",
          "md5": "d7ca92d44bac40098157b6319c3cb7c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.1-sources.jar",
          "size": 241421,
          "sha512": "4fb72a972f0bc9239def280b1feffce748089a86774a535a40f8752dc4691269778520ee1d4db27dca123fb750c043b01d35f0c99787ad92ab4f933301dde8d6",
          "sha256": "132ef7589284d71173b742c1081d3ddcddf1931d557ad44a35cc88e33b02c41e",
          "sha1": "9a577c54ff81c219fae92f8625d7645260df74ea",
          "md5": "55eb6a3387d65cb7a116ac0d70b3fda7"
        }
      ]
    }
  ]
}
