{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2502.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2501.24"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2502.0.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2502.0.jar",
          "size": 11932719,
          "sha512": "d6ced7529a38fdd1c6d4cbcd26f8c1c4a361f823e8f37c47843708cb7ce4aaceed6b49e787560fef3b1ed1725a929b90d481990b38ea4790033469f3a006ee64",
          "sha256": "7023be0dedadb363cac5c236f86b38c78bcd7ba446104d80a0de65c26637e4dc",
          "sha1": "d1bb66b8481c073c33c917ea70dd974cf3172b9b",
          "md5": "6a3c448917ffc413e2058c20de3674af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2501.24"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2502.0.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2502.0.jar",
          "size": 11932719,
          "sha512": "d6ced7529a38fdd1c6d4cbcd26f8c1c4a361f823e8f37c47843708cb7ce4aaceed6b49e787560fef3b1ed1725a929b90d481990b38ea4790033469f3a006ee64",
          "sha256": "7023be0dedadb363cac5c236f86b38c78bcd7ba446104d80a0de65c26637e4dc",
          "sha1": "d1bb66b8481c073c33c917ea70dd974cf3172b9b",
          "md5": "6a3c448917ffc413e2058c20de3674af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2502.0-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2502.0-sources.jar",
          "size": 11142983,
          "sha512": "3df00e949bea6d9db7b9f6a7a9b6af91ef83a735a777bf77e606664115af1b66038325d6a841a5e36e9ed78ee9ac4a90922bd32a702ad3d9163157ccb0664efa",
          "sha256": "a7a86c3d12bad2439cb88ffb1533ae0d2ac9854f3591299b5111b56d1e8913c6",
          "sha1": "67e2f4afa27dcfe50ece9bbc0be9472bd19412ed",
          "md5": "6adb7e2f805ba049c5dabf4e7dc2c164"
        }
      ]
    }
  ]
}
