{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2502.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.1.jar",
          "size": 376622,
          "sha512": "0b365ac40371e2b27525aab9e77733a0ca60ee691122b657e2f88e043ea0c074908c2902aada83abcf0165ac23fddfccc2fb6642c2cdf508c6da4de1be222f4b",
          "sha256": "0288d3fdef06288f2b8c8ef5304ff5622066571fe9ed9744b77975e557cf9d90",
          "sha1": "6ac199e158caa4ec98265881dbe89e93d2579f3d",
          "md5": "700cc98d07e54bd79d36e0a585003dd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.1.jar",
          "size": 376622,
          "sha512": "0b365ac40371e2b27525aab9e77733a0ca60ee691122b657e2f88e043ea0c074908c2902aada83abcf0165ac23fddfccc2fb6642c2cdf508c6da4de1be222f4b",
          "sha256": "0288d3fdef06288f2b8c8ef5304ff5622066571fe9ed9744b77975e557cf9d90",
          "sha1": "6ac199e158caa4ec98265881dbe89e93d2579f3d",
          "md5": "700cc98d07e54bd79d36e0a585003dd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.1-sources.jar",
          "size": 197856,
          "sha512": "a840aa24cedaee7c68c64b9545462792fc590314db9837a93b3c151d3426e6c6ca811da62613b90b1c4b2e24efc577e2b8ffb44a86a5e8f6fb62cae3e5e7b9fd",
          "sha256": "5bcf6b03b245fe5413259b6e2ad62256ce58810e2d3f859abe3cfe28b082a29d",
          "sha1": "e1d90da87f83f7da067e1a86fe247aa504a68926",
          "md5": "cf2d0df452fdcfcdf3bf90db4ef04022"
        }
      ]
    }
  ]
}
