{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2515.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2515.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2515.2.jar",
          "size": 523048,
          "sha512": "6d74e4c35789557b52ef0f01a07d690d6ee15d2f4b5a0bed83c6f0b34fb8fcd02b27ee3ea3c15e60122b526705c110adac6ae96d78437f94a3dcd4e5fe1eaaf0",
          "sha256": "499859e61b27091a95c3221c65ca0a43c45eea2faee44266cda5c89aac049855",
          "sha1": "b0a3dd93cf717b724a87083786870bbe08e5de1e",
          "md5": "b9cbc6fa118e5748034092976d9f2550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2515.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2515.2.jar",
          "size": 523048,
          "sha512": "6d74e4c35789557b52ef0f01a07d690d6ee15d2f4b5a0bed83c6f0b34fb8fcd02b27ee3ea3c15e60122b526705c110adac6ae96d78437f94a3dcd4e5fe1eaaf0",
          "sha256": "499859e61b27091a95c3221c65ca0a43c45eea2faee44266cda5c89aac049855",
          "sha1": "b0a3dd93cf717b724a87083786870bbe08e5de1e",
          "md5": "b9cbc6fa118e5748034092976d9f2550"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2515.2-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2515.2-sources.jar",
          "size": 253329,
          "sha512": "516c63824fad995c3c05c52067bea1bd455d2f600ed4db848aebafe5245ca86d26ac2081e9a39ddad854f78c24697538c735419e7e5b632df96592a6228f60fe",
          "sha256": "b5f01706805dc8a19a4b215a972a9dbcc887d14fc0d0efa1dbc27c667f7bc930",
          "sha1": "b746d8fdec121780e946c8fcf26d7b1dc30d90ae",
          "md5": "24576a80bc952755d09ba63add18f135"
        }
      ]
    }
  ]
}
