{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.6.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.6.jar",
          "size": 378218,
          "sha512": "b36c7bf63a3ad97ae3d17a946d05cefce3a66da6d306df428181c031f79f52335860c3b146509abd44cf036c05a2b4217071139d466cee9b2ad922a93d8b1145",
          "sha256": "bd214201c82513888c74a6491a8eaa189a088a3b086adfa7620772c382912e2a",
          "sha1": "46ba98dfeb873a9d299afe3d7f47b70a75faf51d",
          "md5": "760fecf23646c4c2e7dfaec0c87b12c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.6.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.6.jar",
          "size": 378218,
          "sha512": "b36c7bf63a3ad97ae3d17a946d05cefce3a66da6d306df428181c031f79f52335860c3b146509abd44cf036c05a2b4217071139d466cee9b2ad922a93d8b1145",
          "sha256": "bd214201c82513888c74a6491a8eaa189a088a3b086adfa7620772c382912e2a",
          "sha1": "46ba98dfeb873a9d299afe3d7f47b70a75faf51d",
          "md5": "760fecf23646c4c2e7dfaec0c87b12c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.6-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.6-sources.jar",
          "size": 196743,
          "sha512": "6a7812add2270ee582daef6932bc91618e731752aa7b2af7de6b51a77a389749c0110b84667607774d116704a28d73df366afaab636904df26a418b03526ddeb",
          "sha256": "a6dd2e8fc7790a55156c2480a2e175ed9029bebf7bd32bef48d6e9527e6c5c46",
          "sha1": "0f19c5723f66b699541b800770e39dddc5cc92bb",
          "md5": "e3154686b6ff90dd9b6db035315392d8"
        }
      ]
    }
  ]
}
