{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.7.10.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.2506.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2506.0.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2506.0.jar",
          "size": 14345388,
          "sha512": "7213d46ea558c134df57a2e607f52839c751b2d4b4dea1ec77822e251e394c76a64ece1b46835bbc1745a87ed97dc1e4ebbe5026af2b31c32749ea2492d3733e",
          "sha256": "fd8bf7ed89759aa318d3081d9a8530d127a4e63b921c499f1713201f95570ab5",
          "sha1": "056d5b1e249aee8957e6ca9645cf03f5a28c1bfe",
          "md5": "1b8d710eaef635a4d1289933170b2c12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.2506.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2506.0.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2506.0.jar",
          "size": 14345388,
          "sha512": "7213d46ea558c134df57a2e607f52839c751b2d4b4dea1ec77822e251e394c76a64ece1b46835bbc1745a87ed97dc1e4ebbe5026af2b31c32749ea2492d3733e",
          "sha256": "fd8bf7ed89759aa318d3081d9a8530d127a4e63b921c499f1713201f95570ab5",
          "sha1": "056d5b1e249aee8957e6ca9645cf03f5a28c1bfe",
          "md5": "1b8d710eaef635a4d1289933170b2c12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2506.0-sources.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2506.0-sources.jar",
          "size": 13527404,
          "sha512": "60c0710d4165a7363834589cf3b213707a9b43c22dfdcd72f607f04896bc63909ef91b378b01c932b0e420ce7fe4593e376c99db7ebf676bf712e08d4e1e07c5",
          "sha256": "841668f2d78f114628081361ecc942c8d446357a640ce847036e1585515a5b44",
          "sha1": "ef487c081c1f34d02e97972e1c5c35f54701be98",
          "md5": "a0b9f152f384b0cedb3dbc2b0bffcd1a"
        }
      ]
    }
  ]
}
