{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2510.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.4.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.4.jar",
          "size": 682833,
          "sha512": "e098526a43e747f4c4411e98c5cc87403acf8aa7c221e80bef2f660a7a5b45b8cccfa2596cad6bb68989e318d6b5c6e1c940160151b3a18453d78ed8235ecce8",
          "sha256": "601632e67fe099c01767561e117bfb961769b78a6be235819746d64663203db0",
          "sha1": "2a927a0830e4c27640eaec4e8dd518a597e91f82",
          "md5": "d7d47c1be1f7f6b54669d8861ca312c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.4.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.4.jar",
          "size": 682833,
          "sha512": "e098526a43e747f4c4411e98c5cc87403acf8aa7c221e80bef2f660a7a5b45b8cccfa2596cad6bb68989e318d6b5c6e1c940160151b3a18453d78ed8235ecce8",
          "sha256": "601632e67fe099c01767561e117bfb961769b78a6be235819746d64663203db0",
          "sha1": "2a927a0830e4c27640eaec4e8dd518a597e91f82",
          "md5": "d7d47c1be1f7f6b54669d8861ca312c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.4-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.4-sources.jar",
          "size": 250447,
          "sha512": "68d96528e390b68d8054331974e0ab32b647a91ead88055dfc07b1a861e5308340684f4218db91fa5a68368458ef4e37998ae739360476154999b740cb31f5cf",
          "sha256": "7adba1589547b58ad330d0e468efa25bc0e94fc0d167e8c88828ec06e2b42313",
          "sha1": "8789231117c466a7543715ce2c3c9118f905013d",
          "md5": "8decbcf4efe81739a92d54ac17ffeff0"
        }
      ]
    }
  ]
}
