{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2502.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.13.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.13.jar",
          "size": 442948,
          "sha512": "11085ba2b01809c57e27a3532fbb8e8aab2654f7ea0b274be34450d2755c91cba91f543c9b3f08eb70d3158c10d270ce24c3a5977a2d93c3947020e8a1127af6",
          "sha256": "da9772b0f134d9277440671f56e1d8a58ee2c8061d438da0cfc2609747059d73",
          "sha1": "5e81af40cfbe0da2e8cb7a5feaddc2a34a43d9ee",
          "md5": "a603e47357b5d2a8eb67de1adf80b9c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.13.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.13.jar",
          "size": 442948,
          "sha512": "11085ba2b01809c57e27a3532fbb8e8aab2654f7ea0b274be34450d2755c91cba91f543c9b3f08eb70d3158c10d270ce24c3a5977a2d93c3947020e8a1127af6",
          "sha256": "da9772b0f134d9277440671f56e1d8a58ee2c8061d438da0cfc2609747059d73",
          "sha1": "5e81af40cfbe0da2e8cb7a5feaddc2a34a43d9ee",
          "md5": "a603e47357b5d2a8eb67de1adf80b9c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.13-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.13-sources.jar",
          "size": 228890,
          "sha512": "9df6c4120af153a74b12f4cd8dff90c11f19501c70096901c9139ef0d5d85aa7d5c2a41bef341f213cea73b3538ceddc6a5086e2ff32da039b584cce546114f4",
          "sha256": "5f1281d7384f74113d6dd0fb7c85b23c905a2c9e33e28ac4f047a97f44e8dd7c",
          "sha1": "c2e5063b34da09267c3d601bf72927f2876dbf79",
          "md5": "868af3fa12e025ba565ca15fdc567130"
        }
      ]
    }
  ]
}
