{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.2.2526.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.2.2526.0.jar",
          "url": "legacy-forge-1.21.5-1.8.2.2526.0.jar",
          "size": 19756083,
          "sha512": "c1344909cd55ce6599b0544a6230e0b1677f8d9ffa0e8f10d63e7a60c2273a7001b096c5d4e65fcbc9800e907e2897d8f99968f4e7837bef866e657c32b37c85",
          "sha256": "1b21517d05b788dd2cfde8c26a397576505ffaee798931a1f87223129c23c496",
          "sha1": "35b12e86f5d527ad68413af2050aecd6edfb18bb",
          "md5": "189ac7723f046fb12655c3f694158804"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.2.2526.0.jar",
          "url": "legacy-forge-1.21.5-1.8.2.2526.0.jar",
          "size": 19756083,
          "sha512": "c1344909cd55ce6599b0544a6230e0b1677f8d9ffa0e8f10d63e7a60c2273a7001b096c5d4e65fcbc9800e907e2897d8f99968f4e7837bef866e657c32b37c85",
          "sha256": "1b21517d05b788dd2cfde8c26a397576505ffaee798931a1f87223129c23c496",
          "sha1": "35b12e86f5d527ad68413af2050aecd6edfb18bb",
          "md5": "189ac7723f046fb12655c3f694158804"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.2.2526.0-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.2.2526.0-sources.jar",
          "size": 18885473,
          "sha512": "b1e5b1ee00775d4f659aae49635a3eac37808fdd2b564f4cd29b829222f2b2b9767e208222609fd9b9a144839de2803317c0151e074439c88b99fd1305da7426",
          "sha256": "db2ed2990c60307b30059731e38f3476a208ecd5289155c75b8edc267b14e1c0",
          "sha1": "f19df8a56c63e8069fd820d8bae723f737a9115d",
          "md5": "b2f33d7ea346d0715b3d5b4b90bb9080"
        }
      ]
    }
  ]
}
