{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.1-2.2.7.2606.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.7.2606.1.jar",
          "url": "factory_api-fabric-1.20.1-2.2.7.2606.1.jar",
          "size": 578337,
          "sha512": "69fd1e4f715952d61674325954191aea2dd396c3befb9473d9d2cc992fdc336fe65075812def2d1d400f56cdc04f9c5ab064a5d63c8f37f0b7a449b720151680",
          "sha256": "5e68eca8ddbbc0a3df03ec0ce320952d395ef8aa5d0ea937c83e494be16925b7",
          "sha1": "51b163044eb50e2641a18596e63f6c9a6cd44b78",
          "md5": "2f452f3f7f40c9ec49fb019d0cdf5635"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.7.2606.1.jar",
          "url": "factory_api-fabric-1.20.1-2.2.7.2606.1.jar",
          "size": 578337,
          "sha512": "69fd1e4f715952d61674325954191aea2dd396c3befb9473d9d2cc992fdc336fe65075812def2d1d400f56cdc04f9c5ab064a5d63c8f37f0b7a449b720151680",
          "sha256": "5e68eca8ddbbc0a3df03ec0ce320952d395ef8aa5d0ea937c83e494be16925b7",
          "sha1": "51b163044eb50e2641a18596e63f6c9a6cd44b78",
          "md5": "2f452f3f7f40c9ec49fb019d0cdf5635"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.7.2606.1-sources.jar",
          "url": "factory_api-fabric-1.20.1-2.2.7.2606.1-sources.jar",
          "size": 254207,
          "sha512": "3e540bd362b29f0edcccc80df5123016cf25d5a7af930c16f513339954c5f75e0095495661a4155b6bae13b77a147caf409a6684ff35ce8b95276261bfe44978",
          "sha256": "10817a0305b70ea228547aa04298879d51c02ef48419fe7f5533f752c59e1c2e",
          "sha1": "015bf2e51912ea9f4d955e14a6ce29c094f82e57",
          "md5": "945c451d83dd13f584863252b747f14f"
        }
      ]
    }
  ]
}
