{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2502.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.11.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.11.jar",
          "size": 451629,
          "sha512": "2134baf56c6384d0c48da76e07dcfb7faf75e143f6b6067c726a7584a28a799bdca4889db0cbb4616c4ab13bdff9417ebb125508b274724ec9a09878eea6096c",
          "sha256": "a80c591d5efe33b69f38c920cf3a53d2f0bbcbf5479b5e462a22eeea6409e97b",
          "sha1": "54618a6542920ef666d10b8e65ee6145545f5f5c",
          "md5": "940c04136c8c93fc6189fbd9473e99a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.11.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.11.jar",
          "size": 451629,
          "sha512": "2134baf56c6384d0c48da76e07dcfb7faf75e143f6b6067c726a7584a28a799bdca4889db0cbb4616c4ab13bdff9417ebb125508b274724ec9a09878eea6096c",
          "sha256": "a80c591d5efe33b69f38c920cf3a53d2f0bbcbf5479b5e462a22eeea6409e97b",
          "sha1": "54618a6542920ef666d10b8e65ee6145545f5f5c",
          "md5": "940c04136c8c93fc6189fbd9473e99a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.11-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.11-sources.jar",
          "size": 227575,
          "sha512": "6790ab1b623170ad864fdb21bb5943058f4bd084ed1647b0a0615d7017a63b3811f3e1f47adc4d876ccb15a19e79e463f9c889a8fb876091b3edd378f2c7d1ad",
          "sha256": "1bc29831a5a69448f0532ea2a78558b8658f780db3c6248b4c10600a5c814b31",
          "sha1": "2ca0abc1acb5eb7901bc352477b56cdd4ac9d0a9",
          "md5": "a46ef74f462ee3486f745b39c0aa31e1"
        }
      ]
    }
  ]
}
