{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.2.2526.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.2.2526.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.2.2526.0.jar",
          "size": 19778938,
          "sha512": "da7854ebfd603eca6d9c3534ce5881130680120c42f1babb20d5cc20e388cc05eb1d96ade6cd83962642a2935086976f5d0f34313af5b1c043fbf1285602c4e3",
          "sha256": "330ca1dcf14364fc9691afd856ba376cc53d3fbb03f470cbbd4b694c6c8a814c",
          "sha1": "6bc138aff029d08489de0ba7f9f48175d53cfc69",
          "md5": "06934b1c35a66b83130e0a7693081a4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.2.2526.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.2.2526.0.jar",
          "size": 19778938,
          "sha512": "da7854ebfd603eca6d9c3534ce5881130680120c42f1babb20d5cc20e388cc05eb1d96ade6cd83962642a2935086976f5d0f34313af5b1c043fbf1285602c4e3",
          "sha256": "330ca1dcf14364fc9691afd856ba376cc53d3fbb03f470cbbd4b694c6c8a814c",
          "sha1": "6bc138aff029d08489de0ba7f9f48175d53cfc69",
          "md5": "06934b1c35a66b83130e0a7693081a4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.2.2526.0-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.2.2526.0-sources.jar",
          "size": 18885884,
          "sha512": "c0d1c7ca21f1e17faca5d821a9f26560ee060d0e3812971a48378fef691b647844d88bb7ec64817525b5a8b2946ba7e53c8cacf0124ca193ec4f952833b7b5dd",
          "sha256": "0432ab9df3cc78fe9944895b1576bf81998169b3ff2772135e459617cb9d0e0d",
          "sha1": "004c8cabca1d4a689cca9785bf7ad342e5642dd2",
          "md5": "e817cd7c38023136c0c5d086952c1114"
        }
      ]
    }
  ]
}
