{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.1-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.20.1-2.2.3.2514.2.jar",
          "size": 556531,
          "sha512": "1af236e3dcc2ff3232dbf80117cfc2af6ab52ff4de7db8d22541962e5afd472bad9d88182751a46c9ec448271daf32707806aa149cb78fca3b5d83f5ce83c641",
          "sha256": "286b5f05d14d6e228cd78af7aa1fdacdda28a6f9add3bf9eee3227cfe9bf7ad0",
          "sha1": "95fdc7b119755d62c3a1ce1466173360b061e641",
          "md5": "3a0fe820eedf5ea9468ea214e35c4e03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.20.1-2.2.3.2514.2.jar",
          "size": 556531,
          "sha512": "1af236e3dcc2ff3232dbf80117cfc2af6ab52ff4de7db8d22541962e5afd472bad9d88182751a46c9ec448271daf32707806aa149cb78fca3b5d83f5ce83c641",
          "sha256": "286b5f05d14d6e228cd78af7aa1fdacdda28a6f9add3bf9eee3227cfe9bf7ad0",
          "sha1": "95fdc7b119755d62c3a1ce1466173360b061e641",
          "md5": "3a0fe820eedf5ea9468ea214e35c4e03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.3.2514.2-sources.jar",
          "url": "factory_api-fabric-1.20.1-2.2.3.2514.2-sources.jar",
          "size": 250900,
          "sha512": "b3eb98d46a48ea03a95475e5f14cf07c8effd398781e7399ae103fc4c152fc4190ead9359a7439a9d0fe850efaa0cefae9b946615bc2daa36a2ba65a13d82bb3",
          "sha256": "fe1889423eb8b272700c61039f081a2a7e62a97c58d8aae5fd8474911d9ed008",
          "sha1": "ea4788e0e6311d5bab47eef438b855c6ce90beaa",
          "md5": "365bcc196fc8db1d5ca725048b169cac"
        }
      ]
    }
  ]
}
