{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.10-1.9-pre-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.10-2.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.9-pre-1.jar",
          "url": "legacy-neoforge-1.21.10-1.9-pre-1.jar",
          "size": 44946468,
          "sha512": "124c19d89e8d53c9df57b31bed24f5a93edefb451310f54fc0a84809fbdccf4bd2e8ad8c2b34ad63bb0036f28592a710f8a13a7cf11a1c3efcfe79100e994c63",
          "sha256": "92f8c1dec8b59ffa8f6832d91538e499bb2608ecc6f1b7f6259f431ccefdf70c",
          "sha1": "9c21e5a375ee9211e8f538d2e43ab32fd104278d",
          "md5": "5a31ca14bb8c7ddf911770873008c619"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.10-2.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.9-pre-1.jar",
          "url": "legacy-neoforge-1.21.10-1.9-pre-1.jar",
          "size": 44946468,
          "sha512": "124c19d89e8d53c9df57b31bed24f5a93edefb451310f54fc0a84809fbdccf4bd2e8ad8c2b34ad63bb0036f28592a710f8a13a7cf11a1c3efcfe79100e994c63",
          "sha256": "92f8c1dec8b59ffa8f6832d91538e499bb2608ecc6f1b7f6259f431ccefdf70c",
          "sha1": "9c21e5a375ee9211e8f538d2e43ab32fd104278d",
          "md5": "5a31ca14bb8c7ddf911770873008c619"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.9-pre-1-sources.jar",
          "url": "legacy-neoforge-1.21.10-1.9-pre-1-sources.jar",
          "size": 43355124,
          "sha512": "b2f9351469ce67a5f9fbb01d232ed5cdb2438e5f093d380efdd880932a5a8f5c99609a2986eed5c58e6a9a955e97f64c0fab58a3b0afbf9957d2dffca701cb1c",
          "sha256": "34519519d97bd78d29daafad47ba5e97d09f65b1845aa61582263c8f1fe738be",
          "sha1": "5d33ca3a888b3e1b6592958fb10867a20d32b82d",
          "md5": "4f1d91cb9789889a7a182bc89c2112f6"
        },
        {
          "name": "legacy-neoforge-1.21.10-1.9-pre-1-sources.jar",
          "url": "legacy-neoforge-1.21.10-1.9-pre-1-sources.jar",
          "size": 43355124,
          "sha512": "b2f9351469ce67a5f9fbb01d232ed5cdb2438e5f093d380efdd880932a5a8f5c99609a2986eed5c58e6a9a955e97f64c0fab58a3b0afbf9957d2dffca701cb1c",
          "sha256": "34519519d97bd78d29daafad47ba5e97d09f65b1845aa61582263c8f1fe738be",
          "sha1": "5d33ca3a888b3e1b6592958fb10867a20d32b82d",
          "md5": "4f1d91cb9789889a7a182bc89c2112f6"
        }
      ]
    }
  ]
}
