{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.7.2616.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.1.jar",
          "size": 560424,
          "sha512": "43e3e11218a237b43bdb947d0d386ebd919ccd78dab07238a3cea415d8b6cede4ed6c536986beff5be7593b5f158dd103a6f005dd106aad6f6ff8bb14b4dab3c",
          "sha256": "5f7e9231c0f6ac87e3b2ef136b727476039e77199e4ccf5a889f6f71c8d0d91e",
          "sha1": "86256796575e65d755f8c88cbb0ed7fb5864ca8a",
          "md5": "e90566d5bc837c82733a0a2f76b2104e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.1.jar",
          "size": 560424,
          "sha512": "43e3e11218a237b43bdb947d0d386ebd919ccd78dab07238a3cea415d8b6cede4ed6c536986beff5be7593b5f158dd103a6f005dd106aad6f6ff8bb14b4dab3c",
          "sha256": "5f7e9231c0f6ac87e3b2ef136b727476039e77199e4ccf5a889f6f71c8d0d91e",
          "sha1": "86256796575e65d755f8c88cbb0ed7fb5864ca8a",
          "md5": "e90566d5bc837c82733a0a2f76b2104e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.1-sources.jar",
          "size": 256749,
          "sha512": "0d4a89e570ede3b447f10e80d57a1521578713216a4798edd8b80edab7c28623198cb5b252d97af30a7a848cd1ef8f75363a02ecf616731c487d03fd34313d6b",
          "sha256": "93b735d0b9c9ecdb22dbc4bcfb0fa4dfe8887bdef1adda29ed8deb06764f0855",
          "sha1": "c733d30b0c8bc8d124261a512633b99f682966e9",
          "md5": "ad8e36ab22f44417ab2e48bc207e0919"
        },
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.1-sources.jar",
          "size": 256749,
          "sha512": "0d4a89e570ede3b447f10e80d57a1521578713216a4798edd8b80edab7c28623198cb5b252d97af30a7a848cd1ef8f75363a02ecf616731c487d03fd34313d6b",
          "sha256": "93b735d0b9c9ecdb22dbc4bcfb0fa4dfe8887bdef1adda29ed8deb06764f0855",
          "sha1": "c733d30b0c8bc8d124261a512633b99f682966e9",
          "md5": "ad8e36ab22f44417ab2e48bc207e0919"
        }
      ]
    }
  ]
}
