{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.9.jar",
          "size": 551650,
          "sha512": "f9db33b81837edbd8755b4190e911b3a8faaba9ab52c969c07074a40102ae56f2ce6aed01141082bc9faab8db7eee8be09e13275bd0f3c5a3351b66257ccdfce",
          "sha256": "084406066a96ac4e6f903103cf7205e163ab71f2d84aa554df39511c1728fab9",
          "sha1": "6f16e5404a7b24ef7cf6f8b6fd8e87e52869fccd",
          "md5": "35849ca868504b50c2e93c61b6feb237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.9.jar",
          "size": 551650,
          "sha512": "f9db33b81837edbd8755b4190e911b3a8faaba9ab52c969c07074a40102ae56f2ce6aed01141082bc9faab8db7eee8be09e13275bd0f3c5a3351b66257ccdfce",
          "sha256": "084406066a96ac4e6f903103cf7205e163ab71f2d84aa554df39511c1728fab9",
          "sha1": "6f16e5404a7b24ef7cf6f8b6fd8e87e52869fccd",
          "md5": "35849ca868504b50c2e93c61b6feb237"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.9-sources.jar",
          "size": 256821,
          "sha512": "22da7b8538dbb288ad20baa6d040f71271bb137c1562c6e0edac967046727c173eaec8212ff65d32b4b926a3da9ca015dbeea33531109c1352972bdedbfd9cb6",
          "sha256": "395f9a903af2fccc1b4ec5af37d959fb4d55478aaae7e4a8b61bd46aa4ab522d",
          "sha1": "4687990b244705c5a269f74e978ae7b19baf893d",
          "md5": "c76497013014f468d8c43428033b761d"
        },
        {
          "name": "factory_api-neoforge-1.21.5-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.9-sources.jar",
          "size": 256821,
          "sha512": "22da7b8538dbb288ad20baa6d040f71271bb137c1562c6e0edac967046727c173eaec8212ff65d32b4b926a3da9ca015dbeea33531109c1352972bdedbfd9cb6",
          "sha256": "395f9a903af2fccc1b4ec5af37d959fb4d55478aaae7e4a8b61bd46aa4ab522d",
          "sha1": "4687990b244705c5a269f74e978ae7b19baf893d",
          "md5": "c76497013014f468d8c43428033b761d"
        }
      ]
    }
  ]
}
