{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.10-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.10-2.2.9.jar",
          "url": "factory_api-fabric-1.21.10-2.2.9.jar",
          "size": 599505,
          "sha512": "1b238aed1faa2ab54812d9d1b98fa5d4c3e9d217e714deef0299c7f7bac114b7aad87fb0bf1ddf3ff2cdb3f1a2cfcf0e92cf2f052686c79af819a870aa6cbc4b",
          "sha256": "3f87884c51cca2f4832454c9348cb04ad7baf59b32b750a47f1c853d47b37f46",
          "sha1": "01048dcf191a2199b375c92a998afe40d69a074e",
          "md5": "14f10f00a3b36234937e45e414a27582"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.1+1.21.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "16.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.10-2.2.9.jar",
          "url": "factory_api-fabric-1.21.10-2.2.9.jar",
          "size": 599505,
          "sha512": "1b238aed1faa2ab54812d9d1b98fa5d4c3e9d217e714deef0299c7f7bac114b7aad87fb0bf1ddf3ff2cdb3f1a2cfcf0e92cf2f052686c79af819a870aa6cbc4b",
          "sha256": "3f87884c51cca2f4832454c9348cb04ad7baf59b32b750a47f1c853d47b37f46",
          "sha1": "01048dcf191a2199b375c92a998afe40d69a074e",
          "md5": "14f10f00a3b36234937e45e414a27582"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.10-2.2.9-sources.jar",
          "url": "factory_api-fabric-1.21.10-2.2.9-sources.jar",
          "size": 256854,
          "sha512": "5e10d14e6f00ac60b7a78b65bc9943982eb84f319c39cea99200aa35f843ffde862d27ebdec118ce89256e9fbca6776209de4fda8ec0aaebf90c4c765cf2a756",
          "sha256": "07bbbeedb447ec3614f285771fdbe9c8874ed905bd5e12f09018b6fde277ce5a",
          "sha1": "ef326e9326f244c508eabded8af76568e61d3abb",
          "md5": "28a65bbcd3dfb123fc48a8878f4d444b"
        }
      ]
    }
  ]
}
