{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.19.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.19.jar",
          "size": 387226,
          "sha512": "b058e76d1498dd6800e0d4e739f715f8a91c0cb88d734285317f8bcf6bbb92c3f6f42774317737dcb4cca9d787dfd68cf51a198685a8b61fa09cedf3f2f9ab3a",
          "sha256": "7375ee0a38ac66ccec2f673494df298c2ff3bf6a8210af59400ef21cd5683079",
          "sha1": "fcc907e73d4f6f80549b6c28d1d66c29354446dc",
          "md5": "d46b42db0fa1201af902c683cc0df428"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.19.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.19.jar",
          "size": 387226,
          "sha512": "b058e76d1498dd6800e0d4e739f715f8a91c0cb88d734285317f8bcf6bbb92c3f6f42774317737dcb4cca9d787dfd68cf51a198685a8b61fa09cedf3f2f9ab3a",
          "sha256": "7375ee0a38ac66ccec2f673494df298c2ff3bf6a8210af59400ef21cd5683079",
          "sha1": "fcc907e73d4f6f80549b6c28d1d66c29354446dc",
          "md5": "d46b42db0fa1201af902c683cc0df428"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.19-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.19-sources.jar",
          "size": 200767,
          "sha512": "1fd73629e35cc4b547daef73b86e0bc3bac08aeaacdcc92d8297a1a38c91e8fbfa72fdac45a69c83f3c103ab63d63f16f0515dc2619ba42819b1d12e0ea74fc5",
          "sha256": "369aa92a946364a23505e407a7b84da42fa35ca7123cdd5969457658e4446171",
          "sha1": "822dddca6cb2c272b35ba34c2912e2ef264e38b5",
          "md5": "8c5b4c9a1fb659d78189fc620555df03"
        }
      ]
    }
  ]
}
