{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.4-1.1.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2516.0.jar",
          "size": 596177,
          "sha512": "04dc4743fe4019a382b02abbf791016be728aff931043da4bc1181f0fd9ccf9955d642b6d473ebd1c751e5012f72bfe42678a0c695fc9044119ff0c39cfa400a",
          "sha256": "498e974d379fa730a8ed8cbb30cef6a7ab9dcefe7a96d674d1e8ab8f5040e090",
          "sha1": "ae0dddab8319d8a37f44ca296ab6b9e3bc948af7",
          "md5": "9b02086b45249beb72777b8c1a1c5445"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2516.0.jar",
          "size": 596177,
          "sha512": "04dc4743fe4019a382b02abbf791016be728aff931043da4bc1181f0fd9ccf9955d642b6d473ebd1c751e5012f72bfe42678a0c695fc9044119ff0c39cfa400a",
          "sha256": "498e974d379fa730a8ed8cbb30cef6a7ab9dcefe7a96d674d1e8ab8f5040e090",
          "sha1": "ae0dddab8319d8a37f44ca296ab6b9e3bc948af7",
          "md5": "9b02086b45249beb72777b8c1a1c5445"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2516.0-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2516.0-sources.jar",
          "size": 536414,
          "sha512": "c174bc5dbe9a3fc5afa68806b6e3f5ba2ab3e304ae310738fa8b44dff4785173d0af41585db8550b9da8d1916a3b7c9e947730a2bf3ed49bf1a4a638f7441f04",
          "sha256": "6b519c0c5465ebbcc5b62b8685fa66cc025962fcc5d1f6b79aa333b5b6add435",
          "sha1": "6f713d01a7dcd6229fe2700ac09a4e339741099c",
          "md5": "66f728b49aaaa2c9750603dbd2f82112"
        }
      ]
    }
  ]
}
