{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2507.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.12.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.12.jar",
          "size": 482587,
          "sha512": "22cba44ff1ba36b7e49e530a5c5dcacd367ad90170d4f8b0e007697341a491379b8bb566a1f6b26c9bce4de778acc1dba25c19516ed5204155bcac542c3e6256",
          "sha256": "45ac9da845a6ac4003ad90014414a8a48bb7098b497ea49056ec9d1b3ac1bcf1",
          "sha1": "13e45f3680700ce6c16d66ca8b9e2be4060f4572",
          "md5": "dab3d1ac4a44e411a61b41fe85edc7c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.12.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.12.jar",
          "size": 482587,
          "sha512": "22cba44ff1ba36b7e49e530a5c5dcacd367ad90170d4f8b0e007697341a491379b8bb566a1f6b26c9bce4de778acc1dba25c19516ed5204155bcac542c3e6256",
          "sha256": "45ac9da845a6ac4003ad90014414a8a48bb7098b497ea49056ec9d1b3ac1bcf1",
          "sha1": "13e45f3680700ce6c16d66ca8b9e2be4060f4572",
          "md5": "dab3d1ac4a44e411a61b41fe85edc7c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.12-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.12-sources.jar",
          "size": 244480,
          "sha512": "be8e1af077e8ae0f7e9d849a4253ba1de0d34e944b8c4bf2108d7833d414457605e6891c0d1bbb0861420a54c1cf82fbe487bd239be1d9e9a8c72164064bf86c",
          "sha256": "561a9c7811c6d80e2113f82565bf0624202d0b34b0eac578587dbfff5daa6def",
          "sha1": "baf5a55b03229d66eab64f6d7082c071bf7095c2",
          "md5": "55aaba711f15b74f3634db6666c75d25"
        }
      ]
    }
  ]
}
