{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.20.4-1.8.0.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.8.0.2515.0.jar",
          "url": "legacy-neoforge-1.20.4-1.8.0.2515.0.jar",
          "size": 18275569,
          "sha512": "2f7aa662d2e67981cf70df2de2217cd6657f9bd048fab4e639ba086685913bee377b07ca5ee8a1bf203cd74d7f93a44c94ec1f40c4ae344dac6a4209b6968f24",
          "sha256": "d7d9f02059b5fe317040f883c921e340b523ec9b022c047b9ecfd3274b970ccf",
          "sha1": "ce4508f109a94a52e22e9b9aecfc818bebe8e3c8",
          "md5": "4829ce8c330e028a6e51bf13e01dbc14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.8.0.2515.0.jar",
          "url": "legacy-neoforge-1.20.4-1.8.0.2515.0.jar",
          "size": 18275569,
          "sha512": "2f7aa662d2e67981cf70df2de2217cd6657f9bd048fab4e639ba086685913bee377b07ca5ee8a1bf203cd74d7f93a44c94ec1f40c4ae344dac6a4209b6968f24",
          "sha256": "d7d9f02059b5fe317040f883c921e340b523ec9b022c047b9ecfd3274b970ccf",
          "sha1": "ce4508f109a94a52e22e9b9aecfc818bebe8e3c8",
          "md5": "4829ce8c330e028a6e51bf13e01dbc14"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.8.0.2515.0-sources.jar",
          "url": "legacy-neoforge-1.20.4-1.8.0.2515.0-sources.jar",
          "size": 17432544,
          "sha512": "7f23d0685fd07aaa6581e235a1c1bd4885ac90ad474e7aa38081f787cc9ddbf7e46cd03acba274e4135065a5bee7086f5c73de56a80d04ad0beb72ec683e766a",
          "sha256": "307d551cd56189b359a05e929ec89a903524677ed7663fe99c3e5cb5e2016861",
          "sha1": "13f1548a20d487f8d716d088988d85a9a54699b8",
          "md5": "fa9a5afe6d796a968804d8b389225530"
        }
      ]
    }
  ]
}
