{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2508.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2508.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2508.3.jar",
          "size": 495120,
          "sha512": "e6fa1de8f88eeb49bc87f77c23ed92bff7ab31ec7e16741ee373d0accde75e41a37336515e5e13358e46220be8dc2f5e8df88349fece8dc3f9ae3d273c52d45b",
          "sha256": "107dca96070d40bc281c061d606beac7c0a57c5a5e234de0df38e852de0b38e5",
          "sha1": "2b73b396e5d2fa97b8dd32e0f1665fdf785b4730",
          "md5": "67559bcf5a0b799a6c8ca384d1f12c0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2508.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2508.3.jar",
          "size": 495120,
          "sha512": "e6fa1de8f88eeb49bc87f77c23ed92bff7ab31ec7e16741ee373d0accde75e41a37336515e5e13358e46220be8dc2f5e8df88349fece8dc3f9ae3d273c52d45b",
          "sha256": "107dca96070d40bc281c061d606beac7c0a57c5a5e234de0df38e852de0b38e5",
          "sha1": "2b73b396e5d2fa97b8dd32e0f1665fdf785b4730",
          "md5": "67559bcf5a0b799a6c8ca384d1f12c0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2508.3-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2508.3-sources.jar",
          "size": 248092,
          "sha512": "8b2258e5dad9d91f0d5a707ff5df5f5a278c8e47236da24377f248fc04c2a3a3675afcf35378b6933858c63735d3b85c97499d2df624e4da9aa754684349036a",
          "sha256": "f82e2f4b3e5c77147646ca8bc22e943758f6cf9ba686b601633a47d16e1c6579",
          "sha1": "9adc6794b4262d367e383d07be238d4056fb2270",
          "md5": "e22078c9339d23e197b8e8e116d4183c"
        }
      ]
    }
  ]
}
