{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.0.jar",
          "size": 510097,
          "sha512": "70097bb78a95a296436a44a169a4613639c3eace5a90f688f820ec8684fc10ba73e2ff0e4e21bd23a62fa63f0c7d008f58c0cc08c5919ec8500f4c107a93f7b4",
          "sha256": "b398977fc1383787d3f32b9697e6d659b3a241026257f8f056fec00ffb8f4428",
          "sha1": "1ef6b38eb503340c175a664188750568a2c875cd",
          "md5": "5c887f44853c75aeeee8b7c88c0b752b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.0.jar",
          "size": 510097,
          "sha512": "70097bb78a95a296436a44a169a4613639c3eace5a90f688f820ec8684fc10ba73e2ff0e4e21bd23a62fa63f0c7d008f58c0cc08c5919ec8500f4c107a93f7b4",
          "sha256": "b398977fc1383787d3f32b9697e6d659b3a241026257f8f056fec00ffb8f4428",
          "sha1": "1ef6b38eb503340c175a664188750568a2c875cd",
          "md5": "5c887f44853c75aeeee8b7c88c0b752b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.0-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.0-sources.jar",
          "size": 249429,
          "sha512": "82b2542bbbe13fc79254ecee8a6b7770534d57726fcfcb829d7e853c88d649b812ce04638c398a6d4745d6da135f5026cc7d575ec3cdc2c5440587ab92378e94",
          "sha256": "415bac4987044d7ed32e5ae7c3094a9093150848d1b3e439f0088e704006c21b",
          "sha1": "24c5e208a9c7af2295d17c5223d4be8adbcb1ca7",
          "md5": "1fce13608df1c7c629b99889fe75da0d"
        }
      ]
    }
  ]
}
