{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2510.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2510.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2510.3.jar",
          "size": 699996,
          "sha512": "22668cbb94d9ce661f6ffeaf952166fa94f3d61caecfa27d31da78894b0f48823d3e2532456ef4209b8d8b15054c0bae260a379d3465a34b70739ca61cc96bcf",
          "sha256": "098140805865a2c742767a74a16ca0780e593a446b6ae419b7cb69e197a814fd",
          "sha1": "580da3a5c8b0b48c3c770df8347c2f04908453ab",
          "md5": "96da593924297d1af15a1e8bdde90db9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2510.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2510.3.jar",
          "size": 699996,
          "sha512": "22668cbb94d9ce661f6ffeaf952166fa94f3d61caecfa27d31da78894b0f48823d3e2532456ef4209b8d8b15054c0bae260a379d3465a34b70739ca61cc96bcf",
          "sha256": "098140805865a2c742767a74a16ca0780e593a446b6ae419b7cb69e197a814fd",
          "sha1": "580da3a5c8b0b48c3c770df8347c2f04908453ab",
          "md5": "96da593924297d1af15a1e8bdde90db9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2510.3-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2510.3-sources.jar",
          "size": 250761,
          "sha512": "6907e32e517064d5218072449c29fa7880f5f424b4bce7e3358a93a38faeba8569d6c38e349de553b0dccbf8cc8b785a8a82c3089d9aa44d67b25482666e088c",
          "sha256": "72a7932f33caf3acf988e71c1d4c17da1a8534b0868c56f5937aecedcd9b61f9",
          "sha1": "c81d32196dd1701eb60cbdab56770a367020c03f",
          "md5": "ccb9a6d726d957a33131b5e34189ddb9"
        }
      ]
    }
  ]
}
