{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.5.2532.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.5.2532.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.5.2532.0.jar",
          "size": 533818,
          "sha512": "f07658578b8c0e25b3dc3d06c40122f687cbc5c74d0633212be37925fddcd4c40c810f979bb4c69b1d40179ea9ae140d3807a4bfc50ed93cbf2c7848b9833d6b",
          "sha256": "9c75a4a60c9c03712d659da9ff67607fbe20de5f956dc3f4e374a681a1552bee",
          "sha1": "4b8e060771c4013a0776ce9af8228bb6e38dc91e",
          "md5": "85e0e92abaea817ef406517144206023"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.5.2532.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.5.2532.0.jar",
          "size": 533818,
          "sha512": "f07658578b8c0e25b3dc3d06c40122f687cbc5c74d0633212be37925fddcd4c40c810f979bb4c69b1d40179ea9ae140d3807a4bfc50ed93cbf2c7848b9833d6b",
          "sha256": "9c75a4a60c9c03712d659da9ff67607fbe20de5f956dc3f4e374a681a1552bee",
          "sha1": "4b8e060771c4013a0776ce9af8228bb6e38dc91e",
          "md5": "85e0e92abaea817ef406517144206023"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.5.2532.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.5.2532.0-sources.jar",
          "size": 258814,
          "sha512": "a6da1207deac016f8135e2a44366fb41f653df74e1698381ca2656db0fd5a1384bdcf7652791bf80ac5db60734d8a1e1c3ee1dbf226317f35c822ba222b86381",
          "sha256": "236dd8332299779880dfbd4f4ee0e9ee1845316ccb8e16b7f7c1014fdc9a35af",
          "sha1": "929cdb24532da0bcd6908beca6a5df3091dffb5b",
          "md5": "2f249f4abf4d93854159e81d130311e7"
        }
      ]
    }
  ]
}
