{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.3.2513.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2513.8.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2513.8.jar",
          "size": 521819,
          "sha512": "62c3552dd95c2db5f6272afe4d1e680006642757bd324b9dfb0f96c3b9a29ab5524718e493de8a549266e9bcab9fd3a95a74bc5fbf68607b56f18ae9c0dc2be7",
          "sha256": "f142701d4dadec608e9331b460b6c3d050025d6a8c432b0aa359e6d8d6efe1d5",
          "sha1": "62d755653a413838056b46aa937b82e8ea1893d0",
          "md5": "15ab288b413300c58d81338b42e29371"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2513.8.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2513.8.jar",
          "size": 521819,
          "sha512": "62c3552dd95c2db5f6272afe4d1e680006642757bd324b9dfb0f96c3b9a29ab5524718e493de8a549266e9bcab9fd3a95a74bc5fbf68607b56f18ae9c0dc2be7",
          "sha256": "f142701d4dadec608e9331b460b6c3d050025d6a8c432b0aa359e6d8d6efe1d5",
          "sha1": "62d755653a413838056b46aa937b82e8ea1893d0",
          "md5": "15ab288b413300c58d81338b42e29371"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2513.8-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2513.8-sources.jar",
          "size": 251627,
          "sha512": "d8b25d18dffb10149d287c6e31077a8a224d0805dec57ccfb0ac1899f913aa3391cf93639046e31fb7dab8c7859ff067dedf979b69d9a2fdcbea88305bfd91b4",
          "sha256": "9c79dbbcfb0456bac9f20329675e49579a5898b1ba65613fc1c21cd990a0a7f1",
          "sha1": "b62811d097c433ed7bf5bed49793fa588abeaf75",
          "md5": "00b74d2d1ae72b5f324386aad4089ff2"
        }
      ]
    }
  ]
}
