{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2507.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.6.jar",
          "size": 482137,
          "sha512": "e5cd5382c7661a7a30bb4d7868bf3122e8c24ead36cf16beb67fc1c9d58ede6beceb4dbf7b2bab958a99e990ec16a8bb249c9411fd7fd10c4ffbd3693bbffe37",
          "sha256": "4515b18040a18a2f7a7ea305436e9c8520d21a69ee2e22bbdadb67101d856692",
          "sha1": "22ec7913b590e8e5a8c6dd249b9cbe6d489570ed",
          "md5": "5053c80ac5561675119d02c90bea2173"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.6.jar",
          "size": 482137,
          "sha512": "e5cd5382c7661a7a30bb4d7868bf3122e8c24ead36cf16beb67fc1c9d58ede6beceb4dbf7b2bab958a99e990ec16a8bb249c9411fd7fd10c4ffbd3693bbffe37",
          "sha256": "4515b18040a18a2f7a7ea305436e9c8520d21a69ee2e22bbdadb67101d856692",
          "sha1": "22ec7913b590e8e5a8c6dd249b9cbe6d489570ed",
          "md5": "5053c80ac5561675119d02c90bea2173"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.6-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.6-sources.jar",
          "size": 244242,
          "sha512": "5895e6ff73f10f726770a1defa314d0cc1cab497dede0d4f42234552f70885f4ffbc4757bd23ac1e6ff7d49d53fffb60e2a34860519a3a0e32047393a22e0207",
          "sha256": "86641a1571fbf175a68c4d01554dd20b58e77ac9d4547bbd0bff40abdae9761b",
          "sha1": "147f35b81e60821328f514a0d98076291b7aaf66",
          "md5": "aefae5f572225eadb661d6471687cff4"
        }
      ]
    }
  ]
}
