{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2507.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.1.jar",
          "size": 490907,
          "sha512": "843d83f6bf186fed74f419fb7d33eb58c8dc3cb83dcb87409809d1b30a83877dd2139d464f6e78d42d35dfe7bd125afbfee16b92a2425f5dc1b520a572902f25",
          "sha256": "909ea45d2c5b44531745fc830e4bc41cc2d0743540b7e85d508ffbeafa903ab7",
          "sha1": "2d7833963d668b62a41561f98b2d10019c80fa24",
          "md5": "6f3a44aeedd162417d66642a56e05939"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.1.jar",
          "size": 490907,
          "sha512": "843d83f6bf186fed74f419fb7d33eb58c8dc3cb83dcb87409809d1b30a83877dd2139d464f6e78d42d35dfe7bd125afbfee16b92a2425f5dc1b520a572902f25",
          "sha256": "909ea45d2c5b44531745fc830e4bc41cc2d0743540b7e85d508ffbeafa903ab7",
          "sha1": "2d7833963d668b62a41561f98b2d10019c80fa24",
          "md5": "6f3a44aeedd162417d66642a56e05939"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.1-sources.jar",
          "size": 241393,
          "sha512": "e835f811b4c51b18ce5e581e24899cab8bf6e89083a4cdf2550160c589f4ba0933acf71a0df119e62adcdba45d566a520bcadec084617974fbe78e5c780a127a",
          "sha256": "8f9ddea045b095e7eb4febe1542b94e14922d631836c29756b1232228939dd8c",
          "sha1": "3201f9e79bcdb67a2051a81a3a6e9239fa0e9d78",
          "md5": "bb8dcdb74f33966e7d89461576eadc91"
        }
      ]
    }
  ]
}
