{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3-pre"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8-pre.jar",
          "url": "legacy-forge-1.21.1-1.8-pre.jar",
          "size": 14401818,
          "sha512": "decd3aec2c8df04c74f41c2110e5634cda22f57d734d01cd48eb4cd9d93863eebbc910a1a4c9441d198ed780dd273f0e15f24b3c86d1a3984be9c544309156de",
          "sha256": "e8a0119e71e31fa3b9bd17f939777ba388cd06be336d8729896ba7f11dece132",
          "sha1": "67a5f12f6102fafac7c12e5e772ce4db46028d6c",
          "md5": "1e9628dcf9b562cf8184adff87f71861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3-pre"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8-pre.jar",
          "url": "legacy-forge-1.21.1-1.8-pre.jar",
          "size": 14401818,
          "sha512": "decd3aec2c8df04c74f41c2110e5634cda22f57d734d01cd48eb4cd9d93863eebbc910a1a4c9441d198ed780dd273f0e15f24b3c86d1a3984be9c544309156de",
          "sha256": "e8a0119e71e31fa3b9bd17f939777ba388cd06be336d8729896ba7f11dece132",
          "sha1": "67a5f12f6102fafac7c12e5e772ce4db46028d6c",
          "md5": "1e9628dcf9b562cf8184adff87f71861"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8-pre-sources.jar",
          "url": "legacy-forge-1.21.1-1.8-pre-sources.jar",
          "size": 13586665,
          "sha512": "658b24f8e1da5b5d570dabbe832c1991e02d172eaf2f5930c32147babd6b547f017d024d0333ca5268c42013e333b8413cf676daff134fd551a8378e65d6c04d",
          "sha256": "829a5f84f09698f29de69d6b351bd6134b3dc910cd3e842325b098bff0ff407b",
          "sha1": "f5dc149be8592a163de4fea0e351f41d35256ef3",
          "md5": "3526a2b201369d0a9ee67e8a9fb490b8"
        }
      ]
    }
  ]
}
