{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.0.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2514.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2514.0.jar",
          "size": 18287867,
          "sha512": "9fc92637d762ec77250709db77697157621b3fd0b4cd046b054ac0e6fb26eaaf028d686c52f43b380f8e3d570ed4ba85b1ad0e87ddca1b05db181be37549bff4",
          "sha256": "e31c91922fdf3f991139946d75668597400299efb6347986fb10ce23a94cf34c",
          "sha1": "66429f15e02c1124722ba24818a805e6fa759ed6",
          "md5": "a1171d805231cc1aef9bdc3c43d5e34c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2514.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2514.0.jar",
          "size": 18287867,
          "sha512": "9fc92637d762ec77250709db77697157621b3fd0b4cd046b054ac0e6fb26eaaf028d686c52f43b380f8e3d570ed4ba85b1ad0e87ddca1b05db181be37549bff4",
          "sha256": "e31c91922fdf3f991139946d75668597400299efb6347986fb10ce23a94cf34c",
          "sha1": "66429f15e02c1124722ba24818a805e6fa759ed6",
          "md5": "a1171d805231cc1aef9bdc3c43d5e34c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2514.0-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2514.0-sources.jar",
          "size": 17432548,
          "sha512": "a13e944334224c426d4087595e591c53c07a54fc1845e0723aa9c6e72f6cea47382c72fdb0dec1d226ed4c750468d0d4c10637b5b981a358671f20fd1bbd17c2",
          "sha256": "055c41e96d5149580d8f2bb20f9ab80f46e66bebecdd3e8ebf1b90ea53b61f97",
          "sha1": "db9efccea67f8cc16e6b05d339c035a8ff793fd8",
          "md5": "b9ec6b3e75c66fb7fc9a1bfb927b54b4"
        }
      ]
    }
  ]
}
