{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2509.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2509.1.jar",
          "size": 495632,
          "sha512": "62069f08d11de48dde0eee9dd51a4cb37a87ac6debf508f546870cd6f69daacb03978d7efa1650c3785aae83152e2db82ee6915264064047161a908da301301f",
          "sha256": "3d05f035bf1c6a1c1e711e52f730d874fbecba23e50e5976105311ef28dd1c2b",
          "sha1": "46b0c33d86a0b4f2491ccf52baec84f8d5d90f6c",
          "md5": "05561d7c830c9b626f160a321385de73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2509.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2509.1.jar",
          "size": 495632,
          "sha512": "62069f08d11de48dde0eee9dd51a4cb37a87ac6debf508f546870cd6f69daacb03978d7efa1650c3785aae83152e2db82ee6915264064047161a908da301301f",
          "sha256": "3d05f035bf1c6a1c1e711e52f730d874fbecba23e50e5976105311ef28dd1c2b",
          "sha1": "46b0c33d86a0b4f2491ccf52baec84f8d5d90f6c",
          "md5": "05561d7c830c9b626f160a321385de73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2509.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2509.1-sources.jar",
          "size": 248302,
          "sha512": "f00600668ad4ab4816e40f923500a4f23c2c05920baa73c4403150ee44074aef6844c0adca06a20f48a1b42d73742b2d39459bd49635ca722cbb71e64d434435",
          "sha256": "13dee226696c721f2f5b91d56cdc1df14436673b23d8dd43a5729caa028f0802",
          "sha1": "070d06086a14e5a640ce806b41410a5d50e80d3f",
          "md5": "608ed1d70391ef374d1f5e470b97284b"
        }
      ]
    }
  ]
}
