{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.1-1.1.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.1.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.1.jar",
          "size": 643997,
          "sha512": "363ecd9523128bee4e2779c8bf38a5dedfc663b9733baa5e8ed5256a7e10876183362082288c8653129867c8320a1ae2cc61c31b87f25fa97e5b1d3318cce615",
          "sha256": "9987d51fb76d4c45d1f56cb29829b7f205d65ff187506137bbf10eb7d2ee360d",
          "sha1": "e84aeac2045bb2aa8e01a79ba0f28d1056bc0d46",
          "md5": "10f773aefe1d2b7abaf5339a9ba9e66b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.1.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.1.jar",
          "size": 643997,
          "sha512": "363ecd9523128bee4e2779c8bf38a5dedfc663b9733baa5e8ed5256a7e10876183362082288c8653129867c8320a1ae2cc61c31b87f25fa97e5b1d3318cce615",
          "sha256": "9987d51fb76d4c45d1f56cb29829b7f205d65ff187506137bbf10eb7d2ee360d",
          "sha1": "e84aeac2045bb2aa8e01a79ba0f28d1056bc0d46",
          "md5": "10f773aefe1d2b7abaf5339a9ba9e66b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.1-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.1-sources.jar",
          "size": 585390,
          "sha512": "9b343d84910d2a71072c51fc64563e62ec57bd37f344cbb525fa29d6037b180a8524f26a7ad902909f839030897d09bc792d63b47e29e1e5027f06795bb82ad9",
          "sha256": "903d30a108035586b9db42d9ffe6a2d07a60ebe5e7fbd5782aaf1a07356a461b",
          "sha1": "37d2f0869ab734257fa712f144143b62538163b6",
          "md5": "c4812b9aa5d8b2c8c5ef73eb7c6d1485"
        }
      ]
    }
  ]
}
