{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.5-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2518.5.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2518.5.jar",
          "size": 19702089,
          "sha512": "bcdd61a76a961590de81897e1533fb8c3a54c8aa4b90a1cb297533b2ebfa2c45ee3562319a4eb0af2a306f0fdfe82e7bb1af8aad9a42f47a703623acdd14c632",
          "sha256": "cbcbad5c69c3c844a180668034027f6d15060073914b18c70ad71c21e3419302",
          "sha1": "9200e63d3f53c2bd951bd1718eefe9baf7f1ba42",
          "md5": "c0b45cf10f3d6f06e0bbfa7d4b8694b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "14.0.0-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2518.5.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2518.5.jar",
          "size": 19702089,
          "sha512": "bcdd61a76a961590de81897e1533fb8c3a54c8aa4b90a1cb297533b2ebfa2c45ee3562319a4eb0af2a306f0fdfe82e7bb1af8aad9a42f47a703623acdd14c632",
          "sha256": "cbcbad5c69c3c844a180668034027f6d15060073914b18c70ad71c21e3419302",
          "sha1": "9200e63d3f53c2bd951bd1718eefe9baf7f1ba42",
          "md5": "c0b45cf10f3d6f06e0bbfa7d4b8694b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2518.5-sources.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2518.5-sources.jar",
          "size": 18844027,
          "sha512": "811c006fae6af64e9afdc6e9a49d3728c2404d748c54eb4f1e37960da5bf3990241a1575eafd730a236b914edb9af1c32afbda83636cf9121c390cb71bf0b5ae",
          "sha256": "4246c615ff8e2ebb6b93bad923be0f8d1ebf10f40814ac10623abd39d206b6b0",
          "sha1": "10f64750d8c270c54630102bf0cdbfe88dd97806",
          "md5": "7485c3dbb12b174bfc0568e9bc067d89"
        }
      ]
    }
  ]
}
