{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.5.jar",
          "size": 696836,
          "sha512": "e0ac7d267ec2de7e9cb1193335dc79aeb431ad63d0a85ea56532bd16be59dd76411304d4d9810d1964cb9716b23c7cd520202152ead8a8750958b7a87bb623d9",
          "sha256": "b9a96433426d54f84c7f92586ad72791cc43709ad147c04029b6de9836c4e885",
          "sha1": "f5b90e87ebf9b8ffa03ab2824cb0dc1f4b603a18",
          "md5": "0de60735eb93900e944cbf364889a82b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.5.jar",
          "size": 696836,
          "sha512": "e0ac7d267ec2de7e9cb1193335dc79aeb431ad63d0a85ea56532bd16be59dd76411304d4d9810d1964cb9716b23c7cd520202152ead8a8750958b7a87bb623d9",
          "sha256": "b9a96433426d54f84c7f92586ad72791cc43709ad147c04029b6de9836c4e885",
          "sha1": "f5b90e87ebf9b8ffa03ab2824cb0dc1f4b603a18",
          "md5": "0de60735eb93900e944cbf364889a82b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.5-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.5-sources.jar",
          "size": 253909,
          "sha512": "ac5e5de84de44125e5e512d0948b10ccb77c11e493ac284a715282593c28d2891ce852371e961c8dbf3bb6604a8f57adf2069fa0ef5b740baf376248cefaa5cb",
          "sha256": "a7f7a17a81df0c106d9cc4b10fcba9cc39e89ef17cfb31867c0e6457e874fe8a",
          "sha1": "d6f1ed257aa5c1031b40257bc565866412b8693b",
          "md5": "a1842254c0ef384fc9f49353e7bd1340"
        }
      ]
    }
  ]
}
