{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.9.jar",
          "size": 548230,
          "sha512": "2356bf6b55ffe8d69d62d8831986fee25f7cab47d0f35a1cd174cd743a35ffc9d06ccf66f3fc843504c09093289fb98ad5b345309ea0debc13c7e9f5a062ab2d",
          "sha256": "c69089dcace74a0f9ff2b017cf8bb0323e448822e21acbb07777ed3ed2f965ae",
          "sha1": "15647e9452116aae178289005de99d8b11646c12",
          "md5": "da0a974cb096586f8792673cfcf1df25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.9.jar",
          "size": 548230,
          "sha512": "2356bf6b55ffe8d69d62d8831986fee25f7cab47d0f35a1cd174cd743a35ffc9d06ccf66f3fc843504c09093289fb98ad5b345309ea0debc13c7e9f5a062ab2d",
          "sha256": "c69089dcace74a0f9ff2b017cf8bb0323e448822e21acbb07777ed3ed2f965ae",
          "sha1": "15647e9452116aae178289005de99d8b11646c12",
          "md5": "da0a974cb096586f8792673cfcf1df25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.9-sources.jar",
          "size": 256802,
          "sha512": "51a8e86944c9cce0dc532fd02c3f81bcecf3245b84cd289061d6f6d1d8fb433e085de9ceb86d53c0f49fe16554042441fa7cd971f3daba2d4573b93fe91ebb12",
          "sha256": "8ccba2cd62adf95aa1829f4158e3f6150a0305a2e36d613af496370ee92ed41e",
          "sha1": "9e41c122cc64886dc2d0d590a6d8ab9eab2d7f2c",
          "md5": "c87d6327ae87be33aa1a9011ecb422ec"
        },
        {
          "name": "factory_api-neoforge-1.21.3-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.9-sources.jar",
          "size": 256802,
          "sha512": "51a8e86944c9cce0dc532fd02c3f81bcecf3245b84cd289061d6f6d1d8fb433e085de9ceb86d53c0f49fe16554042441fa7cd971f3daba2d4573b93fe91ebb12",
          "sha256": "8ccba2cd62adf95aa1829f4158e3f6150a0305a2e36d613af496370ee92ed41e",
          "sha1": "9e41c122cc64886dc2d0d590a6d8ab9eab2d7f2c",
          "md5": "c87d6327ae87be33aa1a9011ecb422ec"
        }
      ]
    }
  ]
}
