{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2507.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.14.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.14.jar",
          "size": 496171,
          "sha512": "50e59e47b9760e9dbbb81d3eb19fdc11ca7e43cd9586504d63186049bfcc7b56525f28c9c8c7b48465186cdb5ad8870e393ab51cae2fd6f6e40ab8fea55ddec2",
          "sha256": "bc27104b8ac221f85a969c05084b26bdcfd557ae689519cf61d316da7dff580e",
          "sha1": "f642b888c7986233d826d6911285f751ddc02486",
          "md5": "10e816350557c662a0ef222510ae0d2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.14.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.14.jar",
          "size": 496171,
          "sha512": "50e59e47b9760e9dbbb81d3eb19fdc11ca7e43cd9586504d63186049bfcc7b56525f28c9c8c7b48465186cdb5ad8870e393ab51cae2fd6f6e40ab8fea55ddec2",
          "sha256": "bc27104b8ac221f85a969c05084b26bdcfd557ae689519cf61d316da7dff580e",
          "sha1": "f642b888c7986233d826d6911285f751ddc02486",
          "md5": "10e816350557c662a0ef222510ae0d2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.14-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.14-sources.jar",
          "size": 244774,
          "sha512": "ab56da2f54d3740885ec2825f93888a7b0cea3b51c5ecbb7a070d42f8199495a94ab7b9aad43dc33f7fa0cec54ac644b563276d5fd251fe700f920a2da999cd4",
          "sha256": "fd1e6b8d8931017dd60ea61fb55220d5d691c405fc8cd09be095f98f548e4c32",
          "sha1": "84ee91353f3f332c46e0c1944dcd3cda38299829",
          "md5": "2559c6bc06f6e00442447022246ecb9c"
        }
      ]
    }
  ]
}
