{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2506.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.1.jar",
          "size": 490879,
          "sha512": "46924b136c06d456c8b32997f53ee384b65119b96c77270de31d9dae8a365fe954f57c4d02d2a43ce3c87739ddb0d1e539bb5ce5d9a7bf0771f26e6da79a8744",
          "sha256": "26cf90c26d4e9b92d44b3de2f298ef8857ecd8477505a609dcde7e02ca4c2578",
          "sha1": "fd87b5319a87eb78ed302936f47cfa707c2ed6bf",
          "md5": "e86f99d9a40d6a2b1b3d20396ac12953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.1.jar",
          "size": 490879,
          "sha512": "46924b136c06d456c8b32997f53ee384b65119b96c77270de31d9dae8a365fe954f57c4d02d2a43ce3c87739ddb0d1e539bb5ce5d9a7bf0771f26e6da79a8744",
          "sha256": "26cf90c26d4e9b92d44b3de2f298ef8857ecd8477505a609dcde7e02ca4c2578",
          "sha1": "fd87b5319a87eb78ed302936f47cfa707c2ed6bf",
          "md5": "e86f99d9a40d6a2b1b3d20396ac12953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.1-sources.jar",
          "size": 241400,
          "sha512": "a2a2cf569e56c25eeff249f572759a8e3d7bdfe651d7f15a23b3f64be05a35a60be0c11d1b7b3d72a4c4745a7cd827195ff7e92f237ec899203597bafd99aa66",
          "sha256": "b9c9d4c227fe24cd5047db044ff0458d0643ab1a31fec0d1c5c774417934dfc6",
          "sha1": "25d1a31bd0cccc024d0b0d835f68a4c78dcbd55a",
          "md5": "f03ff0bb9706a0e5b28d92ac75a36ea9"
        }
      ]
    }
  ]
}
