{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2513.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.4.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.4.jar",
          "size": 704004,
          "sha512": "85fad52301e63fddcadfd44260d73a86692430e37466df66d4ccf9830817c8f255575203813d6b5bb73c551bc550a7404df750a536287b483f840c9683fbb45c",
          "sha256": "85067f5932386e0a7676ad017561fbd152971b762bc45a0574f8ebd8660f1d2a",
          "sha1": "656cb0fba82bf5a46edfcd7e811e56a854da753a",
          "md5": "22b579aedf3f1bdfd87dfc4286700b37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.4.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.4.jar",
          "size": 704004,
          "sha512": "85fad52301e63fddcadfd44260d73a86692430e37466df66d4ccf9830817c8f255575203813d6b5bb73c551bc550a7404df750a536287b483f840c9683fbb45c",
          "sha256": "85067f5932386e0a7676ad017561fbd152971b762bc45a0574f8ebd8660f1d2a",
          "sha1": "656cb0fba82bf5a46edfcd7e811e56a854da753a",
          "md5": "22b579aedf3f1bdfd87dfc4286700b37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2513.4-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2513.4-sources.jar",
          "size": 252376,
          "sha512": "e2fb26bd77b4fd84e3f64aba07d41273f0455eb95226dcfb62b1e8b8c210f348bf71ff9751f58604dd8034acdf7be0b6707fccb7b05111c7c7edd98b0f247d39",
          "sha256": "45ece19a8ab2a262d1724b3d3fecb512892077e7d52568fee006692685423cf8",
          "sha1": "af6a619774b50aee1b7ecd1b2418f465250b20d2",
          "md5": "e83db13b6a8d1573566b90303d1a0bd5"
        }
      ]
    }
  ]
}
