{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2517.0.jar",
          "size": 541839,
          "sha512": "35996213b4ef0dca2f3cd9614ef46144c12e7392dd39cdff55a4b58bd4ffcd96d5cabb7633cfce7bc9bf23f1f0536c3a078fa372f7e2449448281892db659c4a",
          "sha256": "7089c554f766cb2f67a543f4222d87a588cfa84ad953cbcb7e31557e96ecd587",
          "sha1": "16189e527e1a972afc4eaeecec75e6edd1ae88e0",
          "md5": "4839a26e0bc372808f9954d98b7d1785"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2517.0.jar",
          "size": 541839,
          "sha512": "35996213b4ef0dca2f3cd9614ef46144c12e7392dd39cdff55a4b58bd4ffcd96d5cabb7633cfce7bc9bf23f1f0536c3a078fa372f7e2449448281892db659c4a",
          "sha256": "7089c554f766cb2f67a543f4222d87a588cfa84ad953cbcb7e31557e96ecd587",
          "sha1": "16189e527e1a972afc4eaeecec75e6edd1ae88e0",
          "md5": "4839a26e0bc372808f9954d98b7d1785"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2517.0-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2517.0-sources.jar",
          "size": 252715,
          "sha512": "96f763e52337ec6e4267e436398380868a37fbedd9008e0b73d5d85a061ddef01d5b67991f984111d2f18f77de6f8b64f8e2724e8fb9e7539a29743d387e893b",
          "sha256": "8e484e02dfa12183957239945acfa0c6d732cb9f94ed2a3631e76e37ce8ac919",
          "sha1": "03d2ca4e478d0bb1ee4e428bcf4890f51d5c7f7b",
          "md5": "66fff3f151f3a3ac41e97716a19348d7"
        }
      ]
    }
  ]
}
