{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "size": 714675,
          "sha512": "f9e6919d16a58d9f7e4a6469a38279058c21775909e69b47eff79b458c6f37bb994d5618a316d7cfcc12fe600a7c272f8995219d8944f1fdf311b4b8df873873",
          "sha256": "307f7d40fff92a625fc096cc8779abcc9030e3469269f5909644eda6c5169d46",
          "sha1": "98c12db016dda5326faa83dde6c132d32b24f0bd",
          "md5": "a6c795456a5a2613b28a19798e94cebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "size": 714675,
          "sha512": "f9e6919d16a58d9f7e4a6469a38279058c21775909e69b47eff79b458c6f37bb994d5618a316d7cfcc12fe600a7c272f8995219d8944f1fdf311b4b8df873873",
          "sha256": "307f7d40fff92a625fc096cc8779abcc9030e3469269f5909644eda6c5169d46",
          "sha1": "98c12db016dda5326faa83dde6c132d32b24f0bd",
          "md5": "a6c795456a5a2613b28a19798e94cebf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.5-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.5-sources.jar",
          "size": 254199,
          "sha512": "2d547e4683a76ee4f013440bc6f0ba7d07cbc4923551b39a9b4ec0036779dc5f558e6a3837fc81e23d8b7a83ed8feaca49f48ab111038fa93bf454e75f7f2788",
          "sha256": "8444b27febf14c85a5211538e8e07e22475f4b7f70d62af853665ec221e8fbca",
          "sha1": "bfc14ce23a57d4950061523f14c24c5083d5a1fd",
          "md5": "9bfd0469768eb0f3e9da818e40150b27"
        }
      ]
    }
  ]
}
