{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "size": 715296,
          "sha512": "1a01740b5efaa55ca28eff0d7df09fbbdd3ed7f048396650886573db52bb497bc82bb2a61974da194da57dfb55558066c7274ea8b17beea985d8ee9ccd7f06ca",
          "sha256": "aee8d1f899973bcfd4230f430cfcf832a288e8edb7d4b8ab3f1e33eccb175a46",
          "sha1": "62e70ecc94229c68a0b8e4ad8476a865c914c073",
          "md5": "3abba77e3786515c9925143c042f4ccb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.5.jar",
          "size": 715296,
          "sha512": "1a01740b5efaa55ca28eff0d7df09fbbdd3ed7f048396650886573db52bb497bc82bb2a61974da194da57dfb55558066c7274ea8b17beea985d8ee9ccd7f06ca",
          "sha256": "aee8d1f899973bcfd4230f430cfcf832a288e8edb7d4b8ab3f1e33eccb175a46",
          "sha1": "62e70ecc94229c68a0b8e4ad8476a865c914c073",
          "md5": "3abba77e3786515c9925143c042f4ccb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.5-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.5-sources.jar",
          "size": 254240,
          "sha512": "590e2f04556eb4f1ad50763d7e2980a401acd39d79422e7b8ad9de8d24d3bcca54acf88ce008a2714a0a17773fb93ebee3a130474fba3309cf67cf6819a45e3d",
          "sha256": "ff6917900a1a53aeffc37e7b102788e51eddb7120e3c3e7c2e0c9f0ca03c3c7e",
          "sha1": "fd250b2defa20593d677251da2362cc27680be76",
          "md5": "980f82a367953dd1435a9868fbb54412"
        }
      ]
    }
  ]
}
