{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2500.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2500.3.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2500.3.jar",
          "size": 356221,
          "sha512": "a4a7faf01a433273aa2b5001128d69b644ca94537277429cf0a9826209695527993bba2c534c030cea46495616eba727463f95fec30576bc954f7d63f23d2207",
          "sha256": "8a57353e218ededeb4abd7424e36137c98031f149e2ebf32306a2e09a98a3fb8",
          "sha1": "2d2f22b17552edf9caa67d6bc316fbe640b60b88",
          "md5": "f0d54e6ca7bb75de0d1ee2973e9c9bfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2500.3.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2500.3.jar",
          "size": 356221,
          "sha512": "a4a7faf01a433273aa2b5001128d69b644ca94537277429cf0a9826209695527993bba2c534c030cea46495616eba727463f95fec30576bc954f7d63f23d2207",
          "sha256": "8a57353e218ededeb4abd7424e36137c98031f149e2ebf32306a2e09a98a3fb8",
          "sha1": "2d2f22b17552edf9caa67d6bc316fbe640b60b88",
          "md5": "f0d54e6ca7bb75de0d1ee2973e9c9bfe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2500.3-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2500.3-sources.jar",
          "size": 192095,
          "sha512": "c84e2514efdd15d7906604100030f0095f953eae2ba69936e84e7936e7b131ab4e33ea914b4e00d8a5d03753a1aa7203365758de9950ce846a89420d2ef66741",
          "sha256": "7a8fd7ef353af8eff02a99f2d80cef5e50534687aa43225382968f414b2bba6a",
          "sha1": "e0b87f8900689501347464ae025b96662318bb9c",
          "md5": "a19cba2bb62a1a719c9b4f247a014599"
        }
      ]
    }
  ]
}
