{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.7.10.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.4.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.4.jar",
          "size": 14290299,
          "sha512": "b553ec745484189b42a240b7b591aa03bd4b25356e994e897061c6c8b15764e91ae43405afa13ae9f90b77e1b1d0234c64160116419626d4f66a41b910f4b075",
          "sha256": "cfdd7b2c3d12af151850e9e930f5115a423fea4fc7cc12b32079aaee75ea53ce",
          "sha1": "30944e158388e6e1fc4caa612eb962629c14a28f",
          "md5": "c90bcc967c5436592895a8f03eeb45b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.4.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.4.jar",
          "size": 14290299,
          "sha512": "b553ec745484189b42a240b7b591aa03bd4b25356e994e897061c6c8b15764e91ae43405afa13ae9f90b77e1b1d0234c64160116419626d4f66a41b910f4b075",
          "sha256": "cfdd7b2c3d12af151850e9e930f5115a423fea4fc7cc12b32079aaee75ea53ce",
          "sha1": "30944e158388e6e1fc4caa612eb962629c14a28f",
          "md5": "c90bcc967c5436592895a8f03eeb45b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.4-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.4-sources.jar",
          "size": 13463689,
          "sha512": "33d58a90c97d82cba8b0a36f606f93a413b7f014e3fc17bfe56ad5339ca08a1f8a67a86d7fb942163444699ab8e8d93a332ed85b76abbdcd2abad786a57bee11",
          "sha256": "e3cf823d49e795148f854203172abfbeade5663206801ace45301aa5028513d2",
          "sha1": "40712b88e6b23c5c3e3282e400e9e1e3e27fa9ca",
          "md5": "8eb087a0b0b27591be01095831ee7b48"
        }
      ]
    }
  ]
}
