{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2518.5.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2518.5.jar",
          "size": 19734895,
          "sha512": "714d47ff415773f4279719faf0c3c703f6a70b8848d6a6b66c2338eefdff764fdfaeda49af3af378f6c8d0057d4fac8cbdc061caf23f1c70be5db337dbcf4887",
          "sha256": "194bcd5c7b611b29dcf245c338f6d334a3ae111b89fde71e70a1dd016e737fa7",
          "sha1": "a20e4b904918dfc7de8500c4e64aa375c0ed435b",
          "md5": "8c1b0344b8a4081d8b0d906d9c6cf12a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2518.5.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2518.5.jar",
          "size": 19734895,
          "sha512": "714d47ff415773f4279719faf0c3c703f6a70b8848d6a6b66c2338eefdff764fdfaeda49af3af378f6c8d0057d4fac8cbdc061caf23f1c70be5db337dbcf4887",
          "sha256": "194bcd5c7b611b29dcf245c338f6d334a3ae111b89fde71e70a1dd016e737fa7",
          "sha1": "a20e4b904918dfc7de8500c4e64aa375c0ed435b",
          "md5": "8c1b0344b8a4081d8b0d906d9c6cf12a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2518.5-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2518.5-sources.jar",
          "size": 18853956,
          "sha512": "df621afc8d202060e52325ac6523b30ff2958e9c366441bffb66246974c6c8caac9719b3705328594154542920e0c5c76b22a2cee237d78174e9a19fd3bb9133",
          "sha256": "444cac3ad2615736fd57433f58a0cc142089b4cada5d26776abf4f68c34d08b6",
          "sha1": "4d869643c80506e2b123b87b6bb96fa195f181d7",
          "md5": "a95628d40f09ec794600ca3f3300d3a7"
        }
      ]
    }
  ]
}
