{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.13.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.13.jar",
          "size": 481924,
          "sha512": "7cdc03e34ecd3db815fec1d9537774f4bfff295794dd1976e64bf0902f610056610d5b2c48b025ba87797b546c62be5ff069ef7481cb6839d9fbc7d2ad63c31e",
          "sha256": "d0d083327b6512522123851c8120ba41034163351127f60bbdf4dd7ff2b9aef1",
          "sha1": "463cb9d9394a9471d58d0cf801f4b0b3cad3677b",
          "md5": "5b2cbb2f6b823a5a74ce2808b2900bad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.13.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.13.jar",
          "size": 481924,
          "sha512": "7cdc03e34ecd3db815fec1d9537774f4bfff295794dd1976e64bf0902f610056610d5b2c48b025ba87797b546c62be5ff069ef7481cb6839d9fbc7d2ad63c31e",
          "sha256": "d0d083327b6512522123851c8120ba41034163351127f60bbdf4dd7ff2b9aef1",
          "sha1": "463cb9d9394a9471d58d0cf801f4b0b3cad3677b",
          "md5": "5b2cbb2f6b823a5a74ce2808b2900bad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.13-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.13-sources.jar",
          "size": 244635,
          "sha512": "74bf88e3d3eedf70bc36d84140f1e41067fcd2229542bc8827b5402b6f54200796f8396ccc88b1b85de0fc0e234503753fd768f3db474455e90fa19c2c16aeae",
          "sha256": "b66a5bc694f441be0dc069b893a7ca65fd3c7b1915d0ab86783b191d092dfa5b",
          "sha1": "1fa090c3c07e525f95af41a25643dd1e33b28e5e",
          "md5": "c88acfbe401bda57530fba0d9be08db6"
        }
      ]
    }
  ]
}
