{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.7.10.2501.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2501.0.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2501.0.jar",
          "size": 11904659,
          "sha512": "e657b4c97f71f90fc7a28a4e7ad3ccbce0fb0e5e09c22c6505ef834cd93c4bf4fd692add20f877616486ef14d504c832415634787e4f90198c357fe9857829b4",
          "sha256": "8bf5a9d74b0076c62cec873f57f9a15d4aded58fdcdd49c646d56f5d587e250d",
          "sha1": "1d5c65b4b659779f924fd8d74aa1d6f8c1ab0362",
          "md5": "4d3cd7ad4bfc601316604b9646578226"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2501.0.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2501.0.jar",
          "size": 11904659,
          "sha512": "e657b4c97f71f90fc7a28a4e7ad3ccbce0fb0e5e09c22c6505ef834cd93c4bf4fd692add20f877616486ef14d504c832415634787e4f90198c357fe9857829b4",
          "sha256": "8bf5a9d74b0076c62cec873f57f9a15d4aded58fdcdd49c646d56f5d587e250d",
          "sha1": "1d5c65b4b659779f924fd8d74aa1d6f8c1ab0362",
          "md5": "4d3cd7ad4bfc601316604b9646578226"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2501.0-sources.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2501.0-sources.jar",
          "size": 11121824,
          "sha512": "25a3fc8b2a736f81fa0d65d3cbfd4e286dc094994c75cdfc24d85a5f1991e52cb5a8487b325df14b1b56c9bcd30fce71b95cf0fd424137e20cc2cdbc6a9555f3",
          "sha256": "a8d5391e325e8ff2c6197f6d027b1579fa64ee21799ce69ce643f1be1173dc3a",
          "sha1": "0d0090559bfdf46d9119fde75a080d5c8cf31bda",
          "md5": "cb4cf4461e83d00e83a4329b6042fe30"
        }
      ]
    }
  ]
}
