{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.1-2.2.2501.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2501.12.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2501.12.jar",
          "size": 414819,
          "sha512": "649a40ecf10cc3ad5a5a9d25bbba05c36f9a438d612038050f1bc50ba3c7e5a1c31ee6c88fa65061af737138a58c82025a568e2ed4cafab2366bd63828a45ff3",
          "sha256": "7db15b1e708359a5512ff64c6d3fdf81d51b0b6231bfaaec77536d27ce38fa89",
          "sha1": "d4b7b04b987e304a3a187307b7ea2399eb3dc2f6",
          "md5": "bfcdcb1d0d9b1d36305afa79c574b1a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2501.12.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2501.12.jar",
          "size": 414819,
          "sha512": "649a40ecf10cc3ad5a5a9d25bbba05c36f9a438d612038050f1bc50ba3c7e5a1c31ee6c88fa65061af737138a58c82025a568e2ed4cafab2366bd63828a45ff3",
          "sha256": "7db15b1e708359a5512ff64c6d3fdf81d51b0b6231bfaaec77536d27ce38fa89",
          "sha1": "d4b7b04b987e304a3a187307b7ea2399eb3dc2f6",
          "md5": "bfcdcb1d0d9b1d36305afa79c574b1a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.2501.12-sources.jar",
          "url": "factory_api-fabric-1.20.1-2.2.2501.12-sources.jar",
          "size": 196084,
          "sha512": "07c3d13a491d85fc57bb32334b048d99462cc07990db2f75e7a565de815d877db05e3b4dbddaba8731c4c213a7f812916d8f914c7f6da0f51bf241753669124f",
          "sha256": "1875767eed480381dfa77894c3339e39dbaa1edb6f672516f3a638913d70cc86",
          "sha1": "1768b710f20cdb9541e248e301fdf63cc84168f9",
          "md5": "4ddc3a744c30eb07df15804f397bd492"
        }
      ]
    }
  ]
}
