{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.7.2616.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2616.1.jar",
          "size": 551894,
          "sha512": "e359fab3a256759b69fb5e641d177721222b82fd4c40a4a572f43c52d94cc69a94eae3a0116b875f2596a1359f440f00ed703de5fe9834e7532f2579e2fc8348",
          "sha256": "ff60601bea394dc586001be12de36983ebe2d4e97f0ab5a8938748a160ec4cb0",
          "sha1": "571f3c789404822de6069150f75cc2cda4f0ae6a",
          "md5": "9607c2b311592c68cdfcab59fd463a36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2616.1.jar",
          "size": 551894,
          "sha512": "e359fab3a256759b69fb5e641d177721222b82fd4c40a4a572f43c52d94cc69a94eae3a0116b875f2596a1359f440f00ed703de5fe9834e7532f2579e2fc8348",
          "sha256": "ff60601bea394dc586001be12de36983ebe2d4e97f0ab5a8938748a160ec4cb0",
          "sha1": "571f3c789404822de6069150f75cc2cda4f0ae6a",
          "md5": "9607c2b311592c68cdfcab59fd463a36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2616.1-sources.jar",
          "size": 256793,
          "sha512": "d68040f673b0e757c27c5c3fb40b47d9970d9f4243ef1c444a2442ded8e9ed19183d4f359c16bb1debcf73927836793f0e0ab068626e4e1d2ef64b2205b27204",
          "sha256": "0036f55bf1ff0068f2fa5b7a0cdf51f77d7992eb9bbcf6958ba257ded03954de",
          "sha1": "c4428a26676e111c178958b4e1d3283b8d29128d",
          "md5": "4b0860cb8d3433450652cdaabe3ac007"
        },
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2616.1-sources.jar",
          "size": 256793,
          "sha512": "d68040f673b0e757c27c5c3fb40b47d9970d9f4243ef1c444a2442ded8e9ed19183d4f359c16bb1debcf73927836793f0e0ab068626e4e1d2ef64b2205b27204",
          "sha256": "0036f55bf1ff0068f2fa5b7a0cdf51f77d7992eb9bbcf6958ba257ded03954de",
          "sha1": "c4428a26676e111c178958b4e1d3283b8d29128d",
          "md5": "4b0860cb8d3433450652cdaabe3ac007"
        }
      ]
    }
  ]
}
