{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.5-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2518.3.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2518.3.jar",
          "size": 19784969,
          "sha512": "50a8e36a65b39a57575bdf36be128ed47543c36a7575552304fd339b0f61065343bf26ee92320ca6e3f87380950771bd0f98c11a2fcba6cd2ab77efd06d395d1",
          "sha256": "e6beb53d8d93a58b46e96e10dc15743497bbc0bafaf142bf39cd6f46303114e5",
          "sha1": "0b850be9219e0e52a2c8d480072e644716bf66af",
          "md5": "8b1ee597e4cbc25164d63dd1556bfcce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2518.3.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2518.3.jar",
          "size": 19784969,
          "sha512": "50a8e36a65b39a57575bdf36be128ed47543c36a7575552304fd339b0f61065343bf26ee92320ca6e3f87380950771bd0f98c11a2fcba6cd2ab77efd06d395d1",
          "sha256": "e6beb53d8d93a58b46e96e10dc15743497bbc0bafaf142bf39cd6f46303114e5",
          "sha1": "0b850be9219e0e52a2c8d480072e644716bf66af",
          "md5": "8b1ee597e4cbc25164d63dd1556bfcce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2518.3-sources.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2518.3-sources.jar",
          "size": 18904540,
          "sha512": "34b3372b9491302eb65e7908f7c39061a7824e8602666a019332c183e22f8306d481468144a0e4e8a44f97d3bebf4de31588f009ab9e5f5386092731dda593df",
          "sha256": "ba86e382eb8ffd4f8349095f8cb6d34c20e68aa5a83a14e9d83c280330d1a8c7",
          "sha1": "f7c63c44ae74c1bf815f3a31af084a9a5abee300",
          "md5": "0a2cd3fde41c2bbd1c43d23a6abd860b"
        }
      ]
    }
  ]
}
