{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2516.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2516.0.jar",
          "size": 693042,
          "sha512": "3812932710ae0656516fd4a426941469793b56f30e50ee314440473274e13bd74a64dd5b8852e4a976909188feabf1c7aa96fe6551a414834a040ad8ad5a4963",
          "sha256": "34f2c34d15c381ecff29346680c952f9bc696b4e021bf400f6a059ba95eee2c2",
          "sha1": "0e2928054c94970328c4b6b46ff47329f55ec3fe",
          "md5": "6838200d22741aaf8eb5427ba86236c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2516.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2516.0.jar",
          "size": 693042,
          "sha512": "3812932710ae0656516fd4a426941469793b56f30e50ee314440473274e13bd74a64dd5b8852e4a976909188feabf1c7aa96fe6551a414834a040ad8ad5a4963",
          "sha256": "34f2c34d15c381ecff29346680c952f9bc696b4e021bf400f6a059ba95eee2c2",
          "sha1": "0e2928054c94970328c4b6b46ff47329f55ec3fe",
          "md5": "6838200d22741aaf8eb5427ba86236c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2516.0-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2516.0-sources.jar",
          "size": 255170,
          "sha512": "7c9f211194b934eeff0e299856fb07aba999cce04238adb219c6326d973cb280b74d8a59eabe0de755595ad2868bdd3e24ab38ff5897a06d4001396c50e8762e",
          "sha256": "49d02012f70b8e036175b2593ee9a0ee3d1e0bf92ef555f124f2da577d788173",
          "sha1": "528c11ad2a22ee23ed54364d27c8c298693b00f0",
          "md5": "71c4cc38241f3c74273ccc0fbe1396ca"
        }
      ]
    }
  ]
}
