{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2513.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.0.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.0.jar",
          "size": 683055,
          "sha512": "e8f9d9454d53ec28a55ac269e9e72c3b0a1a8260d1077b18075a626701aafbfbc54c49c53c9439426752427e719268bfbab27047e309e99494857c9ff7faa6cf",
          "sha256": "9986aa5ae72fab1c77bee8797f61aae8809efda3a75a42a90c2bd62004362aca",
          "sha1": "dcca60f09efbb570727421c08a37a69c834bafc5",
          "md5": "d86a012f5572b430b02f397007b78104"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.0.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.0.jar",
          "size": 683055,
          "sha512": "e8f9d9454d53ec28a55ac269e9e72c3b0a1a8260d1077b18075a626701aafbfbc54c49c53c9439426752427e719268bfbab27047e309e99494857c9ff7faa6cf",
          "sha256": "9986aa5ae72fab1c77bee8797f61aae8809efda3a75a42a90c2bd62004362aca",
          "sha1": "dcca60f09efbb570727421c08a37a69c834bafc5",
          "md5": "d86a012f5572b430b02f397007b78104"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.0-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.0-sources.jar",
          "size": 250456,
          "sha512": "1304bfa3ca4baa94da70c4474fa01f6d238235b2267b14680260f389062fd0d04fa368a5e390ff8a8c0f8daa632b556134e2c6a6fa2dd929a0d99aa0805124b2",
          "sha256": "9dad5747b9bddead6b749a4271bb27ca44283a56fe73357abcbc34d009e20422",
          "sha1": "3d2cf907961511b2260dead3cf590fb03530dd86",
          "md5": "22695c6b42c03b0c0a9d52ed544284eb"
        }
      ]
    }
  ]
}
