{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2515.0.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2515.0.jar",
          "size": 18265491,
          "sha512": "8fb4d49f6eb98fbd5e531f79b6147bf667f310d1a1a0eaf7c1443808d62e117e996ee04f92a371c054f3dda66b573b379c14f67f1edc632aa43b281647540c27",
          "sha256": "435e4e7999ed7a897fcd5fe3cb9d596646cab72eee28e3406b247ce2ba3b18e7",
          "sha1": "af388532ef2006aae8ced4c61834534e9c03ea92",
          "md5": "0e9745b2009b46789cce825a978d4952"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2515.0.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2515.0.jar",
          "size": 18265491,
          "sha512": "8fb4d49f6eb98fbd5e531f79b6147bf667f310d1a1a0eaf7c1443808d62e117e996ee04f92a371c054f3dda66b573b379c14f67f1edc632aa43b281647540c27",
          "sha256": "435e4e7999ed7a897fcd5fe3cb9d596646cab72eee28e3406b247ce2ba3b18e7",
          "sha1": "af388532ef2006aae8ced4c61834534e9c03ea92",
          "md5": "0e9745b2009b46789cce825a978d4952"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2515.0-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2515.0-sources.jar",
          "size": 17432425,
          "sha512": "1fabdbe15715703604080019f022aca8332727be03c31574872973c2a5b6d3b835bfd84c245a62b1e15c86321359031fe278e884122d2f6fdc0036bfea8de707",
          "sha256": "ec0c64a234fc11edc0a4372cd94e07bddbdb77f172094cab996004482e9f6345",
          "sha1": "b8c1ca88f896a1695904bdbcc226b8fa6e1fe255",
          "md5": "951221d4c61e35cee889e9e29b2deef9"
        }
      ]
    }
  ]
}
