{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.7.2604.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2604.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2604.0.jar",
          "size": 528343,
          "sha512": "d5f731c97e4fcb19e7537eeeb589b26b12c80ba67be34f465773546ad6143ced3fea001b112616cfc6d52744e31d384ee615c8f994498e2d9c41423aaf0bb0ca",
          "sha256": "a51b0b0745edcac439267963a1dd4451f7ffc15a96105bc2ecee480ba7938143",
          "sha1": "859f0092d4b95d60e070b1893d52499125ac8254",
          "md5": "c668d1b3a31485e48ea2ff4b47101ff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2604.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2604.0.jar",
          "size": 528343,
          "sha512": "d5f731c97e4fcb19e7537eeeb589b26b12c80ba67be34f465773546ad6143ced3fea001b112616cfc6d52744e31d384ee615c8f994498e2d9c41423aaf0bb0ca",
          "sha256": "a51b0b0745edcac439267963a1dd4451f7ffc15a96105bc2ecee480ba7938143",
          "sha1": "859f0092d4b95d60e070b1893d52499125ac8254",
          "md5": "c668d1b3a31485e48ea2ff4b47101ff4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2604.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2604.0-sources.jar",
          "size": 255962,
          "sha512": "6fde9dfde77ed338f73ee16b8c918e861c93274c3ffc3e5ff5cf7517ee55e45f55e658dd729c0ade62ecb869bb073d30a97421dee87bf10d7a9c9cba679918b7",
          "sha256": "beea42c648a11710db3417d84ef37b6ed58a0508d72eb30823c2ce1b81c21177",
          "sha1": "12ddfe22f4cfc86223a92dedf3def46c9f6b5372",
          "md5": "541daa7ee73dfbae23f90462468c3b5a"
        }
      ]
    }
  ]
}
