{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.7.2616.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2616.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2616.2.jar",
          "size": 548503,
          "sha512": "7f2a17e26604f17ee50996c620c47c82dd7f76a1cb5028d006057363f2741058ddcca013b89049057abb21e1f899a82e4ed080da7254cedb851bcd87f7b3d955",
          "sha256": "238d75eb60aa395f1de2a0693196930f1f3080a4d6e2c1c066967ba754e9da5a",
          "sha1": "ae7d67d9085e865a34b3b61149c180da5df31cd4",
          "md5": "51f70b2dff62dc9adfd1f4b448598697"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2616.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2616.2.jar",
          "size": 548503,
          "sha512": "7f2a17e26604f17ee50996c620c47c82dd7f76a1cb5028d006057363f2741058ddcca013b89049057abb21e1f899a82e4ed080da7254cedb851bcd87f7b3d955",
          "sha256": "238d75eb60aa395f1de2a0693196930f1f3080a4d6e2c1c066967ba754e9da5a",
          "sha1": "ae7d67d9085e865a34b3b61149c180da5df31cd4",
          "md5": "51f70b2dff62dc9adfd1f4b448598697"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2616.2-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2616.2-sources.jar",
          "size": 256779,
          "sha512": "965b8575e5b10863d47ca83bcba8a9ce5e13e091527e6643278de58a1bfef978cb0af18339c5e5dac616b71b0642c635883e60f633dd7893efce0b4ded5aee23",
          "sha256": "f04714837892bc330ef5f271652a617cf4d430ea8803442a1d039b393290dadf",
          "sha1": "f3b0c294fd6eaee3a430e33bfcf35011b3f41f7d",
          "md5": "0c002d0acb6ce92f5370371f47c1b93d"
        },
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2616.2-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2616.2-sources.jar",
          "size": 256779,
          "sha512": "965b8575e5b10863d47ca83bcba8a9ce5e13e091527e6643278de58a1bfef978cb0af18339c5e5dac616b71b0642c635883e60f633dd7893efce0b4ded5aee23",
          "sha256": "f04714837892bc330ef5f271652a617cf4d430ea8803442a1d039b393290dadf",
          "sha1": "f3b0c294fd6eaee3a430e33bfcf35011b3f41f7d",
          "md5": "0c002d0acb6ce92f5370371f47c1b93d"
        }
      ]
    }
  ]
}
