{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2500.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.6.jar",
          "size": 364527,
          "sha512": "9465f65715bdeff1d946be074efb5f6934140fa615ed47d444e0ed1c3c88884ec7a99964c9fdd85c3f77a406d287b36adeec2b42896ec7a0bea8eccf61e6e54f",
          "sha256": "3e3697d40d3649f92b1c11f6351f5d95414a2db67fe0e76a15000072495411c6",
          "sha1": "105a211e9c4fafb316ed088455d93d1a4cf59bd6",
          "md5": "386f32678bb38931812b436852e2f88c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.6.jar",
          "size": 364527,
          "sha512": "9465f65715bdeff1d946be074efb5f6934140fa615ed47d444e0ed1c3c88884ec7a99964c9fdd85c3f77a406d287b36adeec2b42896ec7a0bea8eccf61e6e54f",
          "sha256": "3e3697d40d3649f92b1c11f6351f5d95414a2db67fe0e76a15000072495411c6",
          "sha1": "105a211e9c4fafb316ed088455d93d1a4cf59bd6",
          "md5": "386f32678bb38931812b436852e2f88c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.6-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.6-sources.jar",
          "size": 193559,
          "sha512": "b34e260eacbd51f420d7cbc4de6172f5b65a67a7decb96ba4e7135bb0d5d084108e2553a63254a287ebadc091bc366df47ecd01d1d7dc1cfa6d1806575365155",
          "sha256": "b7411f5b9e12a113e3a748032f9366504d3ff9bc322a5edec3378c828c801909",
          "sha1": "9fff0c601f03e4e62bee7fdbee4e50692a270fa0",
          "md5": "a8a94aadb509fea8c63e9622875afd00"
        }
      ]
    }
  ]
}
