{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2511.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2511.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2511.3.jar",
          "size": 18281706,
          "sha512": "28e76f24ff925b74ad4725fa2887edd9b9af24e194eb0c0c4a23bcd56bf63f4f6b69abf0575d73cc4e7534f1d812418d0754b92cbc7f76d1a38587359b163ebe",
          "sha256": "ddec5105c2764cf55f3cf6cbd5a54b9d04de8a7bb721c20a633f4cb551ee138b",
          "sha1": "56ceb88461407860206b10c1513bb410be71154a",
          "md5": "8ebdc19d5f0e2384ed1d5033cabe8e8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2511.3.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2511.3.jar",
          "size": 18281706,
          "sha512": "28e76f24ff925b74ad4725fa2887edd9b9af24e194eb0c0c4a23bcd56bf63f4f6b69abf0575d73cc4e7534f1d812418d0754b92cbc7f76d1a38587359b163ebe",
          "sha256": "ddec5105c2764cf55f3cf6cbd5a54b9d04de8a7bb721c20a633f4cb551ee138b",
          "sha1": "56ceb88461407860206b10c1513bb410be71154a",
          "md5": "8ebdc19d5f0e2384ed1d5033cabe8e8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2511.3-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2511.3-sources.jar",
          "size": 17422378,
          "sha512": "4b68c36dec1c7a06ceb5eef6b44b2100a57edec6c917ab247d370fe08d42933af5e7aa664c4eeea9eaf5aa4b773cfd6e20d5330e0c0b9a25a51e40d842e7f00f",
          "sha256": "3631b81d68e0b63185872b8ed1f1adf2406445b26029a09df36ada4f51037a9c",
          "sha1": "ddc38d90d28ebaada1f0e899caa5be7d9efe981b",
          "md5": "55ad83960e05af933e70e15c208ceb9e"
        }
      ]
    }
  ]
}
