{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.11-1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.16"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.11-2.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.11-1.9.jar",
          "url": "legacy-fabric-1.21.11-1.9.jar",
          "size": 27545364,
          "sha512": "647b03045a72421e36dd12eb86278b957ca0c7eee518a5299e01bff2b3beb1a02a018d834380cbebcc49680352796ec8b27e2b8337374d20ce6fa962dd474465",
          "sha256": "a85184b270ff128171914a5aead47c16bd0c2c1cf7cf7c704e014df6dfd1be31",
          "sha1": "a71ae9ea2cf548c28ad3ee8628955dd6426ac532",
          "md5": "b0307e493b10f89dbe7116e0c1cfcd21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.16"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.11-2.2.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.1+1.21.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "17.0.0-beta.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.11-1.9.jar",
          "url": "legacy-fabric-1.21.11-1.9.jar",
          "size": 27545364,
          "sha512": "647b03045a72421e36dd12eb86278b957ca0c7eee518a5299e01bff2b3beb1a02a018d834380cbebcc49680352796ec8b27e2b8337374d20ce6fa962dd474465",
          "sha256": "a85184b270ff128171914a5aead47c16bd0c2c1cf7cf7c704e014df6dfd1be31",
          "sha1": "a71ae9ea2cf548c28ad3ee8628955dd6426ac532",
          "md5": "b0307e493b10f89dbe7116e0c1cfcd21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.11-1.9-sources.jar",
          "url": "legacy-fabric-1.21.11-1.9-sources.jar",
          "size": 24311658,
          "sha512": "c8d8635c944f4d9c6a50b39824fa90ba1e64bde456fa464d0fcbf46dc16fe1c68e78ace51196f91ad16410b020014c8f4cc7af7552fba17cc0a3037023f57027",
          "sha256": "1a4e3c1737823dd72d0fd4ac67cccf099564305cdd2ee146b2b3ac1d22425a54",
          "sha1": "ae1540f18ccffbb83ea124dc980327b6ba5bde87",
          "md5": "8c887f5e61ceefe389d21f5f846c509d"
        }
      ]
    }
  ]
}
