{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2502.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.7.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.7.jar",
          "size": 443922,
          "sha512": "524a256ce2cc41718cf688995f9d5ed207f5804b5858727c7f3bdb4c120dfd61883088fb31562224a8206158bd0cf923f24b81d8ef7e72135e4c09f234717d77",
          "sha256": "28e7797dbdd8310a1475c2bb1dfe0a5a7976c89a7a7edabeb45b96bca6b9046b",
          "sha1": "16dd3bfb68518cf1e5877c881f53bad4c00c6551",
          "md5": "65be3fd92d23fb3c8f16e65476e42d36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.7.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.7.jar",
          "size": 443922,
          "sha512": "524a256ce2cc41718cf688995f9d5ed207f5804b5858727c7f3bdb4c120dfd61883088fb31562224a8206158bd0cf923f24b81d8ef7e72135e4c09f234717d77",
          "sha256": "28e7797dbdd8310a1475c2bb1dfe0a5a7976c89a7a7edabeb45b96bca6b9046b",
          "sha1": "16dd3bfb68518cf1e5877c881f53bad4c00c6551",
          "md5": "65be3fd92d23fb3c8f16e65476e42d36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.7-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.7-sources.jar",
          "size": 222293,
          "sha512": "04ac5a6b397178212fc89790da3fab0b29dbdd148ae7d636092e118474d07861a427ceef4404d2d925e8a2afb55871af952fb722a671ceeaed09bab64718deaa",
          "sha256": "deb97bee26a8f38a0623432a8066a2f09951295b6d209d3bd13d710e0c198540",
          "sha1": "3c3491dac8b1bf56472ea753a5bcc9aaaa110c97",
          "md5": "945c103b43d0af914d87389ed8628206"
        }
      ]
    }
  ]
}
