{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.4.jar",
          "url": "factory_api-forge-1.21.5-2.2.4.jar",
          "size": 717866,
          "sha512": "0d4e97df1e40268e9f2f7a386eca1de7e729a7fb0a9bef3f47524cfd123661af9f1f7fa91d368c12dcc6db63d81dab233b8e1ea25692a4d137ac1237d8f9d9cf",
          "sha256": "c5331b9c4ed3db5c9af0d5b1c43472d202ff53829c29c2873bbcb241b59975e5",
          "sha1": "fb99ed29e57355a488afefdcc2f727cb5c2e814c",
          "md5": "67466ba07ef4364372434f34ecf589a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.4.jar",
          "url": "factory_api-forge-1.21.5-2.2.4.jar",
          "size": 717866,
          "sha512": "0d4e97df1e40268e9f2f7a386eca1de7e729a7fb0a9bef3f47524cfd123661af9f1f7fa91d368c12dcc6db63d81dab233b8e1ea25692a4d137ac1237d8f9d9cf",
          "sha256": "c5331b9c4ed3db5c9af0d5b1c43472d202ff53829c29c2873bbcb241b59975e5",
          "sha1": "fb99ed29e57355a488afefdcc2f727cb5c2e814c",
          "md5": "67466ba07ef4364372434f34ecf589a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.4-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.4-sources.jar",
          "size": 255147,
          "sha512": "4350bfab778f209a194319c8668e2d765c9bc4a18d1aa3bdc9a9ceb133191681ddcb8be2dbe2ad2c6c5f58310a606a5bf57c4385611ade4d06a8b287b1e3470c",
          "sha256": "3f7a09adf09083644a06ff00468b2ced6f3f240cc2e4ab57b67f9327ce9485be",
          "sha1": "0743407edd4b966fcfde8f05a7d73bc1791807c8",
          "md5": "ae53a90a958289e14ed9caf8dd5d78a4"
        }
      ]
    }
  ]
}
