{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2515.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2515.0.jar",
          "size": 508083,
          "sha512": "6695d086c8f1edcc031ed9e1d4d6c51eee8e369d60c5fd2608ab340a87dcb7bee5f5381efa9dbdfadbfb2474d7b4a1853183926d331f55adddd37af65a344a41",
          "sha256": "bd97d6d16535c6d34bac8af8cabf157552d0728fe7fddd38b12f664e75a4f20f",
          "sha1": "feccea61a991f9f151035005d763ee0e038748a7",
          "md5": "91480003e63da3757a38a361cd459cb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2515.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2515.0.jar",
          "size": 508083,
          "sha512": "6695d086c8f1edcc031ed9e1d4d6c51eee8e369d60c5fd2608ab340a87dcb7bee5f5381efa9dbdfadbfb2474d7b4a1853183926d331f55adddd37af65a344a41",
          "sha256": "bd97d6d16535c6d34bac8af8cabf157552d0728fe7fddd38b12f664e75a4f20f",
          "sha1": "feccea61a991f9f151035005d763ee0e038748a7",
          "md5": "91480003e63da3757a38a361cd459cb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2515.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2515.0-sources.jar",
          "size": 252746,
          "sha512": "1107156c9eee7df21d9af673a7c7a373aa674ce4e9b2eaf281325b82e81091942164393fdccee66a669c3614bf253581a69b8356da99f9ad373cce3f6459302e",
          "sha256": "62bdda9953e9f999bfa4fb01f5f6ea4897d396793110101e73189ff6334eec29",
          "sha1": "d97e9d4a1a943d6c08219b002b95402ef7c903f9",
          "md5": "aa4daf9dae9de28c7d6062fb55b548fc"
        }
      ]
    }
  ]
}
