{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2516.0.jar",
          "size": 18294131,
          "sha512": "0fb5739e1ba13dc7a75921ec343949a46cf0923bc02798e26304da8eb70ce044ac41651406a6232e9e584be0b29709ea258c286951a5b10f8eeab39086b22aeb",
          "sha256": "5042166d059334553d9da356b0ef80f1a90a58c0412ba176646c9135ef0c9680",
          "sha1": "2aab61d190512daa80aceab1b708c6fe530839e5",
          "md5": "633b769fecfc68feb1f53ffb1da9c355"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2516.0.jar",
          "size": 18294131,
          "sha512": "0fb5739e1ba13dc7a75921ec343949a46cf0923bc02798e26304da8eb70ce044ac41651406a6232e9e584be0b29709ea258c286951a5b10f8eeab39086b22aeb",
          "sha256": "5042166d059334553d9da356b0ef80f1a90a58c0412ba176646c9135ef0c9680",
          "sha1": "2aab61d190512daa80aceab1b708c6fe530839e5",
          "md5": "633b769fecfc68feb1f53ffb1da9c355"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2516.0-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2516.0-sources.jar",
          "size": 17434341,
          "sha512": "2965b7e569423bc5385f734615334a86c491e3292512d83ad79e83543d85a4284fb5cdd48ad23a6c392e9b59ce9f2d6bd03a57d9ffc4ca57f02cc38f35efde95",
          "sha256": "60204dd77c01c17a5e0dbf5ec1a59e8149d65bfeec4ac2273b3e991bd374dbb5",
          "sha1": "f42687c5892e4b2a32cf747427811e099d2f5343",
          "md5": "a68afd27219fb1e553a87a7b40197fb3"
        }
      ]
    }
  ]
}
