{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.1.jar",
          "size": 367775,
          "sha512": "deeff9fa47df39104b1209392b770c9f23141cb705cd726a7cb81f10e8f5d45625985300239a27dfe300b5972ae9e818e5406af6c61bfc0b12fbab1cde90ace1",
          "sha256": "1246dd5eb68e1d46d083bf17a87fe4064499aca02dc15ea4e3e395593295719c",
          "sha1": "47d92d8f21583a880e70baf8124fd6abdfefb193",
          "md5": "8066cc6e52ae6749aaf98492cafb1545"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.1.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.1.jar",
          "size": 367775,
          "sha512": "deeff9fa47df39104b1209392b770c9f23141cb705cd726a7cb81f10e8f5d45625985300239a27dfe300b5972ae9e818e5406af6c61bfc0b12fbab1cde90ace1",
          "sha256": "1246dd5eb68e1d46d083bf17a87fe4064499aca02dc15ea4e3e395593295719c",
          "sha1": "47d92d8f21583a880e70baf8124fd6abdfefb193",
          "md5": "8066cc6e52ae6749aaf98492cafb1545"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.1-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.1-sources.jar",
          "size": 193545,
          "sha512": "18bf5fecd48feb3e268d00b407f927f45fe21f5da24d93b2b2e9bf0128f4b5969441c791434a0176cf0a39e5da4120ac309a72868dec1af2213d70217b19ad69",
          "sha256": "3a636a5176b663ce2822523e3c2d34973400ca3a5767ed8a7db86fb04986e84b",
          "sha1": "4c7ca4f0f2e8fc1839dbd49446c7264355e7d3ae",
          "md5": "1cbce9549b24ada4edf3ee6bf9023bc5"
        }
      ]
    }
  ]
}
