{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2513.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.9.jar",
          "size": 706432,
          "sha512": "56e785c3bf36e62733202a398899095631d1e7cd32c11f68c0251f5b0c85451a9efca2ce9445721c0e23aeb840e3f562cf34c3305202c18a7e63a180246c7a24",
          "sha256": "26f9294c8f906ccfe23e96213e2fd112e6e3c05353682c9cf5408e694c599abe",
          "sha1": "d67978fbbe0b8676f25fdc4985b530f34b8f6f3c",
          "md5": "dd00587cc4f2f277f8414ffb14ca6a97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.9.jar",
          "size": 706432,
          "sha512": "56e785c3bf36e62733202a398899095631d1e7cd32c11f68c0251f5b0c85451a9efca2ce9445721c0e23aeb840e3f562cf34c3305202c18a7e63a180246c7a24",
          "sha256": "26f9294c8f906ccfe23e96213e2fd112e6e3c05353682c9cf5408e694c599abe",
          "sha1": "d67978fbbe0b8676f25fdc4985b530f34b8f6f3c",
          "md5": "dd00587cc4f2f277f8414ffb14ca6a97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.9-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.9-sources.jar",
          "size": 251612,
          "sha512": "a2b492c9ff2ef02df42659702efd773dc1fc5c0b18267743fb51d1d9df1e22ab72ac6b370516ebfca585195ae5ccc329d0c5d33028a83e5a1363f56aca3cc39c",
          "sha256": "19e1ff29904e698574b73eaecd123624b0d7a0630e12c0a141eb68c560cb361f",
          "sha1": "828eeb1cbe7cd5d0779fbe082971663c064922bc",
          "md5": "261b689fac22f61b8de533b2ff3750e6"
        }
      ]
    }
  ]
}
