{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2510.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.8.jar",
          "size": 682702,
          "sha512": "ace4faec7cca25a23209b28aa06a5281a20c5ac5aceb56f7d02506484c6e46c5f11e897f78ece27bade2a1c17aa99f84d390d3b440064b8953ccfdeb001386d5",
          "sha256": "8889f9aa3df9709e9d650cfdbdc254d1f9b5cc343a4b629e518e6060cd7f242d",
          "sha1": "2a5c715317d973b4cafb59cdf6a91b6cd1fbacb2",
          "md5": "0a2d3372c1770d02a5a18ab378b1f49c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.8.jar",
          "size": 682702,
          "sha512": "ace4faec7cca25a23209b28aa06a5281a20c5ac5aceb56f7d02506484c6e46c5f11e897f78ece27bade2a1c17aa99f84d390d3b440064b8953ccfdeb001386d5",
          "sha256": "8889f9aa3df9709e9d650cfdbdc254d1f9b5cc343a4b629e518e6060cd7f242d",
          "sha1": "2a5c715317d973b4cafb59cdf6a91b6cd1fbacb2",
          "md5": "0a2d3372c1770d02a5a18ab378b1f49c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.8-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.8-sources.jar",
          "size": 250414,
          "sha512": "09cc0f1a32c10ac922221710ec85af07881d3bc4a9c49e80523199441e7a9a149189c14762397c9aa1906bc92dba9f8f634c2bbe3b29be47d1235f47f260469d",
          "sha256": "f73381b4736fc2c202e60d68e29f01cb2dad4f9f549bae3334ad4a54d6a638f4",
          "sha1": "69b789d3b5065bbc2c7a2d4b379236e761db3f9d",
          "md5": "0fb455ac85d23fb3e61a3ed75bb68dae"
        }
      ]
    }
  ]
}
