{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2506.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2506.0.jar",
          "size": 468431,
          "sha512": "8b9781a193f640d760f7b5e3898062c51bfb4027782fc8e97f2b3c14bca93fda292288923395b4524a77668d05e9fe0412a250fa9ccc28ceb42ac72d97546a1f",
          "sha256": "5a6ae3176e185a9a604d4c3277fe9a26dfd754d7ef631673eac6aa34d4fe81f5",
          "sha1": "ce37f465ec93fac1d4f3b6d58ab13e3010d41527",
          "md5": "5b41edc2f180f19f5f9e9324efd17b32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2506.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2506.0.jar",
          "size": 468431,
          "sha512": "8b9781a193f640d760f7b5e3898062c51bfb4027782fc8e97f2b3c14bca93fda292288923395b4524a77668d05e9fe0412a250fa9ccc28ceb42ac72d97546a1f",
          "sha256": "5a6ae3176e185a9a604d4c3277fe9a26dfd754d7ef631673eac6aa34d4fe81f5",
          "sha1": "ce37f465ec93fac1d4f3b6d58ab13e3010d41527",
          "md5": "5b41edc2f180f19f5f9e9324efd17b32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2506.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2506.0-sources.jar",
          "size": 237182,
          "sha512": "5489e52cc0a9b901b802c1aa60433d890c1d5e3b77cb74503688fec19b7367b3011a9c9d3ac885ade2d5af832d3c664947cace260fb43442d84aa378411bef89",
          "sha256": "091b88783ad66901ae65112bda2fe87549768776a131493db4a028133b15a05f",
          "sha1": "c76281cc2fc29d397a629b93e2e61daa67d2aff6",
          "md5": "53d449ad92c7749614d11fe1420af642"
        }
      ]
    }
  ]
}
