{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2501.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.18.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.18.jar",
          "size": 375014,
          "sha512": "120d6179bcb22234ff5cbfd5784cf3a6e12a9046efa6dad9335bf10c0a0e56d6ebd2b3925f3a5df39ddd47fb62105325c1d1b4a2d92c40b9e1ce96694b73a5f3",
          "sha256": "a566c198e54ae96db7203ab8f86bae0bbe5ea1f7f56f0fe03208006a8f8d576a",
          "sha1": "ae12bfc3863efe1a71a55e43fdcf1edc34181c4b",
          "md5": "92d47c5793bf036c09823cbef46925ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.18.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.18.jar",
          "size": 375014,
          "sha512": "120d6179bcb22234ff5cbfd5784cf3a6e12a9046efa6dad9335bf10c0a0e56d6ebd2b3925f3a5df39ddd47fb62105325c1d1b4a2d92c40b9e1ce96694b73a5f3",
          "sha256": "a566c198e54ae96db7203ab8f86bae0bbe5ea1f7f56f0fe03208006a8f8d576a",
          "sha1": "ae12bfc3863efe1a71a55e43fdcf1edc34181c4b",
          "md5": "92d47c5793bf036c09823cbef46925ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2501.18-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2501.18-sources.jar",
          "size": 201615,
          "sha512": "b8778d6cd9ee9cdaa2d5954c552c828aaa6b489804e0fbaa9070174a88e523da52fd193d85ade97906d5209606b882178d3bf5167e1ae111b81707811b5f79e7",
          "sha256": "a1fc3dd0903d4d9adb1b46b15e4297c1cadfbb4a073bf677d29089e46ee19174",
          "sha1": "8dda75ef187943f031c48506bc8b51e91fb30ec3",
          "md5": "43883eb3c771b1a0a8cde78a7da6e329"
        }
      ]
    }
  ]
}
