{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.4-1.1.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2516.1.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2516.1.jar",
          "size": 642764,
          "sha512": "367772bc5d49a3cb754f7b455c808fbf98f2bd74e2a5c70777464e1e0aa2350675ea03b5037e52b9f8ec99cf608bc0dd896122c18f4ff57b805ee75f1c5fe04e",
          "sha256": "1207741c1545a436687dfffebea8389906017198be75f07bc7790d538ec68fd4",
          "sha1": "a91d5f87dc2e94e7dc90798d6cfef3f1a3e44a46",
          "md5": "a1583c154ce28e6da772d2b59536856f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2516.1.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2516.1.jar",
          "size": 642764,
          "sha512": "367772bc5d49a3cb754f7b455c808fbf98f2bd74e2a5c70777464e1e0aa2350675ea03b5037e52b9f8ec99cf608bc0dd896122c18f4ff57b805ee75f1c5fe04e",
          "sha256": "1207741c1545a436687dfffebea8389906017198be75f07bc7790d538ec68fd4",
          "sha1": "a91d5f87dc2e94e7dc90798d6cfef3f1a3e44a46",
          "md5": "a1583c154ce28e6da772d2b59536856f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2516.1-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2516.1-sources.jar",
          "size": 585463,
          "sha512": "ee3006863e91ad4590bb42415881f5e7f267e6ee314d2614a12c893d74f73c16dc6d02a9e142bdd5a302257f10537bb3f057a85aa7a3cf4d7cf663e5e13f8b02",
          "sha256": "8288e5079510ebbccd6d58888c663fff0c37a8f06b1f2ed9ae46e98b6a23cdd4",
          "sha1": "a4ec582ace5444e0dddce49b9afc97bd7bdc1097",
          "md5": "4751a465caf92feea435db194cf9320c"
        }
      ]
    }
  ]
}
