{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.6.jar",
          "url": "factory_api-forge-1.21.4-2.2.6.jar",
          "size": 721034,
          "sha512": "398f256d872ba9486c3bae54e18ecf382f23375648ea2a806dbd68d5b369aec5cb3e58c05c675c0ee6bf277ce274c836b0ff831b8d93a9966be77086282ab68e",
          "sha256": "e51c44d8a9ee1e285a1edeae8338e69e6d83188ab725a604f96e442b9f601f13",
          "sha1": "6dd9e8e22f7277e5e62497c12f4b990deb17a943",
          "md5": "5c8d883d14f7eba3fdb575aea4832cbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.6.jar",
          "url": "factory_api-forge-1.21.4-2.2.6.jar",
          "size": 721034,
          "sha512": "398f256d872ba9486c3bae54e18ecf382f23375648ea2a806dbd68d5b369aec5cb3e58c05c675c0ee6bf277ce274c836b0ff831b8d93a9966be77086282ab68e",
          "sha256": "e51c44d8a9ee1e285a1edeae8338e69e6d83188ab725a604f96e442b9f601f13",
          "sha1": "6dd9e8e22f7277e5e62497c12f4b990deb17a943",
          "md5": "5c8d883d14f7eba3fdb575aea4832cbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.6-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.6-sources.jar",
          "size": 258875,
          "sha512": "c76c50f7f478c5ddde822c7ffda26a48446a23ba5a3d7c2cc10d2b250e8f122822243891ce2e0a7f62e2ebdf618a99402089372e8429f830ba5f2bcebc0f05d4",
          "sha256": "0ed064fc99c7e11f2accc2852992b692fca7a039e4db4c8ccaa1743d0edbec31",
          "sha1": "8b8edf5ff70736c4a7a61424a7533bd893724a71",
          "md5": "a66d5807bd2da2de4aca8bc15582bdc4"
        }
      ]
    }
  ]
}
