{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2514.2.jar",
          "size": 692020,
          "sha512": "4b8cc963c40c4f843e0d23b73de1aa54502867539fe9d05fe037acfb7417bc6d036a98c9b2c2a2932664bac6890c23b2f697cea6c5af6b4323953208d28ea292",
          "sha256": "9c03a95db3cdf856dd5b8ccfe278977c959458a5dc498de6b08c0e2db07c8417",
          "sha1": "61b98c7945b48005e7b64c74e7dfc43164d48314",
          "md5": "196cc9675b5e689134723338d4435c16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2514.2.jar",
          "size": 692020,
          "sha512": "4b8cc963c40c4f843e0d23b73de1aa54502867539fe9d05fe037acfb7417bc6d036a98c9b2c2a2932664bac6890c23b2f697cea6c5af6b4323953208d28ea292",
          "sha256": "9c03a95db3cdf856dd5b8ccfe278977c959458a5dc498de6b08c0e2db07c8417",
          "sha1": "61b98c7945b48005e7b64c74e7dfc43164d48314",
          "md5": "196cc9675b5e689134723338d4435c16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2514.2-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2514.2-sources.jar",
          "size": 75215,
          "sha512": "95e53d45ccffd75940f0a2371bd04ca09af799811b8e6afe3eb20b59492aa0e06b7ab84c837e60c824781d7bcb5d4fac091e80e5a37d82b4a86e31c064eb71d0",
          "sha256": "e2f07d266e556a2a9738ad471f256bd81c3d1b3abb43e94adf6a7453670f3039",
          "sha1": "fb9bcffabbe44f15f6d10d66ae084fd68ed32e92",
          "md5": "b30aa1df6f56cb851c684454511daa4f"
        }
      ]
    }
  ]
}
