{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.16.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.16.jar",
          "size": 379488,
          "sha512": "e717d6ef3d57b104b9b3dd92327ce2fd0a7e09768384162d8811aee7999576dd659b9762199e0bf7b14cb115e66ed93b6dc5b432c2713d187ec394e652be2bf4",
          "sha256": "1504bfc4f9a5233bf858cee02b4412a6b2d6512b8d8af75ef820a57479fe33c8",
          "sha1": "ba213fa242b6cf066101a9dcf7bb1237c781ae34",
          "md5": "418578e7ea0139df388935c46d741986"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.16.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.16.jar",
          "size": 379488,
          "sha512": "e717d6ef3d57b104b9b3dd92327ce2fd0a7e09768384162d8811aee7999576dd659b9762199e0bf7b14cb115e66ed93b6dc5b432c2713d187ec394e652be2bf4",
          "sha256": "1504bfc4f9a5233bf858cee02b4412a6b2d6512b8d8af75ef820a57479fe33c8",
          "sha1": "ba213fa242b6cf066101a9dcf7bb1237c781ae34",
          "md5": "418578e7ea0139df388935c46d741986"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.16-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.16-sources.jar",
          "size": 199645,
          "sha512": "e3d91e0cd530840d403941fa3a462ca0f9f5476513f409be3cf2efb2b5cb7e70e6d89bfb23294161f86c0a71f372991355b22fe753115e28392acde607ccea40",
          "sha256": "a844e0966e7a2c50126830c8f20a3c2fb1d9dbc71c5759c606c081b41cc5ed66",
          "sha1": "176ad6a7d3fa126fc353d09f6b9e912371377bfd",
          "md5": "17d0316c87e6b26620317256dc313b84"
        }
      ]
    }
  ]
}
