{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.7.2616.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2616.0.jar",
          "size": 1173316,
          "sha512": "c50a869527355219279433061dfbafb5d0c512a451481e475a45f4b85071bec801208aad8af2aa925a52e8b4b16be15440fc6759179e7ccfc6c271e28975a5e5",
          "sha256": "cd14c0b0725b613b4ba7994b47621031a69e457d35de011977f84477de28c594",
          "sha1": "a0d49b62a4b543b97fe601d47e373d9180f11f85",
          "md5": "7c8d357d2e760865a82de444b288e752"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.0"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2616.0.jar",
          "size": 1173316,
          "sha512": "c50a869527355219279433061dfbafb5d0c512a451481e475a45f4b85071bec801208aad8af2aa925a52e8b4b16be15440fc6759179e7ccfc6c271e28975a5e5",
          "sha256": "cd14c0b0725b613b4ba7994b47621031a69e457d35de011977f84477de28c594",
          "sha1": "a0d49b62a4b543b97fe601d47e373d9180f11f85",
          "md5": "7c8d357d2e760865a82de444b288e752"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2616.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2616.0-sources.jar",
          "size": 256860,
          "sha512": "11fa28c0af99363128457e44b744c7e90369420c8cb2bc0d6f35d3a374ae20841a02e4a3958737d9ee8784ab86b2c00d80fb043d06044f69d6ec2420cf5981e8",
          "sha256": "4d41626a6397964b68b7059aeb9fc4557aac4ea9b2eeae1302c78ac78a035871",
          "sha1": "609f2ef1ab0cdaf7be3e17a05f06cf91b44b2b1f",
          "md5": "f7b8c2f4ef70ec10bde0fb2a62602daf"
        },
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2616.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2616.0-sources.jar",
          "size": 256860,
          "sha512": "11fa28c0af99363128457e44b744c7e90369420c8cb2bc0d6f35d3a374ae20841a02e4a3958737d9ee8784ab86b2c00d80fb043d06044f69d6ec2420cf5981e8",
          "sha256": "4d41626a6397964b68b7059aeb9fc4557aac4ea9b2eeae1302c78ac78a035871",
          "sha1": "609f2ef1ab0cdaf7be3e17a05f06cf91b44b2b1f",
          "md5": "f7b8c2f4ef70ec10bde0fb2a62602daf"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2616.0.jar",
          "size": 1173316,
          "sha512": "c50a869527355219279433061dfbafb5d0c512a451481e475a45f4b85071bec801208aad8af2aa925a52e8b4b16be15440fc6759179e7ccfc6c271e28975a5e5",
          "sha256": "cd14c0b0725b613b4ba7994b47621031a69e457d35de011977f84477de28c594",
          "sha1": "a0d49b62a4b543b97fe601d47e373d9180f11f85",
          "md5": "7c8d357d2e760865a82de444b288e752"
        }
      ]
    }
  ]
}
