{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.0.jar",
          "size": 510106,
          "sha512": "609eddb876a523557d5c96dc48749e3481288f4a45448dc817fe78e663d842c04a9bf4194ff8ca8fc0bce051724cb09c31908cd68b994d1a72e6e3225e6ff8fd",
          "sha256": "f7d9906c7f35f55b7a0e8a17ce1d0ea899de4d6a98dfe399c024bb2015e0809d",
          "sha1": "828a001622b03921426c48e7db4c40f42360ea9e",
          "md5": "af21287fda0ee485ff37b7c7b47d54c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.0.jar",
          "size": 510106,
          "sha512": "609eddb876a523557d5c96dc48749e3481288f4a45448dc817fe78e663d842c04a9bf4194ff8ca8fc0bce051724cb09c31908cd68b994d1a72e6e3225e6ff8fd",
          "sha256": "f7d9906c7f35f55b7a0e8a17ce1d0ea899de4d6a98dfe399c024bb2015e0809d",
          "sha1": "828a001622b03921426c48e7db4c40f42360ea9e",
          "md5": "af21287fda0ee485ff37b7c7b47d54c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2508.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2508.0-sources.jar",
          "size": 249573,
          "sha512": "f274dcdebdc1cc76d1038c5bfae8d5652add7768e41c64a4c69c7350f1aecbfde80a1c48ac88bbd7a2b3a350445e5811b9fe1d4e5deecb71afd2907477c44a01",
          "sha256": "ec3428788455479aa5eb37c79d06f4b7dae3ce2c6bb8ed39f540932a971da705",
          "sha1": "270fec79220a182ad7682d0d2c4856b9ee7bfbb8",
          "md5": "f16ed2fe1aff6e932a3c3ba51231c255"
        }
      ]
    }
  ]
}
