{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.4-1.7.10.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.2509.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.7.10.2509.1.jar",
          "url": "legacy-fabric-1.20.4-1.7.10.2509.1.jar",
          "size": 14383530,
          "sha512": "7259c4f507cdfc2e188ed8f76c35df9fb010b51c8f8638f0120ddd45744b65e495aca1b93fc60a1a9587edb023422fab34032d3fb870c5b1d5c788bd17a14824",
          "sha256": "cde92ff56eb0754774d6c737f80139ce328b4bf967c509052c257d3c2df245ab",
          "sha1": "36bb2fae8bc0ac7364962dab101ff62cde3e4a7d",
          "md5": "ec3338f55819b26730562dad1b369f53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.2509.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.7.10.2509.1.jar",
          "url": "legacy-fabric-1.20.4-1.7.10.2509.1.jar",
          "size": 14383530,
          "sha512": "7259c4f507cdfc2e188ed8f76c35df9fb010b51c8f8638f0120ddd45744b65e495aca1b93fc60a1a9587edb023422fab34032d3fb870c5b1d5c788bd17a14824",
          "sha256": "cde92ff56eb0754774d6c737f80139ce328b4bf967c509052c257d3c2df245ab",
          "sha1": "36bb2fae8bc0ac7364962dab101ff62cde3e4a7d",
          "md5": "ec3338f55819b26730562dad1b369f53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.7.10.2509.1-sources.jar",
          "url": "legacy-fabric-1.20.4-1.7.10.2509.1-sources.jar",
          "size": 13572770,
          "sha512": "85a441ff1b2b268c74f7229bd94ed17ce7c3dd0877f805462e4fc37e1a816777f0395b8a0f77b37f229f3f4054fb440058c6f8fc28ddd1a27a307dc644a480e6",
          "sha256": "5579f3b94c141d03263d174d618c41f3f0b5d8ec1ab4769a9b9f88781e592118",
          "sha1": "bf2f2e34b6250606bd58c4a2371faf866447d96b",
          "md5": "ef86ce5e0e4f2dc73606533d9eb8b8ad"
        }
      ]
    }
  ]
}
