{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.7.10.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2501.23"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2501.2.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2501.2.jar",
          "size": 11929239,
          "sha512": "2890f99cbed30919d0b650dd4d8c62cceed7e6c25ef3f34f80b94188cb9f38031d78888702fb90c0053aee4d26674831e6cb67ddf07fd0b045abf8d5d509dea5",
          "sha256": "0845e277c58758d28bc4188956b0498108b2283d310d7902c8b42fe2f63db4c1",
          "sha1": "eaa991e0141308abd5d2ce5a87ea4c8869b04437",
          "md5": "bd389a23608a1befe4a5d807a394a55c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2501.23"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2501.2.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2501.2.jar",
          "size": 11929239,
          "sha512": "2890f99cbed30919d0b650dd4d8c62cceed7e6c25ef3f34f80b94188cb9f38031d78888702fb90c0053aee4d26674831e6cb67ddf07fd0b045abf8d5d509dea5",
          "sha256": "0845e277c58758d28bc4188956b0498108b2283d310d7902c8b42fe2f63db4c1",
          "sha1": "eaa991e0141308abd5d2ce5a87ea4c8869b04437",
          "md5": "bd389a23608a1befe4a5d807a394a55c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2501.2-sources.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2501.2-sources.jar",
          "size": 11140151,
          "sha512": "4779309c3c6945b920aba747629773acac8cf7ed2cc205325936753daf45c6e9ca24b1e253d773f7fa62033287e12a0da6e0bb1101e5f441825f1db21f0b1042",
          "sha256": "fed96f5ea2305b161b188a6d4b387ff35501cecbaac3ccddc9d5a325735ff669",
          "sha1": "30d2f46c63020fe8be6cda0c1ab12b7c5010ac15",
          "md5": "1611537a96263a0128d7bc1c3b193a9a"
        }
      ]
    }
  ]
}
