{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2502.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.5.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.5.jar",
          "size": 432593,
          "sha512": "6c83d8743cd213a52ebd01f13d3c95b1331b43d55a902e739f826cdd621c52266dd06031d2e0f3d9f5aaaa239bb308db9d23943c6d753fe76418be96e0cf8d97",
          "sha256": "57739857af5613a13a2ca40fe961190b0f63ef0a486152fca7293cddf30ee8dc",
          "sha1": "1a13d0b6306a9b106bef7fa1aa2be92bbc5d5240",
          "md5": "890b1b48dfe3a04138b169f31b885609"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.5.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.5.jar",
          "size": 432593,
          "sha512": "6c83d8743cd213a52ebd01f13d3c95b1331b43d55a902e739f826cdd621c52266dd06031d2e0f3d9f5aaaa239bb308db9d23943c6d753fe76418be96e0cf8d97",
          "sha256": "57739857af5613a13a2ca40fe961190b0f63ef0a486152fca7293cddf30ee8dc",
          "sha1": "1a13d0b6306a9b106bef7fa1aa2be92bbc5d5240",
          "md5": "890b1b48dfe3a04138b169f31b885609"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.5-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.5-sources.jar",
          "size": 221638,
          "sha512": "b8549841ff4e10e7777a4098709e68031636b7595128c3d0d9ffbe2fa4812da91d15668d954510492a5c2f1a2593f6e7df76eb11974a71ad7f06affbe3e16e6d",
          "sha256": "8348de77e996a32d9b10907967713f37283b44c4a81588c1aac7f6539aba9bc9",
          "sha1": "1d867c301d879c05fc9dd938fd881ea5dc8c7fa2",
          "md5": "9b17c934a986d72449d5659ba4423623"
        }
      ]
    }
  ]
}
