{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2502.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.10.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.10.jar",
          "size": 444310,
          "sha512": "91a039f7a29360abb4ed3b7c51be46c50b7088d346aaa9c43d94e26e1dbece94c74af382e1e9f0eecc5d8b32ca1656aa832587961fa8453abcdddb4a0299fe24",
          "sha256": "6e56457b99f5913bd351de9687d427c4d2a915460564aa2c3c682670beebb939",
          "sha1": "29ed1e49f3f125f65ff75b3443e076355e949eaf",
          "md5": "97c001879547245ee5a1679332a6f0f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.10.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.10.jar",
          "size": 444310,
          "sha512": "91a039f7a29360abb4ed3b7c51be46c50b7088d346aaa9c43d94e26e1dbece94c74af382e1e9f0eecc5d8b32ca1656aa832587961fa8453abcdddb4a0299fe24",
          "sha256": "6e56457b99f5913bd351de9687d427c4d2a915460564aa2c3c682670beebb939",
          "sha1": "29ed1e49f3f125f65ff75b3443e076355e949eaf",
          "md5": "97c001879547245ee5a1679332a6f0f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.10-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.10-sources.jar",
          "size": 228044,
          "sha512": "c6257aa700b9c39ecf89b3333fe563d8b42cb3be3bc6752b9ac893a19b3868a94f3a9239492e13ccb2e70f96f9498abf0a1da0026794cbfd87b3f644427da4ad",
          "sha256": "b741920457fb4e9ceed276562650359e28bacba76f7e36751180b966b77a7eb6",
          "sha1": "adf1151b0f71ba70a3cb7256d146cd62348eb4bf",
          "md5": "6be2a88c4ea55306806d8df644a7432c"
        }
      ]
    }
  ]
}
