{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.jar",
          "url": "legacy-forge-1.21.4-1.8.jar",
          "size": 14396281,
          "sha512": "78baba6182e4af2c9b8fec4886169a376da5174986c08a995ab1ce730a789ae3cdee1567b5e04c4e93f6f1273be30507c420e82d55688338b5b7e8abc19b86bb",
          "sha256": "1b19a06a04c1595166780d378677620521adebfb964b05eaf641084d0e39dce8",
          "sha1": "ff3d60e2f151daefaa73d86bfb775a27e5594fae",
          "md5": "f36115873208773ca3410b47343aed7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.jar",
          "url": "legacy-forge-1.21.4-1.8.jar",
          "size": 14396281,
          "sha512": "78baba6182e4af2c9b8fec4886169a376da5174986c08a995ab1ce730a789ae3cdee1567b5e04c4e93f6f1273be30507c420e82d55688338b5b7e8abc19b86bb",
          "sha256": "1b19a06a04c1595166780d378677620521adebfb964b05eaf641084d0e39dce8",
          "sha1": "ff3d60e2f151daefaa73d86bfb775a27e5594fae",
          "md5": "f36115873208773ca3410b47343aed7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8-sources.jar",
          "url": "legacy-forge-1.21.4-1.8-sources.jar",
          "size": 13582101,
          "sha512": "77a29b273e930a3b70d10303f577b43ae2c0d3deb2474470cc6e78489511864f309c987d227f209e04a167b0c79f28907f13aa5efa2c0e49bdec96772a439e2f",
          "sha256": "eae3b7b3aef3b2520c650301d7f6224a705ba616c11ad27716ce2c8e9800dde2",
          "sha1": "9b1d48622c30aa61d0b4411182c7463e7c574a7b",
          "md5": "bdd9d19417ee09ef8b1ac672d3aac6c8"
        }
      ]
    }
  ]
}
