{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2500.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2500.7.jar",
          "url": "factory_api-forge-1.21.1-2.2.2500.7.jar",
          "size": 354223,
          "sha512": "a474dd3520d7f1a9d1529ddc6d12b410c34e849486e28c2779c08d82a0a888cb712781af4bacdbafac119e171f22ed49948ee33ca125891efeacf24f19f4d0a5",
          "sha256": "d6fb42e6a0ab925e074bdffc0e02c4a8cfa42b07299f52cff54fb9e570f9c2b7",
          "sha1": "da6ab1c961c61693a833b813e0b5365bdf535424",
          "md5": "452b95f77b2bf1b50f1c5d3c4d1dba80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2500.7.jar",
          "url": "factory_api-forge-1.21.1-2.2.2500.7.jar",
          "size": 354223,
          "sha512": "a474dd3520d7f1a9d1529ddc6d12b410c34e849486e28c2779c08d82a0a888cb712781af4bacdbafac119e171f22ed49948ee33ca125891efeacf24f19f4d0a5",
          "sha256": "d6fb42e6a0ab925e074bdffc0e02c4a8cfa42b07299f52cff54fb9e570f9c2b7",
          "sha1": "da6ab1c961c61693a833b813e0b5365bdf535424",
          "md5": "452b95f77b2bf1b50f1c5d3c4d1dba80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2500.7-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2500.7-sources.jar",
          "size": 193233,
          "sha512": "28da2750708ef144d618334cf252ee801d14663e210305d4536ef0fcc436353f3d89705a549787b60789af341cbd2565eeef0adee8da1caf2d0943d549799614",
          "sha256": "68df1ae5c57524821221b7c8536819c0cfa36e32bcf8a9016cc09bdc96705bca",
          "sha1": "2688316a43a31f1834a5d7532ee0201639ae3e02",
          "md5": "bcd7f721033424e642f487cbff68a711"
        }
      ]
    }
  ]
}
