{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2502.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.15.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.15.jar",
          "size": 458952,
          "sha512": "f8fb8ba68357a02c12773d45fe89a73d2ef884f906d0ababea75a5b83842a9f8db151c062e2c00cfc65abe7324b410c9932e2ecebd74025e6836eef2fdfc77b6",
          "sha256": "10cb264b289c3b707bb957bc2e089220acd77da1050e10a0e90e446867c93ac2",
          "sha1": "585775307a09d0dcfa2b6730cfa4ea8b571c3a3e",
          "md5": "ff2b374ec73b4c4a05dc92f9458a24a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.15.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.15.jar",
          "size": 458952,
          "sha512": "f8fb8ba68357a02c12773d45fe89a73d2ef884f906d0ababea75a5b83842a9f8db151c062e2c00cfc65abe7324b410c9932e2ecebd74025e6836eef2fdfc77b6",
          "sha256": "10cb264b289c3b707bb957bc2e089220acd77da1050e10a0e90e446867c93ac2",
          "sha1": "585775307a09d0dcfa2b6730cfa4ea8b571c3a3e",
          "md5": "ff2b374ec73b4c4a05dc92f9458a24a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.15-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.15-sources.jar",
          "size": 232017,
          "sha512": "eac6bf718ec89d26dd3bc07529ee7a58181780aba16bb0b46e7e6267f6bb83fb2869df3bb5f65db52861543284e14dc6f079cdba7b8807fb5a4418725453e87c",
          "sha256": "01a56d6decf218a9ec2254c5e6736aa3007a9f7f3b33226f6c5e03795913a442",
          "sha1": "10af7ec4d6f8d7a9fdd4948e6fcf10bda518c263",
          "md5": "afdbc48097949d71f903e2f9bddc2bec"
        }
      ]
    }
  ]
}
