{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.9.jar",
          "size": 441161,
          "sha512": "2855ae9540c8253b4f1feac827c53912b34723ecb5db0f5768a8a12bfe12ad9f25fa966b30c7a67734ddbdfd2f5ba14ed1e6511408213d960a32197fe3acd341",
          "sha256": "28ad3649587383e26fbdc6dd476064b9e9832d558c69bbd495f2453e9543d41a",
          "sha1": "749dd8c16d04f94feea8e7b5c47ead2783dbb208",
          "md5": "06bbb13f677d37d8bc13e7c8fc018da0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.9.jar",
          "size": 441161,
          "sha512": "2855ae9540c8253b4f1feac827c53912b34723ecb5db0f5768a8a12bfe12ad9f25fa966b30c7a67734ddbdfd2f5ba14ed1e6511408213d960a32197fe3acd341",
          "sha256": "28ad3649587383e26fbdc6dd476064b9e9832d558c69bbd495f2453e9543d41a",
          "sha1": "749dd8c16d04f94feea8e7b5c47ead2783dbb208",
          "md5": "06bbb13f677d37d8bc13e7c8fc018da0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.9-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.9-sources.jar",
          "size": 228309,
          "sha512": "399a272d946aed1b2b4c1afb72fb3c1022320a5662a5335e210df7c0e1069c1c58b21a79c2e1708e8b2573920d64e7f8b02403b98d1b5d03036d405097a64f18",
          "sha256": "13d8b1eaccbc24743a0c4398eff96ccce99eaf6ff1149dd6559823336a873cb1",
          "sha1": "3615f68bc0c6ef087a9a14c5dfb7df45c4f4b3d5",
          "md5": "6352b729e6da7df5be6a46d5cc5244a8"
        }
      ]
    }
  ]
}
