{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.11-2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.8.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.8.jar",
          "size": 561189,
          "sha512": "23ba19e364d5f2ee26174345815be060342a4280f97d6cecddc78a0929fdba0f8315ec613fe474d5a0a971ff2dd7ac499b557fe2af74b0739275d283d356d0ff",
          "sha256": "cf70d375d7e04208741c74f61c7044fae8878067ca394964ff0665e4def59e49",
          "sha1": "4cfd61e3bef45e8fe21953c9f695a2f33a236b17",
          "md5": "73a3d72b01e7d0c4c8ebb72509d185d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.8.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.8.jar",
          "size": 561189,
          "sha512": "23ba19e364d5f2ee26174345815be060342a4280f97d6cecddc78a0929fdba0f8315ec613fe474d5a0a971ff2dd7ac499b557fe2af74b0739275d283d356d0ff",
          "sha256": "cf70d375d7e04208741c74f61c7044fae8878067ca394964ff0665e4def59e49",
          "sha1": "4cfd61e3bef45e8fe21953c9f695a2f33a236b17",
          "md5": "73a3d72b01e7d0c4c8ebb72509d185d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.8-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.8-sources.jar",
          "size": 256728,
          "sha512": "22a051102f429c2343b3ad575658812bfed627fd77ab23a626315691b94cb8430d6fcf9f7a7866735a081b29f23f9e57b9ebc5943e226e068fd60ceebf9e36a0",
          "sha256": "c8570222c9fcc2e3ed93f9e7b19172c563a7862a14b1ea16ceb86a17677b9ed8",
          "sha1": "14596cb74122fb9a9b2afa93d81f54361d4e58d8",
          "md5": "69c39afa5336141483d685427b75dc5e"
        },
        {
          "name": "factory_api-neoforge-1.21.11-2.2.8-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.8-sources.jar",
          "size": 256728,
          "sha512": "22a051102f429c2343b3ad575658812bfed627fd77ab23a626315691b94cb8430d6fcf9f7a7866735a081b29f23f9e57b9ebc5943e226e068fd60ceebf9e36a0",
          "sha256": "c8570222c9fcc2e3ed93f9e7b19172c563a7862a14b1ea16ceb86a17677b9ed8",
          "sha1": "14596cb74122fb9a9b2afa93d81f54361d4e58d8",
          "md5": "69c39afa5336141483d685427b75dc5e"
        }
      ]
    }
  ]
}
