{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.15.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.15.jar",
          "size": 384843,
          "sha512": "c6dff6010a59dade89dbb76772befdbc469398b3e0c3e50796edca49b50a712898837c63210b1554d598c58ab2f85a62932c094da2066d68c571507a42998393",
          "sha256": "cf99b6c1b9c337090bf51df93f84868a26254cc173181233ee615fefbc4e0d99",
          "sha1": "7373408452d0cd3f55a3e43a94df03af10845e34",
          "md5": "a9813e5b4d526bbc9e68c131065609b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.15.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.15.jar",
          "size": 384843,
          "sha512": "c6dff6010a59dade89dbb76772befdbc469398b3e0c3e50796edca49b50a712898837c63210b1554d598c58ab2f85a62932c094da2066d68c571507a42998393",
          "sha256": "cf99b6c1b9c337090bf51df93f84868a26254cc173181233ee615fefbc4e0d99",
          "sha1": "7373408452d0cd3f55a3e43a94df03af10845e34",
          "md5": "a9813e5b4d526bbc9e68c131065609b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.15-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.15-sources.jar",
          "size": 199699,
          "sha512": "6d56eff35afaa18ec86731a37136eb99b72df184ffdc3d5ce5b391b655e3bf3f9b955d454801f1dab3ec662844e164f5a3ffff9fed5397e1bf7839b9dc88c137",
          "sha256": "f695e398ab661accc7be9eae8b39e0ea7733706871e9adc5ec69ced898e4d1dd",
          "sha1": "ce2940fb486ec7eef1927abbdf9b81401cc9ff87",
          "md5": "37111ce3a1acf5d7cbab86f05e0c5139"
        }
      ]
    }
  ]
}
