{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.6.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.6.jar",
          "size": 520667,
          "sha512": "630c4451aea990b8e318b8b3d1fc7c7245a8ce2a0247630730c139093cb103f8218018c5217448927c93384083ea71504d66c4f337b6047cee239c1d93f6910a",
          "sha256": "b14867a079599f35e4f52d15b52d8dbceeb7992ca44fda5d4ac8d051a7ffdbd4",
          "sha1": "e2a4c23495448ad907ea78de292800dae1314fe6",
          "md5": "f6cc8ac0d625ff6f8bb55811b8b76617"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.6.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.6.jar",
          "size": 520667,
          "sha512": "630c4451aea990b8e318b8b3d1fc7c7245a8ce2a0247630730c139093cb103f8218018c5217448927c93384083ea71504d66c4f337b6047cee239c1d93f6910a",
          "sha256": "b14867a079599f35e4f52d15b52d8dbceeb7992ca44fda5d4ac8d051a7ffdbd4",
          "sha1": "e2a4c23495448ad907ea78de292800dae1314fe6",
          "md5": "f6cc8ac0d625ff6f8bb55811b8b76617"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.6-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.6-sources.jar",
          "size": 258737,
          "sha512": "c8b301e9c52ed20075be56604dedc3be72b22bc41b73eb1610595fc5a7f7e479dd3b9731f56fa03bb26c06e02ebf849f492e25fc330040b6a037e2d7287420c8",
          "sha256": "cbc04843673ef8d415f4b5d2e46242aee219f1a91241ad0328fe42cbbd71b8c5",
          "sha1": "78ca08cec185514b8ec3cac0d725a1a2953adcfd",
          "md5": "0114f00de0b106fc54f8c559cc221921"
        }
      ]
    }
  ]
}
