{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2510.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.1.jar",
          "size": 494646,
          "sha512": "f2c34b1d608aaf2e673c1313370a3212976bcabbd0a8603e3ba1658c39b891923a7619d42324d99b4195fd6a766e5e0cd6dd670cb06e5984ab81f12a83b08f92",
          "sha256": "c92b9964be796d65fdfe945924e8224947dad9dfc439a2f42d68f8baea6601db",
          "sha1": "7efddb4d7e2e178f0a18d5d0814f4f064b8fda1e",
          "md5": "9360d627c59e58c526b721d5d28ecad5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.1.jar",
          "size": 494646,
          "sha512": "f2c34b1d608aaf2e673c1313370a3212976bcabbd0a8603e3ba1658c39b891923a7619d42324d99b4195fd6a766e5e0cd6dd670cb06e5984ab81f12a83b08f92",
          "sha256": "c92b9964be796d65fdfe945924e8224947dad9dfc439a2f42d68f8baea6601db",
          "sha1": "7efddb4d7e2e178f0a18d5d0814f4f064b8fda1e",
          "md5": "9360d627c59e58c526b721d5d28ecad5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.1-sources.jar",
          "size": 250487,
          "sha512": "eb44e1f7f61ed4096e311ecbc31953120d22c34ee0121d4c9a824940d0e58be6365b7bfa508467ae7adcd5a995ed8f0159e0ebd2019af40b51125246d3ee8c0d",
          "sha256": "b16e25b3bbcd2a16fed1ce114cc10f0199bc17fd0532f0ef58fdb2662012f3a8",
          "sha1": "cb76395c65c13ca1354367674a949c6a0647ab0f",
          "md5": "ebe1e0b55613063fbbb2ba34b0574156"
        }
      ]
    }
  ]
}
