{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2516.3.jar",
          "size": 710546,
          "sha512": "f21a9f36620a37e925fbcc6a853ffa17253947cea5c2f019ac69ee3f43ae2313e3d593e145e46dc7dce78ee897870e0eac765a8e6194ac0379adfca36eedcf4e",
          "sha256": "69deeb041d2cae711cfb23ccca41f7a313438ac229d998ab1b0680daf42f37d6",
          "sha1": "d14ccf3c8799a59ece6ffab767265346550e58c8",
          "md5": "c00bc909be7649f348440b92c715d2b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2516.3.jar",
          "size": 710546,
          "sha512": "f21a9f36620a37e925fbcc6a853ffa17253947cea5c2f019ac69ee3f43ae2313e3d593e145e46dc7dce78ee897870e0eac765a8e6194ac0379adfca36eedcf4e",
          "sha256": "69deeb041d2cae711cfb23ccca41f7a313438ac229d998ab1b0680daf42f37d6",
          "sha1": "d14ccf3c8799a59ece6ffab767265346550e58c8",
          "md5": "c00bc909be7649f348440b92c715d2b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2516.3-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2516.3-sources.jar",
          "size": 253918,
          "sha512": "bf6724ba19c6e78721fc714d4ed8436a9ab079ee13c2863327e83902067709f4d1e12d672f8f65f9a4191058f694295ada3e8779d1793412d6ebbcf10f0e9066",
          "sha256": "5170160816bbbe8c9ce657d226c7e23e5011adaba19fec46f3b94bc3ec09009e",
          "sha1": "05bb552776fe2e02577fce69e009795a4fa6bb72",
          "md5": "211cae9910eb9162854e796a52739b85"
        }
      ]
    }
  ]
}
