{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.8.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.8.jar",
          "size": 370509,
          "sha512": "51cde1636766bf4e3d0c195c6662614a8596a8003475325200c24973d0c269c291c415edf169da7c14164a52e3d8da16d1b08357d4b493390dcfbb2bb95ad84c",
          "sha256": "61ea5b582b15764c88db6f5bdb995a1c0fb63761a99ccf1718d46ac7102de142",
          "sha1": "3b92013abd1424a856560b03b36a8ab150ced8a7",
          "md5": "8cc90f22119180051dfa73c9a6ac7460"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.8.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.8.jar",
          "size": 370509,
          "sha512": "51cde1636766bf4e3d0c195c6662614a8596a8003475325200c24973d0c269c291c415edf169da7c14164a52e3d8da16d1b08357d4b493390dcfbb2bb95ad84c",
          "sha256": "61ea5b582b15764c88db6f5bdb995a1c0fb63761a99ccf1718d46ac7102de142",
          "sha1": "3b92013abd1424a856560b03b36a8ab150ced8a7",
          "md5": "8cc90f22119180051dfa73c9a6ac7460"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.8-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.8-sources.jar",
          "size": 196551,
          "sha512": "ff2ae35d8ea283d384ed20cef881572c50641ff929cb9a3db8b50557afed1aeeb82aafe1347a8da5f08f52c507d518702aa7c20f646c60c6299e9bd67a61a380",
          "sha256": "9db75bab8071974aacf279644f12571a9bb2f9eb8d29fbab23ed7c356c6586f1",
          "sha1": "1656d187c1b9d32789bc6398034c470c33f6b2a5",
          "md5": "581519dd48be87b44780aeb8b16dca07"
        }
      ]
    }
  ]
}
