{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2518.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2518.4.jar",
          "size": 19685989,
          "sha512": "a0e577f25574d27ed6914909a4b4e60d9fb688049b101a223640b63d06720e9a1e02bbcf22d9143960f544142d1741c33e34f02f7fa8bbc7ce5c806adb05e140",
          "sha256": "e4069d3e8de1f906e69e56f7e11c52be633f7ccc46129307c1dd09b1bf177137",
          "sha1": "76b74ecedd26a996df5849cd1b960d5017ab9465",
          "md5": "750ac530b8ecb11fb0f59e40b223af8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2518.4.jar",
          "size": 19685989,
          "sha512": "a0e577f25574d27ed6914909a4b4e60d9fb688049b101a223640b63d06720e9a1e02bbcf22d9143960f544142d1741c33e34f02f7fa8bbc7ce5c806adb05e140",
          "sha256": "e4069d3e8de1f906e69e56f7e11c52be633f7ccc46129307c1dd09b1bf177137",
          "sha1": "76b74ecedd26a996df5849cd1b960d5017ab9465",
          "md5": "750ac530b8ecb11fb0f59e40b223af8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2518.4-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2518.4-sources.jar",
          "size": 18824586,
          "sha512": "2fd66b08365939d87b89e95d4d1041e3282c6ca65ac85ef980999cd27b365fed2d88e26afee9db92da73ff721bbc23b67ef3313370be6c3bbcc2234b44f89a05",
          "sha256": "9b183c21cbb8869d7bcdda00f911d2a949bcf80e50bed72a6f5648bbc905d355",
          "sha1": "67d85da4df9dcbe9b9978e6957ab9ab9a373763b",
          "md5": "d1788f9169ecb750fa44ccca8442a257"
        }
      ]
    }
  ]
}
