{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.5.jar",
          "size": 681786,
          "sha512": "16525d6ed0fda5519d78a5e44a8e230ff110fd2744e537ccf90247d0d079736cab0952f3c5ac3fb9f0561efa63485feffed7111afdc23b71b697ec465a9d2382",
          "sha256": "3861dd288acf80845aed0f8f0d812915ec85206c66dc78b29a371a44f4ab8b6f",
          "sha1": "634b18556b4de97b0b6c44e7c31270e8c49625b4",
          "md5": "72144c2fa757b65def7ce305c0d25609"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.5.jar",
          "size": 681786,
          "sha512": "16525d6ed0fda5519d78a5e44a8e230ff110fd2744e537ccf90247d0d079736cab0952f3c5ac3fb9f0561efa63485feffed7111afdc23b71b697ec465a9d2382",
          "sha256": "3861dd288acf80845aed0f8f0d812915ec85206c66dc78b29a371a44f4ab8b6f",
          "sha1": "634b18556b4de97b0b6c44e7c31270e8c49625b4",
          "md5": "72144c2fa757b65def7ce305c0d25609"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.5-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.5-sources.jar",
          "size": 252430,
          "sha512": "e8f727ad696693701c6102b7a83a197ddda972fef827854440e26bd2cd1330557b0285a5f1c2c2f2fc28cd9af189591ae09c6c817fb8a8081a0ccead72211bb7",
          "sha256": "90af4132ac85e6ac1123c5f2a60ba9411f857669d7406055c85b6df7df783b81",
          "sha1": "e8eafcdb1d4664bb71407abe79e44c0bbdc0f4b9",
          "md5": "10da9b79a79e8c5357d60923003943c7"
        }
      ]
    }
  ]
}
