{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2501.22"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2501.2.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2501.2.jar",
          "size": 11918661,
          "sha512": "6e452a1ccfb9b6886e5945a8921e7bea932d8d0c8ee5819768095ba50abf49cb1c5c7c6563f730313669d56e18513af6f594edc8e10baa00e8c628ea0fd66412",
          "sha256": "799e04743064c1b01cdc5fe1c43f2561c3a3751c806d68beb629a8ebaea185a2",
          "sha1": "871a347fd9c4c75c12de3a295d901c1d3b4734f9",
          "md5": "898fc8e07ff8bc7723b2332b942193f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2501.22"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2501.2.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2501.2.jar",
          "size": 11918661,
          "sha512": "6e452a1ccfb9b6886e5945a8921e7bea932d8d0c8ee5819768095ba50abf49cb1c5c7c6563f730313669d56e18513af6f594edc8e10baa00e8c628ea0fd66412",
          "sha256": "799e04743064c1b01cdc5fe1c43f2561c3a3751c806d68beb629a8ebaea185a2",
          "sha1": "871a347fd9c4c75c12de3a295d901c1d3b4734f9",
          "md5": "898fc8e07ff8bc7723b2332b942193f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2501.2-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2501.2-sources.jar",
          "size": 11133258,
          "sha512": "26de53c41337ac9a176315e63ce46cb95e9ffa003a973510b0162d0c6a4f8e5d456d4db31dd7773e97bf8335c1337b496fe606f7db154f6578e2e260a7de801c",
          "sha256": "5e38d1ec63337f384d74ead6703a46ae52aaaff9f9e62d83ac2c496025b21bc7",
          "sha1": "8e2849bc81dbd9f75a828521bde5cd8f2d8d5db2",
          "md5": "f32275237537d6269f462569df0d4fcc"
        }
      ]
    }
  ]
}
