{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.5-lts",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.5-lts.jar",
          "url": "legacy-neoforge-1.21.4-1.8.5-lts.jar",
          "size": 19927260,
          "sha512": "3c6764eecd657e6f92289d54e71b57aeb437439e79b25b70603c5fec8d091850a12f9462c866c3a8a5cfc93e21b5096f79f6004429e03b7f61beb2cfcd7e20b7",
          "sha256": "a650267a8234d6704af961c8f4d24e38913931e41f350a59d6be578add97a38b",
          "sha1": "f4bc266a291b961954f31cbd028f9ef4f82ac79c",
          "md5": "676fa2adcd43afe0bc21333b87b2002f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.5-lts.jar",
          "url": "legacy-neoforge-1.21.4-1.8.5-lts.jar",
          "size": 19927260,
          "sha512": "3c6764eecd657e6f92289d54e71b57aeb437439e79b25b70603c5fec8d091850a12f9462c866c3a8a5cfc93e21b5096f79f6004429e03b7f61beb2cfcd7e20b7",
          "sha256": "a650267a8234d6704af961c8f4d24e38913931e41f350a59d6be578add97a38b",
          "sha1": "f4bc266a291b961954f31cbd028f9ef4f82ac79c",
          "md5": "676fa2adcd43afe0bc21333b87b2002f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.5-lts-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.5-lts-sources.jar",
          "size": 19036278,
          "sha512": "1e4c43aeb425970b461bf18ec5ca159ae5b5a9d8074c3db086de697801af62fce4d880b9738dda1767253f1c6cf800ed34d66726c310923eb3802af9765abe1e",
          "sha256": "4f81b44330faf2aaafbbb748c8a3f4d224b28aa1947f37a9a84601e46a1657ee",
          "sha1": "6ebea64d55b510c0ba84df393de65e44027e2185",
          "md5": "e6a4b7b22bb2465dc9dda0231eb6c07b"
        }
      ]
    }
  ]
}
