{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.8.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.8.jar",
          "size": 548510,
          "sha512": "48204b1b8ab78d2af05ad7af44dc78666ae07d05b88d694755d395b201471ab5d43b155466ced902a7cec3986df16daa790031924638c7b09ce04822809f4fd3",
          "sha256": "ba588e975b535b51acb0590a77c3d9c291565fb337daacbdcaf4f3265f1a9def",
          "sha1": "fc405c8326c834118838e3ebd6871921b7a81250",
          "md5": "3568f942fd557b671953e1bca013aed2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.8.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.8.jar",
          "size": 548510,
          "sha512": "48204b1b8ab78d2af05ad7af44dc78666ae07d05b88d694755d395b201471ab5d43b155466ced902a7cec3986df16daa790031924638c7b09ce04822809f4fd3",
          "sha256": "ba588e975b535b51acb0590a77c3d9c291565fb337daacbdcaf4f3265f1a9def",
          "sha1": "fc405c8326c834118838e3ebd6871921b7a81250",
          "md5": "3568f942fd557b671953e1bca013aed2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.8-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.8-sources.jar",
          "size": 256760,
          "sha512": "a6f5714dee6a71d082c4930cf411520415f9560571da3d05d2feb1a2824084eee2f13e96f13d9b5988a78e7652b78c11de6921e901acbeba8a2ca2802942e97d",
          "sha256": "95d43d84cacd711c3f5e1f7651f36ce8cf4880304fdbea7391f9fea484f5b3f3",
          "sha1": "7a3c91398e0bf136ab1fdbe10cfa465e4e8d3ef3",
          "md5": "9a4095c67b96cfdcfc88ff4264b92416"
        },
        {
          "name": "factory_api-neoforge-1.21.3-2.2.8-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.8-sources.jar",
          "size": 256760,
          "sha512": "a6f5714dee6a71d082c4930cf411520415f9560571da3d05d2feb1a2824084eee2f13e96f13d9b5988a78e7652b78c11de6921e901acbeba8a2ca2802942e97d",
          "sha256": "95d43d84cacd711c3f5e1f7651f36ce8cf4880304fdbea7391f9fea484f5b3f3",
          "sha1": "7a3c91398e0bf136ab1fdbe10cfa465e4e8d3ef3",
          "md5": "9a4095c67b96cfdcfc88ff4264b92416"
        }
      ]
    }
  ]
}
