{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2500.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.4.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.4.jar",
          "size": 350684,
          "sha512": "ee20c3b7776b2152837f2fe64fadbcc64589ba18b040569401854aa4fd777230685e01b67852bad36ae026886810ada26f096f3e57263badccb4911b62fed6ef",
          "sha256": "a281b8a294e9742b8cfd1792da3a868d059e0d16245353680b4323f82157052b",
          "sha1": "18af1494dac444c3188f13519f54c1f899f16583",
          "md5": "f2e283dbfa4c2141554940df468fe51d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.4.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.4.jar",
          "size": 350684,
          "sha512": "ee20c3b7776b2152837f2fe64fadbcc64589ba18b040569401854aa4fd777230685e01b67852bad36ae026886810ada26f096f3e57263badccb4911b62fed6ef",
          "sha256": "a281b8a294e9742b8cfd1792da3a868d059e0d16245353680b4323f82157052b",
          "sha1": "18af1494dac444c3188f13519f54c1f899f16583",
          "md5": "f2e283dbfa4c2141554940df468fe51d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.4-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.4-sources.jar",
          "size": 194559,
          "sha512": "fc690db19fe3a879d00b01462d72da4f1cbb08a81e365cda8414cb5a0686d78c2958ae008b4b8d797cd811f461909678d8b50c8ccf344688a59b9ab0bdc588c9",
          "sha256": "544e125c9ff4ba6cc970fba6d12f0b1555f854ee0607475f9505f1ba4bfda422",
          "sha1": "90afc49d23b7b689aa5b79c397d5132285821595",
          "md5": "e3553ea75217e64dd3d52cbfad62becd"
        }
      ]
    }
  ]
}
