{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-forge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.5.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.5.jar",
          "size": 19727819,
          "sha512": "8011ec02416bdf00c3cf78bdb1e79b3e20cd9dbd257874734d0e9c6c7459a07cc527a66e23c5a2c6cff50602443914dc8d21f0a3eab8804b444e5494f80e6579",
          "sha256": "60300d950b83745296213b92d1c9cffa9fcb4dbf1214af79c4f6438ad487496d",
          "sha1": "512f5fde4a941852a7aae9b2b23544c0a61f896e",
          "md5": "f46226fbf217c0c3af6b6f35d8d4f1aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.5.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.5.jar",
          "size": 19727819,
          "sha512": "8011ec02416bdf00c3cf78bdb1e79b3e20cd9dbd257874734d0e9c6c7459a07cc527a66e23c5a2c6cff50602443914dc8d21f0a3eab8804b444e5494f80e6579",
          "sha256": "60300d950b83745296213b92d1c9cffa9fcb4dbf1214af79c4f6438ad487496d",
          "sha1": "512f5fde4a941852a7aae9b2b23544c0a61f896e",
          "md5": "f46226fbf217c0c3af6b6f35d8d4f1aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.5-sources.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.5-sources.jar",
          "size": 18860137,
          "sha512": "ee4f82c3c8d26d8ff7f9e650f1a40d46471c55cc4dda5ef83162c92b12917776d587f88d8cc72959eeee0fea62e6647773b3f563ad9564ba951b9108345814bb",
          "sha256": "7fa6ca47015b00733d49c0b8df0e264730b2bcd12ba403c0cf7824d68b3877e7",
          "sha1": "c35b4d2ab022de6eae713f3294f5f4620b7268e4",
          "md5": "c32ef0265d12854fc0b45fd68f0c3cf4"
        }
      ]
    }
  ]
}
