{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.1-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "size": 546102,
          "sha512": "cc10c46adbb989b14cff4bfef3255d79df7650dd128a0f2c484d8663bda69b37528ca08716e7b1ce54b9f8bd73fdf05836133734a118051251b85eb26357cf5d",
          "sha256": "1bdbed7cb21d49ff35b20d527ddde426e5dc745907ff2734d15b4bbff48bf4f8",
          "sha1": "213937b0fc1db327d60874f04750dc3e8229ba57",
          "md5": "f17ba826860772e88721c4f7039ab881"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "size": 546102,
          "sha512": "cc10c46adbb989b14cff4bfef3255d79df7650dd128a0f2c484d8663bda69b37528ca08716e7b1ce54b9f8bd73fdf05836133734a118051251b85eb26357cf5d",
          "sha256": "1bdbed7cb21d49ff35b20d527ddde426e5dc745907ff2734d15b4bbff48bf4f8",
          "sha1": "213937b0fc1db327d60874f04750dc3e8229ba57",
          "md5": "f17ba826860772e88721c4f7039ab881"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2517.0-sources.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2517.0-sources.jar",
          "size": 252682,
          "sha512": "4d4342cd541f0f47b4d07c21b09375dfb25d949923c04bdae9f857274d5caafd52c5fd2d985b5b657a9b781b1f6da5cc475f7a30da0a2198b64048df6f838ad9",
          "sha256": "4eb7a8dfeb7f3b8b965351da2c4a04dc9ac96116ba5083f0394d799f790ac1e6",
          "sha1": "e9540310eb0f02c9aecdaff27037eaae41c983ef",
          "md5": "6877e890a9cbbc2b48aa1e58e26b6875"
        }
      ]
    }
  ]
}
