{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.1-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "size": 546524,
          "sha512": "dec3284adaea87bc1fc72cfaaad514c60e2f24252797cd9d5ba8ebf8e088eeb3fb653d4308165fa18375aefe55025d1e8cc33fd065a583216acc364ef7522e05",
          "sha256": "27992951481a8d61bdc41d592f86335529e0c634737ecebe9613c41eea8a066d",
          "sha1": "12f8ef6346d9a2f966c03370ec32d88e3c7579f5",
          "md5": "a7aec92f797d902953690b63bfbb5c5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2517.0.jar",
          "size": 546524,
          "sha512": "dec3284adaea87bc1fc72cfaaad514c60e2f24252797cd9d5ba8ebf8e088eeb3fb653d4308165fa18375aefe55025d1e8cc33fd065a583216acc364ef7522e05",
          "sha256": "27992951481a8d61bdc41d592f86335529e0c634737ecebe9613c41eea8a066d",
          "sha1": "12f8ef6346d9a2f966c03370ec32d88e3c7579f5",
          "md5": "a7aec92f797d902953690b63bfbb5c5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2517.0-sources.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2517.0-sources.jar",
          "size": 252868,
          "sha512": "0b9ca1affaa2a78e0886e84fea8aeda6e4480569f13c5ceac6aebf513def029fd9784e70f09e1910abae98ff88cc41a83b185e8b5186d47d403f52ba9dee1d50",
          "sha256": "d10946682f81071faa8fb0324e8936363d56937ab970dbca611df6218bf71b62",
          "sha1": "07c1f20f8cb719067571f5622531a6c47904d8d3",
          "md5": "b2a5332f1068caccd2c5a11393159261"
        }
      ]
    }
  ]
}
