{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "size": 490612,
          "sha512": "9a214fed21e2ff0ec4b71d62ea7e58c13dbec545262358adfdc53ba0605ac8efadd4e3dc39b22b3c673ffc94e12835ceaf5d0b6a9859de1984274281e300a628",
          "sha256": "ea7ae7a308dcf3c13d046b0f1986768f272be08e0f9b2be49653f14f0e4aab7d",
          "sha1": "520ce3d262f95b85fc8c82d792ce41a2cfef747d",
          "md5": "91f95bbddfad68823851e416e59d61d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "size": 490612,
          "sha512": "9a214fed21e2ff0ec4b71d62ea7e58c13dbec545262358adfdc53ba0605ac8efadd4e3dc39b22b3c673ffc94e12835ceaf5d0b6a9859de1984274281e300a628",
          "sha256": "ea7ae7a308dcf3c13d046b0f1986768f272be08e0f9b2be49653f14f0e4aab7d",
          "sha1": "520ce3d262f95b85fc8c82d792ce41a2cfef747d",
          "md5": "91f95bbddfad68823851e416e59d61d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2506.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2506.0-sources.jar",
          "size": 238951,
          "sha512": "26f97fe4e5127e166c0655b5e594f1e3401e2020f329883520554bad6d7e201c2903df3e1870c1df7dbcf32a3934243ef2412d177e9a2874abfebfc4117348a3",
          "sha256": "2b885300aadc39e0eae74b5f46a206b76ad08a89e831daf32e91ceaa112d0919",
          "sha1": "2ecc73ad17557020080e489554587e84172b98da",
          "md5": "03c62a19c55708d06dcd3d58b5432320"
        }
      ]
    }
  ]
}
