{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "size": 491605,
          "sha512": "dd625c15f71eaea28a7185b8e0de2809a007f1f5559aef45d902bf86bf0b0fe739dd6649da1e0a7a228a6aa0ffd224e67847acbd8945d8ced7919b7ce6d7c398",
          "sha256": "ef71380cadae0f710983031518745a2167c9e46fc179f2027a7ca22a78eb14a4",
          "sha1": "c9a295e7838d832f316ffa58f26588b2af804d9d",
          "md5": "555fb19e9647a4b3f6b084376ff101af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.2506.0.jar",
          "size": 491605,
          "sha512": "dd625c15f71eaea28a7185b8e0de2809a007f1f5559aef45d902bf86bf0b0fe739dd6649da1e0a7a228a6aa0ffd224e67847acbd8945d8ced7919b7ce6d7c398",
          "sha256": "ef71380cadae0f710983031518745a2167c9e46fc179f2027a7ca22a78eb14a4",
          "sha1": "c9a295e7838d832f316ffa58f26588b2af804d9d",
          "md5": "555fb19e9647a4b3f6b084376ff101af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2506.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2506.0-sources.jar",
          "size": 239162,
          "sha512": "d54bd71abc46aa86c95f151c31f760b3b2a60389d8746b10af8c954b6c11836449a4f69f83dd45c68271d35fadcf8ac5172f2b176f7775468bd3fcafc26d135e",
          "sha256": "be4212c48f462345dcb78fb9f468e76d583fec77e2d27c558f9e5d063a2e00d1",
          "sha1": "d7ecb037c588a689305c242aaa49ccaf1d2a0d4e",
          "md5": "af7d303f8ecb68dc158a11fbedea34e8"
        }
      ]
    }
  ]
}
