{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2507.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.4.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.4.jar",
          "size": 503919,
          "sha512": "3c6e3916a31c10c4dc0cf43e44d538f888549aa56238ae5fe668a3f4e88ab892be3cc38e868bddcd67fc198243d870ff017b23624c76162edac64b8cb0c8683d",
          "sha256": "6ff015b076106107d101ed4fe4d511c1b2372203a094ff04e88e0964d74af814",
          "sha1": "7dcfc8941c518b11aca560e362ee595fbbc21c86",
          "md5": "a1f933ec398e7ad4bb2b2351e8869911"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.4.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.4.jar",
          "size": 503919,
          "sha512": "3c6e3916a31c10c4dc0cf43e44d538f888549aa56238ae5fe668a3f4e88ab892be3cc38e868bddcd67fc198243d870ff017b23624c76162edac64b8cb0c8683d",
          "sha256": "6ff015b076106107d101ed4fe4d511c1b2372203a094ff04e88e0964d74af814",
          "sha1": "7dcfc8941c518b11aca560e362ee595fbbc21c86",
          "md5": "a1f933ec398e7ad4bb2b2351e8869911"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.4-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.4-sources.jar",
          "size": 246357,
          "sha512": "6ab283a7e29329d8b26d814a5600e9de225134ade5ca1e9de5a651f0d0fff51675a1128afd8233f5181ce4b4316ae57e6d06650a32b98fd2762e9fbb3712c319",
          "sha256": "01d95de492c8f32784adb0992cd61f20261533e0d1c0efdb985aa25a819bd0af",
          "sha1": "78f76400ca89baf245fcc9adff67cb1273d47baf",
          "md5": "f61725a1adea05a1acdb7555b7abe3c9"
        }
      ]
    }
  ]
}
