{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2501.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.21.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.21.jar",
          "size": 392290,
          "sha512": "2d51ff7dd735f849dc4499c1d2738508ced9ad3d0c6140e150f08b6d7f2d15b15922f05d133dd5d8501bcb0018873f626ba8b1a8ba8f68fd36392f3deea2930c",
          "sha256": "a988d7de28868b281a177401b14ba842a2c13c763061cad00bec7b3b7805d8a0",
          "sha1": "757c3bbbf09fec4f22db454571da88eb46d3c24e",
          "md5": "20b1e7808fed96253d779b7f2ca0b31c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.21.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.21.jar",
          "size": 392290,
          "sha512": "2d51ff7dd735f849dc4499c1d2738508ced9ad3d0c6140e150f08b6d7f2d15b15922f05d133dd5d8501bcb0018873f626ba8b1a8ba8f68fd36392f3deea2930c",
          "sha256": "a988d7de28868b281a177401b14ba842a2c13c763061cad00bec7b3b7805d8a0",
          "sha1": "757c3bbbf09fec4f22db454571da88eb46d3c24e",
          "md5": "20b1e7808fed96253d779b7f2ca0b31c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.21-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.21-sources.jar",
          "size": 201367,
          "sha512": "429b7c96347a90d6b0802a3ab836eccaae18489ccfd38ba1f506610731f8d93627579032ecc1f824ca4c2542c4a0c6f33073a0e83d68a92d719b8c2fd02248a1",
          "sha256": "c7f6cc08e2efe096cf58cc20e859eef17fca6819c4996462e7b29e349d7ad83c",
          "sha1": "cf6bd0dbdbb1cf37481b719695914bc433639cbd",
          "md5": "22af7ae1e45265ba7697e5c3028b94fd"
        }
      ]
    }
  ]
}
