{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.8.5-lts",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.5-lts.jar",
          "url": "legacy-neoforge-1.21.3-1.8.5-lts.jar",
          "size": 19928664,
          "sha512": "c04ecfd0c79056bbdd311c43283ee0b0dbb562cc5d84e053768eeeca3935517432cde57a5a9b57380f71327246edf8e62ba2e605204bd16f64a7a77c0e4d8cc0",
          "sha256": "d4c7805a48977f102e1b78a8d8bbddb465d68ec8bd792f36e0bb9f7c472760aa",
          "sha1": "6982c4f521bb7a8f98f3e580fc5d7d3f1d176ac6",
          "md5": "0c097eebe44bb2759d1a2ee708e4f9b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.5-lts.jar",
          "url": "legacy-neoforge-1.21.3-1.8.5-lts.jar",
          "size": 19928664,
          "sha512": "c04ecfd0c79056bbdd311c43283ee0b0dbb562cc5d84e053768eeeca3935517432cde57a5a9b57380f71327246edf8e62ba2e605204bd16f64a7a77c0e4d8cc0",
          "sha256": "d4c7805a48977f102e1b78a8d8bbddb465d68ec8bd792f36e0bb9f7c472760aa",
          "sha1": "6982c4f521bb7a8f98f3e580fc5d7d3f1d176ac6",
          "md5": "0c097eebe44bb2759d1a2ee708e4f9b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.5-lts-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.8.5-lts-sources.jar",
          "size": 19036306,
          "sha512": "d38b510fd143791d6a519b809d2ec264bda369a19bc413eca21ba52b3a8a19ffcc9d2ccbd04a264df8215bb63b7471ec4cc2cf79bcffb04fce2566692944e4d4",
          "sha256": "82d5bf8fa822eea3354d7de5592c8782ed36fbe93f75126cca61a836817b099e",
          "sha1": "c681d8f2f2f88492e76593dc5ae182b8ab36e91f",
          "md5": "7183fcb574a9522e7388507e56cacbaf"
        }
      ]
    }
  ]
}
