{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2507.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.12.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.12.jar",
          "size": 504445,
          "sha512": "5452db754d2d5ec92702dc4cf3e5df1d624967cd4d4d28f97e3c35f6f627e9f783a45bcf158dc58ee8de097f7b71b1fc0b0dfa8f0770e11daa08c378303551f8",
          "sha256": "fb88a452df80f632a1bb79047d1accf48b73cbbded48260373424b938a56d2e9",
          "sha1": "16a2fa26a530f9212a2ba4d81eb92de55b5e38f1",
          "md5": "779f2daaf35247da9671f9945916fd7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.12.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.12.jar",
          "size": 504445,
          "sha512": "5452db754d2d5ec92702dc4cf3e5df1d624967cd4d4d28f97e3c35f6f627e9f783a45bcf158dc58ee8de097f7b71b1fc0b0dfa8f0770e11daa08c378303551f8",
          "sha256": "fb88a452df80f632a1bb79047d1accf48b73cbbded48260373424b938a56d2e9",
          "sha1": "16a2fa26a530f9212a2ba4d81eb92de55b5e38f1",
          "md5": "779f2daaf35247da9671f9945916fd7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.12-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.12-sources.jar",
          "size": 246666,
          "sha512": "a66f50b7a2cc94c3f9c6cc442b235bde86c89ee122a1d437d9b00f79a68c89e5a1c65df77dbc4828367c7920692ca9faf383174f9d5c42e53324a00bbf2be307",
          "sha256": "a5aa8e816440ce7dbf5bb3481a07de5ea5faa063ffb1365379c50a5db1289c27",
          "sha1": "861b488d7e7e02799b9d2e33970b03fcc9bf58fb",
          "md5": "036723d88c8439d34dd11c88dfb77a4b"
        }
      ]
    }
  ]
}
