{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.3.2516.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.6.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.6.jar",
          "size": 530691,
          "sha512": "ec7abcb56fb21041c9abf3f88a586db42551be031de041601b67445cb449526029d5bce54dfdf9a359dde0c811aeb5b02b9ea403d9d56c5447e8a3fe03e55267",
          "sha256": "62e8d6d3bc8b3de6c3cb6c55f3dd7820151a33923d27704141bce03d13c1d35e",
          "sha1": "cfaef2fe2fb1b3c7bcfc2be8d88681e7129a3266",
          "md5": "d0da90d8b0c4ae9a52cd20bfc331470f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.6.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.6.jar",
          "size": 530691,
          "sha512": "ec7abcb56fb21041c9abf3f88a586db42551be031de041601b67445cb449526029d5bce54dfdf9a359dde0c811aeb5b02b9ea403d9d56c5447e8a3fe03e55267",
          "sha256": "62e8d6d3bc8b3de6c3cb6c55f3dd7820151a33923d27704141bce03d13c1d35e",
          "sha1": "cfaef2fe2fb1b3c7bcfc2be8d88681e7129a3266",
          "md5": "d0da90d8b0c4ae9a52cd20bfc331470f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.6-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.6-sources.jar",
          "size": 254299,
          "sha512": "7bb47d2e4a79052efbee4f739780ebc4fea700e47fe4e53805c72e0865ef6a1e68b9f319481ea12e5577c3ff63be02b775677a18553658c70330ac83b88526f6",
          "sha256": "0eba76b588c86f8bb203798d2d1e84c35784f539e7a1ac139d112ad2f882aca0",
          "sha1": "fff1488e66c97fe548fa9ca123d893bd0ea241fd",
          "md5": "dce2748061ebfee9d10085743a6f8d52"
        }
      ]
    }
  ]
}
