{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2500.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.9.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.9.jar",
          "size": 351575,
          "sha512": "cf072872a16e2c6f788034dfb5899feae9829a66627d6693be147f159791aec5d5d308be3e911fb7b2e29952b5b6169a4b2ee3f9763bb95393a86d9adce900c0",
          "sha256": "02a0ff1cb7b2bcec4363e6836474e410104971b7f10e63b03149ff4ffda833e1",
          "sha1": "6fe81432c8bbe0634678c848682b49d783a12c1b",
          "md5": "eb648cba85f49893dbb1d101d06c85b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.9.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.9.jar",
          "size": 351575,
          "sha512": "cf072872a16e2c6f788034dfb5899feae9829a66627d6693be147f159791aec5d5d308be3e911fb7b2e29952b5b6169a4b2ee3f9763bb95393a86d9adce900c0",
          "sha256": "02a0ff1cb7b2bcec4363e6836474e410104971b7f10e63b03149ff4ffda833e1",
          "sha1": "6fe81432c8bbe0634678c848682b49d783a12c1b",
          "md5": "eb648cba85f49893dbb1d101d06c85b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2500.9-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2500.9-sources.jar",
          "size": 194824,
          "sha512": "5c6d09e3f2223cf37c4e24ff97b590cf5a7c1cd5cf829dc8bd58394c0f0a78422e381bf56de151434120336d90fb19db50a55d8ab43fb51cbbce159385bf2ac8",
          "sha256": "a3c68997387923a10057ab614626c2cdc18a3c0a7d9eb18567da252d653c667f",
          "sha1": "8d78167c3ed65230e708bdfaf2cba1b9bac54c27",
          "md5": "cb8e929c9f963a8c514aca0097227eb0"
        }
      ]
    }
  ]
}
