{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.7.10.2501.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2501.0.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2501.0.jar",
          "size": 11907252,
          "sha512": "bcd17eaad667e9bdcb9599038dcd4546432e93de78b9b9eadbdfecc6f27f2ec994b7e1f5bb3606c614d1a3f310d77fbff6314da36c57ddd4d7422006ed62f06f",
          "sha256": "efcde68b9487af801daa5a61178379a0270e7e3ded0f88c3ad31f8946c666b4a",
          "sha1": "b5af009f2587c4b51d2ea6cfebc365a9b4dda8f6",
          "md5": "0391cef7472f48ee438da0d5a05529a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2501.0.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2501.0.jar",
          "size": 11907252,
          "sha512": "bcd17eaad667e9bdcb9599038dcd4546432e93de78b9b9eadbdfecc6f27f2ec994b7e1f5bb3606c614d1a3f310d77fbff6314da36c57ddd4d7422006ed62f06f",
          "sha256": "efcde68b9487af801daa5a61178379a0270e7e3ded0f88c3ad31f8946c666b4a",
          "sha1": "b5af009f2587c4b51d2ea6cfebc365a9b4dda8f6",
          "md5": "0391cef7472f48ee438da0d5a05529a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2501.0-sources.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2501.0-sources.jar",
          "size": 11122003,
          "sha512": "a7ebd718f3900e66504da83328ccafe350920e24ddfc1a2cda9f15a69b144b817c4cde0fd2efd41ae8941216c026230e9ab84f93868995c47b7a1297335a0ed4",
          "sha256": "8ff5eda5e57a48fb575eb979a443a95bce47c61f246471fbd41e82a7a2318d5e",
          "sha1": "bced9a19c955edc0c048358559ca4afa3e921b29",
          "md5": "e7c67fe839d9de3b6530c92e430a0b58"
        }
      ]
    }
  ]
}
