{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.7.10.2509.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2509.0.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2509.0.jar",
          "size": 14394820,
          "sha512": "c7b30c50e147895dce9de0da26442a04bfd025d8d88c2852c73cfe38345d8df4402642d9e8b41a5182c9646425378228f68ee3a2d934b812e4103e66e1420d2d",
          "sha256": "c529fda4e76f449e348bb62a89862b3c1a51b4f89ac2406c7f72f0d2795f9843",
          "sha1": "53b2a830a52d8850fc3f16f5289e59336cc03f74",
          "md5": "fe11e6862fbd3950cf6cbf79b2710b5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2509.0.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2509.0.jar",
          "size": 14394820,
          "sha512": "c7b30c50e147895dce9de0da26442a04bfd025d8d88c2852c73cfe38345d8df4402642d9e8b41a5182c9646425378228f68ee3a2d934b812e4103e66e1420d2d",
          "sha256": "c529fda4e76f449e348bb62a89862b3c1a51b4f89ac2406c7f72f0d2795f9843",
          "sha1": "53b2a830a52d8850fc3f16f5289e59336cc03f74",
          "md5": "fe11e6862fbd3950cf6cbf79b2710b5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2509.0-sources.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2509.0-sources.jar",
          "size": 13581395,
          "sha512": "f96c8f78e23fc3e5891a4feaa89132ec7a62e0aca8d9ad00c9609a87333aa12bd62cf26002f7e9aaa8fd39d20a001a713d11627d890eb2ca7bd51e8642b4bb2d",
          "sha256": "59671c75322f62e5cd6a84d46d489b977f78be820425abdeef0d35199c82a429",
          "sha1": "8bc6248ca026736ad9c2726ef76790150d5020dd",
          "md5": "f8d603d4447cfb6ec5dc313d6de55bc0"
        }
      ]
    }
  ]
}
