{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.0.jar",
          "size": 707597,
          "sha512": "8afc2f8077e0a8dd787047771fbb7beb3e119a589765acf19fe5b00fa78fa42e21576bfaca0c76efd87c905bec8a9745a8590d4be87a80889b6cda93816c6cec",
          "sha256": "22def1f3314d4e0f8b1b11a38154902a7e8c726d4d0b28cc447ccd2dd53df5c8",
          "sha1": "ebbcb0c888176747622d3d116c3cd0ed8288bdb4",
          "md5": "9272b5e3e534b0f8124319f9cbb686e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.0.jar",
          "size": 707597,
          "sha512": "8afc2f8077e0a8dd787047771fbb7beb3e119a589765acf19fe5b00fa78fa42e21576bfaca0c76efd87c905bec8a9745a8590d4be87a80889b6cda93816c6cec",
          "sha256": "22def1f3314d4e0f8b1b11a38154902a7e8c726d4d0b28cc447ccd2dd53df5c8",
          "sha1": "ebbcb0c888176747622d3d116c3cd0ed8288bdb4",
          "md5": "9272b5e3e534b0f8124319f9cbb686e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.0-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.0-sources.jar",
          "size": 252326,
          "sha512": "58a4d54dec8e6caa988ce83389d0b0fb49e391e01445d0ea2de96851ae9dcdf3b52ee63053264571bd6c46ab420660d301bab0f4d901523aa15445f7f1efa189",
          "sha256": "2043b5cf88ddb5ddb0017853e82e4f6286508350132b645d07c58f589a4680bc",
          "sha1": "aa4e4165067ef8b59bbe676b3198b7df17085753",
          "md5": "1060e882c5afe43920f189606c946182"
        }
      ]
    }
  ]
}
