{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.1-1.1.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.0.jar",
          "size": 597403,
          "sha512": "ce7bde2a1bab0ce22dd7d2ebf66699cbd069ab5e530245dd0cde2d6e5604c87c6a9d270b52c493daa0fcc5cb9794e35ccbf07e301c51da2aeb7a9f6e65b059e7",
          "sha256": "aef9f671eb6151d8c3980c9134fdb18fe627fa5d11b3c23745654b6a118b8cdb",
          "sha1": "78cbcc2d93edee9244c3f2abada705404ce2276d",
          "md5": "78c0d1be9bc27b4876472c8b23436039"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.0.jar",
          "size": 597403,
          "sha512": "ce7bde2a1bab0ce22dd7d2ebf66699cbd069ab5e530245dd0cde2d6e5604c87c6a9d270b52c493daa0fcc5cb9794e35ccbf07e301c51da2aeb7a9f6e65b059e7",
          "sha256": "aef9f671eb6151d8c3980c9134fdb18fe627fa5d11b3c23745654b6a118b8cdb",
          "sha1": "78cbcc2d93edee9244c3f2abada705404ce2276d",
          "md5": "78c0d1be9bc27b4876472c8b23436039"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.0-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.1-1.1.2516.0-sources.jar",
          "size": 536337,
          "sha512": "45cb9e98354dd675db6038a5960b6c10c4c75ac6200a5831934754cedeb703c8437d689b289d4266c668ff3774f81183f37a1ee8aaf303172ec8dfd6fa077167",
          "sha256": "42bd1c0140c6121a56e9dfd50e7cf5a7ec02895a59c2d7cde149fb9aac5735c0",
          "sha1": "e1c4e59358d6e085fcae8e98f7b8e97bf13cb417",
          "md5": "e26a54549b000a11ec8ecfcbfcabd71c"
        }
      ]
    }
  ]
}
