{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2511.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2511.1.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2511.1.jar",
          "size": 18255673,
          "sha512": "ec7f0a4fbfb5abee33963e681626b6efdb7a767d26b9bd443879a4048827bba85e0585de8569310200ea3eb67bc0bbd89c211b1dc7d97c97356bb3f8c43f6492",
          "sha256": "1ae07def37199a62009bead9f900cb4882899179dfbd6a3dd410f2ba1548aff3",
          "sha1": "2a3db44c4309adca6c0a6580d810d84b3c9f118c",
          "md5": "cceb81926d31c9c264b50b2fad103b49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2511.1.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2511.1.jar",
          "size": 18255673,
          "sha512": "ec7f0a4fbfb5abee33963e681626b6efdb7a767d26b9bd443879a4048827bba85e0585de8569310200ea3eb67bc0bbd89c211b1dc7d97c97356bb3f8c43f6492",
          "sha256": "1ae07def37199a62009bead9f900cb4882899179dfbd6a3dd410f2ba1548aff3",
          "sha1": "2a3db44c4309adca6c0a6580d810d84b3c9f118c",
          "md5": "cceb81926d31c9c264b50b2fad103b49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2511.1-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2511.1-sources.jar",
          "size": 17403533,
          "sha512": "64a4a3b7f5880f30b7169a7da99a2533529c8657256d87aba1798e9e62c25a69528beea73c3cc69c9c5f883da8bc8d92fc9c6a621b2bb190c5c7eaf76c9f53ed",
          "sha256": "e5e3f393b609cd93fdb0abac2395c1262a0ded0e3b07a65549145b8923c9357d",
          "sha1": "6ed29be2b3ad581621155bb560df0d69feee53f9",
          "md5": "2d9c21d10bdaef1dbb2512bffda9aa4b"
        }
      ]
    }
  ]
}
