{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.6.2541.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2541.1.jar",
          "size": 531980,
          "sha512": "5e27a6465a6b755147f101f36e69823f30cbc81ef12084450181f01de9bf25cfd28e74d794b8fc6a309ac6986b57f75fabd617aaf2bd46631f9dead32128b30b",
          "sha256": "10012601d2b603c49873840b3abbe0e221015d409be000e81ff0ab7a79a85eb8",
          "sha1": "c2f192a006ecae29fa66f780f3fcf811ef0d40c6",
          "md5": "696252ce884a8098ab70f30d130bc6fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2541.1.jar",
          "size": 531980,
          "sha512": "5e27a6465a6b755147f101f36e69823f30cbc81ef12084450181f01de9bf25cfd28e74d794b8fc6a309ac6986b57f75fabd617aaf2bd46631f9dead32128b30b",
          "sha256": "10012601d2b603c49873840b3abbe0e221015d409be000e81ff0ab7a79a85eb8",
          "sha1": "c2f192a006ecae29fa66f780f3fcf811ef0d40c6",
          "md5": "696252ce884a8098ab70f30d130bc6fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2541.1-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2541.1-sources.jar",
          "size": 267744,
          "sha512": "eeef2f0294bffc5685f547459c0db2cd985032823c7a7feff1aaf0d50d34cf3bb79e016461055bbc4220eb65a5c77cdb97f794779dec571d7abd7a46e379cd30",
          "sha256": "22bdede882e21b406872e76e816615ff3a8b475ca645c4e179e88bdcf3e199bd",
          "sha1": "e33544cbe1c544856846ea898cc3b22d94399d9d",
          "md5": "333c071a9c1fa813f149f3fcb1ddaf00"
        }
      ]
    }
  ]
}
