{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2513.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.8.jar",
          "size": 690250,
          "sha512": "9eb6bd24ebed75eb356da73874e1ebcfcbd628eba12290b49301577fcb1aa88e0bf5a4d8d99b45774bedb9a6710f5158d0915b66181eda71a18cf1a4c2d26f70",
          "sha256": "869bc4cc159c67323068773f6f2bb7485b38ad4261604cc263edc8b5698f1511",
          "sha1": "41788c71331c5172e80b882d9d18fd2d8d7437e8",
          "md5": "66f1531a729e4bc3b662ac21390e5607"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.8.jar",
          "size": 690250,
          "sha512": "9eb6bd24ebed75eb356da73874e1ebcfcbd628eba12290b49301577fcb1aa88e0bf5a4d8d99b45774bedb9a6710f5158d0915b66181eda71a18cf1a4c2d26f70",
          "sha256": "869bc4cc159c67323068773f6f2bb7485b38ad4261604cc263edc8b5698f1511",
          "sha1": "41788c71331c5172e80b882d9d18fd2d8d7437e8",
          "md5": "66f1531a729e4bc3b662ac21390e5607"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2513.8-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2513.8-sources.jar",
          "size": 251266,
          "sha512": "e42f95fad73f509f8a92a8c52240b7f9c919e8f204a96b68fe88d6be6cf886a2a1b155f79b2e4e1111d7d7b1f02c0dbc0c33f15158454052198ea630a8d3982f",
          "sha256": "c8ef66095b4ac7bca4cc291b9105a430047a08557e89ea0c653087f0e67c6db2",
          "sha1": "6c8d0dfe8580a242335413d9e347e1c31f2f6871",
          "md5": "e08c1297bf59899b56e80db35f9efb6a"
        }
      ]
    }
  ]
}
