{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2515.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2515.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2515.1.jar",
          "size": 522640,
          "sha512": "aad21088717104975a0a65100ccacf202b86ad89810d08835e23888b33233e3a4ec3c9ba6e1e7536336fea638e1bfcb803aea2b8a910552ba9bdf3848c8330fc",
          "sha256": "12e234e7f3ae6b375241d1f4a7085f10fc0bfe6976f417de43ce546155f2417e",
          "sha1": "b0f7c205b772816847e4d73d0f62dec4a56e03e5",
          "md5": "3497fa9891f99fa5615379ab1766a309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2515.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2515.1.jar",
          "size": 522640,
          "sha512": "aad21088717104975a0a65100ccacf202b86ad89810d08835e23888b33233e3a4ec3c9ba6e1e7536336fea638e1bfcb803aea2b8a910552ba9bdf3848c8330fc",
          "sha256": "12e234e7f3ae6b375241d1f4a7085f10fc0bfe6976f417de43ce546155f2417e",
          "sha1": "b0f7c205b772816847e4d73d0f62dec4a56e03e5",
          "md5": "3497fa9891f99fa5615379ab1766a309"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2515.1-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2515.1-sources.jar",
          "size": 253199,
          "sha512": "302b1950893f75b23194bb207a91f02386371e41993d4085e962b64a8a9383a693e872712ba3efc2828b5a4f18d90da6347766dd2d588a3803058d686846656f",
          "sha256": "79f757ad07ef8efffcbbe55bc15134a5368966cbbc2eae59cf10178a7ccb2f25",
          "sha1": "ce825032acd4a2a83ea28cd7a9bb7783d1c896bc",
          "md5": "1205cfa722e3260fd0c95bf96ea10773"
        }
      ]
    }
  ]
}
