{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.7.10.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2504.6.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2504.6.jar",
          "size": 14313510,
          "sha512": "096a742abf852b5b1d1a9e45e1ffdc68d13ee602494b5d2f44e700da0e39a194d559fd7842d5cd37f117e414a5c9fda1d77d43053f3e264235b67950549a70fd",
          "sha256": "2cf8283d3b389d0f4f6eb56cac6959a3002023d8832b86286d647e53f01eaeb9",
          "sha1": "8f28ee382066b1f66f9056571d744768a1afcf8a",
          "md5": "cd03713bc41d6911ac25b44b427ca46e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2504.6.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2504.6.jar",
          "size": 14313510,
          "sha512": "096a742abf852b5b1d1a9e45e1ffdc68d13ee602494b5d2f44e700da0e39a194d559fd7842d5cd37f117e414a5c9fda1d77d43053f3e264235b67950549a70fd",
          "sha256": "2cf8283d3b389d0f4f6eb56cac6959a3002023d8832b86286d647e53f01eaeb9",
          "sha1": "8f28ee382066b1f66f9056571d744768a1afcf8a",
          "md5": "cd03713bc41d6911ac25b44b427ca46e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2504.6-sources.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2504.6-sources.jar",
          "size": 13504883,
          "sha512": "eb8a67e6100d049b1b876055e04d36a68f1d93ff854caea3a7d198feafca5c3fe3d49a1c8b82b33b06a35a223af4e5d06421930f76346b590be111d9c658409b",
          "sha256": "f1b13e09359ab31f6845d44c8ba8c2b36a7bb4c17a6ed4fdb69959ea615c5744",
          "sha1": "6f6f0bf0e2ec68b4d6827f0b2d1b58ef5c4a902e",
          "md5": "db49edbfba4ee56c807a8bb9789d6f77"
        }
      ]
    }
  ]
}
