{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.7.10.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2509.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2509.1.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2509.1.jar",
          "size": 14404780,
          "sha512": "922fe65095786ce686e1c1790c32005fc7d7f1b13ab474a69cc35fc04c36434e0290a7a001c8cb363840edd4e5f5c2ede1e4e44a4adf139911d1dd846ee4c7d2",
          "sha256": "d9c9b759f9f8b66b2595539b940ca885e53f79778fb0805912b8bcc5d1c0b4d6",
          "sha1": "2d7f95151306d5c91d65b85b45ca3613fca342cd",
          "md5": "8a3997717f6dba0aa44b77a5b2ed7752"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2509.1.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2509.1.jar",
          "size": 14404780,
          "sha512": "922fe65095786ce686e1c1790c32005fc7d7f1b13ab474a69cc35fc04c36434e0290a7a001c8cb363840edd4e5f5c2ede1e4e44a4adf139911d1dd846ee4c7d2",
          "sha256": "d9c9b759f9f8b66b2595539b940ca885e53f79778fb0805912b8bcc5d1c0b4d6",
          "sha1": "2d7f95151306d5c91d65b85b45ca3613fca342cd",
          "md5": "8a3997717f6dba0aa44b77a5b2ed7752"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2509.1-sources.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2509.1-sources.jar",
          "size": 13588604,
          "sha512": "b2bbce411b92d6e0c7f11605cca873ec7bf0ef66081056f1a3f729ec68f2243610a6f327cb3b46fcf142075dbd2b6a023219872810999d5f4d753bcd1c718431",
          "sha256": "f9588304fd93cda1dca46e7204bee5a5d0286723b8f0939af0abe990d7b04206",
          "sha1": "a89d7158c53fa212bc52486f6fa86e9e6e8f6432",
          "md5": "f711ef172f3ec31f8b536804959572b4"
        }
      ]
    }
  ]
}
