{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.5-1.8.0.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2517.0.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2517.0.jar",
          "size": 18295347,
          "sha512": "384555e474fab51f36541645254b716a864c1d94929c9274f9cf5b924ed1b970fdf1057ac6c7762046893ff1974c90f79250f4505edfe4a7e410a641f4e39a0e",
          "sha256": "8f75336503855784fdd1d3799c71c1621c1b00647b633ef875213d27f067387d",
          "sha1": "281871f0284e363f01a1b2d8330d041b6cb241d1",
          "md5": "b701698b38b1bd73779496b5351e2eb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2517.0.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2517.0.jar",
          "size": 18295347,
          "sha512": "384555e474fab51f36541645254b716a864c1d94929c9274f9cf5b924ed1b970fdf1057ac6c7762046893ff1974c90f79250f4505edfe4a7e410a641f4e39a0e",
          "sha256": "8f75336503855784fdd1d3799c71c1621c1b00647b633ef875213d27f067387d",
          "sha1": "281871f0284e363f01a1b2d8330d041b6cb241d1",
          "md5": "b701698b38b1bd73779496b5351e2eb6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2517.0-sources.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2517.0-sources.jar",
          "size": 17422497,
          "sha512": "f39fe1aaa701cca83dee1281ae05ca7c8a5d6ef81f21b54769dcbdeac20ee9f217f65e142c24ebb96c833f5115223a352285eea45ddbb41c98f9e6b0cecdc2fa",
          "sha256": "4a4dd00e590063db725f70c54c31df17f1209543e88a40565000473fb6bcd7cf",
          "sha1": "595a6c4180c87acc4544a50f3d32db26ae95a661",
          "md5": "2f47b06dc3c98b20cbe118751f72a026"
        }
      ]
    }
  ]
}
