{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2501.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.10.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.10.jar",
          "size": 372449,
          "sha512": "f331ab160b5b58ad536a2be3a8c6cc3bbb9f015b59487ea355bd3a3b9dcc5e94db89a052709875abb0f06a1258d7b9f0c016f20f6260569800bdce54a3ec76d7",
          "sha256": "73017bf2ed9f51f3f69e58132fb0e3dbab4630e5ff7b3c7eb7fd46fe6ddd2436",
          "sha1": "493a3b3bff937c902400600fce957c646123f5a5",
          "md5": "3dc038b2d5aa0a5d116762cf71c16dbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.10.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.10.jar",
          "size": 372449,
          "sha512": "f331ab160b5b58ad536a2be3a8c6cc3bbb9f015b59487ea355bd3a3b9dcc5e94db89a052709875abb0f06a1258d7b9f0c016f20f6260569800bdce54a3ec76d7",
          "sha256": "73017bf2ed9f51f3f69e58132fb0e3dbab4630e5ff7b3c7eb7fd46fe6ddd2436",
          "sha1": "493a3b3bff937c902400600fce957c646123f5a5",
          "md5": "3dc038b2d5aa0a5d116762cf71c16dbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.10-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.10-sources.jar",
          "size": 197110,
          "sha512": "24447ea6d9b98c1fe54913ece2c4a43fc60b1e9d1928b0b86cde9e0806a63358f3ea1083a8be4caf09e05ab7a96b4aacd516ad542632b9ca4725346a8c956662",
          "sha256": "806bcb57965c30f9044b9494fc7788eda53e36044aadc200dd5d24009a383509",
          "sha1": "fae50e344c18ec998a59363d470b1a2fdf851414",
          "md5": "aa24b9800c4decec3d4e71af4d628a83"
        }
      ]
    }
  ]
}
