{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.3.jar",
          "size": 508774,
          "sha512": "f19e9f7d35b39435bafa129aa4018c9eafcd92f11a9adb1224340590b29edc6e4d300ef2c1efa39903ef0064ee0718e9649398103fd4c47f22028895db4d9d2c",
          "sha256": "28305fab9c15200cf8b87f342ecb56ac387599ba84b82f19c5db428099aa6f8a",
          "sha1": "6e14e0a1387373f5b01e8fac9ff4329b135baff0",
          "md5": "5885245b24fbf2699fa2f1003d7a317c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.3.jar",
          "size": 508774,
          "sha512": "f19e9f7d35b39435bafa129aa4018c9eafcd92f11a9adb1224340590b29edc6e4d300ef2c1efa39903ef0064ee0718e9649398103fd4c47f22028895db4d9d2c",
          "sha256": "28305fab9c15200cf8b87f342ecb56ac387599ba84b82f19c5db428099aa6f8a",
          "sha1": "6e14e0a1387373f5b01e8fac9ff4329b135baff0",
          "md5": "5885245b24fbf2699fa2f1003d7a317c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.3-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.3-sources.jar",
          "size": 253987,
          "sha512": "41287b9933c45c64dd3384dd13a3463e386c01001bc138bdfbcb5110e47abffaf35743413f5736f66f7e140d895e8f166bb7a32177469d7af1515e534152cea0",
          "sha256": "3ba55f8f8ca5c24002affca97304397fe450478fd17d265386c782ba288c0185",
          "sha1": "7b728c30156dcb8c245c963ee625e94c71bc18c9",
          "md5": "cba8dd90c764fc198cf6e4a625024b6b"
        }
      ]
    }
  ]
}
