{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.8-1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.8-2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.8-1.8.3.jar",
          "url": "legacy-forge-1.21.8-1.8.3.jar",
          "size": 19956987,
          "sha512": "9addfb1700855000a11c13f8c311d3d7b0e42cec4804877c558e1b591af61321318d89d3f131ad1065394b8278a0e09b3a66f7182469624f28a57b67eab2d3b6",
          "sha256": "ce248984c4259fefbf0688570b91f7b0adb6d010ca70a60f9c44b6c9c1469db8",
          "sha1": "d4263c4b036b6d90e746832641579fe0424bf005",
          "md5": "63937b01fc96e405a5ff79c0a30b3098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.8-2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.8-1.8.3.jar",
          "url": "legacy-forge-1.21.8-1.8.3.jar",
          "size": 19956987,
          "sha512": "9addfb1700855000a11c13f8c311d3d7b0e42cec4804877c558e1b591af61321318d89d3f131ad1065394b8278a0e09b3a66f7182469624f28a57b67eab2d3b6",
          "sha256": "ce248984c4259fefbf0688570b91f7b0adb6d010ca70a60f9c44b6c9c1469db8",
          "sha1": "d4263c4b036b6d90e746832641579fe0424bf005",
          "md5": "63937b01fc96e405a5ff79c0a30b3098"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.8-1.8.3-sources.jar",
          "url": "legacy-forge-1.21.8-1.8.3-sources.jar",
          "size": 19048912,
          "sha512": "e5b18299aac8f5450227eb2e6abcfa62da0a18279db3a8122cad4cea413b47894481bf06fb77e689e295446a2d191aa4e4f4b5312e938c12fec5a6d35ced0fdc",
          "sha256": "49146f2f986687211956c1ec335298a3d16996370f3f7e9836e1c617219c254b",
          "sha1": "2d80126f2d4b58156276d3cfe647631e95c148fc",
          "md5": "da5faa1625ccbecbfbd363370c8d61d7"
        }
      ]
    }
  ]
}
