{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.jar",
          "size": 536782,
          "sha512": "f49abb4659dd310bd768cf11536fc212048105838ca57e3530d440619b5d5e1e5a99bfbba8ffe3f8feae591bd33ebce6a6541a5d3b029f23265a82e45b09bdaa",
          "sha256": "3ed1157d5907931ba905ca0d8e9abe65789fec01092ef1fdf6a5a13d1375904c",
          "sha1": "a1820e47129106d44b0f6017e05e127ac4570c73",
          "md5": "1bad7787bbe9569f0ee8c8e5ad02cd95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.jar",
          "size": 536782,
          "sha512": "f49abb4659dd310bd768cf11536fc212048105838ca57e3530d440619b5d5e1e5a99bfbba8ffe3f8feae591bd33ebce6a6541a5d3b029f23265a82e45b09bdaa",
          "sha256": "3ed1157d5907931ba905ca0d8e9abe65789fec01092ef1fdf6a5a13d1375904c",
          "sha1": "a1820e47129106d44b0f6017e05e127ac4570c73",
          "md5": "1bad7787bbe9569f0ee8c8e5ad02cd95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6-sources.jar",
          "size": 259012,
          "sha512": "d7f12b83da756c2222ac68a3cd917abd18554bd62b04955df33950b072ac5a0e55777a9c31d3d1dee911609c4b282fb97c9a2a20a1bd5f513b78381f4646400d",
          "sha256": "45bdeadcb9ca5fa7eb9b3ba2e92e133b3e4f46f0a4df4f6739beced98a843144",
          "sha1": "5fbb3fa1d4a53936f8c2e13b866424622737215a",
          "md5": "d4ee551536dc608177afe1a858b2d5a6"
        }
      ]
    }
  ]
}
