{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.9.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.9.jar",
          "size": 382119,
          "sha512": "10ddeae857dce451f30aa685c6bca40071001cb419e2f566843efbe0f03aedb86b4fb9820aa8fe7fef1089c39f19f2557ce9b2aa42feb70edb889dbf69e3aebe",
          "sha256": "07f41aaec4d76ca92c15f922692ebaf54e27254f9e23124b16c51c4afbbd6f27",
          "sha1": "4d5099b505c0ecb463daa4bd4141984e9b58acfa",
          "md5": "befba4f15337a2f9701cb30283926ac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.9.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.9.jar",
          "size": 382119,
          "sha512": "10ddeae857dce451f30aa685c6bca40071001cb419e2f566843efbe0f03aedb86b4fb9820aa8fe7fef1089c39f19f2557ce9b2aa42feb70edb889dbf69e3aebe",
          "sha256": "07f41aaec4d76ca92c15f922692ebaf54e27254f9e23124b16c51c4afbbd6f27",
          "sha1": "4d5099b505c0ecb463daa4bd4141984e9b58acfa",
          "md5": "befba4f15337a2f9701cb30283926ac5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.9-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.9-sources.jar",
          "size": 198522,
          "sha512": "d73ecb12b9ce6015d4cfa492dea1b2496f56d6183135064cb84012d64a2cf56cabcdccbbaa1bd2a6f5e99021554ac0e34791b4dbb9d3316f483ad8a42f48565f",
          "sha256": "b3af305a8b76082626e2cfce5b4df9433226b5904234d9673f6a967f2a446deb",
          "sha1": "2a8f8cca7d9d01597f664a51d2952ccd197c9316",
          "md5": "d388bf5b9d5169961e8239f036b0bf27"
        }
      ]
    }
  ]
}
