{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.3.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.3.jar",
          "size": 18265776,
          "sha512": "b29397e91e3a2f436e5102e85d206da342651c14b6ee1a795b3936f16099c728c384822d951d39430e1c91fae9cc270794102ca8ea20ec9c85faf089e8dabd3e",
          "sha256": "4ff4879077725eb5b1940cacca258c98b1c3603e4ace00ee9f7c236352d0b0da",
          "sha1": "4c86adc1c9a2b074759436dfc60c2feed448c954",
          "md5": "bb0d94a2a2833bff6f1ce10965c3cc6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.3.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.3.jar",
          "size": 18265776,
          "sha512": "b29397e91e3a2f436e5102e85d206da342651c14b6ee1a795b3936f16099c728c384822d951d39430e1c91fae9cc270794102ca8ea20ec9c85faf089e8dabd3e",
          "sha256": "4ff4879077725eb5b1940cacca258c98b1c3603e4ace00ee9f7c236352d0b0da",
          "sha1": "4c86adc1c9a2b074759436dfc60c2feed448c954",
          "md5": "bb0d94a2a2833bff6f1ce10965c3cc6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.3-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.3-sources.jar",
          "size": 17422017,
          "sha512": "0d4e8cccb8e627e5df8e4c81ff7f8be8789426f31cb663f06cadaa36e9c1e8213c9a377232351688d48e2e606842edc3eacd097c1a686b3d9924ca1f780043fb",
          "sha256": "33b8faf6bef8bfcbe5621e8d583e1bd4cfb11bc8001fea6598ac5356b2064175",
          "sha1": "d5fd747a95b1753ac0f1af06e63eb228684463cf",
          "md5": "4091d2d6d944331f508f4d85eaf88462"
        }
      ]
    }
  ]
}
