{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2509.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2509.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2509.0.jar",
          "size": 693031,
          "sha512": "9a112321a308f94e60cbb74c9f1dda5b64310ed2860dd01597a284d6f14bc20d5b40b4d78d2419f04fb6aa0a0614a742c2a4446305af3de2d9e00af11dda4ad5",
          "sha256": "1cbfaa3904a661ec215daa5eb790e7bb34188e461975a0989c151a14b6f49d0b",
          "sha1": "36525c932a4c2c9caefad83bb87b070dd8555b11",
          "md5": "7d169649cee4e02cff22eba98987879d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2509.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2509.0.jar",
          "size": 693031,
          "sha512": "9a112321a308f94e60cbb74c9f1dda5b64310ed2860dd01597a284d6f14bc20d5b40b4d78d2419f04fb6aa0a0614a742c2a4446305af3de2d9e00af11dda4ad5",
          "sha256": "1cbfaa3904a661ec215daa5eb790e7bb34188e461975a0989c151a14b6f49d0b",
          "sha1": "36525c932a4c2c9caefad83bb87b070dd8555b11",
          "md5": "7d169649cee4e02cff22eba98987879d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2509.0-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2509.0-sources.jar",
          "size": 248236,
          "sha512": "a0763f3597cec38dc61bacbb35930835781b68dac2224b329243615a4129738a0fe378d86cfb8c18bbc381af373247056190d6e8a1b5d1b49c9e1ab5957242fd",
          "sha256": "e64a771edab21b4c993d345f53397f5bebf75e1a2be984d4b699e5a81d6800c7",
          "sha1": "41f997f6326fa31632a35501e29a77f99c337442",
          "md5": "4478bbe039728ec11959601626f82d37"
        }
      ]
    }
  ]
}
