{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.10-2.2.6.2541.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.6.2541.3.jar",
          "url": "factory_api-forge-1.21.10-2.2.6.2541.3.jar",
          "size": 719650,
          "sha512": "6a984032dd9c1b2071f5864efa89a37ecc995faf9f07965bf8287cab22344b8f6c3da1f1748de7bd88aec94c65289ef32bbc4c1adfee9aa271b17375c64c7bc7",
          "sha256": "bfc4dac4394b974fa1f0e880f60978f6d2c32fba0d20e366d9bf8bc500f95d66",
          "sha1": "51925860fba26b2b98efcc8ccfe5b0d9b6d955d7",
          "md5": "4860d16a1aeaec8a86c5d258fc8711fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.6.2541.3.jar",
          "url": "factory_api-forge-1.21.10-2.2.6.2541.3.jar",
          "size": 719650,
          "sha512": "6a984032dd9c1b2071f5864efa89a37ecc995faf9f07965bf8287cab22344b8f6c3da1f1748de7bd88aec94c65289ef32bbc4c1adfee9aa271b17375c64c7bc7",
          "sha256": "bfc4dac4394b974fa1f0e880f60978f6d2c32fba0d20e366d9bf8bc500f95d66",
          "sha1": "51925860fba26b2b98efcc8ccfe5b0d9b6d955d7",
          "md5": "4860d16a1aeaec8a86c5d258fc8711fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.6.2541.3-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.6.2541.3-sources.jar",
          "size": 267865,
          "sha512": "a63ee6d80d802fb21418610a339ebc90fc5bdf8438ce1ba7e8141b634e7147c35d8900b7ee44e25bbad6ce6dcba3bb647e3a82a373bdb3caffdccfac8a09db98",
          "sha256": "40bea7b3971f8a9042ed4d288bd4a3986300fbdefca055e43d7339cbf83d4d75",
          "sha1": "a976c4dbc965a44db603acab647527a777818fb7",
          "md5": "3d32bf4f0e75d37eff16cb9ae47bb29b"
        }
      ]
    }
  ]
}
