{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.7.10.2501.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2501.1.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2501.1.jar",
          "size": 11927065,
          "sha512": "f7768ed1b627f4a970daaa7363716835b5e8f0f6fe5e2358c81f3ff1ea197922bb485ce11c2ca7025409c1cd52e068ae0c7b890ee787372b7774164ffd50fc01",
          "sha256": "7371ea7586a59280f341ce4eacceb7a09d4f00bf78ad353d4680383272e400d5",
          "sha1": "ed42446c4bfadaab953bde9c1f27b6b59d29188a",
          "md5": "f456fb6c59e9882e8f11e888fb734cea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2501.1.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2501.1.jar",
          "size": 11927065,
          "sha512": "f7768ed1b627f4a970daaa7363716835b5e8f0f6fe5e2358c81f3ff1ea197922bb485ce11c2ca7025409c1cd52e068ae0c7b890ee787372b7774164ffd50fc01",
          "sha256": "7371ea7586a59280f341ce4eacceb7a09d4f00bf78ad353d4680383272e400d5",
          "sha1": "ed42446c4bfadaab953bde9c1f27b6b59d29188a",
          "md5": "f456fb6c59e9882e8f11e888fb734cea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2501.1-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2501.1-sources.jar",
          "size": 11127719,
          "sha512": "aa5e6270b39a4f5f3978c9d5770b2a2c19f92aabadcfac347661b4648ec7f8297bc9f9eff8743157a60b90d31ed946febfdc063be0802facce22681078579492",
          "sha256": "51ce423e81962b8033c02c6fce1bdc4e28171a1a145a6cbf0c294bc037a22657",
          "sha1": "3549986b023bbb90fc1c5ae398e6b826d4887059",
          "md5": "23773bfa969db14b48310c4873141884"
        }
      ]
    }
  ]
}
