{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2504.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.2.jar",
          "size": 465070,
          "sha512": "be1425ec006269632c8199eab228bb4d98993a0a9c65bef0b6f1079d28f587c3f32ef7057bed8b3709c8dbfe07e4405b87f59551f072f942798f21ad767bc520",
          "sha256": "e849593927110edc060f4aec846ed503a83118a236941afd6b855638a6262f3a",
          "sha1": "124f29e4226276742fcd2ccbf97c2b261cdfdbf2",
          "md5": "78830faf1e11874d751c679c93fed792"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.2.jar",
          "size": 465070,
          "sha512": "be1425ec006269632c8199eab228bb4d98993a0a9c65bef0b6f1079d28f587c3f32ef7057bed8b3709c8dbfe07e4405b87f59551f072f942798f21ad767bc520",
          "sha256": "e849593927110edc060f4aec846ed503a83118a236941afd6b855638a6262f3a",
          "sha1": "124f29e4226276742fcd2ccbf97c2b261cdfdbf2",
          "md5": "78830faf1e11874d751c679c93fed792"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2504.2-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2504.2-sources.jar",
          "size": 231540,
          "sha512": "561f5af8e8a8386aec5026454889ef2edc11f2e736945e56c271fd0a9bb192cabff5b1cc69aabede69fa39001c88c00c5336123f0da5548c7797b47c42d8aad9",
          "sha256": "3d87312f7b8125f6c75e23851b11b14922d68a4197d9a622661f687df53571a7",
          "sha1": "a9b3073f79d7f1a5b6e28d439dd6fcb3e15d7447",
          "md5": "cad23c38941360f41de95b96fdd7e40c"
        }
      ]
    }
  ]
}
