{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.3.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2515.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2515.0.jar",
          "size": 551632,
          "sha512": "3bf7e5ec19cac1cd776ffcbc0c90bd55aa7faea9f41728116c07edc4fcc6195cbdb7b718904aa75db7e24e899b46fbfb4e86d4eff9b728797a850c38f7d30815",
          "sha256": "62d88a4d067ac246dac4d849e561c467f739677017933f8b7da08461d28f5393",
          "sha1": "f9cecdb5b9ad4b63b17165e752833587d3e959d7",
          "md5": "2f78ac6a83929e00f5ba6f7ae8a798bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2515.0.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2515.0.jar",
          "size": 551632,
          "sha512": "3bf7e5ec19cac1cd776ffcbc0c90bd55aa7faea9f41728116c07edc4fcc6195cbdb7b718904aa75db7e24e899b46fbfb4e86d4eff9b728797a850c38f7d30815",
          "sha256": "62d88a4d067ac246dac4d849e561c467f739677017933f8b7da08461d28f5393",
          "sha1": "f9cecdb5b9ad4b63b17165e752833587d3e959d7",
          "md5": "2f78ac6a83929e00f5ba6f7ae8a798bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2515.0-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2515.0-sources.jar",
          "size": 251205,
          "sha512": "9fc4e4a33348534f7ad26baaa413a4a39aaae3d33c068ef9ef2516be2d517d05b1825f3aea62c2242fe05b365d86e7ca479961656f1d8d7d3626aa81eb27bcab",
          "sha256": "4cd76408305a8b9e8f902a4b7303ff03c7e13e18fa9276e7f4e6271a6d43d99b",
          "sha1": "82fc2c120649cc3140ee8a4d26034b41f1250bd9",
          "md5": "0d6c732770e5d0888f6b60a6df8595e9"
        }
      ]
    }
  ]
}
