{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.6.2547.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2547.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2547.0.jar",
          "size": 541647,
          "sha512": "2ec79d044b0ad48a75c5054df45ef3702ab2ec002aa0957d06036b2e1d1eb175446c0f4f14fd280dc66fcd7d9b09a8f5457aa4c36721040239cd97db5febb3d8",
          "sha256": "8e4efe6f5c9a41e8fef79f422d825aba22b036a4f2649fbf7ecb4b6c9bda49aa",
          "sha1": "afbcb28fd3c7be4ca5d149d90ff48bbf450fc2e8",
          "md5": "bc7395d3bb406d0394f639055d56a8bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2547.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2547.0.jar",
          "size": 541647,
          "sha512": "2ec79d044b0ad48a75c5054df45ef3702ab2ec002aa0957d06036b2e1d1eb175446c0f4f14fd280dc66fcd7d9b09a8f5457aa4c36721040239cd97db5febb3d8",
          "sha256": "8e4efe6f5c9a41e8fef79f422d825aba22b036a4f2649fbf7ecb4b6c9bda49aa",
          "sha1": "afbcb28fd3c7be4ca5d149d90ff48bbf450fc2e8",
          "md5": "bc7395d3bb406d0394f639055d56a8bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.6.2547.0-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.6.2547.0-sources.jar",
          "size": 269301,
          "sha512": "7ea25c88f9e2aaebfaede01425297055c68ace0b80b88ee359998cd8d5f7474ea01e0eeb7c8d584ecb6fde665cf6e8b09d72122f7177c8d2f40e0d3f65932709",
          "sha256": "7e59fac70684e3f4da68f36c188d5010ddbaa333fcbd099ae76c1db27c578fa1",
          "sha1": "041bef377e78963d332bc05a62a4f864b3b8185a",
          "md5": "971090d164a640ee250be8d460607caa"
        }
      ]
    }
  ]
}
