{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "size": 523488,
          "sha512": "ded1688e4d9c6f55a0f9e42dc0dc505aa8311638aaf86a0d524eeb1faf7efd7871b9f42c2cbd1c69df257e34a4f3c77bca0dd6e976a486a6127ba5838e56b63f",
          "sha256": "392d98244d2965bf28859ccff504909328e4bca6abf10872361f05cf0b60200a",
          "sha1": "89906af5ff586bcbd218cc12fdf7f9c0aa355457",
          "md5": "9e28f2058d1772df7ec71e8676b7d546"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "size": 523488,
          "sha512": "ded1688e4d9c6f55a0f9e42dc0dc505aa8311638aaf86a0d524eeb1faf7efd7871b9f42c2cbd1c69df257e34a4f3c77bca0dd6e976a486a6127ba5838e56b63f",
          "sha256": "392d98244d2965bf28859ccff504909328e4bca6abf10872361f05cf0b60200a",
          "sha1": "89906af5ff586bcbd218cc12fdf7f9c0aa355457",
          "md5": "9e28f2058d1772df7ec71e8676b7d546"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.2-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.2-sources.jar",
          "size": 252865,
          "sha512": "941d5ae33ca6bf45f9407c32037c67616f5353538b01416b99d7efb2c590ffa596802d0f9a867ca2701bccaadb31866d02e14f31a4abb68bbf5bd523b9f5cbb7",
          "sha256": "32abf76b1eb6ada6c7e63787e5202241bf5e162eb0356fdaf40b6340fe98f850",
          "sha1": "f150755c3349adccd1862726075d7e7c050e4f8e",
          "md5": "65ef772bc144bdfb82f1bc665c63a9e3"
        }
      ]
    }
  ]
}
