{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "size": 523369,
          "sha512": "20580e049d3976b4c314151a925af84be1a7bc9a035e1e23fc4c27761b5a102a92eb0aae66310b52d4631d7c960eabfff9434aa589c6d32b161fecdeaa2039cc",
          "sha256": "deeacc09abebd495200e7a159d0cd69fa3327b91c69bd762c2c1e4a1ffdb36b9",
          "sha1": "6892a54e4c862cc5d2a41df5a403ae57f6754a70",
          "md5": "9429e024495b67d8aa01e7f1500df0ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.2.jar",
          "size": 523369,
          "sha512": "20580e049d3976b4c314151a925af84be1a7bc9a035e1e23fc4c27761b5a102a92eb0aae66310b52d4631d7c960eabfff9434aa589c6d32b161fecdeaa2039cc",
          "sha256": "deeacc09abebd495200e7a159d0cd69fa3327b91c69bd762c2c1e4a1ffdb36b9",
          "sha1": "6892a54e4c862cc5d2a41df5a403ae57f6754a70",
          "md5": "9429e024495b67d8aa01e7f1500df0ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.2-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.2-sources.jar",
          "size": 75227,
          "sha512": "34d88278098c16c8668573e247b22b8232d1bb0619c5623033fe6fe98a4cda72ba2189ed4965cbe94a195e88c5bcd069811fd814e663c074e84cf823febe58b9",
          "sha256": "bccd371015148fff95c1bd5016e3c9282eca269e7fac46d18e47fdbdbf595a71",
          "sha1": "e3981e64219b8a3cb87fd58f3b7e61bfb39ad8d9",
          "md5": "47e5540a536217fecc7154dc65a2c3a5"
        }
      ]
    }
  ]
}
