{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.5.jar",
          "size": 481265,
          "sha512": "2fd090151337cb7c1a8aade90bef0b0bcbc20a25e74431a75e75d362ee7963c38dd4f50f33a493d6336c23e23ed0e590002f8efb4b93eb053e9e9a7b051af863",
          "sha256": "b4fddc8173764001c10ef8d005596fea9ad0901e0db78422fd1c6abff6d4acd7",
          "sha1": "630e571e2bd52b2cf773f878ddf0a44ecda3b081",
          "md5": "c98f729c9d613ec85222c05a28bfbcd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.5.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.5.jar",
          "size": 481265,
          "sha512": "2fd090151337cb7c1a8aade90bef0b0bcbc20a25e74431a75e75d362ee7963c38dd4f50f33a493d6336c23e23ed0e590002f8efb4b93eb053e9e9a7b051af863",
          "sha256": "b4fddc8173764001c10ef8d005596fea9ad0901e0db78422fd1c6abff6d4acd7",
          "sha1": "630e571e2bd52b2cf773f878ddf0a44ecda3b081",
          "md5": "c98f729c9d613ec85222c05a28bfbcd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.5-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.5-sources.jar",
          "size": 246212,
          "sha512": "efc4461c0c4b6dfa5529d38474929664b38ccc2569e599736497846a0bd9dad61e4de029ea287adb8dcfef33d2aa377cef2a3572502c014332569750a71b81a0",
          "sha256": "2830327a8ddc220d3a27db2b3840800ee5ed5f56d938d914c3f9a10ef1fdb5ee",
          "sha1": "493455bf4df7ccacbe2f50d97dfff8a977883bfd",
          "md5": "d972686ac2f02dcbb581ddba95264169"
        }
      ]
    }
  ]
}
