{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.7-1.8.2.2530.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2530.1.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2530.1.jar",
          "size": 19980320,
          "sha512": "54e8ba1336bcfa668ffc9acc0486ed2b70fc1f6409100970c6df3d228fc5ee403332c4556660798acfff151e7958fe907a04b99a9bab83424a6cadaec10d4eab",
          "sha256": "154e2fc380cc9ce2541d8ec84a328f1ef7698935bd7828bf57ff090b45022420",
          "sha1": "acfaa767cd917e8221d6389fc9bd45e1f99ea746",
          "md5": "4ecb6b0d6908b85932211fd43eaa9335"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2530.1.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2530.1.jar",
          "size": 19980320,
          "sha512": "54e8ba1336bcfa668ffc9acc0486ed2b70fc1f6409100970c6df3d228fc5ee403332c4556660798acfff151e7958fe907a04b99a9bab83424a6cadaec10d4eab",
          "sha256": "154e2fc380cc9ce2541d8ec84a328f1ef7698935bd7828bf57ff090b45022420",
          "sha1": "acfaa767cd917e8221d6389fc9bd45e1f99ea746",
          "md5": "4ecb6b0d6908b85932211fd43eaa9335"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2530.1-sources.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2530.1-sources.jar",
          "size": 19050822,
          "sha512": "f2625d8ea0552be83e2eac535a1201f14b7bff506ed2460ce27f227ac5eafc63356e1d37d1c719eb2a9e104fb4cfed80260051d4393635a9fa67499ee761de2e",
          "sha256": "36e48ab7f32e5acebabfb9de00352b9c3b5393c853da2357cda4742e7b0cbe0d",
          "sha1": "579c0363a87541d773e42c9838bcb0e3212957a2",
          "md5": "e2cf309d205390fa2e4a08606e52c6b3"
        }
      ]
    }
  ]
}
