{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.8.0.2512.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2512.4.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2512.4.jar",
          "size": 18286389,
          "sha512": "2147e90837e0a7675358d62056368fb793618f1479b5f23e047afe2b4f8323004e9d5a35fe41101e0fbec250a1d3b7b336a3e1dedcb758518ce19f2e7ef5886a",
          "sha256": "10aaf21ecdc9ae0f5bab7e6fc99d43c3ca4ada7a3e90bb94306c0b7146c43781",
          "sha1": "02a6105a47d86e4c31d33744627eb3e397884c88",
          "md5": "ff694914a30071a4e3d62141a327ca2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2512.4.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2512.4.jar",
          "size": 18286389,
          "sha512": "2147e90837e0a7675358d62056368fb793618f1479b5f23e047afe2b4f8323004e9d5a35fe41101e0fbec250a1d3b7b336a3e1dedcb758518ce19f2e7ef5886a",
          "sha256": "10aaf21ecdc9ae0f5bab7e6fc99d43c3ca4ada7a3e90bb94306c0b7146c43781",
          "sha1": "02a6105a47d86e4c31d33744627eb3e397884c88",
          "md5": "ff694914a30071a4e3d62141a327ca2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2512.4-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2512.4-sources.jar",
          "size": 17426078,
          "sha512": "8b814437e06e6748099f91f8f711fd70c86271653f26e0ea09a931671ba4766c077aa7e9759dc82a86337a970603e6eaa7c1c13191a247081d5a0d2231a090a7",
          "sha256": "962480a0d7d3e2e0d85ddb3826d476b2778bc869df1a127b3fa0ce540258ed2c",
          "sha1": "788900499cd49f7729981a6ccef37ff76b1ce51d",
          "md5": "b88ecc8811ee56c3c78c4cf6c06ee9d4"
        }
      ]
    }
  ]
}
