{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.1-1.1.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.1-1.1.2516.1.jar",
          "url": "betterfurnacesreforged-forge-1.21.1-1.1.2516.1.jar",
          "size": 643943,
          "sha512": "c09544ccde05450b2734604b0d54f0582611d1cfbc62de15fe18590d86db614cb625f8afce374e785e504e988da235afcdffd15529cc031113c5c5da980e4300",
          "sha256": "f80f1d19fe9a9ab0c1f4d3a0912d8b22531d89d73956143b6fa10d101c20ac30",
          "sha1": "b6d9714d3d0c55afc3e1fb4388cc476b5db08966",
          "md5": "1b29d8ae9bba7874a750694dcf171e2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.1-1.1.2516.1.jar",
          "url": "betterfurnacesreforged-forge-1.21.1-1.1.2516.1.jar",
          "size": 643943,
          "sha512": "c09544ccde05450b2734604b0d54f0582611d1cfbc62de15fe18590d86db614cb625f8afce374e785e504e988da235afcdffd15529cc031113c5c5da980e4300",
          "sha256": "f80f1d19fe9a9ab0c1f4d3a0912d8b22531d89d73956143b6fa10d101c20ac30",
          "sha1": "b6d9714d3d0c55afc3e1fb4388cc476b5db08966",
          "md5": "1b29d8ae9bba7874a750694dcf171e2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.1-1.1.2516.1-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.1-1.1.2516.1-sources.jar",
          "size": 585450,
          "sha512": "7782ac96b7bb052bdb2a252a365af8e8865ec6bd83f373e429c98006b515ebc437acf54e14db1652e5f445def0c0c37ccdbdacc402ed2036baab9fd18b228116",
          "sha256": "18adc1261d5a247a3862360ff2fb0a9e976d088351dbc7a9d626b298bb81db03",
          "sha1": "f748246ee763cf011f7a9c09c111cd28187193fb",
          "md5": "f4d56778a2338b632b1b0d00b7d11081"
        }
      ]
    }
  ]
}
