{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.2501.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2501.3.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2501.3.jar",
          "size": 387695,
          "sha512": "209647b5b73f108c4b9f85b43a918130a0ed87cf7645ef8fcf5867b488c19ded18546ff57670da893b351524acee16dc55db5e22c4d6854faa947efd46c5ddb6",
          "sha256": "5fa64834f824d7c4d221bd6d28bc89debb9027e9eb6f5cd7e797e209975b3d9f",
          "sha1": "4a42d3d776590ffd4a39b13e01bfdf4038889475",
          "md5": "f647db5f9242aba39bb338fa32f3936f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2501.3.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2501.3.jar",
          "size": 387695,
          "sha512": "209647b5b73f108c4b9f85b43a918130a0ed87cf7645ef8fcf5867b488c19ded18546ff57670da893b351524acee16dc55db5e22c4d6854faa947efd46c5ddb6",
          "sha256": "5fa64834f824d7c4d221bd6d28bc89debb9027e9eb6f5cd7e797e209975b3d9f",
          "sha1": "4a42d3d776590ffd4a39b13e01bfdf4038889475",
          "md5": "f647db5f9242aba39bb338fa32f3936f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2501.3-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2501.3-sources.jar",
          "size": 193595,
          "sha512": "980a484abc7c85ac519cde1a5f795ad065bcaf965a9416d2844bb9618c85fe87f16688adb01e922488f565b084a6e44d8f935386c2d6c2636ca8d986738e3150",
          "sha256": "5bd161fda9e06d1f1e45a03fa7086d5a956dde2a0f1eaaf84b2859b6de35618d",
          "sha1": "5041d690be70f43c42bede656ad245678d08dcb3",
          "md5": "418013f3842cbb702208cd1095b878be"
        }
      ]
    }
  ]
}
