{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2507.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.0.jar",
          "size": 488223,
          "sha512": "d6ba09b98dec300e0f21187470746606e7907b080f36c89b2d5f58a268268015fe14ad500055f7423af9abdd51a90dafb0d48332d3a7461bb6446f82580f3de8",
          "sha256": "d73794c2ddcf045d3363d4f77ef42e641c67e14ba03f02f517bf2771ae099f2f",
          "sha1": "67899690879947830846c8666b308a143239967d",
          "md5": "f3c78417e2e710b49a7d7240eb41c2fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.0.jar",
          "size": 488223,
          "sha512": "d6ba09b98dec300e0f21187470746606e7907b080f36c89b2d5f58a268268015fe14ad500055f7423af9abdd51a90dafb0d48332d3a7461bb6446f82580f3de8",
          "sha256": "d73794c2ddcf045d3363d4f77ef42e641c67e14ba03f02f517bf2771ae099f2f",
          "sha1": "67899690879947830846c8666b308a143239967d",
          "md5": "f3c78417e2e710b49a7d7240eb41c2fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.0-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.0-sources.jar",
          "size": 241283,
          "sha512": "9f6ed742b4863736e00c796f67c871e3d2073b332aeee52152734ef48c6ea695f287eb5f8b32388b88420b510c24520836ade3b16a5baeec485423cd8b6355ad",
          "sha256": "249de887b89c800b9fcaa479fc509271ced6acca93fba7b1d44c659cea9f183c",
          "sha1": "c4c6c68a5d46c57d4f7df0f3a3e207f8da553a13",
          "md5": "0adb5f5e25a44d79bc6196cc921fe117"
        }
      ]
    }
  ]
}
