{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.11.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.11.jar",
          "size": 374334,
          "sha512": "06f897034e7a028b1f7deb254fdaf265488a12ddc59ac2cb18ac6e3fe2840818a7b4ae519e678e9f2d7ae80f4876a1f5cca597a9ef55bb5f7daace7eeb919269",
          "sha256": "9aa95ceb348c8785e5d66f4ecd1b9461e1895e1797951e90817f7ab0706e3476",
          "sha1": "018c9d6ba9e72add371d5c8f39e945916f295540",
          "md5": "73ddf070148c5fa183e89ab64510a65e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.11.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.11.jar",
          "size": 374334,
          "sha512": "06f897034e7a028b1f7deb254fdaf265488a12ddc59ac2cb18ac6e3fe2840818a7b4ae519e678e9f2d7ae80f4876a1f5cca597a9ef55bb5f7daace7eeb919269",
          "sha256": "9aa95ceb348c8785e5d66f4ecd1b9461e1895e1797951e90817f7ab0706e3476",
          "sha1": "018c9d6ba9e72add371d5c8f39e945916f295540",
          "md5": "73ddf070148c5fa183e89ab64510a65e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.11-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.11-sources.jar",
          "size": 196970,
          "sha512": "c0667ab48259d551974903458bf3ea32eba7d19152a96ba3606e63c4826ce1b5859789219f14ea205a32f71625a1672ec98159ed52373b780adec258f4e280ba",
          "sha256": "4486a1cbfcf0ee630d6d1c70ff1d7fb304581f0904cac784142bfbad6fc99d0c",
          "sha1": "11a5e1c020a4c3445bad99584fb7e125203ebb2d",
          "md5": "7a9141ed09288dc31f426051547f2926"
        }
      ]
    }
  ]
}
