{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2510.5.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2510.5.jar",
          "size": 704796,
          "sha512": "835eac0faf5319a210d3b5ff749e53417233abd8dd7e7a25d56ab3f35705daa09a8810b35053668b5e404744b7f29d9e7d615d965002ba4fe6461cf1788aa0ac",
          "sha256": "a08c3be507a85f7b074f8af650ba89b8261c8ac3b3736d381df9857fcd4b0f71",
          "sha1": "c00b9a31c617ed599a25e9a4421464ad37c49c22",
          "md5": "f57871fd716b6a63dee86c32ae6319ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2510.5.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2510.5.jar",
          "size": 704796,
          "sha512": "835eac0faf5319a210d3b5ff749e53417233abd8dd7e7a25d56ab3f35705daa09a8810b35053668b5e404744b7f29d9e7d615d965002ba4fe6461cf1788aa0ac",
          "sha256": "a08c3be507a85f7b074f8af650ba89b8261c8ac3b3736d381df9857fcd4b0f71",
          "sha1": "c00b9a31c617ed599a25e9a4421464ad37c49c22",
          "md5": "f57871fd716b6a63dee86c32ae6319ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2510.5-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2510.5-sources.jar",
          "size": 252729,
          "sha512": "8d2ac6f9ecf10c7ab86b1bab000cc0401b88151967355ac8d7805ee2435ee5ab1783e0c0e0cc6c6499029c402a38cab5b50be37a6386061bc4bb6fa5f8943137",
          "sha256": "5451df3d8db80b77498e6a9600f0918c27c8ec53ede82f57598323555cbb6ea2",
          "sha1": "b57fabf1e900a2d98dcea55ba755604de4029b06",
          "md5": "ac01636253cee675518389805ac90a70"
        }
      ]
    }
  ]
}
