{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.5-1.8.0.2518.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2518.4.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2518.4.jar",
          "size": 19699542,
          "sha512": "7ef0daa3df26f85c76dff55988e5ca2497907c3cfd58e91a37a9ff774f0c59846aaa7ca640b6e7a315d523944663242f63c517d09d0eb5ba3c06bc95ac496007",
          "sha256": "bbec99f3c9cda074a1261b19d24692cd97f2ac16c2ef247f26642a076d30e8d4",
          "sha1": "844dc145ff8d5a633b3376a2ef01bec39b7fd3b0",
          "md5": "8abedb54d12d5a3d5910643b6ea1eece"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2518.4.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2518.4.jar",
          "size": 19699542,
          "sha512": "7ef0daa3df26f85c76dff55988e5ca2497907c3cfd58e91a37a9ff774f0c59846aaa7ca640b6e7a315d523944663242f63c517d09d0eb5ba3c06bc95ac496007",
          "sha256": "bbec99f3c9cda074a1261b19d24692cd97f2ac16c2ef247f26642a076d30e8d4",
          "sha1": "844dc145ff8d5a633b3376a2ef01bec39b7fd3b0",
          "md5": "8abedb54d12d5a3d5910643b6ea1eece"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2518.4-sources.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2518.4-sources.jar",
          "size": 18818625,
          "sha512": "1a9c7b5a50aeb8df88fea2631b4fe66064479685f0082a44fbd52e7c4b4b202288f2c8f171b39af87f80bd4b6992e9294cd1ba4eb4a7f7b601096381b7ed7926",
          "sha256": "4a032f08bcb681cea1b57f24f950ce9884d576493f17c430e9e491a83aeb7a80",
          "sha1": "a7b34c7279ef5584771927aa6eda2b62375ffaba",
          "md5": "a20274eace8f7c7d51aa37fe596b1036"
        }
      ]
    }
  ]
}
