{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.7.2617.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2617.3.jar",
          "size": 551939,
          "sha512": "2aa02aa85a8b12954f22324c185bfa0387ed2dba9fd5feec2f3f653dd60aa00a0e74cf77bac43260bdc8d80383aa321e49cb45b3e954d3380ee2baee892ba89d",
          "sha256": "2e9a96c1f8b54a8a8fceae360c6ea75623c9bb9b6ec0613482dc379fcc3b4dbc",
          "sha1": "f9f6a7c23ff0aa32eeec8a8029a5a6efe57010af",
          "md5": "3abeac501440f4da222149c21b979ee1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2617.3.jar",
          "size": 551939,
          "sha512": "2aa02aa85a8b12954f22324c185bfa0387ed2dba9fd5feec2f3f653dd60aa00a0e74cf77bac43260bdc8d80383aa321e49cb45b3e954d3380ee2baee892ba89d",
          "sha256": "2e9a96c1f8b54a8a8fceae360c6ea75623c9bb9b6ec0613482dc379fcc3b4dbc",
          "sha1": "f9f6a7c23ff0aa32eeec8a8029a5a6efe57010af",
          "md5": "3abeac501440f4da222149c21b979ee1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2617.3-sources.jar",
          "size": 256780,
          "sha512": "09dadddb610b17a304e49b2d800541a3d6e60fff7bb23ea98fc6355d8c1be9fce208e6d5006c4b05233b0d3608c85d32322ed5d0ffdc8c523034348da3d10d9c",
          "sha256": "58b195c831b8ff79e8abb2db7f2a33843980ff78af7b6d80c49e6623aa3a08b7",
          "sha1": "8d3eb8848efb80a8793a850107d3ae92621f56fe",
          "md5": "5288f2d7c36ddb0188301df29135fd5d"
        },
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2617.3-sources.jar",
          "size": 256780,
          "sha512": "09dadddb610b17a304e49b2d800541a3d6e60fff7bb23ea98fc6355d8c1be9fce208e6d5006c4b05233b0d3608c85d32322ed5d0ffdc8c523034348da3d10d9c",
          "sha256": "58b195c831b8ff79e8abb2db7f2a33843980ff78af7b6d80c49e6623aa3a08b7",
          "sha1": "8d3eb8848efb80a8793a850107d3ae92621f56fe",
          "md5": "5288f2d7c36ddb0188301df29135fd5d"
        }
      ]
    }
  ]
}
