{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.8.0.2518.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.4.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.4.jar",
          "size": 19668735,
          "sha512": "3731589f36fe0540d67bec54bcd79c2fe9df2bab4798793762f686fbbe38218cbe2683dc0c89f9a473c2aa6f733ef54023719e9de2e3fb41465ff9dbee03c7c3",
          "sha256": "8ed7ff5fc2ce2428881eca1cf9091547b90ea14dddde75ca4296536b3863b4ad",
          "sha1": "d13d3c24ff2ac3048c0845cac1e087fea76cf5c9",
          "md5": "5d832188118037dfe5baee77681237f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.4.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.4.jar",
          "size": 19668735,
          "sha512": "3731589f36fe0540d67bec54bcd79c2fe9df2bab4798793762f686fbbe38218cbe2683dc0c89f9a473c2aa6f733ef54023719e9de2e3fb41465ff9dbee03c7c3",
          "sha256": "8ed7ff5fc2ce2428881eca1cf9091547b90ea14dddde75ca4296536b3863b4ad",
          "sha1": "d13d3c24ff2ac3048c0845cac1e087fea76cf5c9",
          "md5": "5d832188118037dfe5baee77681237f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.4-sources.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.4-sources.jar",
          "size": 18808177,
          "sha512": "5cfa69621f5a843e8c9c32ebb793745b2092f9d943250bbe0ce2cfa7c96672f5b402687237bef5f68e7edaae94d90532f096759ed25f61fac74a0f78566ef3f6",
          "sha256": "b0709440f22b5c3b22ec41cc3fc0288c8d1e1ceabb7c545cf8f6fb6530568921",
          "sha1": "a9359d5ad47bb33fa4325fa6e60e7c3d41c3d628",
          "md5": "f7ecbd99804d2b3a03d6f2c7184d7f38"
        }
      ]
    }
  ]
}
