{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.7.2616.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.7.2616.0.jar",
          "size": 1156465,
          "sha512": "8ca93685cb2606fc219330a0d11ba6a04385363e2d58eab353173b60195fe1895638a1ed5d231084226420391aca28b9773c491bc8fc139f385c067ad3b7fd0e",
          "sha256": "54c6ea088801288a369ad4ff41e7562ae24d154abaffd8407bba587bbff37a84",
          "sha1": "fe42a80db370d21708c989c42452d6e97e15d9ff",
          "md5": "5f669e9881655f7ba09eed74c528e79b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.4-54.1.3"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.7.2616.0.jar",
          "size": 1156465,
          "sha512": "8ca93685cb2606fc219330a0d11ba6a04385363e2d58eab353173b60195fe1895638a1ed5d231084226420391aca28b9773c491bc8fc139f385c067ad3b7fd0e",
          "sha256": "54c6ea088801288a369ad4ff41e7562ae24d154abaffd8407bba587bbff37a84",
          "sha1": "fe42a80db370d21708c989c42452d6e97e15d9ff",
          "md5": "5f669e9881655f7ba09eed74c528e79b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.7.2616.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.7.2616.0-sources.jar",
          "size": 256788,
          "sha512": "350e8e22707af004aa8300fa0f071edfff160b5a23edac08c4a0965cd35357e947803a69b17a6db4fbd60eec3d3c248f2b3a30a49bceaf093ae5477096938168",
          "sha256": "6f35bb84fbd56aafcf086b4ee00939a87d08e145375682f01589b5a1867d8f14",
          "sha1": "1be94d3b5415e77f74f8e3ab6b3aacfb95b567d6",
          "md5": "f39c3d147125164f6bf2bbe74d25a75c"
        },
        {
          "name": "factory_api-forge-1.21.4-2.2.7.2616.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.7.2616.0-sources.jar",
          "size": 256788,
          "sha512": "350e8e22707af004aa8300fa0f071edfff160b5a23edac08c4a0965cd35357e947803a69b17a6db4fbd60eec3d3c248f2b3a30a49bceaf093ae5477096938168",
          "sha256": "6f35bb84fbd56aafcf086b4ee00939a87d08e145375682f01589b5a1867d8f14",
          "sha1": "1be94d3b5415e77f74f8e3ab6b3aacfb95b567d6",
          "md5": "f39c3d147125164f6bf2bbe74d25a75c"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.4-54.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.7.2616.0.jar",
          "size": 1156465,
          "sha512": "8ca93685cb2606fc219330a0d11ba6a04385363e2d58eab353173b60195fe1895638a1ed5d231084226420391aca28b9773c491bc8fc139f385c067ad3b7fd0e",
          "sha256": "54c6ea088801288a369ad4ff41e7562ae24d154abaffd8407bba587bbff37a84",
          "sha1": "fe42a80db370d21708c989c42452d6e97e15d9ff",
          "md5": "5f669e9881655f7ba09eed74c528e79b"
        }
      ]
    }
  ]
}
