{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.11.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.11.jar",
          "size": 443641,
          "sha512": "3c8b8b7eee543011758c420276a379473cc77d4d9c83c6811543cb548b00da242c2c7a0300dc669513026a875a39139626fdeda834151885f498879a5882d4d1",
          "sha256": "955ddb0a49e59e8c06eaef6e04b9e00ff9661b1dd02a351b8de5d88fa4b02508",
          "sha1": "99ee1978e78a960c46ee0e0fe35a95a33954edd5",
          "md5": "000a2df071911f7f9138905900ee6b64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.11.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.11.jar",
          "size": 443641,
          "sha512": "3c8b8b7eee543011758c420276a379473cc77d4d9c83c6811543cb548b00da242c2c7a0300dc669513026a875a39139626fdeda834151885f498879a5882d4d1",
          "sha256": "955ddb0a49e59e8c06eaef6e04b9e00ff9661b1dd02a351b8de5d88fa4b02508",
          "sha1": "99ee1978e78a960c46ee0e0fe35a95a33954edd5",
          "md5": "000a2df071911f7f9138905900ee6b64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.11-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.11-sources.jar",
          "size": 229178,
          "sha512": "4292b67f0dd118244b884664e023cf7d2674ef6068256dc7c4b1a431d6e2cc84af17912483223da80da4393898f8a7faea1310a18aa239e205ad9f92f953ac1b",
          "sha256": "060c8cd4392d2d8f802af9acdecd571505568f1b0085ee793a6ad59b3e0d45be",
          "sha1": "d7d0a0293003807cd2ef6041e3a2fbb3eb226b83",
          "md5": "4f7f10be0104386568e5e14ba76b8bfe"
        }
      ]
    }
  ]
}
