{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2545.0.jar",
          "size": 537301,
          "sha512": "0b30498d27eee32d7d503a9decb2f0528e02d58815f5186316d59389e348f3c71f0dfabcdaf3ce59b1b4c1bd248a5827e66685ebecb088af8bd803a7ab3928e3",
          "sha256": "45c915ebc2ce8fca40b4c1abf26b48f37083cb92b196927a041ff3cc3fc95a53",
          "sha1": "0d80d7f991ea11130d6990d8f6aef76404ea1c0d",
          "md5": "cde4b9c3eee71590258f1f250f61ff36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2545.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2545.0.jar",
          "size": 537301,
          "sha512": "0b30498d27eee32d7d503a9decb2f0528e02d58815f5186316d59389e348f3c71f0dfabcdaf3ce59b1b4c1bd248a5827e66685ebecb088af8bd803a7ab3928e3",
          "sha256": "45c915ebc2ce8fca40b4c1abf26b48f37083cb92b196927a041ff3cc3fc95a53",
          "sha1": "0d80d7f991ea11130d6990d8f6aef76404ea1c0d",
          "md5": "cde4b9c3eee71590258f1f250f61ff36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2545.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2545.0-sources.jar",
          "size": 268451,
          "sha512": "a8e7bdc86be9cf99027ac424fa56563880e0c8a2dede2064b309105d4fb28a94f735a48dc849eff67d482c884020a43ddfeb332b8924823de9971a308e0f48c5",
          "sha256": "2e96af09cda0c7ab0e8662c5f7d8f98a973964480e78424f5cedf04fb1b615a0",
          "sha1": "9896070f3dfec65f69373ce51c97722d39bb2a11",
          "md5": "f2c6eecb883221964627183b8a7abc25"
        }
      ]
    }
  ]
}
