{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.14.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.14.jar",
          "size": 379420,
          "sha512": "860cbde4f5cf0fa9bb22fd47096f520fc40e7d876d5c75b05de45cfb89d9bed89bd5cea61490b1c4a85d9e4fd3e5177b65f256844bf7f69d83e50c237bf773ea",
          "sha256": "b164cf3c04e0e422b902a85c84b5e3f3509caee4ed586985bce75e755a7ef8c4",
          "sha1": "3b8e8d2038d953b322bdac484ad4e9bf098d65d7",
          "md5": "6d95f5021fb680d9bdb11dd725b15fbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.14.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.14.jar",
          "size": 379420,
          "sha512": "860cbde4f5cf0fa9bb22fd47096f520fc40e7d876d5c75b05de45cfb89d9bed89bd5cea61490b1c4a85d9e4fd3e5177b65f256844bf7f69d83e50c237bf773ea",
          "sha256": "b164cf3c04e0e422b902a85c84b5e3f3509caee4ed586985bce75e755a7ef8c4",
          "sha1": "3b8e8d2038d953b322bdac484ad4e9bf098d65d7",
          "md5": "6d95f5021fb680d9bdb11dd725b15fbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.14-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.14-sources.jar",
          "size": 199665,
          "sha512": "0cd4f10a50dba2d895db4aee429e6f4450ab0fc205218fae7dfc4a65ebc9cc80e9985101a926b0cb92084ee1f45ce3f425f7cdfdd341a35678d36f1a49e12bcf",
          "sha256": "2d83204e45fa2fa6665064dbe5f19908d2bb5d54b045bbb5f634dd35c5c9d602",
          "sha1": "cb5243d082545b2674733c38f75bc620abaf2654",
          "md5": "b794b027cdf632b0f1638368e1460a8b"
        }
      ]
    }
  ]
}
