{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.7.2616.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.7.2616.0.jar",
          "size": 1157444,
          "sha512": "478546ddbc7675040e16f18bfbb092c1ffbd3706b3077b1b707263c1bbfa586094f09fffc8df1ec3d0ac098eb067289e2b58e719129c90fb9f2026363e19c3b2",
          "sha256": "29fa019e6e0e4e6a3207c342e00aaf00a9868a44385961b6017ca75dca4ac2dc",
          "sha1": "7feb1624d55a914bafc724e95c2ebb6e1198fd18",
          "md5": "1cd32925be94b644f47357dfbe564ad9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.5-55.0.3"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.7.2616.0.jar",
          "size": 1157444,
          "sha512": "478546ddbc7675040e16f18bfbb092c1ffbd3706b3077b1b707263c1bbfa586094f09fffc8df1ec3d0ac098eb067289e2b58e719129c90fb9f2026363e19c3b2",
          "sha256": "29fa019e6e0e4e6a3207c342e00aaf00a9868a44385961b6017ca75dca4ac2dc",
          "sha1": "7feb1624d55a914bafc724e95c2ebb6e1198fd18",
          "md5": "1cd32925be94b644f47357dfbe564ad9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.7.2616.0-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.7.2616.0-sources.jar",
          "size": 256826,
          "sha512": "93e458b575bb678cad062e164862d7f13c9303f59304a3cffd45eb40af34f8aec14873222ad5ec8733ba2b1efba760a34077ecb6aa215a35ad2c0c4a5173918e",
          "sha256": "1f0753daa98a217b9327ab3a1e2eb2cc8abe73c54e5ea6ef84b21700334a4a46",
          "sha1": "664bd3a66c2c251dc1cd408d9c671e64eb6ded67",
          "md5": "1bf4b0402207620f0e281db0f333d058"
        },
        {
          "name": "factory_api-forge-1.21.5-2.2.7.2616.0-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.7.2616.0-sources.jar",
          "size": 256826,
          "sha512": "93e458b575bb678cad062e164862d7f13c9303f59304a3cffd45eb40af34f8aec14873222ad5ec8733ba2b1efba760a34077ecb6aa215a35ad2c0c4a5173918e",
          "sha256": "1f0753daa98a217b9327ab3a1e2eb2cc8abe73c54e5ea6ef84b21700334a4a46",
          "sha1": "664bd3a66c2c251dc1cd408d9c671e64eb6ded67",
          "md5": "1bf4b0402207620f0e281db0f333d058"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.5-55.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.7.2616.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.7.2616.0.jar",
          "size": 1157444,
          "sha512": "478546ddbc7675040e16f18bfbb092c1ffbd3706b3077b1b707263c1bbfa586094f09fffc8df1ec3d0ac098eb067289e2b58e719129c90fb9f2026363e19c3b2",
          "sha256": "29fa019e6e0e4e6a3207c342e00aaf00a9868a44385961b6017ca75dca4ac2dc",
          "sha1": "7feb1624d55a914bafc724e95c2ebb6e1198fd18",
          "md5": "1cd32925be94b644f47357dfbe564ad9"
        }
      ]
    }
  ]
}
