{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2504.3.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2504.3.jar",
          "size": 462386,
          "sha512": "3f9dbca3971463abdcc636142b028736ceb0ef3f2238fd29cab46a51aa35f90861761cf3c2eea5beb9603dadb8fcbf452087e39432850e2761974cc2f890c349",
          "sha256": "dc8f662979b6fc0aade8863a4fe3198648d6946838701be8ff5f4718a10f59b5",
          "sha1": "a7dcbd17eb2312daf90677ef91052f25a9db0cd8",
          "md5": "99684b56c462082bffdee026ce4eea53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2504.3.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2504.3.jar",
          "size": 462386,
          "sha512": "3f9dbca3971463abdcc636142b028736ceb0ef3f2238fd29cab46a51aa35f90861761cf3c2eea5beb9603dadb8fcbf452087e39432850e2761974cc2f890c349",
          "sha256": "dc8f662979b6fc0aade8863a4fe3198648d6946838701be8ff5f4718a10f59b5",
          "sha1": "a7dcbd17eb2312daf90677ef91052f25a9db0cd8",
          "md5": "99684b56c462082bffdee026ce4eea53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2504.3-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2504.3-sources.jar",
          "size": 231574,
          "sha512": "87829dbcf9d288a5f56bff5653a60a0793cd1775e4299e83b13797ec3a909f5a67f1b8d175e2e375bbdeb0dddf027d7b1b59525641dfcdacdd6d69074659024e",
          "sha256": "cbf4cd64c36d00dec16f5912acb40ec61f521fc9ead14d11645118837b2bc883",
          "sha1": "f792af200df1239f05c9aae9b7b1a5151ff5de34",
          "md5": "1f6abf1817d44671a4d94926db9fd778"
        }
      ]
    }
  ]
}
