{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2508.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.3.jar",
          "size": 692613,
          "sha512": "57ac2b3105c0f74fd85eaaabe398d911f68b177bb5207fe5ef76a311c805016f771a8a4a6c27e1dd6f468c9707fc6de2d7a1c2b05babadab774e617659b918be",
          "sha256": "14d68593d480b45bd52426b4ddbed58682a13020649a69ac03f1d645a1b67e1c",
          "sha1": "dc38e1c2dcf2480068b782ce4a2daf84ef857917",
          "md5": "e55b08526eb8745b386f0b6625bf0f5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.3.jar",
          "size": 692613,
          "sha512": "57ac2b3105c0f74fd85eaaabe398d911f68b177bb5207fe5ef76a311c805016f771a8a4a6c27e1dd6f468c9707fc6de2d7a1c2b05babadab774e617659b918be",
          "sha256": "14d68593d480b45bd52426b4ddbed58682a13020649a69ac03f1d645a1b67e1c",
          "sha1": "dc38e1c2dcf2480068b782ce4a2daf84ef857917",
          "md5": "e55b08526eb8745b386f0b6625bf0f5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.3-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.3-sources.jar",
          "size": 248128,
          "sha512": "23a5e37d7b3a0eb27da5c3da9ee83d1aeb74d205bcb17f3315359f810ebe5ba0dfb5a9af1ca9c6c8193d287080cebe2a3fb55416815102036de8eabd1c117071",
          "sha256": "120d6c1e9fb300b71910444f15efbd4cbfb3fd34e5c238f01bad0cdbe2c4476f",
          "sha1": "e199da83ed656966089b348a91358d995e1cae4f",
          "md5": "ef5862127197468079e14566f01f86ad"
        }
      ]
    }
  ]
}
