{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2513.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.8.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.8.jar",
          "size": 706145,
          "sha512": "4ef04b73afb37ee2da402ea3af30cf17a1c76c1debd8cdb9c0fe8d0dc47eb1258c9b575682facbf25242a73ef2c62938c859c3242932e4ccffb38b5d6a74a597",
          "sha256": "e1a7853afba6b50ed52d799718b433e97624cf086609e3cc05293e8ee9ea558d",
          "sha1": "e461011bdce30c0946de9a6ef487c9153dd8b6f4",
          "md5": "fdf9ab27ca455daa2270f57283698d81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.8.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.8.jar",
          "size": 706145,
          "sha512": "4ef04b73afb37ee2da402ea3af30cf17a1c76c1debd8cdb9c0fe8d0dc47eb1258c9b575682facbf25242a73ef2c62938c859c3242932e4ccffb38b5d6a74a597",
          "sha256": "e1a7853afba6b50ed52d799718b433e97624cf086609e3cc05293e8ee9ea558d",
          "sha1": "e461011bdce30c0946de9a6ef487c9153dd8b6f4",
          "md5": "fdf9ab27ca455daa2270f57283698d81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.8-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.8-sources.jar",
          "size": 251495,
          "sha512": "f26065d3e9a2d2bcf6a9c5ef683a10c96e3a7f793a380da318756b2bea3b84ecf6194664a16c1be02f54a8f7e2be27d8e27008d0b629f4700d57f0ecf26bd360",
          "sha256": "7163c8201138ed452f73f8b28e951c11e5f991381034b48d0c7c449afac0b072",
          "sha1": "1380fbe2162cb81c84f086701c353d4ee67976dc",
          "md5": "320823dd4076b4e49b31a5800f7c393a"
        }
      ]
    }
  ]
}
