{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.7.10.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2504.4.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2504.4.jar",
          "size": 14261716,
          "sha512": "6b73fc1dd4aff55ae37aad65f87ed2a712a224fee7e313f4218f764f7980d9a0332bb6582b50356c0fd46d5226c8caad8961c16e7ee7ad8271fc33dd725f5f63",
          "sha256": "1096525d3df76719b36fe4baa080c812dba89a495dde7d261fccfcbed237ade5",
          "sha1": "a7a5711af4adb66ab2dbaa76e35ae8b024561fe8",
          "md5": "c48943cc528b1af597b278d6eeef5162"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2504.4.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2504.4.jar",
          "size": 14261716,
          "sha512": "6b73fc1dd4aff55ae37aad65f87ed2a712a224fee7e313f4218f764f7980d9a0332bb6582b50356c0fd46d5226c8caad8961c16e7ee7ad8271fc33dd725f5f63",
          "sha256": "1096525d3df76719b36fe4baa080c812dba89a495dde7d261fccfcbed237ade5",
          "sha1": "a7a5711af4adb66ab2dbaa76e35ae8b024561fe8",
          "md5": "c48943cc528b1af597b278d6eeef5162"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.7.10.2504.4-sources.jar",
          "url": "legacy-fabric-1.21.4-1.7.10.2504.4-sources.jar",
          "size": 13453814,
          "sha512": "0365b1f1c2cd8ed95cf3d2ab2296408957b2665ba5e9609a09b87f3e6640ddb95e6bf70f7d0688682e838695ed41346799723c95bb5fb81d1dbdd38065bf14d2",
          "sha256": "685caeaa04ee03a930d9f8d4f65aae037c1d58ab752e6c6db849a0cdd84a53fd",
          "sha1": "6be288de22287eecce730f8d8ec019bf6ae9ade8",
          "md5": "e521e1ab9820d4ce679452fe42e0cf7b"
        }
      ]
    }
  ]
}
