{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.20.4-1.7.10.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2501.23"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2501.2.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2501.2.jar",
          "size": 11934492,
          "sha512": "9ccaf0689d6524a39e5bd67fb3cfb8a67828e1870cd3e82d124308cd0e3e27e447424e0df7416fa190e6ae27d79052d37a0cf152a8121a45f999084af89657be",
          "sha256": "6a9fd030d1e108c79bcc960bf7cdcbe2c9ecfa259d677b6e0b9c7579e118aeb9",
          "sha1": "373c40f550684376b52a87c650ac1bb87c7fdad3",
          "md5": "ff8adfd3037039fd61cb8e8381479146"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.2501.23"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2501.2.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2501.2.jar",
          "size": 11934492,
          "sha512": "9ccaf0689d6524a39e5bd67fb3cfb8a67828e1870cd3e82d124308cd0e3e27e447424e0df7416fa190e6ae27d79052d37a0cf152a8121a45f999084af89657be",
          "sha256": "6a9fd030d1e108c79bcc960bf7cdcbe2c9ecfa259d677b6e0b9c7579e118aeb9",
          "sha1": "373c40f550684376b52a87c650ac1bb87c7fdad3",
          "md5": "ff8adfd3037039fd61cb8e8381479146"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.7.10.2501.2-sources.jar",
          "url": "legacy-neoforge-1.20.4-1.7.10.2501.2-sources.jar",
          "size": 11140319,
          "sha512": "69848d4216807532c6637586b783b1657d16a2ae92b58cb93f451acbad5fcb7f8c7dac1f6b418774a0a5e43393975096a6a715e39d5cf8ec66a21dee1c7f8054",
          "sha256": "04cb8a2b5a1a0f7335466146e0c1f9049f4015380f9daea2b11aaf74b323d55f",
          "sha1": "78b444656ce75e576b106b1bfe361020d3c16440",
          "md5": "7c01541d476255b1005015b22971aae1"
        }
      ]
    }
  ]
}
