{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2512.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2512.0.jar",
          "size": 705095,
          "sha512": "b3cc63fcc810396a44332d46b786cfea372e70a398b4dcf36b7f82521113835dab9a70ee8df4bc9de542f708ad9cf0ddb3efc47fb9661780b5023633e57fd309",
          "sha256": "687e4934f5c107735782acaf5405913366d29172601b51da50a0fdf3e749e436",
          "sha1": "08cbd963fa2712f8d42d71e13d0fc4de2db48a09",
          "md5": "243544b2a4a15292e2ee0f25a40bb482"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2512.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2512.0.jar",
          "size": 705095,
          "sha512": "b3cc63fcc810396a44332d46b786cfea372e70a398b4dcf36b7f82521113835dab9a70ee8df4bc9de542f708ad9cf0ddb3efc47fb9661780b5023633e57fd309",
          "sha256": "687e4934f5c107735782acaf5405913366d29172601b51da50a0fdf3e749e436",
          "sha1": "08cbd963fa2712f8d42d71e13d0fc4de2db48a09",
          "md5": "243544b2a4a15292e2ee0f25a40bb482"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2512.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2512.0-sources.jar",
          "size": 252786,
          "sha512": "d5dc6e139982e0bbd0da3d95a2a03ae218c66ea9d08d2bfc24e39bc73cdd52a78dd5fb2ca14a4b3c004db2b8f1236284ef8cd39715d8ae303f282950441b4ae2",
          "sha256": "a437407304c22a2dc1261c05e4c0b777e956b2aea59457ef0013c29cb8efc23d",
          "sha1": "071304ce7ffde4e1de2728d98dcae9c673b36616",
          "md5": "f60d7f045de4b3f29bfd9762f708ab0c"
        }
      ]
    }
  ]
}
