{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.3-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.3-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-forge-1.21.3-1.1.2516.3.jar",
          "size": 642721,
          "sha512": "f5f4ed606da574af2f7ba27d346838013e1f4239df2481edf0f868c216111a84378ddbb49e014939683f9ce4eecc03a647c174474f4936c04c46390c06219005",
          "sha256": "6609c0e088e3fe0c3e848fecc15f6731bd3ef74d05cf0a8598b3b716b45c4872",
          "sha1": "df7fac1d8a3b56f60338300b039eab079c6c51c6",
          "md5": "92f459fd8ae0e935fc1d370faba1b871"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.3-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-forge-1.21.3-1.1.2516.3.jar",
          "size": 642721,
          "sha512": "f5f4ed606da574af2f7ba27d346838013e1f4239df2481edf0f868c216111a84378ddbb49e014939683f9ce4eecc03a647c174474f4936c04c46390c06219005",
          "sha256": "6609c0e088e3fe0c3e848fecc15f6731bd3ef74d05cf0a8598b3b716b45c4872",
          "sha1": "df7fac1d8a3b56f60338300b039eab079c6c51c6",
          "md5": "92f459fd8ae0e935fc1d370faba1b871"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.3-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.3-1.1.2516.3-sources.jar",
          "size": 585484,
          "sha512": "bdf4c13a25f5ea54c2ffbbe4a0b5541e53b2fd831b181e7daf1c4515860e6dc5faca700059dce6d26f191566b58bea1a0fe23810421e0147c171f774f422cecc",
          "sha256": "0bd6db6ef9d5db6c3c646b4532788f79b8f786fdfb44820f31b842c0c9d9fabd",
          "sha1": "2449e19dc3852d00fce5a3b60c161a8830d8db19",
          "md5": "c002a8d905e2cbb1c9874c6e96b34c93"
        }
      ]
    }
  ]
}
