{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.3-1.7.10.2502.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.2501.24"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.3-1.7.10.2502.0.jar",
          "url": "legacy-fabric-1.21.3-1.7.10.2502.0.jar",
          "size": 11920443,
          "sha512": "36a562a7015d577abc40b0579a5472f1fab23e16e9c44b508e364855feace3282ae4e200eb9a18693036956283a968d1dfb4ea760ad72a6cb1b5f85973e77bed",
          "sha256": "b6e780bc8b223dc4d1c60d29df3095dc4c9e5742280838012f70668eed760487",
          "sha1": "bf8fef759b444035f4965a355f8e73e586a51078",
          "md5": "8ffadafe7788cc141666d5235bdce791"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.2501.24"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.3-1.7.10.2502.0.jar",
          "url": "legacy-fabric-1.21.3-1.7.10.2502.0.jar",
          "size": 11920443,
          "sha512": "36a562a7015d577abc40b0579a5472f1fab23e16e9c44b508e364855feace3282ae4e200eb9a18693036956283a968d1dfb4ea760ad72a6cb1b5f85973e77bed",
          "sha256": "b6e780bc8b223dc4d1c60d29df3095dc4c9e5742280838012f70668eed760487",
          "sha1": "bf8fef759b444035f4965a355f8e73e586a51078",
          "md5": "8ffadafe7788cc141666d5235bdce791"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.3-1.7.10.2502.0-sources.jar",
          "url": "legacy-fabric-1.21.3-1.7.10.2502.0-sources.jar",
          "size": 11133412,
          "sha512": "a72f3d98a8d8bd411c6b732156b4e4eeb161e14cb3f9f6ba87ef0c8fe545ddbf7da420e1bae2362044c3dbad95adea01f4880714dbd69ee26d21e8d114cb9e68",
          "sha256": "b537cc62c611c87be91d5a0ff235dfe536553f8b2ae42e5a93eb21b6ac113853",
          "sha1": "cfc600b45451e18a57d84349b3fea9656aa72211",
          "md5": "275206df236029831b17924343c68dd6"
        }
      ]
    }
  ]
}
