{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.6.2541.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2541.1.jar",
          "size": 534517,
          "sha512": "e84e946c5284e039772203d02d3aedb3f06727b28da53699633766c373ea8922e73ce96503204d71290a90b46959abe4989904b56805597bf01576e27dca7f5f",
          "sha256": "17d33b75fb4db405e8b7d4fc2e84dc0870dd532efcbaa370f4623d1e6efbd115",
          "sha1": "a8ead112d00431a4c2b85cb8d234f118670d899f",
          "md5": "6096b52ff6bcf69274d481f957d0bbc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2541.1.jar",
          "size": 534517,
          "sha512": "e84e946c5284e039772203d02d3aedb3f06727b28da53699633766c373ea8922e73ce96503204d71290a90b46959abe4989904b56805597bf01576e27dca7f5f",
          "sha256": "17d33b75fb4db405e8b7d4fc2e84dc0870dd532efcbaa370f4623d1e6efbd115",
          "sha1": "a8ead112d00431a4c2b85cb8d234f118670d899f",
          "md5": "6096b52ff6bcf69274d481f957d0bbc3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2541.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2541.1-sources.jar",
          "size": 267845,
          "sha512": "e305ac86da9cf59df3d0a9a6bf92ff70fe477c591383b6315572746226f4af0e962df20dad00033a5cf89d2788ad80529857d06f9cb9e3d21923a287cfe9433a",
          "sha256": "3d94068e0be346ddae38e2ab47c02e76e5fb40bec656d693e9b6ba908e071871",
          "sha1": "9d07b7f00b70158a58faa480ca113a021cebd648",
          "md5": "58f2a679e71d29c43284d35c115c46ab"
        }
      ]
    }
  ]
}
