{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.0.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2512.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2512.0.jar",
          "size": 18277861,
          "sha512": "10966002726f3830fd67a44db0354daa4312c0e886dee03ebb1643b13dcd313a7e1d56ac4dd35eeaa20607570bbf429404217fef8a8bda4ce01514dd5dc41e08",
          "sha256": "a9ca349f7c229e05d21693acfac40076a63834d0eecf9c2bea26846e09e8ab23",
          "sha1": "5b204b39d8bb3744f963dc5d0bfbd9a9ae40c082",
          "md5": "bc1a25da7adc7a661348935b160b4df0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2512.0.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2512.0.jar",
          "size": 18277861,
          "sha512": "10966002726f3830fd67a44db0354daa4312c0e886dee03ebb1643b13dcd313a7e1d56ac4dd35eeaa20607570bbf429404217fef8a8bda4ce01514dd5dc41e08",
          "sha256": "a9ca349f7c229e05d21693acfac40076a63834d0eecf9c2bea26846e09e8ab23",
          "sha1": "5b204b39d8bb3744f963dc5d0bfbd9a9ae40c082",
          "md5": "bc1a25da7adc7a661348935b160b4df0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2512.0-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2512.0-sources.jar",
          "size": 17422432,
          "sha512": "540f6956fe3ea095dbb73be929aea5b31f41368b40d39b984220f8dca4c8264600408c09ade0e97ef811dde9921aeb35c289bf2da19531047c83b337ba495ec7",
          "sha256": "f10f22d783e8abf8d4ef05e0d2a6d05549686d97b5d84cc91c72e50bfa7bc93d",
          "sha1": "6e325f27eb4710f44eae22f28b198448d1641399",
          "md5": "6f812d327dcb190c2ccf74e8c165bb83"
        }
      ]
    }
  ]
}
