{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.2.jar",
          "size": 560278,
          "sha512": "f2e31f8324ea90fd28b344dd2a2a733aa9ed8ed1e67b5d415c8897387b95ddefdf81c45aac5ae77efad81067b9030a2f3ded271dc164a90cffc11114048695c1",
          "sha256": "fd6f1668af9b374633d06be2c9bbed45e7450a0fc4def539eaa0acf06bf27fbd",
          "sha1": "524943c6173764331a240ae831337610740f82bb",
          "md5": "4225e51439f108f33ef4272146a3b3e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.2.jar",
          "size": 560278,
          "sha512": "f2e31f8324ea90fd28b344dd2a2a733aa9ed8ed1e67b5d415c8897387b95ddefdf81c45aac5ae77efad81067b9030a2f3ded271dc164a90cffc11114048695c1",
          "sha256": "fd6f1668af9b374633d06be2c9bbed45e7450a0fc4def539eaa0acf06bf27fbd",
          "sha1": "524943c6173764331a240ae831337610740f82bb",
          "md5": "4225e51439f108f33ef4272146a3b3e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.2-sources.jar",
          "size": 256725,
          "sha512": "d8e9ef91f7bffe3027d6d12e98559447c02d74f1955ab618a48bb32e61420018c15b799a99273078549207087f0d03c1672a51382758521d1121bb5ff2723977",
          "sha256": "15180d4563c5e0d8a7cb929e6c811e6ab12f3ea743937f1ff1638ae80fd12bb8",
          "sha1": "7267b54a4dcca7938de81933f7acb9a3b35fc21c",
          "md5": "65de2510ee255a3200a89c160ce8a1fb"
        },
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.2-sources.jar",
          "size": 256725,
          "sha512": "d8e9ef91f7bffe3027d6d12e98559447c02d74f1955ab618a48bb32e61420018c15b799a99273078549207087f0d03c1672a51382758521d1121bb5ff2723977",
          "sha256": "15180d4563c5e0d8a7cb929e6c811e6ab12f3ea743937f1ff1638ae80fd12bb8",
          "sha1": "7267b54a4dcca7938de81933f7acb9a3b35fc21c",
          "md5": "65de2510ee255a3200a89c160ce8a1fb"
        }
      ]
    }
  ]
}
