{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.11-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.9.jar",
          "size": 560895,
          "sha512": "8ec9f669c7b8654b962d5cc1f11519e6fc18876fd5bc490310d27f83dc23e84bd577b517e00c81e7022234438925e3b6299eaf20c1aab391933ee34da003640a",
          "sha256": "e7807f5a00e1ab4e8091c0e7f29a060f74eb8da6a657b5c4d84587e8d01caef5",
          "sha1": "eb3b1820a4b52505688189b057507ed730ccd427",
          "md5": "83791b3814a7f76437916dc4dedbebe0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.9.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.9.jar",
          "size": 560895,
          "sha512": "8ec9f669c7b8654b962d5cc1f11519e6fc18876fd5bc490310d27f83dc23e84bd577b517e00c81e7022234438925e3b6299eaf20c1aab391933ee34da003640a",
          "sha256": "e7807f5a00e1ab4e8091c0e7f29a060f74eb8da6a657b5c4d84587e8d01caef5",
          "sha1": "eb3b1820a4b52505688189b057507ed730ccd427",
          "md5": "83791b3814a7f76437916dc4dedbebe0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.9-sources.jar",
          "size": 256774,
          "sha512": "215853e72b4d1f8efc6f4da35c791185f01696aa586a70679a8294f24125f30175c45f8d1be724527a4b3e21a6f75f7e0fa4d296611cf2a04d604503ab178cb7",
          "sha256": "6407269851215ccfc9668795e4f14cededf2f792cfe03bd9ecd04dce550c3c8a",
          "sha1": "8fba2cea02070757b4d088b31e4be252ee171247",
          "md5": "4a7d56de0720f866e6735d19d823407d"
        },
        {
          "name": "factory_api-neoforge-1.21.11-2.2.9-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.9-sources.jar",
          "size": 256774,
          "sha512": "215853e72b4d1f8efc6f4da35c791185f01696aa586a70679a8294f24125f30175c45f8d1be724527a4b3e21a6f75f7e0fa4d296611cf2a04d604503ab178cb7",
          "sha256": "6407269851215ccfc9668795e4f14cededf2f792cfe03bd9ecd04dce550c3c8a",
          "sha1": "8fba2cea02070757b4d088b31e4be252ee171247",
          "md5": "4a7d56de0720f866e6735d19d823407d"
        }
      ]
    }
  ]
}
