{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.7.10.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.6.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.6.jar",
          "size": 14342018,
          "sha512": "e4c5fdb3c918d569e72ef1b42a1cd5132e8882ef3c14c6fc06400854e3eec63d565ab7355207a135d5e9bd00fcfa3addbc9b028f0b0864d5e532dfcc6be474e9",
          "sha256": "0403d7f49d6e015b5dd46035b6107165d59c82d7489f052622821c2dd9b0f549",
          "sha1": "0c51d502aef381fb4dfb437e562357ffb73f922d",
          "md5": "deb20ebcfb9c1a7742af0d9147ec3fab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.6.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.6.jar",
          "size": 14342018,
          "sha512": "e4c5fdb3c918d569e72ef1b42a1cd5132e8882ef3c14c6fc06400854e3eec63d565ab7355207a135d5e9bd00fcfa3addbc9b028f0b0864d5e532dfcc6be474e9",
          "sha256": "0403d7f49d6e015b5dd46035b6107165d59c82d7489f052622821c2dd9b0f549",
          "sha1": "0c51d502aef381fb4dfb437e562357ffb73f922d",
          "md5": "deb20ebcfb9c1a7742af0d9147ec3fab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.6-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.6-sources.jar",
          "size": 13514783,
          "sha512": "4a99ede767867621e63ef5806aaf42398f39630bd3b7e4b1d068c69a37bc0b6bdbe101c3f86b160a323435f867dc028eb636bda068383179a3b0fe737508a428",
          "sha256": "dc7f77108c615dbabd2c2c4127120d745546687831e87a0246d2782a0826f49c",
          "sha1": "878e703dcff90a73f1009f1ef1b2fcd42ff5fb07",
          "md5": "fba9dc0f16954263d43282b9a050d861"
        }
      ]
    }
  ]
}
