{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.15.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.15.jar",
          "size": 496189,
          "sha512": "e20598d146c7d70e987ca63d7352e2829301fe8f0ab2e618381a388d729a6088385efb058075d386e79dcc1237163bc026a0aa04bbb4527e7e0419844b10df13",
          "sha256": "d671bf41795560b3900487739df5efd3874142c8d85fb02a4d629001d80c705d",
          "sha1": "e27fe7e7b90681596904b20087a144c644e16a48",
          "md5": "a8d1ac8e0e7f0f533fdc90ffca85c9c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.15.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.15.jar",
          "size": 496189,
          "sha512": "e20598d146c7d70e987ca63d7352e2829301fe8f0ab2e618381a388d729a6088385efb058075d386e79dcc1237163bc026a0aa04bbb4527e7e0419844b10df13",
          "sha256": "d671bf41795560b3900487739df5efd3874142c8d85fb02a4d629001d80c705d",
          "sha1": "e27fe7e7b90681596904b20087a144c644e16a48",
          "md5": "a8d1ac8e0e7f0f533fdc90ffca85c9c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.15-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.15-sources.jar",
          "size": 244968,
          "sha512": "9bd268a357a0d4231ae53664feff984a622b679c8c28ded0e6bb46da998d5aec064c8825a0588f06f11d7e57be0ca752952a6cdee8b41136541eecded0415ab7",
          "sha256": "061429c8ff143b01c5ab47341b1f20df1a80105924ddff312c87cfbde6022356",
          "sha1": "7377fcc84dd52fa107767cbd14a6797000a25b4f",
          "md5": "7a5aeb7532c2051d70ad5414aa22d2bc"
        }
      ]
    }
  ]
}
