{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.5-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2516.0.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2516.0.jar",
          "size": 18261227,
          "sha512": "c320a362f161d413fee6bb68cd781bf15ab3a2ac8d5054827925412b5304efa85c73a9178d6ed915bee3a108a1e04916a1d35470aad3486fabb3b7990a1add2e",
          "sha256": "15dc33bab547a4a6622d2f6fb4535a86da2c4071596d1dc0dc34ad01294d0db9",
          "sha1": "68d834032af510f133360b56ff8fa1adc4c10b0c",
          "md5": "2663a5bf36479aec35a0f5fe67fcec58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "14.0.0-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2516.0.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2516.0.jar",
          "size": 18261227,
          "sha512": "c320a362f161d413fee6bb68cd781bf15ab3a2ac8d5054827925412b5304efa85c73a9178d6ed915bee3a108a1e04916a1d35470aad3486fabb3b7990a1add2e",
          "sha256": "15dc33bab547a4a6622d2f6fb4535a86da2c4071596d1dc0dc34ad01294d0db9",
          "sha1": "68d834032af510f133360b56ff8fa1adc4c10b0c",
          "md5": "2663a5bf36479aec35a0f5fe67fcec58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2516.0-sources.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2516.0-sources.jar",
          "size": 17424439,
          "sha512": "b2c02b6a7655dc01bd76ec9e683754a671d271b3e271dbd63ca182361b3d4e9204b71372629f9c8476171fa6138c7057d1c0c48abcfd8183828cfe3f2f51e017",
          "sha256": "a7d86c0593b013c3d7bd57fb2347e3863b05db03559ba8a3de9b3ec0130824de",
          "sha1": "f6ce3e58d282799cb214ba7c20baac8975bfad8d",
          "md5": "282aabe94c0f1113e09930adf192375c"
        }
      ]
    }
  ]
}
