{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.8.jar",
          "size": 495487,
          "sha512": "32bd9c7ec4d35fdbca9ffdc385177bcd57350cc32066c626e3214398d0aef8448275b95cf10d6a558c15803f6dbe2d8bdce4801e9a7f9ee3c65f255ba8f23a25",
          "sha256": "73292fff410585f8bd9fd494b19b7d2e8367dbe606aa5f364f9e33c458388960",
          "sha1": "31b78536f845c4dd31989683a17b4c150b3d6422",
          "md5": "cc2f049a0c5a5acceca056aaf7b2b239"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.8.jar",
          "size": 495487,
          "sha512": "32bd9c7ec4d35fdbca9ffdc385177bcd57350cc32066c626e3214398d0aef8448275b95cf10d6a558c15803f6dbe2d8bdce4801e9a7f9ee3c65f255ba8f23a25",
          "sha256": "73292fff410585f8bd9fd494b19b7d2e8367dbe606aa5f364f9e33c458388960",
          "sha1": "31b78536f845c4dd31989683a17b4c150b3d6422",
          "md5": "cc2f049a0c5a5acceca056aaf7b2b239"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.8-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.8-sources.jar",
          "size": 244620,
          "sha512": "a555da18f15ff0e6f3ff6d568bce62afbb1b08ce60187d902e48e5003d53f6199fae9b830d24c6b067f05129cfd7386d00dbeb14395d3e532ede240b97f46956",
          "sha256": "bc3f443e3e7363ab85f90580014edae8182995704115d51b4271be667ef2cd6f",
          "sha1": "bebf9ddee4cc906f7c582331871ba55912f4252e",
          "md5": "2c964d856598e27bd63af473aa07a566"
        }
      ]
    }
  ]
}
