{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2517.0.jar",
          "size": 713480,
          "sha512": "eb84884d984f6072500b75811e7505e94119e33af480695153f591c803eba471125ec57d02dcf41232d4268c598df9ce22ec2b93f3ba391204a9174040dcf055",
          "sha256": "184147983a7a6cb0ac10162aa28f891bfaa6b6db6cbf29c937a966f70bafc37a",
          "sha1": "68ad975aec41fa5136959dece4dd6d6f33460866",
          "md5": "ee99e5b1eca32f177404f91835dab4fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2517.0.jar",
          "size": 713480,
          "sha512": "eb84884d984f6072500b75811e7505e94119e33af480695153f591c803eba471125ec57d02dcf41232d4268c598df9ce22ec2b93f3ba391204a9174040dcf055",
          "sha256": "184147983a7a6cb0ac10162aa28f891bfaa6b6db6cbf29c937a966f70bafc37a",
          "sha1": "68ad975aec41fa5136959dece4dd6d6f33460866",
          "md5": "ee99e5b1eca32f177404f91835dab4fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2517.0-sources.jar",
          "size": 254594,
          "sha512": "93744f2434019829801ec50daa4eb823d4ccd3fa4768444f046bf20e9f9fccccaf167e5873da82e16bc231507c59b66b2346bb508ab37e8d9b3279461fc7a3e0",
          "sha256": "e8e846107630d7655bdb189596abf832377ef20c3ec387143b615cec37388a46",
          "sha1": "62e34fc0e40c1bf4bb7858be664ec061d4e98641",
          "md5": "6954a7d5f785bdf5dcf3c43e90c65294"
        }
      ]
    }
  ]
}
