{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2502.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.14.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.14.jar",
          "size": 451401,
          "sha512": "7c6aae018e0f8d1e70f031a916319d14bc5fc35858b0bca2fbccfd5a89055e5b0dd054375fe786b4886a670cf03d71e0a40adda793fe65ae7cda15dc05b63df0",
          "sha256": "f3ba25e84963d94287ae4792899aa3c9c0be3be7a72c7a6d7c3ff0128e6b941c",
          "sha1": "237a691ac5d6342d3b4eac51807736db56ae37b0",
          "md5": "c2f58f464bc077b820db99ba21b1a96a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.14.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.14.jar",
          "size": 451401,
          "sha512": "7c6aae018e0f8d1e70f031a916319d14bc5fc35858b0bca2fbccfd5a89055e5b0dd054375fe786b4886a670cf03d71e0a40adda793fe65ae7cda15dc05b63df0",
          "sha256": "f3ba25e84963d94287ae4792899aa3c9c0be3be7a72c7a6d7c3ff0128e6b941c",
          "sha1": "237a691ac5d6342d3b4eac51807736db56ae37b0",
          "md5": "c2f58f464bc077b820db99ba21b1a96a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.14-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.14-sources.jar",
          "size": 231799,
          "sha512": "9d716b69e00ba25dba27f5fa97236b2332f06dc364b8a924ec49fe2c87927f5181b66aff7afd923957185fd9b9697f9762d79216e8b89560e40d4d9756f26a0c",
          "sha256": "b507f8e92bfc363a67101d45a2ecca5bc78104d15218bbcfaaca81a53ee3ba9a",
          "sha1": "7479986658611ffb7a59150ae883e01745646a7e",
          "md5": "6d51c306431c4deb6429104216bff5d3"
        }
      ]
    }
  ]
}
