{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "size": 692408,
          "sha512": "0db8858d9315584e03b9ff7508c77bb9705c19de9d83ef774e36b4b122527099ba13dcbc057f631b0df0e32a5c568d447850e2bc886c75b6784f4008e920bf41",
          "sha256": "eb0c3628a2fa14c0759eb1459e939ac86ce6c96975388b5590c638b0d87a39f0",
          "sha1": "2cb473d93f93281f3b13c1da457c1117c807bee3",
          "md5": "3496395cd945dcb7f947ed5eaacb96c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "size": 692408,
          "sha512": "0db8858d9315584e03b9ff7508c77bb9705c19de9d83ef774e36b4b122527099ba13dcbc057f631b0df0e32a5c568d447850e2bc886c75b6784f4008e920bf41",
          "sha256": "eb0c3628a2fa14c0759eb1459e939ac86ce6c96975388b5590c638b0d87a39f0",
          "sha1": "2cb473d93f93281f3b13c1da457c1117c807bee3",
          "md5": "3496395cd945dcb7f947ed5eaacb96c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.2-sources.jar",
          "size": 248077,
          "sha512": "9d7437ac92f42b30734454a346e45f7a4e095eda247e4595d9f8e34ea03e1df350e8d63ff0ab002327f608f4b214c8ac5b663fdb8a579b4efb99d5993556bf36",
          "sha256": "ba238084a7f6703a44fb6e86624cc4751b30e1ec0385691c7ac144f95ccb7b58",
          "sha1": "e3cdb38de317ee20479ede0e1f39cf69ac0ef7c4",
          "md5": "1ca2cb79cff9828e56a2c535f2aabec1"
        }
      ]
    }
  ]
}
