{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "size": 692613,
          "sha512": "61398b2e1410f3326802fe24ec88470b3d34c5e107b8553fc0f05f982c2031c5266f45fc9bd6122f2d02f65231daa2b214835dc3cfe84f4909e54b6fa502069a",
          "sha256": "c3e8b9a66f27a0a51f59a81747827fa202fa3eb7976a4de74813feee9ed16c15",
          "sha1": "6b794e3919595ad221b978f2662c3e17d909e2ed",
          "md5": "1b068fe8a4abfa1edae56ba096b203cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.2.jar",
          "size": 692613,
          "sha512": "61398b2e1410f3326802fe24ec88470b3d34c5e107b8553fc0f05f982c2031c5266f45fc9bd6122f2d02f65231daa2b214835dc3cfe84f4909e54b6fa502069a",
          "sha256": "c3e8b9a66f27a0a51f59a81747827fa202fa3eb7976a4de74813feee9ed16c15",
          "sha1": "6b794e3919595ad221b978f2662c3e17d909e2ed",
          "md5": "1b068fe8a4abfa1edae56ba096b203cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.2-sources.jar",
          "size": 248128,
          "sha512": "0f473e3b32f09586e80c1a811ac2bafdb66dfbdc81310ed821ba390d06a70317a0035832bfefeedd87585ccc0fa067520558224fe4e8437621ddbaaedb36d664",
          "sha256": "864730fe9267ad426a414baf9f1af2bf8e2f57340d68740cdd0970400c567228",
          "sha1": "3f6208316a1adcabbd464fa2b44bbc5ce18fddc9",
          "md5": "99eae9f669ab3122828447ff4e501f92"
        }
      ]
    }
  ]
}
