{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2617.0.jar",
          "size": 534168,
          "sha512": "ba8c54625dc0870ea30e33de8f13efd621eb3b50beb45765012abf919676cff962bfcfa322cd0214fc1b32ed6d7996969c6b8126314214412441f2da75b68f7b",
          "sha256": "6bf172ef3618ff4ef4729e5fdd54883121891279c9c0bea1658d51d121854ac2",
          "sha1": "49e1bd8a37635d9fe30d57278007f70a568ef1e9",
          "md5": "4f4a6df9db0c95467a5901cf85115747"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2617.0.jar",
          "size": 534168,
          "sha512": "ba8c54625dc0870ea30e33de8f13efd621eb3b50beb45765012abf919676cff962bfcfa322cd0214fc1b32ed6d7996969c6b8126314214412441f2da75b68f7b",
          "sha256": "6bf172ef3618ff4ef4729e5fdd54883121891279c9c0bea1658d51d121854ac2",
          "sha1": "49e1bd8a37635d9fe30d57278007f70a568ef1e9",
          "md5": "4f4a6df9db0c95467a5901cf85115747"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2617.0-sources.jar",
          "size": 256820,
          "sha512": "7aa06978758f22e5273919e5f1cf035c9f814c9ae714689cb11f6806cb3b6b85a695b622c5d85d48ca58cacb0b34f1de6ce273cf6b9308388dcec71f6609120f",
          "sha256": "b498da3813df098d3ef58c05cef24371482e7051f9b67a819c7aaa4c6322f324",
          "sha1": "938865fc69054b8bc99baf6ee0ae12409db8b75c",
          "md5": "6bdf83c886d1584226f9a597b66f7077"
        },
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2617.0-sources.jar",
          "size": 256820,
          "sha512": "7aa06978758f22e5273919e5f1cf035c9f814c9ae714689cb11f6806cb3b6b85a695b622c5d85d48ca58cacb0b34f1de6ce273cf6b9308388dcec71f6609120f",
          "sha256": "b498da3813df098d3ef58c05cef24371482e7051f9b67a819c7aaa4c6322f324",
          "sha1": "938865fc69054b8bc99baf6ee0ae12409db8b75c",
          "md5": "6bdf83c886d1584226f9a597b66f7077"
        }
      ]
    }
  ]
}
