{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.7.10.2502.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.2501.24"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2502.0.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2502.0.jar",
          "size": 11918029,
          "sha512": "1167f61b8dc024ff92702216daa25ecaaae39ca30bd9ccf796f51b236709653ec8f0edf737c539f7bb54b3887688f8cee48f8aad03a7e25f305e0dfa40741f8b",
          "sha256": "2ca2300bb34c7d815930535f449c8925cb19a1dc41a37c295c341957b979db94",
          "sha1": "a23c7d64dfef7bb078d33921c8e4505547a150d5",
          "md5": "a06af38f1e5405226860f71e13f6b1e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.2501.24"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2502.0.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2502.0.jar",
          "size": 11918029,
          "sha512": "1167f61b8dc024ff92702216daa25ecaaae39ca30bd9ccf796f51b236709653ec8f0edf737c539f7bb54b3887688f8cee48f8aad03a7e25f305e0dfa40741f8b",
          "sha256": "2ca2300bb34c7d815930535f449c8925cb19a1dc41a37c295c341957b979db94",
          "sha1": "a23c7d64dfef7bb078d33921c8e4505547a150d5",
          "md5": "a06af38f1e5405226860f71e13f6b1e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.7.10.2502.0-sources.jar",
          "url": "legacy-fabric-1.21.1-1.7.10.2502.0-sources.jar",
          "size": 11133168,
          "sha512": "226df79b49922dddfe1fb55fd945bd2061be20ca730534083be75e758d6006f0a640e113bc22f1670b19433672a3abe0522f47e43cdb51437fc6bf0331cddc8e",
          "sha256": "9227ea9fd9cc6a8bf1892047cb2723d67d8be06d197ba7b2fb3180e104bd7d3c",
          "sha1": "e71e9fe9420bbfe0df7d31425792f8aa1bac4f2b",
          "md5": "482da0b5478ddc6861961f0076053507"
        }
      ]
    }
  ]
}
