{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2507.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.2.jar",
          "size": 497544,
          "sha512": "ff2f83a9ea3176ac8313a10b9c233a13affc80008cf02fa0673bc713d6013e651eb35384da66b5aca8943532c14c75f6b16d658cc365d63844618654d906fe2b",
          "sha256": "425772b04ae921e575cf7b985116cd1c621d2d082031ea353d46f0dc481ac72d",
          "sha1": "88f52f086e7bbca995183b5311179e36182e6593",
          "md5": "b7c9298492a27d0fae73d0c4becb70f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.2.jar",
          "size": 497544,
          "sha512": "ff2f83a9ea3176ac8313a10b9c233a13affc80008cf02fa0673bc713d6013e651eb35384da66b5aca8943532c14c75f6b16d658cc365d63844618654d906fe2b",
          "sha256": "425772b04ae921e575cf7b985116cd1c621d2d082031ea353d46f0dc481ac72d",
          "sha1": "88f52f086e7bbca995183b5311179e36182e6593",
          "md5": "b7c9298492a27d0fae73d0c4becb70f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.2-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.2-sources.jar",
          "size": 244127,
          "sha512": "add0e0153c4cb79d175dc14bb5ccdc3711980dbecce22b98a70ae077e952b00b10ee3722734cd21b69dd01229817500154b30cc5096f6c7d5257a8a86d6ef3e7",
          "sha256": "e8633072a0cd51688366b2d5dba8951dfc58d004575d28948c2f812ff98fe3fa",
          "sha1": "fba5b7d900b9c0da8ff4a46624482c8f283f009c",
          "md5": "cdd807e9777fe7af154196c6b5484471"
        }
      ]
    }
  ]
}
