{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.1-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2510.5.jar",
          "size": 533373,
          "sha512": "417577f166d2808e02b7c689e0ab32c45046e2b1a98b910609c12c5df777b31789342020d7f899e6189bdbdadb64023242373335d9375b5e8c9e688d4c8df4e1",
          "sha256": "b1d3f42844a34527a6e3cefd2d26963588567955d955149755d158aabd807626",
          "sha1": "d72cc8a160edacbb8b72b9de3933b923fdfba5c2",
          "md5": "d193e14d83654cc46e5bdf278902c10c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2510.5.jar",
          "size": 533373,
          "sha512": "417577f166d2808e02b7c689e0ab32c45046e2b1a98b910609c12c5df777b31789342020d7f899e6189bdbdadb64023242373335d9375b5e8c9e688d4c8df4e1",
          "sha256": "b1d3f42844a34527a6e3cefd2d26963588567955d955149755d158aabd807626",
          "sha1": "d72cc8a160edacbb8b72b9de3933b923fdfba5c2",
          "md5": "d193e14d83654cc46e5bdf278902c10c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.1-2.2.3.2510.5-sources.jar",
          "url": "factory_api-fabric-1.21.1-2.2.3.2510.5-sources.jar",
          "size": 248891,
          "sha512": "bb6e37a6879bf6c824928c9f0b3f31db20c86a87f6db6385ea8098da290bb843291888a0bc3a0e8b46e939bfce3b65b0f0014c87a9c197b2463d7ce62a65dabf",
          "sha256": "b05e4666333c29d061fdc85c521e56663140c2f07c2b69ea064d695cec9064e4",
          "sha1": "b8704dc45ffb56cf4791be3fb1062b8e76f2073b",
          "md5": "59e1c3840beb98ed745e90788919932c"
        }
      ]
    }
  ]
}
