{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2513.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.3.jar",
          "size": 697343,
          "sha512": "d4aaeabf34f3460473caeb1efc0d135b2429621efffadf3ab1ce2cdafedb59c5d9f9f0af780cb359e80f9a18dae5c4e36ddc0cb58d2544c031069fa4df306fe4",
          "sha256": "4a54193d5086c1e210b3a11fc78d8148e8e672dbc2bc0d24a29650b1d37682a8",
          "sha1": "db31a9bdf26f386a23734d0f1533cc7fec97517e",
          "md5": "aeb92fba982cf78594b62009b1a9c7a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.3.jar",
          "size": 697343,
          "sha512": "d4aaeabf34f3460473caeb1efc0d135b2429621efffadf3ab1ce2cdafedb59c5d9f9f0af780cb359e80f9a18dae5c4e36ddc0cb58d2544c031069fa4df306fe4",
          "sha256": "4a54193d5086c1e210b3a11fc78d8148e8e672dbc2bc0d24a29650b1d37682a8",
          "sha1": "db31a9bdf26f386a23734d0f1533cc7fec97517e",
          "md5": "aeb92fba982cf78594b62009b1a9c7a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.3-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.3-sources.jar",
          "size": 250442,
          "sha512": "590cf56a289bfdcda8c5468af2c34b1c2516e3acf672d5e8c934aaac20132e3e7ed417640cc9e2d1f8e6df5db93ec24eec3e5eb722b98b5da23c64f88a761e62",
          "sha256": "af48edf962d61148a79ca0d046f627f7e5d1c1b2665c98656584a1c2a4736cff",
          "sha1": "d8c2fe132a06f747db30337e3ccc6e66a020aff3",
          "md5": "fa82c66888b804b3ec70e5dfa25192c7"
        }
      ]
    }
  ]
}
