{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.24.jar",
          "size": 375924,
          "sha512": "ffe834b5c63695554e211076162acfb9684030868932aaaa68354d9097ec416527e3938b291eba966ea7418115405e4df27c28315b9bb822f3aee24607192ba4",
          "sha256": "d078976fe475a11b65308db3afb93cc5f3a0723e785919848b00669885e94659",
          "sha1": "75bf817c2f990cc7c8a12d22f7d2f0a962e34f9c",
          "md5": "b224775d04f83934c7db1418921ec82b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.24.jar",
          "size": 375924,
          "sha512": "ffe834b5c63695554e211076162acfb9684030868932aaaa68354d9097ec416527e3938b291eba966ea7418115405e4df27c28315b9bb822f3aee24607192ba4",
          "sha256": "d078976fe475a11b65308db3afb93cc5f3a0723e785919848b00669885e94659",
          "sha1": "75bf817c2f990cc7c8a12d22f7d2f0a962e34f9c",
          "md5": "b224775d04f83934c7db1418921ec82b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.24-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.24-sources.jar",
          "size": 197594,
          "sha512": "990daca028f85714d77e79a79cc2f4efffa2d6100d19fd8f77710aa24b2c4db0980ff2808b4640a0a66828b80fd0d66c6157588b570b763e1f57507343f06242",
          "sha256": "72a277443b13a9ee69726b9a91cdfc3c0b66dc104c94a8fbd662a7ed1d5fb9f5",
          "sha1": "06fe65a0efc4c2c6a270a14f9d0f78e9ac180985",
          "md5": "d69f2f264b159fde21d750d09a972316"
        }
      ]
    }
  ]
}
