{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2510.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.6.jar",
          "size": 513687,
          "sha512": "d76c2ef1a75e98988278db2c9fa4eb34c0414da2845c6a77f2e46c150d161f5c839eefc1c12fbbbd9bd8715e2031b39b5602fa5b6bd8e18cb8f6a74da4de9f5f",
          "sha256": "68cbd0877176fd1747ad866b036a088c66af43d005d4a5f0f0b7536aeb53d0d2",
          "sha1": "ed247a2da8aea153b3884302d10c60357238fb3c",
          "md5": "8d9d042c3798a312551e64dda4bf376f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.6.jar",
          "size": 513687,
          "sha512": "d76c2ef1a75e98988278db2c9fa4eb34c0414da2845c6a77f2e46c150d161f5c839eefc1c12fbbbd9bd8715e2031b39b5602fa5b6bd8e18cb8f6a74da4de9f5f",
          "sha256": "68cbd0877176fd1747ad866b036a088c66af43d005d4a5f0f0b7536aeb53d0d2",
          "sha1": "ed247a2da8aea153b3884302d10c60357238fb3c",
          "md5": "8d9d042c3798a312551e64dda4bf376f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2510.6-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2510.6-sources.jar",
          "size": 250726,
          "sha512": "cb0e20aeb6bbf9220a1ec0b8556db28d3362520d1bf50bfdc44978d223312d4f7eaf7f9052dd05e989863b08a4bdafafff8b059403b0085906f3d43c731844be",
          "sha256": "bc57ffe0d09c3606110dfa97836f39532ccf3f85b6961b268bcb19ce4264895b",
          "sha1": "cbbfdec30c8059368ce386815d74804d5c235033",
          "md5": "ba725b4da09363041be77712c3f132fb"
        }
      ]
    }
  ]
}
