{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2516.1.jar",
          "size": 510358,
          "sha512": "63f88a0ca6b5b08a704f4117b08757251dc4db6878dd46c4176054f7fd823b667743103f8f0abe20f3646ce1f7052a509b45c5f8c0e356da19b53a1275be5e39",
          "sha256": "46597e59f042fb188fea0bd26186ba1b8bc0a32040edb041fa87dffcee66dbbd",
          "sha1": "ef2e4c93fc3d1de43db4f92c32f7d68157b9c4ea",
          "md5": "50cc91637f95939c9ecdc658d887068f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2516.1.jar",
          "size": 510358,
          "sha512": "63f88a0ca6b5b08a704f4117b08757251dc4db6878dd46c4176054f7fd823b667743103f8f0abe20f3646ce1f7052a509b45c5f8c0e356da19b53a1275be5e39",
          "sha256": "46597e59f042fb188fea0bd26186ba1b8bc0a32040edb041fa87dffcee66dbbd",
          "sha1": "ef2e4c93fc3d1de43db4f92c32f7d68157b9c4ea",
          "md5": "50cc91637f95939c9ecdc658d887068f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2516.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2516.1-sources.jar",
          "size": 253317,
          "sha512": "e397846b7589f76c41b602fe406323ff24821320c5d2d453ff0134d1b275e0403da809456932541e887bd91c0e8fefd6ada44faadb7ecc0138078d7b42b5d10a",
          "sha256": "2ef5a72c747e04b234dda569e10d820afb974287d73c001ddb8790bad70020e5",
          "sha1": "f9720ac9368fb923e37dbc497b97d8eb2ef85872",
          "md5": "01cd4a8b52c1e084c8cf3fa6289693af"
        }
      ]
    }
  ]
}
