{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.20.4-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3.2516.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.3.jar",
          "size": 644284,
          "sha512": "730d85eee767ed20b1aa9df0b7af7c3f68c29b074ad4a9e2c779fae60b41cea8e1599be81be108c20c1364a0f098ce557842b0b032c0131724924cf36f20b888",
          "sha256": "18931cb4e08c4c285c0978508f56bbe6803997713a5ea5d64b84cbffb2f2dd4c",
          "sha1": "0311c9a0d18cde39c43867d87061140b6ed6c431",
          "md5": "6f8e170afecd627d8d7f1c01d50fa37d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3.2516.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.3.jar",
          "size": 644284,
          "sha512": "730d85eee767ed20b1aa9df0b7af7c3f68c29b074ad4a9e2c779fae60b41cea8e1599be81be108c20c1364a0f098ce557842b0b032c0131724924cf36f20b888",
          "sha256": "18931cb4e08c4c285c0978508f56bbe6803997713a5ea5d64b84cbffb2f2dd4c",
          "sha1": "0311c9a0d18cde39c43867d87061140b6ed6c431",
          "md5": "6f8e170afecd627d8d7f1c01d50fa37d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.3-sources.jar",
          "size": 585563,
          "sha512": "d363b70c4c00b3693e83e869d8e7ac2d720b9ac7915cdc6183c5b273fd42f03a3d9170c5346f5be83708629f1042feabf619ba1959e66c73eb266cb0e04abf4b",
          "sha256": "813c6827c325e99b0b5320539637bfa7636d90497ea74bc74ca179c023f97f3b",
          "sha1": "6fbdf5f15c59eff505999dbf51c689804f0950f7",
          "md5": "9c1b2332ce07906d8e5f5a5c19fece74"
        }
      ]
    }
  ]
}
