{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2500.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.6.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.6.jar",
          "size": 353550,
          "sha512": "db3d6640940f0f41fddbd8489e7d11ccc9086ab37bcab1a42ce56da4ca6fa0adb00454757a339fdb7cbb7f80aff2b36e15489f7a7a6452986a178e9bfb9c86f2",
          "sha256": "4b1ce9091bd3d764d352da2ec002c09c629555ec1775b60fdf2933b21b528723",
          "sha1": "618ca84eaa2881067025ad4fb70c64274b1cdc3d",
          "md5": "817cf2d966b76a68a4ecb5410091c209"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.6.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.6.jar",
          "size": 353550,
          "sha512": "db3d6640940f0f41fddbd8489e7d11ccc9086ab37bcab1a42ce56da4ca6fa0adb00454757a339fdb7cbb7f80aff2b36e15489f7a7a6452986a178e9bfb9c86f2",
          "sha256": "4b1ce9091bd3d764d352da2ec002c09c629555ec1775b60fdf2933b21b528723",
          "sha1": "618ca84eaa2881067025ad4fb70c64274b1cdc3d",
          "md5": "817cf2d966b76a68a4ecb5410091c209"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.6-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.6-sources.jar",
          "size": 193364,
          "sha512": "ddd0ef6cc318093fc099618d8cb06d2a29a9b7bbe62a538b5c4b777044b1cb37813ac953ab348ef334dad13e0dd5b04678df0bb0f258d91e0d853c139ca186e9",
          "sha256": "6f5c1cdea2236a10e13a7a27552a6ab6cab85866b5a67c6f84479b763094db0a",
          "sha1": "45b1410e4710cd05834555a234d8449b767b12ce",
          "md5": "cbb4f60b7b4534b9d953b094a8780d2e"
        }
      ]
    }
  ]
}
