{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.5-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2516.0.jar",
          "size": 18293833,
          "sha512": "9214f39f5efa54e79fc56d8a69faba70d23eeb68f1951480d25605c17caf3867dd966e558fad38f04ba466bcd7ae7180d512de1d063f17206941ce381ab9032c",
          "sha256": "b6f8fe543deef0c8ee32388bf08a6b2773e370a6c25610149981d2fd3c1771ee",
          "sha1": "91e5e887b6a6c3b41243fb4c4078bec60ee63dd2",
          "md5": "329cc18b43b34b84f2fea3ab20c7c2b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2516.0.jar",
          "size": 18293833,
          "sha512": "9214f39f5efa54e79fc56d8a69faba70d23eeb68f1951480d25605c17caf3867dd966e558fad38f04ba466bcd7ae7180d512de1d063f17206941ce381ab9032c",
          "sha256": "b6f8fe543deef0c8ee32388bf08a6b2773e370a6c25610149981d2fd3c1771ee",
          "sha1": "91e5e887b6a6c3b41243fb4c4078bec60ee63dd2",
          "md5": "329cc18b43b34b84f2fea3ab20c7c2b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2516.0-sources.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2516.0-sources.jar",
          "size": 17434403,
          "sha512": "c6d333467c64b1855e21cc9ad7abe1d30d6c406bc7d9255264b8c530efa962349e76c854152b57098c32d385ecd6cf8832da9abd35b2cd318f6619da38ba0875",
          "sha256": "745a395f19bace14ee2fd8fc217d114e37ef6601628a5c5b4021978c683bb01a",
          "sha1": "64b5eaa6a87bf2796fb60d36f040c4aa1de18ceb",
          "md5": "7e99b2f0585d9e2c4ebbff06e6b9ea6b"
        }
      ]
    }
  ]
}
