{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge-1.21.4",
    "version": "2.2.2500.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.0.jar",
          "size": 357089,
          "sha512": "74b7708e7ee72af96ca64c610ffedbd166115cb16cc0e8ee17cc331a4aa648a30d6b4e1fb995a74dc78c8fcad2149fc44389befb488e64fd28c4204c9d7f5360",
          "sha256": "80efd5471bbc753efd9fede275d21d05585642c437275e7b078b94c6c9bb2262",
          "sha1": "cf1e0bcd5b86e5bd5c57e1ddc883eea9c42819c3",
          "md5": "190fe4f336a3bb4f170575f3f5ee1b98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.0.jar",
          "size": 357089,
          "sha512": "74b7708e7ee72af96ca64c610ffedbd166115cb16cc0e8ee17cc331a4aa648a30d6b4e1fb995a74dc78c8fcad2149fc44389befb488e64fd28c4204c9d7f5360",
          "sha256": "80efd5471bbc753efd9fede275d21d05585642c437275e7b078b94c6c9bb2262",
          "sha1": "cf1e0bcd5b86e5bd5c57e1ddc883eea9c42819c3",
          "md5": "190fe4f336a3bb4f170575f3f5ee1b98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.0-sources.jar",
          "size": 190989,
          "sha512": "46a70e6ea4d75419b3aece7d7e911931de400152fa491a5ccada4c258516fbaa6b8ac072e485f3ccdf9cb7a02ea6235b3d61b43a9cd43b79cb531e19277fd73b",
          "sha256": "2e92f501fea4c00f1f9c5cb346d6167d53ec26639f9eeabf61fcde0c9852dee1",
          "sha1": "10740fb545da1e7f39ba31a8eced9d394dbe9978",
          "md5": "7409a753ffc53ba1991de30f9b4ece5a"
        }
      ]
    }
  ]
}
