{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.8.0.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2514.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2514.1.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2514.1.jar",
          "size": 18264472,
          "sha512": "b3c2e3fb54662e050fa426f2db4acf93bc6788d7fcf080e5e3bbfcba718be112e815cb2dd193e98e28df2045dcf768e8a15976593130eaea9cec7ecbbe2a26cd",
          "sha256": "b9a98ae923fdc2b4f36d36a992c17103e1bd586a783af9de090dbc395f696a26",
          "sha1": "1cd43a69fea8c03c0b1b082a82c966ac3bf3c348",
          "md5": "4cb0484bff24ede1b929f5adc3723a57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2514.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2514.1.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2514.1.jar",
          "size": 18264472,
          "sha512": "b3c2e3fb54662e050fa426f2db4acf93bc6788d7fcf080e5e3bbfcba718be112e815cb2dd193e98e28df2045dcf768e8a15976593130eaea9cec7ecbbe2a26cd",
          "sha256": "b9a98ae923fdc2b4f36d36a992c17103e1bd586a783af9de090dbc395f696a26",
          "sha1": "1cd43a69fea8c03c0b1b082a82c966ac3bf3c348",
          "md5": "4cb0484bff24ede1b929f5adc3723a57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2514.1-sources.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2514.1-sources.jar",
          "size": 17432256,
          "sha512": "f98b5f337d43356489e385a9cb45757992338c84aa543fcb86d71b16f862294f5de8750f4a2f5c774bafceaa02401ee85f98569d71e01c4ce9e477a0ee269fa4",
          "sha256": "8194bdb1d4692815ec18f772f80c17b7e0536b05ff8d82918fd3343fd276014c",
          "sha1": "1fd94d17048b3baa87eb3c21bc26b443cfecd743",
          "md5": "d9995604b0e8e422762eba3ab900918a"
        }
      ]
    }
  ]
}
