{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.13.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.13.jar",
          "size": 370044,
          "sha512": "ca877d1495005aa095a87fa773430a82f0855a7b4fc4eff716df25f7d1b40b4781d310345ae8f626b54efc90ecb84fbffc75aa60bc5bfe70c5a8250c0cca2065",
          "sha256": "7b494fdf5028d8221edcbd502144802ec16b02309b4cff3e4ea6fb9b94aece24",
          "sha1": "ffbf14eb0c9ca1457c5f45d6bd623eaf49eddc8b",
          "md5": "f5ad3a5a43451c739252a61dea100a03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.13.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.13.jar",
          "size": 370044,
          "sha512": "ca877d1495005aa095a87fa773430a82f0855a7b4fc4eff716df25f7d1b40b4781d310345ae8f626b54efc90ecb84fbffc75aa60bc5bfe70c5a8250c0cca2065",
          "sha256": "7b494fdf5028d8221edcbd502144802ec16b02309b4cff3e4ea6fb9b94aece24",
          "sha1": "ffbf14eb0c9ca1457c5f45d6bd623eaf49eddc8b",
          "md5": "f5ad3a5a43451c739252a61dea100a03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.13-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.13-sources.jar",
          "size": 197416,
          "sha512": "e66868e34560165f234c5d135ff5425a123c1022b38ffbe96ca6528e3e878a40eefa2e95c430d751a0613800eb66b0d8ca3206a37278cfaf507493b1f2d889cf",
          "sha256": "f48cf3372823ab617ca3c2663c0d915a8e50060186f77390dda640aee4e3fcc3",
          "sha1": "5186989310bb14ab58cfa6b87805db9474f11d24",
          "md5": "0912bfef984244b2c042ddfbe3683b43"
        }
      ]
    }
  ]
}
