{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "26.1.2-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.9.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.9.jar",
          "size": 561253,
          "sha512": "3cba574994555f5be95a588501fea351b8777b1f73dc0f94d65eae16f063a13d2d2f43de93a27f06ee1541a9d3e252c21477c53d9e9a9a3365feee97452228b2",
          "sha256": "4a17676d1a85a7f118d58294be46d0cccf22fad1b4c306fe38eb180bd9764ced",
          "sha1": "30acd0c23eece24e27369f8cbdf50d9445f767fa",
          "md5": "c9bb996846b0cb8e8530351a12a53adc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.9.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.9.jar",
          "size": 561253,
          "sha512": "3cba574994555f5be95a588501fea351b8777b1f73dc0f94d65eae16f063a13d2d2f43de93a27f06ee1541a9d3e252c21477c53d9e9a9a3365feee97452228b2",
          "sha256": "4a17676d1a85a7f118d58294be46d0cccf22fad1b4c306fe38eb180bd9764ced",
          "sha1": "30acd0c23eece24e27369f8cbdf50d9445f767fa",
          "md5": "c9bb996846b0cb8e8530351a12a53adc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-26.1.2-2.2.9-sources.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.9-sources.jar",
          "size": 256868,
          "sha512": "5a578b8c86722ce0e9b349f9c4de96ec5cba26c050a121b5caf7792d7034cb73a9fd1cfc3095e85dbbfbc57b202a968abba2a3dc84596e15631e9f81cd01e10a",
          "sha256": "9330791cc37fb6defd53170c709d2265a2206950aff125bcb3d2cfde39fd04ce",
          "sha1": "d64779daa352406c44f504ca0a2022f0adfd78a0",
          "md5": "51265887c0068258478aa22c9255d2e8"
        },
        {
          "name": "factory_api-neoforge-26.1.2-2.2.9-sources.jar",
          "url": "factory_api-neoforge-26.1.2-2.2.9-sources.jar",
          "size": 256868,
          "sha512": "5a578b8c86722ce0e9b349f9c4de96ec5cba26c050a121b5caf7792d7034cb73a9fd1cfc3095e85dbbfbc57b202a968abba2a3dc84596e15631e9f81cd01e10a",
          "sha256": "9330791cc37fb6defd53170c709d2265a2206950aff125bcb3d2cfde39fd04ce",
          "sha1": "d64779daa352406c44f504ca0a2022f0adfd78a0",
          "md5": "51265887c0068258478aa22c9255d2e8"
        }
      ]
    }
  ]
}
