{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2515.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2515.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2515.1.jar",
          "size": 509990,
          "sha512": "a28f36bcf458a183abcf70364ddc2b8a32c703bc167bdb9e49c97fae7154c518267db9e03300cf9853d5b67d3fbb4950f5ca2f3d615a2c08195438dc28447439",
          "sha256": "94ad274685b8d946122e4421d05a3b3780efb3f7df7b8d96c375d86749e0cd92",
          "sha1": "381283aded19467bbf784a05f6c80b8686271f3b",
          "md5": "f3d89b848995e7ed7106addbb8ae3941"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2515.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2515.1.jar",
          "size": 509990,
          "sha512": "a28f36bcf458a183abcf70364ddc2b8a32c703bc167bdb9e49c97fae7154c518267db9e03300cf9853d5b67d3fbb4950f5ca2f3d615a2c08195438dc28447439",
          "sha256": "94ad274685b8d946122e4421d05a3b3780efb3f7df7b8d96c375d86749e0cd92",
          "sha1": "381283aded19467bbf784a05f6c80b8686271f3b",
          "md5": "f3d89b848995e7ed7106addbb8ae3941"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2515.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2515.1-sources.jar",
          "size": 253094,
          "sha512": "068f6c4d4409fc95bf444fb0a4b2939a99a344d51302a93ddffc9b6bb688a9d515e37321a66e1fe3b5b6d294bc4545bd132d8e7075b01b63f95a07ab76d504b3",
          "sha256": "f6a243c3bda40b43be70d0ab03f61a50f856eda8444ee2d66e0acbde51ec086d",
          "sha1": "38cb7231ffae5fe22eb7bcdc1ec1293a55617817",
          "md5": "63e17fe91907ff09b689d4110ed3758d"
        }
      ]
    }
  ]
}
