{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.0.jar",
          "size": 18296757,
          "sha512": "fd5b3a8cf7b6b045bd90a755258e5b679cbab70b9462378ca5660c35de3db26df028cbb8984ace15db605000cbdc84bfca3af35cd9d0549edf73be79af16fec7",
          "sha256": "cec2a11ec37913590c30c30bcb3f2a05294a20d8eb6bf2e9013f7dd0a861a183",
          "sha1": "0272938859c288e3f982a417b422816e28458838",
          "md5": "bb866c5510d9b5e3ef182c6e2c00cecb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.0.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.0.jar",
          "size": 18296757,
          "sha512": "fd5b3a8cf7b6b045bd90a755258e5b679cbab70b9462378ca5660c35de3db26df028cbb8984ace15db605000cbdc84bfca3af35cd9d0549edf73be79af16fec7",
          "sha256": "cec2a11ec37913590c30c30bcb3f2a05294a20d8eb6bf2e9013f7dd0a861a183",
          "sha1": "0272938859c288e3f982a417b422816e28458838",
          "md5": "bb866c5510d9b5e3ef182c6e2c00cecb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2516.0-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2516.0-sources.jar",
          "size": 17434253,
          "sha512": "cc4be233f1a8beb4d7d8edded91e37cb91b96e84a304020fad435025e11b41d64cc8af08802e0ab23e246784efb14f8e1a37641f8797991a874d1ff091bc6252",
          "sha256": "8ae50dcaba4e09c6925cd347e6c0c56f8d62cc69e71495915df39426e750b983",
          "sha1": "9c91d8947f63b20006d0cf85ab64bf31afd9448f",
          "md5": "31c36f2641ee69fe1316542f8d9b8e67"
        }
      ]
    }
  ]
}
