{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.3.jar",
          "size": 370561,
          "sha512": "1ad5d1940d9d1089b6bd642a39b268dc59e24815fdf69839f0581e901065a398f6916eafcd995d9b4573432e192e8e3699b626bdbd5d8b549ae91cd7bcfcdb51",
          "sha256": "9e3c28146ee69ce2564ad48e3c7ab4b1f6b29a042703041682bb39dadefdccf4",
          "sha1": "c9eab951092a71180ac78d87aad48eb8f8125d3b",
          "md5": "145f822ca3c1d3692f0d07b16257a652"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.3.jar",
          "size": 370561,
          "sha512": "1ad5d1940d9d1089b6bd642a39b268dc59e24815fdf69839f0581e901065a398f6916eafcd995d9b4573432e192e8e3699b626bdbd5d8b549ae91cd7bcfcdb51",
          "sha256": "9e3c28146ee69ce2564ad48e3c7ab4b1f6b29a042703041682bb39dadefdccf4",
          "sha1": "c9eab951092a71180ac78d87aad48eb8f8125d3b",
          "md5": "145f822ca3c1d3692f0d07b16257a652"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.3-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.3-sources.jar",
          "size": 195066,
          "sha512": "6cb163fec2095f32c04506a85fcd3d7ebf8c81347e53bab0860d19e5c61fcf9493e8d982bdb96b3d1adbd8044fd885976365f863f7d2d586597201d2db3fd4aa",
          "sha256": "5ca3815e3c1e47fe87669a80964f4a12d8a2301fd2796690abdefdb91e4e9ee7",
          "sha1": "8919ea21996c11c31e496e6bfc9db39dceadc11c",
          "md5": "41df70142c1c72a5e72680dc9a7a2f2f"
        }
      ]
    }
  ]
}
