{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.8.0.2512.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.2.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.2.jar",
          "size": 18241599,
          "sha512": "81653d38a0926820e8dc051e1837960b12354f8fea41bfce0a001c0bf7aeb1061efa4ecfb4453a513005ece203e02710569c2b64946ceb7015c843ed6b4f19ca",
          "sha256": "869c5ecd168901e74bde57b65ab590d9236ae278304ad5860fb2c1a2c002a125",
          "sha1": "8e7ab31ef226575bfd9e4f6044c0082264ed80fa",
          "md5": "9b71114570558547c3121e185ac9eb17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.2.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.2.jar",
          "size": 18241599,
          "sha512": "81653d38a0926820e8dc051e1837960b12354f8fea41bfce0a001c0bf7aeb1061efa4ecfb4453a513005ece203e02710569c2b64946ceb7015c843ed6b4f19ca",
          "sha256": "869c5ecd168901e74bde57b65ab590d9236ae278304ad5860fb2c1a2c002a125",
          "sha1": "8e7ab31ef226575bfd9e4f6044c0082264ed80fa",
          "md5": "9b71114570558547c3121e185ac9eb17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.2-sources.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.2-sources.jar",
          "size": 17412744,
          "sha512": "af50f695a63b2f2777069da1187a7464a20cf5c02070406e4b7f0a64dd847556fe86f9d46c7cf7af6467547a5bb656d886135aa589f5161c2f6957dd791261bb",
          "sha256": "6ad1e05b893081f1865315958baa4599f77320b2a4ebd1da5018ef561afb236a",
          "sha1": "5ff1dfc731ede6d7e0c4b8e9a4ca9efc4166d616",
          "md5": "8dc71a6be29f6d8d0ba0667c47387526"
        }
      ]
    }
  ]
}
