{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.10-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.9.jar",
          "url": "factory_api-forge-1.21.10-2.2.9.jar",
          "size": 1156922,
          "sha512": "04df32348cf7300ed4ab997b283e204b3a88f2371ed25841b7940a8833946c1912b3495ac208aad9636ecbc3ec64f8a1c41faef4e2babc57397e523e540e9579",
          "sha256": "b40f9a437471e92b13e4076a60ff746bea743d390262acf652f6414566c8c8f1",
          "sha1": "e616f10e04af9836952990d9bc1c6421d65d74d5",
          "md5": "85ff57ae8e16a2b8a3b8e7ed83a15e77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.10-60.0.0"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.9.jar",
          "url": "factory_api-forge-1.21.10-2.2.9.jar",
          "size": 1156922,
          "sha512": "04df32348cf7300ed4ab997b283e204b3a88f2371ed25841b7940a8833946c1912b3495ac208aad9636ecbc3ec64f8a1c41faef4e2babc57397e523e540e9579",
          "sha256": "b40f9a437471e92b13e4076a60ff746bea743d390262acf652f6414566c8c8f1",
          "sha1": "e616f10e04af9836952990d9bc1c6421d65d74d5",
          "md5": "85ff57ae8e16a2b8a3b8e7ed83a15e77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.9-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.9-sources.jar",
          "size": 256913,
          "sha512": "282575c68bbecdd1ac9f7430ccee9798a884ccdfcc75cbc52bf77fee6e2e66655cda55b8f53cccbde028bc4432eb4458c1665b71a0ac0f7083763b2f4973797a",
          "sha256": "e76c80a31c7f8988bd2e05825cb03be1b8526f7a7324993dd2299d384bb939f4",
          "sha1": "96d8e568c54c3f67f94de5f527db0c5ea2882cbe",
          "md5": "e69dcd8314f1b46a7920ec0e7b6a468a"
        },
        {
          "name": "factory_api-forge-1.21.10-2.2.9-sources.jar",
          "url": "factory_api-forge-1.21.10-2.2.9-sources.jar",
          "size": 256913,
          "sha512": "282575c68bbecdd1ac9f7430ccee9798a884ccdfcc75cbc52bf77fee6e2e66655cda55b8f53cccbde028bc4432eb4458c1665b71a0ac0f7083763b2f4973797a",
          "sha256": "e76c80a31c7f8988bd2e05825cb03be1b8526f7a7324993dd2299d384bb939f4",
          "sha1": "96d8e568c54c3f67f94de5f527db0c5ea2882cbe",
          "md5": "e69dcd8314f1b46a7920ec0e7b6a468a"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.10-60.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.10-2.2.9.jar",
          "url": "factory_api-forge-1.21.10-2.2.9.jar",
          "size": 1156922,
          "sha512": "04df32348cf7300ed4ab997b283e204b3a88f2371ed25841b7940a8833946c1912b3495ac208aad9636ecbc3ec64f8a1c41faef4e2babc57397e523e540e9579",
          "sha256": "b40f9a437471e92b13e4076a60ff746bea743d390262acf652f6414566c8c8f1",
          "sha1": "e616f10e04af9836952990d9bc1c6421d65d74d5",
          "md5": "85ff57ae8e16a2b8a3b8e7ed83a15e77"
        }
      ]
    }
  ]
}
