{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2500.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.8.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.8.jar",
          "size": 364536,
          "sha512": "e160d1a59882d9aced9f2926992d43f6a0039f15a2289b2a4e978ddf94bc306c1ac2d86842dc022a0907a38b1ff5a37255f1158675107a3b301b4075d7ec8316",
          "sha256": "aa6506238f1c8439b7facea246bb607056d9481a512e846989d091b3a2803751",
          "sha1": "dc97c1fa1f402a6fd505aecb58ec13acc4e4cc54",
          "md5": "c54a262f2134b2ad16f889d8e81d4953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.8.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.8.jar",
          "size": 364536,
          "sha512": "e160d1a59882d9aced9f2926992d43f6a0039f15a2289b2a4e978ddf94bc306c1ac2d86842dc022a0907a38b1ff5a37255f1158675107a3b301b4075d7ec8316",
          "sha256": "aa6506238f1c8439b7facea246bb607056d9481a512e846989d091b3a2803751",
          "sha1": "dc97c1fa1f402a6fd505aecb58ec13acc4e4cc54",
          "md5": "c54a262f2134b2ad16f889d8e81d4953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.8-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.8-sources.jar",
          "size": 193554,
          "sha512": "382423cf8cf4cabde0e49dbc731a6c1930d05e510a9ba6620a6d97fa850f241fb106dcd8a53da57ecd1053da8956729c9a9a18614e9dbbba7a7fa9de46c3943c",
          "sha256": "bddfb9b6202fe06d6a88f2c9bb7edf0b69585d708568f09d4a1891cae9ca2ac6",
          "sha1": "7a61167b93cdcb5c526446f0001f6057d033dc4e",
          "md5": "1e52b78d28368e00fbca21f39ec76755"
        }
      ]
    }
  ]
}
