{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.3-1.8.0.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2514.0.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2514.0.jar",
          "size": 18289562,
          "sha512": "bb54bbc48edaa7d5234ce4ae7e954307c9e011cc25fbd537371e0cfc3220aaeddb45733cba2cc5935aba455b9f6a8f3ddbd1b5298da312e29f56c5b3a5aa4d6c",
          "sha256": "48558a4dc5f0b28ce0a193ff21ae818a271c86aede52b418c73c2eb2b1ac5ba2",
          "sha1": "93ab5011da06b8e987c55c7ef0047d24e5bb3e69",
          "md5": "d0fb1e90ee0d9335f0147c0e6bf7854f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2514.0.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2514.0.jar",
          "size": 18289562,
          "sha512": "bb54bbc48edaa7d5234ce4ae7e954307c9e011cc25fbd537371e0cfc3220aaeddb45733cba2cc5935aba455b9f6a8f3ddbd1b5298da312e29f56c5b3a5aa4d6c",
          "sha256": "48558a4dc5f0b28ce0a193ff21ae818a271c86aede52b418c73c2eb2b1ac5ba2",
          "sha1": "93ab5011da06b8e987c55c7ef0047d24e5bb3e69",
          "md5": "d0fb1e90ee0d9335f0147c0e6bf7854f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.3-1.8.0.2514.0-sources.jar",
          "url": "legacy-neoforge-1.21.3-1.8.0.2514.0-sources.jar",
          "size": 17432574,
          "sha512": "a346be1bc1ddb12a03d6b8e16c8ab045cdc8b11147df104000f15728c0df107955afce778ee0389b593efb252b540642c175043daf8e26fbe0d6c2ff64fe6089",
          "sha256": "c7850e09f92c75e0f07bef6aaa605819982a7bf3412ed1569091bc86993150e9",
          "sha1": "a29866709989bbc2eae631de647dc1282cb3dac2",
          "md5": "9b4c65d736ec5ed47a7e9e655af42dd6"
        }
      ]
    }
  ]
}
