{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.4-2.2.2500.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2500.1.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2500.1.jar",
          "size": 391390,
          "sha512": "128cd5d0bb642eeef7524152b9d5fa0d55413dd6ceb7e7d38530dcdd2c2575c89563f149fd1fa18fc10081abf47ee88707ffa61714868928f075b59f5e130c0d",
          "sha256": "f3a44715f46133ed985fb85c8e2826a632ea4a5046978912b8cb263c95b3283c",
          "sha1": "c3e1a075f978e304f9b90f9dafd444cdefcb3b76",
          "md5": "c076b552af03a5ccd8526ca917321972"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2500.1.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2500.1.jar",
          "size": 391390,
          "sha512": "128cd5d0bb642eeef7524152b9d5fa0d55413dd6ceb7e7d38530dcdd2c2575c89563f149fd1fa18fc10081abf47ee88707ffa61714868928f075b59f5e130c0d",
          "sha256": "f3a44715f46133ed985fb85c8e2826a632ea4a5046978912b8cb263c95b3283c",
          "sha1": "c3e1a075f978e304f9b90f9dafd444cdefcb3b76",
          "md5": "c076b552af03a5ccd8526ca917321972"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2500.1-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2500.1-sources.jar",
          "size": 190291,
          "sha512": "f9f7f6a925425bd6bedd79cd3df8ff1e7d5d90fecd6681eff3868330bc81cf20dc866b7043db6ebabe0649a58b354b4cc433b865754ea4dbbbe48013d48e3c7e",
          "sha256": "2855e19348164799183e07663d25e6b5074e7e608761d1a82d7f6bd029fcd808",
          "sha1": "67f758805d777eeaf91646d227b20acd16b49053",
          "md5": "39acd401cfb1bdec15c0184551b05daf"
        }
      ]
    }
  ]
}
