{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2510.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.0.jar",
          "size": 497366,
          "sha512": "36b6d275361eb60a9c2468396cd8332b9b42d8b83f7163f0f759266113d60396afc68065b2cae746fb00983a8780967db43485bdf071549c1fcab5590dceb42b",
          "sha256": "dd9d81aa525e6af4ab3325a6c76f4d6c62c256bfbf2839d24eb86a300c3db7b4",
          "sha1": "87f1f186306608d8fd97cbb4826f163b98730b77",
          "md5": "e46ab67fd2a31a1eeac540f0285eecf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.0.jar",
          "size": 497366,
          "sha512": "36b6d275361eb60a9c2468396cd8332b9b42d8b83f7163f0f759266113d60396afc68065b2cae746fb00983a8780967db43485bdf071549c1fcab5590dceb42b",
          "sha256": "dd9d81aa525e6af4ab3325a6c76f4d6c62c256bfbf2839d24eb86a300c3db7b4",
          "sha1": "87f1f186306608d8fd97cbb4826f163b98730b77",
          "md5": "e46ab67fd2a31a1eeac540f0285eecf1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.0-sources.jar",
          "size": 250223,
          "sha512": "be709b5c4136db6094c0bd02d642c3fcba7b4937aecf7c8c0e85bf46b9577d9bae4e66c2ae9235388b984faf2ecb87f42d7faa2284a84e3d0081f1afe9bdf1a5",
          "sha256": "8cb53eab80942bfb840d81032058b54bef299a1c711480d07981a73353d20bd6",
          "sha1": "19d731b40f3f86a9b6f19a9bde0dd218618ee4ab",
          "md5": "b8c19e46f4ae6147cc0eb3c5053c80e7"
        }
      ]
    }
  ]
}
