{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.11-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.2.jar",
          "size": 561180,
          "sha512": "e26ed3b9e43a84628f8fe6f63733accec6142c598fd453d208fc6d4dedf4e4d5a5d9e03615878edf40a3e910f44600f5e86c481fa4cec27bc8a3a7fb45463f06",
          "sha256": "ac6b5b15e2f54173e726e2c3db3c8ea74faea4f8ce97377890e46ca585709a7c",
          "sha1": "b007067b9daaaddc336f2382209e58e16cb06361",
          "md5": "a0f923d26c0de8b649efff49fe346c7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.2.jar",
          "size": 561180,
          "sha512": "e26ed3b9e43a84628f8fe6f63733accec6142c598fd453d208fc6d4dedf4e4d5a5d9e03615878edf40a3e910f44600f5e86c481fa4cec27bc8a3a7fb45463f06",
          "sha256": "ac6b5b15e2f54173e726e2c3db3c8ea74faea4f8ce97377890e46ca585709a7c",
          "sha1": "b007067b9daaaddc336f2382209e58e16cb06361",
          "md5": "a0f923d26c0de8b649efff49fe346c7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.2-sources.jar",
          "size": 256716,
          "sha512": "2da14fc625bb595258db0c63773740b7fce89e09c86ae246c620555ad4ea8db6740e0a7a23c76074d6809c7c38d69c42afcafb8392b996409a1bf25f0c9136ef",
          "sha256": "ae34d8abf294ad11f3845d4702d4e5631b2aab2ddcb33ac6db7a6d203ba0c3d3",
          "sha1": "39a8e064c9f611b41ee84dc454dc355102f2234c",
          "md5": "93d66e23e2e754c7665ffaf4dda22e09"
        },
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.2-sources.jar",
          "size": 256716,
          "sha512": "2da14fc625bb595258db0c63773740b7fce89e09c86ae246c620555ad4ea8db6740e0a7a23c76074d6809c7c38d69c42afcafb8392b996409a1bf25f0c9136ef",
          "sha256": "ae34d8abf294ad11f3845d4702d4e5631b2aab2ddcb33ac6db7a6d203ba0c3d3",
          "sha1": "39a8e064c9f611b41ee84dc454dc355102f2234c",
          "md5": "93d66e23e2e754c7665ffaf4dda22e09"
        }
      ]
    }
  ]
}
