{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.7.10.2501.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2501.0.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2501.0.jar",
          "size": 11918952,
          "sha512": "dc72ad8787bfd8df427aadf10bddaa9b272c12a325f720c96d1657f1d26d713fbb5943d5479b1aa6ec136fdd6d90298b4489f44ede81879f6f862ff5ad192015",
          "sha256": "1d226f1db2c16e6f60cdfa6f165a30e604fefc241f483279ccbf8b179f9eb8cc",
          "sha1": "9a94c3b2872315a440f211d87c32ac25f11da77d",
          "md5": "34f90f64c65550b7da5725175e9fd7f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2501.20"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2501.0.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2501.0.jar",
          "size": 11918952,
          "sha512": "dc72ad8787bfd8df427aadf10bddaa9b272c12a325f720c96d1657f1d26d713fbb5943d5479b1aa6ec136fdd6d90298b4489f44ede81879f6f862ff5ad192015",
          "sha256": "1d226f1db2c16e6f60cdfa6f165a30e604fefc241f483279ccbf8b179f9eb8cc",
          "sha1": "9a94c3b2872315a440f211d87c32ac25f11da77d",
          "md5": "34f90f64c65550b7da5725175e9fd7f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2501.0-sources.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2501.0-sources.jar",
          "size": 11127776,
          "sha512": "6f561670ccbc24bd9c50a6c705e67eb0911bc3bc61b4baa9314f306a6818163fa7e15a961326ea6b4b85ddfbb4b68d2ff780aafc02c6a2485bec2aaee976d0e9",
          "sha256": "22bb0177c0f5ea38555cb4cd06183efeab38e9d4d2da06bcbef08ca0b96b5dff",
          "sha1": "79ea41f030ca9f9030f1791f0e402caabc853854",
          "md5": "4f898f0e305c287393cb9d637fd49760"
        }
      ]
    }
  ]
}
