{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2507.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.2.jar",
          "size": 494890,
          "sha512": "82dc1c1896f37d9289fbc1b32e6fe1b2c90b5403bf504247f5dd79d4a90b8bb400a26ffee864ebdcd1cb001ef9b82e2f6b561564bc8a428ec3994936dcee4a5a",
          "sha256": "8355fd2a17ce91df5a474e547f47dd7cfd5699c2e00a1e81cde1cb114c1c249f",
          "sha1": "9af14f7800347e0915f89a49620fc6b07baf0f8a",
          "md5": "f1da2a93ed7338036f08643a244b70f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.2.jar",
          "size": 494890,
          "sha512": "82dc1c1896f37d9289fbc1b32e6fe1b2c90b5403bf504247f5dd79d4a90b8bb400a26ffee864ebdcd1cb001ef9b82e2f6b561564bc8a428ec3994936dcee4a5a",
          "sha256": "8355fd2a17ce91df5a474e547f47dd7cfd5699c2e00a1e81cde1cb114c1c249f",
          "sha1": "9af14f7800347e0915f89a49620fc6b07baf0f8a",
          "md5": "f1da2a93ed7338036f08643a244b70f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2507.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2507.2-sources.jar",
          "size": 244013,
          "sha512": "c2b9f400ab82428c783b5899db5dc08acd95ca76e2ccd829fa7b2a41ffa1c39a42af10478b80ebc306617777da1ecac256b96e463c1c8a41915f653e24abca22",
          "sha256": "8bac5050e1f7f6cd7a43d588dcae237885794bb3699abe4abc5f4ffd6e250dd3",
          "sha1": "55b342d6265c90d7dec34e006f40fd1829dace61",
          "md5": "4942fe24809bf5619058a4d4873952d3"
        }
      ]
    }
  ]
}
