{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.9.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.9.jar",
          "size": 433991,
          "sha512": "f130024eea80404c3606fa4671784ef2b85c142ce220934386f6c6556eeca40178b262b24b3d8ca20fb922eca55056b3f72b2a4e9a9a268518c3904063064886",
          "sha256": "830a54c8368d88f16aedb58efe471e79acd12128b92879ad7b9a1bcc4867dc3a",
          "sha1": "b2b7d004cc1597a07a1587da19c3be2209cdd582",
          "md5": "d91f7f7c6348069ee31c90557b9422dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.9.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.9.jar",
          "size": 433991,
          "sha512": "f130024eea80404c3606fa4671784ef2b85c142ce220934386f6c6556eeca40178b262b24b3d8ca20fb922eca55056b3f72b2a4e9a9a268518c3904063064886",
          "sha256": "830a54c8368d88f16aedb58efe471e79acd12128b92879ad7b9a1bcc4867dc3a",
          "sha1": "b2b7d004cc1597a07a1587da19c3be2209cdd582",
          "md5": "d91f7f7c6348069ee31c90557b9422dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.9-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.9-sources.jar",
          "size": 222159,
          "sha512": "d8d75a45d90c744922ef679b520a5f045619f3da184accc0e6cbdc46b7a48a1587c0e9b2cd43090a3c753a44a062f93e657ff873b54b35f2b22f82681f17076c",
          "sha256": "156060f42b0789bf44267d564c59c0654936f66819868c8af7531f7d23a1ca8d",
          "sha1": "30689a5462d8173e75e89be69014db928272e79a",
          "md5": "878f02ef2e2342a737f8cc13a835190e"
        }
      ]
    }
  ]
}
