{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3-pre.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3-pre.jar",
          "size": 509859,
          "sha512": "d860cd04ee6a36b0ac40b18bebe32b6681a91257c23a4aa3203f2915adf8ce96bd72401a133217500bd0994cee74493826a48064567cf46ef4a1d834ff0b8c35",
          "sha256": "f7b406f773b37cec30533277c38498ad93330ac2fc950551e2a28a764ebe95a3",
          "sha1": "d739b26b5fee31230e226d394e134bb7fcfab997",
          "md5": "6272085f6f4b611131c2dddf924de374"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3-pre.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3-pre.jar",
          "size": 509859,
          "sha512": "d860cd04ee6a36b0ac40b18bebe32b6681a91257c23a4aa3203f2915adf8ce96bd72401a133217500bd0994cee74493826a48064567cf46ef4a1d834ff0b8c35",
          "sha256": "f7b406f773b37cec30533277c38498ad93330ac2fc950551e2a28a764ebe95a3",
          "sha1": "d739b26b5fee31230e226d394e134bb7fcfab997",
          "md5": "6272085f6f4b611131c2dddf924de374"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3-pre-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3-pre-sources.jar",
          "size": 248543,
          "sha512": "7586ddc5ebc8bb56bedc0217b3cdc580da402cfbb5330948481b502e72b53d4831c6a50905d31d3807a1abdeb960ecd0d56feeabcecbecb942562aa24134c61b",
          "sha256": "5e4b663231e6fa02e057306b054986ffcb6dda48436c73258c3816f594694334",
          "sha1": "ecf0b42ec81c10f4b6955c57be0e53268eee2752",
          "md5": "84bc182139fbc22e6ef72da0625513a3"
        }
      ]
    }
  ]
}
