{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.3.2516.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.4.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.4.jar",
          "size": 529602,
          "sha512": "4cc5fcbfb0619b975652e836cbc9468834495b41b2e635909572c2da9764f848447b9cb90ea19a66bbc037311c368d7fa6bf8012e3b8b4a7ea04302c085be889",
          "sha256": "afcdfd57d1e83eb613242e7527b576d8da3e7aceb26342013776c5b7109b8535",
          "sha1": "4a8ce6c1284d86fd05d30bef2b57e2a48f002d89",
          "md5": "f7cae963e7f0445b60aba4b10568964f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.4.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.4.jar",
          "size": 529602,
          "sha512": "4cc5fcbfb0619b975652e836cbc9468834495b41b2e635909572c2da9764f848447b9cb90ea19a66bbc037311c368d7fa6bf8012e3b8b4a7ea04302c085be889",
          "sha256": "afcdfd57d1e83eb613242e7527b576d8da3e7aceb26342013776c5b7109b8535",
          "sha1": "4a8ce6c1284d86fd05d30bef2b57e2a48f002d89",
          "md5": "f7cae963e7f0445b60aba4b10568964f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.4-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.4-sources.jar",
          "size": 254146,
          "sha512": "8407224f3120f514677c146c8248beaa521aa77d8f265a23e4744d429fcd2366f4ae9cac4b42e0e37e6c0a118ff6936fffa58ac82735ca29902934f2ce901e26",
          "sha256": "79015b1a03994c3fb664671e37e71cfaeff0d8724138fae3e8a7e5ec6410c29e",
          "sha1": "5fc274a8efd6f6f08030533ed25c5f79b072dbf8",
          "md5": "cef6b30acbb90e033da7d878de519ed8"
        }
      ]
    }
  ]
}
