{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.9.jar",
          "size": 1156221,
          "sha512": "06ffd9dcbe170d88bb60b79864fdafa99bbb7c649076deeb360004a55d12336cdcfd4bcf353fda07bae8c281bdda71fcc6c2a01306d6963446ceced56c51ee5e",
          "sha256": "6c511dafcd54752661ce2e2815496b8afb77f8e08810d5c75d378c6b611e2040",
          "sha1": "62699f6391ce7bbd16e84f98d177cde6721ae0b4",
          "md5": "d1751de3bae63f4504a11869c72f726e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.4-54.1.3"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.9.jar",
          "size": 1156221,
          "sha512": "06ffd9dcbe170d88bb60b79864fdafa99bbb7c649076deeb360004a55d12336cdcfd4bcf353fda07bae8c281bdda71fcc6c2a01306d6963446ceced56c51ee5e",
          "sha256": "6c511dafcd54752661ce2e2815496b8afb77f8e08810d5c75d378c6b611e2040",
          "sha1": "62699f6391ce7bbd16e84f98d177cde6721ae0b4",
          "md5": "d1751de3bae63f4504a11869c72f726e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.9-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.9-sources.jar",
          "size": 256839,
          "sha512": "7f381ec2f5c5e16ea00c8a0b04d06a936181b4e8c5ab3c2d12e571a63a85cf2bd7dcf0faed5691733aa965fe0b73d807d19e7743df4471665aa681c887198bb2",
          "sha256": "7d6a0eb0a3d6974f7e41f337bb95897ec6336c6a8b00e1e96f385ac03a3bcead",
          "sha1": "853a79b1bc88269bf297dc0b9f806077a4c042e9",
          "md5": "d20a36fa72411c7015e9313aa0be33c1"
        },
        {
          "name": "factory_api-forge-1.21.4-2.2.9-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.9-sources.jar",
          "size": 256839,
          "sha512": "7f381ec2f5c5e16ea00c8a0b04d06a936181b4e8c5ab3c2d12e571a63a85cf2bd7dcf0faed5691733aa965fe0b73d807d19e7743df4471665aa681c887198bb2",
          "sha256": "7d6a0eb0a3d6974f7e41f337bb95897ec6336c6a8b00e1e96f385ac03a3bcead",
          "sha1": "853a79b1bc88269bf297dc0b9f806077a4c042e9",
          "md5": "d20a36fa72411c7015e9313aa0be33c1"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.4-54.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.9.jar",
          "size": 1156221,
          "sha512": "06ffd9dcbe170d88bb60b79864fdafa99bbb7c649076deeb360004a55d12336cdcfd4bcf353fda07bae8c281bdda71fcc6c2a01306d6963446ceced56c51ee5e",
          "sha256": "6c511dafcd54752661ce2e2815496b8afb77f8e08810d5c75d378c6b611e2040",
          "sha1": "62699f6391ce7bbd16e84f98d177cde6721ae0b4",
          "md5": "d1751de3bae63f4504a11869c72f726e"
        }
      ]
    }
  ]
}
