{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.7.2616.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.0.jar",
          "size": 560431,
          "sha512": "f5293f973af9641067d70458ea8a861a06f47b391a50ec30108d902f38dac8f338df0948f9006ac0bb3343c622421379a0caedef8f2dc5c304c7aade60dfbd03",
          "sha256": "e9299b125c409be7f7a43f8da480cc10accfa55fd5dbd4cefcfcbd6b427c0189",
          "sha1": "36626406afa12a090cfcfe33b5023e83439f0303",
          "md5": "c25d0c15bccc74aaa91d4df86f8cb455"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.0.jar",
          "size": 560431,
          "sha512": "f5293f973af9641067d70458ea8a861a06f47b391a50ec30108d902f38dac8f338df0948f9006ac0bb3343c622421379a0caedef8f2dc5c304c7aade60dfbd03",
          "sha256": "e9299b125c409be7f7a43f8da480cc10accfa55fd5dbd4cefcfcbd6b427c0189",
          "sha1": "36626406afa12a090cfcfe33b5023e83439f0303",
          "md5": "c25d0c15bccc74aaa91d4df86f8cb455"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.0-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.0-sources.jar",
          "size": 256756,
          "sha512": "004d24761c647f5660ae35c6506442645877f7a80b78cbe997bff63579221a264b8cd2acfc3eac18ca9eda9c90ae26201cc0158fcbe993613d4b9f494429ed65",
          "sha256": "c84a594418cff946f533caab518790898d6a1cf70ceece28fc5ec17cb618295f",
          "sha1": "8da1120bfe4c0a51a04e2a985655fc9f4a016242",
          "md5": "dce04a546cca2356b0c57700c37fc3fc"
        },
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2616.0-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2616.0-sources.jar",
          "size": 256756,
          "sha512": "004d24761c647f5660ae35c6506442645877f7a80b78cbe997bff63579221a264b8cd2acfc3eac18ca9eda9c90ae26201cc0158fcbe993613d4b9f494429ed65",
          "sha256": "c84a594418cff946f533caab518790898d6a1cf70ceece28fc5ec17cb618295f",
          "sha1": "8da1120bfe4c0a51a04e2a985655fc9f4a016242",
          "md5": "dce04a546cca2356b0c57700c37fc3fc"
        }
      ]
    }
  ]
}
