{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.23.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.23.jar",
          "size": 403682,
          "sha512": "41ef6fd6b6db5339c3cdb87b3f5a7aa78af7e466aaf49bfc28409fdc5e111ca6054d474e29521172b83d53f77968424af3068cecfa6d15a5d2ece076991f1318",
          "sha256": "daa1a6ed772f17c90afbe0973b250ed8a41c9add1a0fb450f48e6179acf1f22a",
          "sha1": "1878936f5035576dfb44fa9071170efecff42bb1",
          "md5": "369407a2f5c30e8198397a1a5b3b841e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.23.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.23.jar",
          "size": 403682,
          "sha512": "41ef6fd6b6db5339c3cdb87b3f5a7aa78af7e466aaf49bfc28409fdc5e111ca6054d474e29521172b83d53f77968424af3068cecfa6d15a5d2ece076991f1318",
          "sha256": "daa1a6ed772f17c90afbe0973b250ed8a41c9add1a0fb450f48e6179acf1f22a",
          "sha1": "1878936f5035576dfb44fa9071170efecff42bb1",
          "md5": "369407a2f5c30e8198397a1a5b3b841e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.23-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.23-sources.jar",
          "size": 203080,
          "sha512": "086af5c2dead3696eb167dc5fb5af6f29bb45ad4b959485f0a0e5bd31e3f429a3688bc566dfad7980d52e70a3e3ab8cc1b3745a7b7903f44e4a35395214d0077",
          "sha256": "0c7daa19ff7c6461bc20b0bd7013458bf82d4e0424183b1654330bb7dc4546bb",
          "sha1": "7b51a898f51225966bc3f574ee32e6665cf48a8f",
          "md5": "ac19071f5ed30a1c82504efb9e3166d6"
        }
      ]
    }
  ]
}
