{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.7.10.2508.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2508.1.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2508.1.jar",
          "size": 14374352,
          "sha512": "7518823536890fd5167a1abcd445a91dde532bf7abf7396955171f301edf06aa69fd3a3a862b8abb4ee50362b5a6c78680b5b8688ac34a281b0428be43bccc19",
          "sha256": "a65c67bf7085084c9f3942b615ac13d08f7ae4f079e0a2d122bad1e784f1c724",
          "sha1": "9ec0f8a350d053fa327e3f31dba2a3c656f91c9b",
          "md5": "6dc61689ae6af7f317ccb0e2ac129977"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2508.1.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2508.1.jar",
          "size": 14374352,
          "sha512": "7518823536890fd5167a1abcd445a91dde532bf7abf7396955171f301edf06aa69fd3a3a862b8abb4ee50362b5a6c78680b5b8688ac34a281b0428be43bccc19",
          "sha256": "a65c67bf7085084c9f3942b615ac13d08f7ae4f079e0a2d122bad1e784f1c724",
          "sha1": "9ec0f8a350d053fa327e3f31dba2a3c656f91c9b",
          "md5": "6dc61689ae6af7f317ccb0e2ac129977"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.7.10.2508.1-sources.jar",
          "url": "legacy-forge-1.21.3-1.7.10.2508.1-sources.jar",
          "size": 13553959,
          "sha512": "1582168e1e949420ea88c811aa6c6bdde6674bc6611720dfa7486571700676a62aa498d194c4b4e15c9ea15ba7c4e562d81a7a49eb1f4a12202439c43e58fa99",
          "sha256": "43ef81a917ba1cbc5f997eceb7c0b8126df209babef31605c62981c61abf029c",
          "sha1": "abce37a3b6f70d94625bfd0bc2b6b19951fbd149",
          "md5": "b38c57a048bfb37561c6985635db6315"
        }
      ]
    }
  ]
}
