{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2518.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.4.jar",
          "size": 19675349,
          "sha512": "3989ae81b6fc0ff7c0a5817758e0299c87a5b323b8d477c10a078e333eb6cef594e942bf6c8db1ff6de819ea85a32e62c205eb9556634149e28c19606e132a8b",
          "sha256": "e069d8b728a5c36f43b96758051b6d4513cff88e09737043b25b7eb616deee50",
          "sha1": "0861044f2c5b6ba7c21c4a8076c92b9be7e2e093",
          "md5": "ccc86d1401f0076b73de9f35b17082cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.4.jar",
          "size": 19675349,
          "sha512": "3989ae81b6fc0ff7c0a5817758e0299c87a5b323b8d477c10a078e333eb6cef594e942bf6c8db1ff6de819ea85a32e62c205eb9556634149e28c19606e132a8b",
          "sha256": "e069d8b728a5c36f43b96758051b6d4513cff88e09737043b25b7eb616deee50",
          "sha1": "0861044f2c5b6ba7c21c4a8076c92b9be7e2e093",
          "md5": "ccc86d1401f0076b73de9f35b17082cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2518.4-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2518.4-sources.jar",
          "size": 18818122,
          "sha512": "1f98ff79a1f5a9f50ac8de1990711c3f74b35e3dbef9434fcf25e7272eee907ef43823831fbd20ce48d0e9428443d6ece43d771bed2a9d3e88903e3219236ef5",
          "sha256": "eaf1c9d5329ddab90b8170224ad36226cf34a826f636f5889da8a261e040ef6e",
          "sha1": "3f09084f0208786883c3951dc0842c88eb9a76f2",
          "md5": "794476aad86af6c27c29449b2c921545"
        }
      ]
    }
  ]
}
