{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2502.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.12"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2502.2.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2502.2.jar",
          "size": 14189632,
          "sha512": "51259f4865f155c3ba606743b48af2d0c75bb60cb2f7a044d8a8bea479e7cdbfeea27d644c324a29a8146eb90523d2eaa6ab07c3ce0802abc0a6ce52eec21959",
          "sha256": "0e256acdafc67a083bf92a45f90cd675036c749a7b5e0fcdbc92487226d7d88a",
          "sha1": "14be58ba8699fcf5f02871aac0de89305083573a",
          "md5": "bbe0836a7656fb1279364a1fa1976efd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.12"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2502.2.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2502.2.jar",
          "size": 14189632,
          "sha512": "51259f4865f155c3ba606743b48af2d0c75bb60cb2f7a044d8a8bea479e7cdbfeea27d644c324a29a8146eb90523d2eaa6ab07c3ce0802abc0a6ce52eec21959",
          "sha256": "0e256acdafc67a083bf92a45f90cd675036c749a7b5e0fcdbc92487226d7d88a",
          "sha1": "14be58ba8699fcf5f02871aac0de89305083573a",
          "md5": "bbe0836a7656fb1279364a1fa1976efd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2502.2-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2502.2-sources.jar",
          "size": 13414067,
          "sha512": "297fb0db58d33efb8ee36c3d869c8e5cdb1ac5dadb0e0194724666dbd78241f2082c8dc71f15e318b6cc47215dd17bc6ec31b522cca245bfbe7461f44c28d8f4",
          "sha256": "6107719c460bbdce4d6b3f2326334a106911cf0a0efd45d40f32a9b3dde2e8ca",
          "sha1": "299ff706a6b04263e93297bc4356b545299dd49f",
          "md5": "c70e0aaeedbfa5ac38eb9c942a9cdec7"
        }
      ]
    }
  ]
}
