{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.6.2544.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2544.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2544.0.jar",
          "size": 534088,
          "sha512": "2481ff49b40f9e83cf064e20fdf8e90aaf013f376cc9c5ec61cf9d5badc07d54e10ded1009fb692721c53545782d1314fbf9ca78180ae71a0e03ea7c9f56a61f",
          "sha256": "1e1d703245110ae11d4f3c9afa28529434076d3b33e9f5124585bdaec634b38b",
          "sha1": "987916c0698a9b1bd0047cd4b34e89455a5c5c4d",
          "md5": "aca9c3ade8cc43efcd9b399cbb52f59a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2544.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2544.0.jar",
          "size": 534088,
          "sha512": "2481ff49b40f9e83cf064e20fdf8e90aaf013f376cc9c5ec61cf9d5badc07d54e10ded1009fb692721c53545782d1314fbf9ca78180ae71a0e03ea7c9f56a61f",
          "sha256": "1e1d703245110ae11d4f3c9afa28529434076d3b33e9f5124585bdaec634b38b",
          "sha1": "987916c0698a9b1bd0047cd4b34e89455a5c5c4d",
          "md5": "aca9c3ade8cc43efcd9b399cbb52f59a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2544.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2544.0-sources.jar",
          "size": 268090,
          "sha512": "d78e039cdd440957e358d87e0ac51dd125777bb28fa3678c28e11617c28926e69ed4fb9a1ef6251d7d65dc7f57aa0d311cc5d39cfbce4e0127133a9b1189ef10",
          "sha256": "4b37ee348143c02c470c8744485d2740c8cbcfcb2ec64dc4e232b893b6059136",
          "sha1": "a25d0df46cd73a2f8d4c6be375fa5ba7fa877fe7",
          "md5": "f5db5bb85b056373475aab384287c82f"
        }
      ]
    }
  ]
}
