{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2513.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.6.jar",
          "size": 521827,
          "sha512": "da0a335b54a2143fccc0a55d8f993badeb9611baea4f05a2f594fd2b504c27124e8db2463685e5deb55b6dec0d6afa9dc21adbbed95fd0b44e4c7837d8338d3d",
          "sha256": "238b28ef4d554aff8443d71afbbdfd1cab799786bd729b621faeb33a34c6360f",
          "sha1": "9e0c91b9d9c615ae35bd7c908698f30f812a9890",
          "md5": "523689405d6a7c2c6428f2a6f9965b71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.6.jar",
          "size": 521827,
          "sha512": "da0a335b54a2143fccc0a55d8f993badeb9611baea4f05a2f594fd2b504c27124e8db2463685e5deb55b6dec0d6afa9dc21adbbed95fd0b44e4c7837d8338d3d",
          "sha256": "238b28ef4d554aff8443d71afbbdfd1cab799786bd729b621faeb33a34c6360f",
          "sha1": "9e0c91b9d9c615ae35bd7c908698f30f812a9890",
          "md5": "523689405d6a7c2c6428f2a6f9965b71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.6-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.6-sources.jar",
          "size": 251605,
          "sha512": "312f107afeebdb4df9422559fe92f1740bcc8cb7ed0aa5ca1fc0d2652ef27a14e8f640b295d1548540b102e9d578cccd7150762dbe13114e4b8d4b4f41402cb6",
          "sha256": "8be206cd2a59640c573146078d956011e55db9c902c7ffec31738f7f5b8778c7",
          "sha1": "d34ec9a1a509c27c04ba15e6501816a074570844",
          "md5": "225720488e84862340407ece237adc72"
        }
      ]
    }
  ]
}
