{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2513.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2513.9.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2513.9.jar",
          "size": 518964,
          "sha512": "23bbc1216284e08f6defa07ad7228338674a0af0082bf5ba607632d541f3d78cd36e8de70809cb65c334d1e8ffb0e5e6cc5db74b951872b1f66e7a96135fd4a8",
          "sha256": "f78a66216fdcf4ad7d9fcd228d0d1262555fd67fd1913c2536e0239316c29bc1",
          "sha1": "40b48ba281274f0aad89498ea1e87adc2691cb5e",
          "md5": "4095d42f9e446bc7bd7b6346ef2d94ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2513.9.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2513.9.jar",
          "size": 518964,
          "sha512": "23bbc1216284e08f6defa07ad7228338674a0af0082bf5ba607632d541f3d78cd36e8de70809cb65c334d1e8ffb0e5e6cc5db74b951872b1f66e7a96135fd4a8",
          "sha256": "f78a66216fdcf4ad7d9fcd228d0d1262555fd67fd1913c2536e0239316c29bc1",
          "sha1": "40b48ba281274f0aad89498ea1e87adc2691cb5e",
          "md5": "4095d42f9e446bc7bd7b6346ef2d94ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2513.9-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2513.9-sources.jar",
          "size": 251626,
          "sha512": "97eeabdfd4a3225a8af928805006ef6bb7a18e8b7b06422d16f24e745f5837bf8b2ab2330fe7b7b13efd2104233370caeb04bb687d091ef871fc530e418cd0be",
          "sha256": "3834fc6b6d71383e2f170358f6565bd61a969ab4bcd54539360c975b934e624b",
          "sha1": "855400d78cabd4d54a9895e21a6e107624a76eaa",
          "md5": "307a8ffe0ec71ad47ab444bd8d53c248"
        }
      ]
    }
  ]
}
