{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2500.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.1.jar",
          "size": 365259,
          "sha512": "3b04006ebbbabe0c257212d62c5bc88a9338d8b68410b712e4595d65f236189472cf8ad1478669f5cdebd8b9bc3f56a25fe722c5e4e044723caf62a94a9b872a",
          "sha256": "c245825d8acb90218aee6f062566368eb3f47143e408ca9bd87ec44897ccc8b8",
          "sha1": "d667a5ebd3d87052aa26f9c0f14168f20c403adb",
          "md5": "505885c4c316ca2c5baa5a6c426a0873"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.1.jar",
          "size": 365259,
          "sha512": "3b04006ebbbabe0c257212d62c5bc88a9338d8b68410b712e4595d65f236189472cf8ad1478669f5cdebd8b9bc3f56a25fe722c5e4e044723caf62a94a9b872a",
          "sha256": "c245825d8acb90218aee6f062566368eb3f47143e408ca9bd87ec44897ccc8b8",
          "sha1": "d667a5ebd3d87052aa26f9c0f14168f20c403adb",
          "md5": "505885c4c316ca2c5baa5a6c426a0873"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.1-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.1-sources.jar",
          "size": 192650,
          "sha512": "124a51084f4089079759cc6107a0d836ab73b1b201aa62b34dd3e48fa0d8d44588c9ebfb61ab81c71c2516b328490b4fdfb87eb621c420016ae707b23d1d6193",
          "sha256": "ac5c53d2cc9ea61ec7f771f6f949737e7f29516476fc0cffe352de0f67680d20",
          "sha1": "cb4c859dd94134af26a7496ffa6ef9a307a53fd8",
          "md5": "2bbb1b77ae14993927be23ec96ca2cff"
        }
      ]
    }
  ]
}
