{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.20.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.20.jar",
          "size": 390020,
          "sha512": "8b9c92d8943ed49a48df3e925dc1e27c993e0bc9a47d778a4156332c41d59300e8cbb4955038a87b00e9be3f3795f06a177212e6c9c30a4d2b9868d0fcd6b202",
          "sha256": "cc5c9d64875386d2c07ed8db4fdd9fdf51f5fb122d1fc191d1ab92872e77cebe",
          "sha1": "938bb5f719871c992d68aef5709f7dce48ee5b57",
          "md5": "39f350cbd16a6e0667854009633b852c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.20.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.20.jar",
          "size": 390020,
          "sha512": "8b9c92d8943ed49a48df3e925dc1e27c993e0bc9a47d778a4156332c41d59300e8cbb4955038a87b00e9be3f3795f06a177212e6c9c30a4d2b9868d0fcd6b202",
          "sha256": "cc5c9d64875386d2c07ed8db4fdd9fdf51f5fb122d1fc191d1ab92872e77cebe",
          "sha1": "938bb5f719871c992d68aef5709f7dce48ee5b57",
          "md5": "39f350cbd16a6e0667854009633b852c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.20-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.20-sources.jar",
          "size": 200731,
          "sha512": "1a98191cf87d0c8095dd0df632d216776f68c8ffd9e6b4b6e8013fa1484def6d5178624c10f6c3693d660b89cf936b17a0a0a86a9ddd5dee3a4d66e06fab6da8",
          "sha256": "41935b002322f87331cd4b6f436c4667f0e5ac35b0ee46e99ef4c802da103a29",
          "sha1": "f5d31445e9c7fe5b693517e1c04d2acfe0faed8a",
          "md5": "619549dbaf9d2fe957658dc8be943efb"
        }
      ]
    }
  ]
}
