{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2516.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2516.0.jar",
          "size": 523049,
          "sha512": "df405210cf5739aac7dbab1556b92c8ec1a40e4538ff0f96c621df57d178f830bca30f632251736e44c160123c5cb1018c69defac381bf549166d0ada40dadac",
          "sha256": "7c8fc0f7b6ad412dbb5b76ebc6c33e8dd1e610e2cebe3957e8a607185d9c722c",
          "sha1": "43440e5b343f4407af4015c2f2f0769a6ea89e62",
          "md5": "5da877470b67e9ee81a965db6b2053ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2516.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2516.0.jar",
          "size": 523049,
          "sha512": "df405210cf5739aac7dbab1556b92c8ec1a40e4538ff0f96c621df57d178f830bca30f632251736e44c160123c5cb1018c69defac381bf549166d0ada40dadac",
          "sha256": "7c8fc0f7b6ad412dbb5b76ebc6c33e8dd1e610e2cebe3957e8a607185d9c722c",
          "sha1": "43440e5b343f4407af4015c2f2f0769a6ea89e62",
          "md5": "5da877470b67e9ee81a965db6b2053ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2516.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2516.0-sources.jar",
          "size": 253323,
          "sha512": "6eec49e9ad6cf72f1947556f1b82580940f1b4440df8c961c20629a8d93c87ada88a7aa60195aeafc4f26ebf61abc39a9edc73a8322e0f893299d289471e6704",
          "sha256": "72843fec753ff8e62f7b0777ada5c7ad549655114083a58b3ef99f4ca3d2555d",
          "sha1": "6b69af0372472ccdf334985b8a8f7f75c5e953c2",
          "md5": "3b2c6d0fac3ffa0f25f99ee0903b01b7"
        }
      ]
    }
  ]
}
