{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.3.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.3.jar",
          "size": 19754172,
          "sha512": "ccc1706148c54980e663a2b298d0f0fc44e3d529dd5b283a1d12d6d8226f31f387106c489a256eaf814ea2c03721355bf19e8f91f552960ed47cba2f29e8e8fe",
          "sha256": "73fc4343cd8b6dc55f428b40c3ece33976a811d5137fc69a3692e941d000e5d8",
          "sha1": "ca2d2b8daa1d2ae96f5ca05fd29750455506c446",
          "md5": "f2287787e408574ac67982ece5ece133"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.3.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.3.jar",
          "size": 19754172,
          "sha512": "ccc1706148c54980e663a2b298d0f0fc44e3d529dd5b283a1d12d6d8226f31f387106c489a256eaf814ea2c03721355bf19e8f91f552960ed47cba2f29e8e8fe",
          "sha256": "73fc4343cd8b6dc55f428b40c3ece33976a811d5137fc69a3692e941d000e5d8",
          "sha1": "ca2d2b8daa1d2ae96f5ca05fd29750455506c446",
          "md5": "f2287787e408574ac67982ece5ece133"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.3-sources.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.3-sources.jar",
          "size": 18894104,
          "sha512": "a53c3a94882ea7810d03f1cee8918c205f8983d4c6ea95aa2f9724903087e1437dcb059073b5e0c14b63525bafdde852c3b6f0bac160dce34481aa99c11386fe",
          "sha256": "017127e877fcb43a322edd607a953c4d1f1e527287c8a9f246fc99edab29cbd6",
          "sha1": "a7a39b12ab0312b99c79f48b176b108016398285",
          "md5": "bbbbd7cb98efcba1f86805797574158c"
        }
      ]
    }
  ]
}
