{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2504.3.jar",
          "url": "factory_api-forge-1.20.1-2.2.2504.3.jar",
          "size": 475049,
          "sha512": "d44a17c31e734d37166b2b668a7a35d6e867f145cfe9a4507ec65182f6b2ca3a0819b442d92dd9d5ca0b26a726def75ee6b186a8f6d4fbb32b270e2242d23e13",
          "sha256": "df565fbdd669f97bfe1ee1a70d3633ec5e007e76423f6afdb703452400856c12",
          "sha1": "d39d904e71628fbed926c16e298d47e8afe6e97a",
          "md5": "b0dc3870492b7a7a6483bc0344f99751"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2504.3.jar",
          "url": "factory_api-forge-1.20.1-2.2.2504.3.jar",
          "size": 475049,
          "sha512": "d44a17c31e734d37166b2b668a7a35d6e867f145cfe9a4507ec65182f6b2ca3a0819b442d92dd9d5ca0b26a726def75ee6b186a8f6d4fbb32b270e2242d23e13",
          "sha256": "df565fbdd669f97bfe1ee1a70d3633ec5e007e76423f6afdb703452400856c12",
          "sha1": "d39d904e71628fbed926c16e298d47e8afe6e97a",
          "md5": "b0dc3870492b7a7a6483bc0344f99751"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2504.3-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2504.3-sources.jar",
          "size": 233353,
          "sha512": "0857bd620484ccee5d2dc5d7697b23b01c0722c6cec2e651d7fcbf664f3c7b89ae2323d81dccf691f139b2859ed637ccd4ef800d141a293ff8fac150d7da2fd3",
          "sha256": "2ddb0f32427aadd4c50a19761928ceb8b57963b5ed96228c69f74ca4210345fb",
          "sha1": "a4b8ea4a2efb86252255fcb01b938edb16b111e3",
          "md5": "e649a34aa9f2dd6ea76406bdb64d05f1"
        }
      ]
    }
  ]
}
