{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.2.jar",
          "size": 367778,
          "sha512": "5453c48ba9c1c372ea34a2aba01d9f421eef50a01f780d706ce1c6f55bd95926bd2c7820a5b5bd1eb77cd385f90c414f54fcfc96e6c50cab4e1242e7dfbc9ab0",
          "sha256": "6ee30f639c7f3a1df363ac54889fde5f34bbc3249ec9b217fc94a6dc25772d2e",
          "sha1": "a84d443fe9a799f2d97caf5f55553faf6a20894d",
          "md5": "37ff7c54f852ad0e106d71840c2bcd2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.2.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.2.jar",
          "size": 367778,
          "sha512": "5453c48ba9c1c372ea34a2aba01d9f421eef50a01f780d706ce1c6f55bd95926bd2c7820a5b5bd1eb77cd385f90c414f54fcfc96e6c50cab4e1242e7dfbc9ab0",
          "sha256": "6ee30f639c7f3a1df363ac54889fde5f34bbc3249ec9b217fc94a6dc25772d2e",
          "sha1": "a84d443fe9a799f2d97caf5f55553faf6a20894d",
          "md5": "37ff7c54f852ad0e106d71840c2bcd2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.2-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.2-sources.jar",
          "size": 194928,
          "sha512": "8d51322d82179f2666c2cb5aa620c9b375e6f765a93662de56b97cb5c8476128747a9588cc8bb23e4118bdc2d262b9c8158181ba68cb9ce88b73e40824748d30",
          "sha256": "905c2a5ec5946ca4eabad4569e418a1864f367ea2cb70cbc8096e50ecc8a5454",
          "sha1": "e9ce8c5893f67242051e749fd75d651b65545cc0",
          "md5": "e751ce14d8b2d0811486ac75d942e11a"
        }
      ]
    }
  ]
}
