{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.8.0.2517.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2517.1.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2517.1.jar",
          "size": 18275697,
          "sha512": "a3a9359d041f667fa411e05409838d08db6177985e1c586c61fa852a70f7b0a627bb6ae13357120fca3e67bceb6006c0ce4f1e57b849c52b5220c535bcf7f2a1",
          "sha256": "f30b34f6f3f56d2eaaf822bc7260ee129d811e7d253deefaf7bbe5e243dc13fd",
          "sha1": "acc5a5663dd446e7e5058a4e2c96f7f6c679b015",
          "md5": "ac046e353260a592cccdcd0dbf9eed68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2517.1.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2517.1.jar",
          "size": 18275697,
          "sha512": "a3a9359d041f667fa411e05409838d08db6177985e1c586c61fa852a70f7b0a627bb6ae13357120fca3e67bceb6006c0ce4f1e57b849c52b5220c535bcf7f2a1",
          "sha256": "f30b34f6f3f56d2eaaf822bc7260ee129d811e7d253deefaf7bbe5e243dc13fd",
          "sha1": "acc5a5663dd446e7e5058a4e2c96f7f6c679b015",
          "md5": "ac046e353260a592cccdcd0dbf9eed68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2517.1-sources.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2517.1-sources.jar",
          "size": 17424386,
          "sha512": "0414d896896f7b1585cf5beca9ae665d93569e52bfbdc53b604788e5b3114cc962df525f8afcf5a32f30cbc06c696dd35cea3708a9f65af1a48f300e62037117",
          "sha256": "e4fbdd66afc7b6e4ed3f63d34dee715861e877f4166c790ff78bb9a3a8524968",
          "sha1": "17d58674b5abb4da8f1eba00416f0965521a75e4",
          "md5": "43ce1af2e5d87e86a1767763e3a70a1a"
        }
      ]
    }
  ]
}
