{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.8.0.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2515.0.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2515.0.jar",
          "size": 18255079,
          "sha512": "fc7cab9a223cacd04519157ccf0f1fac694f6362e7786a0f355c8cefb390cfadd33cfb37c4023bab369b9fc439c3d2878d059b0500dbda01bf3a6bb08e1bc646",
          "sha256": "4410bdfd662f8fcdbd65491689451d43566761f38eee9f28fbf10908e8e95e7b",
          "sha1": "5d205b619d6022e234124c7c590cc429b0b0de2f",
          "md5": "3e63a62f8c8dc4f71bf2ebb51025f878"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2515.0.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2515.0.jar",
          "size": 18255079,
          "sha512": "fc7cab9a223cacd04519157ccf0f1fac694f6362e7786a0f355c8cefb390cfadd33cfb37c4023bab369b9fc439c3d2878d059b0500dbda01bf3a6bb08e1bc646",
          "sha256": "4410bdfd662f8fcdbd65491689451d43566761f38eee9f28fbf10908e8e95e7b",
          "sha1": "5d205b619d6022e234124c7c590cc429b0b0de2f",
          "md5": "3e63a62f8c8dc4f71bf2ebb51025f878"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2515.0-sources.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2515.0-sources.jar",
          "size": 17422890,
          "sha512": "362597f2f91ed0299f662b06639c1eeb9028aaef3a792cf1fefb819becca80fc7863fd240494f03c7a1886e2cb4f56bb57be31e870946ea5e53458876e41534a",
          "sha256": "e501a527f06963ad0758633a288c357cf2a8254f18118a0bf58f5c80fa81202e",
          "sha1": "60a12dee20658003f8e4c6fe2435ed6454da5182",
          "md5": "374fd325667a54edea2f7c1d40bec6cf"
        }
      ]
    }
  ]
}
