{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2513.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.7.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.7.jar",
          "size": 703469,
          "sha512": "47749a61daf717a0b3503a37799d0a4adbe928b7254b01689cf4b90e66518c8ab4bea2973f2c4337de5189d89c2db83c5132d344ab36980bff3de7c7f5e33077",
          "sha256": "2eea1e91b91305baf178e2d93acced3755d5ba44d6421ced1a0b4d6284cb970c",
          "sha1": "500e600310d9db666f9260662d079b49f57ed6fb",
          "md5": "5f911f1d737ac2a01cdbe3c393a29ed8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.7.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.7.jar",
          "size": 703469,
          "sha512": "47749a61daf717a0b3503a37799d0a4adbe928b7254b01689cf4b90e66518c8ab4bea2973f2c4337de5189d89c2db83c5132d344ab36980bff3de7c7f5e33077",
          "sha256": "2eea1e91b91305baf178e2d93acced3755d5ba44d6421ced1a0b4d6284cb970c",
          "sha1": "500e600310d9db666f9260662d079b49f57ed6fb",
          "md5": "5f911f1d737ac2a01cdbe3c393a29ed8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2513.7-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2513.7-sources.jar",
          "size": 251320,
          "sha512": "582ccbdc16539e32ba117163e456121891bca2d3fb65b19f5b09041c2f539121a87e235d1adaf3f95938cb1bbab043051aa9346c4faba7d02dec60cabd399fa5",
          "sha256": "14689e8acad921f721f5852db17c63c6c8a6362663d0e607a693565144bba13b",
          "sha1": "f3344e2fc20b359a2ab6fd644b078a81fe698c41",
          "md5": "acf7d5dc58ced9486ac4c8396a5a7bb9"
        }
      ]
    }
  ]
}
