{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.4-1.8.0.2512.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-fabric-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2512.4.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2512.4.jar",
          "size": 18251041,
          "sha512": "6b65df4c2a59ff201be6cf36cfc04f2090bd919d3f079d7d2c01a968abc7aee59d22504fba27e1661a03b629835ce4d4d8dccfcd1134c4d35de99eae8b421327",
          "sha256": "32a52381da367d1f41c662eeda8038aa525ab066a3989955e97d010bd4dfbe99",
          "sha1": "66e311015ede5822451202b40100f88743ef65d5",
          "md5": "ac0db8cbc1164a5e6647a9286be40b81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2512.4.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2512.4.jar",
          "size": 18251041,
          "sha512": "6b65df4c2a59ff201be6cf36cfc04f2090bd919d3f079d7d2c01a968abc7aee59d22504fba27e1661a03b629835ce4d4d8dccfcd1134c4d35de99eae8b421327",
          "sha256": "32a52381da367d1f41c662eeda8038aa525ab066a3989955e97d010bd4dfbe99",
          "sha1": "66e311015ede5822451202b40100f88743ef65d5",
          "md5": "ac0db8cbc1164a5e6647a9286be40b81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.8.0.2512.4-sources.jar",
          "url": "legacy-fabric-1.20.4-1.8.0.2512.4-sources.jar",
          "size": 17415779,
          "sha512": "8ce8b4fae8c9b7ae9a45ed6847f6e798f4c4e5bd09a62d41b032b826f8c7998726d4072cedae71460921157cff1753fd951782f4e5ea98e7fe81f34a04be09fe",
          "sha256": "909c7003504940447ae3ad79efea04ac1e41f19889d2712e4b52de12ae6fdfce",
          "sha1": "240a4838f04bb7def32b168170a4c8d62a0c3d6c",
          "md5": "d36e8ba478f90973123de175c513dfcc"
        }
      ]
    }
  ]
}
