{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.0.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2516.3.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2516.3.jar",
          "size": 18288183,
          "sha512": "fce9bf5d063c957fb10124f92a1ef1c1c68987827991f8c7a57accfab597a7f851ad84aa29bc14909e5efe2b9bc41dee66437b1904f14fd4ad3c490f8086ae71",
          "sha256": "8471b28cdebb6081aeb35d726d11a3933b84215e650d4e9dadd65ce1beeda162",
          "sha1": "651b7ebb901d484b8bfc4229539df33647672aa5",
          "md5": "fa892b0a3ef3ffea7ecfe06bcf5f9db4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2516.3.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2516.3.jar",
          "size": 18288183,
          "sha512": "fce9bf5d063c957fb10124f92a1ef1c1c68987827991f8c7a57accfab597a7f851ad84aa29bc14909e5efe2b9bc41dee66437b1904f14fd4ad3c490f8086ae71",
          "sha256": "8471b28cdebb6081aeb35d726d11a3933b84215e650d4e9dadd65ce1beeda162",
          "sha1": "651b7ebb901d484b8bfc4229539df33647672aa5",
          "md5": "fa892b0a3ef3ffea7ecfe06bcf5f9db4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2516.3-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2516.3-sources.jar",
          "size": 17422416,
          "sha512": "3a3f4aede2e32714d684879926aa5d0235e21a788f37d98319d314911546779608794e398e536e8b18b6ab349b803e6215892a2c8be1744ff29e799fdb3bde04",
          "sha256": "7a48effff28c9adf4f89fc854d4dc2502c042b576694cc49c90e5fdad6949dc9",
          "sha1": "b38f0e5dbcef94de36fb0684a3e43a65ae710722",
          "md5": "85170a30edfcb25448daec2628cfba74"
        }
      ]
    }
  ]
}
