{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2502.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.6.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.6.jar",
          "size": 431557,
          "sha512": "46dd185d4c6944cac32a991cef58c3e476653efd0d4757c300adc0d717e73e4ba8428dea8fe5ed28dba5e88840ea9b7d247845e07d8ee38b1829da64595004b9",
          "sha256": "9914870957d50f998f62160a5785e359e3132c802e233f1936dea5ad10729f0c",
          "sha1": "b361868fe1cd33eb422956d20496a35d0ced4167",
          "md5": "b47ac51040ad349fcc596f65b5b9d304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.6.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.6.jar",
          "size": 431557,
          "sha512": "46dd185d4c6944cac32a991cef58c3e476653efd0d4757c300adc0d717e73e4ba8428dea8fe5ed28dba5e88840ea9b7d247845e07d8ee38b1829da64595004b9",
          "sha256": "9914870957d50f998f62160a5785e359e3132c802e233f1936dea5ad10729f0c",
          "sha1": "b361868fe1cd33eb422956d20496a35d0ced4167",
          "md5": "b47ac51040ad349fcc596f65b5b9d304"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2502.6-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2502.6-sources.jar",
          "size": 223751,
          "sha512": "a30124ce751dbeda5b2534f2e06ed070fd5ea4465f92cef59cbe7479f994233b7d62344e38f1eb93e2825befef5c07fde9e564cb8d65cda986b8fa62f88f48ff",
          "sha256": "a8dd19e8f12fcc387fd66cdaa73eba5e24752225519c1a813044be77e419c36f",
          "sha1": "1a4b53f34c0758d150a9ccbcb0ac62ba80e122da",
          "md5": "746822db120eb94f74bd05284912ed54"
        }
      ]
    }
  ]
}
