{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2508.2.jar",
          "size": 506296,
          "sha512": "4f64beb78de4fd6fba27c023c4e71cf2c33fa7f6cc50d6befbeb27869a344e73d18e7a8837e9f263691715a12afd71b29d4c924fc876a6f9dabf6f085bad156e",
          "sha256": "fded2d06725ef54ea684cd604b48cd36873fccff3429b629093dbd9342a82fa8",
          "sha1": "2b3a59e13658196fc036bce96d44f3211b7ae52b",
          "md5": "c3009c17686465eed84b4b456c083101"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2508.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2508.2.jar",
          "size": 506296,
          "sha512": "4f64beb78de4fd6fba27c023c4e71cf2c33fa7f6cc50d6befbeb27869a344e73d18e7a8837e9f263691715a12afd71b29d4c924fc876a6f9dabf6f085bad156e",
          "sha256": "fded2d06725ef54ea684cd604b48cd36873fccff3429b629093dbd9342a82fa8",
          "sha1": "2b3a59e13658196fc036bce96d44f3211b7ae52b",
          "md5": "c3009c17686465eed84b4b456c083101"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2508.2-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2508.2-sources.jar",
          "size": 248168,
          "sha512": "297d7a8e3edf6ac96b392c8b33c2d60f29909591c66c66e81ce1c646426d66d36f49d649edc96f07adea36bf87d11ce2e86f8b89235f3eba0a90a1e3fcc341fe",
          "sha256": "71e4b4a3b3432b2fa885e4bb9d8be6eda48625a91a9bb1a81cc16949a7d7de35",
          "sha1": "4cb59ba68ce80e5e9ac4ef0d585cf1a03ca677c0",
          "md5": "d0a53f9144d7943a593a18cbabc3b7ba"
        }
      ]
    }
  ]
}
