{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2617.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2617.2.jar",
          "size": 581356,
          "sha512": "1623645eaa1d9f6a99067a3fc0eaafe2f3c87bb5c40f6bcb513bcca312e4a4e37ad84f9e7b7adc3ab653777785071ec46f719c79a1a9ef673ce0d90afee0d5af",
          "sha256": "108d7d4002a1de4e4b203fa046622e91a323e0c8fe1a34dc280f4a8d38e4b19b",
          "sha1": "652fb073a44d39011edcdc41184a62e0f8300e0b",
          "md5": "22a386495f6b5ca23334e552ffebdcdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2617.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2617.2.jar",
          "size": 581356,
          "sha512": "1623645eaa1d9f6a99067a3fc0eaafe2f3c87bb5c40f6bcb513bcca312e4a4e37ad84f9e7b7adc3ab653777785071ec46f719c79a1a9ef673ce0d90afee0d5af",
          "sha256": "108d7d4002a1de4e4b203fa046622e91a323e0c8fe1a34dc280f4a8d38e4b19b",
          "sha1": "652fb073a44d39011edcdc41184a62e0f8300e0b",
          "md5": "22a386495f6b5ca23334e552ffebdcdc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2617.2-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2617.2-sources.jar",
          "size": 256296,
          "sha512": "77419d8a101569cb815f6f72b14485409a7ebb7f2757f4df148ef339eaadf146383af74710fa3f3ef8961ba6b576536ee01fbcd80556898eca46517716127f72",
          "sha256": "4dbf6f712fb104a59eebfc88858ae0409adc38134f2da5e128334e2ebf26e008",
          "sha1": "e99316d5fd7b9a55ae7249ab2a258ba4f09a56c2",
          "md5": "4b5da0cb678ab4612b5f3de5dbd79b78"
        }
      ]
    }
  ]
}
