{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.2.jar",
          "size": 365050,
          "sha512": "86df20047b48550d8a7a9245cf4d94e209fbd4915e01269dd8ca72d1bafe42543e397b534a38f04e17e969147b209564727d81c7244181d75844f77b9facd346",
          "sha256": "9f072f501ec97ce42fa7fd5764e74c7cefb5ec7e859896ad5949b454af38e2be",
          "sha1": "6ae32146a1eec8ba2d4d3151eb9a1eafc8548005",
          "md5": "907d0129d770c0b705e59b978a746ae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.2.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.2.jar",
          "size": 365050,
          "sha512": "86df20047b48550d8a7a9245cf4d94e209fbd4915e01269dd8ca72d1bafe42543e397b534a38f04e17e969147b209564727d81c7244181d75844f77b9facd346",
          "sha256": "9f072f501ec97ce42fa7fd5764e74c7cefb5ec7e859896ad5949b454af38e2be",
          "sha1": "6ae32146a1eec8ba2d4d3151eb9a1eafc8548005",
          "md5": "907d0129d770c0b705e59b978a746ae6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.2-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.2-sources.jar",
          "size": 194979,
          "sha512": "067998caafc694addf64e6133cc592923babd971899a05081a6b874deb0c96195c0fb85aa87505fb8950472c61c8ccc80d776c3b4472670ed1f4e21f00603460",
          "sha256": "403b482cbd6c8733ab6b785bac2593d8c3f006c19344331c148783e3ba6a205b",
          "sha1": "35fdfcf82394fdb8daa8e9fe9fd3677d63595330",
          "md5": "d24eaf1a15483e9b47507c54064b7760"
        }
      ]
    }
  ]
}
