{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.2.jar",
          "size": 555518,
          "sha512": "e9648468586ae4127227f5ad1614ce48dfe1afcba2b305e5b8694624453b4590f6531b19217fa49aebf3a817f128dbe1c8b505837cb783ab2328e98e78e3ba39",
          "sha256": "44d5f8990256dcf2196614afc906dcc575aeb0f8143f4ac807954a5c7f75a5c8",
          "sha1": "52fd2562ebe422f6b8ed63bf5b8355ae44f37aa3",
          "md5": "a28c6fd6cf0f3f156571b5fa58a2ff05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.2.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.2.jar",
          "size": 555518,
          "sha512": "e9648468586ae4127227f5ad1614ce48dfe1afcba2b305e5b8694624453b4590f6531b19217fa49aebf3a817f128dbe1c8b505837cb783ab2328e98e78e3ba39",
          "sha256": "44d5f8990256dcf2196614afc906dcc575aeb0f8143f4ac807954a5c7f75a5c8",
          "sha1": "52fd2562ebe422f6b8ed63bf5b8355ae44f37aa3",
          "md5": "a28c6fd6cf0f3f156571b5fa58a2ff05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.2-sources.jar",
          "size": 256771,
          "sha512": "dccff4536e66f8bca7345674a0f5c451740e3d0d5ccba010417b135e8b0b0aeae46fd684ac8d47a48a8462c370089fb777cc1daa13f0d0788b4d723eceb2baeb",
          "sha256": "e5934124856b6d83f829a51c0982b86f41c89966f094b3d9376dc8e2ddc14279",
          "sha1": "8ce0891ffc4e582a3ab647595247dc3dca802e9c",
          "md5": "807debb01d551a720f0d83d9bf4eeb59"
        },
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.2-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.2-sources.jar",
          "size": 256771,
          "sha512": "dccff4536e66f8bca7345674a0f5c451740e3d0d5ccba010417b135e8b0b0aeae46fd684ac8d47a48a8462c370089fb777cc1daa13f0d0788b4d723eceb2baeb",
          "sha256": "e5934124856b6d83f829a51c0982b86f41c89966f094b3d9376dc8e2ddc14279",
          "sha1": "8ce0891ffc4e582a3ab647595247dc3dca802e9c",
          "md5": "807debb01d551a720f0d83d9bf4eeb59"
        }
      ]
    }
  ]
}
