{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.7.10.2509.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2509.0.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2509.0.jar",
          "size": 14416114,
          "sha512": "2f9a1554566e0d5f59a5f7602199d1cbf1a524b9a92a03f1dfcc04d2009d554b6001e4375aa4b9c0abf4befad5a021568217ffecca3b25af2c796e6b99b8ec64",
          "sha256": "48d6378d0673c68eeb6a7ca962bdb90bc5984b410eaf48fc515d8dd3c1eb8068",
          "sha1": "783ae90df00706fd612a9fe727b9e630e835f1a4",
          "md5": "d6ebf0e42521e66ee7b38200f9553182"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2509.0.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2509.0.jar",
          "size": 14416114,
          "sha512": "2f9a1554566e0d5f59a5f7602199d1cbf1a524b9a92a03f1dfcc04d2009d554b6001e4375aa4b9c0abf4befad5a021568217ffecca3b25af2c796e6b99b8ec64",
          "sha256": "48d6378d0673c68eeb6a7ca962bdb90bc5984b410eaf48fc515d8dd3c1eb8068",
          "sha1": "783ae90df00706fd612a9fe727b9e630e835f1a4",
          "md5": "d6ebf0e42521e66ee7b38200f9553182"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2509.0-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2509.0-sources.jar",
          "size": 13581812,
          "sha512": "6f72d6cc85d47b5b9cd78f2f507bc414664b587606ce431e9f374fe1105cf1d5b27eca8e88dedcc95a8ddaa84f14f0bf0bbb4a10612ac357c93a845ce3a8ed8f",
          "sha256": "c9422f2538c984a9a388bfb3d480a429a3ec950cd764daaa2e697561510fad56",
          "sha1": "92a5706706a880a9ae6e0a8f078bc166d109638f",
          "md5": "5c96d9ac36d9bedd57f9b32911581783"
        }
      ]
    }
  ]
}
