{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2510.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2510.8.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2510.8.jar",
          "size": 697350,
          "sha512": "160f38f89b91e608601565071bfd364f5cf010c68317838537f08f181aed51d2efcc21433236c38402443c4d56348e3e3a379b0598efa43b73d0709b6861fda7",
          "sha256": "da62d8bfa1f45f45b5eb74bdfc5e6e4a71fdc0435bc355d7e6e086025f45c8ae",
          "sha1": "840e7e02244d295e8824bd0ad4a8d8f46d8fe44f",
          "md5": "4443db9ade315faa15de39d10e426007"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2510.8.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2510.8.jar",
          "size": 697350,
          "sha512": "160f38f89b91e608601565071bfd364f5cf010c68317838537f08f181aed51d2efcc21433236c38402443c4d56348e3e3a379b0598efa43b73d0709b6861fda7",
          "sha256": "da62d8bfa1f45f45b5eb74bdfc5e6e4a71fdc0435bc355d7e6e086025f45c8ae",
          "sha1": "840e7e02244d295e8824bd0ad4a8d8f46d8fe44f",
          "md5": "4443db9ade315faa15de39d10e426007"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2510.8-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2510.8-sources.jar",
          "size": 250609,
          "sha512": "4b4ab8dab3d1e816911046c6262ea75ad93bb7678bb430be126c96a7b9dc8ac80f836e24300bbd08f57e22addbb5817f08816cda852fc9916e0c86d58c9fea51",
          "sha256": "8482c7b5bafacf7e9cc1c428e797d1987a98a1137bf2ac3a6f79d4591d9f5faf",
          "sha1": "e5921d6e97218b62ca1c0fc80df87d5f3ae51409",
          "md5": "758862334132d2666858371faa4bff2b"
        }
      ]
    }
  ]
}
