{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.7.2606.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2606.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2606.1.jar",
          "size": 526131,
          "sha512": "5ed78f881321edb21cc40aba4101aae6f895774380d62a21f4332a42f266428ab389095afc1f9608197f5201e778cf348013b5b24a61d424eba4952b07a10d4d",
          "sha256": "c5f75d0aa10b8f8ca8506fd0bcae6beef4b187ebbb440e47a2edf548698c55d8",
          "sha1": "10c5c118b38d6c240f7f792a6e7467b0fcf15797",
          "md5": "312f25304fe8f81fb3b09a130fd62d71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2606.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2606.1.jar",
          "size": 526131,
          "sha512": "5ed78f881321edb21cc40aba4101aae6f895774380d62a21f4332a42f266428ab389095afc1f9608197f5201e778cf348013b5b24a61d424eba4952b07a10d4d",
          "sha256": "c5f75d0aa10b8f8ca8506fd0bcae6beef4b187ebbb440e47a2edf548698c55d8",
          "sha1": "10c5c118b38d6c240f7f792a6e7467b0fcf15797",
          "md5": "312f25304fe8f81fb3b09a130fd62d71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2606.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2606.1-sources.jar",
          "size": 256265,
          "sha512": "fd7f88edb970efe55c2ded900349f6e96cb7d7e2811d5bcf410cdf11f343f2dc0f923e103d9e2af8d2bb6f316396363495cb16294716597ead4289d530b54224",
          "sha256": "3a8cb040f49ff714ae57cfe3c2fea3a2f4edb6ba9ef9e888370c3f1087206f1f",
          "sha1": "a126bddb1a548a3f13e95c3b2eb353df52be8c7b",
          "md5": "1e3bbe86612efce7388f12fdd0eb7ea3"
        }
      ]
    }
  ]
}
