{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2513.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2513.4.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2513.4.jar",
          "size": 681413,
          "sha512": "d235d283a3fef201da620483be7362f1dd5c1e44ce49c58577412cfd8cb8658efa91defa10257b5e82c03bcd309a721d744c4b8793663f14fa11331beced7bba",
          "sha256": "eb1b9e6442945e856a6b79e67c8c0a1a3e62ef70bd162a8b8827ca22d0560d45",
          "sha1": "7f83f865005e7716d746bdc58e8940edac5b9f99",
          "md5": "fe162278ea88987fc38b0ee68edb51b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2513.4.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2513.4.jar",
          "size": 681413,
          "sha512": "d235d283a3fef201da620483be7362f1dd5c1e44ce49c58577412cfd8cb8658efa91defa10257b5e82c03bcd309a721d744c4b8793663f14fa11331beced7bba",
          "sha256": "eb1b9e6442945e856a6b79e67c8c0a1a3e62ef70bd162a8b8827ca22d0560d45",
          "sha1": "7f83f865005e7716d746bdc58e8940edac5b9f99",
          "md5": "fe162278ea88987fc38b0ee68edb51b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2513.4-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2513.4-sources.jar",
          "size": 252191,
          "sha512": "a718bdde582486d1b50999176c7cd759de1a35d34b22cc329c73a225709c5ebc66e27c20bd13d8cef57a86394e192e1770d5f7f556e836dbd264a98cfd122983",
          "sha256": "56c3059474bf824eaefd5594ab4dd701d0f5d0b85273262526366be198c5083b",
          "sha1": "77aaa693fa972f10dae5b9bd6b81079452458485",
          "md5": "19d2905689771c97eaf93987d8d0f91f"
        }
      ]
    }
  ]
}
