{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.7.jar",
          "size": 354426,
          "sha512": "bfab394e3ce4bf6900169a15547740e7ee08c91acbc20d8562157e8a0a01a731336536b1dc7ebb0906c755abc103d553778eb740ad47bc121868986225e33279",
          "sha256": "99535032761bf8050e4cba9086c8fc99f40f28b35bfa597a94ddf44f13a5a2c7",
          "sha1": "c12d0b5bdb2de6cc97796867ffb22eb8a823682f",
          "md5": "fba8f3cc0ddec3c409009d328869db09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.7.jar",
          "size": 354426,
          "sha512": "bfab394e3ce4bf6900169a15547740e7ee08c91acbc20d8562157e8a0a01a731336536b1dc7ebb0906c755abc103d553778eb740ad47bc121868986225e33279",
          "sha256": "99535032761bf8050e4cba9086c8fc99f40f28b35bfa597a94ddf44f13a5a2c7",
          "sha1": "c12d0b5bdb2de6cc97796867ffb22eb8a823682f",
          "md5": "fba8f3cc0ddec3c409009d328869db09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.7-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.7-sources.jar",
          "size": 196276,
          "sha512": "0fec8d3d1a9f77eae6cfd893a8b3a4e3b68f05585781b34c191632c14b1798a80ee50bd81fde738276ae5d6be71db88367c551ab02566523e6d810ec5bf9c14f",
          "sha256": "5621a7c43f4064d4b70b679e65158e8d0452e4f7cdc3bf24184b9910309a5952",
          "sha1": "4c5e2181ec3517ba836d820bb1328438965347df",
          "md5": "b80b9ee84b6e3eca73c38d6ed049edb6"
        }
      ]
    }
  ]
}
