{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.4-1.1.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2517.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2517.0.jar",
          "size": 643273,
          "sha512": "8f5bd742477cf03cd03cbcfdabd0a8042a78fe0976042918bb2ef381ede21421b5193e868564748d5c4f78e9567ee7a66db60cca2cb70ff044c96b938c9b936a",
          "sha256": "673c492e9771e41db8b812276367b35a3f28cebf2be8656005e81bf94c2e55bb",
          "sha1": "2447edf481434013e771eea5eddb71358ffd53f8",
          "md5": "ea954a0db41d624d2df4f74bc2d16c12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2517.0.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2517.0.jar",
          "size": 643273,
          "sha512": "8f5bd742477cf03cd03cbcfdabd0a8042a78fe0976042918bb2ef381ede21421b5193e868564748d5c4f78e9567ee7a66db60cca2cb70ff044c96b938c9b936a",
          "sha256": "673c492e9771e41db8b812276367b35a3f28cebf2be8656005e81bf94c2e55bb",
          "sha1": "2447edf481434013e771eea5eddb71358ffd53f8",
          "md5": "ea954a0db41d624d2df4f74bc2d16c12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.4-1.1.2517.0-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.4-1.1.2517.0-sources.jar",
          "size": 585479,
          "sha512": "d1fb4072073ff8b60fa160bc967a62378cb206cefddcdc582d71e1a63f9c52b2efadf24005e246a093afd5134e0a5df8c3457e98196861dcdbea7ed0c3d6de54",
          "sha256": "54e40a1d185233d50161f1e91d3829aae30d62b6bf57c2fcf1ad981e5a36603c",
          "sha1": "f86cba6f81f8c761a2ca6071bade99b284af06db",
          "md5": "0449684c80c488f35d2aaba476a4a198"
        }
      ]
    }
  ]
}
