{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.7-2.2.5.2527.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.7-2.2.5.2527.0.jar",
          "url": "factory_api-neoforge-1.21.7-2.2.5.2527.0.jar",
          "size": 533234,
          "sha512": "c8c33515ed9ecb7962ad50f7b7d22dacf303f2458c474dd99ae054b085902624c9112557e71b33e4aaa7e50b13cb8c9306aa7d9424677d533f15c9c79ee52062",
          "sha256": "e28716a2867a1842a3ccecb5dd8aeb33faba8edf4cf2f09ea6b0388f42f21c85",
          "sha1": "82a451376c709d3eef9b7f482f8915d9eb19e9ee",
          "md5": "12ef17eac4431ebf292d77c6d37c9437"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.7-2.2.5.2527.0.jar",
          "url": "factory_api-neoforge-1.21.7-2.2.5.2527.0.jar",
          "size": 533234,
          "sha512": "c8c33515ed9ecb7962ad50f7b7d22dacf303f2458c474dd99ae054b085902624c9112557e71b33e4aaa7e50b13cb8c9306aa7d9424677d533f15c9c79ee52062",
          "sha256": "e28716a2867a1842a3ccecb5dd8aeb33faba8edf4cf2f09ea6b0388f42f21c85",
          "sha1": "82a451376c709d3eef9b7f482f8915d9eb19e9ee",
          "md5": "12ef17eac4431ebf292d77c6d37c9437"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.7-2.2.5.2527.0-sources.jar",
          "url": "factory_api-neoforge-1.21.7-2.2.5.2527.0-sources.jar",
          "size": 258690,
          "sha512": "053c900540fe1887b8a7ef9a39e57c65a3f7f9f763801b10d5b15fe54a7005d6e791c1889448f9417a313620bf844292572d9f1bd3b5e8a9a64fd1a55e345ae1",
          "sha256": "b5014fa0b51b17a27e71890f485c0516e080ac9d2e0a6c826478201e30aeb7ed",
          "sha1": "c37cc879b0b411fff305da99e2731312abe438bd",
          "md5": "1f02798cb74814b14d51a829789cf1ad"
        }
      ]
    }
  ]
}
