{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "26.1.1-2.2.7.2616.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "size": 561693,
          "sha512": "6ade861fe691e312581df11e07494084291a85d8b2abf11a8e96818ecf7b5e7d2d3e2ffeba66f78e874cf28f49f2715ba584bdf3d0e6ac6b7dfb998ee369ff3a",
          "sha256": "9e66e8f3e98a89d6b1d4c53d484e270d4a8716aff7187cb12820d7ba9d6314c0",
          "sha1": "71fd3c098effe3950d65364b008aca0a8ed0205a",
          "md5": "9d330d5ad39a22bf51e06734fd1fcde9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "size": 561693,
          "sha512": "6ade861fe691e312581df11e07494084291a85d8b2abf11a8e96818ecf7b5e7d2d3e2ffeba66f78e874cf28f49f2715ba584bdf3d0e6ac6b7dfb998ee369ff3a",
          "sha256": "9e66e8f3e98a89d6b1d4c53d484e270d4a8716aff7187cb12820d7ba9d6314c0",
          "sha1": "71fd3c098effe3950d65364b008aca0a8ed0205a",
          "md5": "9d330d5ad39a22bf51e06734fd1fcde9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "size": 256833,
          "sha512": "563e1cd662afdf5c6a280e213e67a8b2787b3d15e132e7777b5157d18322f28e476fb96110de10266f61be3f4c142f10780c1ee13caa9d681d1023084c369fe8",
          "sha256": "80dff1685c1883fd08692a2dd0c287cadc2a9d540c524048d6b3d4d415da2d94",
          "sha1": "d613900b31cef2c912b4c6566ec696a79be5b11e",
          "md5": "c08b48888280016fad2229f60386e674"
        },
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "size": 256833,
          "sha512": "563e1cd662afdf5c6a280e213e67a8b2787b3d15e132e7777b5157d18322f28e476fb96110de10266f61be3f4c142f10780c1ee13caa9d681d1023084c369fe8",
          "sha256": "80dff1685c1883fd08692a2dd0c287cadc2a9d540c524048d6b3d4d415da2d94",
          "sha1": "d613900b31cef2c912b4c6566ec696a79be5b11e",
          "md5": "c08b48888280016fad2229f60386e674"
        }
      ]
    }
  ]
}
