{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "26.1.1-2.2.7.2616.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "size": 561693,
          "sha512": "fc7e4595495027a3d5269ee776f093bcb8f0deeace92ef8f2a212b6c13db76abe457ff600704eb49550854d218c9522b9e8721dd0d26fb57b1592d86345261b1",
          "sha256": "decbbfbde9506bb4aca45faacade5a2b84954b13868ad96354d8e789d76419ea",
          "sha1": "5b55f96b1bcb9711ecfd04e8052f2f0653f1bb86",
          "md5": "70ce9ca81dd74831153fa73a5eaab6a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2.jar",
          "size": 561693,
          "sha512": "fc7e4595495027a3d5269ee776f093bcb8f0deeace92ef8f2a212b6c13db76abe457ff600704eb49550854d218c9522b9e8721dd0d26fb57b1592d86345261b1",
          "sha256": "decbbfbde9506bb4aca45faacade5a2b84954b13868ad96354d8e789d76419ea",
          "sha1": "5b55f96b1bcb9711ecfd04e8052f2f0653f1bb86",
          "md5": "70ce9ca81dd74831153fa73a5eaab6a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "size": 256833,
          "sha512": "563e1cd662afdf5c6a280e213e67a8b2787b3d15e132e7777b5157d18322f28e476fb96110de10266f61be3f4c142f10780c1ee13caa9d681d1023084c369fe8",
          "sha256": "80dff1685c1883fd08692a2dd0c287cadc2a9d540c524048d6b3d4d415da2d94",
          "sha1": "d613900b31cef2c912b4c6566ec696a79be5b11e",
          "md5": "c08b48888280016fad2229f60386e674"
        },
        {
          "name": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "url": "factory_api-neoforge-26.1.1-2.2.7.2616.2-sources.jar",
          "size": 256833,
          "sha512": "563e1cd662afdf5c6a280e213e67a8b2787b3d15e132e7777b5157d18322f28e476fb96110de10266f61be3f4c142f10780c1ee13caa9d681d1023084c369fe8",
          "sha256": "80dff1685c1883fd08692a2dd0c287cadc2a9d540c524048d6b3d4d415da2d94",
          "sha1": "d613900b31cef2c912b4c6566ec696a79be5b11e",
          "md5": "c08b48888280016fad2229f60386e674"
        }
      ]
    }
  ]
}
