{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2516.1.jar",
          "size": 526134,
          "sha512": "7b73ff2cbc23d6ae31e7409cf49230554a17b100f13553f236630e7074bad6f209cd7b55cccecb983c40db00d7369b00ada7e9117a677b3e4285217aaca103e8",
          "sha256": "99f5bfc17aba1dca45b6bfe316c6170743a256488a0f164cb6ccf92ef4bacd01",
          "sha1": "93de69c635e4b62fdd8ef4de6b1594a8c752946c",
          "md5": "e22a4f6297997cc4fb33f6a5ac3ecaf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2516.1.jar",
          "size": 526134,
          "sha512": "7b73ff2cbc23d6ae31e7409cf49230554a17b100f13553f236630e7074bad6f209cd7b55cccecb983c40db00d7369b00ada7e9117a677b3e4285217aaca103e8",
          "sha256": "99f5bfc17aba1dca45b6bfe316c6170743a256488a0f164cb6ccf92ef4bacd01",
          "sha1": "93de69c635e4b62fdd8ef4de6b1594a8c752946c",
          "md5": "e22a4f6297997cc4fb33f6a5ac3ecaf4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2516.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2516.1-sources.jar",
          "size": 253599,
          "sha512": "493122826b5d0a7744653280112c4fef119d6a3a13a3e3f2ab1b258a36c77b9ab45467dbc30546b69515d363a0a01c3ff65b63dcad4a3476ad1adc1bad9758cc",
          "sha256": "9b29e0f4d43b7c86a5eb5d6af88eae40208bf20b7d98b89295bc727c6189b216",
          "sha1": "41efaeef61a7fa2f4bec2af22118afcdc3627cad",
          "md5": "6a65fd6bdcb1cd9c7a128829361577b8"
        }
      ]
    }
  ]
}
