{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.8.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.8.jar",
          "size": 359561,
          "sha512": "21d398c0926e497b1c42d03f4ca493eb984b35c1023a86a4f5dededb30c1800e764c785b14e3ce54618cc22df460ad363f894a3fcc77f0ac95613080a2bd9de8",
          "sha256": "e551357e569e5ee27af8960370bed3bcd944408c8b0b27fe8f41e0f899e59b9a",
          "sha1": "23cd47a27030b0577847a115e64a33544bdfe590",
          "md5": "825792137bb6d9992dc0772cf8ce607d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.8.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.8.jar",
          "size": 359561,
          "sha512": "21d398c0926e497b1c42d03f4ca493eb984b35c1023a86a4f5dededb30c1800e764c785b14e3ce54618cc22df460ad363f894a3fcc77f0ac95613080a2bd9de8",
          "sha256": "e551357e569e5ee27af8960370bed3bcd944408c8b0b27fe8f41e0f899e59b9a",
          "sha1": "23cd47a27030b0577847a115e64a33544bdfe590",
          "md5": "825792137bb6d9992dc0772cf8ce607d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.8-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.8-sources.jar",
          "size": 196505,
          "sha512": "33d03ed929ee0e203b4baede615855b2f4c111158d8bf18f8ab667d663a9af363dc449f0fcfd5790b8c63f9e2ba364e39ff76757e9613bfaee2291228e8cbfc3",
          "sha256": "40ee39a44dcba6219fb97e414d12cfa4fa36489cc9dbf02c201f0e25770ab396",
          "sha1": "b728dc6fc4256466353a0d2007d9533735b79ed5",
          "md5": "3515315c6e3e1b0b12d2fe051ee1fbfd"
        }
      ]
    }
  ]
}
