{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.6.2544.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2544.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2544.0.jar",
          "size": 536627,
          "sha512": "811574d84e7703dc8f78215bcf5d5502687db0aa88c406f6ef504891ee54eacfe41eb2908a680a76e3ddc041d94ef4234f7e6a1f357c7830a9d8e62c69504090",
          "sha256": "8e16bcd9827876747689ee422d6d211c82bf2a7110f05b913451aa4635e4bafb",
          "sha1": "98553ff5c9beeffc0a7ff2a7f2f4037a25b1bf5c",
          "md5": "3249970558511f10e1616f50f7cde0b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2544.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2544.0.jar",
          "size": 536627,
          "sha512": "811574d84e7703dc8f78215bcf5d5502687db0aa88c406f6ef504891ee54eacfe41eb2908a680a76e3ddc041d94ef4234f7e6a1f357c7830a9d8e62c69504090",
          "sha256": "8e16bcd9827876747689ee422d6d211c82bf2a7110f05b913451aa4635e4bafb",
          "sha1": "98553ff5c9beeffc0a7ff2a7f2f4037a25b1bf5c",
          "md5": "3249970558511f10e1616f50f7cde0b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.6.2544.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.6.2544.0-sources.jar",
          "size": 268194,
          "sha512": "e38ea748f4ba7b423703b2f6519adcb7152ee07b6db843190a67525d72b4793f10cbf34bdade0e84d17afa5f5688f7c44e4989b829effbcf469dd79c6f5daf5b",
          "sha256": "ae3efd63c5754f9e3b2d17cd43d0cce37e3e6fac68e503a66ad272d8e12dd51a",
          "sha1": "dc9d48e241a96f117521b244f914d7751d6e357f",
          "md5": "5ca19cd4056326480926606bceeddd75"
        }
      ]
    }
  ]
}
