{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2508.0.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2508.0.jar",
          "size": 14372612,
          "sha512": "3bc81982c7b1e35acba10af5f94048577c335c4ab0d59aedb4c2437dd41c572e04a3fd7811c5ee7fcdc04aeaac5842c2b315700e95f74269e07d391ebe0d1226",
          "sha256": "09b0375e7d6b6db52bc006d9a57bf4a9713fa13d4e9580e94f0fa721039b8539",
          "sha1": "e6e844e75f1c7932c211e77fe189825d43c56e3f",
          "md5": "d3026df53900f73c55e8bfad9e9e411d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2508.0.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2508.0.jar",
          "size": 14372612,
          "sha512": "3bc81982c7b1e35acba10af5f94048577c335c4ab0d59aedb4c2437dd41c572e04a3fd7811c5ee7fcdc04aeaac5842c2b315700e95f74269e07d391ebe0d1226",
          "sha256": "09b0375e7d6b6db52bc006d9a57bf4a9713fa13d4e9580e94f0fa721039b8539",
          "sha1": "e6e844e75f1c7932c211e77fe189825d43c56e3f",
          "md5": "d3026df53900f73c55e8bfad9e9e411d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2508.0-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2508.0-sources.jar",
          "size": 13553920,
          "sha512": "d55b9f4b3c7290996cee02665b3393e10ef6dd9def214a3a65a88ce205aa301a193df258701e75dd8cf511f1c48dc91f2c54231c4cc4ec746cb35d0396c039c2",
          "sha256": "d468f1f1961d677a822bc33ca5ff6072cdf1f4a6a24be38a3f93ffbff6121399",
          "sha1": "734b200c0a0903dce2f663c3c0604871146f466f",
          "md5": "00c5371360a05c906c7f2badbd0c21f2"
        }
      ]
    }
  ]
}
