{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2506.0.jar",
          "size": 478238,
          "sha512": "27c95fbcd76163102c04a1629729c4100aba9988f6746cd3257e0de4b44d670c0cc4dbfd15972dc2ac76fe3c083d6c7e47529f288abef9c3e78c387cf25d349f",
          "sha256": "7fc523bd9e465545a4f25703073ffeac8951ed506383bfb1e44da971f3362a89",
          "sha1": "8e045a49d7223005bb0c518ac356f0c547943724",
          "md5": "6527cd7d35819e98d7b02f43c78ae118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2506.0.jar",
          "size": 478238,
          "sha512": "27c95fbcd76163102c04a1629729c4100aba9988f6746cd3257e0de4b44d670c0cc4dbfd15972dc2ac76fe3c083d6c7e47529f288abef9c3e78c387cf25d349f",
          "sha256": "7fc523bd9e465545a4f25703073ffeac8951ed506383bfb1e44da971f3362a89",
          "sha1": "8e045a49d7223005bb0c518ac356f0c547943724",
          "md5": "6527cd7d35819e98d7b02f43c78ae118"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2506.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2506.0-sources.jar",
          "size": 237186,
          "sha512": "242d8649bf5d2869a46949418614e3a4eae1420bcc2f56b3c85ffe994f529baa07dafbef7a248f6e8c8223a355f4ef640f5847369508dbccf84452309abb8411",
          "sha256": "8bab50a3392b74b84ed41c7b13e4203039417cc133275b1abc9cedf2f386c3c7",
          "sha1": "d58a8eb0e60defd4b75775d7b441578d9841cff8",
          "md5": "855bd9d5f511af73bb888656ebb5c16f"
        }
      ]
    }
  ]
}
