{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.6.jar",
          "size": 466933,
          "sha512": "a3c6f45173fa1823f0596b6f68c0adabe5c8598892afce72ff043fa1bd6a340d24ed68011364d7dc0e0abc15e94e4cb8244381d0b9ca4ae17d47c38833918653",
          "sha256": "9e0083bf4aff554a8f22963c9d76f707c760a303dbbdc675c506afc29840ee08",
          "sha1": "30c29d461cd464ed2eee057558462c4c44ff6065",
          "md5": "80068f7b9be654b45ee93d99f569d847"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.6.jar",
          "size": 466933,
          "sha512": "a3c6f45173fa1823f0596b6f68c0adabe5c8598892afce72ff043fa1bd6a340d24ed68011364d7dc0e0abc15e94e4cb8244381d0b9ca4ae17d47c38833918653",
          "sha256": "9e0083bf4aff554a8f22963c9d76f707c760a303dbbdc675c506afc29840ee08",
          "sha1": "30c29d461cd464ed2eee057558462c4c44ff6065",
          "md5": "80068f7b9be654b45ee93d99f569d847"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2504.6-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2504.6-sources.jar",
          "size": 236658,
          "sha512": "b8204383f9ae85ca4ad552dc48b64fbaf350e1af0674db26391246b5c84a5e5939688b9dd13c18b6716a49d86a2af2d57de87609e1faeeaab95eecd7100c93d2",
          "sha256": "e81df680afab3b197e9f84df5c97a5314f13013494ac92fbbcf0a46d2d874907",
          "sha1": "baf8c9d2f6584029fd55d3fb8251db609239366d",
          "md5": "a01ad67b56ab8034c52f2932c2a9bb16"
        }
      ]
    }
  ]
}
