{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.10-1.8.5.2541.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.10-2.2.6.2541.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.8.5.2541.2.jar",
          "url": "legacy-neoforge-1.21.10-1.8.5.2541.2.jar",
          "size": 20019866,
          "sha512": "3198511e9ff56821353f13b5ed8610793a3b319c1f066a0dd7d7c3b563e1007d9f2e64da2c0489e1ba6ddffcaade88179a3a0286b0c7cc8f2bb08f5326edf6cf",
          "sha256": "537ae9075696a0d53e5723d94881b5f72cc5dceb244e024deec22e709996af39",
          "sha1": "2f1ce89f89e86089677c776919586835e67c17a8",
          "md5": "97f1c2143221f376bb175dc3f18da7c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.10-2.2.6.2541.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.8.5.2541.2.jar",
          "url": "legacy-neoforge-1.21.10-1.8.5.2541.2.jar",
          "size": 20019866,
          "sha512": "3198511e9ff56821353f13b5ed8610793a3b319c1f066a0dd7d7c3b563e1007d9f2e64da2c0489e1ba6ddffcaade88179a3a0286b0c7cc8f2bb08f5326edf6cf",
          "sha256": "537ae9075696a0d53e5723d94881b5f72cc5dceb244e024deec22e709996af39",
          "sha1": "2f1ce89f89e86089677c776919586835e67c17a8",
          "md5": "97f1c2143221f376bb175dc3f18da7c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.10-1.8.5.2541.2-sources.jar",
          "url": "legacy-neoforge-1.21.10-1.8.5.2541.2-sources.jar",
          "size": 19065139,
          "sha512": "69bada7764bcd2d7df6a30c7daeb3e15d1c750feb4f7fd252024ac9c5744ca8de0e1972d4a70d45517b4e97c6f392d8c9ec59170554d497e6fa57eb5d96730df",
          "sha256": "2345444d79692c5683920e67a5225f7a3fac93d73e7bcabea8b6caa35f976bbc",
          "sha1": "fd753d7659a5a7290f3111c477dfab0d11773b70",
          "md5": "c49c956940b20fc5f778268268ccea5d"
        }
      ]
    }
  ]
}
