{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.10.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.10.jar",
          "size": 454549,
          "sha512": "b1246ac908301f7e2f67ef53802490d920536649617d67f38ee26e0f6a5cf893da8df706813407dd2c7f08ac87bcf1dc1873a2cadf2bb6a471d805ce87dd900b",
          "sha256": "dadd7ad79a9766ec2d75b252b5a68c48c4a45d50fa303044b9f50ddd2600a18f",
          "sha1": "a71a04ecbd4def8e35532777501cae870f0b7361",
          "md5": "17f7c906a12a747b7003513506a64c20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.10.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.10.jar",
          "size": 454549,
          "sha512": "b1246ac908301f7e2f67ef53802490d920536649617d67f38ee26e0f6a5cf893da8df706813407dd2c7f08ac87bcf1dc1873a2cadf2bb6a471d805ce87dd900b",
          "sha256": "dadd7ad79a9766ec2d75b252b5a68c48c4a45d50fa303044b9f50ddd2600a18f",
          "sha1": "a71a04ecbd4def8e35532777501cae870f0b7361",
          "md5": "17f7c906a12a747b7003513506a64c20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.10-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.10-sources.jar",
          "size": 228363,
          "sha512": "4359d64d19c0adb39f036091255e8db9e596723b4a94aa71c814d2f6e95dbb0ee29e7b1f019ea291791c395c1aca371e89ce96ea5218d2bdc92e011a591e399b",
          "sha256": "42a51344028082055e601291db9ba0e9188426d5d3f529f1530747b39a798a24",
          "sha1": "4269965f8fcc4ad4aa22bc48ca35303a97ef1ae9",
          "md5": "4a495806f28619f0a23ab24fe5a0837e"
        }
      ]
    }
  ]
}
