{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2517.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2517.0.jar",
          "size": 531112,
          "sha512": "df30a88313d75eeb25e1bed148ed7f60b827d9c44372e625e56776b154009e483950774d29299b2bd123b9b6d00a4a296aae0e589fa82109d4e68cd6c37acef0",
          "sha256": "ed663552c011f2111e6427f2dd0b0ff705eb21347321813a1e0fa63a088c7af1",
          "sha1": "91e3f0bf9f087819a726d0e948e6fc9b48506f25",
          "md5": "542c96e50331f635a97d21a6212cd8f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2517.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2517.0.jar",
          "size": 531112,
          "sha512": "df30a88313d75eeb25e1bed148ed7f60b827d9c44372e625e56776b154009e483950774d29299b2bd123b9b6d00a4a296aae0e589fa82109d4e68cd6c37acef0",
          "sha256": "ed663552c011f2111e6427f2dd0b0ff705eb21347321813a1e0fa63a088c7af1",
          "sha1": "91e3f0bf9f087819a726d0e948e6fc9b48506f25",
          "md5": "542c96e50331f635a97d21a6212cd8f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2517.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2517.0-sources.jar",
          "size": 254574,
          "sha512": "5c90c99423e6223bceb4abd1aa919de2c011fd8479745c8b6f8f70982510c9bfa4d8c85785948a58c1491e7775ca8653d4ea0cad1eb63eba4c1664429deb4fc8",
          "sha256": "35faf6ac014aa5456eb6c95750dcf64d70bd3695e0dd4bece13e9c7e12410347",
          "sha1": "35f02b618584a28b81dd857ce21a8cd80a05d686",
          "md5": "97b92de04a9a8b485172fc1fecd6d046"
        }
      ]
    }
  ]
}
