{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.0.2512.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2512.1.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2512.1.jar",
          "size": 18260725,
          "sha512": "408cc89593dce4a1799fea3df185672325eadb97291416d738226b34d93d2fe16ab4892f80aadfb6ca6b64ba294b600e13b03175d6afc44cd8e8e97208166b42",
          "sha256": "8c0b799f7f4d5f7724e91ea758b749be763d8f10a6e550831f48cf3695252c16",
          "sha1": "788c2bec7eaad44173e37b7f4fe93baee6a37f5a",
          "md5": "f407fdd4da684dce8c9c38d1152e9f9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2512.1.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2512.1.jar",
          "size": 18260725,
          "sha512": "408cc89593dce4a1799fea3df185672325eadb97291416d738226b34d93d2fe16ab4892f80aadfb6ca6b64ba294b600e13b03175d6afc44cd8e8e97208166b42",
          "sha256": "8c0b799f7f4d5f7724e91ea758b749be763d8f10a6e550831f48cf3695252c16",
          "sha1": "788c2bec7eaad44173e37b7f4fe93baee6a37f5a",
          "md5": "f407fdd4da684dce8c9c38d1152e9f9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2512.1-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2512.1-sources.jar",
          "size": 17422332,
          "sha512": "01f439bf864113bac739b5480b9db17e1b68461209f7310e33b6574238eb798e3a8ec57cda17634b050b352afc9f1aba20e0c98aaeb05f0044722985da3bb750",
          "sha256": "c825b704236588d890b5a2cd847aaa4b777436a54b6f8367685b37c9c2d0d60c",
          "sha1": "4886706dda2cfd96851ea1a379b8ca1483410500",
          "md5": "e6b8670834558409019cb63d919ae0d6"
        }
      ]
    }
  ]
}
