{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.5-lts",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.5-lts.jar",
          "url": "legacy-forge-1.21.1-1.8.5-lts.jar",
          "size": 19906467,
          "sha512": "2881c57192291115c1e14828b113534a0dcb07c9fba8224735c27a1f9e67f90a16e8513f259f1d217133c55f5724ab719f0da9fe3637f2183bcaa4e3749e9b04",
          "sha256": "58c8c481bae8b67b8449b33a1fb722bb21db08a10479976eb2a5325ac845f509",
          "sha1": "10123bac4c3832c0857097f171563dc845c7a070",
          "md5": "47f17ecf8f52f08c96cd1acf74caa431"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.5-lts.jar",
          "url": "legacy-forge-1.21.1-1.8.5-lts.jar",
          "size": 19906467,
          "sha512": "2881c57192291115c1e14828b113534a0dcb07c9fba8224735c27a1f9e67f90a16e8513f259f1d217133c55f5724ab719f0da9fe3637f2183bcaa4e3749e9b04",
          "sha256": "58c8c481bae8b67b8449b33a1fb722bb21db08a10479976eb2a5325ac845f509",
          "sha1": "10123bac4c3832c0857097f171563dc845c7a070",
          "md5": "47f17ecf8f52f08c96cd1acf74caa431"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.5-lts-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.5-lts-sources.jar",
          "size": 19035701,
          "sha512": "9fbf8da9d87a21440f92e44c5259dd199b3446033a41f6aa1e5551cbc5ff40b88c0989104c3b0a9376cdf62d92fd9702ea5ac9319a937c4f74bdf7f9f2f58e71",
          "sha256": "d89c75513f28d9db1f028566b0ac87bcbabeb6169832b9078f96bab087b01b48",
          "sha1": "13cb2cd57bffae419d47cfd10567dfe8fb753c17",
          "md5": "11194b04e1b3f4496c2ad90ed3aad432"
        }
      ]
    }
  ]
}
