{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.4-1.7.10.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.7.10.2504.4.jar",
          "url": "legacy-fabric-1.20.4-1.7.10.2504.4.jar",
          "size": 14253504,
          "sha512": "934db1a5cb24debf281e42a0bdf4f561560d848282d35621d0202e33db6e552efc1bc8084702bc5f138e2b5523e63f138914b859f1175b5645c7e3171ba4d8ed",
          "sha256": "fa3dd46e969e0d631fd490d26c1069befc3dec93cdf584d5635aa99e9fc66610",
          "sha1": "ec75b9d5c9a3e2e5ce5029a3bbed7948e5ebf3fc",
          "md5": "a940bbd1a2ac5253ec70359ff3d1b635"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.4-2.2.2504.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.7.10.2504.4.jar",
          "url": "legacy-fabric-1.20.4-1.7.10.2504.4.jar",
          "size": 14253504,
          "sha512": "934db1a5cb24debf281e42a0bdf4f561560d848282d35621d0202e33db6e552efc1bc8084702bc5f138e2b5523e63f138914b859f1175b5645c7e3171ba4d8ed",
          "sha256": "fa3dd46e969e0d631fd490d26c1069befc3dec93cdf584d5635aa99e9fc66610",
          "sha1": "ec75b9d5c9a3e2e5ce5029a3bbed7948e5ebf3fc",
          "md5": "a940bbd1a2ac5253ec70359ff3d1b635"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.4-1.7.10.2504.4-sources.jar",
          "url": "legacy-fabric-1.20.4-1.7.10.2504.4-sources.jar",
          "size": 13453730,
          "sha512": "342cadc3766090f371a336dc63fe96ada54cfea1166e27c53ca04b8d63ecb12d8ef9d0840efa857094a9ddfb5cba3fa6601fa1c0494199d11c3f6d4db933288f",
          "sha256": "81a8991ce2553fc18db3ed1ef447575bde907d204a442e0e73987ec4f75bd46c",
          "sha1": "cee4a4932d13442c710f62450838d60cf0e18ce1",
          "md5": "310b0b33957d23c6aefcc52cc7c7be8f"
        }
      ]
    }
  ]
}
