{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2500.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.5.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.5.jar",
          "size": 364522,
          "sha512": "565bc41343cd59f5abcc38deed231189e0b3ba714c3cefe84cb877f99ecb7e5a26c7bfc5f24f75ed57af1689eb75bf4797c4a3b3d024cc17b07f18dd16a63e11",
          "sha256": "13796ad9a367d7b847e03eb38e6cbecd0996740050ed3b5978674390733a552d",
          "sha1": "86caf87b13aaddcbf8ff1e045b0978e13ac08da4",
          "md5": "7d0ae17db780001acd530b7c8bb29671"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.5.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.5.jar",
          "size": 364522,
          "sha512": "565bc41343cd59f5abcc38deed231189e0b3ba714c3cefe84cb877f99ecb7e5a26c7bfc5f24f75ed57af1689eb75bf4797c4a3b3d024cc17b07f18dd16a63e11",
          "sha256": "13796ad9a367d7b847e03eb38e6cbecd0996740050ed3b5978674390733a552d",
          "sha1": "86caf87b13aaddcbf8ff1e045b0978e13ac08da4",
          "md5": "7d0ae17db780001acd530b7c8bb29671"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.5-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.5-sources.jar",
          "size": 193402,
          "sha512": "a3025fc07eb02695f995f43d593e81cfb5ca08caa26b40fe53fcee1e9c48af4fa95e127b1c6e3c38a288a224fb3fc318d0f998e2b847f403937ecea98aca0b1c",
          "sha256": "55712cccacab299783d405563e4132ef3b7662a9d37b9720c660f07929f6b33b",
          "sha1": "9acc387d83699009a2d305b0fa7b9cfbf79adbbf",
          "md5": "40dc0b949d37548bfb1b00a10e287c3f"
        }
      ]
    }
  ]
}
