{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.3-1.1.2518.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.3-1.1.2518.1.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.3-1.1.2518.1.jar",
          "size": 643002,
          "sha512": "1590ef0dfb143a6ffa3270c26ac77bd4f81e978ea5bdf14e2e1b5e0a6a2e55fc456d5190cb1d371854ad0a63158a35aab2332f2e77259dfe4e40bd30729ddaa6",
          "sha256": "065a2ace6f821ffaa47664976602ed8f8f02b940ea158a60932d008f2ed53e30",
          "sha1": "9fa63652fc0193d6eab5d25e58ddd138a08a51ea",
          "md5": "d902ae92b3c37cd9d6366701ec07c9eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.3-1.1.2518.1.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.3-1.1.2518.1.jar",
          "size": 643002,
          "sha512": "1590ef0dfb143a6ffa3270c26ac77bd4f81e978ea5bdf14e2e1b5e0a6a2e55fc456d5190cb1d371854ad0a63158a35aab2332f2e77259dfe4e40bd30729ddaa6",
          "sha256": "065a2ace6f821ffaa47664976602ed8f8f02b940ea158a60932d008f2ed53e30",
          "sha1": "9fa63652fc0193d6eab5d25e58ddd138a08a51ea",
          "md5": "d902ae92b3c37cd9d6366701ec07c9eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.3-1.1.2518.1-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.3-1.1.2518.1-sources.jar",
          "size": 585517,
          "sha512": "991cb550930dedcfb791dadcaf8202d500aa3882f2ca162f45fcf8f47317f96afa14c635c9cf4442b33081d020dd86e91b420563fe564e1427456e91acd6d6dc",
          "sha256": "df06aba95d34505104bfb75e16ece7f677184a1d9ae52eeb037d0fc4c16560d2",
          "sha1": "22a933e15d34261b1ec6f3dbbb788b313bdf5851",
          "md5": "692c4a86d3438a0733ec4a86d624e14c"
        }
      ]
    }
  ]
}
