{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2507.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.3.jar",
          "size": 497544,
          "sha512": "4d4558a1b0e81b9ce1c4ff58fb7280a5be7b7955f99fbea29857262c0c26deed6008fb26f08fc4ada509ef64d5d91afad9d608c6d3f4fa0a00e2f9c2de873198",
          "sha256": "a9c10cb9b4fbca9b2dcf01f7d6cd73556fb88c18318daffee0a3e5a4cc5bb926",
          "sha1": "72c8f4d04f5a5872b9ac03c6348dbf91befce826",
          "md5": "c2ec190464c339f3869f608d66192e0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.3.jar",
          "size": 497544,
          "sha512": "4d4558a1b0e81b9ce1c4ff58fb7280a5be7b7955f99fbea29857262c0c26deed6008fb26f08fc4ada509ef64d5d91afad9d608c6d3f4fa0a00e2f9c2de873198",
          "sha256": "a9c10cb9b4fbca9b2dcf01f7d6cd73556fb88c18318daffee0a3e5a4cc5bb926",
          "sha1": "72c8f4d04f5a5872b9ac03c6348dbf91befce826",
          "md5": "c2ec190464c339f3869f608d66192e0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.3-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.3-sources.jar",
          "size": 244124,
          "sha512": "fb77fcc48794a831db674faaa0cfe1718ae3e52ef451b21b40aefacf6a708331b692111dea60085ecfe22ff4aac40cae363f2e7d74760039a24ba36f403b2595",
          "sha256": "2d5c81341bc9b5ac4d88b9ba10c7325094fc3bcf5278acf31b46dd054cbe3bb2",
          "sha1": "baecef4e7562ef2a00e3a61218261bd431b54563",
          "md5": "14f4bf0889398b5deb919a7e1d7de626"
        }
      ]
    }
  ]
}
