{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2512.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2512.0.jar",
          "size": 18265715,
          "sha512": "36749612476c91673f4115902827b6cc7258d6f28951fbdb93d8484da213da6c08d0414a44c92e42eb852d335c5eebebc413d5f2c742e942fc283900e111a86a",
          "sha256": "87231d653ce655f4e1ab556c965ce4293fbe492ecb6ddbac81053548ff62ff83",
          "sha1": "6f5bcd04b56746b052daf77540a6c1a549d81549",
          "md5": "79c13b709593a920638c184de69a5b32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2512.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2512.0.jar",
          "size": 18265715,
          "sha512": "36749612476c91673f4115902827b6cc7258d6f28951fbdb93d8484da213da6c08d0414a44c92e42eb852d335c5eebebc413d5f2c742e942fc283900e111a86a",
          "sha256": "87231d653ce655f4e1ab556c965ce4293fbe492ecb6ddbac81053548ff62ff83",
          "sha1": "6f5bcd04b56746b052daf77540a6c1a549d81549",
          "md5": "79c13b709593a920638c184de69a5b32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2512.0-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2512.0-sources.jar",
          "size": 17428322,
          "sha512": "8278de8ce4cda631e7dd5f3339b77ae742076cbe8ae19fabd3bcb2227493ff89d1cf7aad067bba86cc6f18008120762652b134ad5cb1b4a5ddbea6d78be4dcc1",
          "sha256": "f8a7acca2c680266549c4593604749419c4f6a93f5e359a396d73c165e40e9db",
          "sha1": "bfcdc5daf38a9855f993e534b34d05be88e46691",
          "md5": "f8f77290061810aec3da87cf57604477"
        }
      ]
    }
  ]
}
