{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2516.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.6.jar",
          "size": 697542,
          "sha512": "05a0b1d97dfb239d6918f08d2beaa7b5112373dcdf08c1c2f7dd45fdeb286e33906a8c17df1b9553511e1f76f03ab20e26fc643d376bc2cf06bd17e7a90e0a4b",
          "sha256": "f86175da91191b368e98f779c98057ba36a8f1c230119ea9f09194d12534b7f6",
          "sha1": "247bb4b7246b0dbcc3dabe771906ed76997fb573",
          "md5": "2d17c657d4a470126acf1d1244952c9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.6.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.6.jar",
          "size": 697542,
          "sha512": "05a0b1d97dfb239d6918f08d2beaa7b5112373dcdf08c1c2f7dd45fdeb286e33906a8c17df1b9553511e1f76f03ab20e26fc643d376bc2cf06bd17e7a90e0a4b",
          "sha256": "f86175da91191b368e98f779c98057ba36a8f1c230119ea9f09194d12534b7f6",
          "sha1": "247bb4b7246b0dbcc3dabe771906ed76997fb573",
          "md5": "2d17c657d4a470126acf1d1244952c9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2516.6-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2516.6-sources.jar",
          "size": 253947,
          "sha512": "ebb76a580e2f4eb809d4c1ef29cebb101b04145ce78831fedae4d2b028dfd1c73ab7f7e03e024a391ef83e85c31538f88de312d1e65164d2f3bdd164848d998d",
          "sha256": "7d612fb53c8ecd317087ac995bf69db4390aaa4d49e19047f22520e2624c4cb5",
          "sha1": "3d513ca10dd3d2fe8162e9f6ae920be134f9064a",
          "md5": "b036050ff1ce4c65878789191dcd724d"
        }
      ]
    }
  ]
}
