{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.7.10.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2508.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2508.0.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2508.0.jar",
          "size": 14390432,
          "sha512": "f77971fd90564fe3ddd06e30ce4985d601ebff648ab2f791e5945323cd33f47fc9dc830c3739903a7bd8e0ad35d510788bf47940c303359357d3e06f50681a44",
          "sha256": "b872c681d55a6ff0a54e025f9cec0e281d7483dea62848a37015450ec95b1f79",
          "sha1": "e53eda483502d5e416e87fe4100506d2e12930d8",
          "md5": "0945345678b4856f5f89b993244ceb71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2508.0.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2508.0.jar",
          "size": 14390432,
          "sha512": "f77971fd90564fe3ddd06e30ce4985d601ebff648ab2f791e5945323cd33f47fc9dc830c3739903a7bd8e0ad35d510788bf47940c303359357d3e06f50681a44",
          "sha256": "b872c681d55a6ff0a54e025f9cec0e281d7483dea62848a37015450ec95b1f79",
          "sha1": "e53eda483502d5e416e87fe4100506d2e12930d8",
          "md5": "0945345678b4856f5f89b993244ceb71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2508.0-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2508.0-sources.jar",
          "size": 13554114,
          "sha512": "07370476067b2ab5b5223a4c834bccef7b82c47c92dd7fbfa2aabf52c9c02a69757a29ba9676655b0b767a65b573b54e1f010ad94265e54d7200595fe365a2a5",
          "sha256": "5aed552753528c5358f6e4d85219e82952561c2a74a08ce80db75928d991650a",
          "sha1": "a1e6128a9f2023da48be805c273a44551f09b13f",
          "md5": "912511ed70b0aba439e20012790f0d87"
        }
      ]
    }
  ]
}
