{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2502.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.15.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.15.jar",
          "size": 461701,
          "sha512": "07792c7d96e26e60038da0a5517c90213b0993b4a99dfe4da651a98c9444718cf79bbbe5a30ebc7e247132039f910dd8b9dc996e0e2d68945fa82ae0cec07d5b",
          "sha256": "95603ad00b2cb09ec940cadacdf4f276bde0791939014b99c9e0c2ef3a248c00",
          "sha1": "b272c4ba44602f1fe76ee459bf855c1646e4a1bd",
          "md5": "04fd250be38552eab55d59b152f1df0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.15.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.15.jar",
          "size": 461701,
          "sha512": "07792c7d96e26e60038da0a5517c90213b0993b4a99dfe4da651a98c9444718cf79bbbe5a30ebc7e247132039f910dd8b9dc996e0e2d68945fa82ae0cec07d5b",
          "sha256": "95603ad00b2cb09ec940cadacdf4f276bde0791939014b99c9e0c2ef3a248c00",
          "sha1": "b272c4ba44602f1fe76ee459bf855c1646e4a1bd",
          "md5": "04fd250be38552eab55d59b152f1df0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.15-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.15-sources.jar",
          "size": 231976,
          "sha512": "bcc03e505d7e8e617a2bb4125499bd4e59fd84d472b07627637025464e9d658d07cd6f84eb10344a0bf47ed66373608c5139d5468cdc5821f96c2a9e1caab97b",
          "sha256": "6ac1af545f82da53d9f675d02b16e065360221c8e3b764fb273b8c9ca32ec5bf",
          "sha1": "d6624b3853001bbf2042c4f1c870ca4944c70f07",
          "md5": "3b2fc333871d4700bb9e2ed1d05f8044"
        }
      ]
    }
  ]
}
