{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.7.10.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2508.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-forge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2508.0.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2508.0.jar",
          "size": 14385758,
          "sha512": "ea5251ddbe783c2d4b69b95842c75fc6f02db78c5dae1aac166d9000aba69433c3da764618cf8c1a499186390cf64c4b5a27c5b4e0b096d0cf6b4dcc15cfcb10",
          "sha256": "cf3937f2ca2fb4f9827f183417fcb4f519ceee87624aa37ec9835425801818f3",
          "sha1": "bff68a7e0d595ecee701c626160c8e65a3c6053b",
          "md5": "26182d4c8b7e6a62daf6d2305db257dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2508.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2508.0.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2508.0.jar",
          "size": 14385758,
          "sha512": "ea5251ddbe783c2d4b69b95842c75fc6f02db78c5dae1aac166d9000aba69433c3da764618cf8c1a499186390cf64c4b5a27c5b4e0b096d0cf6b4dcc15cfcb10",
          "sha256": "cf3937f2ca2fb4f9827f183417fcb4f519ceee87624aa37ec9835425801818f3",
          "sha1": "bff68a7e0d595ecee701c626160c8e65a3c6053b",
          "md5": "26182d4c8b7e6a62daf6d2305db257dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2508.0-sources.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2508.0-sources.jar",
          "size": 13560066,
          "sha512": "9db3b58fba09f2f2246c6ad9fe723a8d3222f96387bf0eccdfba3fb27870871541cdab13768639c9c5b198c35496a9a38089351bbc2c2780808def824dbc8f5e",
          "sha256": "9fd7cf6c8cbb3ef714cfd5714d9b4a26492329227ad36fe000375cfe13a188b9",
          "sha1": "cc71ee9c75ff030dbdfa53314841dc87bc2039d0",
          "md5": "f3b6e6d56e834bcedb8413744ec2827e"
        }
      ]
    }
  ]
}
