{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "size": 443650,
          "sha512": "a44ac94ed70295a79472404e544af0de39869bbc360e28e4a26d14d97eb9833455a5b417f9cbc86663918766f87fc54b57bc61558c45faae61e41351bb298624",
          "sha256": "b7fd7d6ddfc2a79431668a62dbe4b18b397457410dfa1b34bfe996fe95994f18",
          "sha1": "903b7f8945e945c45b11debf7b85ef62c9241ac4",
          "md5": "9a3c05eae0a5211f07be94ca08cce72b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "size": 443650,
          "sha512": "a44ac94ed70295a79472404e544af0de39869bbc360e28e4a26d14d97eb9833455a5b417f9cbc86663918766f87fc54b57bc61558c45faae61e41351bb298624",
          "sha256": "b7fd7d6ddfc2a79431668a62dbe4b18b397457410dfa1b34bfe996fe95994f18",
          "sha1": "903b7f8945e945c45b11debf7b85ef62c9241ac4",
          "md5": "9a3c05eae0a5211f07be94ca08cce72b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.9-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.9-sources.jar",
          "size": 228164,
          "sha512": "aebcf138826c9f8d8fc48bf604b4d7a737f85193230a3ed7a93c0dc238370bddb3c8477d68308ba4f42996283332c41c96e8a219fb7ddb5267a434a67d72c5b7",
          "sha256": "7ea0c5b996517bc6ada72b8623b38eb06c7ba651324d27b43a1945e974ba3fd0",
          "sha1": "81056cbff1a72f905e37cad123be86e262b7790a",
          "md5": "17ac88fa0e0768b584eaabab302487ae"
        }
      ]
    }
  ]
}
