{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2502.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "size": 433236,
          "sha512": "db076560319087dab63f53559f4a09f0d739be8225d4d0a784f561a106fb503c25391d14b68545eab39f475fbf783def2383b62f13acc101e9761d49896e560f",
          "sha256": "0f5b2bd14ac633485eb9d54f85161fde9ba33c1db2fcc8046b9492ef833beac5",
          "sha1": "50a0a1edc728fd4f6b2c496a409fd6f11e709aa9",
          "md5": "60399810308a4a9ae8b58d7dba2769d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.9.jar",
          "size": 433236,
          "sha512": "db076560319087dab63f53559f4a09f0d739be8225d4d0a784f561a106fb503c25391d14b68545eab39f475fbf783def2383b62f13acc101e9761d49896e560f",
          "sha256": "0f5b2bd14ac633485eb9d54f85161fde9ba33c1db2fcc8046b9492ef833beac5",
          "sha1": "50a0a1edc728fd4f6b2c496a409fd6f11e709aa9",
          "md5": "60399810308a4a9ae8b58d7dba2769d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.9-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.9-sources.jar",
          "size": 222261,
          "sha512": "e3c99df6612660b94f88c4283413c78bd221d21588ed3e55ab09ec49d816301bbcc88146420a869708473f8e89068ec6eef2c28ee4224f9fb89c389936b42a95",
          "sha256": "dc5eac3e656670a622d283669cb499257d0a27b030c4f8dbe04f33fce491b22d",
          "sha1": "fd1b02d87c54ab84f137a6940beb91d950fb5fb1",
          "md5": "ca355c0c7ceae2f8eecf25853b3f93fa"
        }
      ]
    }
  ]
}
