{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2508.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.4.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.4.jar",
          "size": 692924,
          "sha512": "8dc6f20d3e8498e243ee671250f3cdb3d708bc90fe968d35ba87f07078d7c52dac4e1d18d25063159416169e2ae42e6f69f2171e3ea4bbe6a599b3c59d11b335",
          "sha256": "49a24512fb56dc19fec4cf4dd9c8a461311eb64aebde79aee59e4d0afc1493f9",
          "sha1": "bb0307b8ee666f9f52dcca88ed3ad2264314ac58",
          "md5": "58d9a8ba53c37fa35449a066ee911691"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.4.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.4.jar",
          "size": 692924,
          "sha512": "8dc6f20d3e8498e243ee671250f3cdb3d708bc90fe968d35ba87f07078d7c52dac4e1d18d25063159416169e2ae42e6f69f2171e3ea4bbe6a599b3c59d11b335",
          "sha256": "49a24512fb56dc19fec4cf4dd9c8a461311eb64aebde79aee59e4d0afc1493f9",
          "sha1": "bb0307b8ee666f9f52dcca88ed3ad2264314ac58",
          "md5": "58d9a8ba53c37fa35449a066ee911691"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2508.4-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2508.4-sources.jar",
          "size": 248207,
          "sha512": "962d6cf46f553cba11c41b8d6931c901cff91796bdf86b8165855c0d8d71727eeddba174dde93d763c62b3892c1a17af574e434da9bcb84020063bef844156ec",
          "sha256": "eae4569d5c868557f1571c2a07acae525b7a31de72872f21fbcf508bd5a2e118",
          "sha1": "9734f204c34967a2856819c67cad2baf5677f92e",
          "md5": "4be65881fca8a8185e60d06eaf3fb2cf"
        }
      ]
    }
  ]
}
