{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2518.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-forge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.3.jar",
          "size": 19777711,
          "sha512": "9dd2abf201262c32e4bf542bbe446d620d0291531c2c6bdd9d24ea12531abb0cda2be4dec62308ced66a3f36704e8097763a529871e2c60ae0e040619469d559",
          "sha256": "b9445a1f2d6130041547f0d9fb2623313699ec18e7498b924d8943b1d3913fcc",
          "sha1": "f44750809363c5c5f157f3f5d25c571f996b9379",
          "md5": "85d67e06289f56bacdc49062c778cda6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.3.jar",
          "size": 19777711,
          "sha512": "9dd2abf201262c32e4bf542bbe446d620d0291531c2c6bdd9d24ea12531abb0cda2be4dec62308ced66a3f36704e8097763a529871e2c60ae0e040619469d559",
          "sha256": "b9445a1f2d6130041547f0d9fb2623313699ec18e7498b924d8943b1d3913fcc",
          "sha1": "f44750809363c5c5f157f3f5d25c571f996b9379",
          "md5": "85d67e06289f56bacdc49062c778cda6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2518.3-sources.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2518.3-sources.jar",
          "size": 18910455,
          "sha512": "f4233032118b80b70e9c71b72dc19e038ea17118834ba80cba4668cefb5b3fc48a8d0720b0aa2a7943fe01b0403300bb5091771d485a6182225473c448b6dc8c",
          "sha256": "f2a134684f5fb95dad514c969ca3fbdb510603a1e6dd95c941be7b0d1e45806f",
          "sha1": "10c581758a2221b78071d53804ea82cbcba2b8f3",
          "md5": "1dd8e276f377e348cd54881b4891fec8"
        }
      ]
    }
  ]
}
