{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2513.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.5.jar",
          "size": 497896,
          "sha512": "cff4465dffe939920d920111e2e7b0bcb87a1fd02d390456a6410885197e4553d370c670bb252bceecfc1bee6f87ac72dbb0f6b370fb28386ea782e367ad9467",
          "sha256": "42c4ef23922cd167080a22ae5aedc66420fdddac9afd375d72a899aa381f5d3d",
          "sha1": "e0485dd0e4b5dd8abbd9e9f9f6aeb7b3041b03ac",
          "md5": "12506eba35d05429dd8a5b95e37c4f44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.5.jar",
          "size": 497896,
          "sha512": "cff4465dffe939920d920111e2e7b0bcb87a1fd02d390456a6410885197e4553d370c670bb252bceecfc1bee6f87ac72dbb0f6b370fb28386ea782e367ad9467",
          "sha256": "42c4ef23922cd167080a22ae5aedc66420fdddac9afd375d72a899aa381f5d3d",
          "sha1": "e0485dd0e4b5dd8abbd9e9f9f6aeb7b3041b03ac",
          "md5": "12506eba35d05429dd8a5b95e37c4f44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.5-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.5-sources.jar",
          "size": 250285,
          "sha512": "95114f406c5595057d0957f32e2391239203800a39ace76c95325197fed51cd572901d1a4fbe22fd0e6ac63e7246f50e7e70d2433928fda3b1f19841091e5a88",
          "sha256": "c4bed863e52893de8f84232616dfdf53495a4f93de5f9c969cf15e51733acb32",
          "sha1": "da901e229c4048a93498bd72e8be14d40b841316",
          "md5": "1fe889ad0bb94c1514d04587976682c2"
        }
      ]
    }
  ]
}
