{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2515.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2515.0.jar",
          "size": 713292,
          "sha512": "e8fd8588540ba73a15e20d9348790291d0cab161c726a6d05ae45f325553b07ac4c8851e52ded822a0a0853a99fee5d717409e576610dbcab18c13c7697d4225",
          "sha256": "a7eb5601aee2aff7b06abd259507ac215e1ced09db708473ec3d63c9e24df47e",
          "sha1": "593a1f869427e5f481c10427c7c372be178563e9",
          "md5": "edd25bc70641563f92ac206bb0b84b96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2515.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2515.0.jar",
          "size": 713292,
          "sha512": "e8fd8588540ba73a15e20d9348790291d0cab161c726a6d05ae45f325553b07ac4c8851e52ded822a0a0853a99fee5d717409e576610dbcab18c13c7697d4225",
          "sha256": "a7eb5601aee2aff7b06abd259507ac215e1ced09db708473ec3d63c9e24df47e",
          "sha1": "593a1f869427e5f481c10427c7c372be178563e9",
          "md5": "edd25bc70641563f92ac206bb0b84b96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2515.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2515.0-sources.jar",
          "size": 254889,
          "sha512": "0549282acd68229aba596d1dc8f71b2bb8501648c3b3be1254df19a6fe05fd83d0e365d758247eae2f5ecc5ebdeb0b53b8a85679dfdeb389d992efc864ed5e5f",
          "sha256": "f332f8a16a36ecce35c7e9805703c9aa4fcc54e3eb7e8736104a6fe217ef0d23",
          "sha1": "b4a43a9ffd5b277a587c6da0e496d01dbe10a717",
          "md5": "463ed706bf4ccb22adcadf9223b273af"
        }
      ]
    }
  ]
}
