{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2510.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.6.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.6.jar",
          "size": 681764,
          "sha512": "08e31054c0268b14af1b4309d0e0797c5c4bff50b8412e043d901f5f1fa8d09841b4cf385190db532fb94f1d7a0dbb6ed4da80d63a94443f9497d88d27b5b104",
          "sha256": "e759df07d04c170a3e7f49ff0d7f713869ca49de9884afa7b92169596bb47158",
          "sha1": "2f34c2b97e291b9e76db58dbdbea134de7ed1b53",
          "md5": "f6028d4b0c8b34d154a01069b2bfa146"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.6.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.6.jar",
          "size": 681764,
          "sha512": "08e31054c0268b14af1b4309d0e0797c5c4bff50b8412e043d901f5f1fa8d09841b4cf385190db532fb94f1d7a0dbb6ed4da80d63a94443f9497d88d27b5b104",
          "sha256": "e759df07d04c170a3e7f49ff0d7f713869ca49de9884afa7b92169596bb47158",
          "sha1": "2f34c2b97e291b9e76db58dbdbea134de7ed1b53",
          "md5": "f6028d4b0c8b34d154a01069b2bfa146"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.6-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.6-sources.jar",
          "size": 252430,
          "sha512": "4a5a0f4623313e2cd2695d414ca241c593e8eeafb5442f0d97a5f4400e1f21e491541925d6420c32afea46ed0efa8dc8ec223bbe4b82ccacf93db50289a766b5",
          "sha256": "3e2a28d7d29cbad395aae138cdcdeab923bcbca51a8ad5e482580d51ef3e54c7",
          "sha1": "0c242e2fc2cb23ef383a4052a2d9d8ecc04f873c",
          "md5": "711e5bdd8723aafe88b3493895dc0229"
        }
      ]
    }
  ]
}
