{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2504.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.7.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.7.jar",
          "size": 510544,
          "sha512": "04d63c238d0ecb0e64582337a948f8aa89061c537b25fa314615c4fb556c1371d83eed5f39f137473c0abadc3ee10dda02e4db0a708f1b9811f5e2d6c5d9657b",
          "sha256": "ea41fa3c377d62765a1ce6a44773ecc9205369ba80488a6c255ec515844ff4d2",
          "sha1": "a6f2599f1648712de018b2214e883bf31c7f418a",
          "md5": "859d4927e2b84d6e0d446ac0ce4b699f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.7.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.7.jar",
          "size": 510544,
          "sha512": "04d63c238d0ecb0e64582337a948f8aa89061c537b25fa314615c4fb556c1371d83eed5f39f137473c0abadc3ee10dda02e4db0a708f1b9811f5e2d6c5d9657b",
          "sha256": "ea41fa3c377d62765a1ce6a44773ecc9205369ba80488a6c255ec515844ff4d2",
          "sha1": "a6f2599f1648712de018b2214e883bf31c7f418a",
          "md5": "859d4927e2b84d6e0d446ac0ce4b699f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.7-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.7-sources.jar",
          "size": 235781,
          "sha512": "5e46943b47e11f96fa02d289971730af45fc91d3301740f274ac5a9483e824255119ee0a9d0cf397290c3970f7c422fc7f5f04c1a5e388268eca98f76d1d9389",
          "sha256": "97874a4d5a2bf99bccd1d8358645fc1a07e481cb52593f186ea4047d7dd55a8c",
          "sha1": "f8db6392ffde3002e2ded172ea02a26329109e27",
          "md5": "2f100ec94bdb3c8880036d0c8688dfa4"
        }
      ]
    }
  ]
}
