{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.5-lts",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.5-lts.jar",
          "url": "legacy-neoforge-1.21.1-1.8.5-lts.jar",
          "size": 19931045,
          "sha512": "e139967e62d2b2088082601dd79cd82c62467610c8eb98a550ccf1873b0ea1fbe5a621eb687e12490f76a75008c69be33f9ce8f6f7a247bda8e588021e72fed1",
          "sha256": "943a06af385784486f1acd63482e5258ff251f489d10ad9dc48b40116f709f11",
          "sha1": "ad928be201dacc17da1d4932820ffa4744f09c0a",
          "md5": "52fdbd45c8d134ce94628c9c50d22eac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.5-lts.jar",
          "url": "legacy-neoforge-1.21.1-1.8.5-lts.jar",
          "size": 19931045,
          "sha512": "e139967e62d2b2088082601dd79cd82c62467610c8eb98a550ccf1873b0ea1fbe5a621eb687e12490f76a75008c69be33f9ce8f6f7a247bda8e588021e72fed1",
          "sha256": "943a06af385784486f1acd63482e5258ff251f489d10ad9dc48b40116f709f11",
          "sha1": "ad928be201dacc17da1d4932820ffa4744f09c0a",
          "md5": "52fdbd45c8d134ce94628c9c50d22eac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.5-lts-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.5-lts-sources.jar",
          "size": 19036188,
          "sha512": "1060f1fd321d8abf0d229b9a323b277583b12bd1cdee8a008ab7262e2a1c7d39674aac330d53d8661e652efcf8c1d9197047166561a925ff37b8e8f8ae9485a4",
          "sha256": "ab5c5e98753e726582cc5c4f3e1447f87ea21ba47b5c62668ff147ac0dcdf72c",
          "sha1": "6858675d4685c6977b1a9018b32de7ad0385cfdf",
          "md5": "f57cc76fdbb647369c987bc3cbc16934"
        }
      ]
    }
  ]
}
