{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-forge",
    "version": "1.21.5-1.1.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.5-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-forge-1.21.5-1.1.2516.2.jar",
          "size": 645073,
          "sha512": "7a8dc705bfd010f3bbba61de693006b7ce62f0b6ba8c6c21fa6796bf18154c2ac29922dd71ee5f82eb4d339f98363edababdeb52a44d65e3896821c90cfe4e76",
          "sha256": "387d89d2da11baa38f51db7d248f69b62be1ab24556b5bcf7f3d43297a7ebb94",
          "sha1": "cbc3fc76a77cb1fe988a7903e268776ebdd6660a",
          "md5": "a7b99291337778fd3978b302d6e26b91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.5-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-forge-1.21.5-1.1.2516.2.jar",
          "size": 645073,
          "sha512": "7a8dc705bfd010f3bbba61de693006b7ce62f0b6ba8c6c21fa6796bf18154c2ac29922dd71ee5f82eb4d339f98363edababdeb52a44d65e3896821c90cfe4e76",
          "sha256": "387d89d2da11baa38f51db7d248f69b62be1ab24556b5bcf7f3d43297a7ebb94",
          "sha1": "cbc3fc76a77cb1fe988a7903e268776ebdd6660a",
          "md5": "a7b99291337778fd3978b302d6e26b91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-forge-1.21.5-1.1.2516.2-sources.jar",
          "url": "betterfurnacesreforged-forge-1.21.5-1.1.2516.2-sources.jar",
          "size": 585818,
          "sha512": "b4c47e7fa5f4f8c6a971ca7053eae9b0517b0d63b7030e5d8bb8771fe004ea66e6d8b237e9daa231d06ccb87d6e1ff5ca3842ed3ca5296f0bd86239f996b10be",
          "sha256": "f10b7fdd8a8fb0c7ded381beb83bc93cf7999157a1dda137cd87f0114b4843f7",
          "sha1": "f74772b67ad74ec1a9bc1354783ffcf752472e03",
          "md5": "7ef086fbf323a8c466ae238eefa427bf"
        }
      ]
    }
  ]
}
