{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2502.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.11.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.11.jar",
          "size": 454374,
          "sha512": "2ed17a97828eb1b00e0d446e282ad6f984f5ac6092d4386ac9d6397403ab0d2e1b039d80f80a6754125d8570ddae1a13acd19553b8e7a21eefcacf05bede1183",
          "sha256": "203810552b9de76610ff681ba61508d27abf9c5449159129cd9f491e046db88b",
          "sha1": "eb5cba5bf44bc212b97fac2c9042ccaf34f0e50f",
          "md5": "c2d83d984b003301624741c8d689b6b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.11.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.11.jar",
          "size": 454374,
          "sha512": "2ed17a97828eb1b00e0d446e282ad6f984f5ac6092d4386ac9d6397403ab0d2e1b039d80f80a6754125d8570ddae1a13acd19553b8e7a21eefcacf05bede1183",
          "sha256": "203810552b9de76610ff681ba61508d27abf9c5449159129cd9f491e046db88b",
          "sha1": "eb5cba5bf44bc212b97fac2c9042ccaf34f0e50f",
          "md5": "c2d83d984b003301624741c8d689b6b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.11-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.11-sources.jar",
          "size": 227540,
          "sha512": "d0749f471f7040f2db9fe95956b72249174ef43be40e45d51e3a9e7971f9274acaa5c876962682e5344fdb10dc264e01e84f971a0901906a55271526d363a2e4",
          "sha256": "af8c27dbc5b9b87da8d8205ab0325b7e58aabd8adbe791a32ae9ae5aef2ed6a9",
          "sha1": "1c84e86877a43f4e65555e9d542482f8eb72b789",
          "md5": "024ed54ef02aa9e405913a408563dbc9"
        }
      ]
    }
  ]
}
