{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.1.jar",
          "size": 14228989,
          "sha512": "738fd47f60dfe22d0f8849edfbb7eaecf808caa17fff899d209a57a1ff6c0fec0397d57038ab945e17627ff39ad35f2c13254ff8a347998905c23bfc3c24f49f",
          "sha256": "3fdf70b1988846e8528977b6f4c3d7264c0e6ed3ea2a2c275a9f19798431dcb4",
          "sha1": "4349a47c27476ff2c00a5191d04ca258c7fe176c",
          "md5": "1b3bca94e1be81b4aaca7f2f626e17ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.1.jar",
          "size": 14228989,
          "sha512": "738fd47f60dfe22d0f8849edfbb7eaecf808caa17fff899d209a57a1ff6c0fec0397d57038ab945e17627ff39ad35f2c13254ff8a347998905c23bfc3c24f49f",
          "sha256": "3fdf70b1988846e8528977b6f4c3d7264c0e6ed3ea2a2c275a9f19798431dcb4",
          "sha1": "4349a47c27476ff2c00a5191d04ca258c7fe176c",
          "md5": "1b3bca94e1be81b4aaca7f2f626e17ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.1-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.1-sources.jar",
          "size": 13447458,
          "sha512": "96de6fe92ef17fe9564f2fe86b70d64dd9ffae3a8004fbd6f9b73f8f4e1348c0d90f150efee4f333f9d72dd86f7ad4f35eaccd11f35cd0118a90b302809e7bd3",
          "sha256": "7c5ea6dc574bee161fb44c642006d85554f7be350e9593d9050657e79cbce946",
          "sha1": "9197f6522d4e5452302579005b3fecfce5022375",
          "md5": "47eb3444629f3242ec246c5078807590"
        }
      ]
    }
  ]
}
