{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "size": 509629,
          "sha512": "0e57cc7cf5a712cd7f1e2e5476908773ac9ae0fb549253f5b5ff618208d72730417cfae0f81a06c50f9ac149d7bf3bb6d87e786ca8ad92aafe4ecc72eea84c18",
          "sha256": "f211b57e6781b1d8c7bf995b59492c0490a67a620a5fac4411b374edc1bbb04d",
          "sha1": "c56efdfa9858dc7721f585ef69fc5e3df4a2eaf0",
          "md5": "01c0e325627c44ef9db305c52c2ea8f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "size": 509629,
          "sha512": "0e57cc7cf5a712cd7f1e2e5476908773ac9ae0fb549253f5b5ff618208d72730417cfae0f81a06c50f9ac149d7bf3bb6d87e786ca8ad92aafe4ecc72eea84c18",
          "sha256": "f211b57e6781b1d8c7bf995b59492c0490a67a620a5fac4411b374edc1bbb04d",
          "sha1": "c56efdfa9858dc7721f585ef69fc5e3df4a2eaf0",
          "md5": "01c0e325627c44ef9db305c52c2ea8f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.5-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.5-sources.jar",
          "size": 254127,
          "sha512": "e2605a4f37ede9ad2e5d1887e24649727ca4c765ee0cac9a10ace94e3e52cf55a2f556a269419da176af9e948ee3e09577b7f00d1c2a75bab615d86bcaf63cb5",
          "sha256": "3278f70253324170160316a1f05d7a0c179467dc5d35d8409abcb38b77a66d45",
          "sha1": "47abbba346f6132eb246b4238fa5ff59659f9aef",
          "md5": "e91974b59590f48eb62b8b61907b05e5"
        }
      ]
    }
  ]
}
