{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "size": 508765,
          "sha512": "0ed2900ab67235179843de45391228cef59c99fabea928048ae6a26f076e7cdb611477b8d9a4e4796ae5adb504ce309cae4952e56cd88c43afec6a8a34fe741a",
          "sha256": "38bc29d0e05096d42d1eb4a9767544a9e6859faee54ca0cbd7ca8936fca38f08",
          "sha1": "f291831eb2424317070fbdb7c2c43bb6bc2310ee",
          "md5": "16bbc75164b6c7d6c2a1a5830ae5966a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.5.jar",
          "size": 508765,
          "sha512": "0ed2900ab67235179843de45391228cef59c99fabea928048ae6a26f076e7cdb611477b8d9a4e4796ae5adb504ce309cae4952e56cd88c43afec6a8a34fe741a",
          "sha256": "38bc29d0e05096d42d1eb4a9767544a9e6859faee54ca0cbd7ca8936fca38f08",
          "sha1": "f291831eb2424317070fbdb7c2c43bb6bc2310ee",
          "md5": "16bbc75164b6c7d6c2a1a5830ae5966a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.5-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.5-sources.jar",
          "size": 254097,
          "sha512": "431fbf3515cc91a745bea49af8db4e95db042c83071d11350276989a4babc8ef4aceb52ded61a84375506c0c0b4a403d2091100e763493c08da99eec745daf91",
          "sha256": "9e6a36c9a17f472268db3c51519b21a2d7458bcf006fc9967aa0cf27eb1d2e31",
          "sha1": "19b0ea63b055a1a8903bb4a893c952aff3f84682",
          "md5": "00a8a989f206831a3f7bef30437d86d9"
        }
      ]
    }
  ]
}
