{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.5.jar",
          "size": 682833,
          "sha512": "b2867ee3fee3ac4ed7ae334a38760cd61d0a560fd701884b6628ae82205901a4989b88cb16c80e8d5859617601b370849c1e3f7f5eac85b20085fe8398540224",
          "sha256": "de32bb1ea73366313779275ac23599bc49e2153814e8179d71b160d2c3b6a880",
          "sha1": "a90dcda2d6731f24b98f80bc7b317e2572e314bb",
          "md5": "0b8a520c1dac8c806522c66547775b2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.5.jar",
          "size": 682833,
          "sha512": "b2867ee3fee3ac4ed7ae334a38760cd61d0a560fd701884b6628ae82205901a4989b88cb16c80e8d5859617601b370849c1e3f7f5eac85b20085fe8398540224",
          "sha256": "de32bb1ea73366313779275ac23599bc49e2153814e8179d71b160d2c3b6a880",
          "sha1": "a90dcda2d6731f24b98f80bc7b317e2572e314bb",
          "md5": "0b8a520c1dac8c806522c66547775b2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.5-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.5-sources.jar",
          "size": 250448,
          "sha512": "f103da4871aec3cee3ca7f5a44d75acf6a6669080d3d20f732d2b4cfe8877af59a6dd2be06bc48f632145d09e6a1179eacaf67aca0875520820d09ebd754bf66",
          "sha256": "2ed614780eb90805b2653c7b4864e47c0a13e7c06dad5d4416a479621feb75f8",
          "sha1": "7d89fe5bb8749b2d37e8e52cfae0f978fdc63270",
          "md5": "64b8995fe807a405153836b351bec449"
        }
      ]
    }
  ]
}
