{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2504.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.4.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.4.jar",
          "size": 449206,
          "sha512": "7f2d0515961a9a029f5c700af2fbdb11775dec55d532154e55de876d79e46687807c7d092812b7209548feb3fedd1e33d8daac4d7fa0a398fa6f686ae7d44324",
          "sha256": "92a317c314a00f49e5feb28ca6f11c462663909343385cc0eb1ef1a69e86847c",
          "sha1": "50a2a55e3fd7b199fee7f63bb222526e8f2c91d4",
          "md5": "5abfdfa25b57d8b16ca036068e45db03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.4.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.4.jar",
          "size": 449206,
          "sha512": "7f2d0515961a9a029f5c700af2fbdb11775dec55d532154e55de876d79e46687807c7d092812b7209548feb3fedd1e33d8daac4d7fa0a398fa6f686ae7d44324",
          "sha256": "92a317c314a00f49e5feb28ca6f11c462663909343385cc0eb1ef1a69e86847c",
          "sha1": "50a2a55e3fd7b199fee7f63bb222526e8f2c91d4",
          "md5": "5abfdfa25b57d8b16ca036068e45db03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.4-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.4-sources.jar",
          "size": 231586,
          "sha512": "d326ac0aa8624d950995d005a9a55a192907ec8603b56c1085dbfa99363af21659d53b27d737c66f34e8e9dd7a320544aaac811e2d43a45aa7ec956dcf897098",
          "sha256": "b40fe7960d577d94211ddfef763141d240f1e7198f44a74cbfa89e58875b4341",
          "sha1": "045b5a51129883f37bff6307ca2a8abee54b3d1f",
          "md5": "2b8f05fd3f0a08a0cc4a40813308afe6"
        }
      ]
    }
  ]
}
