{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2500.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.9.jar",
          "size": 367224,
          "sha512": "17311ba68ee15b717564c1fdf67b7bc5093b0341562a2472e3b06a960ef54b87ad003633b47ad9a348e2624ca762e77f3e760eee4a90c88622c02e711b87396b",
          "sha256": "47c84af27d23187f14c7867ab0312e9d4a2ef7da7ddca5cc258e06b8ae22bdeb",
          "sha1": "e3de6ecd91b90a5a06008ef7c61170688815a421",
          "md5": "f68b1d282be82fd878707f41b2c5c766"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.9.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.9.jar",
          "size": 367224,
          "sha512": "17311ba68ee15b717564c1fdf67b7bc5093b0341562a2472e3b06a960ef54b87ad003633b47ad9a348e2624ca762e77f3e760eee4a90c88622c02e711b87396b",
          "sha256": "47c84af27d23187f14c7867ab0312e9d4a2ef7da7ddca5cc258e06b8ae22bdeb",
          "sha1": "e3de6ecd91b90a5a06008ef7c61170688815a421",
          "md5": "f68b1d282be82fd878707f41b2c5c766"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.9-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.9-sources.jar",
          "size": 193492,
          "sha512": "1af694c82842cd6ce983b0b108ea9e542fbdc05d22d9ad48e9ad03e725519b87549359ddb6b40525f0832cac99fe72fa381784441e70a6735ea2ba01c916b036",
          "sha256": "e58520ff5e018d2c0228e6eb4026cb7faed23834e73f2774ae894b200e147310",
          "sha1": "b5f52278f8b1c872045df4a6786ddc1d6507f57f",
          "md5": "4e689e5c4a386e59d1a7fb4882940d34"
        }
      ]
    }
  ]
}
