{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.8.0.2515.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2515.1.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2515.1.jar",
          "size": 18257663,
          "sha512": "2303b6794e9e4dda44a21463c32364c2f99e188400dcc369ecaf9cc07fe1d2b8590784c93004506eb9d5ed1327173ffc6b2a80dfd3d312b77e14364a1b03a57b",
          "sha256": "c880876abf1bf8b145a5f99622196a4f5c404cbbffcaebb5b962797608cdd9e4",
          "sha1": "0b93b6f9359781bc658cffa787aada08e6373777",
          "md5": "237881d87297c8ed45f914badf3d6dd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2515.1.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2515.1.jar",
          "size": 18257663,
          "sha512": "2303b6794e9e4dda44a21463c32364c2f99e188400dcc369ecaf9cc07fe1d2b8590784c93004506eb9d5ed1327173ffc6b2a80dfd3d312b77e14364a1b03a57b",
          "sha256": "c880876abf1bf8b145a5f99622196a4f5c404cbbffcaebb5b962797608cdd9e4",
          "sha1": "0b93b6f9359781bc658cffa787aada08e6373777",
          "md5": "237881d87297c8ed45f914badf3d6dd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2515.1-sources.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2515.1-sources.jar",
          "size": 17422095,
          "sha512": "73c10a61657db59aa88720cc925fc221a36f832f1107e5cca2a6d5b49935ced794c1594176ae79cd83ee6e0963079df0c5741dde199fa2770c69c379eb02760d",
          "sha256": "a923a294b8fc6ba62177a4847ce0245465c65df9963f4babc1746caf4121ed84",
          "sha1": "79d80580c9204656b17a69021100f1aa9bf0c022",
          "md5": "dfded34afb78b93fcee8e86d9d11dade"
        }
      ]
    }
  ]
}
