{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.0.2512.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2512.1.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2512.1.jar",
          "size": 18285064,
          "sha512": "942902097ec92f8339e0dedef9823ca79f765c45f1b0dfb53637957eab361e9c8ce32cc9cfa298f14dbbcc9f9c502bc29611ef1aef5b5a5a9bff4ff87d3f97fe",
          "sha256": "819b61bb922fb4c7f4df17a87547d86d4ce1e66cb7ea28da2db3c60b70fbe4f3",
          "sha1": "60d3f295ce954fbd4126c2c3d07a827b887f398d",
          "md5": "2b92e9d38c330df355bd1bcb1f5b5aa2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2512.1.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2512.1.jar",
          "size": 18285064,
          "sha512": "942902097ec92f8339e0dedef9823ca79f765c45f1b0dfb53637957eab361e9c8ce32cc9cfa298f14dbbcc9f9c502bc29611ef1aef5b5a5a9bff4ff87d3f97fe",
          "sha256": "819b61bb922fb4c7f4df17a87547d86d4ce1e66cb7ea28da2db3c60b70fbe4f3",
          "sha1": "60d3f295ce954fbd4126c2c3d07a827b887f398d",
          "md5": "2b92e9d38c330df355bd1bcb1f5b5aa2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.0.2512.1-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.0.2512.1-sources.jar",
          "size": 17422819,
          "sha512": "2825b2ea4b3aaf71091cdc038bdcf0d33903cb58ff2a4722f10a62db8ad3482e2e716a5fd4a0475d5bc84d0d20ad2e669645ba68cd428b1959aa6ee931949cf3",
          "sha256": "4476642a9b6bfa5bdc0337c43259957e3cc265a45c56e0103c83092861377771",
          "sha1": "ff9466e6dc64587ecc57dddbfb417e573bbb8e8e",
          "md5": "c23fb119e59dad21ebe4aadc37b16a87"
        }
      ]
    }
  ]
}
