{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.7.10.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.3.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.3.jar",
          "size": 14247464,
          "sha512": "18d80f120cba10ea515089cf2c408375019cd9187459f43f6bd76ce143f3d86b35446db95aeba6562e5d2708ba01c9d43db01d221dff970cdf3b460ce5c1e1ac",
          "sha256": "38bc5da83c83419fe983235bc086bf48fa41863cf8fc7b16022d060ae5f40cb8",
          "sha1": "d1f4060131c5b3105cf07bcdff2e5be4a39f9664",
          "md5": "f740824c7d4a3abeeb6f538581b64777"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.3.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.3.jar",
          "size": 14247464,
          "sha512": "18d80f120cba10ea515089cf2c408375019cd9187459f43f6bd76ce143f3d86b35446db95aeba6562e5d2708ba01c9d43db01d221dff970cdf3b460ce5c1e1ac",
          "sha256": "38bc5da83c83419fe983235bc086bf48fa41863cf8fc7b16022d060ae5f40cb8",
          "sha1": "d1f4060131c5b3105cf07bcdff2e5be4a39f9664",
          "md5": "f740824c7d4a3abeeb6f538581b64777"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.3-sources.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.3-sources.jar",
          "size": 13454822,
          "sha512": "4b938f0a8258f4860b9c27d28eebc8627757597da3b845e603745602497fad42b50503dc14b5260389a4b3a3355ef9d5c651eb3c64b24085601e8418dd3976f8",
          "sha256": "2874059bdc0f8e3aa22912756974321f1132ba4ad7a7131d3d3bb28d8eecb4ed",
          "sha1": "e88b4cdbdbd3773c5ecff893dbb9e6a77f2166d2",
          "md5": "c4a286de86785066edf8eaafa39ca00f"
        }
      ]
    }
  ]
}
