{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.0.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2516.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2517.0.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2517.0.jar",
          "size": 18273591,
          "sha512": "1778981162f58b2f00d620926f8b648023f2bc71922232cc10213dcddedc5e06cbde382464172da3c1092dd270920748ca00bffec56be759628a3f3c26202a14",
          "sha256": "3201d44e3ef70d6b657529225e8dfe4fcc5156c6bd1a0806e2d0f33d57f80927",
          "sha1": "e53454ff7fe64efc04a75cd8855e69b33e7da8a3",
          "md5": "451864a38361747365b82e3dc276f899"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2517.0.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2517.0.jar",
          "size": 18273591,
          "sha512": "1778981162f58b2f00d620926f8b648023f2bc71922232cc10213dcddedc5e06cbde382464172da3c1092dd270920748ca00bffec56be759628a3f3c26202a14",
          "sha256": "3201d44e3ef70d6b657529225e8dfe4fcc5156c6bd1a0806e2d0f33d57f80927",
          "sha1": "e53454ff7fe64efc04a75cd8855e69b33e7da8a3",
          "md5": "451864a38361747365b82e3dc276f899"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.0.2517.0-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.0.2517.0-sources.jar",
          "size": 17421843,
          "sha512": "bd697e6d4cfe21b3552fc396663fbf2c24133046c7ddf8f962e7faed285f481269b1853698eb2f42ccc3529d3e6cf5bddd14cbb51f196e3698309e96dd3cf3c6",
          "sha256": "a817900b77fd0044a2fbc4f936194e62cbd9b34469f9656722eec7f9785d5ec6",
          "sha1": "18304a17eb9808e1f411ce18758123680c13623f",
          "md5": "0ce865f05079a4455b0f80d62ae268f5"
        }
      ]
    }
  ]
}
