{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.8.0.2511.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2511.2.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2511.2.jar",
          "size": 18277805,
          "sha512": "2b74da772afc1d82ed212fecdfc02b2e65eec2915a4a5fc74606dee22c7ae3aa6425190f7bc80ebafd713819aa1ba7574b4dcbbe034d756efe075c18a43a8223",
          "sha256": "b713c98f0e4810ed17536debe0bd51b1b473dc4e578aa32e793daa9105d20d5d",
          "sha1": "742b42ad05cfde4c5af1a238d432ed1ca43ad6a5",
          "md5": "f5f869b8494fd812387837c96138c1c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2511.2.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2511.2.jar",
          "size": 18277805,
          "sha512": "2b74da772afc1d82ed212fecdfc02b2e65eec2915a4a5fc74606dee22c7ae3aa6425190f7bc80ebafd713819aa1ba7574b4dcbbe034d756efe075c18a43a8223",
          "sha256": "b713c98f0e4810ed17536debe0bd51b1b473dc4e578aa32e793daa9105d20d5d",
          "sha1": "742b42ad05cfde4c5af1a238d432ed1ca43ad6a5",
          "md5": "f5f869b8494fd812387837c96138c1c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.8.0.2511.2-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.8.0.2511.2-sources.jar",
          "size": 17422169,
          "sha512": "0c5b25180fb38be0c217bd6253e5ca6bc1eedcff35711d82766a0f373a2d310b2d3f4c227d1153e6a53c0220741fd1930f68a7d414806bf84f5e780ab3392f69",
          "sha256": "f4286e1ca9a191215c17fee8bcb0c4b92694f6344014aad9b44b19706dc555b5",
          "sha1": "c9831d5b45a18297a7baba74cf14cfa1dca3489d",
          "md5": "b0f8da487b49ecb2d66d521c08c208fa"
        }
      ]
    }
  ]
}
