{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2617.0.jar",
          "size": 537965,
          "sha512": "beaa97fdb10acc5a046193ca437d7ef00e87df75b3abbefba6bed4548bf1f88d7d03ce76504cf6eb1e164de194fc3fe5420e35c5fe2ffe57f2c83a9cae8f0f5f",
          "sha256": "cfbf3913728dd50fa0a7d2f9785ede1b2ae89dbd6eb913c5e3ece70e57b1af9e",
          "sha1": "e0a5b3444b42c9bcccd16f5e0761900e1dd702a2",
          "md5": "2ac77cf6c6ae83d5c91ac24bb600b586"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2617.0.jar",
          "size": 537965,
          "sha512": "beaa97fdb10acc5a046193ca437d7ef00e87df75b3abbefba6bed4548bf1f88d7d03ce76504cf6eb1e164de194fc3fe5420e35c5fe2ffe57f2c83a9cae8f0f5f",
          "sha256": "cfbf3913728dd50fa0a7d2f9785ede1b2ae89dbd6eb913c5e3ece70e57b1af9e",
          "sha1": "e0a5b3444b42c9bcccd16f5e0761900e1dd702a2",
          "md5": "2ac77cf6c6ae83d5c91ac24bb600b586"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2617.0-sources.jar",
          "size": 256825,
          "sha512": "5544a4d1662c0cbd0001da0a12063cd1fce313ab1842002fa8d34c968f30464b29ccb4114375b4fbbc3477834368970f5770e20730f012582a9409a9a6970c7f",
          "sha256": "bda669036360d100861a779996c2c3db09d3f0b3242a0def63e0ab72767d8446",
          "sha1": "37dd35099811fed807d35b596a88b9063055044b",
          "md5": "12da04a45b957291d163c898fcf51f0e"
        },
        {
          "name": "factory_api-neoforge-1.21.1-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.7.2617.0-sources.jar",
          "size": 256825,
          "sha512": "5544a4d1662c0cbd0001da0a12063cd1fce313ab1842002fa8d34c968f30464b29ccb4114375b4fbbc3477834368970f5770e20730f012582a9409a9a6970c7f",
          "sha256": "bda669036360d100861a779996c2c3db09d3f0b3242a0def63e0ab72767d8446",
          "sha1": "37dd35099811fed807d35b596a88b9063055044b",
          "md5": "12da04a45b957291d163c898fcf51f0e"
        }
      ]
    }
  ]
}
