{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.5-1.8.0.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2516.2.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2516.2.jar",
          "size": 18293520,
          "sha512": "61077edf320557565e67de338a635fe4bc9edcf2112e52c99bf79b2ed873abf2402ed98818700e38d89a9a8baa80fa3233c3b31d7d0660cd5214745101ef0771",
          "sha256": "68570e4ed38e875a35212f791e7ce17c1a03a45b280544e8ac59240040ccda2c",
          "sha1": "72ea0c9bf2a981fa15381ab58110287773e54fc8",
          "md5": "2f4e312d6545618ae1b4f9acc5344b14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2516.2.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2516.2.jar",
          "size": 18293520,
          "sha512": "61077edf320557565e67de338a635fe4bc9edcf2112e52c99bf79b2ed873abf2402ed98818700e38d89a9a8baa80fa3233c3b31d7d0660cd5214745101ef0771",
          "sha256": "68570e4ed38e875a35212f791e7ce17c1a03a45b280544e8ac59240040ccda2c",
          "sha1": "72ea0c9bf2a981fa15381ab58110287773e54fc8",
          "md5": "2f4e312d6545618ae1b4f9acc5344b14"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2516.2-sources.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2516.2-sources.jar",
          "size": 17434022,
          "sha512": "63ee05979c48cce625daa472b5f6a127c209b09cd47d6e1d6aa3aa8beea1b4abc68a3f1eeeef0e8d49dd74821dbc64e450dec35042a181b5e088ef969fc76089",
          "sha256": "7814cd19eedeb9987f58d49ad5f49653ba9852c8b6e82adcb7aeba0477edd668",
          "sha1": "32433f4e1a92fdcc3c23e12287f86c48f3740eca",
          "md5": "069979d587f685f4f171a36ca869d4a0"
        }
      ]
    }
  ]
}
