{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2500.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.1.jar",
          "size": 339694,
          "sha512": "293e65effd1f23ef7b9503464e780354a5e2444513c3688647316e767ed0480e21aabaecd461e3fd02527e6bab163a439fcc9791f0e1b242dbfa61d5d0bae20b",
          "sha256": "0d752eafa86aa39a403b71788cf4f8ccdb60bd43830684cd0d520af072ae1ff5",
          "sha1": "d0740921302ee1dc953a6abc4fc8fd1e691e8226",
          "md5": "a51beb0d10690fd25a9e55ab054d514c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.1.jar",
          "size": 339694,
          "sha512": "293e65effd1f23ef7b9503464e780354a5e2444513c3688647316e767ed0480e21aabaecd461e3fd02527e6bab163a439fcc9791f0e1b242dbfa61d5d0bae20b",
          "sha256": "0d752eafa86aa39a403b71788cf4f8ccdb60bd43830684cd0d520af072ae1ff5",
          "sha1": "d0740921302ee1dc953a6abc4fc8fd1e691e8226",
          "md5": "a51beb0d10690fd25a9e55ab054d514c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.1-sources.jar",
          "size": 191061,
          "sha512": "927a38c149bb5760b2f9f670ca9323bdf06eb9bacf5831ba31f35402d2267c8b3430a251f1ed9880a4a6a99d93db19c22b1d5d9db122ff1547d6feca712215aa",
          "sha256": "b0cc28089193c006571c677bfb2f1ead2e5fe080311021efaeb2bd628f608715",
          "sha1": "7bb9c0c24f1e094f8bd2c67452b357b11256b508",
          "md5": "abfa0b8dc6ed766759a5efbcff61fc6a"
        }
      ]
    }
  ]
}
