{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.5.2527.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.5.2527.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.5.2527.0.jar",
          "size": 532339,
          "sha512": "25dbe6aff457fba8e5718af214205fbcbb43349642bf94cead74a5d2eeabc83e58b39bda1be1f1c573422bcb47d512f8b2d1556c66605d76391c73c40c65a37f",
          "sha256": "e509858b0465e81a5babdfc3404897e1bb060123db9f98568368e736addf5b1e",
          "sha1": "abf688906d946729396dc92babd829c890c3f9bc",
          "md5": "72f6b1d14384428703a413bb9006b6c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.5.2527.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.5.2527.0.jar",
          "size": 532339,
          "sha512": "25dbe6aff457fba8e5718af214205fbcbb43349642bf94cead74a5d2eeabc83e58b39bda1be1f1c573422bcb47d512f8b2d1556c66605d76391c73c40c65a37f",
          "sha256": "e509858b0465e81a5babdfc3404897e1bb060123db9f98568368e736addf5b1e",
          "sha1": "abf688906d946729396dc92babd829c890c3f9bc",
          "md5": "72f6b1d14384428703a413bb9006b6c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.5.2527.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.5.2527.0-sources.jar",
          "size": 258627,
          "sha512": "6f54bfa6ec6776fe0c6cf066d2083a6abc2698d56cc032c2f87e0ac1b48cb0c8bc2270fae294d7c9a1b9082d1ec4b81da4505b4d8c0d7eee2b8955321946fc0c",
          "sha256": "0e5cff953499fd2b9a80a3c9330f84893b8af2e669342998fb32228b07134994",
          "sha1": "e26569eaedfcf8c416e5779775ada0d3327795ca",
          "md5": "e044cbc72ee6c667947ad16ed1943b07"
        }
      ]
    }
  ]
}
