{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2502.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.6.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.6.jar",
          "size": 428954,
          "sha512": "b0318629752a7c44df01ab5d9f2d7c9bbeff06354e9f5d5c30c0c390e0dd43314ff9c258104d131e18bf5e5eb811e8bd84998c9856a0a12364e0f354c343ce3d",
          "sha256": "8bfb202d3d3cd1a35b427b631f09d0cc49cd3def90c000356d678aeab7f2cffe",
          "sha1": "ce8409a6090d6336477529643897edae2c594e80",
          "md5": "29f121ba75e97f5e0eb8f682bf727ce5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.6.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.6.jar",
          "size": 428954,
          "sha512": "b0318629752a7c44df01ab5d9f2d7c9bbeff06354e9f5d5c30c0c390e0dd43314ff9c258104d131e18bf5e5eb811e8bd84998c9856a0a12364e0f354c343ce3d",
          "sha256": "8bfb202d3d3cd1a35b427b631f09d0cc49cd3def90c000356d678aeab7f2cffe",
          "sha1": "ce8409a6090d6336477529643897edae2c594e80",
          "md5": "29f121ba75e97f5e0eb8f682bf727ce5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2502.6-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2502.6-sources.jar",
          "size": 222192,
          "sha512": "d1c10fdc41ae6553b21a9a054d22e43121cb90582660822b7323ef782a9ddfc98263aafed7642420115c23b9d99f05dace4283e45fa311db343c1216f5b1d56b",
          "sha256": "fc9bd07e041fbef9fbeac01161281ef09d4fb7b82b828a617f1dd313eb224637",
          "sha1": "18875a0e6bd9ced244b186a2e6e20475f2dc821f",
          "md5": "7ca9ac163cb858e017362f0e090e0b67"
        }
      ]
    }
  ]
}
