{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2500.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.8.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.8.jar",
          "size": 374630,
          "sha512": "b5de5d02828e92cfad3da1d76865a1952fce10cd9d5bc6edab7caae706574b403e46fd5caa7b021565b9ef0040f071dbd5927c2ca435ff2eda37ecace96cb380",
          "sha256": "ba335ed92434798c0f7e897b86f7c6a8b76dcd275c9aef04616bf06bfa6edae8",
          "sha1": "501661eecb6e4a367d1a650373ffdb42d0302c49",
          "md5": "95d213196aff4352547139954e4c5b60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.8.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.8.jar",
          "size": 374630,
          "sha512": "b5de5d02828e92cfad3da1d76865a1952fce10cd9d5bc6edab7caae706574b403e46fd5caa7b021565b9ef0040f071dbd5927c2ca435ff2eda37ecace96cb380",
          "sha256": "ba335ed92434798c0f7e897b86f7c6a8b76dcd275c9aef04616bf06bfa6edae8",
          "sha1": "501661eecb6e4a367d1a650373ffdb42d0302c49",
          "md5": "95d213196aff4352547139954e4c5b60"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.8-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.8-sources.jar",
          "size": 195078,
          "sha512": "775c747e6c5e901ec0cc74c6dc2bf30337a88b02a6318a3a68409daf0c9c8bfa733c9d96cc5b9f7b0661691c188b698a08f4656cc01bdc59e58ef131c5da6f06",
          "sha256": "5a199b943774cb30718e04a9632951ead8dfb0933f928b156a0cfdb18900fa96",
          "sha1": "be4ea6678b828cf45aa52c58c77e6667761cbf80",
          "md5": "7e1a8f6fe426a6511e44824995f877fe"
        }
      ]
    }
  ]
}
