{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.7.2615.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2615.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2615.2.jar",
          "size": 581165,
          "sha512": "4e6bd9e97ea91ec960531aed3d2ffd7d0dc93feca5d1118919c9cd4b6b232c899f6b5fe11e413c83cda835421fdcbfd843af1a64177e30e5649bf320dd44bba2",
          "sha256": "2aefee3a3434acb3bd1649a5b982291c33bc19fdde6681b0b2f37c63828d2773",
          "sha1": "b9f915bb34010ccbdbae90cb592444581d31af8e",
          "md5": "552d9962e5eae5326116e66fa4029bf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2615.2.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2615.2.jar",
          "size": 581165,
          "sha512": "4e6bd9e97ea91ec960531aed3d2ffd7d0dc93feca5d1118919c9cd4b6b232c899f6b5fe11e413c83cda835421fdcbfd843af1a64177e30e5649bf320dd44bba2",
          "sha256": "2aefee3a3434acb3bd1649a5b982291c33bc19fdde6681b0b2f37c63828d2773",
          "sha1": "b9f915bb34010ccbdbae90cb592444581d31af8e",
          "md5": "552d9962e5eae5326116e66fa4029bf4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2615.2-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2615.2-sources.jar",
          "size": 256456,
          "sha512": "899e8c7e628c30fa919b3c38d38c0a75854315ad25e18ada5dabc9f3ccf8de506684dd09bbc452673c421969ccefeeb5b788fb317a933509086212355c92e2f3",
          "sha256": "1b7d6444c9f5f96d684c3a91c5848f226a9d06e41fce84947af68165be76757e",
          "sha1": "4cf5144495d629dbd452af9ff59dd8c0c6ce2e40",
          "md5": "cf370f7e27c3a94e8315ad239088a80e"
        }
      ]
    }
  ]
}
