{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.7.2617.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.3.jar",
          "size": 555534,
          "sha512": "2588eb1f709c9d73491022ff2d6ec07ca50821336cc644e229d46adf95ac5ece426dcf08d7b7dd570dfedb3fd1ed4346a91289b7e787112157636c0ba6face89",
          "sha256": "2eefca44774aa7d71617f4922903054873da95bbfa008a380150cae44fc41611",
          "sha1": "176906cd285282f7eab03e7855031aa2a981d0eb",
          "md5": "744cd345956489b45cec31420330eac6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.3.jar",
          "size": 555534,
          "sha512": "2588eb1f709c9d73491022ff2d6ec07ca50821336cc644e229d46adf95ac5ece426dcf08d7b7dd570dfedb3fd1ed4346a91289b7e787112157636c0ba6face89",
          "sha256": "2eefca44774aa7d71617f4922903054873da95bbfa008a380150cae44fc41611",
          "sha1": "176906cd285282f7eab03e7855031aa2a981d0eb",
          "md5": "744cd345956489b45cec31420330eac6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.3-sources.jar",
          "size": 256761,
          "sha512": "35349ccf107c857c8777fc7c9892785e5ce535ed7761b659f0147d7bfdcf1575b83c7597544598732bf52ef17cc7434fd3b152368d6e0b193b72c017c18a7b89",
          "sha256": "41a180e521dbf6205febc58773a92af1d5dc287578bb8f28ef1885c593a74acf",
          "sha1": "8bf15cb080acfa828cdf31f61559162b4ad21f68",
          "md5": "0b80731747bd48eb575a2d30e26b4f4c"
        },
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.3-sources.jar",
          "size": 256761,
          "sha512": "35349ccf107c857c8777fc7c9892785e5ce535ed7761b659f0147d7bfdcf1575b83c7597544598732bf52ef17cc7434fd3b152368d6e0b193b72c017c18a7b89",
          "sha256": "41a180e521dbf6205febc58773a92af1d5dc287578bb8f28ef1885c593a74acf",
          "sha1": "8bf15cb080acfa828cdf31f61559162b4ad21f68",
          "md5": "0b80731747bd48eb575a2d30e26b4f4c"
        }
      ]
    }
  ]
}
