{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2501.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.14.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.14.jar",
          "size": 392269,
          "sha512": "374054a74d0da1b37f2b93c463faca8610b33d39d8d0bb107ef20194c449a8a3d53bda4638e2542893f34bffd7108368375f6780a2918e54370bf5e01d8d9257",
          "sha256": "b71a1393a8d9a5886101dc9fbc8970cc928ac44affe14c2f02dcf5518c567482",
          "sha1": "2525d0202dc89bdd4995a7f0671f60a04cc9e20f",
          "md5": "e52c804f5661720c22f00c98eab36a0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.14.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.14.jar",
          "size": 392269,
          "sha512": "374054a74d0da1b37f2b93c463faca8610b33d39d8d0bb107ef20194c449a8a3d53bda4638e2542893f34bffd7108368375f6780a2918e54370bf5e01d8d9257",
          "sha256": "b71a1393a8d9a5886101dc9fbc8970cc928ac44affe14c2f02dcf5518c567482",
          "sha1": "2525d0202dc89bdd4995a7f0671f60a04cc9e20f",
          "md5": "e52c804f5661720c22f00c98eab36a0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2501.14-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2501.14-sources.jar",
          "size": 201316,
          "sha512": "c88d9c96a7e6a5550dbc2963e1cce5028fcba4f9b117b567f3081ce6dc7d5167c363d81799006c0312b8d495a68e7e0f32aceb98bdd7ed67ac17cc34e01e117c",
          "sha256": "c9ad00bc88add9e8a8c874334a5d1f651befa3bea418285bf22174b493bb18b6",
          "sha1": "45833382015b6fa9bc8668f7e2bbc562a8cfdc9d",
          "md5": "8cfb3d627208e788703249e8390a8b68"
        }
      ]
    }
  ]
}
