{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2513.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.1.jar",
          "size": 498855,
          "sha512": "7e530173a4d3b7a19b764474ba4f7e21c43a6511f19604af4921993b6f9d45ca1746c3fabf7873cc616fb3d18eafeebcc70977f03d71a540cc38c8b0d499708a",
          "sha256": "0c688a1d3ded552323625ca2103dc2a286a9b7c99195b915b98bc562c64b74c4",
          "sha1": "cfccd349cb8f7f1362003b4faf1dde6f9cd9ef50",
          "md5": "077e79b9dc14892da7fedc2ee6728242"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.1.jar",
          "size": 498855,
          "sha512": "7e530173a4d3b7a19b764474ba4f7e21c43a6511f19604af4921993b6f9d45ca1746c3fabf7873cc616fb3d18eafeebcc70977f03d71a540cc38c8b0d499708a",
          "sha256": "0c688a1d3ded552323625ca2103dc2a286a9b7c99195b915b98bc562c64b74c4",
          "sha1": "cfccd349cb8f7f1362003b4faf1dde6f9cd9ef50",
          "md5": "077e79b9dc14892da7fedc2ee6728242"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.1-sources.jar",
          "size": 250676,
          "sha512": "07c41d9c8009fd669b6b558b75627c0470002ca7ca6c1d32a81dea9369a934ea34449c848b1b024dc5a8d3527cb8a58e0765901fe54b37d19ca824e78328d512",
          "sha256": "06a7b8a6ea6f6bcd98433e49679e8bbf841742cea78f467e68ac7fd29a443e5a",
          "sha1": "99a3a67e674f76fb5289be8dc710873fe59976b1",
          "md5": "8d7698083835453e703015b15d0280e1"
        }
      ]
    }
  ]
}
