{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.7.10.2508.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2508.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2508.1.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2508.1.jar",
          "size": 14349500,
          "sha512": "91f3ebf45e37958d1dc5da7859ce34b9d18782e892350f7cd2ab6121caba8505502445c9ae6532c6a429ff33a4171d530de7404d7143bc376a79f3d5e26ff38f",
          "sha256": "212b9168f30e26329c995c9e9b0941db9122e1730b0bca7bc94d6ae6bea67762",
          "sha1": "9152c27b2207dd1e898347e3297368f2c929d407",
          "md5": "d9e963cc7f8b971ef8c2ec07448500b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2508.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2508.1.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2508.1.jar",
          "size": 14349500,
          "sha512": "91f3ebf45e37958d1dc5da7859ce34b9d18782e892350f7cd2ab6121caba8505502445c9ae6532c6a429ff33a4171d530de7404d7143bc376a79f3d5e26ff38f",
          "sha256": "212b9168f30e26329c995c9e9b0941db9122e1730b0bca7bc94d6ae6bea67762",
          "sha1": "9152c27b2207dd1e898347e3297368f2c929d407",
          "md5": "d9e963cc7f8b971ef8c2ec07448500b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2508.1-sources.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2508.1-sources.jar",
          "size": 13544324,
          "sha512": "7b31fb1de8cb9240ca9d11f82f8f72a5b08e3f1281cc1f4b77aa2c55d7b6fe06fd28eaf1a4f8a6372575275dbdacf65d76c42af8023eaaf9cbd26503a9db75c4",
          "sha256": "dab6d7e86f2dac4fc2c0e2772c71b6d514927ebe1a362e8a1cd8a1b9afac332e",
          "sha1": "c7ab114136bbbf9e86c85cb9a1fb4492087c3aa8",
          "md5": "ffe3c48996691fa721c76c8611cf15cd"
        }
      ]
    }
  ]
}
