{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2500.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.9.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.9.jar",
          "size": 374634,
          "sha512": "3bc5a73cb15687927ad8311bfb755db691483091af3fe4c3c493a58b0102f4f4a335e7504db9abe13ff44e4a7b370e7b4d3a27eea18156230f9051dfeb68a29c",
          "sha256": "3dd4c54612f90a14356add9b7e3f78532e27eecfb4db31dc50da153c2a8f88a8",
          "sha1": "72a55c04951ab70f80ccecedd251ada4c5b0882a",
          "md5": "67a0dc17c5492516a6b13de4cf8bec2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.9.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.9.jar",
          "size": 374634,
          "sha512": "3bc5a73cb15687927ad8311bfb755db691483091af3fe4c3c493a58b0102f4f4a335e7504db9abe13ff44e4a7b370e7b4d3a27eea18156230f9051dfeb68a29c",
          "sha256": "3dd4c54612f90a14356add9b7e3f78532e27eecfb4db31dc50da153c2a8f88a8",
          "sha1": "72a55c04951ab70f80ccecedd251ada4c5b0882a",
          "md5": "67a0dc17c5492516a6b13de4cf8bec2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.9-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.9-sources.jar",
          "size": 195063,
          "sha512": "7592a157a7a26fd2a0b3773e6b48af1136be8927bb200c27b138bf8414ee59e17553e656c25021ee9479a18663dfecc010c6a65cfb6d8d865408378116d4d10c",
          "sha256": "3733bd022bc12fde2f06cf1d2b4195f65175fd97c8f300e1bea61d54f79d9198",
          "sha1": "b27f76e8833fa3cd2dc4dd25ee6222016d0ae639",
          "md5": "ad430af41cf228f59d42e366259709a5"
        }
      ]
    }
  ]
}
