{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.5.2532.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.5.2532.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.5.2532.0.jar",
          "size": 537579,
          "sha512": "0c0050b3f0e78e0ea024cf360dd850b7c5d2ec49476c75518e1120b2ea0b6243c486ae1fdfad89e6f6e9f7928bfa0ed48da77aaa88290e9d79f9e79edb5abc78",
          "sha256": "9f09b6bfe0326eb6155170521f90d20b1eb6a70f10220ad62f0a0fceb144c66c",
          "sha1": "de6c8ae99789c4dd2b4b3f09f23a6edaabfafba2",
          "md5": "df314e69de0874f493fd8f2de28a7f0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.5.2532.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.5.2532.0.jar",
          "size": 537579,
          "sha512": "0c0050b3f0e78e0ea024cf360dd850b7c5d2ec49476c75518e1120b2ea0b6243c486ae1fdfad89e6f6e9f7928bfa0ed48da77aaa88290e9d79f9e79edb5abc78",
          "sha256": "9f09b6bfe0326eb6155170521f90d20b1eb6a70f10220ad62f0a0fceb144c66c",
          "sha1": "de6c8ae99789c4dd2b4b3f09f23a6edaabfafba2",
          "md5": "df314e69de0874f493fd8f2de28a7f0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.5.2532.0-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.5.2532.0-sources.jar",
          "size": 258979,
          "sha512": "4d531e4a38a239e7f72b25490d9cd23077cc4cbfcbd089e2091afa44138eb2794f42bb34e801b3c427d6d3a8b6a430c8a3837d419dbdd9e1b86c3e8f9e38afd7",
          "sha256": "eaebd86c48e432b2cb26223080a355b2c976d773f3b1077493da74427333627e",
          "sha1": "129338259fb5a7e18aa2ff8631181f5a4295bb1b",
          "md5": "2e8c254da47cefce2a278f8780b27951"
        }
      ]
    }
  ]
}
