{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.7.10.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2509.1.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2509.1.jar",
          "size": 14417214,
          "sha512": "1e7c0461168575f7aff188bc268ad732f5ab0592da349cf2b6367f72a587ff447a225071692527fcd16c3ccd33ce305a1cbfe6dc1cbf1214b9c15599614a4e34",
          "sha256": "34968f0eae2435d8fcbf0586c899577456beedcf9459e96a187eab7d90a04d0d",
          "sha1": "4523a2df8b0c59d212314e815bb3d4384caed283",
          "md5": "3fd3d3e3c2dc71c12e36fe78808da552"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2509.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2509.1.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2509.1.jar",
          "size": 14417214,
          "sha512": "1e7c0461168575f7aff188bc268ad732f5ab0592da349cf2b6367f72a587ff447a225071692527fcd16c3ccd33ce305a1cbfe6dc1cbf1214b9c15599614a4e34",
          "sha256": "34968f0eae2435d8fcbf0586c899577456beedcf9459e96a187eab7d90a04d0d",
          "sha1": "4523a2df8b0c59d212314e815bb3d4384caed283",
          "md5": "3fd3d3e3c2dc71c12e36fe78808da552"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2509.1-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2509.1-sources.jar",
          "size": 13582896,
          "sha512": "2aa8a3e08ef1589db0d43dbdf0e17cf47c9a8c74de9b41942773e05c25979394eef3a6eca21cf8520991b0be9aefb4ec2ecdf74a3379fe3890a71bf37b2d8549",
          "sha256": "e2237f1f024d05930d62baa7fa14d96d657f2fb4181441654cce131fc9c6083d",
          "sha1": "bfe382c3aaa520a1e5e09bc4a6afc681038f9d22",
          "md5": "cc4f255171912467cf5fd5bb90d984cc"
        }
      ]
    }
  ]
}
