{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.4-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2506.0.jar",
          "size": 514302,
          "sha512": "2f4d408747e9ed310837587b1b3845c6db7f2487dffea72a8e6b7fc79231389415481d4f0172b88b61e3b486cd59f265d87a7fdd1d020ec30dfbcb7eadf3146b",
          "sha256": "33d8a4774c7c216fb69b87370b2052514813fc641c5034df8d14773ca25ad66c",
          "sha1": "b727d44471312ef4a76767530f7c31938bc6fdd2",
          "md5": "c80b2016b7a80b60b4086b57c5b25313"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2506.0.jar",
          "size": 514302,
          "sha512": "2f4d408747e9ed310837587b1b3845c6db7f2487dffea72a8e6b7fc79231389415481d4f0172b88b61e3b486cd59f265d87a7fdd1d020ec30dfbcb7eadf3146b",
          "sha256": "33d8a4774c7c216fb69b87370b2052514813fc641c5034df8d14773ca25ad66c",
          "sha1": "b727d44471312ef4a76767530f7c31938bc6fdd2",
          "md5": "c80b2016b7a80b60b4086b57c5b25313"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2506.0-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2506.0-sources.jar",
          "size": 236049,
          "sha512": "7b34413d91cf13a19ba86004c4a4adbc8cc21636acaeae17bcafc7eed3399a20f75de5225a8fff4f9857a4970e2a8d77289771b650c7d3f9debe15c62d416ab6",
          "sha256": "5691f3c388c91c4d136369e1160afd5f556ee0c67cc52bfecdb7c726b9ad4edd",
          "sha1": "fffe7ee3acc6e8855b83bcf0f3bb1295be14cf3e",
          "md5": "a8793f8fd494a334910d6c26ca2fec1f"
        }
      ]
    }
  ]
}
