{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.7.2617.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.3.jar",
          "size": 560294,
          "sha512": "d7e16b8db82510c515acda4e3cc7758cbdad0acf908722ab2b764915d506d22dcc93696d2f91b60d10657a53e2515fabcb48f69e7b20227cb1895f2c4d600d02",
          "sha256": "0e65885015a26ffcc75b4918fd55de8686bd6d9f1a4966918c35c97046963b5c",
          "sha1": "0c6b392b3463574d0d68feb3e5ee34398a2eac73",
          "md5": "b792995ade932ddc6d00a3d66f1d9425"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.3.jar",
          "size": 560294,
          "sha512": "d7e16b8db82510c515acda4e3cc7758cbdad0acf908722ab2b764915d506d22dcc93696d2f91b60d10657a53e2515fabcb48f69e7b20227cb1895f2c4d600d02",
          "sha256": "0e65885015a26ffcc75b4918fd55de8686bd6d9f1a4966918c35c97046963b5c",
          "sha1": "0c6b392b3463574d0d68feb3e5ee34398a2eac73",
          "md5": "b792995ade932ddc6d00a3d66f1d9425"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.3-sources.jar",
          "size": 256740,
          "sha512": "fdd09b66670f1e6cfa745957eb36c71b3ee9ac61396a87cff0ef166293a0ddb0519aa7cb7f7c44da1982e28655aa6a3e4292cace96a6b0af2c408801950355cd",
          "sha256": "b2284dcfcf42b1ce83c6e810d0cd34d3ff83e2fd5809f917de8903d2628bc59f",
          "sha1": "9cf44aeba7f307b51833507bf3aedcfedb0f2cd9",
          "md5": "7d6519de9993706fa052721381a25b0b"
        },
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2617.3-sources.jar",
          "size": 256740,
          "sha512": "fdd09b66670f1e6cfa745957eb36c71b3ee9ac61396a87cff0ef166293a0ddb0519aa7cb7f7c44da1982e28655aa6a3e4292cace96a6b0af2c408801950355cd",
          "sha256": "b2284dcfcf42b1ce83c6e810d0cd34d3ff83e2fd5809f917de8903d2628bc59f",
          "sha1": "9cf44aeba7f307b51833507bf3aedcfedb0f2cd9",
          "md5": "7d6519de9993706fa052721381a25b0b"
        }
      ]
    }
  ]
}
