{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.3.jar",
          "size": 713207,
          "sha512": "d38c0571fb0f3aa72877941e5ed77585230dd1126d49d984e821ffb87ca64f0e43295b49cb9b02c716bdff45ed9e8594602de503278339cbc3388e8e3f001202",
          "sha256": "6ca849bc4dc95808c18a69fa250823c0264457904186ebf0ab6a76e99978981a",
          "sha1": "bb7fb2e465cd78413528e948e9fefed6ee0d2ca6",
          "md5": "ef209a4725d31641aaf06dfdf1d93cf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.3.jar",
          "size": 713207,
          "sha512": "d38c0571fb0f3aa72877941e5ed77585230dd1126d49d984e821ffb87ca64f0e43295b49cb9b02c716bdff45ed9e8594602de503278339cbc3388e8e3f001202",
          "sha256": "6ca849bc4dc95808c18a69fa250823c0264457904186ebf0ab6a76e99978981a",
          "sha1": "bb7fb2e465cd78413528e948e9fefed6ee0d2ca6",
          "md5": "ef209a4725d31641aaf06dfdf1d93cf7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2516.3-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2516.3-sources.jar",
          "size": 254017,
          "sha512": "cb03a8b5ae49e8ab42361d5fc77a028575c45d231c55884e51cc3d58788af67c99a85903ed6c7aba16ae250eb24dd13d8398a812ebd1376c96c1bd5a2d08edf0",
          "sha256": "44858c305ae3246be1db34361e78f1d5a350c6b92563725cba843ce105a2f308",
          "sha1": "f45e54334e9f9e80a4eeefcf91fe5d3c9efb90dd",
          "md5": "6edb188c0c8c3692d1d26b7ca3366d05"
        }
      ]
    }
  ]
}
