{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2518.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2518.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2518.0.jar",
          "size": 515463,
          "sha512": "0811f0049fe4b1657c63c4f8be1a1ccf37858c789837892f85ae8f102a053883bf9c0b5f809145f7fc84ffdd4da422ed5e13128399e57f266b27cbe0d620075b",
          "sha256": "bdc4ae8330977b512b672de86e3b9bbd38d169b0b1cbb33b738f648e29f223fe",
          "sha1": "20d6979deaf5053777cd081f243adee36f2dc745",
          "md5": "5d51acff3f836eb7cfb7cc863ed44f2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2518.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2518.0.jar",
          "size": 515463,
          "sha512": "0811f0049fe4b1657c63c4f8be1a1ccf37858c789837892f85ae8f102a053883bf9c0b5f809145f7fc84ffdd4da422ed5e13128399e57f266b27cbe0d620075b",
          "sha256": "bdc4ae8330977b512b672de86e3b9bbd38d169b0b1cbb33b738f648e29f223fe",
          "sha1": "20d6979deaf5053777cd081f243adee36f2dc745",
          "md5": "5d51acff3f836eb7cfb7cc863ed44f2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2518.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2518.0-sources.jar",
          "size": 254555,
          "sha512": "527dc475f96e0de205a926ecc7aafa4e83ca38a8eacb34a7bcf6fd435ac4cd64cbf76e1a000668e9ff10bab62d4c22a6f8bc4ce96d16e3cc97fb60fe664ffd09",
          "sha256": "da961065a2e36fc5c875740e2f2e4b6b95764179469635d0ecac7cd5f7912d57",
          "sha1": "37f4e395387ccebe629bc0e4a98eb26ade6e0470",
          "md5": "22c47a9e419b398c22465e854cdd54ad"
        }
      ]
    }
  ]
}
