{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.0.jar",
          "size": 477490,
          "sha512": "1b2717445234616d507fc6433e9f5a76be34bd5e8a34a79cd1d45faf98eacf47c1f82a7c4ef8d3fc27944cf15ed20f70c902e1dc43f1e587ca68d1fcf3f56229",
          "sha256": "71f0ea25d7facec8cb0432dacb173f27a60c894d8515d74224d1a927cd834338",
          "sha1": "1ffdf58c31a066e9160ca74d43b2c6e6c5983027",
          "md5": "dfc5b2e4081f71c82cb810bf4c738ad1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.0.jar",
          "size": 477490,
          "sha512": "1b2717445234616d507fc6433e9f5a76be34bd5e8a34a79cd1d45faf98eacf47c1f82a7c4ef8d3fc27944cf15ed20f70c902e1dc43f1e587ca68d1fcf3f56229",
          "sha256": "71f0ea25d7facec8cb0432dacb173f27a60c894d8515d74224d1a927cd834338",
          "sha1": "1ffdf58c31a066e9160ca74d43b2c6e6c5983027",
          "md5": "dfc5b2e4081f71c82cb810bf4c738ad1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.0-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.0-sources.jar",
          "size": 243035,
          "sha512": "6d84d02b9a43d33b8ef41c5c0249cf28c4131dffd19c0dbff125aedd7e06b7dc7290337b8c7df5f729c07bc44693a1706cd37f438cb23d41ee82e11d9ead5556",
          "sha256": "d34950da26e20f7d6ba8d656b9c9e2dbd686a5d3364b173b59023d2bb83d6ae9",
          "sha1": "feef119bb96cea201b92b07b41bebd45037321dd",
          "md5": "b6440c6627ab30b4c679c96e87ee9728"
        }
      ]
    }
  ]
}
