{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2502.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.3.jar",
          "size": 382808,
          "sha512": "daa8829f2e23412673cbcdc2628f46c8168b60332b952cda9a7d4a4083acf6eeedf4e8ac1ec6d7f81e9b8b3dcb55d5ebcd4d0ebcb8d9fbd2b0438ca3a268539b",
          "sha256": "a9b5a1929f7e47e33b63b78f3daa9d657e448b79e06a5699f5e2695c4a5badfc",
          "sha1": "73e848879b184569b7d2d98530cc601ce6f82135",
          "md5": "f361b35b1fb466ff8ed9ab099741c86b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.3.jar",
          "size": 382808,
          "sha512": "daa8829f2e23412673cbcdc2628f46c8168b60332b952cda9a7d4a4083acf6eeedf4e8ac1ec6d7f81e9b8b3dcb55d5ebcd4d0ebcb8d9fbd2b0438ca3a268539b",
          "sha256": "a9b5a1929f7e47e33b63b78f3daa9d657e448b79e06a5699f5e2695c4a5badfc",
          "sha1": "73e848879b184569b7d2d98530cc601ce6f82135",
          "md5": "f361b35b1fb466ff8ed9ab099741c86b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.3-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.3-sources.jar",
          "size": 198226,
          "sha512": "a7d07f928c903ebf408bdc8188a4f43e8f366a2a093134a34e3bac496e79d8002cacc020538de6e9d351bebdebde120d3eb4c5eb93f6cf29dc21b491305681ae",
          "sha256": "862eafa8ac7f5b6f05dc85f9cebb5651fe8e8d91654dd9aec89246f996540c4b",
          "sha1": "727482dd40ca9bd9f1b67f49f78060bd041f26dd",
          "md5": "fcbbaafbbc70b619c45579b9694eb654"
        }
      ]
    }
  ]
}
