{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.7.2606.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2606.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2606.0.jar",
          "size": 543106,
          "sha512": "eef604e43a6364eb11857c0fac407cff84d6005e7ffb3e7ad56c851ab53c367190d5c6bb192eb27085f1f9a7ff7a623588d034af29566329dd197c590dc377fb",
          "sha256": "7d983180276256cfd1a8d9b43d8ef0de733d43f1747ffd8178e836385efa84ae",
          "sha1": "e888960c226dc7d1086eafe17020c9830a710d45",
          "md5": "634f17c4b1d7938439b14fe02adf8365"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2606.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2606.0.jar",
          "size": 543106,
          "sha512": "eef604e43a6364eb11857c0fac407cff84d6005e7ffb3e7ad56c851ab53c367190d5c6bb192eb27085f1f9a7ff7a623588d034af29566329dd197c590dc377fb",
          "sha256": "7d983180276256cfd1a8d9b43d8ef0de733d43f1747ffd8178e836385efa84ae",
          "sha1": "e888960c226dc7d1086eafe17020c9830a710d45",
          "md5": "634f17c4b1d7938439b14fe02adf8365"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.7.2606.0-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.7.2606.0-sources.jar",
          "size": 256276,
          "sha512": "f0df74b156853984fb35ab210650c4f26febe18fe9ce8b5e5f06a7c6f4bcda3cff2f8d088f9504b72dfcc64209794fbbecdc3816a658cc4f034b1753d49d7500",
          "sha256": "abb470a85523c0da1a542fbeb26b8d92f9f468af35bf7c7beba36282ea9e3bbb",
          "sha1": "a17f2761d210d0c0d8674854f03828123fe6d7fb",
          "md5": "07aa6bdc056e42e85d81cdd9e0ad0616"
        }
      ]
    }
  ]
}
