{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.7.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.7.jar",
          "size": 495427,
          "sha512": "263b69d736dd28b006eddb174e3c7630e7be1b8fc9282c1e27a47495786e3c92655c4c72f759ba7d6ebc33a4f8f3e2cb7aa0a96f84007f239a8f0e7c137170d2",
          "sha256": "61d97305f1b0116eab809df7cf9951a0e1fd6333e0d81fa46f6990d0ad1a5a35",
          "sha1": "a6a047ce975ba74fa98cb3601c760b8a21cc32c1",
          "md5": "bbe69fb7a52807f28331f05e35215fb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.7.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.7.jar",
          "size": 495427,
          "sha512": "263b69d736dd28b006eddb174e3c7630e7be1b8fc9282c1e27a47495786e3c92655c4c72f759ba7d6ebc33a4f8f3e2cb7aa0a96f84007f239a8f0e7c137170d2",
          "sha256": "61d97305f1b0116eab809df7cf9951a0e1fd6333e0d81fa46f6990d0ad1a5a35",
          "sha1": "a6a047ce975ba74fa98cb3601c760b8a21cc32c1",
          "md5": "bbe69fb7a52807f28331f05e35215fb1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.7-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.7-sources.jar",
          "size": 244608,
          "sha512": "55182fb4204b0f823fe749d36d4fac69b8df3daa0194b6891447352c0dc842cbd7cfc9118df55ae3468549bbbc809f7970c05d10a29ff99c8f924511abd5c0e2",
          "sha256": "a8545117efce7b37626c2bbbed74a88f230056bfa3f4de7b230bdd0efba67e5b",
          "sha1": "d0fba475444687b2a0df1e36cc3a36c72f08f334",
          "md5": "46e7cb0241d3b8c530d384afd1b0fbc2"
        }
      ]
    }
  ]
}
