{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.8-2.2.7.2616.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2616.2.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2616.2.jar",
          "size": 603414,
          "sha512": "704f2935467acea46412cf9040ecba37a84abf8ec56bce97152e6f34c7e1f12182b8b5939520ea6edf8df115051e4445f9b4ef7835da67c6e6eb092ca6fd2458",
          "sha256": "b5dd4dd2e7ddf32dd5fd751dbf32e2d3dadbaa6a451483c70998254d8a26c3fd",
          "sha1": "77f7eea688752e8180ca8fca213b3c8e5dda6900",
          "md5": "f9c02427c0623beb0e6a2956982567e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.131.0+1.21.8"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "15.0.0-beta.3"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2616.2.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2616.2.jar",
          "size": 603414,
          "sha512": "704f2935467acea46412cf9040ecba37a84abf8ec56bce97152e6f34c7e1f12182b8b5939520ea6edf8df115051e4445f9b4ef7835da67c6e6eb092ca6fd2458",
          "sha256": "b5dd4dd2e7ddf32dd5fd751dbf32e2d3dadbaa6a451483c70998254d8a26c3fd",
          "sha1": "77f7eea688752e8180ca8fca213b3c8e5dda6900",
          "md5": "f9c02427c0623beb0e6a2956982567e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2616.2-sources.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2616.2-sources.jar",
          "size": 256769,
          "sha512": "fe46438f83193b37129d2698c9efa44f1309e41922893fc37c6ff41ed0d8f9ac39ee4d413ed3259d701153e9f89f4f4961b526c043e4538e6138062da9998ce4",
          "sha256": "ff0d04bf47b64f3b8c39990ed241899476cebcdf30e2c3919abadb89262589dd",
          "sha1": "1001a2dbcb91f5eb49205dba84b8384a50281aa7",
          "md5": "66d2c8b2e06e6fb587c98b6c64996e65"
        }
      ]
    }
  ]
}
