{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "size": 717299,
          "sha512": "294252ea51ec00a1bdfb95b2cc5f49eabdc8b6fec25b683087d54a22c757e25040d7c9a7d26ab57a83da955dabe8ca5a593a90255e113cdfc3b4e823a142a0b2",
          "sha256": "b65eb8ec068c1347f415c23d60e900ff3378cf2164fac46facb205f1dd4531c9",
          "sha1": "81cd08e254915b9aaad5cc720d3ea5a96d16f115",
          "md5": "5bad9abd75fa70222f34af8c29ae8a56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "size": 717299,
          "sha512": "294252ea51ec00a1bdfb95b2cc5f49eabdc8b6fec25b683087d54a22c757e25040d7c9a7d26ab57a83da955dabe8ca5a593a90255e113cdfc3b4e823a142a0b2",
          "sha256": "b65eb8ec068c1347f415c23d60e900ff3378cf2164fac46facb205f1dd4531c9",
          "sha1": "81cd08e254915b9aaad5cc720d3ea5a96d16f115",
          "md5": "5bad9abd75fa70222f34af8c29ae8a56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2517.0-sources.jar",
          "size": 254761,
          "sha512": "3e1a634063048deeeecaced80e5748c8e76c3ff4dbb999407d51ba7ca40be5b11176616ccf6f04e0523ccaa40b68e271775e2d83065c12b6485057689ce8e517",
          "sha256": "0f9272629d149ab406eea423b915841e9ba0f7437d7d1a6a361ff1266917e65b",
          "sha1": "70bd92a70beec2c0412ea14b307aff9a9b6ad5ba",
          "md5": "4a464c525c0c08937a5bccbd5acec7a8"
        }
      ]
    }
  ]
}
