{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "size": 715297,
          "sha512": "d8c30e5661460bec0c86a7517928309c59d798b42e7b1084fdd7aa9a4a2e54f480ac4843aca82d2cf9a18ea459d1a854fb697e007aa5bc764a8f845fb842e987",
          "sha256": "da2a64182b99a1dd3328aa9bbb191a070ce93ba1db48e7d116bc2a6806493c16",
          "sha1": "8406140cb5c7e3753e47ebfa096568740087f6e9",
          "md5": "c89898ce1677fffc9c1bd467dbe674b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2517.0.jar",
          "size": 715297,
          "sha512": "d8c30e5661460bec0c86a7517928309c59d798b42e7b1084fdd7aa9a4a2e54f480ac4843aca82d2cf9a18ea459d1a854fb697e007aa5bc764a8f845fb842e987",
          "sha256": "da2a64182b99a1dd3328aa9bbb191a070ce93ba1db48e7d116bc2a6806493c16",
          "sha1": "8406140cb5c7e3753e47ebfa096568740087f6e9",
          "md5": "c89898ce1677fffc9c1bd467dbe674b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2517.0-sources.jar",
          "size": 254315,
          "sha512": "8b0872f7c2277e304bef30cd9ff4ad45bdafe6fd0b30b4a9254b311c990cdfc0806858fceef49537550620e860e2e2cc5b08021537c1c670ba52d69235203308",
          "sha256": "896897776b68e01ae946f65b2e9e18c72e0f179988c44270061735aceab0b2db",
          "sha1": "e68bb9ff0848f6c5154fcb1d145b57ffc75fd792",
          "md5": "d9a5b3ce990b181784a995a98cad12f6"
        }
      ]
    }
  ]
}
