{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.2507.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.3.jar",
          "size": 480752,
          "sha512": "d6fb55840ffd14c2d08e9d45842b9d21dd888238d857a236f82fa7cb33ef72127759ec45bf5265f29163bd0732743d5f1745a0a4d6c05e7d262ad82ebbfa289e",
          "sha256": "3e951b2539d1272f7f4c34a3df9c32b71aa714da7cea090c325b1a2e583b3b2d",
          "sha1": "5488175e9ef9cbe6375dc6f4b03f9e86ad69c856",
          "md5": "34e81d465405ceda9274ebe50e92aa75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.3.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.3.jar",
          "size": 480752,
          "sha512": "d6fb55840ffd14c2d08e9d45842b9d21dd888238d857a236f82fa7cb33ef72127759ec45bf5265f29163bd0732743d5f1745a0a4d6c05e7d262ad82ebbfa289e",
          "sha256": "3e951b2539d1272f7f4c34a3df9c32b71aa714da7cea090c325b1a2e583b3b2d",
          "sha1": "5488175e9ef9cbe6375dc6f4b03f9e86ad69c856",
          "md5": "34e81d465405ceda9274ebe50e92aa75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.2507.3-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.2507.3-sources.jar",
          "size": 245809,
          "sha512": "7e2a667d7056b52149d4dea122841805814d63df5fc531f74c529ae48eb21249d0f52672fc8aae9dc5a38ffed6d7b7e40ca3781b03ac5c4f499f3194aed0ab7a",
          "sha256": "3436a8335e3dec9a1fe88469c80a3417bb173021571052a1d70979dc8c0a7ea7",
          "sha1": "677e262fa3c0f91a8efd35e7a57e8b1f18024c1d",
          "md5": "36d02c71617034f2590e5d03fc32faec"
        }
      ]
    }
  ]
}
