{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2507.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.9.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.9.jar",
          "size": 495715,
          "sha512": "d0ea337035a9fefae683a94b42760859f8ce3c051aafcb1b54fc29ad68ec3ed188b6a20358f6370f09435a879ce7a0e2b6a5e7c46a19ae67aaa69f8c3c1b4fab",
          "sha256": "0ba898c0687152b4a9adb5906c4c75516d280bbcac5b1bc630c263fa1490c03b",
          "sha1": "181a860fdf9805abe1f037bc1a4ebafbdb9886db",
          "md5": "8e6ec00848715d39ff4e31bcfe8d3ab0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.9.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.9.jar",
          "size": 495715,
          "sha512": "d0ea337035a9fefae683a94b42760859f8ce3c051aafcb1b54fc29ad68ec3ed188b6a20358f6370f09435a879ce7a0e2b6a5e7c46a19ae67aaa69f8c3c1b4fab",
          "sha256": "0ba898c0687152b4a9adb5906c4c75516d280bbcac5b1bc630c263fa1490c03b",
          "sha1": "181a860fdf9805abe1f037bc1a4ebafbdb9886db",
          "md5": "8e6ec00848715d39ff4e31bcfe8d3ab0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2507.9-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2507.9-sources.jar",
          "size": 244739,
          "sha512": "63a197ced04047370f8a39354fca397ab76858a8f647779bafdc284e9a45816158bded8182bd6052c3364f21deee295c85198457a2ff55877c566e7b28458dd3",
          "sha256": "50f2e6395bb5188130aad1030fce07e534ce8d90923f6c848d67eccb6603c75d",
          "sha1": "0f0011f5be01f0935b9abbecca4fa8d8e519f8aa",
          "md5": "a2d744c058e4840d2cf81f6690cf48af"
        }
      ]
    }
  ]
}
