{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.2.jar",
          "size": 709269,
          "sha512": "32b72c2f231dbe987f0170181a960b52e17a75dc6213140c001dbf12b793135d9623865de75b617f41155ca74a54a7347ff528d552f26229e0e548b909aa075f",
          "sha256": "f47cd4c0011533a2ef0939dfda99c5b4980bc270ae22e25f244d0d5dbf3e32cb",
          "sha1": "6edc0d890af34545ca22526b4f07aced29a8b48e",
          "md5": "81c53ef83013d8491ebb1bf80f727b1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.2.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.2.jar",
          "size": 709269,
          "sha512": "32b72c2f231dbe987f0170181a960b52e17a75dc6213140c001dbf12b793135d9623865de75b617f41155ca74a54a7347ff528d552f26229e0e548b909aa075f",
          "sha256": "f47cd4c0011533a2ef0939dfda99c5b4980bc270ae22e25f244d0d5dbf3e32cb",
          "sha1": "6edc0d890af34545ca22526b4f07aced29a8b48e",
          "md5": "81c53ef83013d8491ebb1bf80f727b1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2514.2-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2514.2-sources.jar",
          "size": 252842,
          "sha512": "39b8b13d729593d2870900b019e4314f964ce8ffa6168b0f0020229df8482d159543a23e12121867fe244ab58e37775294639c0cfa49e1fd22dabd162447bf41",
          "sha256": "bbdaab20c3b1084eef9ba8efbeb9ac2e2975440482432703d1f3437c04f5cd44",
          "sha1": "73e3c87d85aab6f9f40cb169204fbc73580191b1",
          "md5": "fe2eaf82347f1469642430ed5b68b2ec"
        }
      ]
    }
  ]
}
