{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2507.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.13.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.13.jar",
          "size": 498594,
          "sha512": "9fbcabb80373dcc1e71e845d6d8da3d78d1462e30d996ffcc1b6db3344bdb90b21c5c228c158fcb7c2dc299f6b44a1591c9ba4950718cc914849137508956c2f",
          "sha256": "f4e7f0669c67f5df80c4b1b333de159dad6707bc125187aae6073af102d753b0",
          "sha1": "1a7c5bb18416691369d5a80a5c5c461f8918a66f",
          "md5": "c73a33538025e4af04f10d57f686fb96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.13.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.13.jar",
          "size": 498594,
          "sha512": "9fbcabb80373dcc1e71e845d6d8da3d78d1462e30d996ffcc1b6db3344bdb90b21c5c228c158fcb7c2dc299f6b44a1591c9ba4950718cc914849137508956c2f",
          "sha256": "f4e7f0669c67f5df80c4b1b333de159dad6707bc125187aae6073af102d753b0",
          "sha1": "1a7c5bb18416691369d5a80a5c5c461f8918a66f",
          "md5": "c73a33538025e4af04f10d57f686fb96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2507.13-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2507.13-sources.jar",
          "size": 244787,
          "sha512": "e240e77fba265bcb86b2d1908a1560094fe9153d24c58a43cd6c7f7820f6dfa7a200ce9bc652a928f61d0a4da5dca194d10ab961ece35abda9c907d4df210dad",
          "sha256": "c0d6103ecebfa5dc2df26f0267b6bf77a530a7de6d2c93ca1deed46a0eff45f9",
          "sha1": "ad46ad2c4a546316b5a10bf42a9d802665ad3b12",
          "md5": "6d6a6a1b66a38e66009f5df3dd9eb947"
        }
      ]
    }
  ]
}
