{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.4-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "size": 559389,
          "sha512": "c6c4be7d5568d2b3af0e2bff3424733c90080831b0e52d8163aec3ee079cedc9678101ba0895b212bc1df98c057cfb8e4febb1e47fabb5c307af1c9e7a30134a",
          "sha256": "efcffd6f21b7e7a90b1f9af22be63985fb7674d35ace8ae781ea2d0647ea66a6",
          "sha1": "66ca9d4561292f93bedd02fdd6b6c7cbfcccf9dc",
          "md5": "63c62e9cfdf752014cda4c1f1b35bc86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "size": 559389,
          "sha512": "c6c4be7d5568d2b3af0e2bff3424733c90080831b0e52d8163aec3ee079cedc9678101ba0895b212bc1df98c057cfb8e4febb1e47fabb5c307af1c9e7a30134a",
          "sha256": "efcffd6f21b7e7a90b1f9af22be63985fb7674d35ace8ae781ea2d0647ea66a6",
          "sha1": "66ca9d4561292f93bedd02fdd6b6c7cbfcccf9dc",
          "md5": "63c62e9cfdf752014cda4c1f1b35bc86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2516.5-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2516.5-sources.jar",
          "size": 252501,
          "sha512": "7fa39f3294b25bebe9970824e916ac7440513431f203349b351a2b7ec13eafe392e4db928781804e2afb45534ed7bd46d12c4fe23c8c155d8b8e6fbc9645ec9a",
          "sha256": "17a180fffde74778cd2aff586e796a5a94739a338161e42548127398739b1fee",
          "sha1": "4fc4285a181d196213a39c4cee99001edf4bafec",
          "md5": "c23064f0689696142dbf79b3a5daa7ad"
        }
      ]
    }
  ]
}
