{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.4-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "size": 560000,
          "sha512": "c24c7aad235b1ba8446c58f42e0187e527e664a5e6765f3258854ac3cb99646770bff426eeb437e67436d68817e489de75fb150542d299db0adbb80f4d927483",
          "sha256": "619c823f79ba20af09f3bbe6202584ed04dbecbfe6425b75505ebf9670b91002",
          "sha1": "d03c016c747c1f012335f4fe70d7a365ba635b2d",
          "md5": "89f9e1d8532d93636d4da3a2ba2a7013"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2516.5.jar",
          "size": 560000,
          "sha512": "c24c7aad235b1ba8446c58f42e0187e527e664a5e6765f3258854ac3cb99646770bff426eeb437e67436d68817e489de75fb150542d299db0adbb80f4d927483",
          "sha256": "619c823f79ba20af09f3bbe6202584ed04dbecbfe6425b75505ebf9670b91002",
          "sha1": "d03c016c747c1f012335f4fe70d7a365ba635b2d",
          "md5": "89f9e1d8532d93636d4da3a2ba2a7013"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2516.5-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2516.5-sources.jar",
          "size": 252513,
          "sha512": "322e401903bb6d6dc880374ca5668b047ca1e209ee0333bae506e998f550978286fa7f074c387d2b312d5dead5a8652827a4ae4627a3e439e5f8c7e0c014fd2b",
          "sha256": "023f241b07a12199dae64009db19992e05e8733936c118ff2e16d139541da845",
          "sha1": "7f46b8a41cafcf9ec98cbab15ca31e69cbb9d033",
          "md5": "6eee9d505b2edab1270633365b9c4eb5"
        }
      ]
    }
  ]
}
