{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.9.jar",
          "url": "factory_api-fabric-1.21.3-2.2.9.jar",
          "size": 595754,
          "sha512": "70d1e1a215f3ef182035373b165230241c2b5ba97c2364be60dcb52f04f0dd3c19eaee069da305675adeb1c0a00a705f6a52471b3d384869acce67bfec43d65e",
          "sha256": "3ac7ec1d63dbfd1894a264216af092c3cbcebf0e0ecc3cdf7da7912819ee1a4d",
          "sha1": "5b85a70a2e3ba437f2fc75f9774ea511a722057b",
          "md5": "96612a8cf0e72317a216ce888c507e76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.9.jar",
          "url": "factory_api-fabric-1.21.3-2.2.9.jar",
          "size": 595754,
          "sha512": "70d1e1a215f3ef182035373b165230241c2b5ba97c2364be60dcb52f04f0dd3c19eaee069da305675adeb1c0a00a705f6a52471b3d384869acce67bfec43d65e",
          "sha256": "3ac7ec1d63dbfd1894a264216af092c3cbcebf0e0ecc3cdf7da7912819ee1a4d",
          "sha1": "5b85a70a2e3ba437f2fc75f9774ea511a722057b",
          "md5": "96612a8cf0e72317a216ce888c507e76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.9-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.9-sources.jar",
          "size": 256572,
          "sha512": "5af1a755a5c5f2b4ca24e8261f21fdf9d87850497df1cdfe9b63494359c75ee52c9156a73be0cda440bace15b69b94dc0814a9a2d9aba07c5cd92a7e934d6cc7",
          "sha256": "f95f5bfba0bdc9a2439a3cf6281bf0af894979a1d8f89a1b127a5a4f98a289ce",
          "sha1": "8b9fefea6f78d11c9224c569222e8e33de8e1914",
          "md5": "348ac38c5b56d3e0d74023b4ab829e96"
        }
      ]
    }
  ]
}
