{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.8-2.2.7.2616.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2616.0.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2616.0.jar",
          "size": 603424,
          "sha512": "48c5cdccf1920d87d261fdfc41fb91d95417554363b1afdd06eccfae4b21cffd042abdaecee2c26a5171e5175752da93f8652e1baad6d2b749b472c39f207c9f",
          "sha256": "fd826bce71c988b8eb8bbb9803d9abb5f4ab7b594d163c961fb572009a3b8deb",
          "sha1": "95544ab17db300f7c6b62293098360321b9a6ef7",
          "md5": "3567ba3b1089b2a1a3e580b27d5111a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.131.0+1.21.8"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "15.0.0-beta.3"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2616.0.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2616.0.jar",
          "size": 603424,
          "sha512": "48c5cdccf1920d87d261fdfc41fb91d95417554363b1afdd06eccfae4b21cffd042abdaecee2c26a5171e5175752da93f8652e1baad6d2b749b472c39f207c9f",
          "sha256": "fd826bce71c988b8eb8bbb9803d9abb5f4ab7b594d163c961fb572009a3b8deb",
          "sha1": "95544ab17db300f7c6b62293098360321b9a6ef7",
          "md5": "3567ba3b1089b2a1a3e580b27d5111a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.8-2.2.7.2616.0-sources.jar",
          "url": "factory_api-fabric-1.21.8-2.2.7.2616.0-sources.jar",
          "size": 256764,
          "sha512": "303f084b3c226bc83c1ec7b3a16fcc5fdd285b8aab8a4d423332d83c54c4d3d39418ad70f92664d53b0381b99655df6b9ff2ff24ed6281f9a73fdb75b0919d29",
          "sha256": "7fc6f7555d67aa82f836f1acffedd68f3ac3cca700159ea9b95ae87cd2670d15",
          "sha1": "b040d5062753cb334c125bcbe287c407be9250bf",
          "md5": "86a81d0daf73b940f838609af43c5939"
        }
      ]
    }
  ]
}
