{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.3.2510.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.2.jar",
          "size": 682831,
          "sha512": "82a8b561145acc8c8cc6b72a172aa22b70c55bb59298559aded120f17bf48c761aab5900da3a1a41c68785e583fb139bca82420476b28131f917628f8cb657e1",
          "sha256": "16627a9f9591247db1536d153561b58989de2c3c021a86d9ff357bc5a8a0de16",
          "sha1": "e8babbb37da71ec9d2ba98abff26bd476daaddaa",
          "md5": "38f242299137f74cb841815d7c1c3510"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.2.jar",
          "size": 682831,
          "sha512": "82a8b561145acc8c8cc6b72a172aa22b70c55bb59298559aded120f17bf48c761aab5900da3a1a41c68785e583fb139bca82420476b28131f917628f8cb657e1",
          "sha256": "16627a9f9591247db1536d153561b58989de2c3c021a86d9ff357bc5a8a0de16",
          "sha1": "e8babbb37da71ec9d2ba98abff26bd476daaddaa",
          "md5": "38f242299137f74cb841815d7c1c3510"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.3.2510.2-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.3.2510.2-sources.jar",
          "size": 250444,
          "sha512": "ed499134be388a86b58a2891c882b4893149f4593383d25571e27eb6aae1cf9d0de558e6c004a78876844969aa6f7c9ef57a8666d062c6c96db7d2296a8e1b53",
          "sha256": "983665a659d84a3537414b24245349ebba4bebe3fc09846da4b311f4ed6bf7f3",
          "sha1": "7cc770f655f30be7bced4d7f973239e9ecdbf339",
          "md5": "7e46b73c8134a1106c563ea3d28e6969"
        }
      ]
    }
  ]
}
