{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.5-1.8.0.2515.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2515.1.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2515.1.jar",
          "size": 18255297,
          "sha512": "4e949c9fefcc6426d624c20d9a102cda7acd4eb2440b6a6dd9790fd4f1ac020628d3873c29d90f95bea323ddeb3cd35c5a3f30ab36fb05ccfa20840ff33dd0c5",
          "sha256": "184edd06aefd8dcda8a9afb0e95a5b9a811f00289d8c0a65f74fce0ce06e2ad8",
          "sha1": "ad9a3df6f2dcee5f88ae5f8d4a177deafb610716",
          "md5": "80764426257e311e3bdb6a29467d7beb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "14.0.0-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2515.1.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2515.1.jar",
          "size": 18255297,
          "sha512": "4e949c9fefcc6426d624c20d9a102cda7acd4eb2440b6a6dd9790fd4f1ac020628d3873c29d90f95bea323ddeb3cd35c5a3f30ab36fb05ccfa20840ff33dd0c5",
          "sha256": "184edd06aefd8dcda8a9afb0e95a5b9a811f00289d8c0a65f74fce0ce06e2ad8",
          "sha1": "ad9a3df6f2dcee5f88ae5f8d4a177deafb610716",
          "md5": "80764426257e311e3bdb6a29467d7beb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.5-1.8.0.2515.1-sources.jar",
          "url": "legacy-fabric-1.21.5-1.8.0.2515.1-sources.jar",
          "size": 17422538,
          "sha512": "3fe8584e8bad73f39fead6f904245e4f4809356a32fedc06dff9062f3a4b3444e0c30f8b1010500c250cf57e83a800c6e9fa34e7c9e189b46af91a8f822bcef6",
          "sha256": "d393aab7f33019feb7de1b1d56a6d9b6801c8a44ca8e6e002d5305e77fb6d5ab",
          "sha1": "2aeb5f83d1f1596dc8cc01393b245585da3f1425",
          "md5": "05267cd81a210638f2120cde91ed9e6c"
        }
      ]
    }
  ]
}
