{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2518.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2518.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2518.0.jar",
          "size": 531537,
          "sha512": "55737ce7dc75ce95ed1271b67681fb1e2cbe50d4dc9f2babaaff920b2cfbec40432163271f4b028de634e5d199bdb760d8a915ab8ea1a0fadcb78e670ca6bdbc",
          "sha256": "bd4794f0f688df5c02811835e8f51776c7279d00a44080904d81646cd32769fa",
          "sha1": "5b156da0e95af73d521aa8ec9c075d0935913acc",
          "md5": "5d6d55adb52efb769460e69e75e26ad8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2518.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2518.0.jar",
          "size": 531537,
          "sha512": "55737ce7dc75ce95ed1271b67681fb1e2cbe50d4dc9f2babaaff920b2cfbec40432163271f4b028de634e5d199bdb760d8a915ab8ea1a0fadcb78e670ca6bdbc",
          "sha256": "bd4794f0f688df5c02811835e8f51776c7279d00a44080904d81646cd32769fa",
          "sha1": "5b156da0e95af73d521aa8ec9c075d0935913acc",
          "md5": "5d6d55adb52efb769460e69e75e26ad8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2518.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2518.0-sources.jar",
          "size": 254759,
          "sha512": "74c998e2d0e44f71277b4f2b89ebf53c6477bf2c191afaaa5224b5ce89a4625ecf213d1e6d75faf04ccba0bed9fc74edaccd72388f7825abf5a438f033b4aa12",
          "sha256": "2f51d2094542506b1382de801ec56956159c1a92b555d9d0659da3b8b388505f",
          "sha1": "d90806be4d5a66fce9908cc53c1c69c23f830c66",
          "md5": "473f8915ed856c9bfe77d73253882639"
        }
      ]
    }
  ]
}
