{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.1-2.2.2506.0.jar",
          "size": 468213,
          "sha512": "d0f975267e2f5f498485164f2834e38c7826e3b4a55419c3fa156dd541a2bc8f936df891f7825d4bb17a39576c33aeebd1b406061d347bca2e0a481853059281",
          "sha256": "d27cdcc5dadf0ef49c7ee4d76367e9a4303fd8cde9c4e77a7d7a63d66433c06a",
          "sha1": "bcfc3376c30e6f322c408910b686f05d08227ee0",
          "md5": "952c20a8dff0a0071488d490b0ad9247"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.1-2.2.2506.0.jar",
          "size": 468213,
          "sha512": "d0f975267e2f5f498485164f2834e38c7826e3b4a55419c3fa156dd541a2bc8f936df891f7825d4bb17a39576c33aeebd1b406061d347bca2e0a481853059281",
          "sha256": "d27cdcc5dadf0ef49c7ee4d76367e9a4303fd8cde9c4e77a7d7a63d66433c06a",
          "sha1": "bcfc3376c30e6f322c408910b686f05d08227ee0",
          "md5": "952c20a8dff0a0071488d490b0ad9247"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2506.0-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2506.0-sources.jar",
          "size": 236853,
          "sha512": "2573200e6574edc73f5d2f4b82465375d433d7b7dd3646a5b26c19650431b8711611e1b8d0137f418951069e8a7df1ff8732d7eb7dd36d220b835c64a70e5283",
          "sha256": "c89919794cbf5f16985e7faa686d879981083342f01acf4a40df2f2af3c42a40",
          "sha1": "d3fedde6cb5246e8885fc3cd1d7b9f46728bb695",
          "md5": "e7490e78b9c1d093886883e42bdb9619"
        }
      ]
    }
  ]
}
