{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.9.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.9.jar",
          "size": 356478,
          "sha512": "02a148471854742b338930a369ca1346b14dd43cf2fb1981b822a9a1df8fe3484dc62e286b7905e2f94005f4e466feec6895a32486a483a8b2a550cc802bb749",
          "sha256": "3cb9521a8ad25d29701e6b18700d9c7471982528d34dd93a8a5eacdd647204e7",
          "sha1": "5cfc872ab514aeef5af37f9be9d974ece10d4a44",
          "md5": "4562d02399e31be4ec5d6a0141a667de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.9.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.9.jar",
          "size": 356478,
          "sha512": "02a148471854742b338930a369ca1346b14dd43cf2fb1981b822a9a1df8fe3484dc62e286b7905e2f94005f4e466feec6895a32486a483a8b2a550cc802bb749",
          "sha256": "3cb9521a8ad25d29701e6b18700d9c7471982528d34dd93a8a5eacdd647204e7",
          "sha1": "5cfc872ab514aeef5af37f9be9d974ece10d4a44",
          "md5": "4562d02399e31be4ec5d6a0141a667de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.9-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.9-sources.jar",
          "size": 196846,
          "sha512": "5b344d21094c0ceb43a514edfb8825e9adaf09ac29fecc63211b9c02177dc3cdc42ee2c7c5767d74ecfdfb00bf23c7b7295c5152c9c626f6fac930253916ab24",
          "sha256": "161bd37f9fca54e8302413fa60280ace2ed2862036b774ff63aa5a682c48f6d3",
          "sha1": "58d0f2148da27ac2935c052948744ad3f5df5fb3",
          "md5": "edc74472a8440c36e28a7c667d5f2c85"
        }
      ]
    }
  ]
}
