{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2516.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2516.0.jar",
          "size": 525864,
          "sha512": "43703e8bbad059d5924b60bfe1219de9334dc5c5f0d983ce477428118ce9d9722496b10ad754ca11ef5f5adbb41e2d188a15c23dc4ff04586936726cd7160bf5",
          "sha256": "aee438b69737c9c4dfe0f3853fa4718ca3accee5afd74a434835230e53a8d539",
          "sha1": "c9d68dc9ed39d1109871fd09a71dc1c29b4a2fc9",
          "md5": "fc07435ba624e4072ef6d24c56831950"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2516.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2516.0.jar",
          "size": 525864,
          "sha512": "43703e8bbad059d5924b60bfe1219de9334dc5c5f0d983ce477428118ce9d9722496b10ad754ca11ef5f5adbb41e2d188a15c23dc4ff04586936726cd7160bf5",
          "sha256": "aee438b69737c9c4dfe0f3853fa4718ca3accee5afd74a434835230e53a8d539",
          "sha1": "c9d68dc9ed39d1109871fd09a71dc1c29b4a2fc9",
          "md5": "fc07435ba624e4072ef6d24c56831950"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2516.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2516.0-sources.jar",
          "size": 253418,
          "sha512": "da9e173c32524384b9c7c0a5a41a405d35183bf91aaf6247ec6f652c143c0f4acbfb52a07c5dff9977232ec5ca700c9c51d05ee5d93c26c7a0a938be7bb94343",
          "sha256": "e32841376d15ef938ece08bfd43b17539df7c7fc946256e0911360b395820cf8",
          "sha1": "a8c9c181baa087f1f08e6c1881e94275e37ff940",
          "md5": "70f16f919ffab2d60245998a8de62e0a"
        }
      ]
    }
  ]
}
