{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2501.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.12.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.12.jar",
          "size": 362440,
          "sha512": "3802b7021b0796fefe6ea3a483ea9ddbe7528bb3d9e70960bc26a8238a09ab0ec5f21e594edfe572acd808208568e879075ed7790608c2af62350c1c75197be8",
          "sha256": "9f8e73afa1486c2e2f798787b526f9ca451c61a1aaf19ddb1dc8aa73865effed",
          "sha1": "0e31de72691e5c487d8ce50d83419b6d46fccf3c",
          "md5": "a63e43435be253c84865fc28b7922561"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.12.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.12.jar",
          "size": 362440,
          "sha512": "3802b7021b0796fefe6ea3a483ea9ddbe7528bb3d9e70960bc26a8238a09ab0ec5f21e594edfe572acd808208568e879075ed7790608c2af62350c1c75197be8",
          "sha256": "9f8e73afa1486c2e2f798787b526f9ca451c61a1aaf19ddb1dc8aa73865effed",
          "sha1": "0e31de72691e5c487d8ce50d83419b6d46fccf3c",
          "md5": "a63e43435be253c84865fc28b7922561"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.12-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.12-sources.jar",
          "size": 197187,
          "sha512": "e19d59f93ed560960431b3459786bfd307a5378c988a81e09b7a40cc29eaa5032d27b546d643202ef0010de5d63100bc9d066795a731a95be313ca27979f30fb",
          "sha256": "3eae2109d5c5acfd527c04c214b86cb6123bb451c9bdec24c605635cd3c3d3f2",
          "sha1": "bfcd948198b8ddc4de8c81bcff6eefdc378372a7",
          "md5": "a6b968a7524e9695aa741af73f43a101"
        }
      ]
    }
  ]
}
