{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.21.5-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.5-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.5-1.1.2516.3.jar",
          "size": 637299,
          "sha512": "7a7b83efb436768fc1f1f48e30b33ff5f3a93faac0040bbf0f671a3b8a477ceb02c59df868c1a929e9473f193a43fa6ac816513f021493be077be53a46d08d06",
          "sha256": "4d56c40e7bf9f6727d139ec5809201633e72ae6efde2454716fa07dc8abe8e88",
          "sha1": "aa4c3bc434a5822814a8b887e81054e5570145d4",
          "md5": "fcb86f6d9fff07e08f87e09c07457d5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.5-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.5-1.1.2516.3.jar",
          "size": 637299,
          "sha512": "7a7b83efb436768fc1f1f48e30b33ff5f3a93faac0040bbf0f671a3b8a477ceb02c59df868c1a929e9473f193a43fa6ac816513f021493be077be53a46d08d06",
          "sha256": "4d56c40e7bf9f6727d139ec5809201633e72ae6efde2454716fa07dc8abe8e88",
          "sha1": "aa4c3bc434a5822814a8b887e81054e5570145d4",
          "md5": "fcb86f6d9fff07e08f87e09c07457d5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.5-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.21.5-1.1.2516.3-sources.jar",
          "size": 583025,
          "sha512": "b329fd499e8d23cd331d1eaa6c570e8bfa8625af6ba6b0df3f6f7cd2530add05e124b92d2d23cf518cfb3489c234854ab56d382cca8a63aa11e6182fb88d4285",
          "sha256": "663ece2ee12698b892c33c13f8fa77b31719f64df707a03b99f1c0cfddafe604",
          "sha1": "987e839577c8c3f69f54233d2a5327afe0017f57",
          "md5": "c1694209318d9278c5143452bfa97933"
        }
      ]
    }
  ]
}
