{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.7.10.2502.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2502.8"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2502.1.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2502.1.jar",
          "size": 11943589,
          "sha512": "e3818055c86aea1c715e600d0fe99fa751b4b134db0274ac4786731da53bb70f74f7706d5967cc0f17d8ad9b7b7e9331c9bdb7262918101de332a72ab70ada60",
          "sha256": "9742a485aa504fc55a414f510512c3c355c06648b3c8393b0ff023456fe5261b",
          "sha1": "acc3103097b6603f0cc81a08bbf03d0ec7ba4b9f",
          "md5": "e9f00dde8dbfa948408a195538a8af29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2502.8"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2502.1.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2502.1.jar",
          "size": 11943589,
          "sha512": "e3818055c86aea1c715e600d0fe99fa751b4b134db0274ac4786731da53bb70f74f7706d5967cc0f17d8ad9b7b7e9331c9bdb7262918101de332a72ab70ada60",
          "sha256": "9742a485aa504fc55a414f510512c3c355c06648b3c8393b0ff023456fe5261b",
          "sha1": "acc3103097b6603f0cc81a08bbf03d0ec7ba4b9f",
          "md5": "e9f00dde8dbfa948408a195538a8af29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2502.1-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2502.1-sources.jar",
          "size": 11149110,
          "sha512": "875fb40bf193cee3f02f2fdf7525df7410f3e7d9ddc0f252dfdb42e2f69ce26a412e4ff787e075c928692f132bd1637be63575e0e8d74f44f674601cdc3d0e77",
          "sha256": "7d088c75ec23346ed9d53f90b0342c835179b7b383ca6dd375f19950a7b0bd64",
          "sha1": "9cce508352c8750908b0b2c3c1136eea41f3299d",
          "md5": "9d221edbfcd39276d42b16bd263b9e61"
        }
      ]
    }
  ]
}
