{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2504.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.0.jar",
          "size": 448609,
          "sha512": "eedb6e1d7895c96ef03cabbae6612ef627e80e6d9a36423c642768d2376d9dbd65a56a98cb0ca6899b2b105c40a7c930933aab041ae0487a33f18c4a72419644",
          "sha256": "b1d5608852a0432d7fdb952ed9b58514675498313355cde1f29650ad9e86d9b8",
          "sha1": "3e47c82845a031fe5062a9cad4ee134109e11b40",
          "md5": "3109b1ee1444d120ac4318c3e6289e38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.0.jar",
          "size": 448609,
          "sha512": "eedb6e1d7895c96ef03cabbae6612ef627e80e6d9a36423c642768d2376d9dbd65a56a98cb0ca6899b2b105c40a7c930933aab041ae0487a33f18c4a72419644",
          "sha256": "b1d5608852a0432d7fdb952ed9b58514675498313355cde1f29650ad9e86d9b8",
          "sha1": "3e47c82845a031fe5062a9cad4ee134109e11b40",
          "md5": "3109b1ee1444d120ac4318c3e6289e38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.0-sources.jar",
          "size": 231472,
          "sha512": "2df138d6d4f765b8869104e3aea3706d51ab3288dee3add4c0edc5380f6f9ee9a03155f3c5d7a214cd105366cd9af05b714b02efa45e9bfd629e4ab1cd510bb4",
          "sha256": "3077d805ecb8fe38cf25e64ab35668565b6706a2d16b40ee8dc48de3dd3ba610",
          "sha1": "7382e993c8ce1a3697fe0ce35f6e98d7a04c4bb4",
          "md5": "d7073ce997ce3fa1e1c08b10e042d04e"
        }
      ]
    }
  ]
}
