{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.8.0.2512.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.4.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.4.jar",
          "size": 18244934,
          "sha512": "7b269139a3a1ad7c1a2c1ea06f14a13f197fac6cd9fabb85b355716de68e2605817333d11b16dfd0a20fc3111101ca079b375b125eb7e216b3202ec75196ce38",
          "sha256": "382912137fffb0852543701958ea80961daf2f55c09da55aea461cddc6a3aeb9",
          "sha1": "64ede393bcea0de14706e4e1e676a61ed484d58f",
          "md5": "6cda0b6a0ef7c8e0b36c669c717d643c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.4.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.4.jar",
          "size": 18244934,
          "sha512": "7b269139a3a1ad7c1a2c1ea06f14a13f197fac6cd9fabb85b355716de68e2605817333d11b16dfd0a20fc3111101ca079b375b125eb7e216b3202ec75196ce38",
          "sha256": "382912137fffb0852543701958ea80961daf2f55c09da55aea461cddc6a3aeb9",
          "sha1": "64ede393bcea0de14706e4e1e676a61ed484d58f",
          "md5": "6cda0b6a0ef7c8e0b36c669c717d643c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.4-sources.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.4-sources.jar",
          "size": 17415976,
          "sha512": "ab6c3aae6d1375460bff25f3aac83fda77ed5bf0dd30e8f937b50724adc63e544c11b8a0b6b518ff92f9e3ff6ad02d4dc8a66b9ad0a1ef65ad80c390fe8fbc24",
          "sha256": "9f745c366efc9d8a620f40de0f65f0d2651ccf115f898b8016052aec8ac237b5",
          "sha1": "ff6d438f2164f2be6725f38563de16e997ae27c4",
          "md5": "835511370459080ceb08bd198412adfe"
        }
      ]
    }
  ]
}
