{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2510.5.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2510.5.jar",
          "size": 545617,
          "sha512": "3d26906e683a4d9fb1985c4055f8b0761d9fd8e6523980aa2c107f1a8fc1194feda32fa951f2e28a5f9ec222ac44050357a114810d3dc5d0d24b5a9a3c137804",
          "sha256": "5680bafe3ada9ef96ea1290301c6b1e70330954776cb1e7122335fc49606bc3e",
          "sha1": "f7f7bc9421f7b103180a86e23304b230280123df",
          "md5": "9fdfc528658ca0fcc5a55d5f8f3b9247"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2510.5.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2510.5.jar",
          "size": 545617,
          "sha512": "3d26906e683a4d9fb1985c4055f8b0761d9fd8e6523980aa2c107f1a8fc1194feda32fa951f2e28a5f9ec222ac44050357a114810d3dc5d0d24b5a9a3c137804",
          "sha256": "5680bafe3ada9ef96ea1290301c6b1e70330954776cb1e7122335fc49606bc3e",
          "sha1": "f7f7bc9421f7b103180a86e23304b230280123df",
          "md5": "9fdfc528658ca0fcc5a55d5f8f3b9247"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.3.2510.5-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.3.2510.5-sources.jar",
          "size": 249026,
          "sha512": "fba64438b30e4dc717cc74e53a14426b89fa0b19ce3ae0cec811ce77186f9d0b4b509fad92be7990639157ec27927aa18e5772afca5e5b0d917cb9cf37cc9c78",
          "sha256": "0b0b6a26fb6c0c0c35be4f004b12b932e69591ea575178ad5ed1d38c04b73e3d",
          "sha1": "18430cab300fbace90fc931274764a3d3e252e24",
          "md5": "3084b1e592cbaf7ac9f6734dfb51db07"
        }
      ]
    }
  ]
}
