{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.20.4-1.8.0.2512.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.8.0.2512.3.jar",
          "url": "legacy-neoforge-1.20.4-1.8.0.2512.3.jar",
          "size": 18270925,
          "sha512": "4118c02ff579e0ae74646a06760ffdbca0f9bc9de8f4fcf8b0a204a5a80f292b8dae3fe8f42c347b4fbe98377bfaf4ca5d19db936a6edc7655112a9deeb382ff",
          "sha256": "794b971e890067ef1566e983391b119974af3d9264d7c869caee0f4e12f1cfe2",
          "sha1": "8ce0ec1a559c3718e1eff0a33461f85dd2244082",
          "md5": "d1b2ce456117eaaac9576f56a04e459c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.8.0.2512.3.jar",
          "url": "legacy-neoforge-1.20.4-1.8.0.2512.3.jar",
          "size": 18270925,
          "sha512": "4118c02ff579e0ae74646a06760ffdbca0f9bc9de8f4fcf8b0a204a5a80f292b8dae3fe8f42c347b4fbe98377bfaf4ca5d19db936a6edc7655112a9deeb382ff",
          "sha256": "794b971e890067ef1566e983391b119974af3d9264d7c869caee0f4e12f1cfe2",
          "sha1": "8ce0ec1a559c3718e1eff0a33461f85dd2244082",
          "md5": "d1b2ce456117eaaac9576f56a04e459c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.20.4-1.8.0.2512.3-sources.jar",
          "url": "legacy-neoforge-1.20.4-1.8.0.2512.3-sources.jar",
          "size": 17425301,
          "sha512": "d3fbf527059925098e8500369e874e02aea1c1074dfb038ec4b2b08f0d0fc8447c90b8aaa3ca02343394567c1b0009542bb58a33e79ac6349af14e12a54ac011",
          "sha256": "b6bf2854cd0f69207547f275ba46c7f991a95bc30165473aaba982dadf4a212e",
          "sha1": "89318bcb5ab2087f3815e84e6574673566859617",
          "md5": "4e7414eec9f37153a7c4c32f94694b5c"
        }
      ]
    }
  ]
}
