{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.6.2541.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.3.jar",
          "size": 516972,
          "sha512": "4910a3c1af4b16eead783f5f724747f3c3681888c42d07f36f723f6dfc18f13c65ee5f5882ca730d1043b4ca45cd4de3e227664fb250b24e0fb6b3e04e79198c",
          "sha256": "745ebc46b28e812911a9a6ddb66ee624355d61f1c8efc6686a2a806663f89a2b",
          "sha1": "5d57455808bc6eebaa55f6d11f04160c3102487c",
          "md5": "7abff860cba8707cfabed36670ac7f6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.3.jar",
          "size": 516972,
          "sha512": "4910a3c1af4b16eead783f5f724747f3c3681888c42d07f36f723f6dfc18f13c65ee5f5882ca730d1043b4ca45cd4de3e227664fb250b24e0fb6b3e04e79198c",
          "sha256": "745ebc46b28e812911a9a6ddb66ee624355d61f1c8efc6686a2a806663f89a2b",
          "sha1": "5d57455808bc6eebaa55f6d11f04160c3102487c",
          "md5": "7abff860cba8707cfabed36670ac7f6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2541.3-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2541.3-sources.jar",
          "size": 267727,
          "sha512": "b9056a4e8208f6cad77a7fd38b980c7a5702eae19ab8234a210f21ce6b1171938e70fcde6bef6d1b297e8a99f0d4c0f177e9a349b9ae80a8aae75f6aea765453",
          "sha256": "2f8b08442f84517f28799907f822816368a1d8fdb3eebfb490fffeebae0d4359",
          "sha1": "61e9d606a71d4c82aa495b6181dc100332345c28",
          "md5": "9c43a3eb6cfa127d6beca775d9e50da9"
        }
      ]
    }
  ]
}
