{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.1.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.1.jar",
          "size": 18268981,
          "sha512": "04d33874d05b1c391386d4f0861303ce3b9729ffcb32dd5aabb3e6a95ae4064c975a7b81643ef476b227695f7eacc2b4e1cf754cefa9691432fdc711ccbeddfa",
          "sha256": "5b4a519c5564af8b8c2111d3c921da6aa7059315dd0260fdcb852c9d95cb1ccc",
          "sha1": "e3a083539d1fa270a8ad77cd53ffa1156d52977b",
          "md5": "5404f61cef355b399d9129fab9bcbdad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.1.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.1.jar",
          "size": 18268981,
          "sha512": "04d33874d05b1c391386d4f0861303ce3b9729ffcb32dd5aabb3e6a95ae4064c975a7b81643ef476b227695f7eacc2b4e1cf754cefa9691432fdc711ccbeddfa",
          "sha256": "5b4a519c5564af8b8c2111d3c921da6aa7059315dd0260fdcb852c9d95cb1ccc",
          "sha1": "e3a083539d1fa270a8ad77cd53ffa1156d52977b",
          "md5": "5404f61cef355b399d9129fab9bcbdad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2516.1-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2516.1-sources.jar",
          "size": 17433370,
          "sha512": "e1a71dd32551ad716876cba781abd04efffd9f909b3fd1bf475dfd51cae71d3300de210b5f97484ad9d699347765ba4450d319f3fe8e91860f75ccba3282e76d",
          "sha256": "c9f29c419a9c1aab8ebd311c770939ca9067155cd7bf3edc4ee3ae39ac6ec192",
          "sha1": "a0008549f61e675d4093efed4287d54018b9a90a",
          "md5": "71745d1513a36d7780b0e668e4658264"
        }
      ]
    }
  ]
}
