{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2502.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.13.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.13.jar",
          "size": 445440,
          "sha512": "b476b0ad43e982678275b40eefb8a5682b268550b7a999e4eba41009d9d3ab24b3a90fa3c429c44edfb13852172b4b7501b8bcfeaa8b1f6f5ef7b477e5e51488",
          "sha256": "05a3fe6c44e3be19e0ed9c5cd7c5cd63045d7710cf60dc1046b8cde4a0ed13b9",
          "sha1": "c0e8a0f619d72b5028593fb071d2e0aaaf4de9a1",
          "md5": "a2293954ac8b8fc46fc696da307e3b17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.13.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.13.jar",
          "size": 445440,
          "sha512": "b476b0ad43e982678275b40eefb8a5682b268550b7a999e4eba41009d9d3ab24b3a90fa3c429c44edfb13852172b4b7501b8bcfeaa8b1f6f5ef7b477e5e51488",
          "sha256": "05a3fe6c44e3be19e0ed9c5cd7c5cd63045d7710cf60dc1046b8cde4a0ed13b9",
          "sha1": "c0e8a0f619d72b5028593fb071d2e0aaaf4de9a1",
          "md5": "a2293954ac8b8fc46fc696da307e3b17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2502.13-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2502.13-sources.jar",
          "size": 228798,
          "sha512": "6de3b9e0d3ef4a3e6a7432a188a676b880587fba313d65ed6103ac0592fcb4205fa19650e6b17af81b08b96595438e1f434ce629cb45ddfe176953dd16b6ace1",
          "sha256": "bde29b68e7cd04c2f34ffd7a6ede6229d0bcbb91aad351b6df81f1e64b0a3e77",
          "sha1": "d711ae763d6226cc615b5dcfac76bba19efd2f2a",
          "md5": "796e484481d48e36f68d2cc073dd3309"
        }
      ]
    }
  ]
}
