{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2507.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.8.jar",
          "size": 482382,
          "sha512": "49c62cf1b4068bae9f2d928e5f1d52f020b3732f6dba4c3dc2e7454ab052a4ad126b70955a80c70d14320b86747a97f4869b44228d136b895a5cfdb5a13e81fb",
          "sha256": "de1032f27020d57a79fd2768f69067bf6c36d921efbe45311a5549f8c3ebb07a",
          "sha1": "141e99029c8bf27ec7dc49ae22b98b00813091db",
          "md5": "5c96cd90a70fe8c752f62f9be002a138"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.8.jar",
          "size": 482382,
          "sha512": "49c62cf1b4068bae9f2d928e5f1d52f020b3732f6dba4c3dc2e7454ab052a4ad126b70955a80c70d14320b86747a97f4869b44228d136b895a5cfdb5a13e81fb",
          "sha256": "de1032f27020d57a79fd2768f69067bf6c36d921efbe45311a5549f8c3ebb07a",
          "sha1": "141e99029c8bf27ec7dc49ae22b98b00813091db",
          "md5": "5c96cd90a70fe8c752f62f9be002a138"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2507.8-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2507.8-sources.jar",
          "size": 244313,
          "sha512": "f11371c24c6b6ce4a00d823288cd25b8c54897de4b169d0750f50333c5317c901903ad1e3e26c88fb137d69e67100e108f2b8b14c8be8e6e4c263579102e6d52",
          "sha256": "8f7fcb15da035ebc680b6b6333a9ab8806af7d05e55e2986f0bf8bd99a12da17",
          "sha1": "186b8a39eafa75f0697d549618b39100a226a794",
          "md5": "6e7a8aa9fe54d8fe58ce8e1ed06400ab"
        }
      ]
    }
  ]
}
