{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.8.0.2518.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.5.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.5.jar",
          "size": 19704220,
          "sha512": "da0ea47f781f399b0ca46a56638a6aa0855890519bc1ca34f3b0f9300c21443bea5c912ee7773354acd011a0bf84e8c29f3843f4395689e139802f7dabaa3b35",
          "sha256": "a43bdcd1bf5c63e2d6e591585069c2f3370d84f5569487b266ec3575148b3990",
          "sha1": "b2936d8dd8d3ac695d2785fd2aa0b7ed482163ed",
          "md5": "7b14c9c1f95b4ae3f561a846a8ab5782"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.5.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.5.jar",
          "size": 19704220,
          "sha512": "da0ea47f781f399b0ca46a56638a6aa0855890519bc1ca34f3b0f9300c21443bea5c912ee7773354acd011a0bf84e8c29f3843f4395689e139802f7dabaa3b35",
          "sha256": "a43bdcd1bf5c63e2d6e591585069c2f3370d84f5569487b266ec3575148b3990",
          "sha1": "b2936d8dd8d3ac695d2785fd2aa0b7ed482163ed",
          "md5": "7b14c9c1f95b4ae3f561a846a8ab5782"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2518.5-sources.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2518.5-sources.jar",
          "size": 18843539,
          "sha512": "d3c87adb3c031adcb8c0e13a050b0ebfcc46c73265499570862c827f1a72ca4d9eae2de3068bf6d929bdcbd4a8febcd08309f1190f18202fb7a952af1b964bf4",
          "sha256": "4745e408735c28e3cca783d8075945fedf3aad93d0bfeb2e24c82870d33e383b",
          "sha1": "d6d1b250ab4e25eb326e9c1fd2b23fd95d5354ec",
          "md5": "f7762c8213fd07d69cb2dcfd1df39854"
        }
      ]
    }
  ]
}
