{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.7.10.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.6.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.6.jar",
          "size": 14336214,
          "sha512": "2ca8a3fa665aa8a289577ec3f5c8a0282bdafbc4f41a4c722c82c73e9e59c2e3e5016bebeffae158753f2cf53554d25c7c87095b4328d8d85271c860ed5ff526",
          "sha256": "26ade3301e4f655b2573a7fe7520a474e8c3060dad5786e418afd6e51450f1b7",
          "sha1": "b36f584bb1e10de5c4b8c9b10106b54dd4ff3751",
          "md5": "89f62884e3eafb492f50838c01b6203a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.6.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.6.jar",
          "size": 14336214,
          "sha512": "2ca8a3fa665aa8a289577ec3f5c8a0282bdafbc4f41a4c722c82c73e9e59c2e3e5016bebeffae158753f2cf53554d25c7c87095b4328d8d85271c860ed5ff526",
          "sha256": "26ade3301e4f655b2573a7fe7520a474e8c3060dad5786e418afd6e51450f1b7",
          "sha1": "b36f584bb1e10de5c4b8c9b10106b54dd4ff3751",
          "md5": "89f62884e3eafb492f50838c01b6203a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.6-sources.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.6-sources.jar",
          "size": 13520721,
          "sha512": "5b603fc08dc5bc7f34438a1eca97c9de74876d22dd9e7abc60a05a8c1be582fc3731246ec9b79d6f8db310f24c37e2019b122a69cbe79070a6c730d92008c48e",
          "sha256": "52adfabbccf8b06a5204e3fabf98906bdffce206de6c51ddf379d8ac892071bc",
          "sha1": "de799ea7027123dde39c670329cfb4fe492fc146",
          "md5": "73c607ad4f019db85c921e1d08668354"
        }
      ]
    }
  ]
}
