{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.6.2544.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2544.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2544.0.jar",
          "size": 541064,
          "sha512": "d5e0fae60853c6c26c76d5873a2ff1923e771eeae2e2397cf472ca3d561aa828f2d7c410fa803d5b8e7888179802358499f42a6465d7330828da3f51c3f10052",
          "sha256": "c4e968d1bf350d0747fbb73384cfcb951a380e9af3756f5b267a58835668934a",
          "sha1": "29610bc014c433970c4ddb9dfb1a643e600e2579",
          "md5": "bbae682d5022bd479871597f1b61c5b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2544.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2544.0.jar",
          "size": 541064,
          "sha512": "d5e0fae60853c6c26c76d5873a2ff1923e771eeae2e2397cf472ca3d561aa828f2d7c410fa803d5b8e7888179802358499f42a6465d7330828da3f51c3f10052",
          "sha256": "c4e968d1bf350d0747fbb73384cfcb951a380e9af3756f5b267a58835668934a",
          "sha1": "29610bc014c433970c4ddb9dfb1a643e600e2579",
          "md5": "bbae682d5022bd479871597f1b61c5b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.6.2544.0-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.6.2544.0-sources.jar",
          "size": 268331,
          "sha512": "b7e820890f2033dbf80055e2d664e6e295295368ec0831c701f34164ff583bb40a6b4f19877ad2a7fe4047041d3204e639ef22014da31b475dbad06e50693f94",
          "sha256": "9da1696c3cfe217877dc3a9d929b99773f3376d87ac0eb97b70dfb704cbd06eb",
          "sha1": "40f1a7ec89766b89a10323b0bb4773e7d671a245",
          "md5": "40edc94b83cd3b915396b1b6e6b5001b"
        }
      ]
    }
  ]
}
