{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2502.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.11.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.11.jar",
          "size": 467053,
          "sha512": "193ee57ca809a36960af771e89f3931834a25a56f5011d73fe69252e089115b86c058648d0556b3715b0d8b6793fdfaedf41188511edeb0d20772a73f293ae27",
          "sha256": "ef2a27fa8f9e73689d2a29123c33f91a1532f58b8f33f32b1fac77be7e687de6",
          "sha1": "e8f31e04a2ad816d8d3ecca45e96deb45402ca04",
          "md5": "004c9f1a8e086f275f0006be204aaceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.11.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.11.jar",
          "size": 467053,
          "sha512": "193ee57ca809a36960af771e89f3931834a25a56f5011d73fe69252e089115b86c058648d0556b3715b0d8b6793fdfaedf41188511edeb0d20772a73f293ae27",
          "sha256": "ef2a27fa8f9e73689d2a29123c33f91a1532f58b8f33f32b1fac77be7e687de6",
          "sha1": "e8f31e04a2ad816d8d3ecca45e96deb45402ca04",
          "md5": "004c9f1a8e086f275f0006be204aaceb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.11-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.11-sources.jar",
          "size": 229427,
          "sha512": "08ad63f218c0bb02cb9592f0a2e4c47c1692ca682fbef35df7940a914ae377440fe406900627945692d39ca27c457fde85fd632acb11bc268bc4c090fe89f6e1",
          "sha256": "4877a749907162f27b9956c9e3ffbaf4239b70f5bbf5fa80cb07fa4eddf01b5b",
          "sha1": "16802b3c597e4b3bb6c763dedcca92c604d84365",
          "md5": "9f41608275e34d5b44c00adb268276c1"
        }
      ]
    }
  ]
}
