{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2513.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.9.jar",
          "size": 506318,
          "sha512": "3b1a89fdfd35d830ee74ac111ec6831f147c30f5ca8afd5faa7493dcb18354f170d914cb977cbc74207a970bd9ff7a5f803c9f4d5cdc851cef943a1b75f2635a",
          "sha256": "99693be875744eed177cdaead3c636d535c0bb123454c7a801c226706bc958a8",
          "sha1": "79f18ea8d2a0bbd239003fe6cda2b79129c1fcca",
          "md5": "293c6af212a6e53970a6b0706470082b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.9.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.9.jar",
          "size": 506318,
          "sha512": "3b1a89fdfd35d830ee74ac111ec6831f147c30f5ca8afd5faa7493dcb18354f170d914cb977cbc74207a970bd9ff7a5f803c9f4d5cdc851cef943a1b75f2635a",
          "sha256": "99693be875744eed177cdaead3c636d535c0bb123454c7a801c226706bc958a8",
          "sha1": "79f18ea8d2a0bbd239003fe6cda2b79129c1fcca",
          "md5": "293c6af212a6e53970a6b0706470082b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2513.9-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2513.9-sources.jar",
          "size": 251516,
          "sha512": "28d3e9c5e51cc039807c91e17e770e7d447b7bc47adbb38c1debfa9d114e726cbd584124271861705ea00ebb64e03357cc0e44ee1d981fed1247b6e607827352",
          "sha256": "6123a225b17713c1cc684584969425cc49a14ab2a65191a984ea340f08eb08e6",
          "sha1": "989085fdf42693d37bf6056f0fbecf2c0eb23487",
          "md5": "82032bab9bc58bd1086e1eb4f25c45f5"
        }
      ]
    }
  ]
}
