{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.7.10.2509.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2509.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2509.1.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2509.1.jar",
          "size": 14377853,
          "sha512": "aedf76dafebd018c6b0059d83eaf861c875e4aebfa384793dc04a03417a46902f0bf0239761dca61ca16843e181be90b1353d335061a7cc913ba382f4c7dc0f3",
          "sha256": "3f4dd5c2d063efdc8e47f43845090c831d737b1f9c9bd1fd1aa07810121cc348",
          "sha1": "063d2d2b10198c7e24ce72e474b9330ae116f12e",
          "md5": "1c940f1f3ad26b43c98dbe7860bbefa2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2509.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2509.1.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2509.1.jar",
          "size": 14377853,
          "sha512": "aedf76dafebd018c6b0059d83eaf861c875e4aebfa384793dc04a03417a46902f0bf0239761dca61ca16843e181be90b1353d335061a7cc913ba382f4c7dc0f3",
          "sha256": "3f4dd5c2d063efdc8e47f43845090c831d737b1f9c9bd1fd1aa07810121cc348",
          "sha1": "063d2d2b10198c7e24ce72e474b9330ae116f12e",
          "md5": "1c940f1f3ad26b43c98dbe7860bbefa2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2509.1-sources.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2509.1-sources.jar",
          "size": 13572967,
          "sha512": "58ae0d7e7db02e819afd4a932903747c00c281ce05b45380bf5205e158fd0ed6ecc39697825bddd547c32c75e02c0128c1a4336d15d8e553d1d2bc23e6968f10",
          "sha256": "21c7775bd61bf2a70a5a304ff7def2c297c5b6993b63c0a46f66ccadfd5c9663",
          "sha1": "8388c76f7a310845c52fc0a9c9c2ed24b0560998",
          "md5": "6bc5fecd0221378038f0f9ece902e520"
        }
      ]
    }
  ]
}
