{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.3.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.3.jar",
          "size": 494792,
          "sha512": "e9b35daf5547e6db7cbda4505b25f8726fbc078141d7fe8df32acc1c0a0d89b692dbb06a7804553c0c8951955b5382ee500a4b3a7483fd2c8a4c510e5d62f5ca",
          "sha256": "05eb275cd582d03e70cff60455a346ed6ed0f7a6996088610ca1dfbf1605b460",
          "sha1": "581307b289b2b35a1213971b778bff5fccad1616",
          "md5": "7020f1f38b709c03f919a8bd420d9a90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.3.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.3.jar",
          "size": 494792,
          "sha512": "e9b35daf5547e6db7cbda4505b25f8726fbc078141d7fe8df32acc1c0a0d89b692dbb06a7804553c0c8951955b5382ee500a4b3a7483fd2c8a4c510e5d62f5ca",
          "sha256": "05eb275cd582d03e70cff60455a346ed6ed0f7a6996088610ca1dfbf1605b460",
          "sha1": "581307b289b2b35a1213971b778bff5fccad1616",
          "md5": "7020f1f38b709c03f919a8bd420d9a90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2504.3-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2504.3-sources.jar",
          "size": 230283,
          "sha512": "d187ade769f1677d84e88ad0660ac4c1848b6507aafc52579ad6ccab398ce6fd08d670b57ce0ce435ea29911a639d393c7c833f5d173d1c2d0eff391a39da67e",
          "sha256": "7eb49a71e5b294a9deda628760dba2274d586e0b3efad6ff6dc512d34d3dea08",
          "sha1": "735b32a89bfaf28d03743da8f5697f3cfc851bfd",
          "md5": "b4237eafe30504ca4d40da36d41c7101"
        }
      ]
    }
  ]
}
