{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.7.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.7.jar",
          "size": 372701,
          "sha512": "2b7b5e4cbdd10b804696b0e12aed178ebea518feed83cf651709436b92507b8fbff7fb89e8be11da139fd0c923892f724aef40f92fd0247ee379b814fca93278",
          "sha256": "0f26d399e70bde47b8bde976bb74e12ab130625de0d9407ad4fca6aa6f5ac830",
          "sha1": "c96379ed5310b26abe35750bcea16b939a5ff96a",
          "md5": "b01296134cee79ddf82c699b1c00976a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.7.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.7.jar",
          "size": 372701,
          "sha512": "2b7b5e4cbdd10b804696b0e12aed178ebea518feed83cf651709436b92507b8fbff7fb89e8be11da139fd0c923892f724aef40f92fd0247ee379b814fca93278",
          "sha256": "0f26d399e70bde47b8bde976bb74e12ab130625de0d9407ad4fca6aa6f5ac830",
          "sha1": "c96379ed5310b26abe35750bcea16b939a5ff96a",
          "md5": "b01296134cee79ddf82c699b1c00976a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.7-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.7-sources.jar",
          "size": 196364,
          "sha512": "f8d81b404bc180a86bd15b3fb2cb309e96fe2e78e7d22264405b8f4909c8a50aa3a5f3e11d2a2075b255bc9625731e9c97cfa37373f590325eb465bd43b9dd16",
          "sha256": "58a0aaf1a2aef74ed4b1db44c66b25923539e4fc11bcad39e95ea842ff81c3ab",
          "sha1": "28bb759241141b28bfde8db4efe3044fe8d7686e",
          "md5": "59707f4b8f037ed6881d3dadf385df48"
        }
      ]
    }
  ]
}
