{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.3.jar",
          "size": 367859,
          "sha512": "28ab07a6a64d2175d65fe905b589a5c24e1cc06ea7967aa9d92a54883d81b6c98c94c10f321a5b4f9d8591405e68dea369f2fed579c9debfc63696198b0cba96",
          "sha256": "f04dbd05b30b0d7efa8844b5e325edd2381a54138311e4427f2de1fb6f13a76d",
          "sha1": "968dea5fece6a2cfe78eccd423408c0cabe720b3",
          "md5": "554e234a341a3d5f8c7c44a962e294b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.3.jar",
          "size": 367859,
          "sha512": "28ab07a6a64d2175d65fe905b589a5c24e1cc06ea7967aa9d92a54883d81b6c98c94c10f321a5b4f9d8591405e68dea369f2fed579c9debfc63696198b0cba96",
          "sha256": "f04dbd05b30b0d7efa8844b5e325edd2381a54138311e4427f2de1fb6f13a76d",
          "sha1": "968dea5fece6a2cfe78eccd423408c0cabe720b3",
          "md5": "554e234a341a3d5f8c7c44a962e294b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.3-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.3-sources.jar",
          "size": 194958,
          "sha512": "bfa4bed1fb1d85d42440466350da8489d01b9f7230d86a45a5065e12bb5e75d41a738cf72d70bc3b2ce91c8e8eb054d7532a0ddb8ed1f670f6b783993a8f30bf",
          "sha256": "7cb3a1bbcc071b9a40920131f76670d17602de113987bea3c77503393f4d9bd9",
          "sha1": "5c66ba81fbe1338c577abe46a3829d285a8ace8d",
          "md5": "daaff83dcc445152921b0422f70541fb"
        }
      ]
    }
  ]
}
