{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2502.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.1.jar",
          "size": 392113,
          "sha512": "b1ffc45569dd64f4c151e87f099fb5f43fc5039b5f7b7fa3d53b42aace96944cf81a4f9bf314554c5126d320a01dd2617a797a0698c56c3f2bad0d9fdcebc347",
          "sha256": "ed6b8afc911787fd7ab66a80cd960917a331706710ddd020b183d9e834d86575",
          "sha1": "8efe2e6328254404b3017eaf7d6df96e387057f7",
          "md5": "19f1d3037be29d520e1e11d71b20b93a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.1.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.1.jar",
          "size": 392113,
          "sha512": "b1ffc45569dd64f4c151e87f099fb5f43fc5039b5f7b7fa3d53b42aace96944cf81a4f9bf314554c5126d320a01dd2617a797a0698c56c3f2bad0d9fdcebc347",
          "sha256": "ed6b8afc911787fd7ab66a80cd960917a331706710ddd020b183d9e834d86575",
          "sha1": "8efe2e6328254404b3017eaf7d6df96e387057f7",
          "md5": "19f1d3037be29d520e1e11d71b20b93a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2502.1-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2502.1-sources.jar",
          "size": 197833,
          "sha512": "eaab7b93bd9cd67e01b6a6f1ab4b0dc842e96d4eb6e96b4a7c061b3e57c12c9fda098bfa14cd491fdbe31995354b6d6251123cbf034e3f8231ed7ccad586114e",
          "sha256": "3e2980c6d7abc6ba433edb14a0f46e53f5eac0e3774efeee0c8c576313edc6d6",
          "sha1": "d090e8ea77d7b9760beceb5844e2e164f5798911",
          "md5": "f64440a61da4b148b6e4aa8f66ba9f96"
        }
      ]
    }
  ]
}
