{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.7.10.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2506.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2506.0.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2506.0.jar",
          "size": 14352358,
          "sha512": "137c78a84df3a5c077b5977167ed095ef6587cf244e510dca6048e81f7482df32979f6b33a446e6345f679d25eb93c61a06e42bb26169cd361573251a42fe7bd",
          "sha256": "ac95e3d5fa0d57276d5bc492e382eb39d3f06721a6e2988f47058bcadb9aa395",
          "sha1": "5f464ea7e0230267122e88d3bbb7464e09e6e91f",
          "md5": "d6c78b08e8e2b52cad03db524230e2bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2506.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2506.0.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2506.0.jar",
          "size": 14352358,
          "sha512": "137c78a84df3a5c077b5977167ed095ef6587cf244e510dca6048e81f7482df32979f6b33a446e6345f679d25eb93c61a06e42bb26169cd361573251a42fe7bd",
          "sha256": "ac95e3d5fa0d57276d5bc492e382eb39d3f06721a6e2988f47058bcadb9aa395",
          "sha1": "5f464ea7e0230267122e88d3bbb7464e09e6e91f",
          "md5": "d6c78b08e8e2b52cad03db524230e2bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2506.0-sources.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2506.0-sources.jar",
          "size": 13533699,
          "sha512": "e9b07770d2906558437a9f8229b18b2cc0fd195b3c0da394428023ccb6b6bb2a07f45a885d3f0d1cef11951dcfd5a66eeaeaf0316d28479bc0646c2c03c006d6",
          "sha256": "c1bf712eeac3ebf146ed085c9668378f5b3c08cac8feb0c598e176b93280251f",
          "sha1": "699d968591c8ffb2c0dfab799c2a8110cddb59c0",
          "md5": "f1ca73defabc3cc8ffae2f337b4a3b54"
        }
      ]
    }
  ]
}
