{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric-1.21.4",
    "version": "2.2.2500.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2500.0.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2500.0.jar",
          "size": 389315,
          "sha512": "2350402656f601f7b373d889be346a3cbdb104847f05027f5290c7f4ad151d8613a27312235e7cb4d37372749c571e7d02d89a4427ca48efb995ced31b3c2219",
          "sha256": "ac28943fe9cc3ed38a268c83f8ac878dee8b5ee91f213fe8020f25fdb3fcaee8",
          "sha1": "a591a493383a568baeada22771113fb7df80da27",
          "md5": "b232063983da321cefd55a937d45a971"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2500.0.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2500.0.jar",
          "size": 389315,
          "sha512": "2350402656f601f7b373d889be346a3cbdb104847f05027f5290c7f4ad151d8613a27312235e7cb4d37372749c571e7d02d89a4427ca48efb995ced31b3c2219",
          "sha256": "ac28943fe9cc3ed38a268c83f8ac878dee8b5ee91f213fe8020f25fdb3fcaee8",
          "sha1": "a591a493383a568baeada22771113fb7df80da27",
          "md5": "b232063983da321cefd55a937d45a971"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.2500.0-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.2500.0-sources.jar",
          "size": 190029,
          "sha512": "e651969a566079b4d746fbace9ad760e245397e6bb14aa8320d67e0aac54268f3ffec4cedb8cb34e3e4724f57625ce04806ed75847a529a815cfa44da9000822",
          "sha256": "cd59aa70b1cdf64b8a95bd600aa6b4c1309654fb195cc8da56da2100b0c4fbc8",
          "sha1": "ac22cb17e1e41c434fa1e51d1006d5ba2b726486",
          "md5": "c6afcbd0eec52bd1d0efadd7259accd3"
        }
      ]
    }
  ]
}
