{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.21.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.21.jar",
          "size": 376880,
          "sha512": "c8d90ba605dda8e79310f3ce0c3cbdd9d3e66857588070e872b6d4547ae0c0c4a14563fe157ed5b0f54e81c70bec5779f1ab36a1f22ad366a0f9b4b0dab01d90",
          "sha256": "91e82d82c081a7b70a390078efc5c4266ffd3297efbc9832de5a789f0e374288",
          "sha1": "a432535c96fe49922c63486898375a9840314422",
          "md5": "1c21bc83085856cbe3fc8b6807a86e10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.21.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.21.jar",
          "size": 376880,
          "sha512": "c8d90ba605dda8e79310f3ce0c3cbdd9d3e66857588070e872b6d4547ae0c0c4a14563fe157ed5b0f54e81c70bec5779f1ab36a1f22ad366a0f9b4b0dab01d90",
          "sha256": "91e82d82c081a7b70a390078efc5c4266ffd3297efbc9832de5a789f0e374288",
          "sha1": "a432535c96fe49922c63486898375a9840314422",
          "md5": "1c21bc83085856cbe3fc8b6807a86e10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.21-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.21-sources.jar",
          "size": 201227,
          "sha512": "45d466b987c4db048c4eb752e80a8ef2c55e9ce90bd07a0282f3e046266f8c72e5984b4659e08fbfae61c2bc2b3207d559ffcd32bd41df74cf02a8fd31d7e1b4",
          "sha256": "7b11deca89e264fbb3a1deb95b3dc3238633af9e755514669d6fb51f4e310b99",
          "sha1": "78c77ad65ce7448d9f8b304583d7715e80ecd6d1",
          "md5": "c6e2bb135aabb88daea3371b49fd1f66"
        }
      ]
    }
  ]
}
