{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.5.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.5.jar",
          "size": 530691,
          "sha512": "0e5b19075980069f023d69f2a458a041cd11a55064661e2f2ecdeaf99e1783b160f619ee018b9c75f1d131def6bba534fc8df60fdc36c26d0d5bab899f0c7f65",
          "sha256": "fac4ae84d26760ab0c92e14f1e86c4f429f1820663ae28cd547f8ceeff970ce0",
          "sha1": "12d26f75d66b7a9e9230b26a6c7f241c1b91f788",
          "md5": "4a0cb1210ec705af5de8687afbee7b37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.5.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.5.jar",
          "size": 530691,
          "sha512": "0e5b19075980069f023d69f2a458a041cd11a55064661e2f2ecdeaf99e1783b160f619ee018b9c75f1d131def6bba534fc8df60fdc36c26d0d5bab899f0c7f65",
          "sha256": "fac4ae84d26760ab0c92e14f1e86c4f429f1820663ae28cd547f8ceeff970ce0",
          "sha1": "12d26f75d66b7a9e9230b26a6c7f241c1b91f788",
          "md5": "4a0cb1210ec705af5de8687afbee7b37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.5-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.5-sources.jar",
          "size": 254299,
          "sha512": "88eb09363317422b8fcba601052a65c0881b537878f0bc8ea9e7ea881b8aa49845d7d9ac3140ece26c082855771dd9d21459b6b2ab6ad3a9d890efeaae68c503",
          "sha256": "65e89950a70481472100581cbf4f3c61d43162523d136ee9f9124a7c6b213a10",
          "sha1": "1fe4a713dbfb2a45580afe126f3c10525bb37632",
          "md5": "103fdb169975857358b5d8a1a39abe39"
        }
      ]
    }
  ]
}
