{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2502.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.7.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.7.jar",
          "size": 455246,
          "sha512": "d80cb2a667e0bc54fa8a1fa31a73f38c0d6b22f9d317eb07dbd9d5db832e43875818b591cca3e4798307188d85475216fafc6096560f09415db2c40b8e2bc07a",
          "sha256": "c78a2c49c7a22f1041dbf02253d6d7917a36920da23fac900ed1ea7dedb25556",
          "sha1": "20378bc812bd463e5a40a8e10209efcc905297ab",
          "md5": "da7d5ec623dda8afdd9b460d847ffeb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.7.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.7.jar",
          "size": 455246,
          "sha512": "d80cb2a667e0bc54fa8a1fa31a73f38c0d6b22f9d317eb07dbd9d5db832e43875818b591cca3e4798307188d85475216fafc6096560f09415db2c40b8e2bc07a",
          "sha256": "c78a2c49c7a22f1041dbf02253d6d7917a36920da23fac900ed1ea7dedb25556",
          "sha1": "20378bc812bd463e5a40a8e10209efcc905297ab",
          "md5": "da7d5ec623dda8afdd9b460d847ffeb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2502.7-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2502.7-sources.jar",
          "size": 224077,
          "sha512": "13972f2ea7e43b3dcfc9900d9086e0c7aa457cacc1063c6c3c088188e5e52fab8bfb669cb15acdd8cf3a6681484e975c8dde99575f0651816269150fb9645e9c",
          "sha256": "b2b3874149c073283d32215d9786dfdf5029b3abf01e8b8016db159258b08fa3",
          "sha1": "dcbd25ecedabf533f0ed48f7384a7ba95de896db",
          "md5": "23597af3cad8fd49d5da2a7498b8d15e"
        }
      ]
    }
  ]
}
