{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2500.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.3.jar",
          "size": 358961,
          "sha512": "aacf6bee523552550fd0f2ade2f9b67475772235065d3fb6cf8d881e4225d7fed991cf9f5eeb1fd98969c2bbf90cb1bf3f1747095909361df2ee7d0b70a983c6",
          "sha256": "038cb423a3c254f237ad95e27e43c21c59afaa15e4d6abc46833d46228161bcf",
          "sha1": "2c62382b6ed2624680f150c92f86ad0343cfdb46",
          "md5": "355828b8d67e4e556b8d7629ec0375c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.3.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.3.jar",
          "size": 358961,
          "sha512": "aacf6bee523552550fd0f2ade2f9b67475772235065d3fb6cf8d881e4225d7fed991cf9f5eeb1fd98969c2bbf90cb1bf3f1747095909361df2ee7d0b70a983c6",
          "sha256": "038cb423a3c254f237ad95e27e43c21c59afaa15e4d6abc46833d46228161bcf",
          "sha1": "2c62382b6ed2624680f150c92f86ad0343cfdb46",
          "md5": "355828b8d67e4e556b8d7629ec0375c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2500.3-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2500.3-sources.jar",
          "size": 192044,
          "sha512": "041257ef135b0472c8e4ee40b4e631908416ec57634ea8b7859fb7a4058cd24f7a6fc115f135a5859babcc168594f964020b734480caa2bbc09b38e65a599b46",
          "sha256": "f458b7da8f1c49901985492ace4691d1f5611b3a5c12079b055b723aa020be4d",
          "sha1": "d2401c262a76ac6e1d4d2d4b90efce6e0c961484",
          "md5": "d603f596350ecef05309c06d0339476e"
        }
      ]
    }
  ]
}
