{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.4-1.8.0.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3.2514.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2514.1.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2514.1.jar",
          "size": 18254007,
          "sha512": "534cfea4cb63699c4c7cd2bf506a8231f4da6a8ab3219f004a0215fce47867aab3e3dcacf2da829797e96133750c37193192be81f601bda29cc541a667f0b8ea",
          "sha256": "9216658d866d594ca6762a9da36abd90a024a18597890c5e4442bb4892f9e395",
          "sha1": "a22af4cc5761d979b2a81368cbd7d4cad70676bf",
          "md5": "8ab9657aca159e6e27833ed470915120"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3.2514.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2514.1.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2514.1.jar",
          "size": 18254007,
          "sha512": "534cfea4cb63699c4c7cd2bf506a8231f4da6a8ab3219f004a0215fce47867aab3e3dcacf2da829797e96133750c37193192be81f601bda29cc541a667f0b8ea",
          "sha256": "9216658d866d594ca6762a9da36abd90a024a18597890c5e4442bb4892f9e395",
          "sha1": "a22af4cc5761d979b2a81368cbd7d4cad70676bf",
          "md5": "8ab9657aca159e6e27833ed470915120"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.4-1.8.0.2514.1-sources.jar",
          "url": "legacy-fabric-1.21.4-1.8.0.2514.1-sources.jar",
          "size": 17422743,
          "sha512": "340d5de7f0f0d24a9003d787c76939d87f5e4795a90e7b54d820f1b460e15916ee73fbe8f8e3bce45a61e1c1844df46ec831a1517f691557e394457ab94f9530",
          "sha256": "3cb97ffa6aaa40ca9ab88aa417bc02ec1292e11039efccbb482df1bf08d04f7f",
          "sha1": "93d7ab8d9707e9f9b44d802130c3b1801d08b11c",
          "md5": "38149b58c5ae5487570113e6e7b119f6"
        }
      ]
    }
  ]
}
