{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.7.10.2502.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2502.12"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2502.2.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2502.2.jar",
          "size": 14195119,
          "sha512": "d4d373dd4ac3ce1872370ead40cd4e891228bc32a02aa60d5af1f32a654208dbe48a8efc4e2f1e94734f32e5c9c661c8497e3745b4c0c2fa924578ab91bbf5bd",
          "sha256": "3bbedf2efe7e34680792643fd13c2e7518293fa6b79ff1b331571743e3e60bde",
          "sha1": "4aaa76a59f6240271ba32939042eae217f149eae",
          "md5": "a26e3eabc8197ec8bb24ce6b4bc27776"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.2502.12"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2502.2.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2502.2.jar",
          "size": 14195119,
          "sha512": "d4d373dd4ac3ce1872370ead40cd4e891228bc32a02aa60d5af1f32a654208dbe48a8efc4e2f1e94734f32e5c9c661c8497e3745b4c0c2fa924578ab91bbf5bd",
          "sha256": "3bbedf2efe7e34680792643fd13c2e7518293fa6b79ff1b331571743e3e60bde",
          "sha1": "4aaa76a59f6240271ba32939042eae217f149eae",
          "md5": "a26e3eabc8197ec8bb24ce6b4bc27776"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.7.10.2502.2-sources.jar",
          "url": "legacy-forge-1.20.1-1.7.10.2502.2-sources.jar",
          "size": 13419878,
          "sha512": "0badaf72fb68f0e3a000888ceffdf4aa48b1bbf83668fb09fb53edb1e14e431181472c4257858d6def210c9fcd1cf6849b48e3c6bac1a707d122c1ce9251ed5b",
          "sha256": "3007ad44e347eca9dec59255084434451da1d95bd6159acdb502430018849946",
          "sha1": "29366f0133576f9c43ca9ab2baa8a1140fdb69ae",
          "md5": "d7aaba2df05d831c7914299474e585c1"
        }
      ]
    }
  ]
}
