{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.8.0.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2516.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-forge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2517.0.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2517.0.jar",
          "size": 18288014,
          "sha512": "8e407afb2727fabc88cca7e2bfa6dca4447387bb35dffd62280602ff5433b8402a997d81094d2fe3d9c63f13c927a493700051c659184f776a7ba5d0ec89c68f",
          "sha256": "101df2bed1e23ba8ec35fd510d89a64cad9c625350f9534dda4ad9c6437d28bf",
          "sha1": "835598b110cc849efdbdb25dc9a5caab57659915",
          "md5": "f4f8e25370f08990642ef69ac807e803"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2517.0.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2517.0.jar",
          "size": 18288014,
          "sha512": "8e407afb2727fabc88cca7e2bfa6dca4447387bb35dffd62280602ff5433b8402a997d81094d2fe3d9c63f13c927a493700051c659184f776a7ba5d0ec89c68f",
          "sha256": "101df2bed1e23ba8ec35fd510d89a64cad9c625350f9534dda4ad9c6437d28bf",
          "sha1": "835598b110cc849efdbdb25dc9a5caab57659915",
          "md5": "f4f8e25370f08990642ef69ac807e803"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.8.0.2517.0-sources.jar",
          "url": "legacy-forge-1.20.4-1.8.0.2517.0-sources.jar",
          "size": 17428403,
          "sha512": "d41f84fd4b55779421d94afe45079c0439d05ea702e8bcf06666af072de7befb3ef37457361eb810cad604b169e5d6bea309a343792c596bdcdf2ab113c1afe5",
          "sha256": "a067c69de06fcf69f36af958994c9b439a3f3000ae6a4b70b2ad3d3ef791bfcd",
          "sha1": "0a613938033664105c61a790ff0ac779e92c2aa4",
          "md5": "63a5c2d042d678f4b68635d276f89dc8"
        }
      ]
    }
  ]
}
