{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2500.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.4.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.4.jar",
          "size": 348061,
          "sha512": "1bae6b56d09f05e12c70cd2dc359ca187113fd2b2f76822104144d91ca1284f38b902683944c722b4e66d7aae07d859b2aa068e4cce4a480796113ff9ae37e0c",
          "sha256": "3191ffc48992ead809a020fc360954046296706081d310a50a2de6cae6b07bbf",
          "sha1": "53226a1bcb693bc5ea70710a11fe7b4c642d6638",
          "md5": "9eea05e258512d7a31f6968fad40ba5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.4.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.4.jar",
          "size": 348061,
          "sha512": "1bae6b56d09f05e12c70cd2dc359ca187113fd2b2f76822104144d91ca1284f38b902683944c722b4e66d7aae07d859b2aa068e4cce4a480796113ff9ae37e0c",
          "sha256": "3191ffc48992ead809a020fc360954046296706081d310a50a2de6cae6b07bbf",
          "sha1": "53226a1bcb693bc5ea70710a11fe7b4c642d6638",
          "md5": "9eea05e258512d7a31f6968fad40ba5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.4-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.4-sources.jar",
          "size": 193137,
          "sha512": "3e06daff80b3bceb9ef1b786c3ac478d09b9a9c565925f08e6d71218e7198b5131b46ef146d9f0a62f12229f7ce43cd4478b5c5e3c001f4a8238961625b0bd86",
          "sha256": "e73b5126fbc2c395104eb9174f46dee6da512ed88719da1dc9096580c68735f1",
          "sha1": "fff2df40dfbab748f898efb13ef227ef9c2ea614",
          "md5": "a8cd914cafe7b9486348c6199c71af21"
        }
      ]
    }
  ]
}
