{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.3.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.3.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.3.jar",
          "size": 529605,
          "sha512": "bb90b209218f3c8b5717313b9b997d2561f2e889ccb84fc8f8af1a66c7f94edb273d1762fdc5ecebe962413eab62c8cb5025d2af1dbd9d63b4ec442b8215dcdf",
          "sha256": "4305481d305e34b1b656aadec451774ba0356bfac3b8195e672acb2ec7ab6f28",
          "sha1": "09d4e0433c378e23d9a74420a49b4d2b9362575e",
          "md5": "42c1e40331f2dcba99715700733dd908"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.3.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.3.jar",
          "size": 529605,
          "sha512": "bb90b209218f3c8b5717313b9b997d2561f2e889ccb84fc8f8af1a66c7f94edb273d1762fdc5ecebe962413eab62c8cb5025d2af1dbd9d63b4ec442b8215dcdf",
          "sha256": "4305481d305e34b1b656aadec451774ba0356bfac3b8195e672acb2ec7ab6f28",
          "sha1": "09d4e0433c378e23d9a74420a49b4d2b9362575e",
          "md5": "42c1e40331f2dcba99715700733dd908"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2516.3-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2516.3-sources.jar",
          "size": 254155,
          "sha512": "98b3db426f6eeac43df2a1944487164e121d89b9e5401820b7c6c30906347d5e1643ed247e39a4b634f7c121c0f6b4acf729378562023e5e044c6fd34c01581a",
          "sha256": "b5e0fe9b09bf070805980e71a20207ed0b8333775301773136955d145838b1db",
          "sha1": "0f3d0d47a244c7ef734f88262eaed08c1ef495ca",
          "md5": "fcf7343a5f8744ed883b313853ef1b59"
        }
      ]
    }
  ]
}
