{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.5-1.1.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2517.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2517.0.jar",
          "size": 643163,
          "sha512": "7044972eae62635a5c62a28f15a5f43b67b72282c92ce2bd92fe12a11c90955128950368a000e291cbf1c67008e7b963fc3839843095be98225b9c5e9b8c1442",
          "sha256": "b9822ab4ead0f0ac9b4df30f9ec1433e043e0adacf6176b3ad65cab9943fe906",
          "sha1": "e96f24a91fe6f5d65800a52bbb03ee87fd2319af",
          "md5": "e9abcf2817210bc6d0510a291ed784f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2516.6"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2517.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2517.0.jar",
          "size": 643163,
          "sha512": "7044972eae62635a5c62a28f15a5f43b67b72282c92ce2bd92fe12a11c90955128950368a000e291cbf1c67008e7b963fc3839843095be98225b9c5e9b8c1442",
          "sha256": "b9822ab4ead0f0ac9b4df30f9ec1433e043e0adacf6176b3ad65cab9943fe906",
          "sha1": "e96f24a91fe6f5d65800a52bbb03ee87fd2319af",
          "md5": "e9abcf2817210bc6d0510a291ed784f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.5-1.1.2517.0-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.5-1.1.2517.0-sources.jar",
          "size": 585380,
          "sha512": "2d4dc44bef26a92ea1b9b8bb4738131c020cd0de9d5959dc568bcc65275e18357504ffe32ac86e4f3e1c8ea91f33af19eb5bd84c2f70a55d4097affc9abb6c37",
          "sha256": "24b9f9287882e9d1652f92739043610a9de2dbd820a66aacb852be26307a1aa0",
          "sha1": "af544c56a86f42f138ceeb67ae2e266113cec9c4",
          "md5": "809464ac039ffc4183531791822fd0f2"
        }
      ]
    }
  ]
}
