{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.2.jar",
          "size": 370479,
          "sha512": "b17d76275ba312f248d17474471e8392153d844e6d01bfb36a5d33acc95fd75fb932c4523482a3db573dd725659fe677170707581172a7808f76751e6fb8c17f",
          "sha256": "674148e15f2e77d103891f68d2559efac0eb10f937ecfd08c5c4d96033358db9",
          "sha1": "269d62c0b6ed5e13a3b30e7592c604587910e19c",
          "md5": "36f607c5e57d8bca5b83e3f4f63224ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.2.jar",
          "size": 370479,
          "sha512": "b17d76275ba312f248d17474471e8392153d844e6d01bfb36a5d33acc95fd75fb932c4523482a3db573dd725659fe677170707581172a7808f76751e6fb8c17f",
          "sha256": "674148e15f2e77d103891f68d2559efac0eb10f937ecfd08c5c4d96033358db9",
          "sha1": "269d62c0b6ed5e13a3b30e7592c604587910e19c",
          "md5": "36f607c5e57d8bca5b83e3f4f63224ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.2-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.2-sources.jar",
          "size": 195036,
          "sha512": "1236f7a6606a15485ffd1b59a3afedc3c34ffd9729e647de2842fb69a4bf83e026ad4bc2d0e065de4fefd839cb806d1d342fa6d743669d802de2707e4dd9315c",
          "sha256": "1e1d6056fc3eb3ed1c90959884b0c78d291a4956451d06bbae21f46970314bcf",
          "sha1": "c000b6170ac76ecdd198e3580c59bac18aa45d2d",
          "md5": "436ea8ffaaf3e49313dda70cc3ae6a9b"
        }
      ]
    }
  ]
}
