{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2500.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.7.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.7.jar",
          "size": 364534,
          "sha512": "b6df015c6b7975bcafecbe1e6a8c85018e564aa0927210b0618320e80dfb9c7a70011889bc853c1433dd998d282cd4373dd534de965810e53ec507a9f1eb4204",
          "sha256": "06515a61efb14fee4c7035fa0514c97c72af0d9c5a592fbaed0e476725836259",
          "sha1": "f27380a46480c1744d5aad8c0a5675878f4589db",
          "md5": "5d6eefe1383d0613875b92440d11252e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.7.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.7.jar",
          "size": 364534,
          "sha512": "b6df015c6b7975bcafecbe1e6a8c85018e564aa0927210b0618320e80dfb9c7a70011889bc853c1433dd998d282cd4373dd534de965810e53ec507a9f1eb4204",
          "sha256": "06515a61efb14fee4c7035fa0514c97c72af0d9c5a592fbaed0e476725836259",
          "sha1": "f27380a46480c1744d5aad8c0a5675878f4589db",
          "md5": "5d6eefe1383d0613875b92440d11252e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.7-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.7-sources.jar",
          "size": 193560,
          "sha512": "0477feb4b80648fe37554400db10fcc8eab357b0e1c26737cde47d7a75f804d7107c194ef578a0ac2feb4355a541dd92dba2b2db0f8e3a8eb4e1ad5868099dc9",
          "sha256": "feac6a057bb7063b2a2334ee715d4f6a8753091226c6fb3ffec6280daff6ade0",
          "sha1": "ca1312c0641c58a614f4f29a25dd789afbdccdc1",
          "md5": "ecc19cf0615743157a44864f3ec57860"
        }
      ]
    }
  ]
}
