{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.7-1.8.2.2529.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2529.1.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2529.1.jar",
          "size": 19974373,
          "sha512": "bf1730307f049aedd08fe44876892331379e3fd0e07fa4d2aa1df676e7b021b7782ef4a975a6a20f396b9e54dcc00686b8b2254f28fdadab6b97256dd3f17796",
          "sha256": "3276759114407599aed3f9b7249c194bb6a23e2acd90bb512e4819cdf946d633",
          "sha1": "b01f3379ae11c9592406703b8bc3b9b07a01dcfc",
          "md5": "193d12f09d61d9cb2023e4327bef9788"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.7-2.2.5.2529.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2529.1.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2529.1.jar",
          "size": 19974373,
          "sha512": "bf1730307f049aedd08fe44876892331379e3fd0e07fa4d2aa1df676e7b021b7782ef4a975a6a20f396b9e54dcc00686b8b2254f28fdadab6b97256dd3f17796",
          "sha256": "3276759114407599aed3f9b7249c194bb6a23e2acd90bb512e4819cdf946d633",
          "sha1": "b01f3379ae11c9592406703b8bc3b9b07a01dcfc",
          "md5": "193d12f09d61d9cb2023e4327bef9788"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.7-1.8.2.2529.1-sources.jar",
          "url": "legacy-neoforge-1.21.7-1.8.2.2529.1-sources.jar",
          "size": 19050760,
          "sha512": "484a0aa6506ca44406ae178bf6500ee0b8d2f5dad92f135865b58f3149d50254fb16bf4df793acf618159afa03553edc5152062bc4a670e6d0c28d4d5407d597",
          "sha256": "288689e96b2b7d1e711fd9614745278c4f0c097f261ad09e0d6a57b3adbaf294",
          "sha1": "efb5fb995817733fe93362759363e3d816d0649d",
          "md5": "ec5b1f551af6ef569c5463905d5a2c65"
        }
      ]
    }
  ]
}
