{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.5-1.8.0.2515.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2515.1.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2515.1.jar",
          "size": 18287903,
          "sha512": "4194d8c2344e14e50c93b9e8343500f1764e9b9ecb4af3562fd0fd9d26bda1a67b0a0c5f020c5baf6e0933d7d923e4eed107a8687d8d6c0375d89dcf2de52404",
          "sha256": "66933b5721467a9d15d450f747485412e7705737c2a3e3b9ecac3f832adec985",
          "sha1": "cf4dc734b8402b37ad6ee685f7ab14731ae37789",
          "md5": "2c3b4cd5592ffdcb3314c71ab783c133"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.5-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2515.1.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2515.1.jar",
          "size": 18287903,
          "sha512": "4194d8c2344e14e50c93b9e8343500f1764e9b9ecb4af3562fd0fd9d26bda1a67b0a0c5f020c5baf6e0933d7d923e4eed107a8687d8d6c0375d89dcf2de52404",
          "sha256": "66933b5721467a9d15d450f747485412e7705737c2a3e3b9ecac3f832adec985",
          "sha1": "cf4dc734b8402b37ad6ee685f7ab14731ae37789",
          "md5": "2c3b4cd5592ffdcb3314c71ab783c133"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.5-1.8.0.2515.1-sources.jar",
          "url": "legacy-neoforge-1.21.5-1.8.0.2515.1-sources.jar",
          "size": 17432476,
          "sha512": "0ceedba22d7af8b5282a44ac527cd5b1fbf88c150cfdf91a314bb134856e2fac8f03b23e2ba9dc9c5715eecc485e3ec35b54d98b4755e83b4458f3e87a2545f5",
          "sha256": "ff4f97081d80f538f8fbb67bbdc0e1fea581a7baa742a23e07b0574ad176e4ac",
          "sha1": "8829946b8d6a5944d5645271912ffe19b5e5e004",
          "md5": "e58a23b23d510de2c301ef18b74d749d"
        }
      ]
    }
  ]
}
