{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.1.jar",
          "size": 392107,
          "sha512": "ebf12e3c130d2f0b75df73e80e2a6542c55e82ce09207fd8ff3426862e7601f7e93ee5b8db58c397353baac8f9c1d226d7682725a73d557b45370226c001634a",
          "sha256": "59d40a34558c726ed36a08c27d4cf41fcb1874854a05114b9652d929a92a3d7d",
          "sha1": "77eb5f37668e3bef58342613b4a787d8dd27eb97",
          "md5": "ece047f51238e96990c49cadc3577027"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.1.jar",
          "size": 392107,
          "sha512": "ebf12e3c130d2f0b75df73e80e2a6542c55e82ce09207fd8ff3426862e7601f7e93ee5b8db58c397353baac8f9c1d226d7682725a73d557b45370226c001634a",
          "sha256": "59d40a34558c726ed36a08c27d4cf41fcb1874854a05114b9652d929a92a3d7d",
          "sha1": "77eb5f37668e3bef58342613b4a787d8dd27eb97",
          "md5": "ece047f51238e96990c49cadc3577027"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.1-sources.jar",
          "size": 197992,
          "sha512": "584d89b7f22e2e4b808cc900d5e68b38e80387962d80a820d842d8a0cde90c752f106b0afffa85466bdf0cf77462d42b812f1f0caa1a95dac24ae594ebcc96af",
          "sha256": "606fadba00a04fe4eb4473019ad631d131885cbe714fcaccd62e3177b1f64a79",
          "sha1": "8a4ca6213cd01ed1ffb413e79d64135a8f15d16a",
          "md5": "018fb089fa969d1cb809ee331846d01b"
        }
      ]
    }
  ]
}
