{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.21.1-1.1.2518.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2518.1.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2518.1.jar",
          "size": 646660,
          "sha512": "94c1b32bec5c4124d8f81a585fd145de47fe3ee1315f50fbefc3157ca3ccc455636cd56d7a61e013e77bae64d53b7aba228022a08b801ff3733c86bc577c57c4",
          "sha256": "7bb674dd845e881e1d23ffb6a3621447f414321e23e95b02f8f85cfad6c23754",
          "sha1": "b6a539ee883e3ecdbb274eef882d62be89d25503",
          "md5": "aefe97983efc6d48262b7ff994177044"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3.2518.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2518.1.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2518.1.jar",
          "size": 646660,
          "sha512": "94c1b32bec5c4124d8f81a585fd145de47fe3ee1315f50fbefc3157ca3ccc455636cd56d7a61e013e77bae64d53b7aba228022a08b801ff3733c86bc577c57c4",
          "sha256": "7bb674dd845e881e1d23ffb6a3621447f414321e23e95b02f8f85cfad6c23754",
          "sha1": "b6a539ee883e3ecdbb274eef882d62be89d25503",
          "md5": "aefe97983efc6d48262b7ff994177044"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.1-1.1.2518.1-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.21.1-1.1.2518.1-sources.jar",
          "size": 583009,
          "sha512": "685bd88cd90c3e5b6a67219587c8368b45b5a32cb79165de41f889183e8cd8907279e8c0ecb2f7b6eefcbf89f4e6ea1b8ddecbd3356c4bcdb26a15f1e7981c88",
          "sha256": "7c56fab782fe79b2cbbb65e29fd0cad628ba92773b1749e62692eff31fb53225",
          "sha1": "2f32d5942027f1e2d105a29a07984d245adcd7bf",
          "md5": "bad37cd4f814aa35fb108f1997760635"
        }
      ]
    }
  ]
}
