{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.5-1.8.0.2514.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2514.0.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2514.0.jar",
          "size": 18264633,
          "sha512": "25015321da9b75c0dfd0d12fd60c7cd6b097bc1dbddab8fce1ea1a515f77f5dbca59e46299cd700ef5f2d6439b578a5268bd5ceece897fd7cc6d04c64e181e09",
          "sha256": "1c72ef6ddc520a7346e8229d8dcb724acf792ade775e6bc54d01cd6e553ac6bc",
          "sha1": "13012b6b5a4a105150e1ec166fff47832541517d",
          "md5": "162fb39b48e2fe2a5d30dcff668fdfb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.5-2.2.3.2514.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2514.0.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2514.0.jar",
          "size": 18264633,
          "sha512": "25015321da9b75c0dfd0d12fd60c7cd6b097bc1dbddab8fce1ea1a515f77f5dbca59e46299cd700ef5f2d6439b578a5268bd5ceece897fd7cc6d04c64e181e09",
          "sha256": "1c72ef6ddc520a7346e8229d8dcb724acf792ade775e6bc54d01cd6e553ac6bc",
          "sha1": "13012b6b5a4a105150e1ec166fff47832541517d",
          "md5": "162fb39b48e2fe2a5d30dcff668fdfb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.5-1.8.0.2514.0-sources.jar",
          "url": "legacy-forge-1.21.5-1.8.0.2514.0-sources.jar",
          "size": 17432142,
          "sha512": "33fb0bf3f728c1132bf9e1a9f0f75ede1d54688af8dcdb4cca9d8e8a17fb7de11317f4d1327274beb49eac703f1748885d844ee0e363cd5a2eadf062eeea916e",
          "sha256": "c291e2a379a6b0feaf4f1b21e9a3dfb2262ccbfd61763074953f4e7e2e162fbf",
          "sha1": "73eb6b3a66f9acae235f948deae908db17c486bd",
          "md5": "d88c9ca183620b3f3bfadd5c6e34d816"
        }
      ]
    }
  ]
}
