{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.21.1-1.8.0.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2512.0.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2512.0.jar",
          "size": 18248626,
          "sha512": "7921a196997d0302198152f8f60312667af9f06dae3fd7cfc3212ba5817e109f9a975f472cc29fe92c988a7e599054f272307d492d0fc16faf3ee60aad795946",
          "sha256": "34b1ba241be57027f1da8e73342baf477ade4455c7f5970cfe73dffd1511e62e",
          "sha1": "4bbadcedda090b72eab10732b5ca930c09e9a445",
          "md5": "77d0d9c2a570d5ee7891da041fdfd92f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2512.0.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2512.0.jar",
          "size": 18248626,
          "sha512": "7921a196997d0302198152f8f60312667af9f06dae3fd7cfc3212ba5817e109f9a975f472cc29fe92c988a7e599054f272307d492d0fc16faf3ee60aad795946",
          "sha256": "34b1ba241be57027f1da8e73342baf477ade4455c7f5970cfe73dffd1511e62e",
          "sha1": "4bbadcedda090b72eab10732b5ca930c09e9a445",
          "md5": "77d0d9c2a570d5ee7891da041fdfd92f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.21.1-1.8.0.2512.0-sources.jar",
          "url": "legacy-fabric-1.21.1-1.8.0.2512.0-sources.jar",
          "size": 17411976,
          "sha512": "d2ae763e8b26dfaca300329842a5ca3639970562aa0be10e49a5a55a6ba338a97b7865374f65855b2181fe6d6910a12db94fba25958af3b1771a4b5d8ed617c0",
          "sha256": "1c151b7230f643972ec4ff1c5d3623472b75066e1f8e3c125ee3f3ce8e919773",
          "sha1": "f85024b76375a79968d7194a1625362fbb844e8f",
          "md5": "5a896014461101673416423e7e9c09ff"
        }
      ]
    }
  ]
}
