{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.2.jar",
          "size": 679154,
          "sha512": "9e8ba523d7505fe8a232e63aeaf6cb88390031c9c794e072c660eef0ac87c1066013197c6a532752dabe6242270791d4a9eb3e6edfc65cc23a7510ed47186a95",
          "sha256": "01295a515268ff285bdfaa99340b9eee66c4e380beffb5c3b3d0ce2ddca92823",
          "sha1": "94d8f2b14d9695d2bd6f7d55ab9b2dc0f118791c",
          "md5": "018f7e52790f46a09354c97866b93bba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.2.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.2.jar",
          "size": 679154,
          "sha512": "9e8ba523d7505fe8a232e63aeaf6cb88390031c9c794e072c660eef0ac87c1066013197c6a532752dabe6242270791d4a9eb3e6edfc65cc23a7510ed47186a95",
          "sha256": "01295a515268ff285bdfaa99340b9eee66c4e380beffb5c3b3d0ce2ddca92823",
          "sha1": "94d8f2b14d9695d2bd6f7d55ab9b2dc0f118791c",
          "md5": "018f7e52790f46a09354c97866b93bba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2508.2-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2508.2-sources.jar",
          "size": 247922,
          "sha512": "440cd38c89494725833d3b8ffa43187602dfeff078a62f68465ee4a1757860a27864c4f1463fc3fe83fceb50bfa646fc61cabb6a97b7866fcbbca4385a8a3eec",
          "sha256": "abe6781a194f656bb204a1ec0071daac1904b410e548328a76a89c20d15cd22d",
          "sha1": "b3e5d8c294223b83a1d9aead282f20ff5cfba581",
          "md5": "9ed08f532c306cc2e3793b581d64c93f"
        }
      ]
    }
  ]
}
