{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2500.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.3.jar",
          "size": 347995,
          "sha512": "037ef8560d07a42166e8574eef5497558e87bb2c195abf14f19a736dc7aa746e721fb358bea7ea2d82e6f3ea41d7453f489cb8e1999d0d0be8269837b3ce92ff",
          "sha256": "07fc596bcaa48a4feaf5bdd3c2d83fa793cd399d5bb1ce1f20ff064ace93bf35",
          "sha1": "40bd21bfbd8cda2b19cf6bf1168719bff41b1f3b",
          "md5": "0f2207950d2316eaaa67fcb5ca045a8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.3.jar",
          "size": 347995,
          "sha512": "037ef8560d07a42166e8574eef5497558e87bb2c195abf14f19a736dc7aa746e721fb358bea7ea2d82e6f3ea41d7453f489cb8e1999d0d0be8269837b3ce92ff",
          "sha256": "07fc596bcaa48a4feaf5bdd3c2d83fa793cd399d5bb1ce1f20ff064ace93bf35",
          "sha1": "40bd21bfbd8cda2b19cf6bf1168719bff41b1f3b",
          "md5": "0f2207950d2316eaaa67fcb5ca045a8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2500.3-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2500.3-sources.jar",
          "size": 192003,
          "sha512": "f089217c55760b2b35a2ec280488f7ec1abddfe5703a952aebd176136f25dfafb320b0c0b78ae819581b3753082b853c8592d62544f0e7b3a3e9edc5ea9562aa",
          "sha256": "d1e7552bca58af3a26265cee2b38823a15d5ca1c15d107723caa46e2ac43cef0",
          "sha1": "459fe9320822db64288016473aa748dfc3841ebc",
          "md5": "ff0880d1a34ec42af94e6b59fd43d10b"
        }
      ]
    }
  ]
}
