{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2500.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.0.jar",
          "size": 354383,
          "sha512": "181bb68aadfcb121bd77e9e77b95f4f1b05df73a53823323484aed2a02dd48f9aedb4a96965cbdce05bb06e366ef25c833dd8d6c371d77b4755cba11719abd93",
          "sha256": "5c2492b6a391e746df7f98a5d36f171d560d4fdc780cd629ecd5196641af6b86",
          "sha1": "121175a0afcbedd826fc71177d2a6d03dd08be9d",
          "md5": "db1108f57a14161dc81078afafb1959b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.0.jar",
          "size": 354383,
          "sha512": "181bb68aadfcb121bd77e9e77b95f4f1b05df73a53823323484aed2a02dd48f9aedb4a96965cbdce05bb06e366ef25c833dd8d6c371d77b4755cba11719abd93",
          "sha256": "5c2492b6a391e746df7f98a5d36f171d560d4fdc780cd629ecd5196641af6b86",
          "sha1": "121175a0afcbedd826fc71177d2a6d03dd08be9d",
          "md5": "db1108f57a14161dc81078afafb1959b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2500.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2500.0-sources.jar",
          "size": 191035,
          "sha512": "a338430778b3eb69923dfa2b9f86c772495e681f3ca748aa02a68f71417fbe6c4ead3409cfe9e658650cff711e224f9b82c649d90b7787e1f78eba0abd5859b2",
          "sha256": "b3f42b73f200a9750021b3e787a6512bcc3f94534ae7b79513c307ed505e3394",
          "sha1": "e8ddcc1c3b4dc901443145b86b4eb70dbb25e7eb",
          "md5": "23717c1cfd24b7f8b0c051f1ae1d4384"
        }
      ]
    }
  ]
}
