{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.6.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.6.jar",
          "size": 357277,
          "sha512": "cf159d550bd85bab19b9127d6cab7cfa8d8e96c30b5ad33d68ffea8219920e5b109fb549d413c684ce8e34f49ef4924d0e57c54468a129c7b85afe6bf479f32f",
          "sha256": "753b4d584bfe307effea4fe4c0922f52fe4b047d7eee34cbbc4bc9f82f929097",
          "sha1": "fc470eb2d99133b30a1ed912f36c934dc2e1ae1d",
          "md5": "b1596fc64fa65be096d5111fd69b1acf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.6.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.6.jar",
          "size": 357277,
          "sha512": "cf159d550bd85bab19b9127d6cab7cfa8d8e96c30b5ad33d68ffea8219920e5b109fb549d413c684ce8e34f49ef4924d0e57c54468a129c7b85afe6bf479f32f",
          "sha256": "753b4d584bfe307effea4fe4c0922f52fe4b047d7eee34cbbc4bc9f82f929097",
          "sha1": "fc470eb2d99133b30a1ed912f36c934dc2e1ae1d",
          "md5": "b1596fc64fa65be096d5111fd69b1acf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.6-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.6-sources.jar",
          "size": 195008,
          "sha512": "0615596fa526a7208bf300a702898a53e8c26105bf4e0d82c23f4f65ceed4a65db235c59a8ccb5571139e581f3fd91d72200ecf1b407503b901c7e9e814f6678",
          "sha256": "acc6175fdc1532cfa9e03399c6af9c8d754aef88b583f1c2e2d14dee3dca24e4",
          "sha1": "88a4c4b8005ca9b9feca034015378a5d4d9d1b0d",
          "md5": "ba88ca02ee649d0ba7a8edec76abf3af"
        }
      ]
    }
  ]
}
