{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2513.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.0.jar",
          "size": 514125,
          "sha512": "f09ccc4ed74ba888dacf634e947c35591dca77eaa0be604ee46358e5c7c6154cd86919987679ca602f1d8e8e56646d03c98fc68119819f8ba1c9db3340c622cb",
          "sha256": "d8db945cba41ea68eec1cf618736f40eed84ec5d40d7bef7274483a06f89bd87",
          "sha1": "6d2c4e1ad299db80d0a554af413261649cecb6cb",
          "md5": "9c76182b8f939cb7af9dc94366247652"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.0.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.0.jar",
          "size": 514125,
          "sha512": "f09ccc4ed74ba888dacf634e947c35591dca77eaa0be604ee46358e5c7c6154cd86919987679ca602f1d8e8e56646d03c98fc68119819f8ba1c9db3340c622cb",
          "sha256": "d8db945cba41ea68eec1cf618736f40eed84ec5d40d7bef7274483a06f89bd87",
          "sha1": "6d2c4e1ad299db80d0a554af413261649cecb6cb",
          "md5": "9c76182b8f939cb7af9dc94366247652"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2513.0-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2513.0-sources.jar",
          "size": 250821,
          "sha512": "eed5fb5b47bf026fb75f8f537377a393c5ab63d86e0c54aa849ecc426f496e1d338b8e3b2f30c8777757f6d46ee3394c2330dfbdb3ee8135a31ba16cdd4dffc8",
          "sha256": "d98bf19a617e2ccbe09e6f6bbe3774783038c42d24cc8b052f360a5be34f3070",
          "sha1": "3ad018de4c197b8e523145d4c567e7a547127b48",
          "md5": "a82c636daee6693258dd61d9be8ea8db"
        }
      ]
    }
  ]
}
