{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2507.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.7.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.7.jar",
          "size": 492718,
          "sha512": "83871499e9088ea842b8e7d157470a143bc00a17ac9c54686b819777a22ff8cae509a80e364e2f4a5e6d882568b1d2ebb4cdb01595b2d076b0de953a2013eec7",
          "sha256": "9ee182f22c1c4870c6b330532ad7778f368851d35aa7a285acdfd45daf70b580",
          "sha1": "b97836193b7cc27328327fe3c09c9b9acfb685e5",
          "md5": "60191a3b9e7a09d655e548ef03237626"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.7.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.7.jar",
          "size": 492718,
          "sha512": "83871499e9088ea842b8e7d157470a143bc00a17ac9c54686b819777a22ff8cae509a80e364e2f4a5e6d882568b1d2ebb4cdb01595b2d076b0de953a2013eec7",
          "sha256": "9ee182f22c1c4870c6b330532ad7778f368851d35aa7a285acdfd45daf70b580",
          "sha1": "b97836193b7cc27328327fe3c09c9b9acfb685e5",
          "md5": "60191a3b9e7a09d655e548ef03237626"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2507.7-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2507.7-sources.jar",
          "size": 244491,
          "sha512": "c4965e0bb52501e2064f8f9059dd7934704ee8523e0710b3a56e6f0e3fc2ad2b8449ff08e5049d20ade816ce7d5f99fd16d789d7c95f88fb11f70f582db737d8",
          "sha256": "79d8c58f2ee1ad3628da42a4439381b30bb7661203226cf20d96c1f1810b61b8",
          "sha1": "7483cfb4499e06ae980a778af7e9c1de649a3cd7",
          "md5": "fdf64610cd584ced6d8e2aa74fc98830"
        }
      ]
    }
  ]
}
