{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.7.10.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.1.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.1.jar",
          "size": 14246264,
          "sha512": "0510662d9cea5be2dfc6c6dbbe085fe9260dfdff301fe5250c60e3cf00f3734bfcc9c9eddef1fd44a02519909f2152ef75456750cf2e9b6b18660556307347bf",
          "sha256": "0820780ed1a801b04a0964ff7e9ced00d9c05fc796cf6b96c49b9f626849a37b",
          "sha1": "609d74a4ec64ed34112da10f7df04d35049fb76a",
          "md5": "65746c182da0794c07fd99e26a2c2429"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.1.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.1.jar",
          "size": 14246264,
          "sha512": "0510662d9cea5be2dfc6c6dbbe085fe9260dfdff301fe5250c60e3cf00f3734bfcc9c9eddef1fd44a02519909f2152ef75456750cf2e9b6b18660556307347bf",
          "sha256": "0820780ed1a801b04a0964ff7e9ced00d9c05fc796cf6b96c49b9f626849a37b",
          "sha1": "609d74a4ec64ed34112da10f7df04d35049fb76a",
          "md5": "65746c182da0794c07fd99e26a2c2429"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.7.10.2504.1-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.7.10.2504.1-sources.jar",
          "size": 13447584,
          "sha512": "09f4ef07f213601c34980b04b19bdf09d077c997502c073be0aced39fdf35572768bd03d3295db866122196691884b098c01072e3249da1e3e14351116762e1b",
          "sha256": "71a21333c4c9c383579583006eea3c07184959c7934d3ede2a4a20b4e19c6e27",
          "sha1": "aeb82c8bd337da04f132446e740816295b7e1911",
          "md5": "ff2a1331589c58c0b249443369bf1b87"
        }
      ]
    }
  ]
}
