{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.2500.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2500.7.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2500.7.jar",
          "size": 384445,
          "sha512": "638fbf4166497cf82d6776a375eeff9bae710884b1a8cac9a5a7fe69e33af4ad9aadd4506c39d503bc6e73fc6e6ebc69d0cbe59d8c392d9234467209e9f391cd",
          "sha256": "2a7c3fa21856bbae10863839d9993b7e993931bf9f9e8890e6dd41bca3d7ab8c",
          "sha1": "22d3f006dc9a087007ebe7b4d4d846c9c314a125",
          "md5": "e885e6d3019b30f4aebe87c45ab1f3f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2500.7.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2500.7.jar",
          "size": 384445,
          "sha512": "638fbf4166497cf82d6776a375eeff9bae710884b1a8cac9a5a7fe69e33af4ad9aadd4506c39d503bc6e73fc6e6ebc69d0cbe59d8c392d9234467209e9f391cd",
          "sha256": "2a7c3fa21856bbae10863839d9993b7e993931bf9f9e8890e6dd41bca3d7ab8c",
          "sha1": "22d3f006dc9a087007ebe7b4d4d846c9c314a125",
          "md5": "e885e6d3019b30f4aebe87c45ab1f3f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.2500.7-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.2500.7-sources.jar",
          "size": 192135,
          "sha512": "f14241fdf6b2ce9d08576ac5dfd1d7bee86ecb117918bb5c111921b0d4f92182467d99183f30282682138d7ea48e7db1a8b0d8405d9b3c6e65c148efec9c3f7b",
          "sha256": "9a6023608ebab58a0e6f1223e15a7af792f157aca5e2a93179d88408f95d374d",
          "sha1": "ab2eef0014eb588dc951fdcb72c1c9be78b54073",
          "md5": "f13892937fcc5708021558ab1bb2c454"
        }
      ]
    }
  ]
}
