{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2510.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.2.jar",
          "size": 682012,
          "sha512": "229237ed00417cf9110191392d2d4eafde89bd49cd23fc6a1ef3107abf0074ed05af146f482b92ec674b7de895a089b3aa43d3aaf1ce5c115703ab86ab041b6e",
          "sha256": "7fb9b25f7c825809fdf9176f4e578a23e792d1e597736bfd77913aa0ef3b522b",
          "sha1": "7f23e372937a924e9e197aa47af7ead616c961af",
          "md5": "df4c14b6bdcc9bc2da30779b80bb7838"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.2.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.2.jar",
          "size": 682012,
          "sha512": "229237ed00417cf9110191392d2d4eafde89bd49cd23fc6a1ef3107abf0074ed05af146f482b92ec674b7de895a089b3aa43d3aaf1ce5c115703ab86ab041b6e",
          "sha256": "7fb9b25f7c825809fdf9176f4e578a23e792d1e597736bfd77913aa0ef3b522b",
          "sha1": "7f23e372937a924e9e197aa47af7ead616c961af",
          "md5": "df4c14b6bdcc9bc2da30779b80bb7838"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.2-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.2-sources.jar",
          "size": 252537,
          "sha512": "335543aa2b60ed61ac787087cf0806c6ee09149189c107d46f504707384c389d48e0b24bbe1f5596528cffd1f710633d1dc3cab7396c781d0beb7fd663478ccf",
          "sha256": "6fcbdf1e8e8ac711a0fd6fd7bac985ab15c0fe53bffe87985a2706b803fa37fa",
          "sha1": "876d72d4fafa6e23cdc42a5577221ad23033b067",
          "md5": "a8e822b58852bb957efb7c32058a07d6"
        }
      ]
    }
  ]
}
