{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "size": 482042,
          "sha512": "3887a2321b9069d9bf6546da7e3f9f2a91148463839caccb8d615055a696b9db6636cc68b4b0e32e63a97eb37d59fd230c63c6087842c079605baf014f986337",
          "sha256": "f5331d8ff0411291ff900c86dab2e9b98322eabad5296f4564e23727c3659e5c",
          "sha1": "597e4fa048d5b3af5ed79b761d203e41afe300a5",
          "md5": "95f18b9526b896cdae586bac9d87d6c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "size": 482042,
          "sha512": "3887a2321b9069d9bf6546da7e3f9f2a91148463839caccb8d615055a696b9db6636cc68b4b0e32e63a97eb37d59fd230c63c6087842c079605baf014f986337",
          "sha256": "f5331d8ff0411291ff900c86dab2e9b98322eabad5296f4564e23727c3659e5c",
          "sha1": "597e4fa048d5b3af5ed79b761d203e41afe300a5",
          "md5": "95f18b9526b896cdae586bac9d87d6c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.0-sources.jar",
          "size": 237371,
          "sha512": "9159196eaa25a76a16a81fd1c21f27e139bb6fd058763ff4ce92fac23dbecf9f548bb5fc385ce4ed45b175b3bb9672fd956e3f38bdab3607ea5cb99d2cac05d5",
          "sha256": "35b5f31679547ab100a0e556760e3490febc0d37f1a0642d60ea3ac2a4db1597",
          "sha1": "a8fd319484733f54c426c248e7b5535523631dda",
          "md5": "99e7ab86690af34b448864db9c1fb218"
        }
      ]
    }
  ]
}
