{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2506.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "size": 481051,
          "sha512": "f6a82040e75d5e95c55a5af189261fe69ac531379bf291fab587b1f62f9d23250e73877cad81005894a018d7701faf84953031062892390a8087de725ce15422",
          "sha256": "449eb58e74724219a2f11554f04aee9d84d7144e860273891bdd07ef6d110433",
          "sha1": "b6eca3f0e62dae79b02a9f70f064617a5840e967",
          "md5": "1aa15485a5c89ff9a6c8bd8981e2a4cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.0.jar",
          "size": 481051,
          "sha512": "f6a82040e75d5e95c55a5af189261fe69ac531379bf291fab587b1f62f9d23250e73877cad81005894a018d7701faf84953031062892390a8087de725ce15422",
          "sha256": "449eb58e74724219a2f11554f04aee9d84d7144e860273891bdd07ef6d110433",
          "sha1": "b6eca3f0e62dae79b02a9f70f064617a5840e967",
          "md5": "1aa15485a5c89ff9a6c8bd8981e2a4cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2506.0-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2506.0-sources.jar",
          "size": 237160,
          "sha512": "e103e5ebab9dc57cf223f1f401a33d83fb8b02682f4e8cc4e4cc7e23fd7bce4eca8dc665b0a94295d8fd918e77e0990f880a2e9847e966fb63bb7dfa31e0f1ae",
          "sha256": "be8402a666928315cb728ab6eccff72029eadc63168589b764b5c60329ab20bb",
          "sha1": "40fae8795c13983ab36455b92a4aa46ad705e802",
          "md5": "1f7300661538d6acb5c0d36ec9cf6706"
        }
      ]
    }
  ]
}
