{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "size": 498614,
          "sha512": "b2ff6b5a67ef6b84bb2fee846ed2c4927ef3e21bfc72a25e564adec96a284c01a1d7b763834d3a8b918865303bd2885424e0b8b724e449dfabd18c61b88ad953",
          "sha256": "38e1c6199d2d25bdbc5a5cb57fed04d34fc398abf711f22480ad060cc82bc813",
          "sha1": "08465ae5f79861cab9c2e679ac1ca6e190d1eb57",
          "md5": "0e53152b903222794fe22532d01ac62d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "size": 498614,
          "sha512": "b2ff6b5a67ef6b84bb2fee846ed2c4927ef3e21bfc72a25e564adec96a284c01a1d7b763834d3a8b918865303bd2885424e0b8b724e449dfabd18c61b88ad953",
          "sha256": "38e1c6199d2d25bdbc5a5cb57fed04d34fc398abf711f22480ad060cc82bc813",
          "sha1": "08465ae5f79861cab9c2e679ac1ca6e190d1eb57",
          "md5": "0e53152b903222794fe22532d01ac62d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.5-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.5-sources.jar",
          "size": 250590,
          "sha512": "90e7634891cd6f0c7895a205029448f64f23cf3870fce7ffc97f106c5f3438a679244b8c6c8f341c77184888d2abb24e5577eed00ffc30c09d541f5291d890cd",
          "sha256": "5a0fd5d7a29f9cf406027987ce1ef2af399991bac5e8cc9c79d8565231607954",
          "sha1": "f58ce83da1a544816f5cd514449c3debc656b0f9",
          "md5": "cb4256680430bf68952cbdcd78b5229a"
        }
      ]
    }
  ]
}
