{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2510.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "size": 498422,
          "sha512": "7198b99a364954b4549a4329cdb64ad7f3b99bcb373264398cf1b2514e46643de2c52649727eb180f46216e3143eabf5de3e43e1dae0e7a6dc42c19ecd1ce238",
          "sha256": "7ba5254657257e9d3633ccde42c853423714d194de41d1a027f432807f0b2a36",
          "sha1": "da32125f02bb65bec672cf92fa434a8ee2deeecf",
          "md5": "1bc2ed59cbe8d52126d3b70cd597174a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.5.jar",
          "size": 498422,
          "sha512": "7198b99a364954b4549a4329cdb64ad7f3b99bcb373264398cf1b2514e46643de2c52649727eb180f46216e3143eabf5de3e43e1dae0e7a6dc42c19ecd1ce238",
          "sha256": "7ba5254657257e9d3633ccde42c853423714d194de41d1a027f432807f0b2a36",
          "sha1": "da32125f02bb65bec672cf92fa434a8ee2deeecf",
          "md5": "1bc2ed59cbe8d52126d3b70cd597174a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.5-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.5-sources.jar",
          "size": 250505,
          "sha512": "514e44e4bc779bcd99849725e586651da05621f9ba4a3d2c05639021bc7dbe0d0c12b264c32ecde65f56375f4ff19c74e62bb642e9efee62809d08f250c574d5",
          "sha256": "f88ea04e15d6a56c6ca4d40b47e2da2a1b7dbf4cd13932d21e43c0a3af3a84d7",
          "sha1": "4b8538e7b94e3c0d084e8da0b21a0c5a02bf8ce0",
          "md5": "25703a0019d8f03c1cc836fa8dafb314"
        }
      ]
    }
  ]
}
