{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.2.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.2.jar",
          "size": 491920,
          "sha512": "4326d3d7cfec24628cf12db44ece59da194dc6cbc633df1cb97315962f3cbde48abd1c27f19a8ed7046bddc31cb40211889d8ead8baefb2bfdd758565339974f",
          "sha256": "f41f4d0f7578888ee1867bda8dcbdcd76c583244d712de1e988ae355c0c125ac",
          "sha1": "1d05f9b4726c08c405b9c936b0c07d45eba51b5b",
          "md5": "b12c60697468814d4db4b1fd2c9cb33a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.2.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.2.jar",
          "size": 491920,
          "sha512": "4326d3d7cfec24628cf12db44ece59da194dc6cbc633df1cb97315962f3cbde48abd1c27f19a8ed7046bddc31cb40211889d8ead8baefb2bfdd758565339974f",
          "sha256": "f41f4d0f7578888ee1867bda8dcbdcd76c583244d712de1e988ae355c0c125ac",
          "sha1": "1d05f9b4726c08c405b9c936b0c07d45eba51b5b",
          "md5": "b12c60697468814d4db4b1fd2c9cb33a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.2-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.2-sources.jar",
          "size": 248171,
          "sha512": "b35ff6912d2eef40f347a55fd6b93d776dc802883303191554a384b86efd2ceec65edeb676bb5874678797823a543768d06a32b86b17223bf08c7ffdaf020f5f",
          "sha256": "7f0659bab47bcbc71e20dc4b1859f9f723a41842f554bc49cb8495ed24de8d95",
          "sha1": "30fcd22086b7b7421e01c6a61aef7dcb0320c040",
          "md5": "28a043dd19a723a71e333a055b61ca73"
        }
      ]
    }
  ]
}
