{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.21.4-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.2+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.4-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.4-1.1.2516.3.jar",
          "size": 637499,
          "sha512": "25c0021e54e186b95d6dc1dcfe0a83051bffb8b82d74bc60b42e3b445915e6577fc930fc773d0dd4e11a7331d35a466c1f6805f309ed1ef29bc36d7fce93a492",
          "sha256": "2d2921230d17b6474a1ea4d563ad3e502ed0e17bcdb63bee28bc82f0ec781cbd",
          "sha1": "e51fad5ff24c9c03d0b24b59a0fe91ebc1d45e4a",
          "md5": "2015ab40566cb49f4c99efe044f11be6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.4-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.2+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.4-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.4-1.1.2516.3.jar",
          "size": 637499,
          "sha512": "25c0021e54e186b95d6dc1dcfe0a83051bffb8b82d74bc60b42e3b445915e6577fc930fc773d0dd4e11a7331d35a466c1f6805f309ed1ef29bc36d7fce93a492",
          "sha256": "2d2921230d17b6474a1ea4d563ad3e502ed0e17bcdb63bee28bc82f0ec781cbd",
          "sha1": "e51fad5ff24c9c03d0b24b59a0fe91ebc1d45e4a",
          "md5": "2015ab40566cb49f4c99efe044f11be6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.4-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.21.4-1.1.2516.3-sources.jar",
          "size": 582999,
          "sha512": "74196493a8f4d6ccca8e094ce5c573da27c533d324fec1c483e6ed6af06d80776b16a339d0e26d0606d59fd4418abd1430aea6c651b46a18035f3cbca571d88e",
          "sha256": "ce208ee0fa433c36ce0d54aebfb3a096d349560674a4f98a97ba618adff8d330",
          "sha1": "0f3b56c2845f1b3d8d6b8e4e8c21b064162cf0ba",
          "md5": "b609bc7cdf447d9d75c9911cb69b28c5"
        }
      ]
    }
  ]
}
