{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.7.2617.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2617.2.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2617.2.jar",
          "size": 1173232,
          "sha512": "848d698983f7528d023614534fe05c2b86258f5bc64f8c7c70f435e816aa064e933ec2048a12c7558d4e5a95c18fd139d2c92752eeff5d8283e9d48d16e99378",
          "sha256": "b592c65fc46bb42dacc1bc0181f61ce62a71263e598c4e9b00b85235d51d9fa3",
          "sha1": "fd26c37820d5cacce7450937040cc158c40ea589",
          "md5": "2eb1d4d7be233fcc6e6170aaf2c96192"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.0"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2617.2.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2617.2.jar",
          "size": 1173232,
          "sha512": "848d698983f7528d023614534fe05c2b86258f5bc64f8c7c70f435e816aa064e933ec2048a12c7558d4e5a95c18fd139d2c92752eeff5d8283e9d48d16e99378",
          "sha256": "b592c65fc46bb42dacc1bc0181f61ce62a71263e598c4e9b00b85235d51d9fa3",
          "sha1": "fd26c37820d5cacce7450937040cc158c40ea589",
          "md5": "2eb1d4d7be233fcc6e6170aaf2c96192"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2617.2-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2617.2-sources.jar",
          "size": 256840,
          "sha512": "e1b7a4e86767b9fccaf31a0d43f66746fb20a6664418655790e8b1eb3a91baa8bfcc8f8d0163b6ca9664c54a1d7cdcd323a9661ecc1051dbac01d0e6370a2d5b",
          "sha256": "c537b721c71921fe63a8f3f24b6977e53f447e7c29ddd1e441eb834c6f20e67e",
          "sha1": "bdd4e3c67c00176b28433777053bde9ea60d3877",
          "md5": "82d54aec15bb75c2433d8764bacff999"
        },
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2617.2-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2617.2-sources.jar",
          "size": 256840,
          "sha512": "e1b7a4e86767b9fccaf31a0d43f66746fb20a6664418655790e8b1eb3a91baa8bfcc8f8d0163b6ca9664c54a1d7cdcd323a9661ecc1051dbac01d0e6370a2d5b",
          "sha256": "c537b721c71921fe63a8f3f24b6977e53f447e7c29ddd1e441eb834c6f20e67e",
          "sha1": "bdd4e3c67c00176b28433777053bde9ea60d3877",
          "md5": "82d54aec15bb75c2433d8764bacff999"
        }
      ]
    },
    {
      "name": "jarJarRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.7.2617.2.jar",
          "url": "factory_api-forge-1.20.1-2.2.7.2617.2.jar",
          "size": 1173232,
          "sha512": "848d698983f7528d023614534fe05c2b86258f5bc64f8c7c70f435e816aa064e933ec2048a12c7558d4e5a95c18fd139d2c92752eeff5d8283e9d48d16e99378",
          "sha256": "b592c65fc46bb42dacc1bc0181f61ce62a71263e598c4e9b00b85235d51d9fa3",
          "sha1": "fd26c37820d5cacce7450937040cc158c40ea589",
          "md5": "2eb1d4d7be233fcc6e6170aaf2c96192"
        }
      ]
    }
  ]
}
