{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.15.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.15.jar",
          "size": 371195,
          "sha512": "1d801779098830c4965c3b8091d4c13f0af0bc10b44939a293ee46c16e880a2c4b3f9d27c365d2277ee51727b507b338534409db982379d8ab25f38971b5d817",
          "sha256": "77fecde12d1c3904c8a26a41de7f91de53fc11d458ae6ad29a5a89c656738208",
          "sha1": "42e40e6d1363cf52cf4e2362351d1dc9b0e67f76",
          "md5": "9c87e2cc383030a0953c2f9075dc3b81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.15.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.15.jar",
          "size": 371195,
          "sha512": "1d801779098830c4965c3b8091d4c13f0af0bc10b44939a293ee46c16e880a2c4b3f9d27c365d2277ee51727b507b338534409db982379d8ab25f38971b5d817",
          "sha256": "77fecde12d1c3904c8a26a41de7f91de53fc11d458ae6ad29a5a89c656738208",
          "sha1": "42e40e6d1363cf52cf4e2362351d1dc9b0e67f76",
          "md5": "9c87e2cc383030a0953c2f9075dc3b81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.15-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.15-sources.jar",
          "size": 199545,
          "sha512": "1e00fd2269d9d08377aba60a5edb5fc012ffaff745d52b9cc8e9077e9eabda04491fc2de00d91a719d3a916794fc8d44998cbfa3b196352ac10cd22046b02b72",
          "sha256": "6555458a9db47ab7abb9ac6bec8761e194813bb4d19063468ca2c342dc5e99be",
          "sha1": "068652b889ca38bb02f60b0f3d459c00912e54ed",
          "md5": "4b3aa14bd86f6ca5b1b7764d6d3c8d13"
        }
      ]
    }
  ]
}
