{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.6.2541.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.6.2541.1.jar",
          "size": 521081,
          "sha512": "8295bc4bcafde07080b9efcb1168e740a5751ac12ce282178cd6868c0461aa93a144b1865fca02cc37546466216871127c5f7c63eb44c1374d4eb39b6bb1b952",
          "sha256": "cf00ea669ed2866c96ef142ccb67b16e8420d279b0396234a219f271a5a6d13c",
          "sha1": "a7e57a15013666ec480637a0593460dcb6dc1998",
          "md5": "1dc1185308a8092ba7480ee8013f8501"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.6.2541.1.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.6.2541.1.jar",
          "size": 521081,
          "sha512": "8295bc4bcafde07080b9efcb1168e740a5751ac12ce282178cd6868c0461aa93a144b1865fca02cc37546466216871127c5f7c63eb44c1374d4eb39b6bb1b952",
          "sha256": "cf00ea669ed2866c96ef142ccb67b16e8420d279b0396234a219f271a5a6d13c",
          "sha1": "a7e57a15013666ec480637a0593460dcb6dc1998",
          "md5": "1dc1185308a8092ba7480ee8013f8501"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.6.2541.1-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.6.2541.1-sources.jar",
          "size": 267640,
          "sha512": "801d2631e4aa33ab74fc343169cf9b3d4afcbbdaa815ce093160297242b4ca1c498977872472690c78b1cee166932e7fda7e51195166a8949b1d0ed7580769d8",
          "sha256": "9da4fa86b8d4369b29eed5b54201710f33c68fbd4df1b3cda4d4b63361504d98",
          "sha1": "9a8e0dc1faf5494a740ce5ca51f1c014e0b62655",
          "md5": "2014589c7492d25f25e0e0da91e7de82"
        }
      ]
    }
  ]
}
