{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2502.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.8.jar",
          "size": 433680,
          "sha512": "950268f83ae16de2f4ffcd885f835fc1368d4b3068ccbd58d975fe67d045b7a593748089e61660d1cc97ec894d7fd145bedf86dd186d40936845c6164082db61",
          "sha256": "f7b6e7528663c7b45db8929f4ea1d5220d8b14a793fca7a6100ab95cddec189d",
          "sha1": "dfad12f658d26ab54fcc33e171b7e52a5fa95567",
          "md5": "e7be80607049ea32e913fe2dab3f40fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.8.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.8.jar",
          "size": 433680,
          "sha512": "950268f83ae16de2f4ffcd885f835fc1368d4b3068ccbd58d975fe67d045b7a593748089e61660d1cc97ec894d7fd145bedf86dd186d40936845c6164082db61",
          "sha256": "f7b6e7528663c7b45db8929f4ea1d5220d8b14a793fca7a6100ab95cddec189d",
          "sha1": "dfad12f658d26ab54fcc33e171b7e52a5fa95567",
          "md5": "e7be80607049ea32e913fe2dab3f40fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2502.8-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2502.8-sources.jar",
          "size": 222134,
          "sha512": "bcb116a7e7526e0d5ab225d5bfa6b5e00ed412c23d1c48840ab80e53ca6de3fa67fc02715e88a7fd303e497040cde38a23de1ab925da176fc700e3325112c56b",
          "sha256": "42cceb4715956cbfd6ee50ca92a290981ac3238ddec8d39f0dba77ed2f6912c5",
          "sha1": "bf4312b7cfeeaabdeee94ac6e08b0ef7cc9d1b6f",
          "md5": "b77d61644105aee087676cf09c8e8fe0"
        }
      ]
    }
  ]
}
