{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2510.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.0.jar",
          "size": 680728,
          "sha512": "bb832184e9546caf2dd277da5f751455d9d37cf89c87ebd8d1fd0a0a3127c1d23d98bdda96002b62e5c1308645bc759cf70b662ad784e89f67fbd2e118b34892",
          "sha256": "34e6d5d5b15608b71cfb51016adacce0f60f8cf941f69838c159ac631a770cb5",
          "sha1": "e28e0639c0e89e8a7eb68457ce572a623befa7b6",
          "md5": "64060c7c07f7a31720248b760bc8fc89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.0.jar",
          "size": 680728,
          "sha512": "bb832184e9546caf2dd277da5f751455d9d37cf89c87ebd8d1fd0a0a3127c1d23d98bdda96002b62e5c1308645bc759cf70b662ad784e89f67fbd2e118b34892",
          "sha256": "34e6d5d5b15608b71cfb51016adacce0f60f8cf941f69838c159ac631a770cb5",
          "sha1": "e28e0639c0e89e8a7eb68457ce572a623befa7b6",
          "md5": "64060c7c07f7a31720248b760bc8fc89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2510.0-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2510.0-sources.jar",
          "size": 252153,
          "sha512": "f86c9ee67fea410e8eaae3f9686e305f53e9446278e8c882099ef1f3c70d44bbd037ae15cacdc64055295c468e4fea9bc18289e8f6ca126911d340ea9cd6f6bd",
          "sha256": "e41245ca7588f8a6389ff84e3992bcb6755fe2f423e5a6403b01366128cf19b9",
          "sha1": "c9e4e211ccab448b16a2c216e84e0fe5145d7895",
          "md5": "63e138bc8477d4b63f899bfa158ef748"
        }
      ]
    }
  ]
}
