{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.3.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2512.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2512.0.jar",
          "size": 697752,
          "sha512": "60a5d07b3170bb6d0792bca00edd7a3f2872a9213e4982380f50016b30abcbc637f5deadc781a4a298264289ca2240ee2d93102c35dd8fdbd63b8dc116c7c487",
          "sha256": "bb6373dffdf556d9b256b372e2dda61b244aa8548d687b49da1d60cb53d607a1",
          "sha1": "b487a68db08e1b1882bffcd706756ef0511c0077",
          "md5": "f7d13e0544eaec16b4ccd12ea5f50bfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2512.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2512.0.jar",
          "size": 697752,
          "sha512": "60a5d07b3170bb6d0792bca00edd7a3f2872a9213e4982380f50016b30abcbc637f5deadc781a4a298264289ca2240ee2d93102c35dd8fdbd63b8dc116c7c487",
          "sha256": "bb6373dffdf556d9b256b372e2dda61b244aa8548d687b49da1d60cb53d607a1",
          "sha1": "b487a68db08e1b1882bffcd706756ef0511c0077",
          "md5": "f7d13e0544eaec16b4ccd12ea5f50bfa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.3.2512.0-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.3.2512.0-sources.jar",
          "size": 250715,
          "sha512": "474a795526ac1b3e3d8f9a8eccdbcd0dc4cdc19b8d8f08dc437fac122000b46af7d0e09a16947c55b6ca89044e1878b2799c9536e21fa78060845d3f91d593c0",
          "sha256": "95c624a4b88a212771fa5e59a67d3c5a53959bf236a0dd94a387c6b48a161632",
          "sha1": "fe9c65379fdb7ddd2fdfac60b727342236cc7c5a",
          "md5": "6990bece8fc22924e64ad7ca6a9c4d6e"
        }
      ]
    }
  ]
}
