{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2617.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2617.0.jar",
          "size": 581356,
          "sha512": "61f89bc951511709297a3f58b47054cb68fd51fecaf080b520aeaec605e879594c8b8acfb1b84a9f0f18d8cb3331d5e9123476cf618698c088a185b141d0f479",
          "sha256": "7f115e040630140ecfbb1f7ceae65dd287f1d95015009c94b3edf8a11dcdbfbd",
          "sha1": "882190f3460afc74d2a1e899f07d5e263d0137f0",
          "md5": "de209dde64d404e5608fe8b6b0584d74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2617.0.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2617.0.jar",
          "size": 581356,
          "sha512": "61f89bc951511709297a3f58b47054cb68fd51fecaf080b520aeaec605e879594c8b8acfb1b84a9f0f18d8cb3331d5e9123476cf618698c088a185b141d0f479",
          "sha256": "7f115e040630140ecfbb1f7ceae65dd287f1d95015009c94b3edf8a11dcdbfbd",
          "sha1": "882190f3460afc74d2a1e899f07d5e263d0137f0",
          "md5": "de209dde64d404e5608fe8b6b0584d74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.7.2617.0-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.7.2617.0-sources.jar",
          "size": 256296,
          "sha512": "5f69527b99b4feefd40da2833cfbc42ca2183c02bb9a9c14dd9ec1cbab3237c1bba901f62f718d069199e10ae209c109f7c047fbc184052b2ac68aefb4b91e8e",
          "sha256": "f1219ccc8949b5324f9db47501a423e4c3cec606e42319a89dbaa5fb2928fb17",
          "sha1": "b6e43e3f95302f7a95836fba33127597fe9c54db",
          "md5": "286489362f19302bb9e1804eed62a0d3"
        }
      ]
    }
  ]
}
