{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2502.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.6.jar",
          "size": 443515,
          "sha512": "f804a01c9464b9142220e75e2f2ed7f402d9c6ae37f28a7af6c04680a9bc794dd8d05b035058469167a4272ad2d72239c89d5fb577c6c232fc7a40b9cdda7878",
          "sha256": "e78c1af2689e8923a41d98afff3b4ddb746d4e009679c1d4f2f0c8d4f31cbd20",
          "sha1": "ba13da5feeee48ee62b649071a7d15f50d966b80",
          "md5": "c91f93e3a885f8bfa480519572d3aa15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.6.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.6.jar",
          "size": 443515,
          "sha512": "f804a01c9464b9142220e75e2f2ed7f402d9c6ae37f28a7af6c04680a9bc794dd8d05b035058469167a4272ad2d72239c89d5fb577c6c232fc7a40b9cdda7878",
          "sha256": "e78c1af2689e8923a41d98afff3b4ddb746d4e009679c1d4f2f0c8d4f31cbd20",
          "sha1": "ba13da5feeee48ee62b649071a7d15f50d966b80",
          "md5": "c91f93e3a885f8bfa480519572d3aa15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2502.6-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2502.6-sources.jar",
          "size": 222346,
          "sha512": "8d68f3e329688c67353944a9d8aad79334a58c7c84721d2ad352296677838103862a57be38c82950899d32dcef63e5d9f385e5bd1f549b57c76a7ae596e4dbb7",
          "sha256": "7436841dd2f5b9fa512351674677881bfaeec76a83df4d236d181f3be41bec31",
          "sha1": "389dff46266299ca4e63a5201ba97786507cdd1c",
          "md5": "bc5afd5fefad1ed0feae82bb9fb8e0a3"
        }
      ]
    }
  ]
}
