{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2508.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2508.2.jar",
          "url": "factory_api-forge-1.20.1-2.2.2508.2.jar",
          "size": 701284,
          "sha512": "5a45d8882e863bf522f9f6f143074edd1bb986319e38d1dce4ed43a48b098578977197c6a2db1e035a44119e04e0c96827820357f557a1044c0657403234b5a4",
          "sha256": "d1db2509568587d447d013adc6a9f0e59fd2b730afbf664f319b46c4a539eb1c",
          "sha1": "37d2386990d7d077bf4591107fc943b0b610afab",
          "md5": "903d2100a0a3731608fcce22a8e624f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2508.2.jar",
          "url": "factory_api-forge-1.20.1-2.2.2508.2.jar",
          "size": 701284,
          "sha512": "5a45d8882e863bf522f9f6f143074edd1bb986319e38d1dce4ed43a48b098578977197c6a2db1e035a44119e04e0c96827820357f557a1044c0657403234b5a4",
          "sha256": "d1db2509568587d447d013adc6a9f0e59fd2b730afbf664f319b46c4a539eb1c",
          "sha1": "37d2386990d7d077bf4591107fc943b0b610afab",
          "md5": "903d2100a0a3731608fcce22a8e624f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2508.2-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2508.2-sources.jar",
          "size": 250201,
          "sha512": "6b93392336955119e4a8354959b4b27d99ac42de060745bdbeca583a76dc05b20a494e30b225676fcdac3b3299d05e02ab34ff122fd0888b23a58384daf5ee4c",
          "sha256": "d4e39ae2af7a81ae0401c6010d0a178feaee917e1bdf29fc9173003d48961450",
          "sha1": "cc942bde5a806ed68418e075d37423111f322bed",
          "md5": "278d27f0d28633944e22559e63408cf1"
        }
      ]
    }
  ]
}
