{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.6.2545.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.6.2545.0.jar",
          "size": 706544,
          "sha512": "9e5c9c78928124ebac9dbfa94c2619268190e756da5a08e4bd3dbc329ae3913bd674aef0912d9b950454cf14d27384d13b9af9ba7e1a07be4f2f4a90a79f8fac",
          "sha256": "2bdbeaf3919336aa7ed5ebd0ed946992fe521c7c28b732042968b0bb64cddc67",
          "sha1": "ff8c63232d21eb418b6b0c54e2f5ef61dbb9003f",
          "md5": "f3d11e3d92c32daa8f715c049691c639"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.6.2545.0.jar",
          "url": "factory_api-forge-1.20.4-2.2.6.2545.0.jar",
          "size": 706544,
          "sha512": "9e5c9c78928124ebac9dbfa94c2619268190e756da5a08e4bd3dbc329ae3913bd674aef0912d9b950454cf14d27384d13b9af9ba7e1a07be4f2f4a90a79f8fac",
          "sha256": "2bdbeaf3919336aa7ed5ebd0ed946992fe521c7c28b732042968b0bb64cddc67",
          "sha1": "ff8c63232d21eb418b6b0c54e2f5ef61dbb9003f",
          "md5": "f3d11e3d92c32daa8f715c049691c639"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.6.2545.0-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.6.2545.0-sources.jar",
          "size": 270571,
          "sha512": "5871bb0422130eaddc78c3f34e042187da579c161a35543212aeb0c54da97ec3f232dde5043f1e9fb30f96e8872677539a15ed70bdfd4aa446c09b6d0b5cb659",
          "sha256": "d3c7e8801ed38cd5ab7f590b5d8bf86fb0d7a02e2a1db1f275fc4a200e13c8df",
          "sha1": "fd56a038d3710438ebd38ccdf3bb46d196521572",
          "md5": "39d2aec49eddab0cd1f457ba6b18fcb3"
        }
      ]
    }
  ]
}
