{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.6.2547.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2547.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2547.0.jar",
          "size": 538042,
          "sha512": "a5d325c6cc93c56362747ad081dff27ccdb95d055af6656ba17b537000e06375d2f362a282bcf207e22b574f8968f651cf2cf0c6c010f526e0c5afa134b5e9a7",
          "sha256": "04a6f33a00fac4464ebadf6376c4b6fbcfd1b965352efad24fbf71beef9f713e",
          "sha1": "4cfd8c6e318adf5883a0f6348f458934abf8f758",
          "md5": "ce6d3ac3a9d40d1ae30081d000a05047"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2547.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2547.0.jar",
          "size": 538042,
          "sha512": "a5d325c6cc93c56362747ad081dff27ccdb95d055af6656ba17b537000e06375d2f362a282bcf207e22b574f8968f651cf2cf0c6c010f526e0c5afa134b5e9a7",
          "sha256": "04a6f33a00fac4464ebadf6376c4b6fbcfd1b965352efad24fbf71beef9f713e",
          "sha1": "4cfd8c6e318adf5883a0f6348f458934abf8f758",
          "md5": "ce6d3ac3a9d40d1ae30081d000a05047"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.6.2547.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.6.2547.0-sources.jar",
          "size": 269124,
          "sha512": "7dd659c07d98ea122ed6dbcb26d86d1506375ac4f98b8a48175f95ff6e53851058f25ee57d39e68fe92dcda554257007cd13b6d9db5d09d23c5bab5cabd1ac72",
          "sha256": "dde6473a9965333dd90968b4bef00eaf1b9444ef29073d398370c60a45fa3739",
          "sha1": "7931a5fc135d64843879ae723605827d1b2c8f4c",
          "md5": "109644ccff78ad7559c076929899fff9"
        }
      ]
    }
  ]
}
