{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2512.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2512.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2512.0.jar",
          "size": 511377,
          "sha512": "391d2386af2a9d78e0587a64b7a035ae9b6207e7daaba1cdd99fdc24aeb2e4bec9378e55f0e06127bd3cd630fefcb89eff3afe3aec1e8e42ce15cde391970f03",
          "sha256": "cd60f3d0dd40b4154adf75512f13460bce19569cff73cbd484bf13485c357402",
          "sha1": "9234917f8ab9b7fcc68d6099b0c90a8f9850c0b9",
          "md5": "4f4cb87ee77187515d297d2b9e2f0f0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2512.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2512.0.jar",
          "size": 511377,
          "sha512": "391d2386af2a9d78e0587a64b7a035ae9b6207e7daaba1cdd99fdc24aeb2e4bec9378e55f0e06127bd3cd630fefcb89eff3afe3aec1e8e42ce15cde391970f03",
          "sha256": "cd60f3d0dd40b4154adf75512f13460bce19569cff73cbd484bf13485c357402",
          "sha1": "9234917f8ab9b7fcc68d6099b0c90a8f9850c0b9",
          "md5": "4f4cb87ee77187515d297d2b9e2f0f0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2512.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2512.0-sources.jar",
          "size": 250748,
          "sha512": "800aef9e8e920d52e3fedae81b2ca6744aac72dabb131a809e9f859f8a4ad0ca900338c653baf68b5759c3b081cefd61dc5e6a064b766d6377a6ddc216c734be",
          "sha256": "0aaf3c04e5606cb62c849b7bcc6e19fc166fffc7b47b4150f3cfdd6835d15374",
          "sha1": "6b0f2efe41c922705ab5e4277e4320299f71d995",
          "md5": "2969cb19c8c680fc7b93640c1a0f05a4"
        }
      ]
    }
  ]
}
