{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2501.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.23.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.23.jar",
          "size": 390457,
          "sha512": "058dce455615af987bb25ca696272fe511bc413dfe10071afe576b2fc18a19654131d8dfc858707f98023eedfbe3711331a59022c3733f72b1f2e19edf60621a",
          "sha256": "9f7ab8cceba08d612e6b28987714b35f879c5998c15d710d4b2c6a35fa32913c",
          "sha1": "2c5f4dd5aaf90102ce740262b333942720fe64d7",
          "md5": "65b17b998720621a7ca80d0d40f00df8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.23.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.23.jar",
          "size": 390457,
          "sha512": "058dce455615af987bb25ca696272fe511bc413dfe10071afe576b2fc18a19654131d8dfc858707f98023eedfbe3711331a59022c3733f72b1f2e19edf60621a",
          "sha256": "9f7ab8cceba08d612e6b28987714b35f879c5998c15d710d4b2c6a35fa32913c",
          "sha1": "2c5f4dd5aaf90102ce740262b333942720fe64d7",
          "md5": "65b17b998720621a7ca80d0d40f00df8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2501.23-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2501.23-sources.jar",
          "size": 201402,
          "sha512": "2a46c8a0d642a41fd29ac5c73e3419f598338e8cf1c6f3f1abe84eb59c9d2bd7286432e52327b3868d48b21b589cd36a4d6cffe89c85d2b12e6e6c2cc034eeea",
          "sha256": "5e355029654452711ddd9eb36e4d20025d29c46de53ef0ce7551c18591252635",
          "sha1": "e1248247ceeba24bd06766ecd5e8ccf7e2adbb11",
          "md5": "55f0e4813370fd23b7589609fbbaf390"
        }
      ]
    }
  ]
}
