{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.13.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.13.jar",
          "size": 361811,
          "sha512": "79189b45908c4cc26e0742fe05406bab0d7505f9cad4812bc5daee0e322fb92e14cd443bac54f01dd2b549a45a3414fd7e47ed7589d741c872248af8ae1efbc7",
          "sha256": "de2b7cee2db9fd369bb9100bd6dc39f185ae7b5788a03342513219954f40824e",
          "sha1": "33d9259354a97990a0e4d5509d69f9d03d93e706",
          "md5": "a6cb6c9513ed62cbbbef796afd6c96c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.13.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.13.jar",
          "size": 361811,
          "sha512": "79189b45908c4cc26e0742fe05406bab0d7505f9cad4812bc5daee0e322fb92e14cd443bac54f01dd2b549a45a3414fd7e47ed7589d741c872248af8ae1efbc7",
          "sha256": "de2b7cee2db9fd369bb9100bd6dc39f185ae7b5788a03342513219954f40824e",
          "sha1": "33d9259354a97990a0e4d5509d69f9d03d93e706",
          "md5": "a6cb6c9513ed62cbbbef796afd6c96c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.13-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.13-sources.jar",
          "size": 197320,
          "sha512": "1b673fbe40209f0b8d439c0d7b51f76c660233fb281855fffb2c464ff1eaecb7fe892fba6cdc1b77b785a01b7dea8abe9c6dd526009b9cf10ea3c4554e69699d",
          "sha256": "ac17c0628a766415b13743d3f64408fe88dc897347ca77e938c0c5a986341f86",
          "sha1": "43d25cca228265e7981831540189ad609b9db74c",
          "md5": "9e387079e14aa293be363b565d226539"
        }
      ]
    }
  ]
}
