{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2500.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.6.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.6.jar",
          "size": 374637,
          "sha512": "85f7b90fd3df6a98c0dcbf236d4438a302e0862822f7c4e34398feb5c9c43d1867903218c2a2cdf9ddc925389afdf459f5bc640bd09a546822f08a1068a8ffb6",
          "sha256": "8568a9aaf797a3264d5aa6036e86b943cf7f356ada550bf2d46d8fde18d7f94c",
          "sha1": "b713cb41ac3685f466f2b65a105ba77c5a009d80",
          "md5": "2042ca6c7db623be8534e56d758f2df7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.6.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.6.jar",
          "size": 374637,
          "sha512": "85f7b90fd3df6a98c0dcbf236d4438a302e0862822f7c4e34398feb5c9c43d1867903218c2a2cdf9ddc925389afdf459f5bc640bd09a546822f08a1068a8ffb6",
          "sha256": "8568a9aaf797a3264d5aa6036e86b943cf7f356ada550bf2d46d8fde18d7f94c",
          "sha1": "b713cb41ac3685f466f2b65a105ba77c5a009d80",
          "md5": "2042ca6c7db623be8534e56d758f2df7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2500.6-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2500.6-sources.jar",
          "size": 195085,
          "sha512": "c908b03e49feb255769331a989071ef79a672169cdc19e0811ee27ede1f9769a2926a8c74fb3fca3f522db7bbc70d1018fb5bd487ceca6382bc0afe59242b2ca",
          "sha256": "027f8d1c90db9e53437f3bb462a9f2ae6f418648e3e20bb5ae496ec938f77935",
          "sha1": "d8d51b67b664f4a0ecc881cdb7516b0748c918c3",
          "md5": "d87264f4ca37e619550c65002799988b"
        }
      ]
    }
  ]
}
