{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2507.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.12.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.12.jar",
          "size": 481834,
          "sha512": "837ce38a13b9f743d9c2c11f4c3254d544cbdbdf8f8ea89fd38b21f2b50805dbd92c7fad7fc0c7e3460d797d7510ce5579b2e9f54797e4ddcd2885c6b7464944",
          "sha256": "5e88f7a6c0e131b02010dcaa3b68ac7e88f1da6f489fae841506d47fa28a28ca",
          "sha1": "c8e841e398432958a7d104bcee433f8dfdc7bd98",
          "md5": "d04a62606249bf8817d1934076db397c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.12.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.12.jar",
          "size": 481834,
          "sha512": "837ce38a13b9f743d9c2c11f4c3254d544cbdbdf8f8ea89fd38b21f2b50805dbd92c7fad7fc0c7e3460d797d7510ce5579b2e9f54797e4ddcd2885c6b7464944",
          "sha256": "5e88f7a6c0e131b02010dcaa3b68ac7e88f1da6f489fae841506d47fa28a28ca",
          "sha1": "c8e841e398432958a7d104bcee433f8dfdc7bd98",
          "md5": "d04a62606249bf8817d1934076db397c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2507.12-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2507.12-sources.jar",
          "size": 244592,
          "sha512": "bd7c5359d372676c402d098410aeae930ea6d3a1c2c84868325a33d1905fe7645728d91934071883265ad9797d40eca2f92e91c0dd4af6195a79a9dad133e935",
          "sha256": "8f7973eaff32c43a059abede0e2a885ef467ed3ee2ae904d9b199c8c3619fac1",
          "sha1": "e558505ea707b800820abd07b4b979c18f7e5771",
          "md5": "c668280b8fc5861585c727e89b903800"
        }
      ]
    }
  ]
}
