{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.20.4-1.1.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge-api",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.0.jar",
          "size": 598949,
          "sha512": "5d3b90fa244ed6715568464fff05cea93f24459de0da9bdfbd239d4d872b07b6d59a9e685263a4201ddd91d883e9d61e16ca02e459d2d17766601e1bd8657c24",
          "sha256": "c3ddf356deb2d4edbdb94c07c22ec7a9b29d60a047600208cd073d3313e3a121",
          "sha1": "e2dc274428195d33cbcb50e8c7ba94277c85afdf",
          "md5": "60cd954e5381780d345cc62229fe18cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.20.4-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.4-neoforge",
          "version": {
            "requires": "17.3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.0.jar",
          "size": 598949,
          "sha512": "5d3b90fa244ed6715568464fff05cea93f24459de0da9bdfbd239d4d872b07b6d59a9e685263a4201ddd91d883e9d61e16ca02e459d2d17766601e1bd8657c24",
          "sha256": "c3ddf356deb2d4edbdb94c07c22ec7a9b29d60a047600208cd073d3313e3a121",
          "sha1": "e2dc274428195d33cbcb50e8c7ba94277c85afdf",
          "md5": "60cd954e5381780d345cc62229fe18cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.0-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.20.4-1.1.2516.0-sources.jar",
          "size": 536482,
          "sha512": "5d2707895ea94aeff233896fefdd0bd5fe174c700c2c9af7d7c7cacc75f430ae91f56dd0ce6d4fb8b1cc28a89e3874acfe22fc2af23df37dcd88692c66965da1",
          "sha256": "e78a2fbb736397e4a4ddb81897fc0b7a0ee8af149cea53f003c73ce791f15965",
          "sha1": "6cd71dbe9c47b628ec1008446fd406865d611ab2",
          "md5": "45ee7bbc0b6b1527bd829ea6f62c03cb"
        }
      ]
    }
  ]
}
