{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.1.jar",
          "size": 506710,
          "sha512": "7d1b1faf244c99b034a205b3b375aae4b437fd692bbb6174d492f0791b7d0adfedfa472a2697fa47ebe5b94a328c11542bc28088886969c8bcd63dd34aae517f",
          "sha256": "cabb34178df4d49967f100df6ecff7ab5aedf4af3ca4895145296467520319ac",
          "sha1": "db1c76ab9214abb709793df3c34c4666ee8b380d",
          "md5": "640111e014df814010cc8a3fb33cf2c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.1.jar",
          "size": 506710,
          "sha512": "7d1b1faf244c99b034a205b3b375aae4b437fd692bbb6174d492f0791b7d0adfedfa472a2697fa47ebe5b94a328c11542bc28088886969c8bcd63dd34aae517f",
          "sha256": "cabb34178df4d49967f100df6ecff7ab5aedf4af3ca4895145296467520319ac",
          "sha1": "db1c76ab9214abb709793df3c34c4666ee8b380d",
          "md5": "640111e014df814010cc8a3fb33cf2c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2516.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2516.1-sources.jar",
          "size": 253498,
          "sha512": "381b89bca8ba97fdc8be1d9c0f982504cd352daa8d21a35977689e2eea9d515c4bf95482d901d8c6bcfad6147d3c5533752278212c8e6eaab6db50432d7d173d",
          "sha256": "1018d9ec549e61c88e7c63e5d144fa268e8d89b4fe8ca845c9f0c991db88daa3",
          "sha1": "b1dc21868936759461a2bf7f5b2f1f7532d9643d",
          "md5": "b510f40ca6a3afd34329c06bca6187de"
        }
      ]
    }
  ]
}
