{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.8.2.2526.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-forge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.2.2526.0.jar",
          "url": "legacy-forge-1.21.1-1.8.2.2526.0.jar",
          "size": 19757684,
          "sha512": "9afd0f2f33c03c296b8feeeca80eab43909c5b842a47a962eaa3e359d05e1c7971b0621e98d9035bc14ea1c39545abdbe7f9ac053ab4187b332b1518886477e9",
          "sha256": "b4047fc051c24c864084b7f82a15b2ab9f90d6354d5ba7fad53ed4326919e821",
          "sha1": "8d8ffd95d241c2d310b8f3dc7f619ccc1c44d98c",
          "md5": "bcaac368d37b22e93759aca2c46d910a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.2.2526.0.jar",
          "url": "legacy-forge-1.21.1-1.8.2.2526.0.jar",
          "size": 19757684,
          "sha512": "9afd0f2f33c03c296b8feeeca80eab43909c5b842a47a962eaa3e359d05e1c7971b0621e98d9035bc14ea1c39545abdbe7f9ac053ab4187b332b1518886477e9",
          "sha256": "b4047fc051c24c864084b7f82a15b2ab9f90d6354d5ba7fad53ed4326919e821",
          "sha1": "8d8ffd95d241c2d310b8f3dc7f619ccc1c44d98c",
          "md5": "bcaac368d37b22e93759aca2c46d910a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.8.2.2526.0-sources.jar",
          "url": "legacy-forge-1.21.1-1.8.2.2526.0-sources.jar",
          "size": 18885308,
          "sha512": "8e527fa0bf3a71f54c7ab9a1366504b27aa64bcac73b15984ecacb74870fed945b23747f95990fdd11274140d83437b375781d66a46680c2c60b735c5b390ee6",
          "sha256": "a7b6e630551989e452ff02f69508387b90df487423dd4d6a8eac87888b34b8a7",
          "sha1": "49e89cf03ef341a672f6c2f52e07097134a97ac0",
          "md5": "cb00979ab91adda25ccc3201760ceca2"
        }
      ]
    }
  ]
}
