{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.1-2.2.6.2541.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.6.2541.2.jar",
          "url": "factory_api-fabric-1.20.1-2.2.6.2541.2.jar",
          "size": 569127,
          "sha512": "9877027d4b91a4d9d2cb9359a40a914fdba52160427404e7cf2354f2edb6bb787995babdca32ab0ea3a41423c3b66cc4c6b6fb4ee28a9ccb52ce5126562081ef",
          "sha256": "00f4766bf1cc9bbee523d05105df25a2bf30d13980ac5399d8462f5a9de34f12",
          "sha1": "8357e174c9466d33f6f7b9b2bec281f7d2d7e23f",
          "md5": "ea596de6545e82b2d5bad515c1d66743"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          },
          "excludes": [
            {
              "group": "io.github.juuxel",
              "module": "unprotect"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.6.2541.2.jar",
          "url": "factory_api-fabric-1.20.1-2.2.6.2541.2.jar",
          "size": 569127,
          "sha512": "9877027d4b91a4d9d2cb9359a40a914fdba52160427404e7cf2354f2edb6bb787995babdca32ab0ea3a41423c3b66cc4c6b6fb4ee28a9ccb52ce5126562081ef",
          "sha256": "00f4766bf1cc9bbee523d05105df25a2bf30d13980ac5399d8462f5a9de34f12",
          "sha1": "8357e174c9466d33f6f7b9b2bec281f7d2d7e23f",
          "md5": "ea596de6545e82b2d5bad515c1d66743"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.1-2.2.6.2541.2-sources.jar",
          "url": "factory_api-fabric-1.20.1-2.2.6.2541.2-sources.jar",
          "size": 265613,
          "sha512": "5a945b2d7d7c868036f71d6448e4433c263b36a01ee1dc301087cff3f661d45494acc5e401fcfc9c832bb515ad75956b993c740758bf57d65132f477b2b922ca",
          "sha256": "4da5d3c3da795aca9845678a1e08028d3091fd2b2ddb6adfde92d374d6dde194",
          "sha1": "bb8f8cdf7b8ad8d1f53e564bacaa23374a52927f",
          "md5": "9f561de0ace19339f7e1998c36742394"
        }
      ]
    }
  ]
}
