{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.4-1.1.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.0.jar",
          "size": 596230,
          "sha512": "2e73830a9b0c345cca4aee0b3dedf8664dc1c4fca01b47cf6beedcc786149e1a00e40f7f3406e7a0450507e8635e4cbb2c9279548271203b78f4d6e9ed1893bd",
          "sha256": "ec004aa86ec4f3d9ba959fc6efacad67c11728efbda98f2aff415adb85bdd6a4",
          "sha1": "6bff64e74f80685396357550db01c640aa7efdc8",
          "md5": "6970b7ea56276c6756bd3f49b88ad772"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.0.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.0.jar",
          "size": 596230,
          "sha512": "2e73830a9b0c345cca4aee0b3dedf8664dc1c4fca01b47cf6beedcc786149e1a00e40f7f3406e7a0450507e8635e4cbb2c9279548271203b78f4d6e9ed1893bd",
          "sha256": "ec004aa86ec4f3d9ba959fc6efacad67c11728efbda98f2aff415adb85bdd6a4",
          "sha1": "6bff64e74f80685396357550db01c640aa7efdc8",
          "md5": "6970b7ea56276c6756bd3f49b88ad772"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.0-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.0-sources.jar",
          "size": 536357,
          "sha512": "1cab2343f987c82e38bba5c56cd72f524730578c5cd78f05c1432c06c10f4769aa07fc6c05a7204cf147f5e44eafe836503bda94e1c8af128568f41a29c45245",
          "sha256": "496cb2c9482b182a50e963ab3ad96e7a105b7fe03ca8714b7e6efcba7e7003c9",
          "sha1": "67ab91a4f74c7413d2736095fa24e693169d3e45",
          "md5": "e21f67e8296a60119de946a8612b2a2d"
        }
      ]
    }
  ]
}
