{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2516.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2515.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2516.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2516.0.jar",
          "size": 18280985,
          "sha512": "f70f3b4162ebac03be6ddb74a5e6144b49f22d4c8470f94c6a9c30e4c99231dcf939dafb9fa86186dd304a60edb976d5f56f0f02d3c8a7896c6fe77282f5aa24",
          "sha256": "027e9944526570854ac90caf93cf5961448d94f9553785d5ba45758e3425d723",
          "sha1": "61e2739cdcfbe537faabf2ab64612bd94a8d7da7",
          "md5": "141664a6329378bb9d253c88c845a2af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2515.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2516.0.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2516.0.jar",
          "size": 18280985,
          "sha512": "f70f3b4162ebac03be6ddb74a5e6144b49f22d4c8470f94c6a9c30e4c99231dcf939dafb9fa86186dd304a60edb976d5f56f0f02d3c8a7896c6fe77282f5aa24",
          "sha256": "027e9944526570854ac90caf93cf5961448d94f9553785d5ba45758e3425d723",
          "sha1": "61e2739cdcfbe537faabf2ab64612bd94a8d7da7",
          "md5": "141664a6329378bb9d253c88c845a2af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2516.0-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2516.0-sources.jar",
          "size": 17440386,
          "sha512": "b43e1ae05d538e0074ad00119cb1795f7469894d582823f6b26468a751b53a4555e8ef8ae3ecb1b98621ca96059617639e3ece5637b52786c91a9e317db82aad",
          "sha256": "da66f7c8614cc06b3c43d06bbed21ae7b8b8e8592a64cf619e40ba423c1c07b1",
          "sha1": "2ca4bca015f2c77ed2b093504f4532aed3cb5ff7",
          "md5": "d5ed0e23a3fe9b0185b83e41ec9a53f0"
        }
      ]
    }
  ]
}
