{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.21.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.21.jar",
          "size": 392265,
          "sha512": "31a3dce4525abcec341b93930c875376ad869b37af8322b3ee222fce299e166d1c6307534acfe915870084800bc90245acc6eb98729a25a17a1f277ba95a0aac",
          "sha256": "7fcba296b736e855b77107fd671a2119bddea2957717f7120bd9c92a6ae56d77",
          "sha1": "602a87a5109f905b3cec0f85b79601d9022ddd34",
          "md5": "fb9d993af32c92127c2ced88d298e8b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.21.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.21.jar",
          "size": 392265,
          "sha512": "31a3dce4525abcec341b93930c875376ad869b37af8322b3ee222fce299e166d1c6307534acfe915870084800bc90245acc6eb98729a25a17a1f277ba95a0aac",
          "sha256": "7fcba296b736e855b77107fd671a2119bddea2957717f7120bd9c92a6ae56d77",
          "sha1": "602a87a5109f905b3cec0f85b79601d9022ddd34",
          "md5": "fb9d993af32c92127c2ced88d298e8b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.21-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.21-sources.jar",
          "size": 201211,
          "sha512": "add4598e5e0d138bcfa688f801acdf1706d892d37f2ccee2fc5f9fb295ac79fff75abf234031b475f2ec469280b924c05a5b0f76b8f7cbd4a29486e19fc6352a",
          "sha256": "42ce9b393f12ee5ebd8a12a53f186b1eaa626c0dc23df455d7f65115aac42418",
          "sha1": "a57ea31cd338f4add39568801f2078da8b6ed311",
          "md5": "866616865b157d5d40b8c6cd6bc49093"
        }
      ]
    }
  ]
}
