{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.3-2.2.2502.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2502.13.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2502.13.jar",
          "size": 489002,
          "sha512": "0873326e5fd3e607ad66d598364a901a4686a94635a308cd0c4ad7effa37c592fdbfafc89e7b7333c6f8f245feed86e5d7b4d141235ce20a529daa6c88c54e41",
          "sha256": "966bcb905d0ce62f4f6f178f0226b3983f6800b68e5b1b475ff1d5c928a8a2e6",
          "sha1": "bd6069bb0b6d19846a6df6580973e7613f6a3fe0",
          "md5": "8296a4a9669ed1c17d90f962173b6ff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2502.13.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2502.13.jar",
          "size": 489002,
          "sha512": "0873326e5fd3e607ad66d598364a901a4686a94635a308cd0c4ad7effa37c592fdbfafc89e7b7333c6f8f245feed86e5d7b4d141235ce20a529daa6c88c54e41",
          "sha256": "966bcb905d0ce62f4f6f178f0226b3983f6800b68e5b1b475ff1d5c928a8a2e6",
          "sha1": "bd6069bb0b6d19846a6df6580973e7613f6a3fe0",
          "md5": "8296a4a9669ed1c17d90f962173b6ff4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.3-2.2.2502.13-sources.jar",
          "url": "factory_api-fabric-1.21.3-2.2.2502.13-sources.jar",
          "size": 227791,
          "sha512": "e75bdcc43b3a31612e6f6ed999183e8a102fe755aeb11842bf746ca2e120ebae63b9294b794f96ba32aa567ae339ef418dfa76a01bc62a89ca800489a2500e13",
          "sha256": "ed195090091c22369f7215ac9adf2376b55eb8de4cfc9b9447bfcec76113d74e",
          "sha1": "f2ef127c23565743c88a537cafc88541552676a8",
          "md5": "0b9eabfc2f40d7f1dfecc2fd2a03235f"
        }
      ]
    }
  ]
}
