{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.7.10.2502.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2501.24"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2502.0.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2502.0.jar",
          "size": 11908452,
          "sha512": "b2d595b9638a51c09a1f44c984e9c3176a7fd54ada0ed1494c98017180453c6dec10ad87e42a7f28b11b7cef4f9538a53f307888ff387348a592d3b4a27ffec9",
          "sha256": "0ffa262797c5a95e9f7435b567ec86353c51babc6ccbe8e687b3f1b762bf5c13",
          "sha1": "f47d1325bcc7e526a8ac2402791c2f2be521370a",
          "md5": "56f8c8f724dea449f03a8f29781586cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.2501.24"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2502.0.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2502.0.jar",
          "size": 11908452,
          "sha512": "b2d595b9638a51c09a1f44c984e9c3176a7fd54ada0ed1494c98017180453c6dec10ad87e42a7f28b11b7cef4f9538a53f307888ff387348a592d3b4a27ffec9",
          "sha256": "0ffa262797c5a95e9f7435b567ec86353c51babc6ccbe8e687b3f1b762bf5c13",
          "sha1": "f47d1325bcc7e526a8ac2402791c2f2be521370a",
          "md5": "56f8c8f724dea449f03a8f29781586cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.7.10.2502.0-sources.jar",
          "url": "legacy-fabric-1.20.1-1.7.10.2502.0-sources.jar",
          "size": 11133638,
          "sha512": "71b60847641c0c86b24985a7091cfac907284660ce09f17b6cdb9549d12620f9f34a6f51390ae82f784ebe48bdad9b7f78ad3962cde5bc5d3a5b03fb4c18cc4c",
          "sha256": "c3989d05a300984a418abee80fc42e4712d36776602dd702c53ba54f9ab7bd6f",
          "sha1": "d352078dba970a12e2fc037f45e816a52fc648d9",
          "md5": "4bae80777afc2c8ac275885c62bf1859"
        }
      ]
    }
  ]
}
