{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.20.4-2.2.3.2516.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2516.5.jar",
          "size": 539861,
          "sha512": "9700324842b19f86b7350e1f06d9c9fa791d959b2ca14d31957c75aac0d0cc93189931e86b1efcec2081a287e180bf587856de04994276e45f7f722d4494408a",
          "sha256": "fc54361034085bc0eb05edab12108140325a8b2439df1585b70869d9d94284c8",
          "sha1": "3bc2b19c3b13422d1e39229079914540031d4f20",
          "md5": "6443c9453d0e2b28e822c3cfd5947c9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2516.5.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2516.5.jar",
          "size": 539861,
          "sha512": "9700324842b19f86b7350e1f06d9c9fa791d959b2ca14d31957c75aac0d0cc93189931e86b1efcec2081a287e180bf587856de04994276e45f7f722d4494408a",
          "sha256": "fc54361034085bc0eb05edab12108140325a8b2439df1585b70869d9d94284c8",
          "sha1": "3bc2b19c3b13422d1e39229079914540031d4f20",
          "md5": "6443c9453d0e2b28e822c3cfd5947c9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.20.4-2.2.3.2516.5-sources.jar",
          "url": "factory_api-fabric-1.20.4-2.2.3.2516.5-sources.jar",
          "size": 252191,
          "sha512": "6e9ef99b0f7af1c3a343b758b53af28fbf5eab2c5661e66ff59872f0a206d14329be398442cf8b81107423e7966e9050ec91e5470aec1ff3cd215326e54e9ff5",
          "sha256": "301aad5c7ebfed45ea32b07c50cfbb4224a9a26a8d176de134dc07be1ff1a999",
          "sha1": "1f22ce11c18922b5eb6ef91a5e3d1a7e93bed66e",
          "md5": "1ad2a9fd1c82ccf5a0d8a3146a00d863"
        }
      ]
    }
  ]
}
