{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2500.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2500.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2500.0.jar",
          "size": 351650,
          "sha512": "0f16f5ba6f4531970003c96c8bb9f9f847db513dcec24a822ffe038e4040b00edcf5273c617c52e51440863138f9fbb8e7c1553285806d3c38149a4a2b3e1635",
          "sha256": "6cf42008da69b456e64c8ae913149850cb4c4102286d04bf3f39d831d842d5c6",
          "sha1": "adb1c4936a7ce2277d7dd16417b8bfc8d26cdaef",
          "md5": "a251ab622b891a6cbbfb180ba098f538"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2500.0.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2500.0.jar",
          "size": 351650,
          "sha512": "0f16f5ba6f4531970003c96c8bb9f9f847db513dcec24a822ffe038e4040b00edcf5273c617c52e51440863138f9fbb8e7c1553285806d3c38149a4a2b3e1635",
          "sha256": "6cf42008da69b456e64c8ae913149850cb4c4102286d04bf3f39d831d842d5c6",
          "sha1": "adb1c4936a7ce2277d7dd16417b8bfc8d26cdaef",
          "md5": "a251ab622b891a6cbbfb180ba098f538"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2500.0-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2500.0-sources.jar",
          "size": 190932,
          "sha512": "faeda9b78b43ae3e82df23559523886a9d4bb3b34bf9bfeee49a2dcb04869199fa49555600df3580de3c17e70934f98eed6698df718c9ef848b3e46303c67015",
          "sha256": "43668206cb30873bb1159692c8cc03d3531e3c3a8e8c5a8c663fa5d91f7bfc2c",
          "sha1": "d2991f44db8b3bc07b5737b81e58fab0b880d76d",
          "md5": "4455b11acb6299847bef76233bef40c3"
        }
      ]
    }
  ]
}
