{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "26.1.1-2.2.7.2615.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2615.2.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2615.2.jar",
          "size": 601759,
          "sha512": "a63fa90b8d8311b15415b0796c4586e0ebfc4a7079ad5f70fcac8050a621b510d69b4033c7b0d66c2ac5f47a5fd3a1fc59b299afcacede95c63ef6c69b1eca76",
          "sha256": "31deaa75197cb8cb8d07ee4477c23beb4152f97190ab4dac3073aaf76ec69d15",
          "sha1": "a5870e03e210992be8ce86e91195c3f4aa4f02a0",
          "md5": "5ce86db6b57b11f9eae9b45b21dba119"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.2+26.1.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "18.0.0-alpha.8"
          }
        },
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2615.2.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2615.2.jar",
          "size": 601759,
          "sha512": "a63fa90b8d8311b15415b0796c4586e0ebfc4a7079ad5f70fcac8050a621b510d69b4033c7b0d66c2ac5f47a5fd3a1fc59b299afcacede95c63ef6c69b1eca76",
          "sha256": "31deaa75197cb8cb8d07ee4477c23beb4152f97190ab4dac3073aaf76ec69d15",
          "sha1": "a5870e03e210992be8ce86e91195c3f4aa4f02a0",
          "md5": "5ce86db6b57b11f9eae9b45b21dba119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2615.2-sources.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2615.2-sources.jar",
          "size": 256895,
          "sha512": "539e4d8158d54795e1580c8e867d410aaac9a9e817a8c2fe777839dc95158f4e099d7f2d9ff4bd3e2e6c8a4deffd7c22f99e05ec7bc7061afebc56400a2ef079",
          "sha256": "8e28b1ece86c74889ec44a600e2be7184988f7dcd99001d5c8258d5f7d676400",
          "sha1": "a7a436011b4b8b9a25e8595515ce2fed809f5459",
          "md5": "b324c0fe4c1e231590278f90634a346c"
        },
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2615.2-sources.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2615.2-sources.jar",
          "size": 256895,
          "sha512": "539e4d8158d54795e1580c8e867d410aaac9a9e817a8c2fe777839dc95158f4e099d7f2d9ff4bd3e2e6c8a4deffd7c22f99e05ec7bc7061afebc56400a2ef079",
          "sha256": "8e28b1ece86c74889ec44a600e2be7184988f7dcd99001d5c8258d5f7d676400",
          "sha1": "a7a436011b4b8b9a25e8595515ce2fed809f5459",
          "md5": "b324c0fe4c1e231590278f90634a346c"
        }
      ]
    }
  ]
}
