{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2513.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.5.jar",
          "size": 494864,
          "sha512": "090e46168724bd45af48dc0cb3fc0a4aff2b709c16d0a933d5e44ba07b800bb59e729bcd60d7a6934636d68e8d2ed7780a4d8651d20b3bc4934ed5d50d45ee4a",
          "sha256": "bbaead10552778372d49cafc8fb49d9f053718ec65546046e4012e33a714c365",
          "sha1": "fe6017ca1b4260cc12580dacbf08b8645235b353",
          "md5": "304150cd8cef7265736e415da553aba1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.5.jar",
          "size": 494864,
          "sha512": "090e46168724bd45af48dc0cb3fc0a4aff2b709c16d0a933d5e44ba07b800bb59e729bcd60d7a6934636d68e8d2ed7780a4d8651d20b3bc4934ed5d50d45ee4a",
          "sha256": "bbaead10552778372d49cafc8fb49d9f053718ec65546046e4012e33a714c365",
          "sha1": "fe6017ca1b4260cc12580dacbf08b8645235b353",
          "md5": "304150cd8cef7265736e415da553aba1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2513.5-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2513.5-sources.jar",
          "size": 250397,
          "sha512": "7f47f2e37a07cfe45302355778323681d17c57b2728451ddf1791f9a1835147802e20476be063b3ff987c41dbc18c1325bb95cb9344293f269361625dd3c1d2a",
          "sha256": "368b5bea4808973f396e5c691274ef5efe2e36f810645fad632e352647871678",
          "sha1": "f70db0d2fbb220d863f8c0684b880c909743a7de",
          "md5": "12edef2ed2e44a4043f721034b1fea35"
        }
      ]
    }
  ]
}
