{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.1-1.8.2.2526.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.2.2526.0.jar",
          "url": "legacy-neoforge-1.21.1-1.8.2.2526.0.jar",
          "size": 19782286,
          "sha512": "2f2bcdb4bf36ad808545f8848f30db8aa4095f0dc6a9892e8340868fb510146ad940357faecf5e01879a3a55b53300bfdebb5b410da9fb79869fa637101836c6",
          "sha256": "52332c590a78dd7eba29d08f2017651416564948b62518a6e5223bf3e6b34388",
          "sha1": "5726d8760c1852e8836a1652f9a1b711cf027fe4",
          "md5": "4b5a190b7f4156f6b005bb9ff22c98d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.1-2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.2.2526.0.jar",
          "url": "legacy-neoforge-1.21.1-1.8.2.2526.0.jar",
          "size": 19782286,
          "sha512": "2f2bcdb4bf36ad808545f8848f30db8aa4095f0dc6a9892e8340868fb510146ad940357faecf5e01879a3a55b53300bfdebb5b410da9fb79869fa637101836c6",
          "sha256": "52332c590a78dd7eba29d08f2017651416564948b62518a6e5223bf3e6b34388",
          "sha1": "5726d8760c1852e8836a1652f9a1b711cf027fe4",
          "md5": "4b5a190b7f4156f6b005bb9ff22c98d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.1-1.8.2.2526.0-sources.jar",
          "url": "legacy-neoforge-1.21.1-1.8.2.2526.0-sources.jar",
          "size": 18885796,
          "sha512": "0b5fc09ce47d956e2ec5b0f1dd5a92b576a33b7e24f388786ad45f0cf020457538bfafb4bf5c2f6ca2245493c23b85a874742d76bd3c1e40ef41fcd181e9c6f7",
          "sha256": "0ad36002c094413a2c51fabc04a74363b65a3dab042b7e94fb46a7add4f0b61d",
          "sha1": "80f6285bbd6b4734bc827a07dfa215ec689e1fa1",
          "md5": "fdb0dd1f3931f4a24c8b5e4eb197699a"
        }
      ]
    }
  ]
}
