{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.3.2513.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.2.jar",
          "size": 700363,
          "sha512": "6bac1223d55f956600f6eeb9d0a61336e112b025fe11b7f160c05c2a677389213879172a243b590cbeeb8d9f363c3f2a41e989bd33793995de39a565b36c5ac1",
          "sha256": "4b2dff992736ec6316c4d3f7589acbe73d6769d7ec79d436154b806a7cba40a2",
          "sha1": "d08c3a0f92561c8dd461906f35e3d9307d2ae4aa",
          "md5": "50977d810fec478287eea5f670344d4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.2.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.2.jar",
          "size": 700363,
          "sha512": "6bac1223d55f956600f6eeb9d0a61336e112b025fe11b7f160c05c2a677389213879172a243b590cbeeb8d9f363c3f2a41e989bd33793995de39a565b36c5ac1",
          "sha256": "4b2dff992736ec6316c4d3f7589acbe73d6769d7ec79d436154b806a7cba40a2",
          "sha1": "d08c3a0f92561c8dd461906f35e3d9307d2ae4aa",
          "md5": "50977d810fec478287eea5f670344d4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.3.2513.2-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.3.2513.2-sources.jar",
          "size": 250834,
          "sha512": "0569e3f2a2d7c8459bd9688c6d661808f32627bc404612da0b67b4e632ee838cc8bcd5eed38fe6942eef8b3ef1460083ee0b4825bcdd22b1b5734d184f9a3296",
          "sha256": "4d403496bc9a07dee9af330c6c5aafdfb32416fc648e53b8166ebb85b229c051",
          "sha1": "c587daa42aab99e01773eaaa7e430062ae8af23e",
          "md5": "5be3d090cf8752b79fbcceaeb132b92d"
        }
      ]
    }
  ]
}
