{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.8.0.2518.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2518.3.jar",
          "size": 19673241,
          "sha512": "7642f78e8445d671d2b5132a93043bf05d6e4d7f5d393bd4d1d873f26e3dcced6e8a0289a33df7b7477455e7e55197a56e1546454262eb5a5699b17c0c582755",
          "sha256": "0c4afde677d0b868745f742797810d6b12c706a6cde6f27ea46518c06611efab",
          "sha1": "7b646d4cbb65e19ac69b6ca0a29f2d9693e25ec3",
          "md5": "783dcfff0f3ad85a1c3dea8ab1661345"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2518.3.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2518.3.jar",
          "size": 19673241,
          "sha512": "7642f78e8445d671d2b5132a93043bf05d6e4d7f5d393bd4d1d873f26e3dcced6e8a0289a33df7b7477455e7e55197a56e1546454262eb5a5699b17c0c582755",
          "sha256": "0c4afde677d0b868745f742797810d6b12c706a6cde6f27ea46518c06611efab",
          "sha1": "7b646d4cbb65e19ac69b6ca0a29f2d9693e25ec3",
          "md5": "783dcfff0f3ad85a1c3dea8ab1661345"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.8.0.2518.3-sources.jar",
          "url": "legacy-forge-1.21.4-1.8.0.2518.3-sources.jar",
          "size": 18818015,
          "sha512": "509a12690b0a6f30006337c5c5f1aface2adc3fd536447e9d8fa92e409dea49891c04b88ea8c260a5f34a74aa8d9d3c7052b17c8e0eb2a145644f0179e59869f",
          "sha256": "6a6698100f34fb4bdb7fbd77b4e3a137df25d427afa869211a589ef43ef76d24",
          "sha1": "595c10e8966e25e8cc6f943422403f85e859b43e",
          "md5": "270fd388e07982e3937fe62f4d32e2c8"
        }
      ]
    }
  ]
}
