{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.1-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.24.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.24.jar",
          "size": 381101,
          "sha512": "a0f428c396a7d91a8ddbad942f441fd5d51eecc4a7c0071818b79973bbc50894848eb3bbf7311f8942ca39a3a56240cc551582c68462e72493876c93d6f51bed",
          "sha256": "4a7943324163d161936234b3e25a522d62818214a964c8286448991253d41ec2",
          "sha1": "ab12cf742e90ebcdf4aa57cd126813e9285ee1ea",
          "md5": "60ffcb4b4c6669a155e316dcf0798422"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.24.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.24.jar",
          "size": 381101,
          "sha512": "a0f428c396a7d91a8ddbad942f441fd5d51eecc4a7c0071818b79973bbc50894848eb3bbf7311f8942ca39a3a56240cc551582c68462e72493876c93d6f51bed",
          "sha256": "4a7943324163d161936234b3e25a522d62818214a964c8286448991253d41ec2",
          "sha1": "ab12cf742e90ebcdf4aa57cd126813e9285ee1ea",
          "md5": "60ffcb4b4c6669a155e316dcf0798422"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.1-2.2.2501.24-sources.jar",
          "url": "factory_api-forge-1.21.1-2.2.2501.24-sources.jar",
          "size": 197403,
          "sha512": "6cb6234f016e443033b83c118fb42ac64707db8fcf80da52b8b8d562b87a661dbddce1778af69021352733b56d4d0bdcf3fac12b6f86ac2ac76c87ae7cf0b07e",
          "sha256": "1f0a6c448f4344a8c2b361594195812ec7c5a50a898a7ed71755d6f7bc99be00",
          "sha1": "4fb3f817dfb40bdd964ebfc8747d6ebe9932421b",
          "md5": "68a52b805559dad58ae6d1d82f328fc8"
        }
      ]
    }
  ]
}
