{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.0.jar",
          "size": 364525,
          "sha512": "7d25f40ad62ec4754a8d1b4fa9a916cbf55cdf0ba4a5c8bdcdd9d79666725a426dc1cd2ba731538633fae0d41284b5a38c54936d9044a7ecb4cab9691288fd20",
          "sha256": "99f84816785aa75cf8b3892ad06ba66588822d992e48d94f18f6cd27485c3ddf",
          "sha1": "fd0c69e9b9d65806e04ce482f78f965208b75950",
          "md5": "b399126c0f864a883db1b1cdf3b0b26d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.0.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.0.jar",
          "size": 364525,
          "sha512": "7d25f40ad62ec4754a8d1b4fa9a916cbf55cdf0ba4a5c8bdcdd9d79666725a426dc1cd2ba731538633fae0d41284b5a38c54936d9044a7ecb4cab9691288fd20",
          "sha256": "99f84816785aa75cf8b3892ad06ba66588822d992e48d94f18f6cd27485c3ddf",
          "sha1": "fd0c69e9b9d65806e04ce482f78f965208b75950",
          "md5": "b399126c0f864a883db1b1cdf3b0b26d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.0-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.0-sources.jar",
          "size": 193386,
          "sha512": "f3bb0b97142d9b6708b8b55bd9851488af47b2d352c114d35a1bba5c45b8edafcaf529711351fc6d54ff1ca24d07c7da4079e537a9fcd7c4be49f8ef21e2f1c1",
          "sha256": "5051d78eea4adebfd53f8bbd533d93729f709ee278ca66933afd3e2a051a297b",
          "sha1": "32f363037b5aa7423f12a0cf160b0713c95ead1e",
          "md5": "c8b3f5a2c8d7ce0db16c1f1162bbcc9a"
        }
      ]
    }
  ]
}
