{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.6.2544.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2544.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2544.1.jar",
          "size": 519333,
          "sha512": "48429c362a9ccb44edbb056d1c0b850665a96fe31feed85138e837dbb85807714bd25b760130c89a18ea8e7e633746c548bc59e7fbb2285646c4696cfa2d737d",
          "sha256": "65c895663ac0459593054773692a0b8ce1816cb64812511ad6be5382792d11f8",
          "sha1": "2bf98635b753db11e259d42dfe90b031ab3989af",
          "md5": "62e8ec896eb57c741a0e4898939e6dff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2544.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2544.1.jar",
          "size": 519333,
          "sha512": "48429c362a9ccb44edbb056d1c0b850665a96fe31feed85138e837dbb85807714bd25b760130c89a18ea8e7e633746c548bc59e7fbb2285646c4696cfa2d737d",
          "sha256": "65c895663ac0459593054773692a0b8ce1816cb64812511ad6be5382792d11f8",
          "sha1": "2bf98635b753db11e259d42dfe90b031ab3989af",
          "md5": "62e8ec896eb57c741a0e4898939e6dff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.6.2544.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.6.2544.1-sources.jar",
          "size": 268209,
          "sha512": "db1078e37c323ca9123dc6922719e7d4dff5bb528d62a410262b33251664171d77e3fe7a8a336fc5876e92561ccd02da30492c566dd41dd74b513033deab0e8a",
          "sha256": "d616dd44e9e04efaf3d379460184d41776e9b7cd6f745c87c915994b1e044c39",
          "sha1": "35fef8633d5fc201f009426279a56ee007cae428",
          "md5": "4dfabe02b3646c7fffefef5b52c412b1"
        }
      ]
    }
  ]
}
