{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2500.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.7.jar",
          "size": 348950,
          "sha512": "a437a0166c7b831bec613fc0e4d59ebe01ebcdb840e19028789370837f882e6595f31d5f3f73954a8fdba1461067d97a98c888558bb5cb87c574f190d354778d",
          "sha256": "dd3b60d80d298fe4bfa22dc8ac8d4e4c805b58edfb584490b37f3baeb5d48d70",
          "sha1": "79b38275bd00abac1f9e16ee4bf5c3cf0006abcf",
          "md5": "41b9ebf6ac2ec162c50277eee09d21fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.7.jar",
          "size": 348950,
          "sha512": "a437a0166c7b831bec613fc0e4d59ebe01ebcdb840e19028789370837f882e6595f31d5f3f73954a8fdba1461067d97a98c888558bb5cb87c574f190d354778d",
          "sha256": "dd3b60d80d298fe4bfa22dc8ac8d4e4c805b58edfb584490b37f3baeb5d48d70",
          "sha1": "79b38275bd00abac1f9e16ee4bf5c3cf0006abcf",
          "md5": "41b9ebf6ac2ec162c50277eee09d21fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.7-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.7-sources.jar",
          "size": 193430,
          "sha512": "14d199cae256018deb57ee211a457dc039cb8238c5ce23c4afb6ddfc89fa82c4a4841b661c7a66cf5b8ff361c42b65098f96ad0e34ce5ba5e7ea7bb5e5cc0d98",
          "sha256": "84ab400283444de34e0c06fc20d3aad0b59a258c788a38a6de97c3163520004b",
          "sha1": "d28aefbef399ff411b270cfb0ec33df013bfee03",
          "md5": "516d2afe361385389e32727d45fbd5b0"
        }
      ]
    }
  ]
}
