{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "26.1.1-2.2.7.2616.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2616.2.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2616.2.jar",
          "size": 601460,
          "sha512": "ea246ced6d22502cac9a9843ea479c7dee6e9eaa4ea21b3f8b760164bf21c30b5e66bee5c5c59133b90f0120f39092b1990c5045be8cef868a7d871c390c783c",
          "sha256": "6e1f92f4aea6aac3b1fe53d238813afdadb3ed7e43d8ef45f3cc73fe59915695",
          "sha1": "79782272ed829cd0f5cd4af08d82a7180e8187b6",
          "md5": "f6295e244d282a21dcbe51981721b842"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.2+26.1.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "18.0.0-alpha.8"
          }
        },
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2616.2.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2616.2.jar",
          "size": 601460,
          "sha512": "ea246ced6d22502cac9a9843ea479c7dee6e9eaa4ea21b3f8b760164bf21c30b5e66bee5c5c59133b90f0120f39092b1990c5045be8cef868a7d871c390c783c",
          "sha256": "6e1f92f4aea6aac3b1fe53d238813afdadb3ed7e43d8ef45f3cc73fe59915695",
          "sha1": "79782272ed829cd0f5cd4af08d82a7180e8187b6",
          "md5": "f6295e244d282a21dcbe51981721b842"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2616.2-sources.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2616.2-sources.jar",
          "size": 256693,
          "sha512": "1ca229b513561098dc19ea4fb8b7616dc1be7a8bea2153765ec44b8930a257c95671873124b619f2481cf1a1f588a9c964613286811fde15b78dc1ffb9bea5ba",
          "sha256": "cfae5bfbed5e0e4efe2243bb5a02ce1c7123819dda8cf1911ef4ab36f0fab0e4",
          "sha1": "c6438ef0f32eefe4117bd7f75545e93bdda6ec2c",
          "md5": "609a9da7f092962a02e13c6faf303aac"
        },
        {
          "name": "factory_api-fabric-26.1.1-2.2.7.2616.2-sources.jar",
          "url": "factory_api-fabric-26.1.1-2.2.7.2616.2-sources.jar",
          "size": 256693,
          "sha512": "1ca229b513561098dc19ea4fb8b7616dc1be7a8bea2153765ec44b8930a257c95671873124b619f2481cf1a1f588a9c964613286811fde15b78dc1ffb9bea5ba",
          "sha256": "cfae5bfbed5e0e4efe2243bb5a02ce1c7123819dda8cf1911ef4ab36f0fab0e4",
          "sha1": "c6438ef0f32eefe4117bd7f75545e93bdda6ec2c",
          "md5": "609a9da7f092962a02e13c6faf303aac"
        }
      ]
    }
  ]
}
