{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2504.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.2.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.2.jar",
          "size": 14235660,
          "sha512": "fef80fb5be5ac7efb7ca33793b428903d16db66bbd926c5a5dc002d07d3f9cfa2ac7f464f2f4aa66295fcd1e31083c1e5f7ac616a052b31302a706122a7d3041",
          "sha256": "953f76b221d1ddf83c4726ac9be115d6ca0629538f7e3e11969f42c0ced46e43",
          "sha1": "f1e9c5fd8cfe15a97cbef82b9a89f672189b3b70",
          "md5": "66c487dc615f86b8e0eca6b5c74a80eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.2.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.2.jar",
          "size": 14235660,
          "sha512": "fef80fb5be5ac7efb7ca33793b428903d16db66bbd926c5a5dc002d07d3f9cfa2ac7f464f2f4aa66295fcd1e31083c1e5f7ac616a052b31302a706122a7d3041",
          "sha256": "953f76b221d1ddf83c4726ac9be115d6ca0629538f7e3e11969f42c0ced46e43",
          "sha1": "f1e9c5fd8cfe15a97cbef82b9a89f672189b3b70",
          "md5": "66c487dc615f86b8e0eca6b5c74a80eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.2-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.2-sources.jar",
          "size": 13448968,
          "sha512": "5467ced1b4ee5d28038c8550bffb7246aad3637b06eb0bbd264c4d1f3d0ba9bf4ce2bc3029d6e5a348740ca1c8e61eabf54642677806208d3d8cca8a67d3a0dd",
          "sha256": "5a07a397c4ca7940be49e91c47d11ab38e2bc34f0a14062efd93383552b1a80c",
          "sha1": "c2481a2a4193fe8e0bbeba61d78ea9a7b811826f",
          "md5": "286e111cdf4aff6871c24c2207f47aa8"
        }
      ]
    }
  ]
}
