{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.18.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.18.jar",
          "size": 387934,
          "sha512": "f0ab6d6dace121066f10a6d8a8a3b248ecc73011944235851c5b1e6148327df53236f4313227a4a894cfad01b816a356fb03060987e56fab9303ac94ccbb7090",
          "sha256": "dda40510b1c678186a9284841d2593cea5f832c1474a5e3b442458c1b11aaf39",
          "sha1": "656142f34dccbea6db00751caefea151914ef7cf",
          "md5": "ffa0c9df965bf88786cb5dd1e4b12dcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.18.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.18.jar",
          "size": 387934,
          "sha512": "f0ab6d6dace121066f10a6d8a8a3b248ecc73011944235851c5b1e6148327df53236f4313227a4a894cfad01b816a356fb03060987e56fab9303ac94ccbb7090",
          "sha256": "dda40510b1c678186a9284841d2593cea5f832c1474a5e3b442458c1b11aaf39",
          "sha1": "656142f34dccbea6db00751caefea151914ef7cf",
          "md5": "ffa0c9df965bf88786cb5dd1e4b12dcd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.18-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.18-sources.jar",
          "size": 200184,
          "sha512": "1cf47a3378dc9a756ce9ae8dd5da6abdf66904cde7621c79c0644c1a6daa945825ffad350070115de28438facc66a14eb838afd27de5b81b21828d1283a2caec",
          "sha256": "72fc8ea48c4db3db4d8f2658197869a5e9df136cac1c22d94861155c16501928",
          "sha1": "d76ec11172d83dc5aa360b5d3d920eaca05ce495",
          "md5": "d103c46bc331d3a4b6bbfca0f51c329e"
        }
      ]
    }
  ]
}
