{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "size": 720513,
          "sha512": "fa834fe830ec84e0cdbb7e5391a1b90dfe928c4427e3f7b1d62394f1a106c43893fe44da90a39c7b1fc61c692ce4b703523d059a8b6643f6c085d78c317c44b3",
          "sha256": "06ea13e6bfd78097c9e5b8251b51a31d287f1526ba254bd61ffd3b67f8648313",
          "sha1": "a61e4e4f0f3d09ed931ac6c6dfe55e7a8d7d953e",
          "md5": "f6839f3e58cc64a62230ff626b1cbab5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "size": 720513,
          "sha512": "fa834fe830ec84e0cdbb7e5391a1b90dfe928c4427e3f7b1d62394f1a106c43893fe44da90a39c7b1fc61c692ce4b703523d059a8b6643f6c085d78c317c44b3",
          "sha256": "06ea13e6bfd78097c9e5b8251b51a31d287f1526ba254bd61ffd3b67f8648313",
          "sha1": "a61e4e4f0f3d09ed931ac6c6dfe55e7a8d7d953e",
          "md5": "f6839f3e58cc64a62230ff626b1cbab5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0-sources.jar",
          "size": 256711,
          "sha512": "d0e99eda363ee4af8bc31af4ca5111685d29f71512f46c33c9e091a5f14124d11143e3dfd5dfa8c53b8a622bf43ad83c04253a11d603f950c73648071a39ce73",
          "sha256": "a798b1d9a5ca5fc4f1de6e93459302642fcd67fcb244ec7ea1050aa0354af553",
          "sha1": "31d312b4209dc53afbec150ccd8f2bf21ae2fecb",
          "md5": "92c4cef9d5d92dab037822ab67e2e076"
        }
      ]
    }
  ]
}
