{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "size": 718717,
          "sha512": "c0d9fbd9fef21dfea19d2263769e81b90ce0cd0d374e08aa7e35093acc580b4fdce62329bf9d2953b3ca0c2f830a3c7a578acbeb00bdce8030e7c740b9322327",
          "sha256": "542c5b590e0d2f5ba2cc7d06a2bbae1d9770448dbd8fb559325cd01975e62dca",
          "sha1": "7402fb1e1d78a8f0d5f740b0234ab9bf31140726",
          "md5": "e6d9bb74a46473f2360feece267797af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "size": 718717,
          "sha512": "c0d9fbd9fef21dfea19d2263769e81b90ce0cd0d374e08aa7e35093acc580b4fdce62329bf9d2953b3ca0c2f830a3c7a578acbeb00bdce8030e7c740b9322327",
          "sha256": "542c5b590e0d2f5ba2cc7d06a2bbae1d9770448dbd8fb559325cd01975e62dca",
          "sha1": "7402fb1e1d78a8f0d5f740b0234ab9bf31140726",
          "md5": "e6d9bb74a46473f2360feece267797af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0-sources.jar",
          "size": 256252,
          "sha512": "b2b9f12753daac637d12044607f6e672c4a05aaa0b7350ce26e436dab842cb57a95570a04f2e9c1b86bddfdffd3aaa42ef7148591ff79957bf870eb6d7c815a2",
          "sha256": "6d17d36bfddd835940f48273e739b88ac0c6cb832fd917acefecf1006707d1d0",
          "sha1": "9ed1298375be486ad8c50480a400ecf8224ffca1",
          "md5": "c7e974f4b0db022deffaeabb8a85d38d"
        }
      ]
    }
  ]
}
