{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "size": 720292,
          "sha512": "03c8f72e1ae8579a8e250e82c64dc30ca5a8898d7010192808c54051352e634f56429354a5db391c91aede3ef1a415e7f8e2a75210327bb0a63fb55ed9605742",
          "sha256": "e443d925e5d5ef0efaebde4201c29034ce5e610c70716f8aa6b469b8e410d53a",
          "sha1": "06fab0933be7d32e71727e708b80a91506b1da3d",
          "md5": "d7af55e5468f5811c9404e8df137581a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0.jar",
          "size": 720292,
          "sha512": "03c8f72e1ae8579a8e250e82c64dc30ca5a8898d7010192808c54051352e634f56429354a5db391c91aede3ef1a415e7f8e2a75210327bb0a63fb55ed9605742",
          "sha256": "e443d925e5d5ef0efaebde4201c29034ce5e610c70716f8aa6b469b8e410d53a",
          "sha1": "06fab0933be7d32e71727e708b80a91506b1da3d",
          "md5": "d7af55e5468f5811c9404e8df137581a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2517.0-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2517.0-sources.jar",
          "size": 256514,
          "sha512": "2de0aefe0fbd6a6ffd211239a49ee67fd753080afb32a2463ed94c9f5bf8e8b6711e09ab5345c8e350af2adf28bd3bc419ec7a9abaeedd5d3997e8aa9dc387ed",
          "sha256": "b6c1a213b411c3009bde02175a07a908c09a5f35e5a0ac1220d66df00262bf06",
          "sha1": "54e450f4e49289e99ebb8a93e473be7767bc48d7",
          "md5": "a7c3dc210987cdc831254051aaa34a79"
        }
      ]
    }
  ]
}
