{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.10-2.2.7.2604.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2604.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2604.0.jar",
          "size": 551071,
          "sha512": "842eb1fbcb539efbd7d3e049379e2476a0b9df408250b00de1622423ac08d4b129ee108ae355d48fafc50d32db7a458b720830d855532917924e76508ccf347a",
          "sha256": "9f689a555c27d8bd1174c6336c43487c6282ed0e2fb9076dfed182bd85b6238c",
          "sha1": "a81c746f7155373a93ac694d81ea086d2d3c24b4",
          "md5": "33ad82d7d8fa440967f05601ee492e6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2604.0.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2604.0.jar",
          "size": 551071,
          "sha512": "842eb1fbcb539efbd7d3e049379e2476a0b9df408250b00de1622423ac08d4b129ee108ae355d48fafc50d32db7a458b720830d855532917924e76508ccf347a",
          "sha256": "9f689a555c27d8bd1174c6336c43487c6282ed0e2fb9076dfed182bd85b6238c",
          "sha1": "a81c746f7155373a93ac694d81ea086d2d3c24b4",
          "md5": "33ad82d7d8fa440967f05601ee492e6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.10-2.2.7.2604.0-sources.jar",
          "url": "factory_api-neoforge-1.21.10-2.2.7.2604.0-sources.jar",
          "size": 256181,
          "sha512": "3d65fa23b32076ccb9db0624ee1d1e8a471337747a6733b4a127bec5fd5085b56b05cad9132f694e97a04d2c575dfde60b0fd8af233ce85a48ae33388ead34af",
          "sha256": "23c55d906f34b1538c1d9b7bc8c7882ece3f2bc24ecceedad158cdb1c271dbd9",
          "sha1": "c3e53c51b72d82e4a36bb3a48efb4f96943b2637",
          "md5": "666b263c4fccfa69232050aa986e9109"
        }
      ]
    }
  ]
}
