{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.1-1.7.10.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2504.1.jar",
          "size": 14228161,
          "sha512": "e413fd3598e1747feb22938090beb429f870b6e5983d8dd5a3653afb404f9320999a39b01988003961298d33b56e32e45386b9e8c2dbfbe30bf3834bafdbe33c",
          "sha256": "960a67009bcda2edc61b6b3ddc03972be733b0cd859106a2801ba478820f8821",
          "sha1": "54f5c532fa98f7a5359578f2ef7d8681e6607c06",
          "md5": "88f2288efaac8950cda022e3e0377dc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.1-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2504.1.jar",
          "size": 14228161,
          "sha512": "e413fd3598e1747feb22938090beb429f870b6e5983d8dd5a3653afb404f9320999a39b01988003961298d33b56e32e45386b9e8c2dbfbe30bf3834bafdbe33c",
          "sha256": "960a67009bcda2edc61b6b3ddc03972be733b0cd859106a2801ba478820f8821",
          "sha1": "54f5c532fa98f7a5359578f2ef7d8681e6607c06",
          "md5": "88f2288efaac8950cda022e3e0377dc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.1-1.7.10.2504.1-sources.jar",
          "url": "legacy-forge-1.21.1-1.7.10.2504.1-sources.jar",
          "size": 13447313,
          "sha512": "609ddde40700eeb1d83618211060b16d03b0d1e9951b49fae0968eac02e16a085037b1ce929ba5de139d0173276d0288aac4d10b175a42b7624ef9f96fdbddd9",
          "sha256": "eaf24266769691e7401defa640aa7fe95af40cb90040479b13b18c70d0d8b955",
          "sha1": "32e8fde706839922960814c2c6d0b83115f4edba",
          "md5": "911157b6d282c8427947516935ed0181"
        }
      ]
    }
  ]
}
