{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.8.0.2512.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.1.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.1.jar",
          "size": 18241546,
          "sha512": "fefd33a953e686621726802316b3045785e53941dadefc5d12944e4db799d7ed86d98f781424955c8d79c7450702e2216684882a393d4eee3ea2aad00339fa17",
          "sha256": "f3374230d06398ea81dfbe1cded6b495c933544762a947ece7ee030252cae002",
          "sha1": "98a339926defab0484fbe32237bc5dda36d15c98",
          "md5": "c0b46b413f7960c3086fb452df310f91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.1.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.1.jar",
          "size": 18241546,
          "sha512": "fefd33a953e686621726802316b3045785e53941dadefc5d12944e4db799d7ed86d98f781424955c8d79c7450702e2216684882a393d4eee3ea2aad00339fa17",
          "sha256": "f3374230d06398ea81dfbe1cded6b495c933544762a947ece7ee030252cae002",
          "sha1": "98a339926defab0484fbe32237bc5dda36d15c98",
          "md5": "c0b46b413f7960c3086fb452df310f91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2512.1-sources.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2512.1-sources.jar",
          "size": 17412754,
          "sha512": "b7e5026d14ae999416e4eb89a9ace6f694273228f5bddca90852a28738c1935e6a63dbc56dfca092ec4611ea2306650505c7ad12a24379de15e189ab7bbb3839",
          "sha256": "2fce9aaedaf631acfb0927bc5127e7cb1bc960138cc3191dc6a07790847a7668",
          "sha1": "20345fb6f4ddd7f08edf46c3dac097244a08acfa",
          "md5": "679619b8c26c8fb5df403cf5a27aebc3"
        }
      ]
    }
  ]
}
