{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.3-1.8.0.2518.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2518.4.jar",
          "size": 19674945,
          "sha512": "eae97c740f8fa2009a4a2e0995fcc62569c8e0752478297feaf1e44480d3bf3b5917a674b031f31177b0611d779cb97c4e7bcb56e17af8d495368d9225c4d420",
          "sha256": "a84f090d238ac5d8a6b0d0ee244cac81c80d4a488625cb14d75664bb41ce20f8",
          "sha1": "602513fbab15920bf8bcb2a27071ef2d0ec1f52b",
          "md5": "0b50d3579d353c3148734cc1e9870728"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.1.9.075c033-66"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.3-2.2.3.2518.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2518.4.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2518.4.jar",
          "size": 19674945,
          "sha512": "eae97c740f8fa2009a4a2e0995fcc62569c8e0752478297feaf1e44480d3bf3b5917a674b031f31177b0611d779cb97c4e7bcb56e17af8d495368d9225c4d420",
          "sha256": "a84f090d238ac5d8a6b0d0ee244cac81c80d4a488625cb14d75664bb41ce20f8",
          "sha1": "602513fbab15920bf8bcb2a27071ef2d0ec1f52b",
          "md5": "0b50d3579d353c3148734cc1e9870728"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.3-1.8.0.2518.4-sources.jar",
          "url": "legacy-forge-1.21.3-1.8.0.2518.4-sources.jar",
          "size": 18818044,
          "sha512": "c15360687fe0cc7f38d1aab89f8bab1c104be1e5f043077990e764e1455045fab14296d009ed7fa4be1cd1f32911ed6b8831bbd21c4871db71c2adf4c0a10c20",
          "sha256": "ad558e1f246f61d138a105698560930e7cf89b912793d1a78a658621fcd433b8",
          "sha1": "f17ee949584ebdc6a1d9e30c97337ecb356e1464",
          "md5": "c0bd48bae92ca2d4a2f0c8febfa6f522"
        }
      ]
    }
  ]
}
