{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.5.2532.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.5.2532.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.5.2532.0.jar",
          "size": 520660,
          "sha512": "9fabdf8892a32e47a6ca5a3b367d63beba2ac645e61c8d29a90850fbd4c69fa2c77ca5aea46bfd957c59f1f2b962453b860b84cd9721c161e9c2b2b20e5ab051",
          "sha256": "65450657478aab08984a72bd34cdb212b7c734afc766b5e5281a6e332a5ffbe3",
          "sha1": "d2f331a3ecc2696b6a839f39b05d4dd1fd546160",
          "md5": "a29deea4e780ef03e55f4c5a4c42cbc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.5.2532.0.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.5.2532.0.jar",
          "size": 520660,
          "sha512": "9fabdf8892a32e47a6ca5a3b367d63beba2ac645e61c8d29a90850fbd4c69fa2c77ca5aea46bfd957c59f1f2b962453b860b84cd9721c161e9c2b2b20e5ab051",
          "sha256": "65450657478aab08984a72bd34cdb212b7c734afc766b5e5281a6e332a5ffbe3",
          "sha1": "d2f331a3ecc2696b6a839f39b05d4dd1fd546160",
          "md5": "a29deea4e780ef03e55f4c5a4c42cbc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.5.2532.0-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.5.2532.0-sources.jar",
          "size": 258739,
          "sha512": "1a7b4b5d4efe58af353aef586a5caa2a13596ddeb072f9ca0d36eb636f887064723520e74f36fd952f15d80f28272d2e0c884d881bbf710ea4739cf2c3282ce9",
          "sha256": "47a2e88f6b25ab10cd7cc03749fe0173177fc24755341b1161ec497d7d72adda",
          "sha1": "3267dfc4de7f7466544e75119b06d49048fb66fb",
          "md5": "f6612e2664590216c656e93c4a2ea97f"
        }
      ]
    }
  ]
}
