{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.4-1.7.10.2504.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.1.jar",
          "size": 14240925,
          "sha512": "70ef87b950d85da28bd50db826f65827de5bfce6ba6b52201ebde141c8e92e636f58a958f4de804e4f9ae6786494b54c3881f330708da9c47174ea53e1dfbd9a",
          "sha256": "ed088de6a18ce6fbb21716237fa73187d71551f39776245976bc79129c3bdff0",
          "sha1": "a4504f50261ee5171838e94c0889291b2cdabc69",
          "md5": "f6348b8bb0eb4181f9a6b8411a812e34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.4-2.2.2502.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.1.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.1.jar",
          "size": 14240925,
          "sha512": "70ef87b950d85da28bd50db826f65827de5bfce6ba6b52201ebde141c8e92e636f58a958f4de804e4f9ae6786494b54c3881f330708da9c47174ea53e1dfbd9a",
          "sha256": "ed088de6a18ce6fbb21716237fa73187d71551f39776245976bc79129c3bdff0",
          "sha1": "a4504f50261ee5171838e94c0889291b2cdabc69",
          "md5": "f6348b8bb0eb4181f9a6b8411a812e34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.4-1.7.10.2504.1-sources.jar",
          "url": "legacy-forge-1.20.4-1.7.10.2504.1-sources.jar",
          "size": 13453315,
          "sha512": "75c344c1e9e5bbf8ed6a1e1b6d25a414309a809b061eedca3131156eea3b99ad3d1147e5459e9fe3e463c83b935c68e90c0b2be0a68d69399b25052af1499062",
          "sha256": "0a5eb3e4d02a0e555534cb10ef99816f5f29440b6c99a2db1782e7a46cfc93c3",
          "sha1": "179d5bcd4de10b72e90faf3cfd309f0ea3da5b93",
          "md5": "1123dde249f1b1d438170d98cefd32f8"
        }
      ]
    }
  ]
}
