{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.21.3-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "size": 639100,
          "sha512": "4dfc5d71278a3b5d95e5699db88d1e4501a181faad12b6711d5dfa6121bef6ba44045b6423df57265a68d772ca321ccc43f1d978ac4be78cc540e01300a33d40",
          "sha256": "97b5ee3efc03ac1c72a3498d30849e97a5ca29c64a270170e2c5b5df263c572c",
          "sha1": "f283dc20d1d013cf253159462f1ecc67c52fd1b5",
          "md5": "af628056d27c83603c87a79795f779f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "size": 639100,
          "sha512": "4dfc5d71278a3b5d95e5699db88d1e4501a181faad12b6711d5dfa6121bef6ba44045b6423df57265a68d772ca321ccc43f1d978ac4be78cc540e01300a33d40",
          "sha256": "97b5ee3efc03ac1c72a3498d30849e97a5ca29c64a270170e2c5b5df263c572c",
          "sha1": "f283dc20d1d013cf253159462f1ecc67c52fd1b5",
          "md5": "af628056d27c83603c87a79795f779f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3-sources.jar",
          "size": 583652,
          "sha512": "11f1090538bfc40b55434e368364a5d575b6a3431b06e357c7347213037d3839350f0201b3385712a65e9b74da4ed6127d58a01d2b0e05f54c041eadfe435e52",
          "sha256": "fa641dafb8492d93e02a5db6bce2156cdc7fffb4722b0679b3da553cbaee7100",
          "sha1": "6900bc578bfb6609e03faaad25f7afe0bddd2e74",
          "md5": "c06fd267d046cef592a586bc2abfd868"
        }
      ]
    }
  ]
}
