{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-fabric",
    "version": "1.21.3-1.1.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "size": 636945,
          "sha512": "ba4bf346f89097f4496acb373737a64f2bb9bc7f258ec70cf37d871d2d7bdb5cf3ecfe9400e730efb88721c7b56d487bdeed1d34a4ceca98d3b75673ca91adda",
          "sha256": "28aad40b1e2e9da863f8ca746341bce226a167a6fea771011c47d308b52b2cb8",
          "sha1": "c48be575294fc05493a3d8a0436d463de7e30386",
          "md5": "341ba18cab7ed0061c5799cecbcab409"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.21.3-2.2.3.2516.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "url": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3.jar",
          "size": 636945,
          "sha512": "ba4bf346f89097f4496acb373737a64f2bb9bc7f258ec70cf37d871d2d7bdb5cf3ecfe9400e730efb88721c7b56d487bdeed1d34a4ceca98d3b75673ca91adda",
          "sha256": "28aad40b1e2e9da863f8ca746341bce226a167a6fea771011c47d308b52b2cb8",
          "sha1": "c48be575294fc05493a3d8a0436d463de7e30386",
          "md5": "341ba18cab7ed0061c5799cecbcab409"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3-sources.jar",
          "url": "betterfurnacesreforged-fabric-1.21.3-1.1.2516.3-sources.jar",
          "size": 582970,
          "sha512": "061996ecaf49709e090118fe40bda7db1d57b9b9fde4f21a16ec06cea92f68a4fe93f5e1530ea0b90027c3e1d73d34cdd3cdbf8f37737410bfc091e566e505cf",
          "sha256": "9cfa8d7bc3d78aa7a33b1f8b098ee5c2a6ee912d5c2fb3fea4cbfdfeab6e8afc",
          "sha1": "9392cf318037f88be08dc50591f0d3accf81ab7f",
          "md5": "316fe609026287987c85b16e2dfdcbc8"
        }
      ]
    }
  ]
}
