{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.11-2.2.7.2617.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.1.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.1.jar",
          "size": 561178,
          "sha512": "103125ed72f970fd061c46dfe7c91b5fccb30b8c83376a4fd484c2431e09a6caf05cbd85898cd5597cbdca0340f264ebfd4c32a65854a0ca3b936588862493b1",
          "sha256": "349ea1c623157357a107c6f263bd184d7d2be75240caad3346c83bfb69047676",
          "sha1": "755ca88d75472f29363a2de49b76df85085230cb",
          "md5": "e5b46c82e6e703a7454eb5b69646cec9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.1.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.1.jar",
          "size": 561178,
          "sha512": "103125ed72f970fd061c46dfe7c91b5fccb30b8c83376a4fd484c2431e09a6caf05cbd85898cd5597cbdca0340f264ebfd4c32a65854a0ca3b936588862493b1",
          "sha256": "349ea1c623157357a107c6f263bd184d7d2be75240caad3346c83bfb69047676",
          "sha1": "755ca88d75472f29363a2de49b76df85085230cb",
          "md5": "e5b46c82e6e703a7454eb5b69646cec9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.1-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.1-sources.jar",
          "size": 256714,
          "sha512": "0da91f7976531562d491fbc5a898481a4ce534d4d0a2aa97d4885212d0f105fdbf7d1318e34b1ca96f72b5b51c415d464e4b7ecbf7a331420e4c3ae45281120d",
          "sha256": "fe2008cc359cc0d45d94dd8905c1908a49547a892fc41327af4490e9d16ef571",
          "sha1": "bc8bcf3180a08fd7c0e3248288ef17e5d61c93d3",
          "md5": "9ee884f68001fa67d14ef5c24910c583"
        },
        {
          "name": "factory_api-neoforge-1.21.11-2.2.7.2617.1-sources.jar",
          "url": "factory_api-neoforge-1.21.11-2.2.7.2617.1-sources.jar",
          "size": 256714,
          "sha512": "0da91f7976531562d491fbc5a898481a4ce534d4d0a2aa97d4885212d0f105fdbf7d1318e34b1ca96f72b5b51c415d464e4b7ecbf7a331420e4c3ae45281120d",
          "sha256": "fe2008cc359cc0d45d94dd8905c1908a49547a892fc41327af4490e9d16ef571",
          "sha1": "bc8bcf3180a08fd7c0e3248288ef17e5d61c93d3",
          "md5": "9ee884f68001fa67d14ef5c24910c583"
        }
      ]
    }
  ]
}
