{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.10-1.8.5.2546.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.10-2.2.6.2545.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.10-1.8.5.2546.0.jar",
          "url": "legacy-forge-1.21.10-1.8.5.2546.0.jar",
          "size": 20120396,
          "sha512": "c8dbb7abde2c6b841daedbb4f6c27374b46b1cb2ec277c6fc91f12664ffd8b83dcb3373ab0a9751f0036865eaabdb0dd4b8ff46932ef241828cf158213e96ba1",
          "sha256": "4c1d72df6e4b5d1491e6c02215913b340f3fe575e4c5ca74176f3d47ecf50f75",
          "sha1": "3c6815abd948279ca47ebeab4872aea8b4b619f9",
          "md5": "70c5bccd347a6cb9c2f838fe44addd71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.2.18.release-3.2.18-79"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.10-2.2.6.2545.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.10-1.8.5.2546.0.jar",
          "url": "legacy-forge-1.21.10-1.8.5.2546.0.jar",
          "size": 20120396,
          "sha512": "c8dbb7abde2c6b841daedbb4f6c27374b46b1cb2ec277c6fc91f12664ffd8b83dcb3373ab0a9751f0036865eaabdb0dd4b8ff46932ef241828cf158213e96ba1",
          "sha256": "4c1d72df6e4b5d1491e6c02215913b340f3fe575e4c5ca74176f3d47ecf50f75",
          "sha1": "3c6815abd948279ca47ebeab4872aea8b4b619f9",
          "md5": "70c5bccd347a6cb9c2f838fe44addd71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.10-1.8.5.2546.0-sources.jar",
          "url": "legacy-forge-1.21.10-1.8.5.2546.0-sources.jar",
          "size": 19122028,
          "sha512": "65ebdb59ba4317a8f6e784d09209cb1c5dd863dfa476a5c987c3ad164ed3892d1c98ad81f1fd890d15728ed089c2e0f44f1717ceb979f8e8f4e71d4f41ae23ba",
          "sha256": "5b0b4fc57c7639e48da97a7ecf8c7bd023ccddd313715f1bb55124a9a4c823cc",
          "sha1": "e1cdb544ba6bbff9b22a8795b974ff21b258d564",
          "md5": "7252cbd5e87079adcf95b34b1fa6ea59"
        }
      ]
    }
  ]
}
