{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.betterfurnaces",
    "module": "betterfurnacesreforged-neoforge",
    "version": "1.21.4-1.1.2516.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.2.jar",
          "size": 645276,
          "sha512": "eab27e05b4c0817ef20a33d7a6a581ed5aec00e70e8810798819c847aacf0879df7450225c97b356b981ca9c0b6d792cc6883bfe89f667096bada80469518d97",
          "sha256": "64f5ddfebad08f5567afcb5f27fa8f2a312c6e66caae9664fff54ebd4ed642b7",
          "sha1": "270b905885bb0ab55fedb8b4d7fe647398b8a189",
          "md5": "345722632a094ee4f77faabc920ca3f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.3.2516.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.2.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.2.jar",
          "size": 645276,
          "sha512": "eab27e05b4c0817ef20a33d7a6a581ed5aec00e70e8810798819c847aacf0879df7450225c97b356b981ca9c0b6d792cc6883bfe89f667096bada80469518d97",
          "sha256": "64f5ddfebad08f5567afcb5f27fa8f2a312c6e66caae9664fff54ebd4ed642b7",
          "sha1": "270b905885bb0ab55fedb8b4d7fe647398b8a189",
          "md5": "345722632a094ee4f77faabc920ca3f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.2-sources.jar",
          "url": "betterfurnacesreforged-neoforge-1.21.4-1.1.2516.2-sources.jar",
          "size": 585784,
          "sha512": "90cb40226800ad99bc15f6b63bf83c7c1e8ce658612d0b08f92cefd0db630653a0ef190a721f6f49db2d9aeec3c31cff99427baf0cdeed7b82bc25999fae232e",
          "sha256": "8a2ff7b77326bdcef7e13e0147026ebf841ef8cc8dbaf9c7546e75d24ebf910e",
          "sha1": "11826e8e298a4ccc06efd458ed9040b35bcf47bb",
          "md5": "42cab559fd0b60fd7722c4abaf94b5d2"
        }
      ]
    }
  ]
}
