{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.7.2617.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.0.jar",
          "size": 555519,
          "sha512": "37f58d75a3957988778dc6e057c915627c34a40d7a9e0cdc888ee387dd49d59d0ad26280c9270be7dcf1c4a30ccc0c7feb81660693d6e4a6988f34571ee9eb53",
          "sha256": "6d62a5adb42fc4a449ffd39540f5ef740bc6c67666a5f447af27fb6059375d4b",
          "sha1": "7e17e963b8160227842e2ad48afd01d3d3bf2f9a",
          "md5": "a93976412a372d93b3f59f6b12053be9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.0.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.0.jar",
          "size": 555519,
          "sha512": "37f58d75a3957988778dc6e057c915627c34a40d7a9e0cdc888ee387dd49d59d0ad26280c9270be7dcf1c4a30ccc0c7feb81660693d6e4a6988f34571ee9eb53",
          "sha256": "6d62a5adb42fc4a449ffd39540f5ef740bc6c67666a5f447af27fb6059375d4b",
          "sha1": "7e17e963b8160227842e2ad48afd01d3d3bf2f9a",
          "md5": "a93976412a372d93b3f59f6b12053be9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.0-sources.jar",
          "size": 256771,
          "sha512": "ea32c2a29687fdb230705cb73dbd853ada2c92141997f5aaf98509f46b4eb63a4ffa29f626bcad88c28d59ca7c1cbafbced3fd47b5b2f88d37210b9596cbd00f",
          "sha256": "f47e77be04bcb33f3355e858df27187f4481e37a7413904735c650aa3b7d10f1",
          "sha1": "52e5d3b3c6b483346b3800851894a2ba32bf30fc",
          "md5": "c8d43ac52320fead659000bd910cce79"
        },
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2617.0-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2617.0-sources.jar",
          "size": 256771,
          "sha512": "ea32c2a29687fdb230705cb73dbd853ada2c92141997f5aaf98509f46b4eb63a4ffa29f626bcad88c28d59ca7c1cbafbced3fd47b5b2f88d37210b9596cbd00f",
          "sha256": "f47e77be04bcb33f3355e858df27187f4481e37a7413904735c650aa3b7d10f1",
          "sha1": "52e5d3b3c6b483346b3800851894a2ba32bf30fc",
          "md5": "c8d43ac52320fead659000bd910cce79"
        }
      ]
    }
  ]
}
