{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2500.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.5.jar",
          "size": 348947,
          "sha512": "18a2fe291d3df02d614d3705cca6d4ecf2b26aa8ce558be5b008ea11ff03ce354daee675bb64a42f57f8451f8406f24981897e453f90e0ea690b6ef02ad088cc",
          "sha256": "65f3a8e954e8beb5725d3b07a45a4f395c40f4e52e107888d54f3111f86d53fd",
          "sha1": "274e53a622451a8fec1d77bf03e77eb616a0ced9",
          "md5": "882e56c117bd1a878038e453238027db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.5.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.5.jar",
          "size": 348947,
          "sha512": "18a2fe291d3df02d614d3705cca6d4ecf2b26aa8ce558be5b008ea11ff03ce354daee675bb64a42f57f8451f8406f24981897e453f90e0ea690b6ef02ad088cc",
          "sha256": "65f3a8e954e8beb5725d3b07a45a4f395c40f4e52e107888d54f3111f86d53fd",
          "sha1": "274e53a622451a8fec1d77bf03e77eb616a0ced9",
          "md5": "882e56c117bd1a878038e453238027db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2500.5-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2500.5-sources.jar",
          "size": 193427,
          "sha512": "40dce8762438ffb5ed3d72dc63ea9b21f55813dcc6fb5a8951ce2283044820f83f36668d0e7f3f5428f8267dc07d492436e4a681a40c6c876789fc2a03adcc82",
          "sha256": "59a6f19cfa248442e9df640a8141c2d95f095f88c5e9c521805c18a98486bdd0",
          "sha1": "35f39815deedd3e66afadbf00d4f06e80b9d983c",
          "md5": "6f5d8c445fe4ff49f5763bd0fd11d50a"
        }
      ]
    }
  ]
}
