{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2504.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.3.jar",
          "size": 448950,
          "sha512": "c1c35f9536d43bb15e5c609e3ace1e89e0edb3020bbc5de04c72f14561f325edba6a70d9f92047b647dd4edda75e08d5cddd949101a2375bc9c6f67fda8f53bc",
          "sha256": "1aae57f41108cf7fb26c5c689861ad585996d88a9cf824883df48ada0a3e489c",
          "sha1": "836355ed3077bc9249e9dafeee168a95951d5d89",
          "md5": "d7089f91b28106af6cae96276d0cf60e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.3.jar",
          "size": 448950,
          "sha512": "c1c35f9536d43bb15e5c609e3ace1e89e0edb3020bbc5de04c72f14561f325edba6a70d9f92047b647dd4edda75e08d5cddd949101a2375bc9c6f67fda8f53bc",
          "sha256": "1aae57f41108cf7fb26c5c689861ad585996d88a9cf824883df48ada0a3e489c",
          "sha1": "836355ed3077bc9249e9dafeee168a95951d5d89",
          "md5": "d7089f91b28106af6cae96276d0cf60e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2504.3-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2504.3-sources.jar",
          "size": 231516,
          "sha512": "fbb65146d11505f6fa767a6a1b92a512805057f84e2e49e9bf8b24dc2474e9791fdc8d6552bafd75ec1408e67cf34716c65a0eb2344b22396789360d7c022378",
          "sha256": "7d8ca5bed46298d4ec87ada8fb567096cd5a574128182ed97fe631a8dbf13c28",
          "sha1": "73a3519126f7b4cdf9823b62efed1fa57d969751",
          "md5": "06ea814f90b1e80c8c4661c17c714cf8"
        }
      ]
    }
  ]
}
