{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.2507.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.1.jar",
          "size": 500321,
          "sha512": "8c4932c3c5ee3ce783eb620ad818bab25ed3d5688f873b032355c97fe45ac225f06c455cd1e766c36479ab3862b032ef13312a667c1e0dc5b593224026a7b0f3",
          "sha256": "443331076288776f206f0d455a28c4360af4065b9bab5f1614b710a624c77548",
          "sha1": "82e305e89aca2baaae670ee2a41136b44fe37769",
          "md5": "d92049a9440e5011a1a78ba29e39df97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.1.jar",
          "size": 500321,
          "sha512": "8c4932c3c5ee3ce783eb620ad818bab25ed3d5688f873b032355c97fe45ac225f06c455cd1e766c36479ab3862b032ef13312a667c1e0dc5b593224026a7b0f3",
          "sha256": "443331076288776f206f0d455a28c4360af4065b9bab5f1614b710a624c77548",
          "sha1": "82e305e89aca2baaae670ee2a41136b44fe37769",
          "md5": "d92049a9440e5011a1a78ba29e39df97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.2507.1-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.2507.1-sources.jar",
          "size": 243233,
          "sha512": "d8fec33c2559d150699755b5510743e58593f40c82afa939c54cb5cbfc00e4db51b8bcd03763bd16e68e3d1053b267b1d21427e795789f6c19c4c7777a65eb3f",
          "sha256": "ef7e99852e32852fa39b68915e7d214a311634ea697256ee3b69f599ec9c5885",
          "sha1": "8a07a8af138735074ad8406713b39a40048bf279",
          "md5": "e69d5f627010fa230bebdf886f1bdb98"
        }
      ]
    }
  ]
}
