{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.5-2.2.3.2516.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.3.jar",
          "size": 714365,
          "sha512": "fce06f6b21ecd405f2a18812252c33525f4841b59b0861d5150539366d2d68befa691a02ba549b257c862d3bf15bccba6624f1d95677119c2e21a004f63abbfc",
          "sha256": "a874121069f03640d2f8cb2e52adf007c03323c03212ba4a6586fc83f3a859c8",
          "sha1": "5bf98b503b60a60ec5e4c3201ce3c275dc1af65c",
          "md5": "7da9ce1add073d3eedc8f3b5eebdf4a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.3.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.3.jar",
          "size": 714365,
          "sha512": "fce06f6b21ecd405f2a18812252c33525f4841b59b0861d5150539366d2d68befa691a02ba549b257c862d3bf15bccba6624f1d95677119c2e21a004f63abbfc",
          "sha256": "a874121069f03640d2f8cb2e52adf007c03323c03212ba4a6586fc83f3a859c8",
          "sha1": "5bf98b503b60a60ec5e4c3201ce3c275dc1af65c",
          "md5": "7da9ce1add073d3eedc8f3b5eebdf4a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.5-2.2.3.2516.3-sources.jar",
          "url": "factory_api-forge-1.21.5-2.2.3.2516.3-sources.jar",
          "size": 254086,
          "sha512": "c17b8b204cbbcf05cb58a2b20c98771a7ad9df9d42c83750963bd2e293171d7a6acc9a77d6714d1146b9d1281553501a1b457fd663f280097b80f6f06ad00307",
          "sha256": "1304ab5c60fb76ee9070d90a7ed16a5177f7cf77a74224eb30e1df5aa965f7d6",
          "sha1": "c81614462f413a037a9c4176ef4e6348731cf146",
          "md5": "3421df9a3392ca371b74b615685b8bf5"
        }
      ]
    }
  ]
}
