{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.5-2.2.3.2514.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.21.5-2.2.3.2514.2.jar",
          "size": 555533,
          "sha512": "ca0de0e7356c4b62dba51e96f895882a3d5c7e318b5295609b76aea5c80df1dcf63fdf8eee324b12755652cf49e7411ba80c604231188ff2d61a2cff3abfca27",
          "sha256": "b75e0107784142c5b981957f33b0d900b111f69f844d0aa6324a8dd7e4a888dd",
          "sha1": "429c8f038ada16428abe1863f930ee743823f0a1",
          "md5": "914c3394cffddd0af6fe56e9e4d6210d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.5+1.21.5"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "14.0.0-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.3.2514.2.jar",
          "url": "factory_api-fabric-1.21.5-2.2.3.2514.2.jar",
          "size": 555533,
          "sha512": "ca0de0e7356c4b62dba51e96f895882a3d5c7e318b5295609b76aea5c80df1dcf63fdf8eee324b12755652cf49e7411ba80c604231188ff2d61a2cff3abfca27",
          "sha256": "b75e0107784142c5b981957f33b0d900b111f69f844d0aa6324a8dd7e4a888dd",
          "sha1": "429c8f038ada16428abe1863f930ee743823f0a1",
          "md5": "914c3394cffddd0af6fe56e9e4d6210d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.5-2.2.3.2514.2-sources.jar",
          "url": "factory_api-fabric-1.21.5-2.2.3.2514.2-sources.jar",
          "size": 251173,
          "sha512": "64e7e3c32411a1c44aa8ae8c9e3ef0981b49bb5ba32fedf9ab984eef3f2490a422f12c296bb78edc035a46d6e4884934f2a3598201f9cd14680ad8135fb15d65",
          "sha256": "f004020bc858ea12bf8ba9ee9b6b50fd4a3d1a344455429b6baa394bb405c124",
          "sha1": "e4e77895d814db64dedddef311f9b9e0663ac5ce",
          "md5": "03afeef87f9c81b6c3e9dab174bbe2f1"
        }
      ]
    }
  ]
}
