{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2508.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.0.jar",
          "size": 493064,
          "sha512": "c8c54c51e6608a41759bf5586891f7fe0557cb5d27434d895a58a7f306d344ab44d68cde0df42be6d4227901b96d0d032ad2530882af8f4e53af1d075e435e7d",
          "sha256": "07d029964646120c1e8b40af122472e8a69ce5f7ac6fcdf1d642a268bec57bea",
          "sha1": "e9c3bf2b86ad4e16ad1c5ae91e3f4a5fa1f98049",
          "md5": "1cd56ae8e150bfb82f9979d3b06be8e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.0.jar",
          "size": 493064,
          "sha512": "c8c54c51e6608a41759bf5586891f7fe0557cb5d27434d895a58a7f306d344ab44d68cde0df42be6d4227901b96d0d032ad2530882af8f4e53af1d075e435e7d",
          "sha256": "07d029964646120c1e8b40af122472e8a69ce5f7ac6fcdf1d642a268bec57bea",
          "sha1": "e9c3bf2b86ad4e16ad1c5ae91e3f4a5fa1f98049",
          "md5": "1cd56ae8e150bfb82f9979d3b06be8e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2508.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2508.0-sources.jar",
          "size": 249524,
          "sha512": "4727273bdad2b151e9b9f3a220ae7b93c7084dbba608ef373e99a16fefcff3328efd52593e3d44851c4df7fb19aaf6e2045b078c02510387306e03121d8e5c99",
          "sha256": "a79965279352f15e45b96b311c766e8ea7494a2e394b5405d14c6fd4e16cca41",
          "sha1": "b3b3ce784b81976af5dc1548f03c0ab4b472e5f9",
          "md5": "d22734072ebbdb8d42122c862d62e642"
        }
      ]
    }
  ]
}
