{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.1.jar",
          "size": 349489,
          "sha512": "5c0c814947efe672c686be107a9804f810d06fd5881bef70f1f32eda315cdbe6c14814e12098f8b5c8113094a22c54b51bf0b52c89ac318111b61cfeeca92ee7",
          "sha256": "dfb0e23616de1a685eb25514176bdddefa475f8e2ff25657b79f708a9298fee7",
          "sha1": "2d570266771a0130f67b0fd9fcbfed651f575c8c",
          "md5": "02d306d7bc17b47594034d6e030fc876"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.1.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.1.jar",
          "size": 349489,
          "sha512": "5c0c814947efe672c686be107a9804f810d06fd5881bef70f1f32eda315cdbe6c14814e12098f8b5c8113094a22c54b51bf0b52c89ac318111b61cfeeca92ee7",
          "sha256": "dfb0e23616de1a685eb25514176bdddefa475f8e2ff25657b79f708a9298fee7",
          "sha1": "2d570266771a0130f67b0fd9fcbfed651f575c8c",
          "md5": "02d306d7bc17b47594034d6e030fc876"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.1-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.1-sources.jar",
          "size": 193462,
          "sha512": "efa7ed399337971085dec8dfc5ca2530bb3e1cf7f543ea508dbcd8a4430e763056d3fad10bdff32fcea2854e72e27cb5e2665f3489a01e83a50d3184914a3770",
          "sha256": "c13b1270751a09abad8912045ed5b43557b2ea9c40a4b8cf455977c698f564c4",
          "sha1": "428de80c8f55c34dbc2fc658f4ac98c64358abc3",
          "md5": "47d1d0536ef62ac842a987fd5cd62357"
        }
      ]
    }
  ]
}
