{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "size": 715823,
          "sha512": "a88510c5f5144084502f75bfd9a31ac62604396ba7b4018b141258dc87c2b2fcb9770ae7edede97d81daefd3b4698f096cacebb11cd041397748a339361129cf",
          "sha256": "34a7b21033d9603c887a1879eca4f07dcdfb316f6d167d46a5176662ef827add",
          "sha1": "d2bca7d979cfae4c808e41ecb8b96c660d0174ba",
          "md5": "f945d7d8117b4f2cf6fe17be56625f71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "size": 715823,
          "sha512": "a88510c5f5144084502f75bfd9a31ac62604396ba7b4018b141258dc87c2b2fcb9770ae7edede97d81daefd3b4698f096cacebb11cd041397748a339361129cf",
          "sha256": "34a7b21033d9603c887a1879eca4f07dcdfb316f6d167d46a5176662ef827add",
          "sha1": "d2bca7d979cfae4c808e41ecb8b96c660d0174ba",
          "md5": "f945d7d8117b4f2cf6fe17be56625f71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2516.1-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2516.1-sources.jar",
          "size": 255548,
          "sha512": "5c4c1d890ed1c1321908cc7415b859d15f29c9c99fe332049ca5e20b2e2e6d03bb5be3115829db420b0f5cd2466964a74b77bd1d2e2d5bbf51976b1013e10174",
          "sha256": "325f8f8d166c147dfd366ff4ad71e9604ff58a6292c2dfbca78e2a2f945e87b7",
          "sha1": "0185ba3d3d5939174a4a3a5e76a2b4032443d9f3",
          "md5": "5a6a7db5a3712bdef1bcfd840de5922d"
        }
      ]
    }
  ]
}
