{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.1-2.2.3.2516.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "size": 715592,
          "sha512": "4fcddeea1c32253c42c1b6bd6de577d8cf7b3e82544ce74850975edad41355b4ec439a98bfaf905bdb77ba11f80583191fd0f85823e0356a2a43d3265f66f185",
          "sha256": "9afbb9606452f24ea51a8dd3cc9114308a1f432a462fae508ff6c63ed1367174",
          "sha1": "4df1876e045c9815f1d019bde80fb59e8137ad84",
          "md5": "d95364236a77031d309b0e1c1e963405"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2516.1.jar",
          "size": 715592,
          "sha512": "4fcddeea1c32253c42c1b6bd6de577d8cf7b3e82544ce74850975edad41355b4ec439a98bfaf905bdb77ba11f80583191fd0f85823e0356a2a43d3265f66f185",
          "sha256": "9afbb9606452f24ea51a8dd3cc9114308a1f432a462fae508ff6c63ed1367174",
          "sha1": "4df1876e045c9815f1d019bde80fb59e8137ad84",
          "md5": "d95364236a77031d309b0e1c1e963405"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.1-2.2.3.2516.1-sources.jar",
          "url": "factory_api-forge-1.20.1-2.2.3.2516.1-sources.jar",
          "size": 255461,
          "sha512": "2f8221de04971f38c086e00b065a3e5094feccda88e2840808715facacc10d130cd3c5b4baadd82fe3d9e8b351293d73d68d38f2eea30f630b6d0fa1bf9249c5",
          "sha256": "20bbdfc05a32e44aabb27200dc06d5ac7531c66bcf43e81c2602ef1553894647",
          "sha1": "333f5284960213e8f001cd7ee223c49db6d08742",
          "md5": "d9093ea9e22f4402e2577a31c529c005"
        }
      ]
    }
  ]
}
