{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.7.2617.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2617.3.jar",
          "size": 548517,
          "sha512": "60004ae69e2e098ead9c42285a8ff63373df39614e61c444cabb5362cea66ee19d8525fe2095695c0d939f4e245cc41a16f9f0c8f07f4b5045518171c30bfcbd",
          "sha256": "0cef2212358409f141821f2f9abaaa074de48dd9a9d6bd95e9627d3d3fc97db1",
          "sha1": "91d358331d410f4c0080d3767a74a427c9e2e52e",
          "md5": "119d69a3af050edf6ab79b5f62bba1e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2617.3.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2617.3.jar",
          "size": 548517,
          "sha512": "60004ae69e2e098ead9c42285a8ff63373df39614e61c444cabb5362cea66ee19d8525fe2095695c0d939f4e245cc41a16f9f0c8f07f4b5045518171c30bfcbd",
          "sha256": "0cef2212358409f141821f2f9abaaa074de48dd9a9d6bd95e9627d3d3fc97db1",
          "sha1": "91d358331d410f4c0080d3767a74a427c9e2e52e",
          "md5": "119d69a3af050edf6ab79b5f62bba1e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2617.3-sources.jar",
          "size": 256760,
          "sha512": "a6f5714dee6a71d082c4930cf411520415f9560571da3d05d2feb1a2824084eee2f13e96f13d9b5988a78e7652b78c11de6921e901acbeba8a2ca2802942e97d",
          "sha256": "95d43d84cacd711c3f5e1f7651f36ce8cf4880304fdbea7391f9fea484f5b3f3",
          "sha1": "7a3c91398e0bf136ab1fdbe10cfa465e4e8d3ef3",
          "md5": "9a4095c67b96cfdcfc88ff4264b92416"
        },
        {
          "name": "factory_api-neoforge-1.21.3-2.2.7.2617.3-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.7.2617.3-sources.jar",
          "size": 256760,
          "sha512": "a6f5714dee6a71d082c4930cf411520415f9560571da3d05d2feb1a2824084eee2f13e96f13d9b5988a78e7652b78c11de6921e901acbeba8a2ca2802942e97d",
          "sha256": "95d43d84cacd711c3f5e1f7651f36ce8cf4880304fdbea7391f9fea484f5b3f3",
          "sha1": "7a3c91398e0bf136ab1fdbe10cfa465e4e8d3ef3",
          "md5": "9a4095c67b96cfdcfc88ff4264b92416"
        }
      ]
    }
  ]
}
