{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.7.2604.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2604.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2604.0.jar",
          "size": 524273,
          "sha512": "9453ded526417bfd426cc88c75b703a42f579b47ad5beefefe7e0d0611f5ee8ad4e54909d166c174ccd8fed8578541ccbac5b081a6ed881d9fe95343bb218417",
          "sha256": "8e4cdf4a259f28dcdc9f90b0c0ac463b34fbf054ae6dded0b5771e109baee9b3",
          "sha1": "39b8bea3bc808f026c1e2e3ad84e47c3bd736b12",
          "md5": "2e3e8b8e6391364abc964e53149ff383"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2604.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2604.0.jar",
          "size": 524273,
          "sha512": "9453ded526417bfd426cc88c75b703a42f579b47ad5beefefe7e0d0611f5ee8ad4e54909d166c174ccd8fed8578541ccbac5b081a6ed881d9fe95343bb218417",
          "sha256": "8e4cdf4a259f28dcdc9f90b0c0ac463b34fbf054ae6dded0b5771e109baee9b3",
          "sha1": "39b8bea3bc808f026c1e2e3ad84e47c3bd736b12",
          "md5": "2e3e8b8e6391364abc964e53149ff383"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.2604.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.2604.0-sources.jar",
          "size": 256060,
          "sha512": "9ad46f0b84304e719612aaaa509e9af80bd4110c55be462fce5390c485d3e03acbc5cc39f447b239891fb95336ee1b7c322572f0ba7d61ee8c7ab12570cd1001",
          "sha256": "742d36e2e55809dd04aa164aecc3658e1482a803198c236018fa7410afda2ec7",
          "sha1": "946c5891211d9ae67d6e6bfe36869d7c088960c3",
          "md5": "5b9eb55a460b5d84044012f658cef12c"
        }
      ]
    }
  ]
}
