{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2515.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2515.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2515.1.jar",
          "size": 525454,
          "sha512": "13d54a3336ff1e0184659d97ccac1ec5f012abf64bc6d8fbfc724a23dc2afb5f6f9be8846aa9cbcd3697e5d9473d7c128e98f103410ec936c383dd39514a4fde",
          "sha256": "d487571a2a9ddbf8939447a2984ee01472892e80a50b44f6ae7a14e3564a89f9",
          "sha1": "979b9fccb2b063430efe28a3008d8b41c1b21640",
          "md5": "20389e6e05d068866740a0a760be22c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2515.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2515.1.jar",
          "size": 525454,
          "sha512": "13d54a3336ff1e0184659d97ccac1ec5f012abf64bc6d8fbfc724a23dc2afb5f6f9be8846aa9cbcd3697e5d9473d7c128e98f103410ec936c383dd39514a4fde",
          "sha256": "d487571a2a9ddbf8939447a2984ee01472892e80a50b44f6ae7a14e3564a89f9",
          "sha1": "979b9fccb2b063430efe28a3008d8b41c1b21640",
          "md5": "20389e6e05d068866740a0a760be22c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2515.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2515.1-sources.jar",
          "size": 253292,
          "sha512": "c95b8f314f4be5f1e4a94a2a5a037d988fc9e0462059c2cb90b9d6ed8d2e28008f04f41b41c4037cbf6541032897c2e70edc7b77c2a429de34068712354c3849",
          "sha256": "ed413ff9de3c32d7efc45209af41542ad7470e232eb3e694a3728b97bcc2d019",
          "sha1": "a856fd8a569893f4311872f93830155124950f15",
          "md5": "03f1d7704bdc119a23d6384961bd0901"
        }
      ]
    }
  ]
}
