{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2501.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.19.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.19.jar",
          "size": 392640,
          "sha512": "bf95ff9e765fdbc9847751aa85174864446d82bb137dffc82e5bccbc43005978bbd7271fad0d123140f1e7d2d8906f7997ea6fef2a9e3b49b66df4da4ebb96a1",
          "sha256": "df9718adde4d532252af54aa1087ab2e86c95c4df7729c219475bfbaea04a54d",
          "sha1": "2f9ca18cd07a439f84dc76cd2a7a39f297a8d834",
          "md5": "ad8a51f71351d271754b0195c3f2aec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.19.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.19.jar",
          "size": 392640,
          "sha512": "bf95ff9e765fdbc9847751aa85174864446d82bb137dffc82e5bccbc43005978bbd7271fad0d123140f1e7d2d8906f7997ea6fef2a9e3b49b66df4da4ebb96a1",
          "sha256": "df9718adde4d532252af54aa1087ab2e86c95c4df7729c219475bfbaea04a54d",
          "sha1": "2f9ca18cd07a439f84dc76cd2a7a39f297a8d834",
          "md5": "ad8a51f71351d271754b0195c3f2aec8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2501.19-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2501.19-sources.jar",
          "size": 200825,
          "sha512": "ab838ed31a011359197149ba0dff3453f12f7b96a7ae2db9635c34d902159e9717a7551ad570808cc66e3c231184a3a99123986886e2781c5030299ab0b5a32e",
          "sha256": "ec2056ce656d258a89dd33fb68e25adb0bc4aac60468baf00b82c9132522306c",
          "sha1": "abef95ab8b20a1b119c6fc4db712a74350c2da3e",
          "md5": "b9d0a0d0d9920e27322265f1ab8edf0c"
        }
      ]
    }
  ]
}
