{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.3.2513.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2513.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2513.1.jar",
          "size": 511450,
          "sha512": "2e46abbd4ab6b43573de4ab09b5927c31c09daa8dbdb84250a6c7de2aef44b0837a2c8b1b5b84115922f68af096117b1518476f65f7dc88cfdbd72e0df4fa448",
          "sha256": "292755a3a1848c4c793e2a0e787dacfeab0634c2b0dadbb4a7ffde601864a0ab",
          "sha1": "d52d5383d7ebc47e8fb2b645134994e0012f7af4",
          "md5": "659db3676e8677af2b506ee653306922"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2513.1.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2513.1.jar",
          "size": 511450,
          "sha512": "2e46abbd4ab6b43573de4ab09b5927c31c09daa8dbdb84250a6c7de2aef44b0837a2c8b1b5b84115922f68af096117b1518476f65f7dc88cfdbd72e0df4fa448",
          "sha256": "292755a3a1848c4c793e2a0e787dacfeab0634c2b0dadbb4a7ffde601864a0ab",
          "sha1": "d52d5383d7ebc47e8fb2b645134994e0012f7af4",
          "md5": "659db3676e8677af2b506ee653306922"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.3.2513.1-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.3.2513.1-sources.jar",
          "size": 250778,
          "sha512": "7315866800297874fc9af756543a2aba4f36874f0abd4358d1076773df8338d90a10c748ecdceb6048fbae4ff8a1d5abfe9e568e71529ab855a22c04c30d61f5",
          "sha256": "8d279ee32b93da4007ef849f31d8b6036f26ffa7f0d86a5c133b460b9f4a9826",
          "sha1": "1edffcb40aac75e40ab4a568cf962bba86eee5a9",
          "md5": "9a336d37c1aeab2f160eeeadf0405c7e"
        }
      ]
    }
  ]
}
