{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-fabric",
    "version": "1.21.4-2.2.3.2510.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2510.4.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2510.4.jar",
          "size": 548438,
          "sha512": "d39168d283cc417f2e98f72dc10c17d48faf579a631b09c35c902cc0d9460a790d8f7d39febe54631fdaaeef869e55019f69f710e1ee4438588b7b0ddc9fe934",
          "sha256": "9afc75dc080c35546ea55f51d0ca84a15430914ea241445b357c748a1623a250",
          "sha1": "e603df675bf6161297510c2c3ea2a84c4b645ed6",
          "md5": "a9b442725a5da2f8afc2cd8337d91e0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.112.1+1.21.4"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2510.4.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2510.4.jar",
          "size": 548438,
          "sha512": "d39168d283cc417f2e98f72dc10c17d48faf579a631b09c35c902cc0d9460a790d8f7d39febe54631fdaaeef869e55019f69f710e1ee4438588b7b0ddc9fe934",
          "sha256": "9afc75dc080c35546ea55f51d0ca84a15430914ea241445b357c748a1623a250",
          "sha1": "e603df675bf6161297510c2c3ea2a84c4b645ed6",
          "md5": "a9b442725a5da2f8afc2cd8337d91e0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-fabric-1.21.4-2.2.3.2510.4-sources.jar",
          "url": "factory_api-fabric-1.21.4-2.2.3.2510.4-sources.jar",
          "size": 249235,
          "sha512": "ccf5b55efeb1cf497f333d2ce1cd7b92e8fec1f9b80c5729f1ecc66fb237142342061f3627749a5de466bbb356d5703c7997d8526a58129dcc119c99872050c0",
          "sha256": "dcdaec09602f5f7c497ad5c632e9fe4893cb3b1d11c473b4feccbd845cafaa85",
          "sha1": "15c5c31ba6da8cecd182212f0f4099e9a40e2ae0",
          "md5": "17e9458c8985bb22367df3539e6d2ec8"
        }
      ]
    }
  ]
}
