{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2507.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2507.8.jar",
          "size": 478551,
          "sha512": "03b08934b93aaca90024ab04ad264921f559760f9f824e3e6e2d74f6ecee9da782f27b1f18d31778e1c8d55f07c9ca65989d1cf4731710424feb38b3d7e4cbb8",
          "sha256": "9f8e422d94e62d1a023136f830258f6a8977def6db939a4405c002795a78855c",
          "sha1": "d638a1b28beae8e952b5aefbf81bd5670af09cc7",
          "md5": "b43d0699d8400d618b0bf8a392024837"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2507.8.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2507.8.jar",
          "size": 478551,
          "sha512": "03b08934b93aaca90024ab04ad264921f559760f9f824e3e6e2d74f6ecee9da782f27b1f18d31778e1c8d55f07c9ca65989d1cf4731710424feb38b3d7e4cbb8",
          "sha256": "9f8e422d94e62d1a023136f830258f6a8977def6db939a4405c002795a78855c",
          "sha1": "d638a1b28beae8e952b5aefbf81bd5670af09cc7",
          "md5": "b43d0699d8400d618b0bf8a392024837"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2507.8-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2507.8-sources.jar",
          "size": 244563,
          "sha512": "4e56b9aa93a4b0ac571280728712e10a49ecc22c851d672e58ce668fa5b45344bee97c6d8d9427bc20a190c934558e208347c457ce11a06604a5a08ab7d62036",
          "sha256": "31bb4f5d74c3b6bf9ffc104a5d00011288f59d87edd41741934cd38a88fd2cce",
          "sha1": "38fda80ae106e1d19f12cb850bbd1aa187845c00",
          "md5": "a05b7d40e8aac352e5587333e03547fe"
        }
      ]
    }
  ]
}
