{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.24.jar",
          "size": 380461,
          "sha512": "ad91d117aa3413564a3fe2008ef0c37d1818e532638859a9a1241fe76e7ced2f60916cd8e965a6759b5921c40ff5535f5dc4dc9f0facec21e91bb520e8927861",
          "sha256": "c8013b80e76510a16c4bc2bf7ee7b22b652399ac1a5718fd6647fbfd3f3d1c46",
          "sha1": "6800d5f7336efa60334445e38007ce53971d06c1",
          "md5": "feab7720e0f622242ff0b1694b4531aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.24.jar",
          "size": 380461,
          "sha512": "ad91d117aa3413564a3fe2008ef0c37d1818e532638859a9a1241fe76e7ced2f60916cd8e965a6759b5921c40ff5535f5dc4dc9f0facec21e91bb520e8927861",
          "sha256": "c8013b80e76510a16c4bc2bf7ee7b22b652399ac1a5718fd6647fbfd3f3d1c46",
          "sha1": "6800d5f7336efa60334445e38007ce53971d06c1",
          "md5": "feab7720e0f622242ff0b1694b4531aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.2501.24-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.2501.24-sources.jar",
          "size": 197531,
          "sha512": "e93cd221d9e95dd42286acaef5f0475dcfa85ba0aeed7c8f28b6cdb0c818aa1b0a6dc6ac215931f670da576c231d8b6ba77f08d1e54b7fdaa4a2a326aeaf934c",
          "sha256": "46f0668b99f30ba8f101182d486f50a30c092179efbf280dd4f54594e4be4bef",
          "sha1": "a00bcd78a643da135f9cbae4de25d19b485e8b9f",
          "md5": "0b2e23551a4486ee559f9d1b93ba9d8e"
        }
      ]
    }
  ]
}
