{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.5-2.2.3.2517.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2517.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2517.0.jar",
          "size": 530692,
          "sha512": "9137b096ac80d32c5204d009420034ff8d0db23d3b53decddd7fd2ec6058815493ee6ec018a6df1acb40313bd24bfa9c2c6b17f4f4f4580edabf4523e7884e0a",
          "sha256": "215c0d2dd92e2b68dc90a0240949460856e1149ad3cb03f53d6cdc46cabb0d9d",
          "sha1": "3fcaa737a98cff8358be3481df6f17ee88b92630",
          "md5": "360358db27f9b0ec35c20ad6257ff536"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2517.0.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2517.0.jar",
          "size": 530692,
          "sha512": "9137b096ac80d32c5204d009420034ff8d0db23d3b53decddd7fd2ec6058815493ee6ec018a6df1acb40313bd24bfa9c2c6b17f4f4f4580edabf4523e7884e0a",
          "sha256": "215c0d2dd92e2b68dc90a0240949460856e1149ad3cb03f53d6cdc46cabb0d9d",
          "sha1": "3fcaa737a98cff8358be3481df6f17ee88b92630",
          "md5": "360358db27f9b0ec35c20ad6257ff536"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.5-2.2.3.2517.0-sources.jar",
          "url": "factory_api-neoforge-1.21.5-2.2.3.2517.0-sources.jar",
          "size": 254377,
          "sha512": "775ffbf072585ce5048568ebadcf49da0907747eae49518e97883803744679352a167a26f2c8ee3c5ee633a0ab881e297da13718da6ece967a529311e8c6c6f4",
          "sha256": "878e7f638076806f96607aac2406b7664c9d3eca0562d10d9e797dae8ec8d3e9",
          "sha1": "e3a3985c260e71c8161979a5f04c86165f7d682d",
          "md5": "99ff26fbe17b4e5c049edbd1add56d2f"
        }
      ]
    }
  ]
}
