{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.jar",
          "size": 495831,
          "sha512": "d3e7fd62e7c0e6472c5a2c3c6d15110ebc55f0d44b1c7ac5da005cb4052e8850f4b505fbd3b4bf3afe5d0e7ea1ffee730c100136fdb4c6ff782485ffa724543e",
          "sha256": "304c73c426110f127525dacfaa8f1dc1306f8127a0fc2fd857a61024c03e7d82",
          "sha1": "d777c34b82c3a616380a008b56ddcc53db071583",
          "md5": "f5b7d90c34a2968f45f2d5d95a51a346"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.jar",
          "size": 495831,
          "sha512": "d3e7fd62e7c0e6472c5a2c3c6d15110ebc55f0d44b1c7ac5da005cb4052e8850f4b505fbd3b4bf3afe5d0e7ea1ffee730c100136fdb4c6ff782485ffa724543e",
          "sha256": "304c73c426110f127525dacfaa8f1dc1306f8127a0fc2fd857a61024c03e7d82",
          "sha1": "d777c34b82c3a616380a008b56ddcc53db071583",
          "md5": "f5b7d90c34a2968f45f2d5d95a51a346"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3-sources.jar",
          "size": 248370,
          "sha512": "1c8c28f4e6bb424a80920cb01bd945128606dfe816128cd62e4a5682655c235f5127036ec2555b19f9d1447f83bbedcf18894d28c9bd06760464c2e02da06636",
          "sha256": "2356de24ad7819dc8a6338ba25cee6d7cf492bc533004e92fa53e16f4e919a90",
          "sha1": "74a09e1f6715579e6aa18cd519b86054a9b7fd0b",
          "md5": "4c9681da08565a820151d3c7c7267aef"
        }
      ]
    }
  ]
}
