{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2514.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2514.1.jar",
          "size": 688993,
          "sha512": "befd6e81f13762f094ccae94f7c1c1f06cd322a5906a600590eb63756895fdecf3e972075244503db9c088484527cd674c92099a662f0ff6fe0999f89ce1a4d3",
          "sha256": "4b5f10433ad8108b80bb7eb280e7c376f351ba442576a0ec501ea4a3e093356d",
          "sha1": "ccdc5af9af4c7a43cd2e8c41ee3bacc5b0ad0d2d",
          "md5": "c73f08aca90b7975a1a0c261897ae251"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2514.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2514.1.jar",
          "size": 688993,
          "sha512": "befd6e81f13762f094ccae94f7c1c1f06cd322a5906a600590eb63756895fdecf3e972075244503db9c088484527cd674c92099a662f0ff6fe0999f89ce1a4d3",
          "sha256": "4b5f10433ad8108b80bb7eb280e7c376f351ba442576a0ec501ea4a3e093356d",
          "sha1": "ccdc5af9af4c7a43cd2e8c41ee3bacc5b0ad0d2d",
          "md5": "c73f08aca90b7975a1a0c261897ae251"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2514.1-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2514.1-sources.jar",
          "size": 254152,
          "sha512": "080b9e33b2295880e6bb996918c3207c8bbf6ffb88ff813090609c2d57f633cc4fb96d35c70ee98961f03cebff4dce16dcd89545739881ce9719376883e9e539",
          "sha256": "8a8bc7d98c8196d53af3fa860028db866ec2da096b0671ee9440cf1a5df55b32",
          "sha1": "b21405bc450c9563dc096bfee8c9f8a3ad430dd2",
          "md5": "83d11cdf4250dd77ea6eb3500e2e300e"
        }
      ]
    }
  ]
}
