{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-fabric",
    "version": "1.20.1-1.8.0.2511.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2511.1.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2511.1.jar",
          "size": 18213269,
          "sha512": "5cc624937a76d49efcc74aa0529a9073060a9644737c51e04d65a08a87fc798d2dfc3c1cd493b82fad1627d8035d0ffd21c90708a3295cc6c983e1edbf59bd7a",
          "sha256": "a597564aaf0940126ca9f9041c949c9a33bb4f93c1bb0cce8f1e36f33a247567",
          "sha1": "965f0ada4373cac597f3bb7b12d1b03956745246",
          "md5": "b944768482449492cdf68b029ad6427f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-fabric",
          "version": {
            "requires": "1.20.1-2.2.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2511.1.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2511.1.jar",
          "size": 18213269,
          "sha512": "5cc624937a76d49efcc74aa0529a9073060a9644737c51e04d65a08a87fc798d2dfc3c1cd493b82fad1627d8035d0ffd21c90708a3295cc6c983e1edbf59bd7a",
          "sha256": "a597564aaf0940126ca9f9041c949c9a33bb4f93c1bb0cce8f1e36f33a247567",
          "sha1": "965f0ada4373cac597f3bb7b12d1b03956745246",
          "md5": "b944768482449492cdf68b029ad6427f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-fabric-1.20.1-1.8.0.2511.1-sources.jar",
          "url": "legacy-fabric-1.20.1-1.8.0.2511.1-sources.jar",
          "size": 17393488,
          "sha512": "559fd8fd1204f4838341e0003e51660d7f35179e8e85665734edb8b48d5959d2731a84f1a1adb189c9010ebc23d871bb03572cfa4e4c7f8c8719b8a7361aaf60",
          "sha256": "b9724e66abef2d77f78557aef42b237ffe9fdaaa7188b9458012a57a64a4e63b",
          "sha1": "56bc86b43de96c196dfc542a3a4c815072b27fc1",
          "md5": "b935a376bd753dee38a94639d1d24ebd"
        }
      ]
    }
  ]
}
