{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.20.4-2.2.3.2513.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2513.1.jar",
          "size": 682341,
          "sha512": "f66f06757ff9347b7dfc698c350e9dca75597e9cad89d70d7287540b258ff48d4b9994369e05af95b1fca063243019c8c89e904b847dc4d0e2a913bb2e3a663f",
          "sha256": "b52064bfc8c1b63f148c4ac23f64e1cc2b6b9b5340b0bb6d4a254c1ad7e66cee",
          "sha1": "dff51143cd342f49dd5ae6e57ad9f3b9b7bb23da",
          "md5": "a08dea077d997490380c64e1ecfaf2a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2513.1.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2513.1.jar",
          "size": 682341,
          "sha512": "f66f06757ff9347b7dfc698c350e9dca75597e9cad89d70d7287540b258ff48d4b9994369e05af95b1fca063243019c8c89e904b847dc4d0e2a913bb2e3a663f",
          "sha256": "b52064bfc8c1b63f148c4ac23f64e1cc2b6b9b5340b0bb6d4a254c1ad7e66cee",
          "sha1": "dff51143cd342f49dd5ae6e57ad9f3b9b7bb23da",
          "md5": "a08dea077d997490380c64e1ecfaf2a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.20.4-2.2.3.2513.1-sources.jar",
          "url": "factory_api-forge-1.20.4-2.2.3.2513.1-sources.jar",
          "size": 252633,
          "sha512": "cdfede35e9cc749662fb96afeac5c9d2f338d6aff285b68d491ee2b0c1749fb57747a904d67243486d6d03503e200d1e5e26d456d1bf64203eba3bf4baec4a11",
          "sha256": "dd21b486116b8b780ff7fb55cd9403c6a5292343ec7d5684957d4f80817f7f0b",
          "sha1": "d5478a345353fa6dda21ed522b54b68c66830184",
          "md5": "079fe17ba0371736af241f5d03efe1f2"
        }
      ]
    }
  ]
}
