{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-neoforge",
    "version": "1.21.4-1.7.10.2501.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2501.22"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2501.2.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2501.2.jar",
          "size": 11935337,
          "sha512": "8b7328e8ad7f297ebec22916848227591208d280b702ea28d62c819caafa9fe5ab7d775ca5591f7eee4aa998c6205dd395fe0eb95b731979ea1fbb4afc56fb67",
          "sha256": "dbc031de53626eb818243a1d1836685e970de6398485b95bc23efe0a2eaba5f5",
          "sha1": "bf70d2e34d5298a6137efaddb34809f65f33a3aa",
          "md5": "3064b21859b843b12de41089e045c110"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-neoforge",
          "version": {
            "requires": "1.21.4-2.2.2501.22"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2501.2.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2501.2.jar",
          "size": 11935337,
          "sha512": "8b7328e8ad7f297ebec22916848227591208d280b702ea28d62c819caafa9fe5ab7d775ca5591f7eee4aa998c6205dd395fe0eb95b731979ea1fbb4afc56fb67",
          "sha256": "dbc031de53626eb818243a1d1836685e970de6398485b95bc23efe0a2eaba5f5",
          "sha1": "bf70d2e34d5298a6137efaddb34809f65f33a3aa",
          "md5": "3064b21859b843b12de41089e045c110"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-neoforge-1.21.4-1.7.10.2501.2-sources.jar",
          "url": "legacy-neoforge-1.21.4-1.7.10.2501.2-sources.jar",
          "size": 11133411,
          "sha512": "05dd9a153f4375f4ae19f031ec5af06d25bbd95f8bfd1200456e0a445ce05582cf01ff5b9cae48e75cef501a60e12a5738fc88780590c51bb3edd192bb48099f",
          "sha256": "f20bb4fbf075b61995fbaeca7c68fa3118c684ae8088c65024f8d92561725adb",
          "sha1": "298be7d4499c0c742f78bbcd7ae3b7408abdc697",
          "md5": "dd0c3f501f8f8adc3d6825a86ead2b6e"
        }
      ]
    }
  ]
}
