{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.5.2527.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.5.2527.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.5.2527.0.jar",
          "size": 512597,
          "sha512": "f106a8d40619236ef64adc255ad9ac710883126bf9a95617e4fe3f03f980f914d5e4548c4e70d601c7f617a05cafd1b66ecf6559490e999b9852c2b90bda3b6e",
          "sha256": "0323816c2d81c3ef6e5d032c7540e9731a985baf3a0baa7f044311e6f9624b27",
          "sha1": "ea2d0836896cc16ca06eaffa1473d2b9b9456898",
          "md5": "d592b30fdb23c52538dc888c8bfb6562"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.5.2527.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.5.2527.0.jar",
          "size": 512597,
          "sha512": "f106a8d40619236ef64adc255ad9ac710883126bf9a95617e4fe3f03f980f914d5e4548c4e70d601c7f617a05cafd1b66ecf6559490e999b9852c2b90bda3b6e",
          "sha256": "0323816c2d81c3ef6e5d032c7540e9731a985baf3a0baa7f044311e6f9624b27",
          "sha1": "ea2d0836896cc16ca06eaffa1473d2b9b9456898",
          "md5": "d592b30fdb23c52538dc888c8bfb6562"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.5.2527.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.5.2527.0-sources.jar",
          "size": 258546,
          "sha512": "112b0d7305ab02bd6ac7f65aefa9d6f342d43350986182cc0435a3a1b271e2ebe93fb5d7af92402a5a0ad586cc73a77e236c9f03487d06ca72d8a748f3ba32e6",
          "sha256": "5c1e8dcbce427ccee5bfae75d6cbfdedbd381e63252adeb4f12e71531942214f",
          "sha1": "23987c559d136a4c17e5e0a311885237c82b437d",
          "md5": "818d6fdf2d46c8b5ef4b3b9dd6cf10ee"
        }
      ]
    }
  ]
}
