{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.3.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.1.jar",
          "size": 521798,
          "sha512": "e0c0454078ac58a8c3775bfd9ccecfdf5ec368e45c872cd011c612062cfcc5c60d9e89a68da4a6af8ef43c3fcca8f7663b07d3530822f32403d38079de38acb9",
          "sha256": "00208d3b6af12b9e2b7fc8f1417ff805377b455d0b00a73fc36dbd1d5ec6a213",
          "sha1": "57f66c85243e3088c4714fe3332c44315853b36e",
          "md5": "099b3b11e26596fdff752daff6d3025e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.1.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.1.jar",
          "size": 521798,
          "sha512": "e0c0454078ac58a8c3775bfd9ccecfdf5ec368e45c872cd011c612062cfcc5c60d9e89a68da4a6af8ef43c3fcca8f7663b07d3530822f32403d38079de38acb9",
          "sha256": "00208d3b6af12b9e2b7fc8f1417ff805377b455d0b00a73fc36dbd1d5ec6a213",
          "sha1": "57f66c85243e3088c4714fe3332c44315853b36e",
          "md5": "099b3b11e26596fdff752daff6d3025e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.3.2514.1-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.3.2514.1-sources.jar",
          "size": 252377,
          "sha512": "cea37e3354e72466d494eea9f5e813c46e6046651c3701c97b7cadc34f437e4e27ffb9f42b7b8876d64caef8dba625cb8ef378e529067abff36fdcccdea4ea7a",
          "sha256": "4e7b7419a331cda454fd5aa9d60b670eedc95c4a350bd208fea2952ebe2d0af8",
          "sha1": "a1bb4dc9c102e3643e2665437f95203de9022215",
          "md5": "50a7882cef582941e6eb18533f9ba70d"
        }
      ]
    }
  ]
}
