{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2509.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2509.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2509.0.jar",
          "size": 492545,
          "sha512": "9fbc4297321f83c279bddfe0a074759eb9080abc5bb4573e4cf48879ee05d8c44679311b763d060fd57385efe66b6e5120f4c173b7b22bf936858342729de791",
          "sha256": "3445341b6b359ca840488abec001bf9469c6cc3d0f55e7e507edb6a3918fe15f",
          "sha1": "f88ae46ccc761980fc596dacef6c73c4bd39b60d",
          "md5": "c6fc92cf6a4cad76515079a6a206eb56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2509.0.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2509.0.jar",
          "size": 492545,
          "sha512": "9fbc4297321f83c279bddfe0a074759eb9080abc5bb4573e4cf48879ee05d8c44679311b763d060fd57385efe66b6e5120f4c173b7b22bf936858342729de791",
          "sha256": "3445341b6b359ca840488abec001bf9469c6cc3d0f55e7e507edb6a3918fe15f",
          "sha1": "f88ae46ccc761980fc596dacef6c73c4bd39b60d",
          "md5": "c6fc92cf6a4cad76515079a6a206eb56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2509.0-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2509.0-sources.jar",
          "size": 248331,
          "sha512": "ded56b459e14af7600ec8f1eb77232b2b747d3d54960189fca816e688f1faeb7b0f682cc7da79fc5a2d3b2d0143ab458710ddfc9476460c5a0945b6f7d2e41b5",
          "sha256": "efc3c31b520b9299644661712e530f3c653348469628fbfb3ef5dfd70c99a0de",
          "sha1": "71aee75d7df7db59a660384760eec610bf4a58fb",
          "md5": "e649f665a9ffc8046e25cc7344dccd77"
        }
      ]
    }
  ]
}
