{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.20.1-1.8.0.2514.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2514.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2514.1.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2514.1.jar",
          "size": 18275587,
          "sha512": "b0c514ab1dd8526dfe9f8026e9964eb855c64367f7e54393161f2057a32b03ceafb57764d4a0ebcb4cb2fa16f9542b8f87b8f6f9346746e921a5c06924b95bdb",
          "sha256": "f2cd64180e1e48ee4367a60f55b858b1177665f724ec4024ed858895c95ad00c",
          "sha1": "d942b962304a99a4d7976144babd481946784cdf",
          "md5": "cc9587e38eda56a09fc87a21f77fba8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.20.1-2.2.3.2514.2"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2514.1.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2514.1.jar",
          "size": 18275587,
          "sha512": "b0c514ab1dd8526dfe9f8026e9964eb855c64367f7e54393161f2057a32b03ceafb57764d4a0ebcb4cb2fa16f9542b8f87b8f6f9346746e921a5c06924b95bdb",
          "sha256": "f2cd64180e1e48ee4367a60f55b858b1177665f724ec4024ed858895c95ad00c",
          "sha1": "d942b962304a99a4d7976144babd481946784cdf",
          "md5": "cc9587e38eda56a09fc87a21f77fba8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.20.1-1.8.0.2514.1-sources.jar",
          "url": "legacy-forge-1.20.1-1.8.0.2514.1-sources.jar",
          "size": 17438716,
          "sha512": "7e179ad876fed1249e82eba9150bdb93ffab19879b881933309e54b549a257b306607609846c253c3620f38862f75023f40efdb9e22894db6045399397845c92",
          "sha256": "74316cc76fa868ca1202b683866501d1fea2b00248215023e34b8c11ea5130e3",
          "sha1": "5194c12b68aa08146185321edef73f7291441923",
          "md5": "a905e11b162030181fdb0171041ebadf"
        }
      ]
    }
  ]
}
