{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.4-2.2.2500.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.7.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.7.jar",
          "size": 367227,
          "sha512": "92731647827344e2e81246de5a8d3b53afefb924896fe195f1fabe0c261eee659dded6e17a1d311e90f7e1fc952f0e60e97da36140e849257ef902b3b2f1b001",
          "sha256": "3c6b7610b13dc65ef7578e52146d31ac0e2800e3c5437eb9670f4f82550a2c93",
          "sha1": "cbc5c2c567eed1548b10a1ca44140d0b72fada91",
          "md5": "bbd81dedfaf82375825f1169bb115e96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.7.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.7.jar",
          "size": 367227,
          "sha512": "92731647827344e2e81246de5a8d3b53afefb924896fe195f1fabe0c261eee659dded6e17a1d311e90f7e1fc952f0e60e97da36140e849257ef902b3b2f1b001",
          "sha256": "3c6b7610b13dc65ef7578e52146d31ac0e2800e3c5437eb9670f4f82550a2c93",
          "sha1": "cbc5c2c567eed1548b10a1ca44140d0b72fada91",
          "md5": "bbd81dedfaf82375825f1169bb115e96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.4-2.2.2500.7-sources.jar",
          "url": "factory_api-forge-1.21.4-2.2.2500.7-sources.jar",
          "size": 193513,
          "sha512": "a42d653498e69748e2af02e7d4a912d43c2af8e1bf8e2b82aec5c7a6827895cc774936043fcc34d494bda90bac9d386aebb81cc34f5a04671dea60b4b78e1e7c",
          "sha256": "f7828b93c749024ae6a157452a579aa0602ff7ceb9b31314e73e08afda38b5e6",
          "sha1": "69f8813c33b1d7e96f51fb2df3fc6fc62a0901ea",
          "md5": "f79516314931a0d7789b3c323b7fa183"
        }
      ]
    }
  ]
}
