{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.legacy",
    "module": "legacy-forge",
    "version": "1.21.4-1.7.10.2504.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.6.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.6.jar",
          "size": 14326539,
          "sha512": "5904089624b8d2d9595cad263d9e6cf61b8399eade31778d133b10ca578b1c49b461f2c923299192aa4a46be3cafdc22d8aca69f99046f8c1cc70635fdaafc18",
          "sha256": "1a85df1de3515405e52cb37f39011ef63efc05703d5c08f1525b637eaea72d4b",
          "sha1": "48b98af54c701fae31080b3c7e96bd4cf190d66d",
          "md5": "cb26eaebe2ff7fd75eefd76d5aab2c91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.isxander",
          "module": "libsdl4j",
          "version": {
            "requires": "3.preview-3.1.3-46"
          }
        },
        {
          "group": "wily.factory_api",
          "module": "factory_api-forge",
          "version": {
            "requires": "1.21.4-2.2.2504.5"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.6.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.6.jar",
          "size": 14326539,
          "sha512": "5904089624b8d2d9595cad263d9e6cf61b8399eade31778d133b10ca578b1c49b461f2c923299192aa4a46be3cafdc22d8aca69f99046f8c1cc70635fdaafc18",
          "sha256": "1a85df1de3515405e52cb37f39011ef63efc05703d5c08f1525b637eaea72d4b",
          "sha1": "48b98af54c701fae31080b3c7e96bd4cf190d66d",
          "md5": "cb26eaebe2ff7fd75eefd76d5aab2c91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-forge-1.21.4-1.7.10.2504.6-sources.jar",
          "url": "legacy-forge-1.21.4-1.7.10.2504.6-sources.jar",
          "size": 13514659,
          "sha512": "33a693d4062e0b933ad5d28089212f010f7cd4fa9bac4cb327680bae5f05762d21d9c173884d474cdd982f299fa20060a694f705bccb2e934ce135dbd94211ba",
          "sha256": "42750dfdd3945557bea98986b9daca1807c2b18a12ef0aa60ad5f7b41273411c",
          "sha1": "dd0ca5044bfbbf8faf607b7268d2904d7dbc3690",
          "md5": "d6e2c8fd8447de17cc3ccb9aa0ed4c6f"
        }
      ]
    }
  ]
}
