{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.9.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.9.jar",
          "size": 371983,
          "sha512": "2f43ec86c5c3207ba0213c0902cc47a109624eb1777d962fe18f5abb03a619870c798938caaaa59fa4f00fb59d89273141128cf0604f38c45ce0adf8e2bc9494",
          "sha256": "a9e21b7a71e61364efaae98f54ba3aa9d47fcddec1df278c4b7724be3b45a5bc",
          "sha1": "9b741d03b625d6adf01db2030d998f88c8ad8df0",
          "md5": "2f110e9f59262762c5f2a0d8ce56d6a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.9.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.9.jar",
          "size": 371983,
          "sha512": "2f43ec86c5c3207ba0213c0902cc47a109624eb1777d962fe18f5abb03a619870c798938caaaa59fa4f00fb59d89273141128cf0604f38c45ce0adf8e2bc9494",
          "sha256": "a9e21b7a71e61364efaae98f54ba3aa9d47fcddec1df278c4b7724be3b45a5bc",
          "sha1": "9b741d03b625d6adf01db2030d998f88c8ad8df0",
          "md5": "2f110e9f59262762c5f2a0d8ce56d6a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.9-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.9-sources.jar",
          "size": 196832,
          "sha512": "e6007eeed0cc5f2878462342d102b936a7022c50aee4e8efe8a2a5d6835d14276fd8312f6c95edf4b7391142d215f91a2f9229394335008ae8e664a49e781ead",
          "sha256": "30e74429f5002950c4875e028da82c96b92d8dcface886662ea512b97e6e5931",
          "sha1": "56f1b21576b18ac48be25c5a319b9a91cc4ab43f",
          "md5": "23bb362853565d8e91f5c6cacf4c057f"
        }
      ]
    }
  ]
}
