{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.jar",
          "size": 523460,
          "sha512": "f6bfe8fe6e70c4631bcfd34e41c3776b5972393143a050ccaa4619d044390a1a96b8c8df9b1473bd6616080aa100ddcf49d0d0b6d8c9078ea33e2ef1f7a496a0",
          "sha256": "9fdc6fdc1540ab980fd96f93898b2879c8a4d22d042f1fa1e7cf2855a8e720a0",
          "sha1": "feb292665c24c2e00b74dbdd6b83b737bde4042a",
          "md5": "9bd5e3e69ee7bebae3bc66557a3ef455"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7.jar",
          "size": 523460,
          "sha512": "f6bfe8fe6e70c4631bcfd34e41c3776b5972393143a050ccaa4619d044390a1a96b8c8df9b1473bd6616080aa100ddcf49d0d0b6d8c9078ea33e2ef1f7a496a0",
          "sha256": "9fdc6fdc1540ab980fd96f93898b2879c8a4d22d042f1fa1e7cf2855a8e720a0",
          "sha1": "feb292665c24c2e00b74dbdd6b83b737bde4042a",
          "md5": "9bd5e3e69ee7bebae3bc66557a3ef455"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.7-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.7-sources.jar",
          "size": 269193,
          "sha512": "a27beefbddadb77fe2f15e502cda71fd3f4298d95c429ac3e7a495916772db3602dad67681c9bbef6183fb9babd4972aa94315fad4bbfe51242ace3f1faa3876",
          "sha256": "998a16748107556d55a9570b9da0a17f75bc235f1f32189f8c7fd3b94aacc82e",
          "sha1": "d446c3d99a373d9fcd6716236cdd51aa6da28eb3",
          "md5": "f15422c35ba5e9c2988fae6d539d577a"
        }
      ]
    }
  ]
}
