{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.2501.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.3.jar",
          "size": 352297,
          "sha512": "5d833dbd5bbe81ad88852340c2a9f1e179621767c4717021d75cf9780a81bd77fafdc68b6690710b23d8695f8024c6a245bdca71950fc2a0feddc5565fa88fe2",
          "sha256": "d31d99e8bac83e27ef9ac38d066038f6bb2057feb7d5e32b492c2f034f98c48b",
          "sha1": "b31b06b5b5de1ed7c0ae21b4b7d9613ee8209043",
          "md5": "5c0b3a7ed67b6b5d9a1eaa17da2ed93f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.3.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.3.jar",
          "size": 352297,
          "sha512": "5d833dbd5bbe81ad88852340c2a9f1e179621767c4717021d75cf9780a81bd77fafdc68b6690710b23d8695f8024c6a245bdca71950fc2a0feddc5565fa88fe2",
          "sha256": "d31d99e8bac83e27ef9ac38d066038f6bb2057feb7d5e32b492c2f034f98c48b",
          "sha1": "b31b06b5b5de1ed7c0ae21b4b7d9613ee8209043",
          "md5": "5c0b3a7ed67b6b5d9a1eaa17da2ed93f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.2501.3-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.2501.3-sources.jar",
          "size": 194982,
          "sha512": "0f1550b60e639118e19e0aabaf79f2c615bd57ddddeae4f62754b94b751dfcded17f4c110ceebdf0915cc9c9896f0b42d7cf09e84768c206b495523e3b7b287b",
          "sha256": "7869f019716232fb191f8b4bcb323744fbd32ca5882de37022bd0dbff0ef96f3",
          "sha1": "6048eda8067f0748b49d530b6d67a76dc3db7a7e",
          "md5": "fc4805fbaf2860789858f6550c42b2f8"
        }
      ]
    }
  ]
}
