{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.1-2.2.3.2510.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.7.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.7.jar",
          "size": 498461,
          "sha512": "acc406a3a2ae0c8d5260dcc8eda573e7ca0a1d3c673cecc3840e52cec092c457248ef72c544d4b2d74fdc963e888b323838f6d71f4a4a14b6ec7e4dcf46356a8",
          "sha256": "39924b50218c44af7c7793b46574ce610d0bdff87fd6cf8938a0a011211d62bd",
          "sha1": "25f72d94f7e7ef090bddf65931ba410d95732a2a",
          "md5": "42ba27f0e46ce7e470d9ac1c8aab4f90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.7.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.7.jar",
          "size": 498461,
          "sha512": "acc406a3a2ae0c8d5260dcc8eda573e7ca0a1d3c673cecc3840e52cec092c457248ef72c544d4b2d74fdc963e888b323838f6d71f4a4a14b6ec7e4dcf46356a8",
          "sha256": "39924b50218c44af7c7793b46574ce610d0bdff87fd6cf8938a0a011211d62bd",
          "sha1": "25f72d94f7e7ef090bddf65931ba410d95732a2a",
          "md5": "42ba27f0e46ce7e470d9ac1c8aab4f90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.1-2.2.3.2510.7-sources.jar",
          "url": "factory_api-neoforge-1.21.1-2.2.3.2510.7-sources.jar",
          "size": 250519,
          "sha512": "e9444acbf28b6ed34522aadd9671eb6a58eb89ec2234e6e13fd46af30eb6936eec97abd89ba37bca206623a66af48e0dc21df24807177595fc2637c7ee3dbdc0",
          "sha256": "2c5fe21b163bca1c4b29bd12bff7a5915bf3bbc07ac6408e12ffda6085bd44a6",
          "sha1": "31b2f34d62f994d4426f009337142ef61641aa87",
          "md5": "cbd5fddb3cfefae5ea3da791043edc9f"
        }
      ]
    }
  ]
}
