{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.20.4-2.2.3.2510.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.4.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.4.jar",
          "size": 495601,
          "sha512": "028527e81189add4dd50ae007100a0a8ddc5174fcdf71fe68bb418a09805e686b32689bf2325456977774232d76ebe0d4b926e1022a3942fb14f7ec5c4a496f1",
          "sha256": "b8791a82505a0f3532878c3a5b2ed118a03f423e4f984dd7e3de2788441304aa",
          "sha1": "04f6d3f37b9f824a47e83851391f5dfd99dea202",
          "md5": "c83b253025c6756ecc04c7fc69b370ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.4.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.4.jar",
          "size": 495601,
          "sha512": "028527e81189add4dd50ae007100a0a8ddc5174fcdf71fe68bb418a09805e686b32689bf2325456977774232d76ebe0d4b926e1022a3942fb14f7ec5c4a496f1",
          "sha256": "b8791a82505a0f3532878c3a5b2ed118a03f423e4f984dd7e3de2788441304aa",
          "sha1": "04f6d3f37b9f824a47e83851391f5dfd99dea202",
          "md5": "c83b253025c6756ecc04c7fc69b370ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.20.4-2.2.3.2510.4-sources.jar",
          "url": "factory_api-neoforge-1.20.4-2.2.3.2510.4-sources.jar",
          "size": 250698,
          "sha512": "e09bb3d92d97b940716a82c4e90f28c79895882abdf31abea034974a1be3df78977f8b1a0ecc2fb06b2e9b61090e4f0b8a273bf7a48bbc89dc4bf12955230731",
          "sha256": "db017a8f6bb8428b8a3a4d27727565108d364d3dd141d09affe0d3b0a3a86ac8",
          "sha1": "bc55d9878b7caf2b93294d64dfe1cdf39407c543",
          "md5": "8de453e08e7364b877c8653adddf59cb"
        }
      ]
    }
  ]
}
