{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.4-2.2.2501.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.24.jar",
          "size": 391307,
          "sha512": "eaae8335bfc2c483691c348e214b92b940df97ca6f3327a0deaed60783acbd51854707ca04c34d264e516f9ed861dd4a01a1d543ff5795e5d4cb2648d3e8310a",
          "sha256": "ff726a07da970da3c04bf9e17ae92db014bd1db0cab75820e370935d033e2d35",
          "sha1": "108a73e6e5ed75e5ad48bb92cecd9c79d24caae0",
          "md5": "668d0ba4528340ca167d94c181fc585d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.24.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.24.jar",
          "size": 391307,
          "sha512": "eaae8335bfc2c483691c348e214b92b940df97ca6f3327a0deaed60783acbd51854707ca04c34d264e516f9ed861dd4a01a1d543ff5795e5d4cb2648d3e8310a",
          "sha256": "ff726a07da970da3c04bf9e17ae92db014bd1db0cab75820e370935d033e2d35",
          "sha1": "108a73e6e5ed75e5ad48bb92cecd9c79d24caae0",
          "md5": "668d0ba4528340ca167d94c181fc585d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.4-2.2.2501.24-sources.jar",
          "url": "factory_api-neoforge-1.21.4-2.2.2501.24-sources.jar",
          "size": 197728,
          "sha512": "71e32559ebfdbc1c9012753cb944784932154d9eff70554961feaa328cb5e3096cb2cf0a01ab683c2ca3e1142fab02360d8d8a8925d9aaa0f189fa606662cb25",
          "sha256": "9061c3a8abc88d8d58fee89608edb3a1d8bb237af3d416244e098cfacc5ce868",
          "sha1": "90260853d673639313e297812b10344aa170e872",
          "md5": "09bca02198903cc24df4d7732e7b4a6a"
        }
      ]
    }
  ]
}
