{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.3-2.2.2502.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.4.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.4.jar",
          "size": 439340,
          "sha512": "9d2cc88d336c7fbffec439368693baad78f23d3997a72d819606a5ae75555545c479246ab3e002f39a171100ddd954faadd3b0f85c1b303e9e2275344a1fa11f",
          "sha256": "2a97cf60138571ef04b418e8e412e16130da9b0a8e0e8d11f0ae7e04a7e1b1c3",
          "sha1": "8c8ae445e27c9bdc3628dd6024815d4787d6a97e",
          "md5": "0d36d2660092e68be6cb2d136d1bf55c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.4.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.4.jar",
          "size": 439340,
          "sha512": "9d2cc88d336c7fbffec439368693baad78f23d3997a72d819606a5ae75555545c479246ab3e002f39a171100ddd954faadd3b0f85c1b303e9e2275344a1fa11f",
          "sha256": "2a97cf60138571ef04b418e8e412e16130da9b0a8e0e8d11f0ae7e04a7e1b1c3",
          "sha1": "8c8ae445e27c9bdc3628dd6024815d4787d6a97e",
          "md5": "0d36d2660092e68be6cb2d136d1bf55c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.3-2.2.2502.4-sources.jar",
          "url": "factory_api-neoforge-1.21.3-2.2.2502.4-sources.jar",
          "size": 221725,
          "sha512": "15355f3e3cfa6c4f5a776ee45a49c066595daabde3e74e0cfb0c20dd09e40ee69a1c750334160fe907c818214b79733002d18ea002c68f7ecef147a93702c9bd",
          "sha256": "18d1dadcb293851ee4e3fd855bcee2cf3a441b41f8a90f2778176bb91cc1918f",
          "sha1": "61b11eda42ce36b7d2b0716db5d932d0d196e7de",
          "md5": "fb25def8e7888f0ad446060ac2badbfb"
        }
      ]
    }
  ]
}
