{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-neoforge",
    "version": "1.21.8-2.2.7.2616.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2616.1.jar",
          "size": 555514,
          "sha512": "852b56fd413c7ea5539e1c137498f60e60b9b675d96a60ab7152dd49c1a90f2fb6ba84dd6e24f8225003b2e8117c8b95b87531449169afa53ff6beac851c52c1",
          "sha256": "5881e32e868ef962a3ff8faa230ae6c78bc19d4d890e967f86fe8427bbdc5118",
          "sha1": "7d5c089b6c50f25a68cc458b01c87172ec9d85dd",
          "md5": "9b5a9c447f125352e609c34b94e1469e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2616.1.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2616.1.jar",
          "size": 555514,
          "sha512": "852b56fd413c7ea5539e1c137498f60e60b9b675d96a60ab7152dd49c1a90f2fb6ba84dd6e24f8225003b2e8117c8b95b87531449169afa53ff6beac851c52c1",
          "sha256": "5881e32e868ef962a3ff8faa230ae6c78bc19d4d890e967f86fe8427bbdc5118",
          "sha1": "7d5c089b6c50f25a68cc458b01c87172ec9d85dd",
          "md5": "9b5a9c447f125352e609c34b94e1469e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2616.1-sources.jar",
          "size": 256776,
          "sha512": "9383c6248240f43540c3a96002559a3d921a81eca5efd11748bebd377dcefde618636965ea5b5e733eb03a08567aab63f13d3e047df2c06a88abdd244300232e",
          "sha256": "c23f7b420af8c5423210c811fe5e2b60f4bad67d11da0209a91c165bbd8a7004",
          "sha1": "4b9b6442a4b83e6825861fda3bd2030ad8b5bcd4",
          "md5": "df54ea8bcb7296bbc46b14cfac675b63"
        },
        {
          "name": "factory_api-neoforge-1.21.8-2.2.7.2616.1-sources.jar",
          "url": "factory_api-neoforge-1.21.8-2.2.7.2616.1-sources.jar",
          "size": 256776,
          "sha512": "9383c6248240f43540c3a96002559a3d921a81eca5efd11748bebd377dcefde618636965ea5b5e733eb03a08567aab63f13d3e047df2c06a88abdd244300232e",
          "sha256": "c23f7b420af8c5423210c811fe5e2b60f4bad67d11da0209a91c165bbd8a7004",
          "sha1": "4b9b6442a4b83e6825861fda3bd2030ad8b5bcd4",
          "md5": "df54ea8bcb7296bbc46b14cfac675b63"
        }
      ]
    }
  ]
}
