{
  "formatVersion": "1.1",
  "component": {
    "group": "wily.factory_api",
    "module": "factory_api-forge",
    "version": "1.21.3-2.2.2501.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.17.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.17.jar",
          "size": 378795,
          "sha512": "69274fe3e634fd77e962a53626063dc318351122f9ab70b5525d06c5abf179aca4211c1a17dbee51b4cde721afb0b310476458bffee019b7379f49ed5c7e3ba2",
          "sha256": "c1f14f25e801f85153a0e9b046ff9a107c6103cb00dbcc8d27876a1a85ff710e",
          "sha1": "1861a1ca88532aa97c66ed83bd2b952d05f80064",
          "md5": "6f3334426666df2f91355783667287bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.17.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.17.jar",
          "size": 378795,
          "sha512": "69274fe3e634fd77e962a53626063dc318351122f9ab70b5525d06c5abf179aca4211c1a17dbee51b4cde721afb0b310476458bffee019b7379f49ed5c7e3ba2",
          "sha256": "c1f14f25e801f85153a0e9b046ff9a107c6103cb00dbcc8d27876a1a85ff710e",
          "sha1": "1861a1ca88532aa97c66ed83bd2b952d05f80064",
          "md5": "6f3334426666df2f91355783667287bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "factory_api-forge-1.21.3-2.2.2501.17-sources.jar",
          "url": "factory_api-forge-1.21.3-2.2.2501.17-sources.jar",
          "size": 198887,
          "sha512": "03d0f3243f4f7c3d9db5ca7e633ad4e0a7f5318ef91585c52c3c15a3f2e38f08cc0b832df1059af8b4c22cf49ced02f635627f1863e250042ef5bb9f3c8e9f7e",
          "sha256": "f4a6637a95014c5bd2ad042b7e9580062d05ab430e4d7b17bb7a2da30505772b",
          "sha1": "d5dcbd01a3a91663840d2188fabc99c98a67fb92",
          "md5": "8789b40b765da0e7ea356ae19a45c330"
        }
      ]
    }
  ]
}
